ministryofjustice/modernisation-platform

.github/workflows/format-code.yml
This fixes an issue from the template-repository to point the code-formatter action from `master` to `main`.
=> Change GitHub action from pointing to master, to pointing to main

.gitignore, terraform/README.md, terraform/global-resources/README.md, terraform/global-resources/locals.tf, terraform/global-resources/main.tf, terraform/global-resources/s3.tf, terraform/global-resources/versions.tf
This PR:
- Defines some local variables for tagging
- Defines an S3 bucket to use for a Terraform backend
- Defines the Terraform backend
This allows remote state sharing in Terraform to ensure that local references are up-to-date and that `terraform apply` doesn't create a conflicting state set if run at the same time by different people.
=> Configure Terraform S3 backend

terraform/global-resources/iam.tf
This PR:
- Moves to using the superadmin Terraform module to allow superadmin access to accounts
- Devolves password policy management to the Terraform module
This allows us to reuse the superadmin and password management policy across accounts.
=> Use superadmin Terraform module

terraform/global-resources/versions.tf
This PR:
- Specifies the AWS provider source
This is because of a change in how [Terraform 0.13 handles provider sources](https://www.terraform.io/upgrade-guides/0-13.html#explicit-provider-source-locations). It introduces a namespace to specify community-maintained providers as a dependency and although it is only required for community-maintained modules, it's best to be explicit, and allows us to view all provider dependencies in one place as the Modernisation Platform grows.
=> Specify AWS provider source

terraform/global-resources/main.tf, terraform/global-resources/s3.tf
This PR:
- Encrypts the `terraform.tfstate` file stored in S3
- Encrypts new S3 objects in the bucket
- Explicitly blocks public access to the S3 bucket
This is to ensure our S3 bucket is as secure as possible.
=> Add a public access block and enable S3 encryption

.github/workflows/check-environment-definitions.yml, README.md, environments/non-production/shared-services.json, scripts/check-environment-definitions.js, scripts/utilities.js
This PR:
- Adds some sample data to this repository
- Adds a script that will warn about missing key value pairs that are needed to create an OU and account for an application to sit on the Modernisation Platform, and will throw an error if required tags from the MoJ Technical Guidance are missing
- Creates a GitHub workflow to run the script on new PRs, and comment the outcome
It is a clean PR that has been extrapolated from ministryofjustice/modernisation-platform#24, though the optional tag message has been removed as this script checks every file, not just changed ones, so it would have commented on every successive PR about optional tags. ministryofjustice/modernisation-platform#24 was extrapolated from ministryofjustice/modernisation-platform-terraform-environments#1.
=> Add environment tag checking with a sample environment

scripts/utilities.js
This PR:
- Fixes the check-environment-tags.yml workflow to only check `.json` files
=> Fix workflow to only check JSON files

terraform/global-resources/environments.tf, terraform/global-resources/main.tf, terraform/global-resources/secrets.tf
This PR:
- Includes [ministryofjustice/modernisation-platform-terraform-environments](https://github.com/ministryofjustice/modernisation-platform-terraform-environments) for environment management
- Configures a new provider for environment management
- Retrieves secrets for environment management from AWS Secrets Manager
This PR resolves #11, and requires ministryofjustice/aws-root-account#6.
=> Use `modernisation-platform-terraform-environments` for environment management

.gitignore, terraform/environments/README.md, terraform/environments/environments.tf, terraform/environments/iam.tf, terraform/environments/locals.tf, terraform/environments/main.tf, terraform/environments/providers.tf, terraform/environments/providers.tmpl, terraform/environments/secrets.tf
This PR:
- changes how Organisational Units and accounts are created; from the Modernisation Platform assuming a role, to running this directly in the MOJ root account
- creates dynamically generated providers for new OUs and accounts
- creates an assumable role in new accounts for the Modernisation Platform to assume directly rather than through the MOJ root account
=> Bootstrap new AWS accounts with assumable roles

README.md
The IAM Federated Access module is now repurposed as the AWS SSO base configuration for the root account, which we can utilise for Federated Access instead of setting up our own IAM Federated Access configuration.
=> Remove link to IAM Federated Access module

environments/shared-services.json, scripts/check-environment-definitions.js, terraform/environments/environments.tf
This PR removes a split between non-production and production organization units, and instead has OUs on an application-by-application basis. It also removes checking for the `is-production` tag as this is now inferred.
It requires ministryofjustice/modernisation-platform-terraform-environments#4.
=> Simplify OU and account creation

terraform/global-resources/baselines.tf
I've moved PR #33, #34, #35 to a separate [Terraform module](https://github.com/ministryofjustice/modernisation-platform-terraform-baselines) and this enables that.
=> Enable baselines module

terraform/global-resources/iam.tf
This PR pins the Auth0 module to the working hash whilst we move toward AWS SSO.
=> Pin IAM to a hash due to change to AWS SSO

terraform/global-resources/defaults.tf, terraform/global-resources/s3.tf
This resolves the VPC configuration being non-compliant in AWS Config due to not having tags, and tightens up public restrictions on the Terraform state S3 bucket.
=> AWS Config remediation: tag default VPC and update S3 bucket permissions

terraform/global-resources/s3.tf
This resolves an AWS Config non-compliancy on S3 buckets requiring SSL.
=> Require SSL for the modernisation-platform-terraform-state bucket

terraform/global-resources/defaults.tf
This PR brings the AWS default Network ACL and SecurityGroup into Terraform management, and adds tags to them.
=> AWS Config remediation: add tags to default VPC ACL and SG

terraform/global-resources/providers.tf
This explicitly sets the `aws` default provider to use the Modernisation Platform `eu-west-2` provider, rather than relying on the caller's `AWS_REGION`.
=> Set aws provider to use eu-west-2

terraform/global-resources/route53.tf
Adds a Route53 Hosted Zone for `modernisation-platform.service.justice.gov.uk`.
=> Add Route53 Hosted Zone for modernisation-platform.service.justice.gov.uk

terraform/global-resources/route53.tf
This adds the missing tags to the Route53 Hosted Zone.
=> Add missing tags to Route53 hosted zone

terraform/global-resources/versions.tf
This adds the `local` provider to `versions.tf`, as recommended by Terraform 0.13.
=> Add local provider to versions.tf for Terraform 0.13

terraform/global-resources/providers.tf, terraform/templates/providers.tmpl
This sets the region for S3 buckets to be replicated into as `eu-west-1`.
=> Specify replication_region for S3 buckets

terraform/github/README.md, terraform/github/main.tf, terraform/github/modules/repository/main.tf, terraform/github/modules/repository/outputs.tf, terraform/github/modules/repository/variables.tf, terraform/github/modules/team/main.tf, terraform/github/modules/team/variables.tf, terraform/github/versions.tf
This moves clickops management of GitHub resources into `terraform`.
=> Add GitHub resources

terraform/environments/providers-shared-services-dev.tf, terraform/global-resources/providers.tf, terraform/templates/providers.tmpl
Requires ministryofjustice/modernisation-platform-terraform-baselines#36.
This removes the `replication_region` variable and introduces the `provider.replication-region` declaration.
=> Update baseline variables/providers

terraform/environments/main.tf, terraform/global-resources/main.tf, terraform/global-resources/s3.tf
This PR enforces Terraform states to be uploaded with the `bucket-owner-full-control` and enforces a policy for the root account to only be able to upload objects with the ACL `bucket-owner-full-control`.
=> Force Terraform state ownership to be bucket-owner-full-control

terraform/environments/versions.tf, terraform/github/versions.tf, terraform/global-resources/versions.tf
This specifies that the minimum Terraform version required is `0.13.5` and also specifies to use the following provider versions:
- `aws` to use at least `3.13.0`
- `local` to use at least `2.0.0`
=> Update required Terraform and Terraform providers versions

docs/alliance.md, docs/index.md, docs/team.md
This resolves #71 where we agreed to document our team alliance openly and publicly.
=> Write up our team alliance in our docs

docs/alliance.md, docs/index.md, docs/team.md
GitHub creates headings based on repository names so our pages appear as follows:
This removes "Modernisation Platform" from our headings so it will now show like this:
=> Remove duplicate headings that GitHub creates

terraform/global-resources/providers.tf, terraform/templates/providers.tmpl
This is the first part of #75, which refreshes AWS Trusted Advisor every 60 minutes to get the most up-to-date check results.
=> Add Trusted Advisor refresh Lambda

README.md, terraform/github/main.tf, terraform/github/modules/repository/main.tf, terraform/github/modules/team/main.tf
This updates repository descriptions to match the README descriptions and makes them clearer as to what each repository does.
It also changes the separator from an emdash (`—`) to a typographic bullet (`•`) to make it easier to read.
=> Update repository descriptions to match README

terraform/github/modules/team/main.tf, terraform/github/versions.tf
This pulls in the other GitHub [team members](https://github.com/orgs/ministryofjustice/teams/modernisation-platform) into Terraform management.
=> Add other GitHub team members into Terraform

.github/workflows/check-environment-definitions.yml
This restricts the `check-environment-definitions` workflow from running unless a PR changes something in `environments/**`, which should mean less checks for unrelated PRs.
=> Change check-environment-definitions to only run on PRs that change something in environments/**

terraform/github/main.tf, terraform/github/modules/repository/main.tf, terraform/github/modules/repository/variables.tf
Part of #88.
This allows us to set GitHub repository secrets via Terraform in one place.
Note that when you run `terraform plan` it specifies that the plaintext_value is `(sensitive)`.
=> Allow secrets to be set via Terraform

terraform/github/main.tf
Using the word `public` conveys that we have private repositories, which we don't, so I've switched this out to `core` so it makes more sense.
=> Change public to core

terraform/modernisation-platform-account/locals.tf
Adds a missing aws_caller_identity block that is required by https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/modernisation-platform-account/s3.tf#L8.
=> Add missing aws_caller_identity block

terraform/github/modules/team/main.tf
The CI user needs to be a team maintainer to edit the team members.
=> Make CI users maintainers

architecture-decision-record/0002-use-iam-federated-access.md, architecture-decision-record/0003-use-aws-sso.md, architecture-decision-record/README.md
Resolves #69 
As a team, we discussed advantages and disadvantages for using AWS SSO or IAM Federated Access and we've opted to use AWS SSO, for a centrally managed JML process for access into AWS accounts and shared operational services for the Modernisation Platform.
A further benefit of this is that AWS SSO can be used across _all_ AWS accounts, not just ones provisioned within the Modernisation Platform, as long as the AWS account is part of the AWS organisation.
=> Mark AWS SSO ADR as accepted, and reject AWS IAM Federated Access ADR as rejected

environments/core.json
Resolves an issue where the concat of the application name and environment names can't exceed 36 characters.
=> Rename Modernisation Platform core to core

.github/workflows/create-accounts.yml, scripts/create-accounts.sh
This changes the workflow to only run when a new environment definition is added, and hides the output from the `terraform init` command.
=> Restrict workflow to environments/ path and hide output for terraform init

terraform/github/main.tf
Adds the network-services-cidr-allocation repository to be managed by the Modernisation Platform.
=> Add network-services-cidr-allocation repository

terraform/modernisation-platform-account/dynamodb.tf, terraform/modernisation-platform-account/locals.tf, terraform/modernisation-platform-account/providers.tf, terraform/modernisation-platform-account/route53.tf, terraform/modernisation-platform-account/s3.tf, terraform/modernisation-platform-account/vpc.tf
As we've moved this out of `global_resources`, I thought it'd be good to tidy up the tag key that's used.
=> Changes tag key from global_resources to tags

terraform/environments/bichard7/versions.tf, terraform/environments/bootstrap/versions.tf, terraform/environments/core-logging/versions.tf, terraform/environments/core-network-services/versions.tf, terraform/environments/core-sandbox/versions.tf, terraform/environments/core-security/versions.tf, terraform/environments/core-shared-services/versions.tf, terraform/environments/remote-supervision/versions.tf, terraform/environments/versions.tf, terraform/modernisation-platform-account/versions.tf
This pins the Terraform version to a minimum of 0.13 in preparation for the release of Terraform 0.14.
Labelled as a bug because if you run any of these configurations using Terraform 0.12, you get a sporadic phantom resource change that doesn't actually do anything.
=> Add or update versions.tf files in preparation for Terraform 0.14

environments/bichard7.json, environments/core-logging.json, environments/core-network-services.json, environments/core-sandbox.json, environments/core-security.json, environments/core-shared-services.json, environments/remote-supervision.json, scripts/check-environment-definitions.js, scripts/create-accounts.sh
Removes the name key from environment definitions in favour of using the filename, and updates the `create-accounts.sh` script to use the input_filename provided by `jq`.
This is in preparation for #163.
=> Remove name key in env definitions and update create_accounts to use filename instead

scripts/create-per-account-local-workspaces.sh
Fixes an issue resulting from #165, in preparation for #163.
=> Fix create-per-account-local-workspaces.sh by removing reliance on .name

scripts/internal/loop-through-bootstrap-workspaces-and-plan.sh
This script will `cd` into the `terraform/environments/bootstrap` folder, get a list of workspaces, and run `terraform plan` in all of them synchronously.
Previously you would have had to do this manually for each terraform workspace, whereas this does it for you so you can start running it and leave it until it's finished. It outputs something similar to the below in your shell:
```Running terraform init for prepare_terraform, in the bootstrap directory
Running terraform validate for prepare_terraform, in the bootstrap directory
Switched to workspace "default".
Switched to workspace "bichard7-dev-current".
Running terraform refresh for bichard7-dev-current (this may take a while)
Running terraform plan for bichard7-dev-current (this may take a while)
No changes. Infrastructure is …
```
=> Add a team script for an easier way to see differences between bootstrapped environments

docs/user-guide/creating-environments.md, docs/user-guide/index.md
This increases the heading levels as GitHub pages already creates a standard `<h1>` so we needn't replicate it. It also moves the link "Creating environments" from a heading to a bullet point.
=> Fix headings for the user guide

docs/team-guide/index.md, docs/team-guide/useful-scripts.md
Explains what the `scripts` directory holds and why they're used or not used as part of a CI/CD pipeline.
=> Add docs for useful scripts

terraform/environments/core-network-services/route53.tf
Delegates `rs-production.modernisation-platform.service.justice.gov.uk` and `rs-non-production.modernisation-platform.service.justice.gov.uk` to the Remote Supervision accounts.
There is a limit on how long an initial FQDN can be in ACM, so we've shortened these to under 64 characters until the MP platform works on centralising domain and ACM management.
=> Remote Supervision: NS delegation

environments/justice-on-the-web.json, terraform/environments/bootstrap/.terraform.lock.hcl
Updates the JotW tag which will: kick-off the create-accounts workflow; after we [upgraded to Terraform 0.14.1 for environment creation](https://github.com/ministryofjustice/modernisation-platform/pull/181).
=> Update JotW tag

environments/justice-on-the-web.json
Using brackets within a tag value causes AWS to error as they're invalid.
=> Remove brackets from tags (they're invalid)

.github/workflows/create-accounts.yml, terraform/environments/bootstrap/versions.tf, terraform/environments/versions.tf
Enforces the requirement for Terraform 0.14.2 for bootstrapping accounts and the GitHub actions workflow.
=> Require Terraform 0.14.2 for account bootstrapping

terraform/modernisation-platform-account/.terraform.lock.hcl, terraform/modernisation-platform-account/versions.tf
Updates the Modernisation Platform account to use Terraform 0.14.2.
=> Upgrade the Modernisation Platform landing zone to use Terraform 0.14.2

terraform/github/.terraform.lock.hcl, terraform/github/versions.tf
Requires Terraform 0.14.2 to run the Terraform for GitHub resoures.
=> Upgrade GitHub resources to use Terraform 0.14.2

terraform/modernisation-platform-account/providers.tf
This PR updates the `modernisation-platform-account` Terraform configuration to use the `regional-enablement` branch of the `modernisation-platform-terraform-baselines`.
This is to allow us to test the [organisational Service Control Policy](https://github.com/ministryofjustice/aws-root-account/pull/95) that restricts regional services to EU and us-east-1 only, and removes superfluous regional enablement of things like GuardDuty, etc.
Note that this only affects the Modernisation Platform account _and not_ any of the environments configured within.
=> Restrict baselines to certain regions for the Modernisation Platform account

terraform/environments/bootstrap/.terraform.lock.hcl, terraform/environments/bootstrap/locals.tf, terraform/environments/bootstrap/main.tf
Resolves #197.
This uses the `regional-enablement` branch of the baselines module to destroy resources in restricted regions as part of the [Organizational Service Control Policy](https://github.com/ministryofjustice/aws-root-account/blob/main/terraform/organizations-service-control-policies.tf#L61).
=> Deprecate regional services for restricted regions in the bootstrap step

terraform/environments/core-shared-services/vpc.tf
- update shared-services json file to change prefix name to live-data
and non_live_data. Existing names were live and non_live.
A decision has been made to have two environments in our core
accounts which will align with two Transit Gateway routing tables.
=> Change shared services prefix names

terraform/modules/ec2-tgw-attachment/main.tf, terraform/modules/ec2-tgw-attachment/outputs.tf, terraform/modules/vpc-tgw-routing/main.tf
- update live and non-live refs in core-vpc to match the names used in
core-network-services
This change is required to allow the use of the new naming convention in
network-services
=> Change live and non-live data refs in core-vpc

terraform/environments/core-vpc/transit-gateway-attachment.tf, terraform/modules/ec2-tgw-attachment/main.tf, terraform/modules/ec2-tgw-attachment/outputs.tf, terraform/modules/ec2-tgw-attachment/variables.tf
Marked as draft due to requiring `terraform state mv`.
This PR cleans up the EC2 Transit Gateway attachment module to allow you to attach to different types of VPCs depending on Terraform workspace (live_data, non_live_data).
It also tags taggable resources with passed-through tags and adds the explicit default options for a TGW attachment.
=> Clean-up EC2 Transit Gateway attachment module

terraform/environments/core-vpc/backend.tf, terraform/environments/core-vpc/locals.tf, terraform/environments/core-vpc/transit-gateway-attachment.tf, terraform/modules/ec2-tgw-attachment/main.tf, terraform/modules/ec2-tgw-attachment/variables.tf
This PR moves the RAM principal association for our shared Transit Gateway into our attachment module.
Marked as draft as it requires a `terraform state mv`.
=> Move the RAM principal association into the EC2 TGW attachment module

config/tech-docs.yml
This turns off `multipage_nav` and `collapsible_nav` due to links being incorrectly generated in the tech docs gem.
It also fixes the canonical URL.
=> Remove broken nav links & fix canonical URLs

.github/workflows/check-links.yml, makefile
Thanks to @digitalronin for updating tech-docs 👍🏼 
This PR:
- updates `tech-docs-github-pages-publisher` to 1.1, which:
- fixes a bug where the link checker fails for unpublished pages, as it used the `host` URL rather than a relative link
- removes the need to set `ROOT_DOCPATH`
- adds a workflow to check links on PRs that change `source` rather than just on push to main
=> Update tech-docs and workflows to tech-docs 1.1

terraform/environments/bootstrap/delegate-access/.terraform.lock.hcl, terraform/environments/bootstrap/delegate-access/versions.tf, terraform/environments/bootstrap/secure-baselines/backend.tf, terraform/environments/bootstrap/secure-baselines/main.tf
This PR moves the secure-baselines `workspace_key_prefix` from `environments/bootstrap` to `environments/bootstrap/secure-baselines`, to mimic the folder structure in this repository.
=> Move secure-baselines workspace_key_prefix to mimic folder structure

scripts/redact-output.sh, scripts/terraform-apply.sh, scripts/terraform-init.sh, scripts/terraform-plan.sh
This adds some base scripts to run Terraform as part of a CI/CD pipeline.
`plan` and `apply` are piped to `redact-output.sh`, to redact `AWS_SECRET_ACCESS_KEY` and `AWS_ACCESS_KEY_ID` if exposed, alongside IDs that may be sensitive.
=> Add base Terraform scripts for workflows

scripts/loop-through-terraform-workspaces.sh
This script runs Terraform in a specified directory and runs either `terraform plan` or `terraform apply` across all workspaces configured within the backend in the directory.
It's a prerequisite for our GitHub workflow that will create new environments, delegate access to the Modernisation Platform, and configure secure baselines within all of the environments.
Requires #246.
=> Add script to loop through Terraform workspaces and run plan, or apply

.github/workflows/new-environment.yml
This corrects the path for the terraform scripts to change directory into for secure-baselines.
=> Fix path for secure baselines in GitHub workflow

source/team-guide/useful-scripts.html.md.erb
This adds information to the [Useful scripts](https://ministryofjustice.github.io/modernisation-platform/team-guide/useful-scripts.html#useful-scripts) page regarding new scripts we're using in workflows:
- git-commit.sh
- git-pull-request.sh
- git-setup.sh
- terraform-apply.sh
- terraform-init.sh
- terraform-plan.sh
- provision-terraform-workspaces.sh
- loop-through-terraform-workspaces.sh
- provision-environment-directories.sh
- redact-output.sh
- check-environment-definitions.js
- internal/upgrade-terraform-providers.sh
- utilities.js
=> Update useful scripts documentation to cover: git, terraform, and other new scripts

terraform/templates/versions.tf
As part of #258 and #262, #263, #264, #265, #266, #267, #268, #269, and #270, I had to manually copy and paste a `versions.tf` file. We can add this to the templates directory to automatically copy across for new environments instead of having to remember 👍🏼
=> Add template for versions.tf

terraform/environments/justice-on-the-web/.terraform.lock.hcl, terraform/environments/justice-on-the-web/backend.tf, terraform/environments/justice-on-the-web/locals.tf, terraform/environments/justice-on-the-web/versions.tf
This PR updates the structure of the `.tf` files within the justice-on-the-web environment. It's part of our move to create a separation of concerns and split files by resource within environments so they are easily found and is a follow on from #258.
Terraform plan across workspaces returns no changes:
```
Getting remote workspaces
Finished getting remote workspaces
Running terraform plan across all workspaces in terraform/environments/justice-on-the-web
No changes. Infrastructure is up-to-date.
This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
Finished running terraform across all workspaces in terraform/environments/justice-on-the-web
```
=> Update justice-on-the-web templates to match new structure

terraform/environments/core-network-services/.terraform.lock.hcl, terraform/environments/core-network-services/backend.tf, terraform/environments/core-network-services/locals.tf, terraform/environments/core-network-services/providers.tf
This PR updates the structure of the `.tf` files within the core-network-services environment. It's part of our move to create a separation of concerns and split files by resource within environments so they are easily found and is a follow on from #258.
Terraform plan across workspaces returns no changes:
```
Getting remote workspaces
Finished getting remote workspaces
Running terraform plan across all workspaces in terraform/environments/core-network-services
...refreshing state
No changes. Infrastructure is up-to-date.
This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
Finished running terraform across all workspaces in terraform/environments/core-network-services
```
=> Update core-network-services templates to match new structure

terraform/environments/core-network-services/transit-gateway.tf, terraform/environments/core-network-services/vpc.tf
This PR restructures core-network-services Transit Gateways and the general VPC CIDR configuration to match the newer structure in `core-vpc`.
This PR also renames the resource key of route tables from `transit-gateway-route-table` to `route-tables` to drop the duplication from the resource name.
=> Restructure core-network-services Transit Gateways and VPC configuration to match core-vpc

terraform/environments/core-vpc/transit-gateway-attachment.tf, terraform/modules/ec2-tgw-attachment/main.tf, terraform/modules/ec2-tgw-attachment/variables.tf
This PR corrects some provider declarations for data sources to enable you to call it from a different account to what it needs to be run in.
It also introduces a `vpc_name` variable. This allows you to tag Transit Gateway attachments to appear as `${vpc-name}-attachment`, rather than the previously set `shared-transit-gateway-attachment`.
It means our Transit Gateway attachments in `core-vpc-production` list as:
`hmpps-production-attachment`, and
`laa-production-attachment`
=> Transit Gateway attachments: correctly set providers and allow tagging of attachments

terraform/modules/ec2-tgw-attachment/main.tf
This allows the retagging of Transit Gateway attachments in the host account based on the tenant account's attachment.
=> Retag EC2 Transit Gateway attachments in the host

terraform/modernisation-platform-account/providers.tf
Updates the [modernisation-platform-terraform-baselines](https://github.com/ministryofjustice/modernisation-platform-terraform-baselines) from `regional-enablement` to `v2.0.0` for the Modernisation Platform landing zone.
=> Update baseline module reference from regional-enablement to v2.0.0

.github/workflows/check-links.yml, .github/workflows/publish.yml, makefile
This PR updates [tech-docs-github-pages-publisher](https://github.com/ministryofjustice/tech-docs-github-pages-publisher) from 1.1 to 1.2.
=> Update tech-docs-github-pages-publisher to 1.2

terraform/modules/core-vpc/main.tf, terraform/modules/core-vpc/outputs.tf
This expands acronyms from:
- IG -> Internet Gateway
- TGW -> Transit Gateway
and  rekeys the Internet Gateway to `default` (rather than `ig`, this module only configures 1).
It adds some missing tags on `aws_cloudwatch_log_group`, and updates the default NACLs to be use `=` rather than `:` as key, value separators to match Terraform and show the correct in-file syntax highlighting for IDEs.
=> Expand acronyms and add missing tags

terraform/environments/core-network-services/ram.tf, terraform/environments/core-shared-services/transit-gateway-attachment.tf, terraform/environments/core-vpc/transit-gateway-attachment.tf
This renames references to `shared-transit-gateway` (which is shared via Resource Access Manager) to `transit-gateway`, as it's inferred that it's shared as it's part of a resource share.
=> Rename shared-transit-gateway to transit-gateway

terraform/environments/core-shared-services/.terraform.lock.hcl, terraform/environments/core-shared-services/vpc.tf, terraform/modules/core-vpc-tgw-routes/main.tf, terraform/modules/core-vpc/main.tf, terraform/modules/core-vpc/outputs.tf
This PR moves the TGW routes from the `core-vpc` module into `core-vpc-tgw-routes`, so you can explicitly `depends_on` the VPC attachment before creating Transit Gateway routes for the core VPC.
=> Move TGW routes into a separate module for explicit depends_on

terraform/modernisation-platform-account/.terraform.lock.hcl, terraform/modernisation-platform-account/locals.tf, terraform/modernisation-platform-account/outputs.tf, terraform/modernisation-platform-account/versions.tf
This PR does some routine cleanup for the Modernisation Platform account Terraform:
- removes the unused data call for `aws_regions`
- adds a description for the IAM superadmin passwords output
- removes the unused local provider from `required_providers`
=> Cleanup Modernisation Platform account: remove unused vars and add output description

terraform/environments/.terraform.lock.hcl, terraform/environments/versions.tf
This PR removes the unused `local` provider and adds the `random` provider to `required_providers` for the environments/ Terraform.
=> Remove unused required provider from environments/ configuration and add random provider

terraform/modernisation-platform-account/baselines.tf, terraform/modernisation-platform-account/providers.tf
General cleanup of moving the baselines module out of the providers file.
=> Separate baselines & providers for Modernisation Platform account

terraform/environments/core-vpc/vpc.tf, terraform/modules/vpc-tgw-routing/main.tf, terraform/modules/vpc-tgw-routing/variables.tf, terraform/modules/vpc-tgw-routing/versions.tf
This PR cleans up the VPC TGW routing module:
- Removes the need to specify both a default and aliases for the provider as the module only uses one provider (core-network-services), so you can use the module's default provider, mapped to the correct root provider
- adds suitable descriptions and types to variables
- adds a versions.tf with a minimum Terraform and AWS provider version
=> Cleanup VPC Transit Gateway routing module

terraform/environments/analytical-platform-management/versions.tf, terraform/environments/bichard7/versions.tf, terraform/environments/core-logging/versions.tf, terraform/environments/core-network-services/versions.tf, terraform/environments/core-sandbox/versions.tf, terraform/environments/core-security/versions.tf, terraform/environments/core-shared-services/versions.tf, terraform/environments/core-vpc/versions.tf, terraform/environments/justice-on-the-web/versions.tf, terraform/environments/remote-supervision/versions.tf, terraform/environments/versions.tf, terraform/modernisation-platform-account/versions.tf, terraform/templates/versions.tf
This PR updates the templates directory to use a minimum version for:
- Terraform itself, with a minimum version of v0.14.2
- the AWS provider, with a minimum version of v3.20.0
This is to ensure older Terraform versions and AWS providers aren't used, which may cause issues with our configuration. For instance, Terraform 0.14.0 [introduced a bug](https://github.com/hashicorp/terraform/blob/v0.14/CHANGELOG.md#0141-december-08-2020) where ignore_changes doesn't appear to work, forcing some resources to be created, which was fixed in Terraform 0.14.1. Terraform 0.14.1 [also introduced a bug](https://github.com/hashicorp/terraform/blob/v0.14/CHANGELOG.md#0142-december-08-2020) where remote backends were checked for compatibility when they were only used for read rather than write.
By …
=> Update required providers to always specify a minimum AWS provider and Terraform version

terraform/environments/core-vpc/vpc.tf, terraform/modules/vpc-nacls/main.tf, terraform/modules/vpc-nacls/variables.tf, terraform/modules/vpc-nacls/versions.tf
This PR cleans up the VPC custom NACLs module:
- removes the tags_common variable, which is unused as NACL rules are untaggable
- adds variable descriptions
- adds a `versions.tf` file
=> Cleanup VPC custom NACLs module

terraform/github/backend.tf, terraform/github/main.tf, terraform/github/modules/repository/main.tf, terraform/github/modules/repository/variables.tf, terraform/github/modules/repository/versions.tf, terraform/github/modules/team/main.tf, terraform/github/modules/team/versions.tf, terraform/github/providers.tf
This PR:
- splits out the `backend` and `provider` declarations into separate files, to mimic other parts of this repository
- imports the `modernisation-platform-cidr-allocation` repository which was manually created, so we can manage it here
- fixes version declarations to use Terraform 0.14.2 or above, and the correct minimum provider version for GitHub
- adds a `visibility` variable for the `modernisation-platform-cidr-allocation` repository to be internal
=> Split out backend and providers declarations, import orphaned repository resource

.github/dependabot.yml
This PR enables Dependabot to complete version checking for Terraform and GitHub actions.
This is different to vulnerability scanning via dependabot, in that this configuration will automatically create PRs for new versions of things _even if_ there aren't any security vulnerabilities reported in the old version.
The configuration can be [validated through Dependabot](https://dependabot.com/docs/config-file/validator/) through and there is an open issue as to why each directory needs its own declaration at dependabot/dependabot-core#2178.
Also note that [Dependabot doesn't currently support HCL2](https://github.com/dependabot/dependabot-core/issues/1176), so the Terraform configuration won't be functional until they do; but it's on the [roadmap for Q1 …
=> Enable Dependabot for GitHub actions and Terraform

terraform/github/.terraform.lock.hcl, terraform/github/locals.tf, terraform/github/main.tf, terraform/github/modules/team/main.tf, terraform/github/modules/team/outputs.tf, terraform/github/modules/team/variables.tf, terraform/github/modules/team/versions.tf, terraform/github/versions.tf
This PR:
- pulls the `local` variable from inside the module for `maintainers`, `members`, `ci` to outside it
- introduces module variables to create teams with different structures, e.g. a subset can be members of a child team
- introduces the `parent_team_id` variable to nest GitHub teams
- updates the GitHub provider to v4.40.0 to allow the creation of default maintainers for a team
This PR forms the basis of introducing a subset team of people who need AWS access, for AWS SSO.
=> GitHub team module: update to 4.40.0 and introduce variables for team members

.github/labeler.yml, .github/workflows/labeler.yml
This PR _should_ fix the following issues:
- PRs that include `**.lock.hcl` file changes not being appropriately tagged as `dependencies` ([example](https://github.com/ministryofjustice/modernisation-platform/pull/316/files))
- Labeler ignoring sync-labels being unset or explicitly "false" due to the way ECMAScript uses the variable ([more info](https://github.com/actions/labeler/issues/104)), by now explicitly setting an empty variable. This should fix the issue where manually tagged PRs lose their labels when labeler runs ([example](https://github.com/ministryofjustice/modernisation-platform/pull/320#event-4296370480))
=> Fix labeller ignoring non-defined sync-labels option and ignoring .lock.hcl glob

terraform/github/locals.tf, terraform/github/main.tf, terraform/github/modules/team/main.tf
This PR creates a new GitHub team for `engineers` so we can infer AWS access via AWS SSO.
This PR also cleans up pre-existing role determination, so usernames needn't be duplicated if split across more than one team, by providing a local that concats all lists into one.
The module will also work out which team member gets which role, i.e. if someone is a GitHub organisation _owner_ and in the `maintainers` list, they will become a maintainer even if they're passed through as a `member`, as they will always have that permission by being an organisation owner.
=> Add an 'engineer' team and clean up pre-existing role determination

terraform/environments/core-network-services/route53.tf
This delegates the `bichard7.` subdomain to the bichard7 Hosted Zone.
They're aware that we'll centrally manage this in the future, so this is to unblock them 👍🏼
=> NS delegation for bichard7

terraform/modernisation-platform-account/.terraform.lock.hcl, terraform/modernisation-platform-account/baselines.tf, terraform/modernisation-platform-account/iam.tf, terraform/modernisation-platform-account/s3.tf
Part of #72.
This PR pins the following modules in the Modernisation Platform account Terraform:
- `modernisation-platform-terraform-trusted-advisor`
- `modernisation-platform-terraform-iam-superadmins`
- `modernisation-platform-terraform-s3-bucket`
=> Pin modules used in modernisation-platform-account

terraform/modernisation-platform-account/iam.tf
Part of #88 and works toward allowing us to run the Modernisation Platform as part of automation.
This PR creates a couple of things:
- an IAM group for CI users to live inside, that has two policies attached: AdministratorAccess, and some specific denies
- an IAM user called `ci` that lives inside the `CI` group
- some Terraform managed access keys for the `CI` user, allowing us to run `terraform taint aws_iam_access_key.ci` to rotate them
- an output for the Terraform managed keys, marked as `sensitive`. This stops Terraform outputting the keys as they're sensitive, _but they are still stored in plain-text in the statefile and should not be echo'ed out somewhere public, such as a CI pipeline_
=> Add a CI user with a specific deny policy to allow us to run Terraform as part of a CI/CD pipeline

terraform/modernisation-platform-account/iam.tf, terraform/modernisation-platform-account/secrets.tf
This PR moves the CI users IAM access keys into AWS Secrets Manager, so we can take advantage of getting the latest version from our GitHub configuration, and Lambda-driven rotation.
=> Move AWS access keys into Secrets Manager

.github/workflows/new-environment.yml, terraform/github/.terraform.lock.hcl, terraform/github/aws.tf, terraform/github/main.tf, terraform/github/providers.tf, terraform/github/versions.tf
This PR allows our GitHub Terraform to get the AWS access keys for the CI user from AWS; and sets them as repository secrets.
It also changes the previous access keys into a new key: `secrets.PRIVILEGED_AWS_ACCESS_KEY_ID`, so people can default on using `secrets.AWS_ACCESS_KEY_ID` for non-privileged actions.
This PR forms part of the work around #88, #142, and #295.
=> Set GitHub repository secrets from AWS Secrets Manager

terraform/environments/core-network-services/output.tf, terraform/environments/core-network-services/vpc.tf, terraform/modules/vpc-hub/main.tf, terraform/modules/vpc-hub/outputs.tf, terraform/modules/vpc-hub/variables.tf, terraform/modules/vpc-hub/versions.tf
This PR:
- Points `core-network-services` to the VPC Hub module, which replaces the `core-vpc` module
- Adds missing tags
- Points `aws_network_acl_rule` to the right NACL, rather than just `public`
- Fixes outputs in VPC Hub to meet the previous implementation
- Fixes an issue with NAT being configured even if `var.gateway` isn't NAT
=> VPC Hub fixes: point NACL rules to the right resource, add missing tags

terraform/github/locals.tf
This PR adds Fasih and David to the `modernisation-platform` GitHub team.
=> Add Fasih and David to the correct GitHub teams

.github/workflows/new-environment.yml
The `delegate-access` workflow relies on OrganizationAccountAccessRole that is only usable with the privileged access keys in this repository.
=> Provide right AWS keys for the delegate-access workflow

environments/core-vpc.json
This PR removes `core-vpc-non-live-data` from the Modernisation Platform as part of the the guide in the #429.
I expect this to return 2 to destroy:
- the AWS secret needs to be replaced, so will be destroyed (to remove the account ID)
- the random string that is set as the email address for the account will also be destroyed as it's a separate Terraform resource
=> Remove core-vpc-non-live-data

scripts/provision-terraform-workspaces.sh
The `provision-terraform-workspaces.sh` script has been failing since the structure of the environment JSON files changed as part of #400.
Instead of pointing to the array value, this now points to the object's value for the environment's `name`.
=> Fix provision workspaces to use the new environments JSON structure

terraform/environments/bootstrap/single-sign-on/versions.tf
The GitHub action for [single sign-on failed](https://github.com/ministryofjustice/modernisation-platform/runs/2002715394?check_suite_focus=true) due to the runner using Terraform 0.14.6 and the required version being `0.14.7`. This reduces the Terraform version by one patch version to resolve that issue.
=> Reduce required Terraform version for single sign-on

scripts/git-pull-request.sh
Explicitly set the `curl` method to POST and remove double space to create a PR as part of the [`new environments files` workflow](https://github.com/ministryofjustice/modernisation-platform/actions/workflows/new-environment-files.yml).
=> GitHub creating a pull request: set method to POST explicitly

terraform/environments/core-network-services/acm-pca.tf, terraform/environments/core-network-services/ram.tf, terraform/environments/core-sandbox/base_variables.tf, terraform/environments/core-sandbox/bastion_linux.tf.bak, terraform/environments/core-sandbox/locals.tf, terraform/environments/core-sandbox/networking.auto.tfvars.json, terraform/environments/core-sandbox/playground.tf, terraform/environments/core-sandbox/providers.tf, terraform/environments/core-vpc/vpc.tf, terraform/modules/member-vpc/outputs.tf, terraform/modules/ram-ec2-retagging/main.tf, terraform/modules/ram-principal-association/main.tf, terraform/modules/ram-principal-association/variables.tf, terraform/templates/locals.tf, terraform/templates/main.tf
This PR fixes and adds a number of core features:
- Automates ACM Private Root CA and Subordinate certificates. 
- ACM Private CA revocation S3 bucket and list
- ACM PCA subordinate RAM shares for live and non-live CA
- Fixes the core account RAM shares for subnet-sets by association the correct subnets in the resources section
- Fixes the base member account RAM share mapping so that the member accounts map to the correct RAM share hosting the    correct subnet-sets 
- fix the RAM member account tagging for subnets
=> Feature/private acm configuration and member account RAM share config

.github/ISSUE_TEMPLATE/bug-template.md, .github/ISSUE_TEMPLATE/story-template.md
Automatically add bug or enchancement labels for issues depending on
which template is used.
=> Add labels to issues templates

terraform/github/locals.tf
Reverts ministryofjustice/modernisation-platform#558
Removing temporarily as Christine is not part of the moj organisation yet and this is causing the workflow to fail. (Which we need to fix)
=> Revert "Add Christine to the github team"

terraform/github/modules/repository/main.tf
2 reasons for reverting this,
1) This means the check must always run, if it doesn't then the merge is
blocked.
2) This is at the module level so it is forcing all of these checks to
run even in repos that don't even have this workflow. Unfortunately it
doesn't work only if they exist, it expects them to exist.
=> Revert adding checks

.github/workflows/publish.yml
Publish.yml workflow was running on nearly every merge. This is not
needed.
=> Run publish only on source documentation changes

scripts/tests/validate/opa.sh
Currently the tests return an exit code of 0 even if they fail.  This is
because they are being piped. Adding the pipefail fixes this.
=> Set pipefail option to fail tests

policies/networking/core-vpc.rego
The bastion test fails because the check for the key returns false if the key is present but it has a false value:
https://www.openpolicyagent.org/docs/latest/policy-reference/#objects
`# check if key "foo" exists and is not false`
`obj.foo`
I've not found a good fix for this yet and since we are not using the bastion key and will be removing commenting this out for now so that we can see the other tests results more easily.
=> Comment out bastion test

terraform/environments/core-vpc/vpc.tf, terraform/modules/member-vpc/main.tf, terraform/modules/member-vpc/variables.tf
Change variable name for Transit Gateway CIDR range as the name could cause confusion.
=> amend-transit-gateway-variable-name-in-member-vpc-module

scripts/terraform-apply.sh, scripts/terraform-plan.sh
Because the options variable was in quotes it was being passed into the
command as a string
=> Fix bug where options aren't passed in correctly

terraform/github/main.tf
Following the same pattern as on the modernisation-platform repo, we
give write (aka push) access to all-org-members. The main branch is
protected by codeowners.  This avoids us having to add teams to the repo
individually and keeps control of who can merge what into main in the
codeowners file.
Resolves #748
=> Give write access to all-org-members on env repo

terraform/environments/core-vpc/locals.tf, terraform/environments/core-vpc/vpc.tf, terraform/modules/dns-zone/main.tf, terraform/modules/dns-zone/variables.tf
We want to be able to assume the dns role using the new member ci user.
This user and role will be used to make member changes to dns rather
than the main mod platform ci user and the admin role.
Resolves #746
=> Change DNS role to be assumed by mp account

terraform/modernisation-platform-account/iam.tf, terraform/modernisation-platform-account/secrets.tf
We don't want to use the main ci user with access to everything for the
member ci workflows, this user will use account focussed or restricted
access roles.
Resolves #755
=> Add member ci user to mod plat account

scripts/provision-environment-directories.sh, scripts/provision-member-directories.sh, terraform/modules/dns-zone/main.tf, terraform/templates/member-providers.tf
To secure the members terraform, we needed to change the core-vpc role
to use a business unit scoped role rather than an all access role, and
remove the role for shared services. To do this via sed/file
manipulation was becoming messy, so instead we've created a separate
member-providers.tf template file, and depending on whether the
provision member directories script or the provision environment
directories script is running the correct template will be copied. This
also allows us to further modify the repective providers.tf files in
future if we need to and not have to further modify the scripts.
Terraform plan for the member accounts was failing with the error:
`not authorized to perform: route53:GetHostedZone on resource:`
I checked the policy and it is missing this, also it was …
=> Update templates and DNS role policy

environments-networks/platforms-development.json
This wasn't actually applied for some reason (which we need to look into
why the core-vpc workflow didn't pick it up or if it failed)
Since it's not needed for the PoC removing for now until we can re-add
and investigate further. #763 issue for investigation.
=> Remove us-east-1 endpoint

terraform/modernisation-platform-account/iam.tf
The original ci user has the AdministratorAccess policy attached, so it
could access the buckets and secrets etc. This adds a much more
restricted policy to allow the access the user requires.
=> Add policy for member ci user

terraform/environments/core-network-services/iam.tf
The permissions were not open enough and causing errors, adding get and
list permissions so it can retrieve all the zones.
=> Update permissions for dns role

.github/workflows/new-member-environment-files.yml, .github/workflows/templates/workflow-template.yml, scripts/git-create-environments.sh, scripts/provision-member-directories.sh
Github environments will allow users to control when their deployments
happen.  This takes the github teams defined in the environments json,
and creates an environment per mp environment (aws account). For
preprodcution and production environments, along with reviewer protection,
you can only deploy from main.
Also adds a workflow template that generates a workflow file on account file creation.
=> Add automation to generate Github environments

scripts/terraform-apply.sh, scripts/terraform-init.sh, scripts/terraform-plan.sh
Because of piping the terraform command through the redaction script,
the success code will always be 0. Adding pipefail to fix this and also
-e in case there are other uncaught errors in the script.
Closes #559
=> Fix terraform scripts always exit with 0

terraform/github/main.tf, terraform/github/modules/repository/main.tf, terraform/github/modules/repository/variables.tf, terraform/github/modules/team/main.tf
Checks were done on the module level, changing this so that checks can
also be passed in per repo and passing in the opa check to run.
=> Require OPA tests to be run in environments repo

terraform/environments/core-vpc/vpc.tf, terraform/modules/dns-zone/main.tf
closes #779 
- remove dns member role from DNS module
- create generic role in core-vpc top level
- add additional permissions for data lookups
This change is required to make the delegate-member role more generic
rather than focused purely on DNS
=> refactor-member-iam-role

.github/workflows/core-vpc-development-deployment.yml, .github/workflows/core-vpc-preproduction-deployment.yml, .github/workflows/core-vpc-production-deployment.yml, .github/workflows/core-vpc-test-deployment.yml
The core VPC workflows were only being triggered by new network json
file, now they run when we make changes to the terraform or the workflow
as well.
=> Add trigger for core VPC worklfows

terraform/modules/bastion_linux/main.tf
This change comments out the shared subnet-set vpc data object and shared subnet-set private (az (a) subnet) data object so that data calls are instead done from the member account.
=> Comment out data call providers so they are instead called by local accounts.

terraform/github/locals.tf, terraform/github/main.tf
Adding teams that need access to the environment repo. We need to
explicitly specify team access in the repo for github environments
approvals to work (as we require a team approval, that team must have
access).  Hopefully
https://github.com/ministryofjustice/operations-engineering/issues/139
will be possible and we can just add the parent team once here.  If not
we will need to automate the updating of this list of application teams
and trigger the github workflow to run when any changes to environment
json files are made.
=> Add team access to environments repo

terraform/modernisation-platform-account/locals.tf, terraform/modernisation-platform-account/s3.tf
In order to create SCPs in the root account you need a user with more
permissions than the ModernisationPlatformOrganisationManagement which we use
to create OUs and accounts, this change gives users with the approriate
permissions access to the state file to be able to make these changes.
=> Give DavidElliott user state access

terraform/modules/bastion_linux/outputs.tf
Bastion instance private IP is used by application instance security group rules so the output was included.
=> Add output for ec2 private IP to bastion module

terraform/environments/bootstrap/secure-baselines/main.tf
We are now enabling GuardDuty from all new accounts by default, so this
is no longer needed in the baselines.
Resolves #809
=> Remove GuardDuty from baselines

scripts/loop-through-terraform-workspaces.sh
This is temporary until we delete default VPCs for all other accounts
AP will fail as they have deleted their default vpc, we want to delete all default vpcs
But are waiting for v4 of the aws provider which will allow us to do this via TF
=> Skip analytical platform on baselines

terraform/environments/bootstrap/single-sign-on/main.tf, terraform/environments/core-vpc/vpc.tf
Interpolation-only expressions became depreciated in TFv0.12, fixing to
remove the warnings.
=> Remove interpolation warnings

.github/workflows/scheduled-baseline.yml
Baselines where being skipped when run on a schedule due to the if
statement.  Removing the statement to fix.  By default this should now
run against the latest commit on main.
=> Fix scheduled baselines not running

terraform/modernisation-platform-account/iam.tf, terraform/templates/member-providers.tf
Now that we have a restricted member role for member infrastructure
changes we need to update the template.
Also changing the role that the member-ci user can assume to this one.
=> Update template and member-ci user to use new member role

terraform/environments/bootstrap/delegate-access/iam.tf, terraform/modules/iam_baseline/main.tf
Resolves #810, currently the member CI/CD user uses a unrestricted admin
role to create infrastructure.  This is a new role which can be assumed
with restricted permissions, so that we can have confidence that users
don't create resources that we don't want them to to.
=> Add role to create infrastucture for members

scripts/git-commit.sh, scripts/git-pull-request.sh
Currently if the workflow runs and there are no changes a branch still
gets created.  We want to prevent this from happening as we end up with
a load of unecessary branches. Resolves #826
=> Stop creating empty branch if no changes

scripts/provision-member-directories.sh, terraform/environments/bench/locals.tf, terraform/environments/bench/outputs.tf, terraform/environments/bootstrap/delegate-access/locals.tf, terraform/environments/bootstrap/secure-baselines/locals.tf, terraform/environments/cooker/locals.tf, terraform/environments/heater/locals.tf, terraform/environments/ops-engineering/locals.tf, terraform/environments/performance-hub/locals.tf, terraform/environments/sprinkler/locals.tf, terraform/templates/locals.tf
Currently tags are all statically defined in the locals file for member
accounts. This change pulls the tags from the environments file, so if
the tags in the environment json file are changed this will be reflected
the next time the infrastructure terraform for that account is run.
I am getting the .json file directly from github over http, rather than
referencing the file in the repository, because the same template is
used in the environments repository, and this will work from both
repositories to pull the file to generate the tags. This keeps it
consistent across the repos.
Also some minor updates to the tags to add things like the source code
repository. This will help going forward to identify if a resource in an
account was generated from the members environments repo or this …
=> Enable dynamic tagging

.github/workflows/publish.yml
This ignores the 0 errors that cause the publisher to fail incorrectly
=> Update to lastest publisher version

.github/workflows/core-logging-deployment.yml, .github/workflows/core-network-services-deployment.yml, .github/workflows/core-security-deployment.yml, .github/workflows/core-shared-services-deployment.yml, .github/workflows/core-vpc-development-deployment.yml, .github/workflows/core-vpc-preproduction-deployment.yml, .github/workflows/core-vpc-production-deployment.yml, .github/workflows/core-vpc-test-deployment.yml, .github/workflows/new-environment-files.yml, .github/workflows/new-member-environment-files.yml, .github/workflows/terraform-github.yml, terraform/github/main.tf, terraform/github/providers.tf
This adds a notification to slack when a workflow fails. Note this is
added only to jobs that run when merged into main.  There is no point in
added alerts to jobs that run when a PR is created - we'll see if it
fails on the PR.  But currently once we merge a PR and a job runs you
either have to manually check that the workflow ran ok, or assume it
runs sucessfully.  As 99% of the time they run sucessfully it has caught
us out in the past where things have failed and we've not seen the
impact of the failure until later.
=> Add slack notification for workflow failure

terraform/github/modules/repository/main.tf
The code formatter hangs when it has to make a commit because it uses
the same repo token therefore doesn't trigger the workflow to run after
making a commit. This leaves the PR in a hung state as it can't be
merged until the required check has run.
https://github.community/t/push-from-action-does-not-trigger-subsequent-action/16854/5
Removing the need for the formatter to be required, it is only
formatting code and not critical that it runs.
Closes #926
=> Remove format-code required

environments/performance-hub.json
Elevating the developers access to admin. 'developer' access current does not give access to cloudwatch or secretsmanager
=> Make perf hub team - AWS admins

.github/workflows/check-links.yml, makefile
The main publish workflow was updated previously but we missed these
versions in the check-links.yml and make file.
=> Update missed publisher versions

source/user-guide/creating-environments.html.md.erb, terraform/environments/bootstrap/single-sign-on/main.tf
The developer permission set was ViewOnly with additional permissions.
Changing this to ReadOnly with additional permissons. For view only
users we will now use the generic ViewOnlyAccess.
Closes #936
See the root account changes in https://github.com/ministryofjustice/aws-root-account/pull/237
=> Separate out view and developer sso roles

environments/performance-hub.json
Reverts ministryofjustice/modernisation-platform#935
We have changed the developer permission set now to have the required permissions so we can revert performance hub team back to developer access.
=> Revert "Make perf hub team - AWS admins"

.github/workflows/terraform-static-analysis.yml
To improve our code quality we want to run static code analysis on our
terraform code.
This action should run TFSEC and Checkov on changed terraform folders.  There is a workflow dispatch option to run a full scan on all our terraform.
There are currently a lot of alerts so we need to tweak this.  Also it takes a couple of minutes to run as it's 2 tests combined, it might be better to use the official actions and split out into 2 workflows that run concurrently.  The main benefit of this custom action is to only run on folders which have changed, and to be able to run a full scan.  The standard actions you have to pass in the terraform directory name, which means if multiple terraform directories are changed it will scan only one.  So there is also no way to scan everything at once.
Work …
=> Add terraform static code analysis

.github/workflows/terraform-static-analysis.yml, terraform/environments/bootstrap/delegate-access/iam.tf, terraform/modules/iam_baseline/main.tf
Suppressing some errors that we don't care about -
AWS095 - we will not be using CMK for most things.
AWS099 and checkcov warnings in bootstrapping - these policies need to be open to allow
creation of resources.
Also adding AWS access keys so that terraform init can run which will
give warnings about modules used as well.
Restricted the IAM policy slightly as that is possible.
=> Quiet unwanted warnings and resolve errors with static analysis

policies/README.md, policies/environments/environment-definitions.rego, policies/environments/environment-definitions_test.rego, policies/member/environment-definitions.rego, policies/member/environment-definitions_test.rego, policies/member/utilities.rego, policies/networking/core-vpc_test.rego, scripts/tests/validate/README.md, scripts/tests/validate/run-opa-tests.sh
The follow validation is added:
For all accounts -
- business unit name max 20 characters, only a-z A-Z and -
For member accounts
- file (application) name max 30 characters, only a-z and -
- only development,test,preproduction and production environment names
allowed.
OPA tests and readme updated.
Closes #725
=> Add naming validation to OPA tests

.github/workflows/terraform-static-analysis.yml
The terraform static analysis repo is now in the moj repo, switching
over to using this one.  Also removing AWS credentials as the tf init
part of the action has been removed over security concerns of these
scripts having access to the creds.
Closes #309
=> Switch Terraform Static analysis to MoJ repo

scripts/provision-member-directories.sh
This file currently gets missed as the templates variable is only
terraform files.  This explicitly copies the required file.  If we end
up needing more non TF files we may want to switch this to exclude files rather
than include them.
=> Copy application variables template accross

scripts/git-create-environments.sh
Currently only the application owner github team can make deployments to
github environments.  We've found this is becoming unmanageble as we
often need to make deployments to the infrastructure, especially during
on boarding.
This adds the modernisation platform github team as a default reviewer.
Fixes #974
=> Add modernisation platform team as reviewer

.github/workflows/terraform-static-analysis.yml
Address part of #947 
Simple addition of exclusion already added for checkov to reduce noise from tfsec.
=> Exclude tfsec warning about public github repos

.github/workflows/terraform-static-analysis.yml
Addresses part of #947 - See Network category of warnings
After a team chat last week, we discussed the value of this rule [https://tfsec.dev/docs/aws/vpc/no-excessive-port-access/](https://tfsec.dev/docs/aws/vpc/no-excessive-port-access/) in the context of mod platform and the costs/benefits of it.
It was deemed to be the case that the cost of this (i.e. the noise it generates within the context of the overall design and approach of the mod platform) outweighs any benefits. We agreed that tfsec shouldn't be considered the optimal way to check for quality in the context of mod platform network security. 
This exclusion would eliminate 36 warnings based on decisions made in terraform/modules/vpc-hub/main.tf
=> Exclude static code analysis open nacl ports warnings

terraform/environments/scp_mp_core.tf, terraform/environments/scp_mp_member_unrestricted.tf
Addresses part of #947
Suppress warnings for policies intended for admin users
=> Suppress Checkov IAM failure messages

scripts/provision-terraform-workspaces.sh
Both member and member unrestricted account types need the workspaces to
be created.  This changes the logic so an non core account type get the
workspace created.  This is in keeping with the other logic in the
script.
Fixes #1012
=> Change create workspace logic to not core

terraform/environments/core-network-services/acm-pca.tf
This addresses part of #947 
Propose we add an exclusion for this since we're creating a CRL associated to the private CA, with a specific, restricted access permitted from acm-pca.amazonaws.com. This is based on https://docs.aws.amazon.com/acm-pca/latest/userguide/PcaCreateCa.html#s3-policies and https://aws.amazon.com/premiumsupport/knowledge-center/s3-bucket-error-crl-acm-ca/.
=> Add tfsec exclusion for blocking public access to CRL ACM-PCA s3 bucket

terraform/github/README.md
Updated GitHub readme outlining how to create a new repository for a terraform module and suggesting the addition of a linting job.
=> Updated GitHub readme for terraform modules

terraform/modules/member-vpc/main.tf, terraform/modules/vpc-hub/main.tf
Follows a chat with @davidkelliott regarding the action to take regarding these warnings.
e.g. _Check: CKV2_AWS_12: "Ensure the default security group of every VPC restricts all traffic" FAILED for resource: aws_vpc.vpc_
https://docs.bridgecrew.io/docs/networking_4
Outcome of discussion was to exclude these warnings. Default security groups are unused. Better longer-term solution would be to bring these under better terraform management / be able to remove them.
=> Exclude checkov warning regarding default SGs and full traffic restriction

terraform/environments/core-network-services/acm-pca.tf
Relates to static code analysis checkov warning:
```
Check: CKV_AWS_144: "Ensure that S3 bucket has cross-region replication enabled"
FAILED for resource: aws_s3_bucket.acm-pca
File: /acm-pca.tf:13-59
Guide: https://docs.bridgecrew.io/docs/ensure-that-s3-bucket-has-cross-region-replication-enabled
```
Consistent with decisions around cross-regional replication for S3 buckets elsewhere, this PR adds an exclusion for a checkov rule suggesting that replication should be set up. Exclusion added for this particular use case to at least encourage some consideration in future cases should they be different or if design principles change.
=> Ignoring lack of cross-regional replication for acm-cma bucket

scripts/provision-environment-directories.sh, terraform/environments/tariff/locals.tf, terraform/templates/locals.tf
The application json file is part of the templates and needed for the
environments repository, but it isn't needed here.  Commenting rather
than removing as it's less code in the provisioning script to comment
rather than remove. Also leaving as a comment also serves as a reminder
as to how we should handle environment specific variables if it is ever
needed in this repository.
=> Fix bug where the app json file is needed

terraform/environments/core-network-services/acm-pca.tf
As per a recent discussion on the valid arguments for excluding server access logging on this bucket.
Reasons around purpose of bucket (just used by the AWS private cert authority for CRL) and the restrictive access policy that exists anyway.
=> Adding SCA exclusion for ACM-PCA S3 bucket logging

terraform/modules/member-vpc/main.tf, terraform/modules/vpc-hub/main.tf
tfsec static code analysis warning is
```
[aws-cloudwatch-log-group-customer-key][LOW] Resource 'aws_cloudwatch_log_group.default' is only using default encryption
/github/workspace/terraform/modules/member-vpc/main.tf:196-200
```
For both member-vpc and vpc-hub modules
Following team discussion, these changes are the addition of tfsec exclusions around use of kms key encryption for vpc flow log CloudWatch log group. Wasn't felt this was something that needed to be addressed now. To be reconsidered in the future alongside discussions of our approach to key usage/management across the platform.
=> Skip tfsec warnings about cloudwatch log group kms encryption

terraform/environments/secrets.tf, terraform/modernisation-platform-account/secrets.tf
Example SCA warning:
```
Check: CKV_AWS_149: "Ensure that Secrets Manager secret is encrypted using KMS"
FAILED for resource: aws_secretsmanager_secret.member_ci_iam_user_keys
File: /secrets.tf:27-31
Guide: https://docs.bridgecrew.io/docs/ensure-that-secrets-manager-secret-is-encrypted-using-kms
```
After a discussion among the team, cost outweighs the benefits of encrypting these secrets with a customer-managed KMS key. AWS-managed key will suffice. This replaces #1043 which was to create and reference the kms keys.
=> SCA exclusions for secrets not managed by customer-managed KMS keys

terraform/modernisation-platform-account/s3.tf
Adding regional replication and switching to customer managed KMS keys for the
terraform state bucket. This follows the AWS best practice guidelines,
and if there is ever an issue where we loose access to the London region
we will still be able to see the last known state of the platform.
=> Add regional replication to S3 state bucket

terraform/environments/core-network-services/acm-pca.tf
Makes a fix to #1037 
Given requirement for resource element in kms key policy (see https://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html), resource element has been reverted to "*" and checkov exclusions added.
=> Fix and simplify ACM-PCA kms key policy

README.md
Having core and member modules together was confusing, now it's clear
which modules members can use in their infrastructure.
=> Update readme to make modules clearer

terraform/modernisation-platform-account/dynamodb.tf, terraform/modernisation-platform-account/iam.tf
This fixes an issue with member account CI, specifically with environment terraform operations failing due to lack of access to the kms key used to encrypt the terraform remote state bucket (introduced in https://github.com/ministryofjustice/modernisation-platform/pull/1081)
In addition to adding permissions to the policy applied to the MemberCIAllowActions policy, it
- Explicitly adds required permissions for dynamodb state locking table
- Adds missing alias for dynamodb kms key
=> Add member-ci iam policy permissions

README.md, source/index.html.md.erb
We had some feedback that it wasn't clear from the repo what the
platform was, correcting this.
=> Update readme to explain what mp is

terraform/modernisation-platform-account/s3.tf
The root account currently can't access the terraform state after the
changes to the state bucket KMS encryption.  This adds access to the KMS
key for anyone who should have access to the state bucket.
=> Update access to KMS key for state bucket

terraform/environments/core-network-services/route53.tf
We want our user guidance to have a .service.gov.uk url.
Closes #1097
=> Add route53 record for github pages user guidance

config/tech-docs.yml
The user guidance has broken, this is the only thing that's been changed
in the last PR that might have done that.
=> Revert config change

terraform/modules/iam_baseline/main.tf
There is a need for the application CICD user to read and write to an S3
bucket.  Adding the permissions as documented here -
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_s3_rw-bucket.html
=> Add read/write permissons for S3 buckets for CICD

environments/ops-engineering.json
The ops engineering account is marked for deletion, restricting this
again just in case.
=> Remove admin permissions on ops-eng account

terraform/environments/core-shared-services/ecr_repos.tf, terraform/modules/app-ecr-repo/main.tf, terraform/modules/app-ecr-repo/variables.tf
The existing permissions would only allow the deployment users and the
main modernisation platform account to push and pull from the repo. But
the actual environment account will be the account pulling the image
when ECS starts the container in that account.  This change splits out
the push and pull permissions in the module to make it possible to have
different permissions for each.
=> Fix permissions with perf hub ECR repo

terraform/environments/core-logging/vpc.tf, terraform/environments/core-security/vpc.tf, terraform/environments/core-shared-services/vpc.tf, terraform/modules/app-ecr-repo/README.md, terraform/modules/vpc-hub/README.md, terraform/modules/vpc-hub/main.tf, terraform/modules/vpc-hub/variables.tf
- update vpc-hub module to enable the default routes to point to the
attached Transit Gateway
- update code to supply Transit Gateway ID in
- core-security
- core-logging
- core-shared-services
=> bug core-accounts-missing-default-routes

terraform/environments/core-shared-services/data.tf, terraform/environments/core-shared-services/vpc.tf, terraform/modules/vpc-hub/outputs.tf
Adding VPC endpoints (and dependent resources) to private subnet in non_live_data vpc in shared services account as part of the capability to securely build AMIs using Image Builder.
Related to #1061 .
=> Networking for AMI building in shared services

environments-networks/cica-development.json, environments-networks/garden-development.json, environments-networks/garden-production.json, environments-networks/hmpps-development.json, environments-networks/hmpps-preproduction.json, environments-networks/hmpps-production.json, environments-networks/hmpps-test.json, environments-networks/house-development.json, environments-networks/house-production.json, environments-networks/platforms-development.json, environments-networks/platforms-test.json, environments-networks/template-only.txt
- update protected cidr ranges to use addresses from 10.238.0.0/16
range rather than 10.232.0.0/16 range.
This change is due to a CIDR overlap identified as part of the work to
join Modernisation Platform TGW with PTTP production TGW. The 10.232
range is being used for Magistrates Courts
=> change-cidr-range-for-protected-subnets

policies/networking/expected.rego, terraform/environments/core-logging/vpc.tf, terraform/environments/core-security/test/go_test.go, terraform/environments/core-security/vpc.tf, terraform/environments/core-shared-services/test/go_test.go, terraform/environments/core-shared-services/vpc.tf
- change core-security account CIDRs
- live_data     "10.231.128.0/19"   => "10.230.192.0/19"
- non-live-data "10.231.160.0/19"   => "10.230.224.0/19"
- change core-shared-services account CIDRs
- live_data     "10.231.0.0/19"     => "10.230.64.0/19"
- non-live-data "10.231.32.0/19"    => "10.230.96.0/19"
- update below accounts to use core-vpc-tgw-routes for transit-gateway routing
- core-security
- core-shared-services
- core-logging
- updated OPA test json for protected subnets cidr change
- updated Terratest vpc CIDRs
closes #1142 
closes #1140 
closes #1141
=> change-cidr-for-core-security-and-shared-services

terraform/github/main.tf
Adding the AWS CI access key and secret to the [AMI build repo](https://github.com/ministryofjustice/modernisation-platform-ami-builds) so workflows can authenticate to AWS.
Related to #1059
=> Add ci secrets to ami-builds repo

environments-networks/hmpps-test.json, terraform/modules/vpc-nacls/main.tf
NACLs added to allow the following:
Internet access via the NAT gateway for the data subnets
Web traffic through to the private subnet from the Global Protect VPN
=> Add NACLs for hmpps-test

terraform/environments/core-logging/athena.tf, terraform/modules/app-ecr-repo/main.tf
Some new SCA warnings have appeared, looking at them:
```
[aws-lambda-enable-tracing][LOW] Resource 'aws_lambda_function.athena_table_update' uses default value for tracing_config.mode
```
We have already decided that X-Ray tracing is not required and excluded
it from other checks.
```
[aws-ecr-repository-customer-key][LOW] Resource 'module.performance_hub_ecr_repo:aws_ecr_repository.ecr_repo' configures encryption without using CMK
```
We are using the Amazon managed keys, we do not need the flexibility of
customer managed keys for this repo.
=> Ignore new SCA warnings

.github/workflows/core-vpc-development-deployment.yml, .github/workflows/core-vpc-preproduction-deployment.yml, .github/workflows/core-vpc-production-deployment.yml, .github/workflows/core-vpc-test-deployment.yml, .github/workflows/new-environment.yml, scripts/git-create-environments.sh
When trying to remove operations engineering account (the last
platforms-development account) there is an error on the delegate access
and single sign on plans as it is pulling in an "account name" of
platforms-development.
```
Run accounts=(platforms-development)
[+] Running single sign on baseline for account platforms-development
Initializing the backend...
Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing provider plugins...
- Finding hashicorp/aws versions matching ">= 3.47.0"...
- Installing hashicorp/aws v3.63.0...
- Installed hashicorp/aws v3.63.0 (signed by HashiCorp)
Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file …
```
=> Fix removal of last account from a business unit

environments/nomis.json
The Nomis team no longer need administrative privillages so returning
them to the developer role.
=> Change NOMIS test account to developer role

cidr-allocation.md
- update cidr-allocation.md with new CIDR range for core-vpc-sandbox
- move sprinkler and cooker applications to use new CIDR space above
=> core-vpc-sandbox-cidr-allocation-update

terraform/environments/core-network-services/transit_gateway_connections.tf
- remove VPC and subnets used specifically for routing workaround
- remove routing tables and entries for routing subnets
- remove FlowLogs for routing VPC
- accept TGW peering request from PTTP Transit Gateway
- update TGW routing tables to use Peering attachment
=> change-routing-configuration-for-tgw-peering

terraform/modernisation-platform-account/iam.tf
The sprinker workflow was failing with:
```
Error: error configuring Terraform AWS Provider: IAM Role (arn:aws:iam::xxxxxxx:role/member-delegation-garden-sandbox) cannot be assumed.
```
This adds the missing resource to the allow statement
=> Add missing sandbox role to member ci

terraform/environments/core-logging/transit-gateway-attachment.tf, terraform/environments/core-security/transit-gateway-attachment.tf, terraform/environments/core-shared-services/transit-gateway-attachment.tf
The attachment has now been moved outside of the module, this removes
an unneeded variable and we tidied up the terraform state.
=> Remove unneeded variable

environments-networks/hmpps-test.json
- update HMPPS NACLs in test environment to allow traffic from
Global Protect VPN through PTTP Transit Gateway
=> alter-HMPPS-ingress-nacls-for-test-env

.github/workflows/core-vpc-development-deployment.yml, .github/workflows/core-vpc-preproduction-deployment.yml, .github/workflows/core-vpc-production-deployment.yml, .github/workflows/core-vpc-test-deployment.yml, terraform/environments/core-logging/locals.tf, terraform/environments/core-logging/monitoring.tf, terraform/environments/core-logging/secrets.tf, terraform/environments/core-network-services/locals.tf, terraform/environments/core-network-services/monitoring.tf, terraform/environments/core-network-services/secrets.tf, terraform/environments/core-security/locals.tf, terraform/environments/core-security/monitoring.tf, terraform/environments/core-security/secrets.tf, terraform/environments/core-shared-services/locals.tf, terraform/environments/core-shared-services/monitoring.tf, terraform/environments/core-shared-services/secrets.tf, terraform/environments/core-vpc/locals.tf, terraform/environments/core-vpc/monitoring.tf, terraform/environments/core-vpc/secrets.tf, terraform/modernisation-platform-account/baselines.tf, terraform/modernisation-platform-account/locals.tf, terraform/modernisation-platform-account/monitoring.tf, terraform/modernisation-platform-account/secrets.tf, terraform/modules/pagerduty-integration/main.tf, terraform/modules/pagerduty-integration/variables.tf
See https://github.com/ministryofjustice/modernisation-platform/issues/1334
We want the GuardDuty, SecurityHub and Config Cloudwatch alarms that are already configured to go to a service on pagerduty and then onto our #modernisation-platform-alarms channel.
Module changes:
Having the data lookups in the module breaks when you move add the
module to an account where the integration key secret data lookups don't
exist.
The change means you pass in the integration key rather than the name of
the integration and makes the module is more flexible.
Closes #1334
=> Integrate existing core alarms with pagerduty

terraform/pagerduty/policy-schedules.tf, terraform/pagerduty/services.tf
We don't currently have an oncall rota so no one is actively responding
to pagerduty alerts, to make the channel less noisy doing the following:
Only loop to escalate to someone once
No secondary schedule
No auto acknowledge (only auto resolve after 4 hours)
This should reduce the number of slack messages we receive.
=> Relax pager duty escalation policy

terraform/pagerduty/services.tf
This warning whilst required for security hub, it triggers everytime we
log in using SSO (which does actually use MFA via GitHub). So
suppressing this.
Note, when using the path it needs to be a CEF field, see here - https://support.pagerduty.com/docs/pd-cef
This are case sensitive and should be lower case.
Suppressed alarms can still be seen in pagerduty they just don't create
incidents or get pushed to the slack channel.
=> Suppress sign-in-without-mfa alarms

source/team/team.html.md.erb, terraform/github/locals.tf
This alphabetises the team, removes @donmasters (👋🏼 good luck in your new role!), adds David Sibley and Scott Seaward (👋🏼 welcome!).
=> Remove Don, add David and Scott to team

source/team-guide/adding-a-new-team-member.html.md.erb
Some very minor contextual adjustments to clarify the need for superadmin role access, and that changes will be made by CI on completion of a PR
=> minor amendments to team onboarding guide for clarity

terraform/environments/core-logging/locals.tf, terraform/environments/core-network-services/iam.tf, terraform/environments/core-security/iam.tf, terraform/environments/core-security/locals.tf, terraform/environments/core-shared-services/iam.tf, terraform/environments/core-shared-services/locals.tf, terraform/environments/core-vpc/iam.tf, terraform/environments/sprinkler/iam.tf, terraform/environments/sprinkler/locals.tf, terraform/modernisation-platform-account/iam.tf, terraform/modules/pagerduty-integration/README.md, terraform/modules/read-only-users/README.md, terraform/modules/read-only-users/main.tf, terraform/modules/read-only-users/outputs.tf, terraform/modules/read-only-users/variables.tf, terraform/modules/read-only-users/versions.tf, terraform/modules/vpc-tgw-routing/README.md
This is for an IT health check.  This adds the testers to the
modernisation platform core account and gives them read only access to
that account and the ability to assume a readonly role in the other core
accounts.
The readonly role is created in the required accounts.
This PR should be reverted and all users and roles removed after the
health check.
Closes #1318
=> Add temporary read only users to core accounts

.github/workflows/scheduled-baseline.yml
When the schedule baselines runs on a schedule, the last job,
secure-baselines isn't running, this runs when you manually trigger it.
I believe it is because of the if statement, the `refs/heads/main` part
of this statement isn't triggered it is not a merge into main as it is
with a PR.  Removing this if statement as it's not needed in any case.
=> Fix secure-baselines not running on scheduled run

source/team-guide/accessing-aws-accounts.html.md.erb
This fixes a formatting error in the references section of the team guidance on accessing AWS accounts
=> added bullet listing to references

environments-networks/hmpps-test.json, terraform/environments/core-network-services/firewall.tf, terraform/environments/core-network-services/transit_gateway_connections.tf
This adds the following:
MP TGW egress route back to NOMIS VNETs
MP Firewall rule to allow traffic from NOMIS VNETs
MP NACLs rules updated to allow traffic from NOMIS VNETs
This initial PR is for database connectivity, we will add further
connectivity in later PRs.
Part of issue #1379
=> Add networking for Azure to NOMIS test

terraform/environments/core-network-services/firewall.tf
It seems that _ is not allowed in firewall group names, changing to -
=> Fix invalid firewall group name

environments-networks/hmpps-test.json, terraform/environments/core-network-services/firewall.tf, terraform/environments/core-network-services/transit_gateway_connections.tf
This adds the following:
- MP TGW egress route back to CP
- MP Firewall rule to allow traffic from CP to MP NOMIS
- MP hmpps-test subnet NACLs rules updated to allow traffic from CP
This initial PR is for database connectivity, we will add further
connectivity in later PRs.
Part of Issue #1383
=> Add networking for Cloud Platform to NOMIS test

terraform/environments/core-logging/s3_logging.tf
This PR solves #1355 - from what I could tell the AWS S3 logging service could not access the KMS key used to encrypt the bucket. I previously investigated switching the bucket encryption to use AWS:SSE instead of AWS:KMS which solved the issue, but in discussion with AWS support found that the principal `logging.s3.amazonaws.com` would also work.
While the documented solution is to switch the bucket to AWS:SSE, I think that allowing the principal access to the logging bucket key is more in line with how we have delivered encryption to logging buckets.
=> added logging.s3.amazonaws.com to kms principals

terraform/modules/kms/main.tf
This PR resolves an issue with the creation of KMS keys; namely an invalid principal which was down to a `/` where a`:` was appropriate.
=> replace / with : to fix invalid principal identifier for KMS policy

terraform/modernisation-platform-account/s3.tf
The permissions to read the state buckets were introduced to allow
developers to run plans locally, however, they only need access to the
top level state file and the member environment state files for this.
=> Decrease scope of permissions for state bucket

terraform/modernisation-platform-account/providers.tf, terraform/modules/dns-zone/versions.tf
Incidents like this - https://moj-digital-tools.pagerduty.com/incidents/Q38DC32KBA0XF3
are caused due to terraform trying to check supported EC2 platforms when
it doesn't have permission in these regions.  We don't need to do this
for these regions so skipping this check to quieten down the alarms.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs
Similar to https://github.com/ministryofjustice/modernisation-platform/pull/1329
=> Fix uneeded alarm regarding api calls

policies/networking/core-vpc.rego, policies/networking/core-vpc_test.rego, policies/networking/expected.rego, scripts/tests/validate/run-opa-tests.sh
After refactoring the networking code to remove the need to manually
assign protected and transit gateway subnets, adjustments to these tests
were missed.  Also fixing the call as the jq was looking for no existent
keys now.
=> Delete unneeded OPA tests

source/team-guide/adding-collaborators.html.md.erb, source/user-guide/running-terraform-plan-locally.html.md.erb, terraform/environments/bootstrap/delegate-access/iam.tf, terraform/modernisation-platform-account/iam.tf, terraform/modernisation-platform-account/s3.tf
These permissions are required to enable collaborators with developer
access to run terraform plans locally.
=> Add permissions needed to run plans as collab dev

terraform/environments/bootstrap/delegate-access/iam.tf, terraform/modules/iam_baseline/main.tf
This PR exists to tighten what the CICD user can do. We had a recent case where a team was able to create and add a role policy to the CICD user but not remove it. We probably don't want to allow the unexpected expansion of what the CICD user can do, so this PR adds a statement preventing the CICD user from making changes to itself (eg, attaching extra role policies).
=> Restrict permissions of CICD user

terraform/environments/bootstrap/delegate-access/iam.tf, terraform/environments/core-network-services/acm-pca.tf, terraform/environments/core-network-services/providers.tf, terraform/environments/core-network-services/versions.tf, terraform/environments/core-vpc/vpc.tf, terraform/modules/pagerduty-integration/versions.tf, terraform/modules/vpc-hub/versions.tf
* Adds a handful of exclusions for wildcards
* Refactors some exclusions
* Adds a public access block to control access to ACM:PCA bucket based on [AWS Guidance](https://aws.amazon.com/about-aws/whats-new/2021/05/aws-certificate-manager-private-certificate-authority-supports-storing-crls-in-private-s3-buckets/)
* Refactors configuration for ACM bucket to be compliant with v4.0 of Terraform AWS Provider
* Sets AWS provider to use only releases in the v4.x train
=> Resolve tfsec errors

terraform/environments/core-network-services/transit_gateway_connections.tf
This PR widens the range of addresses being routed from the ModPlatform TGW to the PTTP TGW for PSN endpoints
=> Widen route to PSN on TGW

terraform/environments/bootstrap/single-sign-on/main.tf
This role allows read only access and enables the user to log support
tickets with AWS.
This is designed to be used as a daily troubleshooting role, rather than
full admin access.  We want to avoid using admin access where possible
as it make accidental or deliberate click ops possible.
Over time we can add more permissions to this role if we feel we need
them. This is part of a longer term strategy to only use admin role as
breakglass emergency roles.
=> Add Modernisation Platform Engineer role to SSO

terraform/environments/core-shared-services/iam.tf
This adds a new role to give readonly permissions, EC2 image builder
imaage start permissions and support read only permissions to any users
in accounts in the modernisation platform organisational unit.
This is required to enable members to start and troubleshoot their image
builder pipelines.
=> Add role for shared services account

environments-networks/hmcts-development.json
These NACL changes were implemented in preprod and prod and now need to 
be done in development as the majority of testing is being done there.
=> Add NACL rules to allow inbound traffic

source/team-guide/deleting-an-environment.html.md.erb, terraform/environments/scp_mp_core.tf, terraform/environments/scp_mp_member.tf, terraform/environments/scp_mp_member_unrestricted.tf
This is now implemented at the P&A level so inherited from therefore no
longer required at this level. Updating the userguidance as well to
reflect this.
(also fixed a typo)
Closes #1324
=> Remove MP OUs SCP prevent root access policy

policies/collaborators/collaborators.rego, terraform/environments/bootstrap/delegate-access/iam.tf
ITHC team for Xhibit portal have said they need this role to perform
their tests.
Closes #1481
=> Add security audit role to collaborator roles

terraform/environments/bootstrap/delegate-access/iam.tf
This is a temporary solution to get Xhibit Portal ITHC ready for Monday.
=> Add RDP permissions to security audit role

collaborators.json
This temporarily fixes an issue with the OPA tests for collaborators.json
When a field is picked up as empty, the field fails a test condition. However, we don't always know if we will be supplied with a github username. As a temporary measure I've added comments into these fields
=> added stub github usernames where not supplied

collaborators.json, environments-networks/hmpps-test.json
This will allow the hmpps-test general data subnet to make a connection
to the FixNGo estate via the Azure landing zone on port 1521.
(Added missing username to fix the failing test)
=> Add rule to allow outbound traffic to 1521 ALZ

terraform/environments/core-network-services/firewall.tf
Allowing the return traffic from the MP Nomis call to 1521 on Azure
Nomis.
=> Open firewall for Azure Nomis ->MP Nomis return

terraform/modernisation-platform-account/s3.tf
After a conversation with DavidE, we decided that access logging is ONLY needed for "Modernisation Platform (modernisation-platform-terraform-state)" while none of the following requires access logging enabled:
Core Logging Production (athena-CloudTrail-query)
Modernisation Platform (aws-athena-query-results-946070829339-eu-west-2)
Core Security (CloudTrail--replication20210429142113322300000005)
Modernisation Platform (config-20201009133419819400000001)
Core Logging Production (config-20201120153025006600000007)
Core Network Services (config-20201120153521856000000007)
Core Security (config-20201120154030575300000007)
Core Security (log-bucket-replication20210429142053929700000004)
false alarm - Core Logging Production (modernisation-platform-logs-CloudTrail)
Core Logging Production …
=> Enable access logging for the terraform state bucket

scripts/git-create-environments.sh, scripts/provision-member-directories.sh, scripts/provision-terraform-workspaces.sh
We initially set up the modernisation-platform-environments repo to
include automation for generating terraform for the unrestricted member
accounts. However as time goes on and we are applying updates to code,
we are finding that no one is using this code, and also as they have
full access to the accounts, they are able to do things that break the
infrastructure that we're trying to automate.
Therefore we have decided to remove all member automation for the
unrestricted accounts, these will be soley managed out side of the
platform.  Our efforts will be focused on moving these to member
accounts if that is sensible rather than trying to do a hybrid approach.
=> Remove automation for terraform in unrestricted accounts

terraform/environments/equip/data.tf, terraform/environments/equip/locals.tf, terraform/templates/data.tf, terraform/templates/locals.tf
On new account creation of Equip discovered that the data sources won't
work until the networking ram share step has been run, but this can run
with the data sources uncommented so fails.  Commenting out the
data sources, these can be uncommented as needed by application teams.
Also removed the DNS configuration, this depends on a resource which
doesn't exist yet.  I've opened a new issue to look into how we make DNS
easier for users (#1544)
=> Fix template to work with networking

terraform/modules/vpc-hub/main.tf
The restriction of all traffic to and from 0.0.0.0/0 caused the
core-shared-services calls to S3 Gateway endpoints to fail.  This is
because S3 Gateway endpoints use public IPs (even though the traffic is
routed privately
https://docs.aws.amazon.com/AmazonS3/latest/userguide/privatelink-interface-endpoints.html)
This change adds in rules to allow outgoing traffic to port 443, and
incoming traffic from S3 (on ephemeral ports
https://aws.amazon.com/premiumsupport/knowledge-center/connect-s3-vpc-endpoint/#Network_ACL_rules)
=> Allow outgoing traffic on 443

.github/workflows/core-shared-services-deployment.yml
The core shared services account creates a key per business unit which
is shared to the accounts for that business unit. The TF pulls these
accounts from the environments secret, but this only happens when the TF
is run. This will ensure when new accounts are added to the
modernisation platform, the core-shared-services workflow runs again
getting the latest account numbers.
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
=> Trigger core-shared-services workflow on new account

.github/workflows/generate-dependabot-file.yml, scripts/generate-dependabot-file.sh
Currently everytime we add a new terraform folder, we have to manually
add the dependabot entry (which we mostly forget to do).  This action
and script will update the dependabot file weekly, to ensure it is up-to-date.
=> Add automation to generate dependabot file

.github/workflows/add-issues-to-project.yml
The standard token doesn't have enough permissions to run the action,
attempting to see if it works when adding additional permissions.
=> Add permissions to token

.github/workflows/add-issues-to-project.yml
For some bizzare reason the permissions on the standard token do not
cover projects which are considered org level. So using our ci user
token which has the required permissions.
=> Switch from using standard token to PAT

source/index.html.md.erb, source/runbooks/disaster-recovery.html.md.erb, source/runbooks/general-incident.html.md.erb
We need to ensure all platform engineers know what to do when there is
an incident.  We can add more runbooks on how to resolve specific
incidents as we go and learn what sort of things cause incidents and how
to resolve them.
=> Add disaster recovery + incident management runbooks

terraform/modules/iam_baseline/main.tf
This is to allow cicd-member-user accessing information about EC2
instances running under the member account
=> Add EC2 readonly policy to member cicd user

terraform/environments/bootstrap/delegate-access/iam.tf
in order to query loadbalancer access logs
=> Athena permissions are required to build a database

scripts/provision-environment-directories.sh, terraform/templates/data.tf
These data sources were causing issues in the inital networking setup as
they didn't exist yet so they were commented out temporarily.
This uncomments them and just doesn't copy them now to the main repo
where the networking runs.
Closes #1608
=> Remove need to uncomment data files

terraform/environments/bootstrap/delegate-access/iam.tf
The database is required to be able to query loadbalancer access logs
=> Glue permissions are required to create an Athena db

terraform/github/main.tf, terraform/github/modules/repository/main.tf, terraform/github/modules/repository/variables.tf
We are creating more and more modules, with many additional things such
as terradocs, SCA, dependabot etc that is not included with the standard
MoJ repo.
This will make it quicker and more consistent to build
=> Add a new template repository for terraform module

terraform/modernisation-platform-account/iam.tf
In order for the environments repo to be able to access pager duty
integration keys the member-ci user needs permissions to this secret.
=> Allow member-ci access to the pagerduty int keys

environments-networks/hmpps-development.json
Allow traffic in to public subnets with a destination port of `tcp:80`.
Primarily added at the request of the Equip team who will redirect calls on `tcp:80` to `tcp:443`.
=> added NACL rule for http traffic in to equip dev

terraform/environments/bootstrap/delegate-access/iam.tf
This role per account allows the AWS Shield advanced SRT (shield response team) to
access data to help troubleshoot and develop mitigations for DDoS
attacks.
See details here - https://docs.aws.amazon.com/waf/latest/developerguide/ddos-srt-access.html
Note, SRT access still has to be manually enabled in the console per
account here https://us-east-1.console.aws.amazon.com/wafv2/shieldv2#/overview
=> Add role for AWS Shield advanced SRT support

environments-networks/hmpps-production.json
* Amends core-vpc-production nACLs to allow traffic out to the internet on `tcp/80` and `tcp/443`
* Amends core-vpc-production nACLs to allow traffic back in from internet on dynamic source port
=> Allow Nomis / HMPPS Production to send traffic to internet

terraform/modernisation-platform-account/iam.tf
to resolve the error:
An error occurred (AccessDeniedException) when calling the GetSecretValue operation: User: arn:aws:iam::<account id>:user/member-ci is not authorized to perform: secretsmanager:GetSecretValue on resource: nuke_account_ids because no identity-based policy allows the secretsmanager:GetSecretValue action
=> Allow the member-ci user to access the nuke_account_ids secret 

config/tech-docs.yml
Remove the .GOV and Alpha which has caused some confusion, added in MoJ
for the main title to clarify that we are part of the MoJ not .GOV UK.
=> Update user guidance to refer to MoJ

scripts/provision-member-directories.sh
The codeowners file for the environments repo is invalid as it doesn't
give the full organisation slug for the team.
Fixing here for future generations and will amend the current file.
=> Add full slug for codeowners template

.github/dependabot.yml, scripts/generate-dependabot-file.sh
* Add some content to `generate-dependabot-file.sh` to find and populate entries for `go` dependencies such as those used in tests
=> updated script to include gomod dependency checks for tests

terraform/environments/core-logging/monitoring.tf, terraform/environments/core-network-services/monitoring.tf, terraform/environments/core-security/monitoring.tf, terraform/environments/core-shared-services/monitoring.tf, terraform/environments/core-vpc/monitoring.tf, terraform/modernisation-platform-account/monitoring.tf, terraform/modules/core-monitoring/README.md, terraform/modules/core-monitoring/main.tf, terraform/modules/core-monitoring/variables.tf
These topics will allow us to push alarms to the pagerduty high and low
priority services.
The code was getting repetitive so drying it out by moving to a module.
=> Add high and low priority SNS alarm topics in core

terraform/environments/bootstrap/delegate-access/iam.tf, terraform/github/main.tf, terraform/github/modules/repository/main.tf
After reviewing with the wider P&A community, there is no desire to
start enforcing signed commits at this stage.
As a team we are happy with only one PR review.
=> Formatting and SCA ignores

terraform/environments/core-network-services/transit_gateway_connections.tf
Adds a new egress route from the live data vpc to the production azure
landing zone for nomis.
=> Add an egress route for nomis production

terraform/environments/bootstrap/delegate-access/iam.tf
The account alias is needed for the aws nuke, part of the sandbox
functionality, it is currently manually added, this change means the
alias will already be present and the manual step can be removed.
The name will follow our account name and workspace naming convention eg sprinkler-development
Closes #1704
=> Add account alias for member accounts

terraform/environments/bootstrap/delegate-access/iam.tf, terraform/environments/bootstrap/delegate-access/locals.tf
Alias are globally unique, there is a chance that another AWS account
has the same naming convention and uses an alias.  This provides and
option to list out alias to skip.
=> Add logic to skip alias if taken

.github/workflows/core-logging-deployment.yml, .github/workflows/core-network-services-deployment.yml, .github/workflows/core-security-deployment.yml, .github/workflows/core-shared-services-deployment.yml, .github/workflows/core-vpc-development-deployment.yml, .github/workflows/core-vpc-preproduction-deployment.yml, .github/workflows/core-vpc-production-deployment.yml, .github/workflows/core-vpc-test-deployment.yml, terraform/environments/core-network-services/monitoring.tf, terraform/environments/core-network-services/providers.tf, terraform/environments/core-network-services/route53.tf, terraform/environments/core-vpc/monitoring.tf, terraform/modules/core-monitoring/main.tf
- Add shield advanced protection to the modernisation-platform hosted
zone
- Add shield advanced to application hosted zones
- Add DDoS monitoring for the above
- Add missing paths to trigger github builds
- Add checkov skips for encrypting sns topics, these do not work with
pagerduty subscriptions if they are encrypted.
=> Add shield advanced and DDoS monitoring to mp zone

terraform/environments/bootstrap/delegate-access/locals.tf
Skip the unsurprisingly not unique testing-test alias
=> Skip testing-test alias

terraform/environments/bootstrap/delegate-access/iam.tf
* Add `dlm:*` to policy document for MemberInfrastructureAccess
=> allow member accounts to make use of data lifecycle manager

.github/workflows/core-vpc-development-deployment.yml, .github/workflows/core-vpc-preproduction-deployment.yml, .github/workflows/core-vpc-production-deployment.yml, .github/workflows/core-vpc-test-deployment.yml, cidr-allocation.md, environments-networks/hq-development.json, environments-networks/hq-production.json, policies/networking/expected.rego
Also add the new security accounts to these subnet sets.
[Modify targeted plan to remove nacls module](https://github.com/ministryofjustice/modernisation-platform/pull/1822/commits/99253ba254c3be8d8c19f1c15830318a11170b98) 
The following error:
```
Error: Invalid for_each argument
on ../../modules/vpc-nacls/main.tf line 32, in resource "aws_network_acl_rule" "open_endpoint_cidrs_for_data_subnets_egress":
32:   for_each = {
33:     for key, data in var.cidrs_for_s3_endpoints :
34:     "${data.name}-${key}" => data
35:   }
├────────────────
│ var.cidrs_for_s3_endpoints is a list of dynamic, known only after apply
```
Comes about as the vpc needs to be created before the data look-up is
valid.  We have come across this before and resolved it by running a
targetted plan, then a targetted …
=> Add HQ VPCs and general subnet sets

terraform/environments/core-network-services/iam.tf
```
Error finding Route 53 Hosted Zone: AccessDenied: User: arn:aws:sts:::assumed-role/read-dns-records/aws-go-sdk is not authorized to perform: route53:ListHostedZones because no identity-based policy allows the route53:ListHostedZones action
```
The above error was occuring on local plans, this is due to the addition
of application hosted zones not being added to the policy.
This changes to give get and list permissions to everything, and for the
write role add in the application zones.
=> Fix failing local plans for dns

terraform/github/main.tf
This will allow other modules to be able to run tests against the
testing-test account.
Also setting the unit tests to be a required check for the S3 bucket.
We should add this to the other modules once tests are in place to
ensure tests are always passing.
=> Add testing keys to module repos

terraform/environments/bootstrap/delegate-access/iam.tf
This will allow developers to turn the bastion on after 9pm or make
emergency changes to scale out the number of instances.
Note any manual changes will be short lived as the next Terraform run will
overwrite any changes with the coded ones.
=> Enable MP collaborator devs to amend autoscaling groups

source/user-guide/our-offer-to-you.html.md.erb
Following on from the risk register, it was highliged that we don't
control members application teams which have access to their
infrastruture.  This updates the offer to make it clear responsibility
for maintaining application github teams is with the application team.
=> Update offer to include Github team reponsibility

environments/ppud.json
We currently don't have a sandbox role for collaborators so it makes
sense to keep this account with developer access.
=> Change ppud access to developer

environments-networks/hmpps-development.json, environments-networks/hmpps-production.json
Removed email endpoint; SMTP mail should flow through email-smtp endpoint.
See support record for context: https://us-east-1.console.aws.amazon.com/support/home?region=eu-west-2#/case/?displayId=10265461951&language=en
=> trimmed endpoint list for hmpps

terraform/environments/equip/data.tf
Fix IAM policy for email user as SID contains spaces which are unsupported
=> amend policy SID to remove spaces

terraform/environments/core-network-services/route53.tf
This record is no longer needed has validation has taken place.
=> Remove uneeded record

scripts/provision-member-directories.sh
The testing account is only used for automated testing.  There is no
reason to have a testing directory generated here.  Adding this line as
the automation kept on trying to create it after we deleted it.
=> Skip testing account for member directories

terraform/modernisation-platform-account/iam.tf, terraform/modernisation-platform-account/secrets.tf
This user has now been replaced by the testing-ci user in the
testing-test account.
=> Remove the testing-ci user from the mp account

terraform/pagerduty/aws.tf, terraform/pagerduty/data.tf, terraform/pagerduty/kms.tf, terraform/pagerduty/locals.tf
* Add new KMS key an alias for pagerduty secret
* Create cross-account access policy for pagerduty secret
* Add cross-account access policy to pagerduty secret
* Create IAM policy for new KMS key
* Attach policy to new KMS key
=> Allow access to pagerduty secret for other accounts

.github/workflows/core-security-deployment.yml, terraform/environments/core-security/versions.tf
Updating to the latest version of TF.  Note the difference in versioning specification.  Tested as follows to prove - 
Terraform version(which checks the version of TF complies):
```
required_version = "~> 0"
using terraform 1.0.1
Plan completes!
```
And obviously...
```
required_version = "~> 1"
using terraform 1.0.1
Plan completes!
```
So to follow up...
```
required_version = "~> 2"
using terraform 1.0.1
Plan fails
```
So for the terraform action version which impacts the installed version of terraform, I tried:
`terraform_version: "~0"`
And that got TF version:
`Terraform v0.15.5`
Then I tried:
`terraform_version: "~1"`
And that got TF version:
`Terraform v1.2.4`
Then I tried:
`terraform_version: "~1.0"`
And got:
`Terraform v1.0.11`
=> Update core security to TF 1.2.4

terraform/environments/core-network-services/transit_gateway_connections.tf
This is needed to allow management instances in the noms-mgmt-live Azure
vnet to connect to Nomis in the production environment.
Also renaming the Nomis routes to match the Azure VNet names to be
clear.
=> Add routes for Azure noms-mgmt-live

environments-networks/hmpps-production.json
This is to allow traffic from the Azure noms-mgmt-live vnet to the
hmpps-production environment.
=> Open NACLs on hmpps-production

terraform/environments/core-network-services/iam.tf
Tests were failing as the testing-ci user did not have permissions to
assume the modify-dns-records role.
=> Give modify dns permissions to testing-ci user

terraform/environments/equip/data.tf, terraform/pagerduty/data.tf
The two warnings here, one is on a policy which is auto generated by SES
and we've just imported it into TF.
The other the condition restricts the access.
=> Ignore SCA warnings

terraform/environments/core-network-services/firewall.tf, terraform/environments/core-network-services/transit-gateway.tf, terraform/environments/core-network-services/transit_gateway_connections.tf, terraform/modules/ec2-tgw-attachment/main.tf
* Prevent important Transit Gateway components from being destroyed inadvertently with `prevent_destroy` lifecycle rules
=> added prevent_destroy to tgw and vpc attachment resources

.github/workflows/publish.yml
Cloud platform is using gem-patches to fix the search issue - https://github.com/ministryofjustice/cloud-platform-user-guide/blob/main/gem-patches/search.js.patch
The latest version of ministryofjustice/tech-docs-github-pages-publisher
comes after this commit making the same gem-patches folder obsolete -
https://github.com/ministryofjustice/tech-docs-github-pages-publisher/commit/6cde709cfd1a900cab3352d36d6e5493c7e11284
so I'm assuming updating will fix the search bar issue.
Closes #1904
=> Update to latest version of publisher

terraform/environments/core-logging/transit-gateway-attachment.tf, terraform/environments/core-security/transit-gateway-attachment.tf, terraform/environments/core-shared-services/transit-gateway-attachment.tf, terraform/environments/core-vpc/transit-gateway-attachment.tf, terraform/modules/ec2-tgw-attachment/main.tf
* Use a `for_each` loop to take multiple tags in for TGW VPC attachments
* Refactor where the attachment module is called to supply both the name, and the local tag values
=> Refactor TGW attachment tagging

terraform/environments/core-network-services/monitoring.tf
* Create a rich list of Transit Gateway attachments matching `is-production:true`
* Use the list of production Transit Gateway attachments to create CloudWatch metric alarms
* CloudWatch alarms will report when `PacketsIn` on an attachment is below `1` for five minutes.
* SNS topic will receive these alarms and pass through PagerDuty integration to `high priority alarms`
* Solves #1988
=> Add Cloudwatch Alarm & PagerDuty integration for TGW Attachments

terraform/environments/core-network-services/monitoring.tf
* `treat_missing_data` for CloudWatch Metric Alarm argument changed to correct case
=> Corrected wrong case in alarm argument

terraform/environments/core-network-services/monitoring.tf
* CloudWatch Metric Alarm dimensions need to state both the TransitGateway ID and the VPC attachment ID in order to correctly read the metric for review.
=> Correct CloudWatch alarm dimensions

terraform/github/main.tf, terraform/github/modules/repository/main.tf
Also change has project to true
This always reverts to true for some org level reason, so if we set it
to false for non core repos we just end up with loads of changes every
time we run this code.
=> Add testing-ci secrets to load balancer module

terraform/pagerduty/locals.tf, terraform/pagerduty/policy-schedules.tf
PagerDuty requires that a user is always assigned to a service, since we
do not want to get low priority notifications, they are assigned to this
user.
The notifications still go through to the slack channel, but this user's
notifications have been removed (so we won't get the emails coming
through)
=> Create generic pagerduty user

terraform/pagerduty/locals.tf, terraform/pagerduty/policy-schedules.tf
Update the on call schedule to start next week.  Add the modernisation
platform user as a base layer, so that there is always someone on call
(you can't have a schedule with no oncall user).  Schedules can be
manually overwritten in pagerduty for holidays etc.
=> Update on call schedules

source/team/operational-processes.html.md.erb
As a team the Modernisation platform generally is an early start team.
Updating the support and on-call hours to reflect this and ensure this
is clear for users.
=> Update on call hours

terraform/modernisation-platform-account/lambda.tf
* Using `abspath()` function forces the provision of the absolute path for the lambda function
=> applied abspath function 

terraform/environments/core-network-services/locals.tf, terraform/environments/core-network-services/transit_gateway_connections.tf
* Add two statically typed lists with `live_data` and `non_live_data` VPCs
* Add data call to create a list of all TGW attachment IDs
* Add data call to create map of all TGW attachment attributes 
* Adds propagation statements to populate route tables with relevant attachments
=> Add TGW propagation statements

terraform/environments/core-network-services/locals.tf, terraform/environments/core-network-services/transit_gateway_connections.tf
While the branch that added static lists for route propagation planned successfully, the application of the branch raised some errors that can be seen in the logs. These appeared to reference the `core-network-services` attachments, and some entries in the resource to populate the firewall route table.
This PR removes those propagation statements and the static lists with related data calls, leaving in place the data calls required to create dynamic lists.
=> remove new propagation statements

terraform/environments/core-network-services/transit-gateway.tf, terraform/environments/core-network-services/transit_gateway_connections.tf
* Solves #1397 
* Amend name tags for two transit gateway route tables to better clarify their purposes
* Programatically retrieve `transit_gateway_attachment_id` and populate two separate local values with the contents
* Add `aws_ec2_transit_gateway_route_table_propagation` statements that use local values for `live_data` / `non_live_data` route tables.
* Add `aws_ec2_transit_gateway_route_table_propagation` statement to give firewall VPC knowledge of all attached VPCs.
* Remove statements superseded by these new propagation statements
=> Dynamic vpc route propagation

terraform/environments/analytical-platform-data/locals.tf, terraform/environments/cooker/locals.tf, terraform/environments/equip/locals.tf, terraform/environments/example/locals.tf, terraform/environments/mi-platform/locals.tf, terraform/environments/nomis/locals.tf, terraform/environments/performance-hub/locals.tf, terraform/environments/ppud/locals.tf, terraform/environments/sprinkler/locals.tf, terraform/environments/tariff/locals.tf, terraform/environments/testing/locals.tf, terraform/environments/threat-and-vulnerability-mgmt/locals.tf, terraform/environments/xhibit-portal/locals.tf, terraform/templates/locals.tf
The Terraform http provider has deprecated the `body` attribute.
This PR will replace `body` with `response_body`.
https://github.com/hashicorp/terraform-provider-http/blob/main/CHANGELOG.md
https://github.com/hashicorp/terraform-provider-http/pull/137
=> update attribute reference following http provider update

terraform/environments/core-vpc/vpc.tf, terraform/modules/vpc-tgw-routing/main.tf, terraform/modules/vpc-tgw-routing/variables.tf
This removes the creation of static routes in the relevant `live_data` / `non_live_data` route table as well as the `firewall` route table. These routes are now supplied through dynamic propagation, so the static routes are no longer required.
=> remove creation of static TGW routes from vpc-tgw-routing module

scripts/setup-baseline.sh, scripts/terraform-init.sh, scripts/terraform-plan.sh, terraform/environments/bootstrap/delegate-access/locals.tf
* Use `sort()` function to ensure list of skipped aliases is always presented consistently
* Removed `set -x` where used for debugging
=> updated skip-locals list, removed set -x from scripts

terraform/templates/data.tf, terraform/templates/locals.tf
Bug identified when creating accounts - the necessary data calls were 
not present in the locals file in the modernisation platform member 
accounts upon account creation. This PR moves the necessary data calls 
back to the locals.tf from data.tf
=> Add environments_file and OU root account data calls to locals.tf

terraform/modules/kms/main.tf
Discovered that, in some situations, `kms:ListGrants` was required for use of per-business-unit KMS keys.
https://github.com/hashicorp/terraform-provider-aws/issues/4141#issuecomment-506216964
=> added missing KMS permission

terraform/environments/bootstrap/delegate-access/iam.tf, terraform/environments/core-network-services/iam.tf
Reverts ministryofjustice/modernisation-platform#2091
Does so as this breaks two automated steps due to invalid principals:
https://github.com/ministryofjustice/modernisation-platform/runs/7765852215#step:4:494
https://github.com/ministryofjustice/modernisation-platform/runs/7765848186#step:6:57
=> Revert "OIDC provider permissions"

source/runbooks/deleting-an-environment.html.md.erb
* Referenced script no longer exists, so references have been removed
* Updated reference to documentation for account deletion as an Organization-centric view is not necessarily appropriate; an account can be deleted without that access as a root user
=> Update on account deletion process

terraform/environments/bootstrap/delegate-access/iam.tf, terraform/environments/bootstrap/delegate-access/locals.tf, terraform/environments/bootstrap/delegate-access/versions.tf
* Adds github-oidc module to `delegate-access` step, ensuring that required resources are provisioned when accounts are created.
=> OIDC for all member accounts

terraform/modernisation-platform-account/s3.tf
The access logs bucket currently doesn't work, this is due to AES256 not
being available in the module for the target bucket (fixed) and a deny
policy preventing any aws:SecureTransport false traffic.  We don't want
to remove this policy, so access log buckets will need to be created
manually or we add the full code to the S3 bucket module with a flag, eg
enable_access_logs which will create everthing.
Having compared the differences in the logs verses what we get with
cloudtrail here - https://docs.aws.amazon.com/AmazonS3/latest/userguide/logging-with-S3.html
We don't need the additional logs for the state bucket.  We will
re-address this if a user needs it.
=> Remove S3 access bucket logging for state bucket

terraform/environments/bootstrap/delegate-access/iam.tf, terraform/environments/bootstrap/delegate-access/locals.tf
* Resolve issue where `application_environment` is incorrectly created for legacy accounts
* Ensure only `member` type accounts are provided with Github OIDC resources
=> Make Github OIDC conditional based on member type

terraform/environments/core-network-services/iam.tf
* Fixes previous version where two conditions were applied, but conditions must exist in one condition block
=> correctly populate IAM statement conditions

terraform/environments/core-network-services/iam.tf
* Correctly concatenates the two condition operators used for securing wildcard access to the `modify-dns-rule`
=> Correctly state condition keys for IAM Policy

source/user-guide/accessing-ec2s.html.md.erb
New bastion is re-created on daily basis. The result is that when the user SSH to the bastion, he/she has to remove the old host key from known_hosts every time bastion is reset:
```
ssh sprinkler-sandbox-bastion
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:EFrOMMDrFFu37+1oISNRxSvKRKM+XhYg1qVpTaeQlas.
Please contact your system administrator.
Add correct host key in …
```
=> Resolve the bastion host key change warning

source/user-guide/accessing-the-aws-console.html.md.erb, source/user-guide/creating-resources.html.md.erb, source/user-guide/deploying-your-application.html.md.erb, source/user-guide/getting-aws-credentials.html.md.erb, terraform/environments/bootstrap/delegate-access/iam.tf
* `modernisation_platform_account_id` reference updated to reflect where it sits in the json
=> amended how modernisation platform account ID is referenced

policies/collaborators/collaborators_test.rego, policies/environments/environment-definitions.rego, policies/environments/environment-definitions_test.rego
A recent error when creating an environment could have been avoided with
better validation of the json file.  This test should prevent the same
thing happening again.
=> Add new OPA test to check valid Access level

terraform/github/locals.tf
Having Christine included now that she's left the team meant that terraform apply runs were failing
=> remove Christine Elliot from members list 

terraform/environments/core-network-services/firewall.tf, terraform/modules/vpc-hub/main.tf
EC2-Classic networking has been retired and references to it have been
deprecated in the AWS provider -
https://github.com/hashicorp/terraform-provider-aws/issues/23625
This change fixes deprecation warnings we started getting -
```
Warning: Argument is deprecated
with module.vpc.aws_vpc.default,
on ../../modules/vpc-hub/main.tf line 105, in resource "aws_vpc" "default":
105:   enable_classiclink             = false
With the retirement of EC2-Classic the enable_classiclink attribute has been
deprecated and will be removed in a future version.
```
=> Remove classic link options

.github/workflows/core-shared-services-deployment.yml, terraform/modules/kms/main.tf
After looking at the KMS CreateGrant permission issue where the
developer role didn't have the correct permissions to create grants, it
appears this policy at present is to open, allowing grants to be created
for things other than AWS resources, see documentation here -
https://aws.amazon.com/premiumsupport/knowledge-center/kms-iam-ec2-permission/
=> Restricting what KMS grants can be created for

terraform/environments/bootstrap/delegate-access/iam.tf
In order to start instances with EBS volumes encrypted with shared KMS keys, developers need to be able to create a grant to the instance.
Adding this permission to the dev role along with a restriction on the types of resources that can get the grant.
For reference: https://aws.amazon.com/premiumsupport/knowledge-center/kms-iam-ec2-permission/
=> Adding CreateGrant permission to dev role for shared keys

terraform/modernisation-platform-account/iam.tf, terraform/modernisation-platform-account/locals.tf
This is for the github-actions role within the member SSO accounts to be able to assume this githubreadonly role to make the initial OIDC request through the AWS provider.
This will enable us to get things from the main mp account when using
github actions role from the local account or when using the superadmin
role when running locally
=> Create assumable role githubreadonly with managed policies

terraform/environments/bootstrap/delegate-access/iam.tf
This is required for decrypting the state bucket. The state bucket KMS key has not be specified as a resource as you cannot use the alias in the policy, and we don't want to hard code the key ARN.
Adding the githubReadOnly role and fixing the member delegation role.
=> Add permission for OIDC role to decrypt KMS

.github/workflows/new-environment.yml, terraform/environments/main.tf, terraform/environments/secrets.tf, terraform/environments/variables.tf
In order to not hard code account numbers, Github needs access to the map of account names to account numbers in the environemnt management json.
=> Add environment management info to Github

terraform/environments/secrets.tf
The token we had didn't have permissionst to add organisation level secrets so it failed on merge.  Attempting this time to add a repo level secret.
=> Change method of adding secret

terraform/environments/bootstrap/delegate-access/iam.tf
This line is referring to the role itself, it does not need to assume itself.
=> Remove uneeded policy line

terraform/environments/bootstrap/delegate-access/iam.tf
Sprinkler and cooker were created as development accounts, so have development as the environment and platforms as the business unit.
They have since been used to test the vpc sandbox so actually are sandbox environment and garden and house business units respectively.
All this means is that logic to restrict what role the github-actions role can assume gives the incorrect business unit and environment.
The options to get this to work are:
1. Rebuild sprinkler and cooker from scratch with new accounts with the sandbox environment, however this will also need an exclusion from the opa tests otherwise we'll have to have sandbox as a valid environment which we don't want.
2. Don't have sprinkler and cooker run using the same workflows as everything else, which would then be hard to make sure …
=> Horrible hackiness to get sprinkler and cooker to work

terraform/modules/vpc-nacls/data.tf, terraform/modules/vpc-nacls/main.tf
`from_port` and `to_port` values were not being supplied when creating subnet static rules. As we were providing a `protocol` value of `-1` at first, this was fine because no `from_port` or `to_port` was required. However, when we added egress/ingress rules for HTTPS traffic out from subnets, these new rules were created without ports and thus did not work as expected.
This PR adds a conditional value to supply a port value is one is present, or `null` if not value is supplied / required
=> Properly populate port ranges for subnet static rules

environments/refer-monitor.json, policies/networking/core-vpc.rego, terraform/github/locals.tf
`nacl` in the network definition json is not required any longer since the refactoring done last sprint.
=> Removing interventions-reporting-discovery as not a MOJ team.

terraform/github/main.tf
Remove the obsolete repository modernisation-platform-terraform-lambda-scheduler-stop-start If I recall correctly, we originally created this repository in order to maintain a fork of the third party repository https://github.com/diodonfrost/terraform-aws-lambda-scheduler-stop-start Since we could not trust third party code to use it directly, the idea was to use a fork.
=> Remove the obsolete repository lambda-scheduler-stop-start

terraform/github/main.tf, terraform/github/modules/repository/variables.tf
The default was set to module, which although most repos will be modules, it is not intuitive that the default would not be the basic repo template.  Also explicitly setting the type for each repo so that it's clear to others going forward.
=> Tidy up repo type and change default

terraform/modules/kms/main.tf
Slack thread for context: https://mojdt.slack.com/archives/C01A7QK5VM1/p1663335087474439
There's currently a limitation set on shared KMS keys which block "kms:CreateGrant" action when the grantee principal is not an AWS service.
However, this prevents the destination accounts from using images encrypted with shared keys from using those images in autoscaling groups because, as outlined [here](https://docs.aws.amazon.com/autoscaling/ec2/userguide/key-policy-requirements-EBS-encryption.html), this requires an intermediary grant, to a role in the destination account.
This change adds "kms:CreateGrant" permission to all member account roots but adds an explicit deny which blocks the action unless the principal grantee is either an AWS service OR the the AWS service role for autoscaling. This …
=> Fixing KMS Create Grant permissions on cross-account shared keys.

terraform/environments/core-network-services/transit_gateway_connections.tf
Since we are refactoring the firewall soon it makes no sense to spend time figuring out rules now, especially since LAA are in the early stages and wide ranges would likely be used in any case.
=> Skip the firewall for LAA traffic

terraform/environments/core-logging/athena.tf, terraform/modernisation-platform-account/lambda.tf
We have strict controls already in place to ensure only code deployed to lambda only goes through GitHub with an approval.  We do not need extra code signing for lambda.
=> Ignore code signing for lambda

terraform/environments/bootstrap/delegate-access/iam.tf
Reverts ministryofjustice/modernisation-platform#2352
Testing completed. 
- github-actions is able to amend the policy that attaches to the role
- MemberInfrastructureAccess is unable to delete the OIDC provider.
=> Revert "Add temporary permission to github-actions policy to test SCP. #2111"

.github/workflows/scheduled-baseline.yml
If this module is modified then the scheduled baselines will need to run again to deploy the changes.
=> Trigger scheduled baselines when iam module update

terraform/environments/bootstrap/delegate-access/iam.tf
This is to allow testing-ci user to assume the role to test OIDC provider module.
=> Adding testing-ci user to the trust for the ModPlatformAccess role

terraform/environments/core-network-services/transit_gateway_connections.tf
* Refactors the regex used to select TGW attachments for consistency with the `vpc-nacls` module
* Removes some VPC attachment propagations as these are present in either `aws_ec2_transit_gateway_route_table_propagation.propagate_live_data_vpcs` or `aws_ec2_transit_gateway_route_table_propagation.propagate_non_live_data_vpcs`
* Replaces a hard-coded reference to a TGW attachment with one based on a data call
* Includes some small linting / formatting fixes
=> Begin TGW Code cleanup

.github/workflows/templates/workflow-template.yml, terraform/templates/locals.tf, terraform/templates/member-providers.tf, terraform/templates/platform_secrets.tf
Changes:
.github/workflows/templates/workflow-template.yml
- AWS secrets env vars have been removed
- plan and deploy jobs have been amended to use a different AWS authentication action
- plan and deploy jobs have been refactored to use the new matrix strategy to improve code quality
templates/providers.tf
- changed provider definition to use oidc
- amended local plan provider definitions for compatibility
templates/platform_secrets.tf
- changed secret definitions to allow retrieval from modernisation-platform account
- removed commented out section as changes to secrets are no longer required to run local plans
templates/locals.tf
- added a datasource to lookup OIDC session information
- added a new local to retrieve the account id of modernisation-platform account (using a datasource …
=> Convert templates for OIDC and matrix workflow. #2039 #2350

terraform/environments/core-network-services/transit_gateway_connections.tf
Temporarily populate TGW external route table with values for all connected VPCs.
=> add route propagations to external-in TGW route table

source/user-guide/running-terraform-plan-locally.html.md.erb
Updating local terraform plan instructions to remove `platform_secrets.tf` as that is now the same for GHA and local runs.
=> Updating local plan docs in line with OIDC changes #2030

terraform/environments/core-vpc/vpc.tf
* Update reference to `modernisation-platform-terraform-member-vpc`
* Remove reference in `environments/core-vpc` to local TGW routing module as this is now handled by the `modernisation-platform-terraform-member-vpc`
* Remove redundant code elements
This PR will require approximately two runs to successfully complete, allowing a five minute interval for AWS API actions to take place, based on observations in sandbox environment
=> Apply default routes via TGW in VPC module

terraform/environments/bootstrap/delegate-access/iam.tf
Checking to make sure OIDC provider exists in an account before trying to add github-actions role to the trust policy for Platform Access role.
=> Check additional trusts for OIDC provider

terraform/environments/core-network-services/firewall.tf, terraform/modules/vpc-hub/README.md
* Enable `appliance_mode` support for the Inspection VPC attachment
* More information on the implications of this change can be found [here](https://docs.aws.amazon.com/vpc/latest/tgw/transit-gateway-appliance-scenario.html#:~:text=vpc%2Dattachment%20command.-,Stateful%20appliances%20and%20appliance%20mode,-When%20appliance%20mode).
In brief, `appliance_mode` ensures that traffic flows stay within an AWS availability zone ensuring that the statefulness of flows is observed by the same endpoint.
=> Enable appliance mode for Inspection VPC attachment

terraform/environments/core-shared-services/iam.tf, terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf
Plan: 4 to add, 0 to change, 0 to destroy.
aws_iam_role.instance-scheduler-lambda-function: Creating...
Error: error creating Lambda Function (1): InvalidParameterValueException: Source image instance-scheduler-ecr-repo:latest is not valid. Provide a valid source image. {
RespMetadata: {
StatusCode: 400,
RequestID: "a1f03d5c-f72b-4e7e-a923-7858e8970475"
},
Message_: "Source image instance-scheduler-ecr-repo:latest is not valid. Provide a valid source image.",
Type: "User"
}
=> Fix image_uri issue.

.github/workflows/format-code.yml, terraform/environments/bootstrap/delegate-access/iam.tf, terraform/environments/bootstrap/delegate-access/locals.tf, terraform/environments/core-network-services/iam.tf, terraform/modernisation-platform-account/s3.tf
Giving AdministratorAccess SSO role enough permissions to run `terraform apply` in modernisation-platform-environments
- Permission to assume MemberInfrastructureAccess
- Permission to assume ModernisationPlatformAccess
- Permissions to write to the state s3 bucket
- Permissions to assume modify-dns-records roles in core-vpc accounts
=> Using SSO credentials instead of superadmin

terraform/environments/core-shared-services/iam.tf, terraform/modernisation-platform-account/secrets.tf
This is needed so that the instance scheduler lambda function that runs within the core-shared-services-production account can access the secret.
=> Create a resource share for the environment management secret

terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf
Those are provided within the Docker image and throw an error if specified in the resource where package type is Image
=> Removing handler and runtime from lambda function

terraform/environments/core-network-services/transit_gateway_connections.tf
As per #2375, this PR amends the routes for Nomis for live VPCs (`production` / `preproduction`).
Also, the order of the routes has been amended somewhat. It's not exactly alphabetised, but the routes are mostly in order (private routes, public routes, in numerical order)
=> Update TGW routes for Nomis

terraform/environments/bootstrap/delegate-access/iam.tf
This allows the core-shared-services github-actions role to update lambda code when a new version of the image is released.
=> Allow lambda updates in core-shared-services

terraform/environments/bootstrap/delegate-access/iam.tf, terraform/environments/bootstrap/delegate-access/locals.tf, terraform/modernisation-platform-account/locals.tf, terraform/modernisation-platform-account/s3.tf
Linked Issue: https://github.com/ministryofjustice/modernisation-platform/issues/1859
After a steer from Dave E, a new way forward is to use the MP AdministratorAccess role for modernisation-platform repo local plans and applies. 
To enable this:
- Allow MP AdminstratorAccessRole permission to assume ModernisationPlatformAccess roles
- Give MP AdministratorAccessRole permissions to write to the accounts folder in state file bucket.
Housekeeping:
- Bump cross-account module version (has been tested in cooker, example and sprinker)
Additional relevant PR:
https://github.com/ministryofjustice/aws-root-account/pull/612
=> Adjust permissions and add resources to enable SSO plans/applies

terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf
Skip the accounts ccms-ebs-development maatdb-development from instance scheduling until the feature is tested
=> Skip the accounts from instance scheduling

terraform/modules/firewall-policy/main.tf
Use nested functions to create what ought to be syntactically correct names for the `aws_networkfirewall_policy` and `aws_networkfirewall_rule_group` resources
=> Correctly format firewall rulegroup & policy names

terraform/modules/firewall-policy/main.tf
Both the policy and rule group need a reference to "STRICT_ORDER" in order to make use of top-to-bottom parsing of rules.
=> amend rule order to match API requirements

terraform/environments/bootstrap/delegate-access/iam.tf, terraform/environments/core-shared-services/iam.tf, terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf
- Move core-shared-services OIDC provider to environments/core-shared-services
- Removing the uneeded try statement.
=> Migrating core-shared-services OIDC provider to environments/core-shared-services

terraform/modules/vpc-hub/main.tf
The retention period was not set which goes against the 2 year maximum defined in the security guidance.
=> Set retention period for vpc flow logs

terraform/environments/core-shared-services/iam.tf
The lambda role needs to be assumable by GH actions role.
=> Adding GH actions role principal to the lambda function role policy document

source/index.html.md.erb, source/user-guide/how-to-use-shared-kms-keys.html.md.erb, terraform/templates/data.tf
Also adds the required data sources to the data.tf, so users don't need to add this themselves.
A further PR to add this data to the existing environments in the environments repo will be required.
=> Add documentation for shared KMS keys

terraform/modules/firewall-policy/main.tf
Without an explicit `create_before_destroy` lifecycle statement, terraform will try to destroy the existing network firewall rule group, and fail as the rule group cannot be destroyed while in use. This should change the behaviour to create a new rule group, replace the original rule group, and then delete the original resource
=> Resolve issue with replacing FW rule group

scripts/internal/get-security-hub-findings/main.go
Inspector has new lines in the title for some findings, which causes issues when importing the findings to a Google sheet.
=> Fix issue with new lines

terraform/environments/core-shared-services/iam.tf
Add "kms:CreateGrant" to instance scheduler role to try fixing the issue
State transition reason: Server.InternalError
State transition message: Client.InternalError: Client error on launch
=> Add "kms:CreateGrant" to instance scheduler role

terraform/environments/bootstrap/delegate-access/iam.tf
Try removing the "kms:CreateGrant" permission and verify if lambda can start sprinkler-db-mgmt-server
=> Try removing kms:CreateGrant

terraform/environments/bootstrap/delegate-access/iam.tf
Instance Scheduler needs kms:CreateGrant permissions to manage encrypted ebs volumes. The grantee in this instance is the EC2 service, so it's possible to lock the permission down using `kms:GrantIsForAWSResource` condition.
=> Restrict CreateGrant permission in instance scheduler role

.github/workflows/core-network-services-deployment.yml, .github/workflows/core-vpc-test-deployment.yml
Refactoring the following workflows to use GH actions OIDC for AWS credentials:
- core-vpc-test-deployment (I have missed it in the previous PR)
- core-network-services-deployment
Additionally, improving workflow code readability by adding some consistency and spacing.
=> OIDC refactor in core-vpc-test-deployment and core-network-services-deployment workflows

terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf
Enable Instance Scheduling for remaining accounts except xhibit-portal-development,xhibit-portal-preproduction,nomis-development,nomis-test,nomis-preproduction,apex-development,ccms-ebs-development,maatdb-development,mlra-development,
The accounts that will be enabled are: oasys-development,data-and-insights-wepi-development,testing-test,oasys-preproduction,tariff-development,delius-iaps-development,ppud-development,refer-monitor-development,digital-prison-reporting-development,oasys-test,threat-and-vulnerability-mgmt-development,
=> Enable Instance Scheduling for remaining accounts except some

terraform/environments/bootstrap/delegate-access/iam.tf, terraform/environments/core-shared-services/ecr_repos.tf
In order to run terratest on the lambda module, `testing-test` needs some additional permissions:
* pull an image from ECR repo
* Assume the InstanceSchedulerAccess role
=> Adding testing-test permissions to pull from ecr and assume lambda scheduling role.

terraform/environments/bootstrap/delegate-access/iam.tf
As the terratest will run in the testing-test account and assuming the role in testing-test account, an explicit change to the role trust policy isn't needed.
Will achieve the same by adding an sts:AssumeRole permission to the role policy in the test code instead as per https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html#:~:text=To%20allow%20a,role%27s%20trust%20policy.
=> Reverting the change in trust policy for InstanceSchedulerAccess

environments/digital-prison-reporting.json
Agreed with the DPR team to switch to a sandbox environment and disable auto-nuke for the remainder of the PoC period (Dec 2022).
This will enable them to finish the PoC quicker.  Either sandbox to be removed or auto-nuke to be re-enabled after this time.
=> Change DPR to sandbox account

source/concepts/sdlc/user-workflow.html.md.erb
- removing a reference to ci user that's been replaced by OIDC
- adding more detail to who can approve PRs.
=> Fixing AWS user refs & adding detail to PR approvals

.github/workflows/scheduled-baseline.yml
https://github.com/ministryofjustice/modernisation-platform/actions/runs/3435363726/attempts/1
The above run failed because the token expired before the job could complete. I'm seeing runtimes of between 45 and 55 minutes fairly regularly. Splitting them out is a clean way of fixing without adjusting token TTL which isn't needed for anything else.
=> Secure baselines plan+apply taking ~60m, running up against token expiration.

source/runbooks/removing-a-team-member.html.md.erb
See the PR here - https://github.com/ministryofjustice/moj-terraform-scim-github/pull/36
So we no longer need to manually remove users.
=> SSO removal now happens in SCIM

terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf
Instance Scheduler automatically skips non-member accounts lacking the InstanceSchedulerAccess role. This PR is to explicitly skip those to avoid additional warnings in the logs and as a safety precaution.
=> Explicitly skip non-member accounts from Instance Scheduling

terraform/environments/core-network-services/monitoring.tf
Our current alarms alert if one datapoint is missed, or polls as `0`, in a 5 minute window. The net effect of this is that in any rolling five minute window an alert can trigger if no traffic is detected. Our goal with these alerts was to warn us if a major even occurred in a VPC (such as a routing change or ACL / security change) stopped traffic flowing through the Transit Gateway. The alert is so sensitive that so far we've only had one situation where the alert has been legitimate.
=> Decrease alert sensitivity

terraform/github/locals.tf
Removing write access for ops eng team to MP module repositories, as they have removed themselves manually already.
Additionally, they do not have accounts in our platform anymore.
=> Removing write access for ops eng team to MP module repositories

source/concepts/environments/backups.html.md.erb
The guidance assumed only a small number of things where backed up, in reality we have opted in for everything possible.
=> Amend backup guidance to reflect what is backed up

terraform/github/modules/repository/main.tf
Following the GitHub guidance, adding tag protection as detailed here:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules
Tag protection rules contributors from creating or deleting tags unless they have the admin write permission.
=> Adding tag protection to github repositories

.github/workflows/scorecards.yml
Adding OSSF as recommended in the GitHub security hardening guidance here - https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-openssf-scorecards-to-secure-workflows
=> Add OSSF scanning

.github/workflows/add-issues-to-project.yml, .github/workflows/documentation.yml, .github/workflows/format-code.yml, .github/workflows/generate-dependabot-file.yml, .github/workflows/labeler.yml, .github/workflows/new-environment-files.yml, .github/workflows/new-member-environment-files.yml, .github/workflows/opa-policies.yml, .github/workflows/terraform-pagerduty.yml, .github/workflows/terraform-static-analysis.yml, terraform/modules/firewall-policy/README.md
Restricting in line with GitHub security hardening guidelines
contents:read vs contents:write
Terraform documenter failed when writing changes to a PR when contents
was set to read.  Assuming that other things that need to write to a PR
also need write permission, adding this in.  After everything is
confirmed as working as is, we can then start changing things to read
and see if they break.
=> Restrict GitHub tokens permissions

.github/workflows/documentation.yml, .github/workflows/format-code.yml, .github/workflows/generate-dependabot-file.yml, .github/workflows/new-environment-files.yml
As best practice write permissions should be at the job level so that any new jobs don't get write permissions as standard.
=> Moving write permissions to job level

.github/workflows/core-logging-deployment.yml, .github/workflows/core-network-services-deployment.yml, .github/workflows/core-security-deployment.yml, .github/workflows/core-shared-services-deployment.yml, .github/workflows/core-vpc-development-deployment.yml, .github/workflows/core-vpc-preproduction-deployment.yml, .github/workflows/core-vpc-production-deployment.yml, .github/workflows/core-vpc-test-deployment.yml, .github/workflows/generate-dependabot-file.yml, .github/workflows/modernisation-platform-account.yml, .github/workflows/new-environment-files.yml, .github/workflows/new-environment.yml, .github/workflows/new-member-environment-files.yml, .github/workflows/publish-gh-pages.yml, .github/workflows/scheduled-baseline.yml, .github/workflows/terraform-github.yml, .github/workflows/terraform-pagerduty.yml, .github/workflows/terraform-static-analysis.yml
Following best practice guidance, pinning this to a commit hash.
See guidance here https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
=> Pin the slackbot version

terraform/environments/core-network-services/monitoring.tf
The alarm is going off regularly as it is too sensitive.  Changing so that there has to be 15minutes of zero traffic before it triggers.
=> Make alarm less sensitive

terraform/environments/core-network-services/transit_gateway_connections.tf
As discussed in https://github.com/ministryofjustice/modernisation-platform/issues/2199 this PR does the following:
* Add a route to `10.26.0.0/16` via the inspection VPC to the `external` route table
* Remove propagations for lower environments from the `external` route table
* Add routes to RFC1918 private address ranges via the inspection VPC to the `non_live_data` route table
* Remove non-RFC1918 routes from the `non_live_data` route table
* Add default route to `0.0.0.0/0` via the PTTP TGW peering attachment to the `inspection` route table
* Refactors the names of some locals for readability
The net effect of this PR is that traffic coming over the PTTP TGW peering attachment to a lower environment will route through the inspection VPC (and therefore through the AWS Network …
=> Route traffic to/from MP lower environments via Network Firewall

terraform/environments/bootstrap/delegate-access/iam.tf, terraform/environments/core-shared-services/iam.tf, terraform/modernisation-platform-account/iam.tf
Relevant issue: https://github.com/ministryofjustice/modernisation-platform/issues/2563
* Adding `[Modernisation Platform AMI Builds](https://github.com/ministryofjustice/modernisation-platform-ami-builds)` repository to the modernisation-platform-account OIDC provider to allow those workflows to convert to OIDC
* Updating OIDC module versions in the rest of `delegate-access` and `core-shared-services` code to account for a breaking change in the `github_repositories` variable introduced in [this PR](https://github.com/ministryofjustice/modernisation-platform-github-oidc-provider/pull/13) (this change should not produce any differences from the current terraform state)
=> Adding AMI builds repo to MP OIDC provider default role to allow OIDC conversion.

terraform/environments/secrets.tf, terraform/modernisation-platform-account/iam.tf
To use OIDC provider in authentication, the workflow needs to know the full arn of the role it's assuming post-authentication before terraform can run. Therefore, the environments-management secret, which contains all the member account numbers is loaded as a GHA secret instead.
Additionally, fixing a bug introduced in the previous OIDC PR: passing the ami repo name with the organisation name prefix.
ETA: It looks like one of the certs in the certificate chain for the github oidc host have been updated, as one of the thumbprints has changed. I verified the one starts with 69* is still valid.
=> Adding environents management secret to AMI repo to be consumed by the OIDC github workflow.

terraform/github/main.tf
Relevant issue: https://github.com/ministryofjustice/modernisation-platform/issues/2593
Adding a repo for a module for an AssumableWithWebIdentity role that can be used with Github OIDC providers
=> Adding oidc-role module repo.

terraform/environments/core-network-services/transit_gateway_connections.tf
covered by one as /8 on non-live.
Not showing the IP addresses in here
May need additional work later but this will be under a new request
=> Added IP address to code for live data,

source/index.html.md.erb, source/runbooks/cloudwatch-networking-alarms.html.md.erb
This PR adds a runbook covering our networking-related CloudWatch alarms, with some discussion on what can cause the alerts to trigger, and what actions can be taken in the event that an alert has triggered.
=> Runbook for cloudwatch networking alarms

.github/workflows/new-environment.yml
Related Issue: https://github.com/ministryofjustice/modernisation-platform/issues/2568
Converting the remaining workflow to OIDC. 
* Converting new-environments/check-environments-deployment-plan to OIDC
* Converting new-environments/create-environment to OIDC
For details see: https://github.com/ministryofjustice/modernisation-platform/pull/2686
=> Converting remaining aws-root-account jobs to OIDC.

.github/workflows/core-vpc-development-deployment.yml, .github/workflows/core-vpc-preproduction-deployment.yml, .github/workflows/core-vpc-production-deployment.yml, .github/workflows/core-vpc-test-deployment.yml
The old command was working based on if there was an addition of the networking.auto.tfvars.json, but this file doesn't change after it's initially been created.  Now we are looking for change in the environments-networks/*.json files, these change every time there is a new ram share, either by the file being created in the first instance or by and account being added to it.
The only problem is there is no simple way to know which account has been added, it's easy to do if there is only one account added to existing ones but for the first time file creation it's all new.
So this solution will return all of the accounts and the ram share will run for all of the accounts in a VPC, this shouldn't be a problem however as it should just run and show no changes if they haven't been newly added.
=> Fix ram share not running on network change

source/index.html.md.erb, source/team/ways-of-working.html.md.erb
This change is part of the [#2641](https://github.com/ministryofjustice/modernisation-platform/issues/2641) and:
1. Introduces working with Git/GitHub section
2. Updates task management section
This has been tested locally.
=> Expanding on ways of working guide

terraform/environments/bootstrap/delegate-access/iam.tf
Related conversations:
https://mojdt.slack.com/archives/C01A7QK5VM1/p1669116439379209
https://mojdt.slack.com/archives/C013RM6MFFW/p1669116932521259
The `AWSSupport-CalculateEBSPerformanceMetrics` requires the following permissions:
```
ec2:DescribeVolumes
ec2:DescribeInstances
ec2:DescribeInstanceTypes
cloudwatch:PutDashboard
cloudwatch:ListMetrics
ssm:GetAutomationExecution
```
Adding the ones missing from the developer role as well as `cloudwatch:DeleteDashboards` to allow cleanup.
=> Add permissions required to diagnose EBS iops issues.

terraform/environments/core-network-services/vpn.tf
Without the provision of a `log_output_format` attribute, the AWS API will select `json` by default. However, on seeing this Terraform will attempt to delete this value leading to an unneccesary loop.
This fix PR adds the missing option to prevent this behaviour
=> added missing option to tunnel log options

.github/workflows/core-vpc-development-deployment.yml, .github/workflows/core-vpc-preproduction-deployment.yml, .github/workflows/core-vpc-production-deployment.yml, .github/workflows/core-vpc-test-deployment.yml
```
Environment: production
Account: mlra-preproduction
Running terraform across workspace mlra-preproduction-production Terraform init
Error handling -chdir option: chdir terraform/environments/mlra-preproduction: no such file or directory Error: Process completed with exit code 1.
```
RAM sharing was running for accounts it shouldn't, eg above it's running in production for a preproduction account.  This is because the list of changed accounts isn't being filter.  The new grep checks and filters out any accounts which don't match the environment.
Also fixing spelling errors.
=> Fix ram sharing running when it shouldn't

.github/workflows/core-vpc-development-deployment.yml, .github/workflows/core-vpc-preproduction-deployment.yml, .github/workflows/core-vpc-production-deployment.yml, .github/workflows/core-vpc-test-deployment.yml
Passing in multiple lines to the github action output doesn't work, it only takes the first line.  This change merges the lines in to one, and then itterates through strings on a single line separated by a space.
=> Ram association fix - one line

terraform/pagerduty/aws.tf, terraform/pagerduty/member-services-integrations.tf, terraform/pagerduty/policy-schedules.tf
Adding a Pagerduty service and integration for Nomis, once created we will manually associate the service with the slack channel (this cannot be coded unfortunately).
This also creates a new dead end escalation policy which goes through to our dead end user.  This saves having to create the required escalation policy, schedule and user for teams which only want to use this for slack integration.
=> Add pagerduty service for Nomis

scripts/get-applications-and-run-ram.sh
The git diff command is returning a non 0 when there are no accounts to find, this is causing the script to exit with a non zero status.  As we want to exit nicely if this happens, removing the pipefail option.
=> Remove pipefail option

terraform/environments/core-network-services/transit_gateway_connections.tf
* Removes a default static route from the TGW `external` route table
* Adds a static route for the MP core VPCs to the TGW `external` route table
The rationale for this PR is as follows: there's no need for a `0.0.0.0/0` route on the `external` route table. That route table exists to correctly forward traffic entering the MP from outside, and the only traffic we should expect ought to be for MP destinations. Therefore we only need three routes in line with our [CIDR allocation register](https://github.com/ministryofjustice/modernisation-platform/blob/main/cidr-allocation.md).
Secondarily, by having a `0.0.0.0/0` route on the `external` route table we are at risk of advertising this route to connected parties via BGP. As we only want to receive traffic for an MP …
=> Amend routes on TGW external route table

terraform/github/main.tf
Relevant Issue: https://github.com/ministryofjustice/modernisation-platform/issues/2400
Since `testing-test` doesn't have an OIDC provider (as we use it to test changes to the various OIDC modules) in order to run aws-nuke against it, the workflow needs access to the testing-test ci user keys.
=> Adding testing-test keys to modernisation-platform-env repo for use by aws-nuke.

terraform/github/modules/repository/main.tf
This was manually enabled on some repos, adding to code for all.
=> Enable security scanning on repos

terraform/github/main.tf
Relevant Issue: https://github.com/ministryofjustice/modernisation-platform/issues/2041
The last time these credentials were used was November 17th. Removing these credentials from github repos with a view of deleting the user next week.
=> Remove ci user credentials from core repo secrets.

terraform/environments/environments.tf
This version fixes how nuke-related lists were generated to allow for definition of multiple access blocks per environment, including multiple sandbox blocks and multiple values for nuke:
See PR for more details: https://github.com/ministryofjustice/modernisation-platform-terraform-environments/pull/27
And a fix for a misspelled name of a local: https://github.com/ministryofjustice/modernisation-platform-terraform-environments/pull/28
=> Bumping environments module version.

terraform/github/aws.tf, terraform/github/main.tf
Relevant Issue: https://github.com/ministryofjustice/modernisation-platform/issues/2041
Member-ci credentials have not been used since Dec 4th. Removing them from the `modernisation-platform-environments` repo secrets.
As `ci` and `member-ci` locals are not used elsewhere, removing the locals and datacalls from `terraform/github`
=> Removing member-ci secret from environments repo and deleting ci-related data calls.

terraform/github/main.tf
Relevant Issue: https://github.com/ministryofjustice/modernisation-platform/issues/2041
This PR removes the placeholders for the org-level secrets in the modernisation-platform repo.
The org keys have not been used since November 18th. 
Note: while the user is managed in code in the `aws-root-account` repo, the keys aren't so I've requested that the keys for the user be manually disabled.
=> Removing org secrets from the MP repo.

terraform/environments/bootstrap/delegate-access/collaborators.tf
These permissions are available to the developer role but missing from the collaborator sandbox role.
=> Add additional GUI perms for sandbox collaborators

environments/delius-iaps.json
Linked slack thread: https://mojdt.slack.com/archives/C01A7QK5VM1/p1671020159562879
Delius developer reported issues with running plans after a nuke that potentially could have been linked to the rebuild running on main rather than their working branch.
Disabling rebuild for now.
=> Disabling rebuild after nuke for delius-iaps to avoid conflict with working branches.

.github/workflows/terraform-github.yml, source/runbooks/creating-accounts-for-end-users.html.md.erb, terraform/github/locals.tf, terraform/github/main.tf
- dynamically generate a list of the application teams to be added to our repo from the json files, rather than using a static list that needs to be updated on new account creation.
- modify the workflow to run on json file changes
- update documentation
=> Change from static to dynamic github app teams

.github/workflows/add-issues-to-project.yml
Our custom add all issues to project action had stopped working due to API changes.  Now though there is an official version in the actions repo, so switching to this.
=> Switch to official add issue to project action

terraform/github/aws.tf, terraform/github/testing-ci.tf
Relevant Issue: https://github.com/ministryofjustice/modernisation-platform/issues/2576
Setting values for the testing_ci_iam_user_keys local from the aws_iam_access_key resource since the value of the aws_secretmanager_secret_version resource is unknown until apply and terraform plan fails when trying to predict changes to dynamic secret resources within the github terraform module..
Additionally:
- Bumping rotation period to 7 days.
=> Correct the definition of the testing ci keys local

.github/workflows/close-stale-prs.yml
Using this action - https://github.com/actions/stale we can automate the tidying up of old PRs.
After 30 days of no activity, the PR will be marked as stale.  If no body comments or removes the stale tag, after a further 10 days the PR will be closed and the branch deleted.  This includes draft PRs.
=> Add automation to tidy old PRs

.github/workflows/terraform-github.yml, source/concepts/sdlc/testing-strategy.html.md.erb, terraform/github/README.md, terraform/github/locals.tf, terraform/github/testing-ci.tf, terraform/github/versions.tf
Closes https://github.com/ministryofjustice/modernisation-platform/issues/2576
- Adding tags to make it more obvious which `testing-test` resources are managed in the github project.
- Updating testing docs
- Updating README
- Adding schedule to github workflow to run every Saturday at midnight.
=> Adding testing account information and tags, workflow scheduling and updating docs.

source/concepts/environments/backups.html.md.erb, terraform/environments/bootstrap/delegate-access/iam.tf, terraform/environments/bootstrap/secure-baselines/main.tf
- bump baselines to new version with non production backup plans
- give memberinfrastructureaccess role permissions to create backup plans
- update documentation
This finishes off the outstanding actions in our patching strategy here: https://github.com/ministryofjustice/modernisation-platform/blob/main/architecture-decision-record/0023-backup-strategy.md
=> Add new backup features

environments-networks/laa-development.json, environments-networks/laa-preproduction.json, environments-networks/laa-production.json, environments-networks/laa-test.json
Query via ask channel:
The MLRA application that we're moving across from the LAA Landingzone uses AWS X-RAY to collect telemetry data. Our testing of the initial deployment of the stack in mlra-development has thrown up some errors being caught by x-ray when it's launching. Specifically: [Error] Get instance id metadata failed: EC2MetadataError: failed to make EC2Metadata request status code: 401, request id: We have gone over the IAM policies that the EC2 uses and we've content there are no differences that would causes this. However what we have discovered is that the x-ray service endpoint doesn't seem to be available in the core VPC - as covered here - https://docs.aws.amazon.com/xray/latest/devguide/xray-security-vpc-endpoint.html.
=> Add Xray VPC endpoint

scripts/get-applications-and-run-ram.sh, scripts/member-account-ram-association.sh
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
Finished running ram share association for application: mlra
Error: Process completed with exit code 1.
```
I can't work out what is causing the exit code to be one, explicitly exiting successful functions with zero to see if this helps
Example failing ram share here - 
https://github.com/ministryofjustice/modernisation-platform/actions/runs/3712483609/jobs/6294104349
=> Fix non zero exit status

terraform/environments/core-shared-services/ssm.tf
This created an automation script in the core-shared-services account, which can either scan or install updates across accounts. It's a slight change to a command script supplied by AWS. If this creates fine, then I can edit it, and change the script to what is required, a script that can have single packages handed to it as variables, which will be installed across the accounts that are supplied.
This has been tested when created manually, and is not scheduled at all, it needs manual running.
=> Creation of automation script with default variables.

terraform/environments/bootstrap/delegate-access/policies.tf
By moving to a manged policy rather than inline, SSO fails if the policy doesn't exist in the account.  Since these are just policies it's safe to add them to all accounts and then let the SSO control when they are used.
=> Add policies to all MP accounts

terraform/environments/bootstrap/delegate-access/collaborators.tf
The count was removed from the policies but not removed here, causing the workflow to fail.
=> Remove unneeded count

terraform/environments/bootstrap/delegate-access/policies.tf
On the collaborator role these are directly on the user, but now we are using the same policy for SSO we need to add them here as well.
=> Add missing sts permissions

scripts/provision-member-directories.sh
This allows any repository users to be able to approve changes to the terraform/modules directory.
=> Add modules folder to codeowners generation

terraform/environments/bootstrap/delegate-access/iam.tf, terraform/modules/iam_baseline/main.tf
This is to enable LAA to recreate codebuild tests.
=> Add codebuild and codepipeline permissions

terraform/environments/bootstrap/delegate-access/policies.tf, terraform/environments/bootstrap/single-sign-on/main.tf
Create a common policy and include it in other policies to avoid duplication.
Include developer policy in the migration policy and then add additional permissions for migration.
Resolve some SSO data attribute deprecated warnings.
Add sids to allow use of overrides
=> Refactor policies to avoid duplication

.github/workflows/bootstrap-sprinkler-plan.yml
Bootstrap terraform runs across all accounts, so it would take a long time to plan and review all accounts, this workflow runs the plan against sprinkler-development, giving us a way to easily see and review what the plan would likely do across all accounts.
=> Add workflow to plan for bootstrap

.github/workflows/scheduled-baseline.yml, scripts/update-sso-permission-sets.sh
When the policy changes we need to be able to trigger the permission set to update with the new managed policy.
New script created to do this which runs after delegate access,
this is where the policies are set.  Also making sure it runs after
single-sign-on to ensure there are no clashes with this workflow.
=> Add script to trigger SSO permission set update

.github/workflows/scheduled-baseline.yml
The job was failing as the script call was in a separate run command. The call needs to be in the same run command in order to have access to the credentials in the environment.
=> Fix update-permission-sets job

.github/workflows/new-environment.yml
The order of these were changed to fix a bug here - https://github.com/ministryofjustice/modernisation-platform/pull/2855
But this then breaks the SSO as the role doesn't exist yet.  There is no way round this dependancy, so reversing this change and will have to find another way to fix the bug.
=> Change order of new environment workflows

terraform/environments/bootstrap/delegate-access/policies.tf
Adding the following permissions to allow fleet manager remote desktop SSO sign on
(https://aws.amazon.com/blogs/security/how-to-enable-secure-seamless-single-sign-on-to-amazon-ec2-windows-instances-with-aws-sso/): `identitystore:DescribeUser`
`sso:ListDirectoryAssociations`
Adding the following permissions to allow credentials to be imported for linking a codebuild project to a source GitHub repository: `codebuild:ImportSourceCredentials`
`codebuild:PersistOAuthToken`
=> Add developer permissions for codebuild and fleet

.github/workflows/scheduled-baseline.yml
The baselines workflow is taking over an hour, by switching to a matrix the jobs can run concurrently, massively reducing the amount of time needed.
Note that the limit for using a matrix is 256, we currently are on 62 workspaces so this should last us a while and we can refactor if we reach the limit.
See example here of the workflow working - https://github.com/ministryofjustice/modernisation-platform/actions/runs/3829932063 it now completes all stages in under 15min
=> Use GitHub Actions matrix for sceduled baselines

terraform/environments/bootstrap/delegate-access/policies.tf
Adding the following permissions to allow fleet manager remote desktop SSO sign on (https://aws.amazon.com/blogs/security/how-to-enable-secure-seamless-single-sign-on-to-amazon-ec2-windows-instances-with-aws-sso/): identitystore:DescribeUser sso:ListDirectoryAssociations
Adding the following permissions to allow credentials to be imported for linking a codebuild project to a source GitHub repository: codebuild:ImportSourceCredentials codebuild:PersistOAuthToken
=> Add permissions to sandbox for rdp sso and codebuild

source/user-guide/getting-aws-credentials.html.md.erb
Our user guide doesn't make clear that the AWS SSO landing page is for Ministry of Justice employees, and that external collaborators should review different guidance. Given that we've had a few customers query us about this, it's worth clarifying for them.
=> updated getting-aws-credentials to reflect relevance

environments/refer-monitor.json
[IPB-44](https://dsdmoj.atlassian.net/browse/IPB-44): Add the @ministryofjustice/hmpps-interventions-dashboard-access team to the `refer-monitor` environment to allow access to QuickSight and Athena for non-developer people with GitHub accounts.
If there's a better way to achieve the above, I am happy to change this.
`hmpps-interventions-dev` is tied to other operational resources, making extending unsafe.
[IPB-44]: https://dsdmoj.atlassian.net/browse/IPB-44?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add dashboard team to refer-monitor environment

terraform/environments/core-network-services/vpn.tf
Our VPN code relies on terraform default values for attribute such as `tunnel1_ike_versions`. This means that AWS then fills in the blanks by writing in the default values. However, on re-running terraform the `aws_vpn_connection` resource sees those defaults but does not expect them and attempts to remove them, leading to the AWS API to recreate them.
In order to prevent this thrashing, I've added a lifecycle `ignore_changes` statement to cover the relevant attributes.
=> Prevent VPN resource thrashing

scripts/get-applications-and-run-ram.sh
After the first if statement was successful, the script was exiting with 0 status without running the 2nd if statement which is required if there
are changes with the networking vars.
The exit 0 statements were put in there to try to fix an error where the script was running successfully but returning a non zero code and the workflow was failing.
Removing the set e to try to resolve this.  We will have to see how the next new account run looks to see if this has resolved it.
=> Remove exit 0 from RAM account script

terraform/environments/core-network-services/monitoring.tf
I have set the max aggregation interval as the documentation states that for transit gateway id it has to be set to 60
=> Set max aggregation interval

terraform/environments/core-network-services/vpn_attachments.json
This adds the configuration necessary to create a VPN to Azure UK West.
It will need a corresponding change from DSO, as well as some consideration on how to handle routing.
However, without the creation on our side we won't generate PSKs to be passed to DSO.
=> Added VPN configuration for NOMS Live VPNs

terraform/environments/core-network-services/locals.tf, terraform/environments/core-network-services/vpn.tf
This PR repeats a pattern used for the NOMS non-live static routes, creating statically-typed locals that are fed into single-purpose resource declarations to create routes on the Modernisation Platform Transit Gateway in the `inspection` route table.
This will allow traffic to leave the Modernisation Platform and be routed through the correct VPN to 6Degrees.
=> Static routes for 6DG

terraform/environments/core-network-services/locals.tf, terraform/environments/core-network-services/vpn.tf, terraform/environments/core-network-services/vpn_attachments.json
Once the VPNs between the MP TGW and Azure FNG have been establish, static routes will be required to correctly make use of these VPNs.
This PR should **not** be completed until the live Azure VPNs are active.
This PR also renames the existing resource for NOMS routes to clarify the distinction between DR and Live.
=> NOMS Live routes

terraform/environments/core-network-services/vpn.tf, terraform/environments/core-network-services/vpn_attachments.json
* Amends `vpn_connection` resource to support `static_routes_only` argument
* Set 6DG VPNs to use `static_routes_only` in the configuration for their `vpn_connections`. The CGWs will still contain BGP configuration as this is a required field
=> Set VPN connections to 6DG to use static addresses only

source/index.html.md.erb, source/runbooks/rotating-secrets.html.md.erb, terraform/modernisation-platform-account/secrets.tf
Adding documentation on how to rotate our secrets.
Also creating secrets manager secrets for the MP GitHub CI user secrets which we'll be moving out of password management into GitHub secrets.
=> Add secret rotation docs and move secrets to SM

terraform/github/aws.tf, terraform/github/main.tf
Now that the PAT is stored in secrets manager it can be updated in code rather than manually in the GitHub gui.
=> Update github to pull secrets from secrets manager

terraform/environments/bootstrap/member-bootstrap/iam.tf
Checkov ignore was incorrect in the check it was set to CKV_AWS_40 but the actual check is as bellow with a CKV2
Check: CKV2_AWS_40: "Ensure AWS IAM policy does not allow full IAM privileges
FAILED for resource: aws_iam_policy_document.member-access
File: /iam.tf:17-190
this should fix this checkov error now
=> Change to the checkov ignore

environments/delius-jitbit.json
Disable the auto-nuke feature in the jitbit dev environment.
This is likely to be temporary until we have the app pipeline built which we're currently working on. At which point, we should remove this from being a sandbox account.
=> Disable auto-nuke on delius-jitbit dev environment

terraform/templates/data.tf, terraform/templates/locals.tf, terraform/templates/member-locals.tf, terraform/templates/platform_secrets.tf
Some resources in the template files do not belong to the files that they are in, hence shifting them around. This is needed as part of the https://github.com/ministryofjustice/modernisation-platform/issues/2521 ticket.
Renaming files and generating files in the environments changes will be raised in a separate PR.
=> Moving resources around within template files

terraform/modernisation-platform-account/iam.tf, terraform/modernisation-platform-account/locals.tf
Adding the ssm parameter allows the data source to function regardless of the user source, SSO or IAM calling it.
Allowing collaborators to assume the read only role in the modernisation platform, again this gives consistency to the providers file.
=> Changes to allow one providers file

environments/analytical-platform-data-engineering.json, environments/analytical-platform-data.json, environments/analytical-platform.json
Provided some erroneous access configuration. The PR fixes the errors in access in the AP json files.
* Amending slug name for ap-analytical-platform-data-engineering-production account.
* Giving analytics-hq view-only access in the analytical-platform-data-development account.
* Removing data-engineering access from analytical-platform-development account.
=> Adjusting AP access

terraform/environments/core-logging/route53_resolver_logs.tf, terraform/modules/r53-resolver-logs/main.tf, terraform/modules/r53-resolver-logs/variables.tf, terraform/modules/r53-resolver-logs/versions.tf
* Add new cloudwatch group to take Route53 resolver logs
* Add module to turn on resolver logging
Essentially a rollup of @SteveLinden 's prior branches
=> Add CloudWatch log group and Route53 resolver logs module

terraform/environments/core-vpc/providers.tf, terraform/environments/core-vpc/vpc.tf, terraform/modules/r53-resolver-logs/main.tf
* Add a new provider and data call to get ARN of CloudWatch Log Group in `core-logging` account
* Use a `for` expression in a `for_each` to get the VPC IDs in each workspace and apply the `r53-resolver-logs` module
* Remove an unsupported `tags` attribute from the `r53-resolver-logs` module
=> Turn on resolver logs in each customer VPC

terraform/environments/core-logging/route53_resolver_logs.tf
The changes in the core-vpc earlier were not allowed due to log writing issues. This is to correct the name of the location to allow this access.
=> Fix logging location for route53 log files

environments/analytical-platform-data.json
This is Data Engineering's main working account. Giving them limited access in it.
=> Give members of data-engineering-aws team developer access in analytical-platfrom-data-prod

terraform/environments/ppud/iam.tf
Modify conditional statements so the correct resources are created in each environment -
- MGN user will be needed in all envs for migration
- SES user will not be needed in production as using CJSM
Applied locally to all environments successfully.
=> PPUD environment resources changes

.github/workflows/format-code.yml
* Adjusted variable that supplies list of linters to use, as spaces are not supported in variables
* Added variable to exclude `.github` directory from yaml linter
* Adjusted `check for changes` to state if there are, or are not, changes detected
=> Complete configuration for new code formatter MVP

terraform/environments/bootstrap/member-bootstrap/account.tf, terraform/environments/bootstrap/member-bootstrap/locals.tf
This will enable AWS health operations and security emails to go directly to the application support teams rather than to Jake -> MP -> App teams.
https://docs.aws.amazon.com/accounts/latest/reference/manage-acct-update-contact.html
Tested on sprinkler development
Resolves https://github.com/ministryofjustice/modernisation-platform/issues/3069
=> Add alternative contacts for accounts

terraform/environments/bootstrap/delegate-access/policies.tf
Allow the migration role to create access keys for users, we don't know the name of the user being created for the migration activities, and their may be multiple, so leaving this as a *.
=> Allow migration role to create access keys

terraform/environments/bootstrap/delegate-access/collaborators.tf, terraform/environments/bootstrap/delegate-access/policies.tf
Some AWS migration services have managed policies, adding these to the role rather than defining them so that if they change we don't need to update them ourselves.
=> Add AWS managed policies for migration services

terraform/modules/firewall-policy/main.tf
This is to allow the apply to work as it fix's the firewall group name
=> Name change for firewall group

terraform/environments/bootstrap/delegate-access/policies.tf
This PR adds `ec2:SecurityGroup` permissions for use in conjunction with the AWS Application Migration Helper service.
=> updated migration policy to allow further EC2 security group permissions

terraform/environments/bootstrap/delegate-access/collaborators.tf
Number of custom policies was set to `2`, causing only the first two roles alphabetically to be attached to the migration role
=> updated number of custom policies for migration role

terraform/environments/core-network-services/firewall.tf, terraform/modules/firewall-policy/main.tf
after looking at the issue i have found that for the rule group name underscores are not allowed only the following is aloud
The name must have 1-128 characters. Valid characters: a-z, A-Z, 0-9 and -(hyphen). The name can’t start or end with a hyphen, and it can’t contain two consecutive hyphens.
so i have amended the code and change the two underscores for two dashes
=> Change in rule group name

environments-networks/hmcts-development.json, environments-networks/hmcts-production.json, policies/networking/expected.rego
Adding networks - put tipstaff in against development (tipstaff-development) and production (tipstaff-production) in policies/networking/expected.rego
=> Adding network connection for tipstaff

terraform/modules/firewall-policy/main.tf
This PR is to see if the change in priority allows for the rule group to be created as currently this is failing with the following error
Error: creating NetworkFirewall Firewall Policy (corenetworkservicesfwpolicymD8): InvalidRequestException: Priority cannot be provided, parameter: [1], context: StatefulRuleGroupReferences[0][Priority=1]
i believe this is because the priority is in use by the current rule group. i plan to do another PR to change the priority back to one if this PR apply completes successfully.
=> Change of priority to allow rule group creation

terraform/environments/bootstrap/delegate-access/policies.tf
This PR add in permission for running instances this is to help with the ppud migration as AWS AMS does not seam to have permission to run the migrated instances
=> added in permission to be able to run instances

scripts/provision-member-directories.sh
This PR is part of the #2521 .
Tested locally, the network files are populated correctly now.
=> Fixing a bug introduced when extracting dir names as variables

terraform/environments/bootstrap/delegate-access/collaborators.tf, terraform/environments/bootstrap/delegate-access/policies.tf
Following discussion [here](https://mojdt.slack.com/archives/C01A7QK5VM1/p1677234391245069?thread_ts=1676971355.526159&cid=C01A7QK5VM1), I've revisited somewhat how we supply permissions for use with the migration role. I've also asked the customer to give us a full list of what they need in future so we're not stuck in a back-and-forth should this be insufficient.
=> Expand scope of permissions for Migration role

scripts/provision-member-directories.sh
This PR is part of the #2521 .
Fixing another bug, that @davidkelliott pointed out. thanks Dave!
It's fixing renaming of member default files.
=> Dropping member_ prefix for env default files

terraform/environments/bootstrap/delegate-access/collaborators.tf
Adding the AWSApplicationMigrationEC2Access managed permission to resolve permission issues.
https://docs.aws.amazon.com/mgn/latest/ug/security-iam-awsmanpol-AWSApplicationMigrationEC2Access.html
=> Add further permissions to allow MGN usage

.github/workflows/templates/workflow-template.yml, terraform/templates/platform_locals.tf
This PR is part of the https://github.com/ministryofjustice/modernisation-platform/issues/2521 ticket.
The checkout action version must have been updated, as the live workflow use a version 3.3.0, but the template is still at 3.1.0. This is to fix it.
Also fixing what gets assigned when there is no json file present in the locals.
=> Updating template files, tested with apex and delius-iaps accounts

collaborators.json
This is temporarily to allow the migration of data into production and then will be changed to development.
=> Add PPUD dev collaborators to production

terraform/environments/bootstrap/delegate-access/policies.tf
Hi mod-platform team 
In light of [this thread](https://mojdt.slack.com/archives/C8NJZFNPN/p1677837492790619) where we've identified an alert firing (legitimately) but it's due to some planned task - it'd be useful to be able to disable specific alerts linked to a specific host/metric from the AWS UI, then 
I _believe_ this is the correct place to add cloudwatch:DisableAlarmActions to `User: arn:aws:sts::272983201692:assumed-role/AWSReservedSSO_modernisation-platform-developer_45e3801ef842cbf1/<DSOUSER>@digital.justice.gov.uk` generally
Thanks
=> allow cloudwatch:DisableAlarmActions and cloudwatch:EnableAlarmActions for DSO

terraform/environments/core-network-services/development_rules.json
Allow the CCMS-EBS team to use AWS Workspaces to administer hosts in the MP LAA Development VPC in cases where X11 forwarding is required. See https://mojdt.slack.com/archives/C01A7QK5VM1/p1677684248238249 for more discussion
=> MP Network Firewall rules

terraform/environments/bootstrap/delegate-access/policies.tf
This is to empower our users to scale bastion instances in the out of hours and hopefully not raise an incident.
=> Updating developer role to include scaling of bastion instances

terraform/environments/core-logging/s3_logging.tf
Another instance of the incorrect variable on rarely run code.
I've searched the rest of the MP repo there are no more of these.
=> Fix incorrect input

terraform/github/modules/repository/main.tf
This means branches don't have to be updated against main prior to merging.  This is off by default and only comes on when you have status checks, but it is very annoying and doesn't add much value as merge conflict will still prevent bad merges and the opa tests are rarely updated and protected by codeowners.
=> Turn off strict checking

terraform/modules/firewall-policy/main.tf
When this code was previously written it was compliant with the AWS API. Since then, the way that the firewall rule option and settings are passed in has changed. This means that with our current code, every change has repeating iterations of the following:
```
- rule_option {
- keyword  = "sid" -> null
- settings = [
- "1",
] -> null
}
+ rule_option {
+ keyword  = "sid:1"
+ settings = []
}
```
This change will correct that by ensuring that the `keyword` and `settings` are separated.
=> Update rule options generation

scripts/provision-member-directories.sh
Codeowners for teams with multiple teams was generating like this:
```
* @ministryofjustice/modernisation-platform
/terraform/environments/apex @ministryofjustice/laa-aws-infrastructure @ministryofjustice/modernisation-platform
/terraform/environments/ccms-ebs @ministryofjustice/laa-ccms-migration-team @ministryofjustice/modernisation-platform
/terraform/environments/ccms-ebs @ministryofjustice/modernisation-platform-security @ministryofjustice/modernisation-platform
/terraform/environments/ccms-ebs @ministryofjustice/laa-ccms-migration-team @ministryofjustice/modernisation-platform
/terraform/environments/ccms-ebs @ministryofjustice/modernisation-platform-security @ministryofjustice/modernisation-platform
/terraform/environments/ccms-ebs @ministryofjustice/laa-ccms-migration-team …
```
=> Fix codeowners generation

terraform/environments/core-shared-services/ecr_repos.tf
The mlra codebuild pipeline gets triggered by cicd-member user, currently it fails on pull and the cicd-member is not listed in the ECR repo pull permissions.
This change hopefully fixes it.
=> Allowing cicd member pull permissions on the mlra ecr repo

terraform/pagerduty/business-services.tf, terraform/pagerduty/services.tf
Dependancies for business services can only be added one block at a time.  Split into a separate file to avoid confusion with normal services.
=> Fix dependancies for business services

terraform/environments/bootstrap/member-bootstrap/iam.tf
Added permissions for AWS CodeDeploy following request [here](https://mojdt.slack.com/archives/C01A7QK5VM1/p1678810798208709), this expands the permissions for the MemberInfrastructureAccess role to include them.
=> added codedeploy to permissions

environments-networks/hmpps-preproduction.json
In line with [this request](https://mojdt.slack.com/archives/C01A7QK5VM1/p1678884616231059), this PR adds the SMTP VPC endpoint to HMPPS preproduction so that the PPUD team can use AWS SES
=> added additional endpoint for SMTP/SES to hmpps for ppud preprod

terraform/environments/core-network-services/preproduction_rules.json, terraform/environments/core-network-services/production_rules.json
To allow internal MOJ administrators access to the PPUD systems being replatformed onto the Modernisation Platform, some firewall rules need to be added.
=> PPUD firewall rules

terraform/environments/core-network-services/test_rules.json
Based off of a request through the #ask-modernisation-platform slack channel, we were requested to allow traffic in from the LAA landing-zone AWS accounts: https://mojdt.slack.com/archives/C01A7QK5VM1/p1679308738746229
=> added firewall rules for traffic from LAA landing zones to mp-laa-test

terraform/environments/bootstrap/delegate-access/policies.tf
Without `kms:CreateGrant` the permissions are insufficient to allow a developer to start an instance with a KMS-encrypted EBS volume. This permission could be scoped more specifically if needed with a separate statement but this is minimally sufficient. A more specific statement would probably look like this:
```
statement {
sid    = "AccountLocalCreateGrantAllow"
effect = "Allow"
actions = [
"kms:CreateGrant"
]
resources = ["arn:aws:kms:*:${local.environment_management.account_ids[***account-name***]}:key/*"]
condition {
test     = "Bool"
variable = "kms:GrantIsForAWSResource"
values   = ["true"]
}
}
```
=> added kms:creategrant to developer policy

scripts/git-create-environments.sh
In response to #3476 this PR removes sections of the `git-create-environments` script that add in the modernisation platform team as a secondary approver for environment deployments, and trims the part of the script that populates the `modernisation_platform_id` variable.
=> Trim reviewers for new environments

environments/delius-core.json
Change to access level for delius-core-dev while doing some initial testing of using DMS to migrate Oracle data.
=> Change delius-core-dev to sandbox while testing out dms

source/user-guide/deploying-your-infrastructure.html.md.erb
Cancelling a workflow can lead to the loss or corruption of Terraform state, adding a warning of this.
=> Add workflow cancellation warning

terraform/environments/data-platform/data-platform-oidc.tf, terraform/environments/data-platform/data.tf, terraform/environments/data-platform/locals.tf
Using the modernisation platform oidc role module to create a web-identity-assumable role to be used in external data platform repositories.
List of repositories managed via a local.
Permissions are duplicates of cicd-member-user
=> Adding the OIDC role in the environments directory.

scripts/provision-environment-directories.sh, scripts/provision-member-directories.sh, terraform/templates/modernisation-platform-environments/README.md, terraform/templates/modernisation-platform-environments/application_variables.json, terraform/templates/modernisation-platform-environments/data.tf, terraform/templates/modernisation-platform-environments/locals.tf, terraform/templates/modernisation-platform-environments/platform_backend.tf, terraform/templates/modernisation-platform-environments/platform_base_variables.tf, terraform/templates/modernisation-platform-environments/platform_data.tf, terraform/templates/modernisation-platform-environments/platform_locals.tf, terraform/templates/modernisation-platform-environments/platform_providers.tf, terraform/templates/modernisation-platform-environments/platform_secrets.tf, terraform/templates/modernisation-platform-environments/platform_versions.tf, terraform/templates/modernisation-platform-environments/secrets.tf, terraform/templates/modernisation-platform/data.tf, terraform/templates/modernisation-platform/locals.tf, terraform/templates/modernisation-platform/platform_backend.tf, terraform/templates/modernisation-platform/platform_base_variables.tf, terraform/templates/modernisation-platform/platform_secrets.tf, terraform/templates/modernisation-platform/platform_versions.tf, terraform/templates/modernisation-platform/providers.tf, terraform/templates/modernisation-platform/subnet_share.tf
There are too many differences between the terraform files in the modernisation platform repo and the environments repo to keep using the same templates.  This splits the templates into two folders, one for each repo.  The scripts have been updated and simplified to account for this.  Now we can make changes to one set of files without impacting the other.
=> Refactor provisioning script

environments/analytical-platform-data-engineering.json, environments/analytical-platform-data.json, environments/analytical-platform-landing.json, environments/analytical-platform-management.json, environments/analytical-platform.json, environments/data-platform.json, policies/environments/environment-definitions.rego, policies/environments/environment-definitions_test.rego, source/user-guide/creating-environments.html.md.erb, source/user-guide/working-as-a-collaborator.html.md.erb, terraform/environments/bootstrap/single-sign-on/main.tf
- Adding security-audit and read-only permission options, updating rego.
- Switching permission_set_arn for instance-management.
- Documentation update
SecurityAudit and ReadOnly permission sets are already defined in the root account, so this is code to enable these permissions for MP and MP users.
=> Enabling security-audit and read-only permission sets

environments/analytical-platform-data-engineering.json, environments/analytical-platform-data.json, environments/analytical-platform-landing.json, environments/analytical-platform-management.json, environments/analytical-platform.json, environments/data-platform.json
https://github.com/ministryofjustice/analytics-platform-infrastructure/issues/1053
This change was requested by the DP security team because they'd like to have a limited-permissions role for viewing things like SecurityHub but will also on occasion need to look at the contents of S3 buckets as part of their work.
=> Giving Security & Audit team read-only permissions in addition to security-audit

terraform/github/repositories.tf
Have the go tests as required is mostly slowing us down being able to bulk merge minor PRs unrelated to the go tests.  We can still make sure as part of the PR review process that these checks pass.
=> Remove go tests being required

scripts/replace-platform-files-with-templates.sh
This is a helper script to quickly replace all the platform_files in the environments repo to match the environment repo templates.
Note if you keep your environments folder in a different location you will need to update the environments_folder location.
=> Add script to replace platform files

source/user-guide/running-terraform-plan-locally.html.md.erb, source/user-guide/working-as-a-collaborator.html.md.erb, terraform/templates/modernisation-platform-environments/platform_base_variables.tf, terraform/templates/modernisation-platform-environments/platform_providers.tf, terraform/templates/modernisation-platform-environments/platform_secrets.tf
To run plans locally you used to have to comment and uncomment the provider files.  This change updates the templates so that the user you are using is detected and the appropriate provider settings applied.
Also updating documentation around this.
Issue https://github.com/ministryofjustice/modernisation-platform/issues/2943
=> Update provider templates for better local plans

terraform/templates/modernisation-platform-environments/platform_providers.tf
This will allow plans locally for resources created in us-east-1 which were failing previously.
=> Add dynamic provider for us-east-1

scripts/replace-platform-files-with-templates.sh
Skipping sprinkler and cooker as changes are already made in those first, plus they have slightly different files as they are sandbox vpc accounts.
Also skipping platform_versions.tf as we said we would allow changes for these files for users to add different provider versions as they needed.
=> Skip certain files in replace script

terraform/pagerduty/policy-schedules.tf, terraform/pagerduty/users-teams.tf
This enables a clear separation between member services and core platform services
=> Split member services into separate pagerduty team

terraform/pagerduty/aws.tf, terraform/pagerduty/services.tf
In order to start using the new services we need to store the integration tokens in the shared secret.
=> Add new service integrations to secret

terraform/environments/core-network-services/monitoring.tf, terraform/environments/core-vpc/monitoring.tf
Moving these alarms over to the newly created service specific services.
=> Switch DDOS and TGW alarms to use new services

environments/analytical-platform-data-engineering.json, environments/analytical-platform-data.json
https://github.com/ministryofjustice/analytics-platform-infrastructure/issues/804
Assigning the new `data-engineer` access level to `data-engineering-aws` Github team.
=> Setting up data-engineering-aws team with data-engineer access.

terraform/environments/bootstrap/delegate-access/policies.tf
https://github.com/ministryofjustice/analytics-platform-infrastructure/issues/804
Additional permissions for the data-engineer access level to perform operational tasks in the console. 
* Athena stop/stop query execution
* dms start/stop execution tasks
* states:StartExecution is for triggering step functions.
=> Adding additional permissions to the DE policy.

environments/analytical-platform-data-engineering.json
Giving developer access to a new team of data engineers as their ask doesn't align well with other access levels.
=> Data Engineering Prod: Giving a new team developer access

terraform/environments/core-network-services/production_rules.json
This is required for delius iaps, see request here - https://mojdt.slack.com/archives/C01A7QK5VM1/p1681394593957699
=> Allow traffic from I2N to HMPPS prod and preprod

terraform/modules/core-monitoring/main.tf, terraform/pagerduty/aws.tf, terraform/pagerduty/services.tf
We weren't really using these topics anyway, the new alerts based on service areas make more sense.
=> Remove old high low priority alarm infra

terraform/environments/bootstrap/delegate-access/policies.tf
https://github.com/ministryofjustice/analytics-platform-infrastructure/issues/804
Additional requests for stopping execution of glue jobs and step functions.
=> Data-Engineer: Permissions to stop job executions from console.

terraform/environments/core-network-services/route53.tf
Hosted zone for ccms-ebs domain so that this domain can be delegated to the modernisation platform.
=> Add ccms-ebs delegated hosted zone

architecture-decision-record/0023-backup-strategy.md, architecture-decision-record/0024-egress-traffic-inspection.md
The backup strategy ADR appeared to share a number with patching strategy, so this fixes the numbering for two ADRs.
=> Fix numbering for ADRs

environments/cooker.json, scripts/git-create-environments.sh
Recently our newly created accounts do not have workflow protection, which means that apply gets deployed automatically if the plan passes OK. This can cause a lot of problems, e.g. unwanted destruction of resources in a test environment if a dev environment passes.
This PR is to fix the problem. It's been already tested and applied on `cooker` and on the `hmpps-intelligence-management`.
=> Fixing creation/update of environments settings

environments/mlra.json
At the request of @mikereiddigital , via [this slack conversation](https://mojdt.slack.com/archives/C01A7QK5VM1/p1681824743606659), I've added the laa-crime-apps-team to the slugs allowed to access the MLRA accounts.
=> added laa-crime-apps team to mlra access

terraform/environments/core-network-services/production_rules.json
The port 80 was too restrictive on one of the laa firewall settings so it has been amended to ANY.
=> Amend LAA rule to ANY port rather than 80

terraform/pagerduty/business-services.tf, terraform/pagerduty/services.tf
Specific areas such as TGW or DDOS have their own services, but if there is a generic issue which isn't covered by one of the other services we need to be able to raise it somewhere.
Following the incident meeting we decided we preferred to keep networking, operations and security as business services as it's makes it clear to users where the problem is, but add additional general services which feed in to these business services.
=> Add generic services to raise incidents manually

terraform/environments/core-network-services/vpc.tf, terraform/modules/vpc-hub/main.tf, terraform/modules/vpc-hub/outputs.tf, terraform/modules/vpc-hub/variables.tf
As part of #3547 this PR adds code to the `vpc-hub` module to conditionally create the following:
* Inspection subnets to hold firewall endpoints
* Inspection NACLs
* Inspection route tables
Later PRs will address further parts of #3547 such as creating the firewalls, policies, and endpoints, and eventually adjusting the routing to make egress traffic flow bidirectionally through the new firewalls, but this PR changes no existing functionality.
This PR also alphabetises the variables in the `vpc-hub` module.
=> Create initial resources for inline inspection

terraform/environments/core-network-services/firewall.tf, terraform/modules/firewall-logging/main.tf, terraform/modules/firewall-logging/variables.tf, terraform/modules/firewall-policy/main.tf, terraform/modules/firewall-policy/variables.tf
At present the `firewall-policy` module introduces a cyclic dependency when it's used with a new firewall.
* A new firewall resource requires a policy
* The `firewall-policy` module requires a firewall ARN for its logging configuration
This PR separates out the logging into its own small module, and includes a random prefix to both ensure the new log groups are unique, and to prevent a clash with the existing log groups before they are destroyed.
=> Move logging out of firewall policy module

terraform/environments/bootstrap/secure-baselines/main.tf, terraform/modernisation-platform-account/baselines.tf
In the tfprovider-aws4.64.0 update the default for control_finding_generator is set to `SECURITY_CONTROL`.
This is different to what we have set at the org level, so we are now getting errors on applies -
```
~ resource "aws_securityhub_account" "default" {
~ control_finding_generator = "STANDARD_CONTROL" -> "SECURITY_CONTROL"
id                        = "***"
}
```
Because this setting is controlled at the org level we do not have permissions to make this change.
Setting the default as `STANDARD_CONTROL` to fix.
=> Bump secure baselines version to fix default ctrl

terraform/environments/core-network-services/firewall.tf, terraform/modules/firewall-logging/main.tf
Because the `for_each` keys contain underscores, the inline inspection firewall names fail to pass validation.
Using a terraform `replace()` changes these out to hyphens which are supported in the AWS API reference here: https://docs.aws.amazon.com/network-firewall/latest/APIReference/API_CreateFirewall.html#API_CreateFirewall_RequestSyntax
A small cosmetic fix for the naming of cloudwatch log groups is also included.
=> Fix naming of inline inspection firewalls

terraform/modules/kms/main.tf
I missed an `=` sign when reviewing a prior PR; this branch introduces the missing operator
=> Fix broken KMS policy

terraform/modules/kms/main.tf
As a result of a recent PR, an extra service principal was granted access to our platform-supplied KMS keys. This PR adjusts the scope of this new service principal so that it is only applied to the `general` KMS key.
=> Trim permissions for generic KMS keys

terraform/environments/core-network-services/firewall-rules/production_rules.json
10.40.0.0/16 this will be changed to noms-live-vnet (10.40.0.0/18)
10.27.8.0/16 this will be changed to hmpps-production (10.27.8.0/21)
The other IPs stay the same just converting to using the locals.
=> Update incorrect ranges

environments/laa-ccms-infra-azure-ad-sso.json
Changed slug based on this request - https://mojdt.slack.com/archives/C01A7QK5VM1/p1683022120483349
Seems possible thanks to the documentation here - https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/changing-environment-details.html#change-the-github-slug-for-an-environment-takaway
=> Changed Github Slug for laa-ccms

terraform/environments/core-network-services/firewall-rules/fqdn_rules.json
As part of the request for issue [#3339](https://github.com/ministryofjustice/modernisation-platform/issues/3339)
we need to add in the sass dns name to the allowed list before the nacl ticket is complete to allow the traffic to flow out to the site from the environments
=> new fqdn rule for equip

terraform/environments/core-shared-services/ecr_repos.tf
Adding two shared ECR repos for data platform. Currently only `data-platform-development` is allowed to push/pull but will be used by all data platform accounts.
=> Adding ECR repo for data platform.

terraform/environments/core-network-services/route53.tf
Changes made based on request from ops engineering. Name did not conform to naming standards.
=> Update route53.tf laa-finance-data.service.justice.gov.uk

terraform/environments/core-network-services/cidr-ranges.tf, terraform/environments/core-network-services/firewall-rules/preproduction_rules.json, terraform/environments/core-network-services/firewall-rules/production_rules.json
Add additional firewall rules for HMPPS preproduction and production to allow devices connected to Prison networks and DOM1 VPN
=> allow Mojo and DOM1 end user compute access to preprod and prod hmpps

terraform/environments/core-network-services/firewall.tf, terraform/environments/core-network-services/test/go_test.go, terraform/environments/core-network-services/vpc.tf, terraform/modules/vpc-hub/main.tf, terraform/modules/vpc-hub/outputs.tf, terraform/modules/vpc-hub/variables.tf
After some internal discussion we've decided that the creation of egress VPCs with inline inspection is better handled in a separate module. The current approach adds extra complexity and spreads resources around in a number of locations which isn't ideal for user comprehension or code maintenance.
This PR unwinds the changes that have already been made.
=> Unwind inspection changes
