ministryofjustice/modernisation-platform

terraform/modules/vpc-inspection/firewall.tf, terraform/modules/vpc-inspection/main.tf, terraform/modules/vpc-inspection/outputs.tf, terraform/modules/vpc-inspection/variables.tf
This PR bundles up previous work to create a module which can be used to create an inline inspection VPC.
The VPC contains the following::
* AWS VPC with three types of subnet; `transit-gateway`, `inspection`, and `private`
* AWS Network Firewall with endpoints spread across the `inspection` subnets
* AWS Route tables and routes to flow traffic out through the firewall endpoints and back in via the transit gateway
* AWS NAT gateways with Elastic IP addresses
* AWS Network ACLs
* Outputs to be used in the creation of tests
=> Inline inspection module

terraform/environments/core-network-services/vpn_attachments.json
* create customer gateway to parole board
* set placeholder BGP ASN (customer is not using BGP, but this is a required field)
* create site-to-site vpns to parole board
* attach VPN to MP Transit Gateway
* associate attachment with `external` Transit Gateway route table
=> Create VPN to Parole Board

terraform/environments/core-network-services/transit-gateway.tf, terraform/environments/core-network-services/vpc.tf, terraform/modules/vpc-inspection/firewall.tf, terraform/modules/vpc-inspection/outputs.tf, terraform/modules/vpc-inspection/variables.tf
This PR creates two VPCs from the `vpc-inspection` module, and attaches them to the MP transit gateway.
A future PR will be needed to route traffic through these new VPCs and remove the old VPCs, as well as to introduce tests to ensure that VPCs remain functional.
=> Create two inline_inspection VPCs

terraform/environments/core-network-services/transit-gateway.tf, terraform/modules/vpc-inspection/outputs.tf, terraform/modules/vpc-inspection/transit_gateway.tf, terraform/modules/vpc-inspection/versions.tf
* Move the `aws_ec2_transit_gateway_vpc_attachment` resource into the `vpc-inspection` module
* Update outputs to remove use of legacy splat syntax
* Remove unused output from `vpc-inspection` module
* Added version constraints to align with good practice
=> Move inspection VPC TGW attachment into module

terraform/modules/vpc-inspection/firewall.tf
As detailed [here](https://docs.aws.amazon.com/network-firewall/latest/APIReference/API_CreateFirewall.html#API_CreateFirewall_RequestSyntax:~:text=Required%3A%20No-,FirewallName,-The%20descriptive%20name), underscores are not valid in a firewall name. This PR uses a replace function to pull `_` characters and replace them with `-` characters.
=> Use replace function to sanitise name of network firewall

terraform/environments/bootstrap/delegate-access/policies.tf
The sso permission set provisioning was failing as the policy name didn't match.  Changing to match the name defined here:
https://github.com/ministryofjustice/aws-root-account/blob/efd728ed376d8ae244c4fb2b1cc99005d3033cc3/management-account/terraform/sso-admin-permission-sets.tf#LL304C13-L304C39
=> Fix policy name

terraform/environments/core-network-services/route53.tf
maat-libra-administration-tool.service.justice.gov.uk to replace mlra.service.justice.gov.uk
Request from Mike.
https://mojdt.slack.com/archives/C01A7QK5VM1/p1683712424562449
=> Update route53.tf for mlra

terraform/environments/core-network-services/transit-gateway.tf, terraform/modules/vpc-inspection/outputs.tf, terraform/modules/vpc-inspection/transit_gateway.tf
In preparation for migration, the new inspection VPCs need to be associated with the correct TGW route tables.
As the route tables are defined in `core-network-services`, I think this is the most appropriate place to put the route table association; I could feed it into the module (which is probably the better approach) but starts to blur the line on where the associations are done and for the sake of comprehensibility I'm going to leave the association in its current location.
* Add output of TGW attachment ID to `vpc-inspection` module
* Consume output in `core-network-services`
=> Associate inspection VPCs with TGW route tables

terraform/environments/core-network-services/transit-gateway.tf
* Amend default routes for `live_data` and `non_live_data` route tables to flow traffic out through new inline-inspection VPCs
=> Route traffic to internet through new inline-inspection VPCs

terraform/modules/vpc-nacls/data.tf
This PR is part of the https://github.com/ministryofjustice/modernisation-platform/issues/2999 ticket.
This is to allow egress traffic on port 80 in our non-public subnets. This change has a dependency on the https://github.com/ministryofjustice/modernisation-platform/issues/3547 ticket and should not be merged before #3547 is completed (hence the draft PR)
=> Allow egress traffic on port 80 in non-public subnets

terraform/environments/core-network-services/firewall-rules/development_rules.json, terraform/environments/core-network-services/firewall-rules/inline_fqdn_rules.json, terraform/environments/core-network-services/firewall-rules/preproduction_rules.json, terraform/environments/core-network-services/firewall-rules/production_rules.json, terraform/environments/core-network-services/firewall-rules/test_rules.json, terraform/modules/vpc-nacls/data.tf
This Pr is to cover the work related to [Allow access from Equip to 3rd party monitoring tool#3339](https://github.com/ministryofjustice/modernisation-platform/issues/3339) this adds a NACL Rule as well as updated the network firewall and add the saas dns name to the new inline fqdn inspection rules these are all required to be able to facilitate the saas agent for the equip team
=> Code Changes for equip networking

terraform/environments/core-network-services/acm-pca.tf, terraform/environments/core-network-services/transit-gateway.tf, terraform/modules/vpc-inspection/main.tf, terraform/modules/vpc-inspection/variables.tf
This PR addresses findings from `checkov` and `tfsec` introduced by the new `vpc-inspection` module, as well as tidying up some checks that are no longer relevant.
This PR also introduces an optional `cloudwatch_kms_key_id` variable to allow for the encryption of VPC flow logs in the inspection VPCs.
=> Inline-Inspection VPC secure code analysis mitigations

terraform/environments/core-shared-services/vpc.tf
In light of [this Slack conversation](https://mojdt.slack.com/archives/C01A7QK5VM1/p1683885328284989?thread_ts=1683799211.928769&cid=C01A7QK5VM1), it appears that the AWS ImageBuilder service attempts to write to CloudWatch logs from an EC2 instance.
Instead of find why this traffic is failing to pass through the new inspection VPCs, I think the better approach is to give it a VPC endpoint for CloudWatch, instead of continuing with traffic passing out to the internet.
=> CloudWatch Logs VPC Endpoint

terraform/environments/core-network-services/cidr-ranges.tf, terraform/environments/core-network-services/firewall-rules/inline_rules.json, terraform/modules/vpc-inspection/main.tf
During the implementation of inline-inspection, our expectation was that traffic in the Modernisation Platform core environments would not need to pass out to the internet. However, on further inspection we've found that some services such as our image builder pipelines *do* need internet access. This PR does the following:
* Add routes to the MP core ranges to the `vpc-inspection` module that builds our inline inspection VPCs.
* Add a name for the MP core ranges
* Use the new name in the inline rules to allow outbound HTTPS access
=> Route traffic back to MP core ranges

environments-networks/laa-development.json, environments-networks/laa-preproduction.json, environments-networks/laa-production.json, environments-networks/laa-test.json
Following [this request](https://mojdt.slack.com/archives/C01A7QK5VM1/p1684164890037909), this PR adds an extra endpoint to the `LAA` VPCs: `com.amazonaws.eu-west-2.email-smtp`
=> Add SMTP endpoint to LAA VPCs

terraform/environments/core-network-services/data.tf, terraform/environments/core-network-services/output.tf, terraform/environments/core-network-services/test/go_test.go
This PR recreates the existing tests for the old egress VPCs and rewrites them for the new inline-inspection egress VPCs.
=> Tests for new inspection VPCs

terraform/pagerduty/aws.tf, terraform/pagerduty/member-services-integrations.tf
Some of our unit tests make use of pagerduty integration keys. This PR introduces a new pagerduty service that can be used by our unit tests.
=> add pagerduty service for test alarms

.github/ISSUE_TEMPLATE/new-environment.md
We added this to help with self service, but I don't think it's helping and sometimes blocking environment creation if we are waiting for firewall rules which are not yet known.
I think firewall requests should be raised in the ask channel (or knowledgble users can raise PRs themselves)
=> Removing the firewall section

.github/workflows/core-logging-deployment.yml, .github/workflows/core-network-services-deployment.yml, .github/workflows/core-security-deployment.yml, .github/workflows/core-shared-services-deployment.yml
Our core environment tests utilise a hardcoded version of `go` that is incompatible with modern versions of the `testify` library. In order to stay current, this PR will allow us to use more modern versions.
We should consider refactoring these workflows to use a GitHub action that installs `go`, but in the interim this will do.
=> update golang version used in tests

terraform/environments/core-network-services/output.tf, terraform/environments/core-network-services/route53.tf, terraform/environments/core-network-services/test/go_test.go, terraform/environments/core-network-services/vpc.tf
Following the completion of #3547 , this PR will remove the tests and terraform relevant to the now-unused egress VPCs.
=> Prune code relating to old egress VPCs

environments/equip.json, environments/nomis.json, environments/performance-hub.json, environments/xhibit-portal.json, scripts/internal/get-application-data-summary/main.go
Simple go script to get the go-live-dates and number of applications from the environment files.  Also updating the dates with correct dates of go live.
Current output:
```
Member applications (29):
apex
ccms-ebs
data-and-insights-wepi
data-platform
delius-core
delius-iaps
delius-jitbit
digital-prison-reporting
equip
hmpps-intelligence-management
laa-ccms-infra-azure-ad-sso
laa-oem
long-term-storage
maatdb
mlra
mojfin
nomis-combined-reporting
nomis-data-hub
nomis
oas
oasys
performance-hub
portal
ppud
refer-monitor
tariff
tipstaff
tribunals
xhibit-portal
Upcoming migrations (2):
2023-05-26 ccms-ebs
2023-06-10 ppud
Live in production applications (5):
2023-05-15 delius-iaps
2022-06-17 equip
2022-08-25 nomis
2021-11-10 performance-hub
2022-03-25 xhibit-portal
```
=> Add script to pull dates from environment files

terraform/environments/core-network-services/firewall-rules/development_rules.json, terraform/environments/core-network-services/firewall-rules/preproduction_rules.json, terraform/environments/core-network-services/firewall-rules/production_rules.json, terraform/environments/core-network-services/firewall-rules/test_rules.json
The hmpps firewall rules for hmpps dev and test were combined, giving the azure estate access to the entire mp dev-test range.  This change splits them out in to dev and test and restricts to hmpps vpcs only.
Also moving the defaults blocks to the top, and renaming a few things for clarity.
=> Split out hmpps dev and test firewall rules

terraform/environments/core-network-services/data.tf, terraform/environments/core-network-services/firewall.tf, terraform/environments/core-network-services/networking.auto.tfvars.json, terraform/environments/core-network-services/vpc.tf, terraform/modules/firewall-policy/main.tf, terraform/modules/firewall-policy/variables.tf, terraform/modules/vpc-inspection/firewall.tf, terraform/modules/vpc-inspection/main.tf, terraform/modules/vpc-inspection/variables.tf
This PR addresses some Checkov issues as follows:
* Skips Checkov checks for network ACLs as these are not relevant in context
* Adds use of `general-platforms` KMS key to encrypt network firewalls, policies, and rule groups at rest
* Adds `delete protection` statements to firewalls to prevent accidental deletion
=> Resolve Checkov issues with firewalls

.github/workflows/format-code.yml
Currently the workflow exits with 1 if there are no changes, this was fine, but now that we are measure workflow failures this is affecting metrics. Switching to using conditional steps.
Tested on this PR which has changes and it worked successfully see here https://github.com/ministryofjustice/modernisation-platform/actions/runs/5059188129/jobs/9080363501
Will need to have it run and merge to see if it works and skips when there are no changes
=> Add logic to skip later steps if no changes

terraform/environments/delius-jitbit/iam.tf, terraform/environments/secrets.tf, terraform/github/testing-ci.tf, terraform/modernisation-platform-account/secrets.tf, terraform/pagerduty/aws.tf
We either can't, don't want to or currently do rotate these via a different mechanism.
=> Ignore rotation warnings

environments/digital-prison-reporting.json
This PR reverts the nuke option that was implemented last week so that the environment is now excluded from the weekly nuke
=> Revert Change

terraform/environments/bootstrap/delegate-access/policies.tf
In line with [this Slack conversation](https://mojdt.slack.com/archives/C01A7QK5VM1/p1684835060715299), this allows users to move their SES accounts from the AWS sandbox and into production.
=> added permission to move SES account from sandbox

terraform/environments/bootstrap/delegate-access/iam.tf, terraform/environments/bootstrap/delegate-access/policies.tf, terraform/environments/bootstrap/member-bootstrap/iam.tf, terraform/environments/ccms-ebs/iam.tf, terraform/environments/core-logging/s3_logging.tf, terraform/environments/core-network-services/firewall.tf, terraform/environments/core-network-services/iam.tf, terraform/environments/core-shared-services/iam.tf, terraform/environments/core-shared-services/kms.tf, terraform/environments/secrets.tf, terraform/modernisation-platform-account/s3.tf, terraform/modules/kms/main.tf
These are mostly for policies which are directly attached to the resource or similar and there for resources needs to be *.  They have been ignored for tfsec before but this is a new check with checkov now doing the same thing.  Also a couple of other ignores which have been verified as ok.
=> SCA ignores for open policies

terraform/environments/core-network-services/firewall-rules/development_rules.json, terraform/environments/core-network-services/firewall-rules/preproduction_rules.json, terraform/environments/core-network-services/firewall-rules/production_rules.json, terraform/environments/core-network-services/firewall-rules/test_rules.json
As per [this Slack thread](https://mojdt.slack.com/archives/C01A7QK5VM1/p1685014974773159), this PR adds firewall rules to allow JDBC calls from the MOJ Cloud Platform into the HMPPS VPCs where the Digital Prisons Reporting app is hosted.
=> Allow Cloud Platform JDBC calls into HMPPS VPCs

terraform/environments/bootstrap/delegate-access/policies.tf
As per [this Slack thread](https://mojdt.slack.com/archives/C01A7QK5VM1/p1685021660706549?thread_ts=1684838327.099879&cid=C01A7QK5VM1), this PR adds the IAM permission statement to the `sandbox_additional` policy, allowing sandbox users to make use of the AWS API Gateway
=> add ability to use apigateway to sandbox policy

terraform/environments/core-shared-services/s3.tf
The image artefact bucket is a shared bucket containing software artefacts used during AMI/Docker image building.
To ensure that IAM policy only governs access (and that objects PUT to the bucket from different accounts are still owned by the bucket, and not the source account), this change is required.
=> Set BucketOwnerEnforced for core-shared-services image-artefact bucket

terraform/environments/core-network-services/monitoring.tf
Added firewall cloudwatch alarm with no sns topic attached. Already applied, and works.
Related to this card. https://github.com/ministryofjustice/modernisation-platform/issues/3290
=> Firewall Alarm Dropped Packets

.github/workflows/new-environment-files.yml, .github/workflows/new-member-environment-files.yml, .github/workflows/terraform-github.yml
Fixes
https://github.com/ministryofjustice/modernisation-platform/issues/3767.
Github environments were being created in the environments repository after the application files were being created.  However adding teams to deployment environment approvers isn't dependant on this.  It is dependant however on adding the github team to the repository, which happens in the terraform-github.yml workflow, so moving this job to there.
=> Fix change of github teams not going to approvers

terraform/environments/core-network-services/route53.tf
As per [this Slack request](https://mojdt.slack.com/archives/C01A7QK5VM1/p1685458203323369), this PR adds a hosted zone that can be used by the jitbit team to test a DNS cutover to the Modernisation Platform
=> Add hosted zone for jitbit migration test

terraform/environments/bootstrap/member-bootstrap/grants.tf, terraform/environments/core-network-services/monitoring.tf, terraform/modules/license-manager/main.tf, terraform/modules/license-manager/variables.tf, terraform/modules/license-manager/versions.tf
As part of #3876 , this PR creates a module to both grant & accept an AWS LicenseManager grant based on a supplied `source_license_arn` value.
The goal of this PR is to allow us to accept an AWS Marketplace agreement in our main `modernisation-platform` account by hand, and then grant that to member accounts through code, ensuring that our LicenseManager grants are managed in Terraform and not through ClickOps.
=> Grant RHEL-6 ELS license to all member accounts

terraform/environments/bootstrap/member-bootstrap/grants.tf, terraform/environments/bootstrap/member-bootstrap/providers.tf, terraform/modules/license-manager/main.tf, terraform/modules/license-manager/variables.tf
* Trim default allowed grant operations
* Add new providers for `us-east-1`
* Supply new providers into module
* Update data call to correct from `grant` to `license`
=> Fix License Manager grants

terraform/modules/license-manager/main.tf
This PR fixes the format function used to populate ARNs in grant principals.
It ensures that any leading 0s are included by setting the string width to 12 characters and padding with 0s on the left.
=> Fix member-bootstraps for License Manager grants

terraform/environments/bootstrap/member-bootstrap/iam.tf
We're deploying Airflow to our Apps and Tools account in Data Platform, but we get the following error
```bash
╷
│ Error: creating MWAA Environment (development): AccessDeniedException: User: arn:aws:sts::***:assumed-role/MemberInfrastructureAccess/aws-go-sdk-1685711006413181890 is not authorized to perform: airflow:TagResource on resource: arn:aws:airflow:eu-west-2:***:environment/development
│ 
│   with aws_mwaa_environment.main,
│   on mwaa-environments.tf line 5, in resource "aws_mwaa_environment" "main":
│    5: resource "aws_mwaa_environment" "main" {
│ 
╵
```
This pull request adds `airflow:*`
Relates to https://github.com/ministryofjustice/modernisation-platform-environments/pull/2402
=> Add Airflow permissions to MemberInfrastructureAccess

.github/workflows/code-scanning.yml
Currently to find the errors you need to scroll through all the successful checks, switching to quiet mode will only show the failed checks.
Also adding a workflow dispatch trigger so that this workflow can be manually be run following corrections.
=> Switch to quiet and add workflow dispatch for SCA

terraform/environments/core-network-services/firewall-rules/inline_fqdn_rules.json, terraform/environments/core-network-services/firewall-rules/inline_rules.json, terraform/modules/firewall-policy/main.tf, terraform/modules/vpc-nacls/data.tf
This PR should amend network ACLs, network firewall rules, and allowed inspected destinations to permit SMTP Submission traffic on `tcp/587` to the `cjsm.net` domain
=> Allow SMTP Submission traffic to CJSM

terraform/pagerduty/aws.tf, terraform/pagerduty/member-services-integrations.tf
We don't have access to PagerDuty. Could you please handle [this step](https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/integrating-alarms-with-pagerduty-with-slack.html#4-link-the-pagerduty-service-to-your-slack-channel) for us.
=> IAPS: set up production alerts

terraform/environments/core-network-services/firewall-rules/inline_fqdn_rules.json, terraform/environments/core-network-services/firewall-rules/inline_rules.json, terraform/modules/vpc-nacls/data.tf
After further discussion with the PPUD migration team the changes to allow hosts in private subnets to send SMTP Submission traffic out to the internet is no longer needed. This PR removes those changes, and re-orders the firewall rules for readability.
=> Remove SMTP Submission changes

cidr-allocation.md
This range will be used for the data platforming team to build a VPC for Airflow and any other non platform networking requirements.
Note this range is not used in the Modernisation Platform core accounts or core-vpc accounts and management of the range is delegated to the data platforming team.
=> Allocate /21 CIDR range to data platforming

terraform/environments/core-network-services/vpn.tf, terraform/environments/core-network-services/vpn_attachments.json
Following the migration of CCMS-EBS to the Modernisation Platform, our VPN connections to Six Degrees are no longer required and can be removed. We've confirmed this with the migration team [here](https://mojdt.slack.com/archives/C04EZ78B6US/p1686063147217849).
=> Remove 6DG vpns

terraform/environments/bootstrap/member-bootstrap/iam.tf
As part of [Allow Route53 query logging in cloudwatch#3926](https://github.com/ministryofjustice/modernisation-platform/issues/3926) users needed the ability to create logs for route53 tracking this pr expands on an existing role that has been assigned to the nomis team to include the ability to create logs in the us-east-1 region
=> Adding extra permissions to create logs

.github/workflows/terraform-github.yml
This was running for PRs as well which we don't need to know about via slack.  Now we will only get alerted if it fails when merging.
=> Only run slack failure when on main

terraform/modules/vpc-hub/main.tf
This PR is part of the https://github.com/ministryofjustice/modernisation-platform/issues/3951 ticket.
NACLs have quota of max 20 rules.
There are currently 10 rules in total in NACLs that are used with private/data subnets: 
[L73](https://github.com/ministryofjustice/modernisation-platform/blob/31db3faa5328cb3340480748a4bf46a7bae19e06/terraform/modules/vpc-hub/main.tf#L73), [L349](https://github.com/ministryofjustice/modernisation-platform/blob/31db3faa5328cb3340480748a4bf46a7bae19e06/terraform/modules/vpc-hub/main.tf#L349), [L363](https://github.com/ministryofjustice/modernisation-platform/blob/31db3faa5328cb3340480748a4bf46a7bae19e06/terraform/modules/vpc-hub/main.tf#L363), [L374](https://github.com/ministryofjustice/modernisation-platform/blob/31db3faa5328cb3340480748a4bf46a7bae19e06/t …
=> Securing the NACLs rules

terraform/environments/core-network-services/cidr-ranges.tf, terraform/environments/core-network-services/firewall-rules/production_rules.json
In response to [this request](https://mojdt.slack.com/archives/C01A7QK5VM1/p1686649139459569), this adds a firewall rule allowing traffic from LAA AppStream subnets into the LAA Production VPC.
This also removes a rule from `production.json` that refers to preproduction, that also appears in the preproduction rules and also cleans up an incorrect name.
=> LAA appstream rules

terraform/environments/core-network-services/cidr-ranges.tf, terraform/environments/core-network-services/firewall-rules/development_rules.json, terraform/environments/core-network-services/firewall-rules/production_rules.json
As part of https://github.com/ministryofjustice/modernisation-platform/issues/4211, this introduces rules allowing access from the VPC for LAA Appstream to the LAA development and production VPCs on the Modernisation Platform
=> LAA shared services firewall rules

terraform/environments/bootstrap/delegate-access/policies.tf
a follow up to #4209 which didn't give quite enough permissions to have required glue usage.
=> adding additional glue trigger permissions for data engineers

terraform/environments/data-platform-apps-and-tools/vpc-endpoints.tf, terraform/environments/data-platform-apps-and-tools/vpcs.tf
As per the conversation in [#ask-modernisation-platform](https://mojdt.slack.com/archives/C01A7QK5VM1/p1686562058335599), I have downgraded the affected modules to a compatible version.
```bash
$ terraform init -backend=false
Initializing modules...
Downloading registry.terraform.io/terraform-aws-modules/vpc/aws 4.0.2 for vpc...
- vpc in .terraform/modules/vpc
Downloading registry.terraform.io/terraform-aws-modules/vpc/aws 4.0.2 for vpc_endpoints...
- vpc_endpoints in .terraform/modules/vpc_endpoints/modules/vpc-endpoints
Initializing provider plugins...
- Finding hashicorp/aws versions matching ">= 3.29.0, >= 3.47.0, >= 4.0.0, >= 4.35.0, < 5.0.0"...
- Finding hashicorp/http versions matching "~> 3.0"...
- Installing hashicorp/aws v4.67.0...
- Installed hashicorp/aws v4.67.0 (signed by …
```
=> 📌 Downgraded Data Platform Apps and Tools' AWS VPC modules to 4.0.2

terraform/environments/core-network-services/firewall-rules/development_rules.json, terraform/environments/core-network-services/firewall-rules/production_rules.json
This PR is part of the https://github.com/ministryofjustice/modernisation-platform/issues/3822 ticket.
This is to allow traffic from CP to platforms-development to allow for latency testing between nettest namespace and example-development EC2. This is a permanent change so that future tests can be performed without a need of changes.
This rule has been tested manually and it worked.
=> Allowing ICMP from CP to platforms-development in FW

.github/workflows/terraform-pagerduty.yml
Another case of the slack failure notification being send on PR failure rather than a failure on merge.
=> Fix failure notification on PR

terraform/environments/core-vpc/vpc.tf
Where customers have a requirement for application-local AWS Route53 Private zones, we allow them to create those zones but not to associated them with the relevant business-unit VPC that is shared with their account.
This PR will add the ability for the role assumed by the `provider.core-vpc` used by customers to associate a VPC with a private Route53 zone.
=> Allow shared VPCs to be associated with private zones

terraform/environments/core-vpc/vpc.tf
Reverts ministryofjustice/modernisation-platform#4383
Because the `aws_route53_zone` resource requires a `vpc_id` in order to create a private zone, and since the VPC is only shared with member accounts and thus there are not sufficient permissions to create and associate the zone, this PR is being reverted so that we can approach this in a more considered fashion
=> Revert "Allow shared VPCs to be associated with private zones"

terraform/environments/core-network-services/firewall-rules/inline_rules.json
* Ensures that only traffic to HTTP hosts in `allowlist` are permitted through network firewall
* Amend names and allowed sources for 3rd party saas monitoring traffic
=> Trim traffic permitted through inspection VPCs

terraform/environments/core-network-services/secrets.tf
* Add `aws_kms_alias`
* Add KMS policy document
* Apply KMS policy document
NB. From what I can see in the code, this KMS key isn't actively used for CloudWatch encryption, but could do so in future, and as such this new policy should be appropriate for its intended use.
=> SCA fixes for core-network-services

terraform/environments/core-network-services/firewall-rules/fqdn_rules.json, terraform/environments/core-network-services/firewall-rules/inline_fqdn_rules.json
Updated fqdn_rules.json with a http url allow for Edge browser updates. https://learn.microsoft.com/en-us/deployedge/microsoft-edge-security-endpoints
This is because there are very few options available on Windows servers (using Edge) to force the browser to use HTTPS... 
Without this the browser update process initialises and then never completes...
=> add edge download update url to allow list in mod-platform firewall

terraform/pagerduty/member-services-integrations.tf
Terraform runs for PagerDuty are failing with a message like...
```
Error: PUT API call to https://app.pagerduty.com/integration-slack/workspaces/T02DYEB3A/connections/P5YNAW3 failed 400 Bad Request. Code: 0, Errors: <nil>, Message: You don't have Slack permission to that channel or we couldn't find it. Please connect another channel or contact your Slack admin to try again.
```
From what I can see the channel ID is incorrect, so this should adjust the code to match the correct channel ID
=> Update mojfin pagerduty chanel ID

.github/workflows/modernisation-platform-account.yml
Stops us getting slack failure messages to the channel if it's on a PR
=> Modify so only trigger on main

terraform/environments/core-shared-services/ecr_repos.tf
Allows us to push to ECR using our OIDC role
Related: https://github.com/ministryofjustice/modernisation-platform-environments/pull/2691
=> Add Data Platform OIDC role to Data Platform repos

terraform/environments/core-shared-services/ecr_repos.tf, terraform/modules/app-ecr-repo/main.tf
Part of our workflow checks for the existence of the tag in ECR
```bash
imageTag=$(aws ecr describe-images \
--registry-id "XXXXXXX" \
--repository-name "XXXXXXX" \
| jq -r --arg imageTag "" '.imageDetails[] | select(.imageTags[] == $imageTag) | .imageTags[]')
export imageTag
if [[ -z "${imageTag}" ]]; then
echo "tag_exists=false" >>"${GITHUB_ENV}"
else
echo "tag_exists=true" >>"${GITHUB_ENV}"
fi
```
However this returns
```bash
An error occurred (AccessDeniedException) when calling the DescribeImages operation: User: arn:aws:sts::***:assumed-role/data-platform-github-actions/GitHubActions is not authorized to perform: ecr:DescribeImages on resource: arn:aws:ecr:eu-west-2:XXXXXXX:repository/XXXXXXX because no resource-based policy allows the ecr:DescribeImages action
```
---
Also, fix …
=> Allow push principal to describe ECR images

.github/workflows/new-environment.yml
This is the initial code change for the set-output lines on the modernisation-platform repo.
It is based on the code shown in the call log and other research I have done.
It cannot be tested so it will only be "hit" when we create a new environment. Testing will take place when this is run as the code is in new-environment.yml file under the github workflows.
Reference to changes from the call - https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Changes to set-output code as shown in link on the call log

terraform/environments/core-network-services/firewall-rules/production_rules.json
In lieu of a full list of PPUD customers, this rule will allow access to PPUD via the PTTP Transit Gateway for on-premise customers.
=> Temp rule for access to ppud-production

terraform/modules/vpc-inspection/main.tf
Switch to use new attribute for `aws_eip` in vpc-inspection module.
=> Update deprecated value in vpc-inspection module

terraform/environments/data-platform-apps-and-tools/iam-policies.tf, terraform/environments/data-platform-apps-and-tools/iam-roles.tf, terraform/modules/vpc-inspection/main.tf
* Use of commit hashes is not supported for Terraform Module registry
* See [this terraform issue](https://github.com/hashicorp/terraform/issues/29867) for more detail
* Added skip around `aws_eip` resources as these are used by NAT gateways
=> addressed checkov failures

terraform/environments/bootstrap/delegate-access/policies.tf
We require Glue Permissions for Optimising the Glue ETL Jobs, Cloudwatch Permissions are required for Monitoring Glue Jobs, 
Ref: https://docs.aws.amazon.com/glue/latest/ug/getting-started-min-privs.html#getting-started-min-privs-cloudwatch
=> Glue Permissions and CW Dashboard

environments/data-platform.json
Data Platform is holding a hackathon on its All-Hand on the 11th of July. This group is a temporary way to grant participants AWS access and will be retired after the hackathon is complete.
=> Granting Hackathon Team Sandbox Access

terraform/environments/core-network-services/firewall-rules/preproduction_rules.json, terraform/environments/core-network-services/firewall-rules/production_rules.json
As the PPUD team do not presently have a definitive list of customer network address ranges, this PR allows internal users to get access to the PPUD UAT environment.
=> Allow access to PPUD UAT environment

terraform/environments/bootstrap/delegate-access/policies.tf
Customers should be empowered to raise appropriate service requests. This PR adds the `servicequotas:*` permission to the developers policy which will allow customers to handle their own quota requests.
=> Allow developers to self-service quota requests

terraform/github/locals.tf, terraform/github/teams.tf
This github team will be used to give users permissions to access the long term storage account.
=> Create a github team to give long term storage

.github/workflows/terraform-member-environments.yml, scripts/terraform-workspace.sh
In line with [this story](https://github.com/ministryofjustice/modernisation-platform/issues/4365), this PR introduces a workflow that watches for changes to `terraform/environments/**/*.tf`.
This new action should, on the creation of a PR, get a list of directories with changes, and then use this to run a `terraform plan` for each workflow of the changed environment.
A future PR will then introduce the following:
* Output a .tfplan from the plan step
* Introduce a `terraform apply` job with `development` and `test` environments that consumes the relevant .tfplan files.
Following this, another PR will add a `terraform apply` job that will be executed when a branch is merged into main with `preproduction` and `production` with environment protection rules that require approval before …
=> Workflow for customer environment changes

scripts/internal/get-application-data-summary/main.go
Improve the script by listing out member-unrestricted and mp controlled accounts as well.
=> Add other account types to script

terraform/environments/bootstrap/delegate-access/policies.tf
Adds `ce:CreateReport` to data engineering role
Resolves https://github.com/ministryofjustice/data-platform-support/issues/152
=> ❇️ Add Cost Explorer's Create Report permission for Data Engineers

terraform/environments/secrets.tf
This is to test the new OIDC role that will later be used for CICD in other repositories. This is to satisfy https://github.com/ministryofjustice/modernisation-platform/issues/3909 .
=> Adding MODERNISATION_PLATFORM_ENVIRONMENTS to the configuration management repo

source/runbooks/creating-accounts-for-end-users.html.md.erb
Updated section 6 as the editing of the PR to comment out any environments that are not used in the GitHub Actions workflow file is no longer required.
=> 📝 Update to creating new environments for end users

source/team/vision.html.md.erb
Correcting a typo and replacing 'environment' with 'platform' in first line
=> Doc/amend vision - correct typos

terraform/environments/corporate-staff-rostering/iam.tf
This is to add the`AWSApplicationDiscoveryAgentAccess` policy to the management/automation/migration user in the CSR accounts, as requested by CSR team [here](https://mojdt.slack.com/archives/C013RM6MFFW/p1689607431807879).
=> Adding AWSApplicationDiscoveryAgentAccess to CSR automation user

terraform/environments/core-shared-services/ecr_repos.tf
Adds ECR repo to store containers used for the get_glue_metadata lambda function
=> add ecr repo for get_glue_metadata lambda function

terraform/environments/corporate-staff-rostering/iam.tf
As per Slack conversation https://mojdt.slack.com/archives/C013RM6MFFW/p1689764646387769 this PR adds the `AWSMigrationHubFullAccess` policy to the MGN-Test user.
=> Add MigrationHub policy to MGN-Test user

terraform/environments/bootstrap/delegate-access/policies.tf
Have added these permissions as are required to disable and enable object created event triggers in eventbridge, during a migration exercise
=> add enable, disable event permissions to data engineer policy

terraform/environments/core-network-services/firewall-rules/inline_fqdn_rules.json, terraform/environments/delius-jitbit/iam.tf, terraform/modules/vpc-nacls/data.tf
As discussed in [this slack thread](https://mojdt.slack.com/archives/C01A7QK5VM1/p1689849118728639), SES is not always an appropriate choice for customers to relay outbound email through. While we would generally prefer that SES be used, this PR will allow customers in the same situation as the JitBit application to send traffic out over the [SMTP submission port](https://www.cloudflare.com/en-gb/learning/email-security/smtp-port-25-587/#:~:text=The%20official%20default%20port%20for%20SMTPS%20is%20port%20587.%20SMTPS%20connections%20start%20with%20a%20%22STARTTLS%22%20command%20to%20let%20the%20mail%20server%20know%20that%20the%20SMTP%20traffic%20will%20be%20sent%20over%20TLS.)
Further to this, this PR removes the now-unneeded SES users that were created previously.
=> Allow customers to send outbound email through egress VPCs

.github/workflows/bootstrap-sprinkler.yml
As per https://github.com/ministryofjustice/modernisation-platform/issues/4095, this PR amends the name of the `bootstrap-sprinkler-plan.yml` and adds steps to conduct a `terraform apply`.
The apply steps all reference the `production` environment as it, presently, has a defined reviewer. Although the `development` environment also currently references a reviewer, it is not a certainty that this will continue to be the case.
=> Add apply steps to bootstrap-sprinkler.yml

.github/workflows/terraform-member-environment.yml
Noticed I didn't have slack failure notifications in my workflow - I'd removed them previously while I was working on it but forgot to reinstate them when I was finished.
=> Added slack failure notifications to bespoke environment changes

terraform/environments/bootstrap/delegate-access/policies.tf
As per Slack conversation [here](https://mojdt.slack.com/archives/C013RM6MFFW/p1690193214354109) this PR adds the discovery:* permissions to the migration role. If this fails to resolve the issue for the users I believe the next step would be to add the 'AWSApplicationDiscoveryServiceFullAccess' policy to the migration role as per David E. suggestion.
=> Add discovery permissions to migration role

terraform/environments/core-network-services/firewall-rules/inline_fqdn_rules.json
In line with [this request](https://mojdt.slack.com/archives/C01A7QK5VM1/p1689849118728639), this PR amends the filtering for traffic to `office365.com`.
=> Allow traffic to wider range of office365 addresses

terraform/environments/corporate-staff-rostering/iam.tf
Users have installed the agent on two servers (1 Windows, 1 Linux) using the mgn-test user however these are visible on the migration, this PR bumps up the permissions (same as ppud user) to hopefully resolve this while continuing to investigate.
=> Add AWSApplicationMigrationFullAccess permission for CSR

terraform/environments/core-network-services/firewall-rules/inline_rules.json, terraform/modules/vpc-nacls/data.tf
As per Slack conversation [here](https://mojdt.slack.com/archives/C01A7QK5VM1/p1689849118728639) this PR adds two new firewall rules for hmpps-dev to any for ports 465 & 587 and also updates the nacls to include port 465 (587 already existed)
=> add inline firewall rule and update nacls vpc

.github/workflows/terraform-member-environment.yml
The `terraform-member-environments` workflow file has an accidental typo in it where it conducts a `git diff` on a completed pull request. This PR removes the typo.
You can see an example of this causing a workflow to fail [here](https://github.com/ministryofjustice/modernisation-platform/actions/runs/5656256881/job/15324268633).
=> Fix typo in workflow file

environments/corporate-staff-rostering.json
Following on from some troubleshooting with Hope and the addition of permissions to the migration user, Hope has requested for the migration user to be configured on the development environment.
=> Add migration level access to CSR development

environments-networks/hq-development.json, environments-networks/hq-preproduction.json, environments-networks/hq-production.json, terraform/environments/core-network-services/firewall-rules/development_rules.json, terraform/environments/core-network-services/firewall-rules/preproduction_rules.json, terraform/environments/core-network-services/firewall-rules/production_rules.json, terraform/modules/vpc-nacls/data.tf
As part of https://github.com/ministryofjustice/modernisation-platform/issues/4538, this PR allows traffic from MOJ Global Protect users to access a redshift VPC endpoint.
There would also need to be a corresponding change to the [modernisation-platform-terraform-member-vpc](https://github.com/ministryofjustice/modernisation-platform-terraform-member-vpc/blob/d568b0d83bb7cec82ee9eddb7c264cf8c02757a4/main.tf#L317) module to amend the security group, and a method for an AWS Load Balancer target group attachment to discover the relevant IP address (probably a combination of a data call and a for_each expression).
=> Allow access to Redshift VPC endpoint from Global Protect users

environments-networks/hq-development.json, environments-networks/hq-preproduction.json, environments-networks/hq-production.json
From further research, it appears that the `redshift-data` endpoint is the appropriate option for RedShift Serverless querying.
=> Update redshift VPC endpoint type

terraform/environments/bootstrap/delegate-access/policies.tf
A user is currently receiving an error when trying to view the recommendations on the migration hub. This PR adds the migrationhub-strategy permissions to the migration user.
=> Add migrationhhub strategy permissions

terraform/environments/core-vpc/vpc.tf
This PR updates the version of the `modernisation-platform-terraform-member-vpc` module; the latest release includes an amendment to the VPC Endpoint security group common to VPCs created with this module. In order to accommodate VPCs that make use of AWS Redshift endpoints, the security group needs to include `tcp/5439` in its allowed inbound traffic.
This should be the last piece needed for https://github.com/ministryofjustice/modernisation-platform/issues/4538
=> Allow Redshift access to Redshift endpoints

.github/workflows/terraform-member-environment.yml
According to the [GitHub documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths) on path filtering, I believe that the current path options are causing the `terraform-member-environments` action to trigger inappropriately when changes are made to terraform files in `core-*`.
Although the ordering is correct, I think that the use of `**/*.tf` is being matched and as it is more specific than `!core-*`, exclusions are not being applied as originally anticipated.
=> Fix inappropriate triggering of `terraform-member-environments`

terraform/environments/core-network-services/route53.tf
Following [this request](https://mojdt.slack.com/archives/C01A7QK5VM1/p1690384894123369) on Slack, and based on the name meeting suitable qualifying criteria (a well known, internal tool), this PR adds a DNS zone for `dacp.service.justice.gov.uk` to the `core-network-services` account.
We will need to liaise with the Ministry of Justice P&A Operations Engineering team to delegate this domain across to the Modernisation Platform.
=> Add application zone for dacp

terraform/environments/bootstrap/delegate-access/policies.tf
As per Slack request [here](https://mojdt.slack.com/archives/C01A7QK5VM1/p1690461621394229) Ijaz has requested Application Migration Service permissions. 
(also sorted permissions alphabetically)
=> Add application migration services permissions to migration user

.github/workflows/terraform-member-environment.yml
As the `terraform-member-environments` workflow did not exclude the bootstrap directories, changes here caused an inappropriate triggering of the workflow.
=> Exclude bootstrap subdirectories from member-environments updates

terraform/environments/bootstrap/member-bootstrap/iam.tf
Investigating the use of this OIDC policy showed that the original value was insufficient for use cases of the role.
When an attempt was made to use this through a PR in a different repository (`ministryofjustice/modernisation-platform-configuration-management`), a subject value was being supplied through as `sub:ministryofjustice/modernisation-platform-configuration-management:pull_request`).
This PR updates the permitted subject claims to allow any value. You can see more detail on subject claims [here](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#example-subject-claims).
=> Updated subject value used in oidc role for cicd user

terraform/environments/core-network-services/firewall-rules/inline_fqdn_rules.json
PR to add `archive.ubuntu.com` to allowed domains as per slack request [here](https://mojdt.slack.com/archives/C01A7QK5VM1/p1691052534081459)
=> update allowed_domains inline fqdn list to include archive.ubuntu.com

terraform/environments/core-network-services/firewall-rules/inline_fqdn_rules.json
As per Slack conversation: https://mojdt.slack.com/archives/C01A7QK5VM1/p1691052534081459 if further Ubuntu subdomains are required can update the list reflect *.ubuntu.com
=> Add security.ubuntu.com to allowed_domains

terraform/environments/core-network-services/iam.tf
As per slack [request](https://mojdt.slack.com/archives/C01A7QK5VM1/p1691055181067629) i am adding the hosted zone to the policy as a temporary workaround while the bug/issue is investigated.
=> Temporarily add aws dev legalservices hostedzone to dns iam policy

terraform/environments/core-network-services/firewall-rules/fqdn_rules.json
As per Slack conversation: [here](https://mojdt.slack.com/archives/C01A7QK5VM1/p1691052534081459) adding ubuntu domain to fqdn rules.
=> Add Ubuntu to firewall rules

environments/corporate-staff-rostering.json
New group csr-application-support created to allow App support team access to CSR resources in AWS. 
Added to Test, PreProd, and Prod.
=> feat: adding new application support github group to CSR envs

terraform/environments/core-network-services/firewall-rules/fqdn_rules.json
As per Slack conversation [here](https://mojdt.slack.com/archives/C01A7QK5VM1/p1691052534081459) Umesh has request the below domain be whitelisted for the PPUD server docker build. 
```
.docker.io
.docker.com
.ubuntu.com
.ghcr.io
```
=> Add firewall rules to allow PPUD server docker build

terraform/environments/bootstrap/delegate-access/policies.tf
as part of the bellow request from the ask channel i have added the decode permission to the migration role
Hi MP. Update regarding the Migration tool issue that was raised last week after raising the issue with AWS they have gotten back to us and told us the following message :
"As we can confirm from the backend and your screenshot that the Test EC2 instance is not getting launched due to conversion failed, the internal team to further review your issue has checked the "RunInstances" API call to see if the conversion server has been launched successfully. We can confirm that the conversion server is not getting launched with the following information:
Error code: Client.UnauthorizedOperation"
They then asked us to run the following command from CLI :
aws sts decode-authorization-message …
=> Decode added to migration role for fault finding

scripts/provision-environment-directories.sh, scripts/provision-member-directories.sh, terraform/environments/core-logging/base_variables.tf, terraform/environments/core-logging/networking.auto.tfvars.json, terraform/environments/core-network-services/base_variables.tf, terraform/environments/core-network-services/networking.auto.tfvars.json, terraform/environments/core-sandbox/base_variables.tf, terraform/environments/core-sandbox/locals.tf, terraform/environments/core-sandbox/networking.auto.tfvars.json, terraform/environments/core-sandbox/playground.tf, terraform/environments/core-security/base_variables.tf, terraform/environments/core-security/networking.auto.tfvars.json, terraform/environments/core-shared-services/base_variables.tf, terraform/environments/core-shared-services/networking.auto.tfvars.json, terraform/environments/core-vpc/base_variables.tf, terraform/environments/core-vpc/networking.auto.tfvars.json, terraform/environments/sprinkler/base_variables.old
This PR relates to https://github.com/ministryofjustice/modernisation-platform/issues/4139. As we make use of `networking.auto.terraform.tfvars` to share resources, it's not relevant to our core accounts and as such this PR makes its creation conditional.
* Updates the scripts that output this file to conditionally skip the creation when we read the account type from `environments/*.json` and see that they account-type value is core.
* Removes `networking.auto.terraform.tfvars` from core accounts.
* Adds defaults to `base_variables.tf` for both core-sandbox and core-vpc accounts to accommodate removal of tfvars.
* Tidies up some of core-sandbox account to remove some unused code and fix a broken data call.
=> Conditionally generate tfvars for non-core accounts

terraform/environments/core-network-services/iam.tf
This PR updates the hosted zone id for the dev.legalservices.gov.uk - This is an update from https://github.com/ministryofjustice/modernisation-platform/pull/4731
=> Update dev legalservices hostedzone id in dns iam policy

.github/workflows/new-environment.yml
In line with the guidance offered by GitHub [here](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings), this PR uses field delimiters to allow the output of multiline strings into the `$GITHUB_OUTPUT`.
=> Wrap git diffs into delimiters to handle multiline outputs

.github/workflows/terraform-member-environment.yml
Using `HEAD~` in the workflow results in the following error because it is ambiguous:
```
From https://github.com/ministryofjustice/modernisation-platform
* branch            main       -> FETCH_HEAD
fatal: ambiguous argument 'HEAD~': unknown revision or path not in the working tree.
```
Using `HEAD^` should ensure the correct parent is used. You can see an example of the failure in action here: https://github.com/ministryofjustice/modernisation-platform/actions/runs/5830970854/job/15813426954
=> Amend how workflow compares on push to `main`

terraform/environments/core-network-services/iam.tf
Following slack conversation [here](https://mojdt.slack.com/archives/C01A7QK5VM1/p1691484375454639) as the hosted zone id changing following an update this PR uses s `data` block to obtain the zone_id.
=> Add data block for use in portal-dev dns IAM policy

terraform/modules/iam_baseline/main.tf
Lambda update / invoke PR appears to have triggered a Checkov error, but as this change is intentional, I've set to skip the check
=> added checkov exclusion

terraform/environments/bootstrap/delegate-access/policies.tf
User has requested extra permission for a restore
Silviana Horga
[9 minutes ago](https://mojdt.slack.com/archives/C01A7QK5VM1/p1692106046491899)
Hi MP team,
I’m trying to perform an EFS backup restore locally using AWS CLI but I get the following error
An error occurred (AccessDeniedException) when calling the StartRestoreJob operation: User:xxxx is not authorized to perform: backup:StartRestoreJob on resource: arn:aws:backup:eu-west-2:326912278139:recovery-point:ef633021-fdd3-4db6-b986-2beb406e1aad because no identity-based policy allows the backup:StartRestoreJob action
Can I be granted permissions to perform the action above? Or is there another method we must use to perform a backup restore?
adding backup:StartRestoreJob to the sandbox policy
=> Extra permissions on sandbox

terraform/environments/data-and-insights-wepi/additional_subnet_share.tf
As part of https://github.com/ministryofjustice/modernisation-platform/issues/4797, this PR handles the association between the `data-and-insights-wepi` accounts, and the resource share for the protected subnets.
=> data-and-insights-wepi subnet association

terraform/environments/core-network-services/vpn.tf
This PR relates to https://github.com/ministryofjustice/modernisation-platform/issues/4523
Adds a host route for each of the NOMS Transit Live VPNs for testing purposes.
With this we can attempt to connect to the endpoint host and confirm the routing behaviour.
=> added static routes across both NOMS vpns for testing

terraform/environments/core-network-services/vpn.tf
This PR relates to https://github.com/ministryofjustice/modernisation-platform/issues/4523 and proves that we can't apply duplicate static routes to a TGW route table:
```
Error: creating EC2 Transit Gateway Route (tgw-rtb-xxxxxxxxxxxx_10.102.1.179/32): RouteAlreadyExists: Route 10.102.1.179/32 already exists in Transit Gateway Route Table tgw-rtb-xxxxxxxxxxxx.
```
=> Remove NOMS test routes

terraform/environments/core-network-services/firewall-rules/development_rules.json
This PR is to allow LAA Landing Zone WorkSpaces access to our Portal Windows Instance via RDP for testing purposes. Once the environment is good and ready for cutover, this rule will be removed.
https://dsdmoj.atlassian.net/browse/LAWS-3432
=> Allow RDP from LAA LZ to MP LAA

.github/workflows/terraform-member-environment.yml
The current path filtering still appears to be triggering inappropriately. This change should prevent changes anywhere but in customer environments from triggering the workflow
=> 🪛 Fix member-environments bespoke changes workflow to avoid accidental recursive matching

terraform/environments/bootstrap/secure-baselines/main.tf
This will move update to the latest module removing the creation of the security hub resource which is now handled at the org level.
Note the plan for sprinkler secure baselines runs clean (security hub resource has been removed from state).
=> Bump secure baselines module

.github/workflows/terraform-member-environment.yml
Updated this in line with GitHub documentation [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths).
=> Update path matching for member environment changes

terraform/pagerduty/locals.tf, terraform/pagerduty/policy-schedules.tf
As discussed within the team, adding Mark and Aaron to our MP on-call rota.
Note, the immediate on-call schedule (~next two months) will be preserved by manual overrides after this code gets merged.
The TF plan has been run manually with no issues.
=> Enrolling Mark and Aaron onto MP on-call rota

environments/cooker.json, scripts/git-create-environments.sh
This PR updates the `scripts/git-create-environments.sh` to include an optional `additional-reviewers` function which can be provided in the application .json file (example here: `environments/cooker.json`). This additional function uses the patch method to update the list of reviewers.
The script has also been updated to handle pagination to fetch more than 100 environments from the GitHub API.
=> :sparkles: Add Additional Reviewers

terraform/environments/bootstrap/secure-baselines/main.tf, terraform/modernisation-platform-account/baselines.tf
Changing the code to point to the v7.0.0 release on modernisation-platform-terraform-baselines.
=> Changed release to v6.1.0 for backup changes

terraform/modernisation-platform-account/baselines.tf
This includes a bump of the node.js that the lambda is using to v.18 and the migration of the AWS SDK from v2 to v3.
Tested locally and in the console.
=> Bumping the version of trusted advisor lambda function

terraform/environments/bootstrap/member-bootstrap/instance-scheduler.tf
This Pr is part of [Add RDS instances to instance scheduler#4673](https://github.com/ministryofjustice/modernisation-platform/issues/4673) as we have found that the role needs addtional permissions to be able to read rds
=> Permissions update

terraform/environments/core-shared-services/ecr_repos.tf
When I copied the previous ECR repo config, I forgot to change the retrieval policy to reflect the corresponding lambda which will use the repo.
=> Corrected retrieval policies for ECR repos

cidr-allocation.md
Originally it was thought that Data Platform would only consume a small amount of compute for Amazon MWAA, but that is changing now we're also hosting other components that require non-shared networking.
This PR:
- allocates a development/test range
- updates allocation name
=> Update Data Platform CIDR allocation

terraform/environments/core-shared-services/ecr_repos.tf
We want to terratest locally connected to DE sandbox . This has capability to apply from locally . We need for POC.  The infrastructure has lambda image which need to be pulled  and created in sandbox account
=> Allow DE sandbox to pull image for testing POC

terraform/environments/core-network-services/firewall-rules/development_rules.json
- changes to development environment firewall rules for testing adding corporate-staff-rostering-development Windows servers trying to connect to the AD domain in fixngo
- have looked at the inbound rules for NOMSMgmt-Core-NSG as a guide 
- as far as I can tell wrt fixngo we allow all TCP IN, TCP OUT and UDP IN 
- previously UDP out to fixngo blocked all UDP OUT apart from port 53 (udp dns) and 1521 (udp database)
- Kerberos ports included to allow DSO team members to test Linux domain join
=> tentative *-development env changes allow EC2 connections to fixngo ad

terraform/environments/bootstrap/delegate-access/policies.tf
User is having issues running Athena queries from the console see bellow: - 
Morning team, no rush on this, but I’m trying to query nomis-preproduction load balancer logs via Athena in AWS console but get below error.  If I try athena:StartQueryExecutionin [IAM Policy Simulator](https://policysim.aws.amazon.com/home/index.jsp?#roles/developer) it says denied by AWS Organization SCPs.  Any clues?
You are not authorized to perform: athena:StartQueryExecution on the resource. After your AWS administrator or you have updated your permissions, please try again.
adding this permission to the developer role
=> Ask channel request

terraform/environments/bootstrap/member-bootstrap/ssm.tf
This will sync the inventory information in all member accounts to an S3 bucket in the Organisation security account.
From here analysis can be conducted on things like Oracle licensing.
=> Add SSM data sync resource in member accounts

environments/sprinkler.json, scripts/git-create-environments.sh
Following on from PR https://github.com/ministryofjustice/modernisation-platform/pull/4945 where the additional_reviewers function could not be used to 'patch' in additional reviewers I have created/updated the below functions...
`get_github_team_id`: Retrieves GitHub Team ID
`get_github_user_id`: Retrieves GitHub User ID 
`create_team_reviewers_json`:  formats team reviewers ready for the GitHub API.
`create_user_reviewers_json`: formats user reviewers ready for the GitHub API.
`create_reviewers_json`: combines the above outputs ready for the environment creation/update.
Previous payload example: `Payload: {"reviewers": [{"type":"Team","id":1234567}]`
New payload example (including additional reviewer:  `payload='{"reviewers": [{"type":"Team","id":1234567},{"type":"Team","id":7654321},{"t …
=> ✨ : Add Additional Reviewers Functionality

source/user-guide/creating-environments.html.md.erb
This PR updates the creating-environments user guide following the addition of the feature to add additional reviewers.
I have also updated the example code blocks updated to include ‘additional reviewers’, ‘github-oidc-team-repositories’ and ‘go-live-date’.
=> 📝 Update Creating-Environments Documentation

terraform/environments/bootstrap/delegate-access/policies.tf
While developers can create manual RDS snapshots, they cannot share these snapshots between accounts.
As this is an occasional task that developers need to accomplish, this PR adds the `rds:ModifyDBSnapshotAttribute` permission to the `developer_addtional` policy which will permit this action.
=> Allow developer role to share RDS snapshots

.github/workflows/core-logging-deployment.yml, .github/workflows/core-network-services-deployment.yml, .github/workflows/core-security-deployment.yml, .github/workflows/core-shared-services-deployment.yml
The new Terratest versions highlighted by dependabot require Go version `1.21.x` to run. This PR bumps the versions in use by our current tests.
=> Bump Go version

environments/performance-hub.json
following on a rebase that went a little bit wrong (https://github.com/ministryofjustice/modernisation-platform/pull/5003) I have created a new PR on @jemnery's behalf with the oidc changes they committed.
=> Add repo name for performance-hub

.github/workflows/core-logging-deployment.yml, .github/workflows/core-network-services-deployment.yml, .github/workflows/core-security-deployment.yml, .github/workflows/core-shared-services-deployment.yml
This PR resolves https://github.com/ministryofjustice/modernisation-platform/issues/5056
It replaces the direct acquisition of a Go runtime with one installed through a GitHub action, and trims the Terratest section of the Plan job to remove now unnecessary conditional handling.
=> Update defensive tests for core accounts

.github/ISSUE_TEMPLATE/story-template.md
changing the title on the old form for now as the two titles are the same on the new form and the old form and this is preventing the new form from being shown on the list when you click on new issue
=> changing the title

terraform/modules/firewall-policy/main.tf, terraform/modules/firewall-policy/variables.tf, terraform/modules/vpc-inspection/firewall.tf, terraform/modules/vpc-inspection/variables.tf
As part of https://github.com/ministryofjustice/modernisation-platform/issues/2934, this PR allows to optional use of a new variable for firewall policies: `fw_managed_rule_groups`.
The AWS managed firewall rule groups can be found here: https://docs.aws.amazon.com/network-firewall/latest/developerguide/aws-managed-rule-groups-threat-signature.html
To apply these rule groups to an existing firewall policy (for example. through the inspection VPC module in `core-network-services/vpc.tf` we would supply a list like so:
```
module "vpc_inspection" {
for_each = local.networking
source                = "../../modules/vpc-inspection"
...
fw_managed_rule_groups = ["ThreatSignaturesBotnetActionOrder", "ThreatSignaturesEmergingEventsActionOrder"]
}
```
There might need to be further discussion …
=> Allow use of AWS managed firewall rule groups

terraform/github/repositories.tf
In relation to [Migrate modernisation-platform-terraform-trusted-advisor lambda function to Go#5054](https://github.com/ministryofjustice/modernisation-platform/issues/5054)
This change adds the `testing-ci` IAM user credentials to the `modernisation-platform-terraform-trusted-advisor` repository.
This will enable writing terratests for the current IaC to ensure migrating to Go does not impact current functionality.
=> ✨ Add `testing-ci` user to `modernisation-platform-terraform-trusted-advisor`

environments/planetfm.json, terraform/environments/planetfm/iam.tf
This PR covers work requested from the ask channel bellow
Hope Aitchison
:spiral_calendar_pad:  [09:02](https://mojdt.slack.com/archives/C01A7QK5VM1/p1695369742393229)
Morning Mod platform! :slightly_smiling_face:
We need analogous IAM changes made to Planet FM environments (Dev to Prod) as we have had made in CSR (corporate staff rostering)
If you could please create us this MGN user https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/environments/corporate-staff-rostering/iam.tf
And we'll need the federated user migration role added to the Planet FM environments too https://github.com/ministryofjustice/modernisation-platform/blob/c480b10e3a23cc7dd547db8f75e06beb0b04fd11/terraform/environments/bootstrap/delegate-access/policies.tf#L471
We'll be replicating all …
=> New iam user for planetfm

terraform/environments/core-network-services/firewall-rules/development_rules.json, terraform/environments/core-network-services/firewall-rules/fqdn_rules.json, terraform/environments/core-network-services/firewall-rules/inline_fqdn_rules.json, terraform/environments/core-network-services/firewall-rules/preproduction_rules.json, terraform/environments/core-network-services/firewall-rules/production_rules.json, terraform/environments/core-network-services/firewall-rules/test_rules.json
- allow all TCP traffic back from mp environments to the related azure fixngo NSG's
- allow PowerShell Gallery CDN endpoint for external traffix
- fix incorrect destination_ip in the development rules
=> allow TCP all from mp to related fixngo destinations

terraform/environments/core-network-services/locals.tf
These routes are no longer used and serve no purpose; they're not referenced in any code, or installed in any route tables.
=> 🗑️ Removed unused routes for sixdg

terraform/environments/core-network-services/firewall-rules/test_rules.json
as per slack request https://mojdt.slack.com/archives/C01A7QK5VM1/p1695998966079929 this PR adds a firewall rule for cloud platform to laa-test on port 1521
=> Add firewall rule for CP to Laa Test

terraform/environments/core-network-services/locals.tf, terraform/environments/core-network-services/transit_gateway_connections.tf, terraform/environments/core-network-services/vpn.tf
* Creates a filtered set of attachment IDs for the `NOMS` VPN connections
* Uses this set to create propagation statements to add advertised routes into the `Inspection` TGW route table
* Moves some config around to a more logical location (eg, where the rest of the VPN/TGW config is located)
This will ensure that once I remove static routes from the `Inspection` TGW route table they are immediately replaced by propagated routes learned via BGP. As a consequence I will then be in a position to start removing the locals that cover static routes for NOMS connections.
=> 🧱 Propagate advertised routes into Inspection route table

environments/tipstaff.json
The original email address that is in the environment file for Tipstaff has an automatic response saying the folowing:
> Thank you for your email. This mailbox closed on 31st August 2023 and is no longer monitored. Please resend your email to [DTS-ITServiceDesk@justice.gov.uk](mailto:DTS-ITServiceDesk@justice.gov.uk) to be actioned. This e-mail is private and is intended only for the addressee and any copy recipients. If you are not an intended recipient, please advise the sender immediately by reply e-mail and delete this message and any attachments without retaining a copy. Activity and use of this communication is monitored to secure their effective operation and for other lawful business purposes. Communications using these systems will also be monitored and may be recorded to secure …
=> Updating contact details for Tipstaff

environments/apex.json
For the migration, the team will need permissions to create AMIs from snapshots, and it would be good to know if the migration role has this permission and that it would work.
=> Developer to migration role.

terraform/environments/core-network-services/firewall-rules/inline_fqdn_rules.json
Following a request in [this Slack thread](https://mojdt.slack.com/archives/C01A7QK5VM1/p1696332394159879), this PR adds a domain to the list of allowed HTTP destinations through the egress VPCs and their inline AWS Network Firewalls.
=> Allow http traffic to amazontrust.com

environments/eric.json, policies/environments/expected.rego
Account request from the ask channel
This PR covers the work for creation of the Eric accounts requested bellow
Hello Team,
As part of migrating LAA application to MP can you create an aws account for application called eric for test and production environment please. We want to start moving the ec2 instance across to the MP account
Regards
Tunde
=> New Account request for ERIC

terraform/environments/bootstrap/delegate-access/locals.tf
Delegated access work flow failed for the eric account as the alias was not unique this pr adds eric to the skip list on delegated access locals
=> Fix for delegated access

terraform/environments/core-network-services/iam.tf
As part of #5001 I replaced the `read-dns` role with `read-logs`. This had some unanticipated side effects around how users were making use of the `read-dns` role and how it was assumed. While we work on the issues around assuming the `read-logs` role, this PR will create a role named `read-dns` and attach an AWS-managed IAM policy.
The policy details can be see here: https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AmazonRoute53ReadOnlyAccess.html
They broadly cover the same scope as the old `ReadDNSRecords` inline policy, but allow role assumers to also get the value that Route 53 returns in response to a DNS request.
=> Reintroduce read-dns role

terraform/environments/bootstrap/member-bootstrap/locals.tf, terraform/environments/bootstrap/member-bootstrap/ssm.tf
Currently the bucket policy and KMS policy in the organisation security account SSM resource sync bucket require account numbers to be added in order to restrict access to the organisation, as you can't use org principal paths with service principals (ssm in this case).  This has been raised with AWS and a feature request added.  Until then our options are limited as we can't create the resource sync until the org sec terraform has run after the new account is created and then the account has permissions to the bucket.
Triggering the org sec to run after the env is created but before the bootstrap runs is a possibility, but not at this point as the org sec tf is run manually.  This looks to be the only way to ensure that this pipeline doesn't fail because of this, but it does mean there …
=> Change SSM resource sync to be opt in

.github/workflows/terraform-member-environment.yml
GIHUB_OUTPUT doe not play well with multi-line outputs so in order to pass changed directories when more than one directory is impacted, what works is to encode the value as 
base64.
GITHUB_ENV has a similar problem which is why there's an export statement in every step that uses it.
An alternative approach is to pass it as json.
Example of failure here: https://github.com/ministryofjustice/modernisation-platform/actions/runs/6430537080/job/17461731958#step:3:18
=> base64 encoding/decoding multiline output to prevent errors when passing between jobs.

terraform/environments/core-shared-services/ecr_repos.tf
This creates an ECR repo that will contain images for the new lambda being introduced in https://github.com/ministryofjustice/data-platform/issues/1659
Note: We will be able to get rid of the data_platform_get_glue_metadata_ecr_repo module once this work done, but I will do this after I have removed the infrastructure that is using it.
=> Add ECR repo for new lambda

.github/workflows/terraform-member-environment.yml
This export allows the correct decoding of directories from the base64 output.
=> Add missing base64 decode to terraform-member-environments action

terraform/environments/bootstrap/delegate-access/policies.tf
Adding permission to allow modifying DMS replication tasks in the console in addition to starting and stopping them.
=> Adding permission to modify a dms replication task in the console

terraform/environments/core-shared-services/ecr_repos.tf
This will hopefully fix permission errors when pushing to core-shared-services.
example here - . https://github.com/ministryofjustice/performance-hub/actions/runs/6458192620/job/17531368318#step:5:937
=> Moving from cicd to modernisation-platform-oidc-cicd

terraform/environments/bootstrap/delegate-access/policies.tf
As part of #5001 , this PR allows the `developer` role to assume `read-log-records` so that developers with console access can read firewall logs in the `core-network-services` account.
=> Add ability for developers to assume read-log-records

terraform/environments/core-network-services/iam.tf, terraform/environments/core-vpc/vpc.tf
As part of #5001, this PR expands the inline IAM policies for the `member-delegation-read-only` and `read-log-records` roles so that Modernisation Platform customers who can assume these roles will be able to view VPC flow logs.
=> 🔧 Allow member-delegation and read-log-records ability to read flow logs

terraform/environments/bootstrap/delegate-access/policies.tf
So we can trigger Glacier S3 restores from AWS Console.
=> Give Developer role ability to restore objects from Glacier storage

environments-networks/hmpps-test.json, policies/networking/expected.rego
Delius-core-test networking configuration as per steps in https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/creating-accounts-for-end-users.html#3-create-a-pull-request-for-the-changes-in-step-1-and-2
=> add delius-core test networking configuration

terraform/environments/bootstrap/delegate-access/policies.tf, terraform/modernisation-platform-account/iam.tf
As part of https://github.com/ministryofjustice/modernisation-platform/issues/5001, the deprecated `read-dns-records` role is to be removed from the developer trust relationship. Users of the `developer` role can utilise the `read-log-records` role which will give them the same level of access to Route53 records, as well as unrelated access to CloudWatch log groups for troubleshooting.
=> :boom: Remove ability for users to assume deprecated read-dns-records role

terraform/environments/core-network-services/iam.tf
As part of #5001 we (_I_ 😅) replaced the `read-dns-records` role with `read-log-records` which expands out the access given to users. Now that we no longer make use of the `read-dns-records` role this PR removes the code used to create the role.
=> 🗑️ Remove read-dns-records role

terraform/environments/bootstrap/member-bootstrap/iam.tf
Adds:
* datasync:List* 
* datasync:TagResource
To the oidc role, so that datasync tasks, locations can be listed and tags can be added to them.
=> Add datasync permissions for oidc role

terraform/pagerduty/aws.tf, terraform/pagerduty/member-services-integrations.tf
- new slack channel for CSR alarms
- no distinction between prod and non-prod as all CSR environments are either production or pre-production
=> create pagerduty integration for csr alarms

source/user-guide/integrating-alarms-with-pagerduty-with-slack.html.md.erb
This PR corrects and error in the documentation of the example given for pager duty integration it currently states v1 of the module pager duty integration but there has been a recent release to that module that bumps it to version 2 there for amending to show that change
=> Version change within the example

terraform/environments/bootstrap/member-bootstrap/iam.tf
Add `datasync:StartTaskExecution` so that `aws datasync start-task-execution` can function
=> Add datasync:StartTaskExecution to oidc role

environments/data-platform-apps-and-tools.json, policies/environments/environment-definitions.rego, policies/environments/environment-definitions_test.rego, terraform/environments/bootstrap/single-sign-on/main.tf
Resolves https://github.com/ministryofjustice/data-platform/issues/791
Enables access to [`modernisation-platform-mwaa-user`](https://github.com/ministryofjustice/aws-root-account/blob/main/management-account/terraform/sso-admin-permission-sets.tf#L181-L187)
=> 🛂 Add MWAA User access for Data Platform Apps and Tools

.gitignore, terraform/environments/data-platform-apps-and-tools/.tfsec/config.yml, terraform/environments/data-platform-apps-and-tools/rds.tf, terraform/environments/observability-platform/iam-roles.tf, terraform/environments/observability-platform/managed-grafana.tf, terraform/environments/observability-platform/managed-prometheus.tf
Because tfsec will not obey inline exclusions (https://github.com/aquasecurity/tfsec/issues/1935) for the reported data-platform-apps-and-tools error, I've had to introduce a .tfsec/config.yml file to cover the exclusion.
=> Address SCA issues for data-platform-apps-and-tools and observability-platform

terraform/environments/data-platform-apps-and-tools/eks-cluster.tf
Reverts ministryofjustice/modernisation-platform#5258
=> Revert "Bump terraform-aws-modules/eks/aws from 19.16.0 to 19.17.2 in /terraform/environments/data-platform-apps-and-tools"

terraform/modernisation-platform-account/s3.tf
This PR adjusts the bucket policy attached to the `modernisation-platform-terraform-state` bucket to improve readability, and intent of policy statements. This should make future changes clearer in their intent, and less likely to be disruptive:
* Applies minor linting fixes (missing lines, `terraform fmt`)
* Adds missing SIDs / gently renames some SIDs for clarity
* Splits out the statement for `s3:ListBucket` and `s3:GetObject` for members of the Modernisation Platform OU into two statements
* * The first statement allows only `s3:ListBucket` to the bucket itself
* * The second statement allows only `s3:GetObject` to permitted keys inside the bucket
=> ♻️ Refactor `modernisation-platform-terraform-state` bucket policy

.github/workflows/terraform-member-environment.yml
Resolves #5272
`actions/checkout` only fetches a single commit, so when trying to perform a diff, it has no history to compare 😭 
Adding `--unshallow` should fetch the history
=> 🚑 Add `--unshallow` when fetching origin

environments/tipstaff.json
As requested by @matt-k1998 , this PR lowers the SSO permission level that Tipstaff developers will use to access their preproduction environment
=> set tipstaff preprod permissions level to developer

source/team/ways-of-working.html.md.erb
To help Modernisation Platform Engineers ensure they are following common practices when tagging and releasing software
Added documentation to our `Ways of Working` within the `Git and GitHub` section
- Mainly adding this because I recently tagged and released some software and wasn't 100% sure about the etiquette
- Still unsure if we should create a Draft version first and get this reviewed? 🤔 I left this out because it's not something I believe in. The code itself has already been reviewed and approved at the release stage. Release notes can always be changed after the fact if any issues are spotted 👀 
- I've attempted to keep the advice fairly generic, but the advice has not been agreed upon as a team, so happy for opinions and comments! 💬
=> ✨ Add docs for `Tags and Releases` in GitHub

terraform/environments/bootstrap/member-bootstrap/iam.tf
Adds ssm:PutParameter to the oidc role policy.
As part of a workflow that schedules overnight shut downs and morning start ups for ECS services, we store the state in an ssm parameter.
This was originally supposed to be a tag on the services itself, but due to a bug in the aws TF provider, this is not currently feasible due to the `tags` attribute on the data source for `aws_ecs_service` returning an empty map
=> Add ssm:PutParameter to oidc policy

terraform/modernisation-platform-account/iam.tf
Because roles are implicitly allowed access to S3 buckets in an account, this PR denies this for the limited read role to prevent unexpected disclosure of objects in S3.
=> Restrict `modernisation-account-limited-read-member-access`

terraform/modernisation-platform-account/iam.tf
Previous resource statement was incorrectly formatted.
=> Corrected resource statement to deny all access to S3 resources

terraform/environments/bootstrap/member-bootstrap/iam.tf
This PR resolves #5291 by using a conditional count statement.
I looked at using a `for_each` as an alternative, but as that would separate the contents of the `github-oidc-team-repositories` list into separate values, it would necessitate work on the `modernisation-platform-github-oidc-role` module that would then require a breaking change to the version.
=> Only create OIDC role when repositories are supplied

terraform/environments/core-network-services/route53.tf
As part of issue [Configure and publish external status page#3784](https://github.com/ministryofjustice/modernisation-platform/issues/3784) we want to implement a custom url pager duty needs these cnames so it can verify the dns we have selected the dns name of status.modernisation-platform.service.justice.gov.uk
=> cname entry's for custom pagerduty url

terraform/environments/core-network-services/route53.tf
On clicking verify on the button on pagerduty all the new cname got verified but a new on popped up that was unverified this new record is for the TLS cert
=> Addtional cname for tls

scripts/internal/get-security-hub-findings/go.mod, scripts/internal/get-security-hub-findings/main.go
This PR fixes the MaxResults pointer for the securityhub findings script, and raises the minimum Go version to `1.21`
=> Fix pointer for securityhub script

terraform/environments/digital-prison-reporting/iam.tf
Failed SCA run, removing ones which are currently ignored on the cicd member user.
=> SCA Fix Ignores

terraform/environments/bootstrap/member-bootstrap/iam.tf
We have multiple GitHub Workflows located [here](https://github.com/ministryofjustice/hmpps-delius-operational-automation) which utilise Ansible to perform certain operational automation tasks. Ansible accesses EC2 instances via SSH over SSM, currently the OIDC role does not permit establishing or managing SSM instance sessions. This PR adds the required permissions.
=> Ensure OIDC policy allows required SSM Session actions for Ansible automation

terraform/environments/digital-prison-reporting/versions.tf
Required Providers TLS Addition for SCA.
https://github.com/ministryofjustice/modernisation-platform/actions/runs/6781087098/job/18430785125
Required Providers TLS Addition for SCA.
https://github.com/ministryofjustice/modernisation-platform/actions/runs/6781087098/job/18430785125
It should remove the error message for SCA.
The plan and its changes will be the test.
Will this deployment impact the platform and / or services on it? 
No impact, only for DPR
- [- ] I have made corresponding changes to the documentation
- [- ] Plan and discussed how it should be deployed to PROD (If needed)
Hopefully this will fix the SCA error  https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.1/docs/rules …
=> Required Providers TLS Addition for SCA.

terraform/environments/bootstrap/member-bootstrap/iam.tf
A follow-up to the previous PR to add various permissions to allow SSH over SSM for our GitHub Workflows:
https://github.com/ministryofjustice/modernisation-platform/pull/5384
The session can be established, however it cannot close cleanly without the `ssm:TerminateSession` action permission. Adding it back in.
=> Add ssm:TerminateSession action to OIDC role policy

terraform/environments/bootstrap/delegate-access/iam.tf
Removed as part of migrating to OIDC, goodbye long lived creds.
Tested on sprinkler.
If any errors occur on the plan / apply it means that someone has re generated keys. I shall remove them and re run the terraform and it will pass.
Although its removing the user, a lot of code will be left for a week in case we need to revert. Changing as little as possible here seems sensible.
=> Removing cicd user from delegate access.

terraform/environments/core-shared-services/ecr_repos.tf
We are creating a lambda function to read logs and output an excel file from them. As a consequence, we will need an ECR repo to store the image for the lambda/requirements file.
This adds terraform to create the new repo.
It has not, but is patterned on existing code to do the same.
Will this deployment impact the platform and / or services on it? 
No
=> Adding a new ecr repo for future lambda image

terraform/environments/core-shared-services/ecr_repos.tf
Removing reference to the old user that no longer exists.
I think this might fix the apply issue we have in core-shared-services currently.
Plan looks good, applied it locally and it worked, unlike the apply on main right now.
Will this deployment impact the platform and / or services on it? 
I did it, which is jumping the gun, but main does not currently work.
=> Removed cicd refrences

terraform/pagerduty/aws.tf, terraform/pagerduty/member-services-integrations.tf
Adding pagerduty integration for PlanetFM instance alarms
Makes sns topic planetfm_alarms available for alarms to be sent to 
Reproduces what's already working for nomis etc.
No
Will implement the sns topic part for alarms for planetfm in the modernisation-platform-environments repo shortly
=> create planetfm alarms slack/pagerduty connection

terraform/environments/core-network-services/cidr-ranges.tf, terraform/environments/core-network-services/firewall-rules/preproduction_rules.json
CSR application needs to have external MoJo devices access it directly on the following ports - 80, 7770, 7771, 7780, 7781, 2109, 45054. 
**IMPORTANT** This has been implemented in the pre-prod environment only at the moment for testing MoJo connectivity and app performance wrt CSR. 
Initially attempted to lock this down so that 'incomiing' (sources) is restricted to the following: -
```
mojo-azure-landing-zone          = “10.192.0.0/16”
mojo-aws-globalprotect-vpc       = “10.184.0.0/16"
mojo-wifi                        = “10.154.0.0/15”
vodafone_wan_nicts_aggregate     = “10.80.0.0/12"
atos_arkc_ras                    = “10.175.0.0/16”
atos_arkf_ras                    = “10.176.0.0/16"
aks-studio-hosting-live-1-vnet   = “10.244.0.0/20”
```
But, neither `source_ip` or `destination_ip` …
=> mojo access to csr app in pre-prod

.github/workflows/terraform-member-environment.yml
Resolves https://github.com/ministryofjustice/modernisation-platform/issues/5432
It runs this job when merging to main similar to how we do in [data-platform](https://github.com/ministryofjustice/data-platform/blob/46f0868b8c77bffc0de91a0e6825928811c15bd7/.github/workflows/reusable-workflow-terraform.yml#L345)
Its the same logic as [data-platform](https://github.com/ministryofjustice/data-platform/blob/46f0868b8c77bffc0de91a0e6825928811c15bd7/.github/workflows/reusable-workflow-terraform.yml#L345)
No
We thought about using 
```yaml
if: github.event.pull_request.merged == true
```
but would need to add
```yaml
on:
pull_request:
types:
- closed
```
which might require removing
```yaml
on:
push:
branches:
- main
```
=> 🚑 Fix applying to production logic

terraform/pagerduty/aws.tf, terraform/pagerduty/member-services-integrations.tf
Integrating CloudWatch Alarms with PagerDuty and Slack
Adds it
It hasn't, doing it on dev to test it
No, dev only
=> NCAS: Add PagerDuty

terraform/environments/core-network-services/firewall-rules/preproduction_rules.json, terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf
The current way we schedule the lambda to run for instance scheduler is based on UTC time and does not take into account daylight savings time
This PR amends the cron job to account for the daylights savings
it will implement a temporary fix that will stop the instances from being shutdown to early
=> Change of the time for instance schedular

terraform/environments/core-network-services/firewall-rules/development_rules.json
This is for a some testing for connectivity between DOM1 devices connected to the ATOS VPNs to the MP development VPC where I have built a test loadbalancer/web server so w ecan test the connection.
Adds connectivity required for the testing.
No testing yet - we need the rule in place on the firewall so the network connectivity can be tested.
It will open up connectivity from DOM1 to the MP development VPC so will open up connectivity to other users of that VPC although I think we are happy with this.
=> added rules for DOM1 devices to access mp dev

terraform/pagerduty/aws.tf, terraform/pagerduty/member-services-integrations.tf
Integrating CloudWatch Alarms with PagerDuty and Slack
Adds it to ncas prod
No
=> NCAS Prod: Add PagerDuty

terraform/pagerduty/aws.tf, terraform/pagerduty/member-services-integrations.tf
Integrating CloudWatch Alarms with PagerDuty and Slack
Adds it to PRA, Tipstaff and DACP preprod and prod environments
No
=> add pager duty config for pra, tipstaff and dacp apps

terraform/environments/core-network-services/iam.tf
Going through the process of debugging network connectivity issue(s) from MoJo devices in to an app that's being moved from Azure/fixngo to AWS we can't see the whole story. Not just for this instance but generally DSO/users are going to want to check that inbound traffic is hitting the transit gateway as expected
Allows others to read the transit gateway logs
Added arn for tgw-* to resource allow list 
No
=> add ability to read transit-gateway flow logs

terraform/environments/bootstrap/delegate-access/policies.tf
"sqlworkbench:GetAutocompletionResource",
https://dsdmoj.atlassian.net/jira/software/c/projects/DPR2/boards/1282?selectedIssue=DPR2-182
Add sqlworkbench:GetAutocompletionMetadata to reporting_operations role  so that users can use the Redshift Query Editor without being interrupted by alerts.
Yes tested on Sandbox Environment 
=> SQLWorkbench Policy Updates

.github/workflows/opa-policies.yml, policies/.regal/config.yaml, policies/collaborators/collaborators.rego, policies/collaborators/utilities.rego, policies/environments/environment-definitions.rego, policies/environments/expected.rego, policies/environments/utilities.rego, policies/member/environment-definitions.rego, policies/member/utilities.rego, policies/networking/core-vpc.rego, policies/networking/expected.rego, policies/networking/utilities.rego
Hi there! 👋 This PR introduces [Regal](https://github.com/styrainc/regal) for linting the Rego in this project. A few of the linter violations reported have been fixed as part of the PR:
* [non-raw-regex-pattern](https://docs.styra.com/regal/rules/idiomatic/non-raw-regex-pattern)
* [use-assignment-operator](https://docs.styra.com/regal/rules/style/use-assignment-operator)
* [use-some-for-output-vars](https://docs.styra.com/regal/rules/idiomatic/use-some-for-output-vars)
Rules related mostly to style have been disabled in the configuration file also included here, and may be enabled later if desired.
The Conftest version used here was ancient (from 2020!), which prevented using some modern constructs like the `in` keyword. I've had that updated in the CI pipeline, but if there was any …
=> Add Regal for linting Rego

terraform/environments/core-network-services/firewall-rules/development_rules.json
Slack request here: https://mojdt.slack.com/archives/C01A7QK5VM1/p1699975122396359
This PR adds firewall rules from Data Platform Apps and Tools to DOM1 NAS filer for ports 445 & 389
All automated testes have completed successfully
No this PR only adds additional rules and will not impact any services. 
=> Add firewall rules for DPAT to DOM1 (development)

terraform/github/locals.tf
Remove Scott from the list of GitHub users
Currently failing due to `Inviter has insufficient permissions` https://github.com/ministryofjustice/modernisation-platform/actions/runs/6866176803/job/18675516426
N/A
No, only removing someone who has already left.
=> 😢 Remove Scott S from Github locals

terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf
Fixing issue raised here, last PR on this moved the hour the wrong way. https://moj.enterprise.slack.com/archives/C01A7QK5VM1/p1700212020612529
Issue mentioned here in slack (https://moj.enterprise.slack.com/archives/C01A7QK5VM1/p1700212020612529)
Corrects the time.
N/A
Will not impact live services.
=> Changing scheduled time power on / off

terraform/environments/core-network-services/cidr-ranges.tf, terraform/environments/core-network-services/firewall-rules/preproduction_rules.json, terraform/environments/core-network-services/firewall-rules/production_rules.json
SQL UDP connection required in from azure/fixngo jumpservers to PlanetFM sql db for testing
Opens UDP port 1434 in the AWS firewall
Will see the connection working once this port is open
No
Included in Prod as well
=> allow UDP 1434 in from noms_mgmt_live_vnet in azure

terraform/environments/bootstrap/member-bootstrap/iam.tf
Requested in slack: https://mojdt.slack.com/archives/C01A7QK5VM1/p1700474464062909
Allow for a CICD pipeline to create a state machine that can be used by AWS Step Function.
Automated checks to be passed.
This permission deployment will be applied in all member environments.
=> Adding permissions to CICD pipeline to allow state machine creation/listing

terraform/environments/bootstrap/delegate-access/policies.tf
Allow Create Step Functions for Sandbox Role
We are looking for permissions to add Step Functions though Sandbox/Dev Role 
Able to Add Step Functions
This will allow us to test the new step functions we are writing
No
=> Allow Create Step Functions for Sandbox Role

.github/workflows/terraform-github.yml
`/scripts/git-create-environments.sh` is running on the opening of a pull request and subsequently applying changes. (as described here: https://github.com/ministryofjustice/modernisation-platform/issues/5363).
This PR updates the workflow to only run the script when updates are made to the `main` branch. 
All test green. I won't be able to fully test until the change is merged into `main` and then a relevant change to trigger the script is submitted. 
Will this deployment impact the platform and/or services on it?
This change shouldn't impact the platform or any services, worse case would be that the scrip continues to run without the changes being merged into main. 
- [ X ] I have performed a self-review of my …
=> git-create-environments fix apply on open PR

terraform/environments/core-network-services/firewall-rules/production_rules.json
We need to give access to PPUD in production to a set of k8s pods in Cloud Platform to enable an automation service to run
This gives access to MP production from Cloud Platform 
Have just tested syntatical correctness of json
terraform?
It will enable traffic on port 443 from cloud platform through to the modernisation platform's production environment
Discussed with Ewa on slack https://mojdt.slack.com/archives/C01A7QK5VM1/p1700478069757819
=> Enables access to prod from cloud platform over port 443 (https)

terraform/environments/bootstrap/delegate-access/policies.tf
reference, https://aws.permissions.cloud/iam/states
We are unable to start, add tags, add actions and other activities with respect to step functions
This will give permissions for managing under sandbox Role
This permission will allow us to test this feature
No
[{Permission Reference Document}](https://aws.permissions.cloud/iam/states)
=> Add required permissions for managing Step Functions

terraform/environments/core-network-services/firewall-rules/development_rules.json
This is to allow us to test connectivity to private mp ranges from alpha protect vpn.
TF plan in checks
New firewall rule will be added.
=> Allow traffic from alpha vpn to platforms-dev

.github/workflows/terraform-github.yml, environments/sprinkler.json, scripts/git-create-environments.sh
As per ticket https://github.com/ministryofjustice/modernisation-platform/issues/5363 this PR updates the `terraform-github.yml` workflow to add a 'plan' to the `create-github-environments` job. This job passes through a `dry_run` flag which in turn omits the GitHub API submission 
This change will ensure that API submissions will only be applied when changes are merged into `main`
I have tested that changes are not submitted to the API when a pull request is raised. Once this PR is merged I will raise a small change to ensure changes are still being applied correctly on merge to `main`.
This PR should have no impact on the platform or services. 
- [ X ] All checks have …
=> GitHub member environments Plan feature

terraform/environments/data-platform-apps-and-tools/eks-cluster.tf, terraform/environments/data-platform-apps-and-tools/eks-iam-policies.tf, terraform/environments/data-platform-apps-and-tools/eks-iam-roles.tf
This PR allows us to create kubernetes resources from our `data-platform` repository.
This mirrors how we operate on Cloud Platform.
=> :wrench: Allow Helm releases from Data Platform to EKS

.github/workflows/terraform-member-environment.yml
Removed `workflow_dispatch` from `terraform-member-environment.yml` as it was only added to test the Slack failure notification changes by running the workflow manually.
https://github.com/ministryofjustice/modernisation-platform/issues/5000
=> removed workflow_dispatch as it was added only for testing the workflow

terraform/environments/core-network-services/cidr-ranges.tf, terraform/environments/core-network-services/firewall-rules/development_rules.json
Following a discussion with the MOJ Networks Team around Alpha VPN traffic traversing MOJ private networks, this PR removes any rules allowing traffic from devices using the GlobalProtect Alpha VPN to the Modernisation Platform.
=> Removed rule for alpha VPN traffic

terraform/environments/bootstrap/member-bootstrap/iam.tf
https://github.com/ministryofjustice/data-platform/issues/2454
We are building out another catalogue candidate meant to be deployed into EKS. To minimise the dependencies on MP team, we would like to build out as much infra in the MPE repository as possible. This is a request for read-level EKS permissions to allow lookups via datasources.
This gives the member infra role read-level permissions on the EKS cluster.
The local plan works because this permission is already available in the sandbox account but the deployment via GHA fails.
This should have no impact on PROD. This adds rather than removes or restricts permissions. 
- [?] I have made corresponding changes to the documentation
- [?] Plan and discussed how it should be deployed to PROD (If needed)
=> Adding permission to describe EKS cluster to member infra role

terraform/environments/bootstrap/delegate-access/policies.tf
The PR was raised based on the [ticket#2457](https://github.com/ministryofjustice/data-platform/issues/2457). The data engineers who work in the Analytical Platform use the “restricted-admin” role to run the Glue jobs. It looks like using “restricted-admin” to run Glue jobs will be difficult as something is retiring. For this reason, the ticket proposes to add the pre-existing "data-first-data-science" (which has sufficient permissions to run the Glue jobs) role to the SSO role so that the users can continue running their Glue jobs.
=> Added iam PassRole to Data engineering SSO

terraform/environments/bootstrap/member-bootstrap/iam.tf
https://github.com/ministryofjustice/data-platform/issues/2454
This allows OpenSearch to be deployed from Modernisation Platform Environments repository
Not feasible to test without permission being granted. This fixes an apply workflow which failed with lack of permission.
No. Permissions are additive.
=> Add OpenSearch permissions

terraform/environments/data-platform-apps-and-tools/eks-cluster.tf
https://github.com/ministryofjustice/data-platform/issues/2454
This adds the Member Infra role to the list of cluster masters for the apps and tools cluster, allowing helm and k8 deployments via Terraform from the MPE repo.
This requires deployment to test.
No
=> Enable Apps-Tools Helm Deployments from MPE Repo

terraform/modernisation-platform-account/dynamodb.tf
https://github.com/ministryofjustice/modernisation-platform/issues/5534
Added a new role - `modernisation-platform-member-state-access` - to allow Modernisation Platform Environments repository accounts to make use of a role in the Modernisation Platform account for state locking.
However, initial testing from `sprinkler` gave the following error:
```
api error AccessDeniedException: KMS key access denied
Unable to retrieve item from DynamoDB table "modernisation-platform-terraform-state-lock": operation error DynamoDB: GetItem
```
This PR grants the `modernisation-account-terraform-state-member-access` role access to the `dynamodb-state-lock` key, allowing Terraform to make use of the relevant table for state locking
Amended KMS policy manually to add role to permissions list.
Conducted …
=> 🔧 Add state access role to dynamodb encryption key

.github/workflows/email-requester-onboarding-close.yml
See [Automation to provide info for new onboarders#3451](https://github.com/ministryofjustice/modernisation-platform/issues/3451) got full details
Sends the email once the request is closed
Used act to test, initially, via "act -W 'email-requester-onboarding-close.yml'"
Initial errors corrected in updated version.
No impact to other services
This will be tested by creating a dummy onboarding release and seeing if it sends an email to the person listed as the owner (me). Should only take place on close
=> The email on close code for review

.github/workflows/secrets-rotation-reminder.yml
Unfortunately I had an issue with permissions on the secrets rotation reminder workflow - the only part I hadn't tested on my branch as I didn't want to spam our issues list with my testing but it has come back to bite!
I've also changed the schedule to 11:30 so hopefully I can watch it run in half an hour :)
=> fix permissions & change schedule to 11:30

.github/workflows/scheduled-baseline.yml
AWS SSO API limits were being hit, see here - https://github.com/ministryofjustice/modernisation-platform/actions/runs/7058404921/job/19217087981#step:7:120
Attempting to limit the number of calls to allow the workflow runs to succeed.
Not possible to test as needs a matrix to run.
Fix existing issue.
=> Set the max parallel jobs for single sign on

.github/workflows/email-requester-onboarding-close.yml, .github/workflows/notify-user-new-environment-created.yml
#3451 
Automatically generates the email on closing the onboarders release
Used act (act -W 'email-requester-onboarding-close.yml') to test and further tests require the release to be posted.
Does not impact any other services
It will be tested using a dummy onboarders call which will be closed to cause the yml to run
=> Removed the item that was causing an error on run.

terraform/environments/core-shared-services/iam.tf, terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf
This PR partially implements [the issue 2722](https://github.com/ministryofjustice/modernisation-platform/issues/2722).
This is to allow the instance scheduler lambda function to publish to SNS topics and to create topics that the lambda is going to use as the destination config. This is also integrating with an existing pagerduty service.
This is to enable alerts when the instance scheduler fails/succeeds.
Run the tf plan locally and it works as expected for the added functionality, but it fails for a transit gateway policy saying it needs an apply. Not end-to-end tested yet, as the lambda terraform module needs updating first.
The instance scheduler IAM policy may be impacted if configured incorrectly.
SNS topics and the …
=> Creating SNS topics and updating IAM policy for instance scheduler

environments/cdpt-ifs.json, policies/environments/expected.rego
Environment details
We require an environment that will allow us to host a C# application on .NET Framework 4.8 with SQL Server
Application Name
cdpt-ifs
Description of application
It is a business-critical function for managing fraud cases in different parts of the organisation.
Integrated Fraud System is a .NET Framework 4.8 application built using the MVC design pattern, using a SQL Server database.
This Pr is creating a new account as requested above
=> New environment for cdpt-ifs

environments-networks/hq-development.json, environments-networks/hq-preproduction.json, environments-networks/hq-production.json, policies/networking/expected.rego
Network Ram Share for  new cdpt-ifs environment
adds the account to the ram share
=> Networking for New cdpt-ifs

.github/labeler.yml, .github/workflows/labeler.yml
Removing '`ANY`' from config as not required, also fixing .github path in config as previous PR did not get labeled with `github-workflow` .
as per above
N/A
No
=> Remove Any from Labeler Config

terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf
Addressing SCA failures in https://github.com/ministryofjustice/modernisation-platform/actions/runs/7109130936
and adding the policy back to the instance scheduler role, which has been removed in the merge yesterday.
Adding hash for PD integration and suppressing SNS topic error, as encryption is not possible with PD integration.
Also, the lambda function has changed between the merge commit yesterday and the version that has been used in the past, the logic has changed and when using the module, it was missing on var that is used in the conditional that would either create that policy or not…so because it wasn’t meeting that conditional’s requirements, it would delete the policy from the role. This fix is to add the permissions back to the role.
Checks should pass now and it has been …
=> Addressing checkov failures

terraform/environments/bootstrap/delegate-access/policies.tf
https://github.com/ministryofjustice/modernisation-platform/issues/5534
In order for developers to run local terraform plans, they will need to be able to assume the `modernisation-account-terraform-state-member-access` role.
Once this PR is implemented, I will run a local terraform plan and apply from Example-development using a `-backend-config` input to assume the backend role
=> added backend role to trusted entities for developers

environments/cica-copilot.json
member-bootstrap job failed due to infrastructure-support tag is missing in cica-copilot.json
Added infrastructure-support tag in cica-copilot.json inorder to run the member-bootstrap job
=> Add infrastructure-support tag in cica-copilot.json

source/user-guide/running-terraform-plan-locally.html.md.erb, terraform/templates/modernisation-platform-environments/platform_backend.tf
https://github.com/ministryofjustice/modernisation-platform/issues/5534
Updates documentation for customers, and templates for new Modernisation Platform Environments customers.
Changes to `platform_backend.tf` are identical to those in my test PR and full PR in the Modernisation Platform Environments repository
No
Corresponds with https://github.com/ministryofjustice/modernisation-platform-environments/pull/4254
=> Update documentation and templates for state locking

terraform/environments/core-network-services/cidr-ranges.tf, terraform/environments/core-network-services/firewall-rules/development_rules.json, terraform/environments/core-network-services/firewall-rules/production_rules.json
See #5713 
Adds the firewalls for when the ports are opened
Not yet testable
=> New firewall rules to allow access  to Nomis

terraform/environments/bootstrap/delegate-access/policies.tf
This pull request adds S3 Storage Lens permissions to the developer policy
It's not a problem, but an additional set of features
It hasn't
It will extend the current developer policy
https://aws.amazon.com/s3/storage-lens/
https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage_lens_iam_permissions.html#storage_lens_iam_permissions_account
=> 🛂 Add S3 Storage Lens permissions

terraform/environments/bootstrap/delegate-access/policies.tf
Wrong permissions for deleting ECR images
This should be to allow users to delete images, rather than repositories.
TF Plan
No (unless people are manually deleting ECR repos which they shouldn't be)
=> Reduce ECR delete scope

terraform/environments/digital-prison-reporting/iam.tf
Additional CircleCI Role Permissions
Additional CircleCI Role Permissions
Additional CircleCI Role Permissions will allow DPR Specific Pipelines to manage the AWS resources, currently we are unable to manage the DMS/Glue and S3 resources as per our requirements
Tested on Sandbox Dev
N/A
=> Additional CircleCI Role Permissions

.github/workflows/publish-gh-pages.yml
Deploy GitHub Pages action is broken. We believe this is due to how the `upload-artifact/v4` action requires unique names.
Appends the `run_id` and `run_attempt` to the archive name
It will be tested when this workflow is created by using `workflow_dispatch`
=> Make name of artifact unique based on GitHub action run

terraform/environments/data-platform-apps-and-tools/kubernetes-namespaces.tf, terraform/environments/data-platform-apps-and-tools/src/helm/gatekeeper/values.yml.tftpl
Adds a Kubernetes namespace in DPAT EKS
It's not a problem
It hasn't
No, it's tenant code
=> 🏰 Add `actions-runners` namespace

.github/workflows/publish-gh-pages.yml
Fixed broken GH Pages deployment
Overrides the default artifact name that the action looks for
It will be tested in live.
No.
=> override default artifact name for pages deployment

.github/workflows/publish-gh-pages.yml
This is to Revert the change of upload-artifact back to V3 as currently V4 is not working correctly in our workflows
version change
=> Revert back to v3 of upload-artifact

terraform/environments/bootstrap/delegate-access/policies.tf
https://github.com/ministryofjustice/modernisation-platform/issues/5810
Creates a permission set that can be used by an SSO role focused on managed AD administration
N/A
This will be deployed through the `Terraform: Scheduled baseline` job
https://github.com/ministryofjustice/aws-root-account/pull/843
=> Create policy for Managed AD administrator

source/user-guide/running-terraform-plan-locally.html.md.erb
Apparently PyCharm displays markdown a bit differently to how it's interpreted when the user guide pages are created. This should fix a linting error in the page presentation.
=> Fix linting in page for running a local terraform plan

terraform/environments/bootstrap/single-sign-on/main.tf
https://github.com/ministryofjustice/modernisation-platform/issues/5810
This PR should allow us to assign an access level of `active-directory-management` through the `environments/$application.json` files
No
It shouldn't.
See these related PRs:
https://github.com/ministryofjustice/modernisation-platform/pull/5821
https://github.com/ministryofjustice/aws-root-account/pull/843
=> Add domain admin to sso

source/runbooks/rotating-secrets.html.md.erb
https://github.com/ministryofjustice/modernisation-platform/issues/5646
I've rotated the secret and have added some documentation on the process for it in case that would be of use in future. The GitHub Resources workflow step in particular was a part where I wasn't aware that needed to happen.
I have run the [GitHub resources](https://github.com/ministryofjustice/modernisation-platform/actions/runs/7250267742) job to import the new secrets from AWS Secrets Manager and subsequent workflows have successfully used the new secret. The status in Github shows that the new secret has been "Used within the last week".
Not if done correctly! 
As a side …
=> Docs/5646 rotate GitHub ci user pat

terraform/environments/bootstrap/member-bootstrap/iam.tf
Updates `MemberInfrastructureAccess` to have `eks:*`
It's not a problem
@ep-93 did it live
No, it's an enhancement
This pull request theoretically allows tenants to create EKS clusters, however that is gated somewhat by https://github.com/ministryofjustice/modernisation-platform-environments/blob/b3a1d61ee9a3045272719ab04c3c5c88d5245b67/scripts/terraform-plan-evaluator.sh#L7
=> 🛂 Update EKS permissions

terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf
This is to finish the https://github.com/ministryofjustice/modernisation-platform/issues/2722 issue implementation.
It aggregates lambda cloud watch alarms to narrow it down to the instance-scheduler lambda function only.
Tested manually in the console and local terraform plan. The checks should pass as well.
No impact on the platform/services.
=> Aggregating lambda cloudwatch alarms for instance-scheduler

environments/sprinkler.json, policies/environments/environment-definitions.rego, policies/environments/environment-definitions_test.rego
https://github.com/ministryofjustice/modernisation-platform/issues/5810
If we build an AWS Managed Microsoft Active Directory cluster in `sprinkler` for testing purposes, we need to also test the role to manage it.
Also I've alphabetised the list of roles checked in the OPA policy.
=> Add directory management for sprinkler

terraform/environments/environments.tf
If the secret is cleared for any reason this terraform won't run as it's needed currently to get the modernisation platform ou id.  By getting this from a data look up it means that we are not dependant on the secret.
=> Switch local to data rather than secret

terraform/modernisation-platform-account/iam.tf
Updates the ref to the superadmins module to references v2.0.2
As per issue 5830.
Tests undertaken as per doc - https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/adding-a-new-team-member.html#adding-them-as-a-superadmin-in-our-aws-landing-zone
Not according to the documentation.
=> Updates ref of the superadmins module to use v2.0.2 of the module.

.github/workflows/terraform-static-analysis.yml
This PR is to fix [this issues](https://github.com/ministryofjustice/modernisation-platform/issues/5890) and to test [this change](https://github.com/ministryofjustice/github-actions/pull/226/).
By setting tflint_call_module_type to none to skip tf module scanning with tflint.
Locally in a dockerfile, but not in action yet.
No
=> Setting tflint_call_module_type to none

.github/workflows/terraform-static-analysis.yml, terraform/environments/bootstrap/member-bootstrap/iam.tf
Currently the TSA (Terraform Static Code Analysis) workflow is failing due to an incorrect commit hash, this PR updates the commit hash to the correct value. 
failing workflow: https://github.com/ministryofjustice/modernisation-platform/actions/runs/7383085655
error: `Unable to resolve action ministryofjustice/github-actions@7433c75e44be4eabb0a6ca573951090b9da4901cf, unable to find version 7433c75e44be4eabb0a6ca573951090b9da4901cf`
=> Terraform Static Code Analysis - fix commit hash

terraform/environments/core-network-services/firewall-rules/preproduction_rules.json
Cloud platform unable to connect to preprod nomis DB in hmpps-preproduction. This is to facilitate migration of container app from Azure to Cloud Platform.
Adds required firewall rule
N/A
No
=> Firewall rule: allow cloud platform to hmpps-preprod for Oracle DB port

terraform/environments/core-network-services/cidr-ranges.tf, terraform/environments/core-network-services/firewall-rules/preproduction_rules.json, terraform/environments/core-network-services/firewall-rules/production_rules.json
PlanetFM enduser client access is currently blocked by these FW rules
Adds access to private subnets for PlanetFM end users
We can see traffic being blocked and the underlying SG's are correct
Will allow currently ongoing connectivity testing to proceed. 
Delays in local testing will impact UAT test schedule (which we really don't want)
Similar exercise already been carried out for CSR
=> add fw rules for planetfm endusers access

terraform/environments/core-network-services/route53.tf
We’re contacting you from the [Domain Management team](https://www.gov.uk/government/groups/domain-management-team) at the Central Digital & Data Office (CDDO). We help to secure public sector domains.
We've noticed some inconsistencies with subdomains under [modernisation-platform.service.justice.gov.uk](http://modernisation-platform.service.justice.gov.uk/)
These are the subdomains that we have identified:
[rs-non-production.modernisation-platform.service.justice.gov.uk](http://rs-non-production.modernisation-platform.service.justice.gov.uk/)
[rs-production.modernisation-platform.service.justice.gov.uk](http://rs-production.modernisation-platform.service.justice.gov.uk/)
[video.rs-production.modernisation-platform.service.justice.gov.uk](http://video.rs-production.modernisation-platform. …
=> removing dns records that are no longer required

terraform/environments/core-network-services/cidr-ranges.tf, terraform/environments/core-network-services/firewall-rules/inline_rules.json, terraform/modules/vpc-inspection/main.tf
Traffic from Sandbox VPCs to the internet does not return to the source host
This PR adds routes back to the TGW for traffic from Sandbox VPCs
Observed traffic reaching inline NWFW endpoints in egress VPCs, but no return traffic seen on source host.
No
Routes should be added by GitHub action
=> Route traffic for sandbox VPCs back to TGW

terraform/environments/bootstrap/member-bootstrap/iam.tf
https://github.com/ministryofjustice/modernisation-platform/issues/5924
This should allow member accounts to build CUR definitions (Cost & Usage Reports) via terraform to a specified s3 bucket.
I'm running TF locally to test in example-development but get the following error when I try to build the CUR definition with the us-east-1 provider...
`User: arn:aws:sts::083957762049:assumed-role/MemberInfrastructureAccessUSEast/aws-go-sdk-1704803134428561000 is not authorized to perform: cur:PutReportDefinition on resource: arn:aws:cur:us-east-1:083957762049:definition/example-cur-report-definition because no identity-based policy allows the cur:PutReportDefinition action`
Once this is merged I will test fully and then look at doing it through the pipeline.
Will this deployment impact the …
=> add cur permissions to member-access-us-east

terraform/environments/bootstrap/member-bootstrap/locals.tf
Allows the oasys accounts to be picked up on Oracle licensing reports.
=> Add Oasys to Oracle license reporting

terraform/environments/bootstrap/delegate-access/policies.tf
Users who make use of the directory management role need SSM permissions to connect to a directory service management instance.
Adds `ssm:*` to permissions for role policy.
Observed failure when attempting to connect to management instance:
```
An error occurred while calling the StartConnection API operation. AccessDeniedException: An error occurred (AccessDeniedException) when calling the StartSession operation: User: arn:aws:sts::000000000000:assumed-role/AWSReservedSSO_mp-active-directory-management_93c9c1890364ab9b/user@digital.justice.gov.uk is not authorized to perform: ssm:StartSession on resource: arn:aws:ec2:eu-west-2:000000000000:instance/i-028fd3a3be2530136 because no identity-based policy allows the ssm:StartSession action
``` …
=> allow directory management permission set to start SSM connections

scripts/provision-member-directories.sh
See #5908 
Allows specifying a top level array containing github_slugs to be considered as `codeowners`. If you have not provided a `codeowners` key, then the existing method of considering all `github_slugs` with member access as codeowners is still used.
I have tested the bash locally using an example `${environment_json_dir}/${application_name}.json` file. 
=> Separating GitHub codeowners and aws access #5908

environments/delius-core.json
As per the request info on #5908 
Additionally another change has been made to the provision-members-directories.sh file too
Should prevent those with codeowners:false from approving PRs
Difficult to test so will be done by approving this and hoping it runs the above sh
=> Amended the delius-code json to add codeowner false to the dba group

.github/workflows/notify-user-new-environment-created.yml
[Pinned-Dependency](https://github.com/ministryofjustice/modernisation-platform/security/code-scanning/1053)
#4998 
Pins each Action to an immutable checksum as recommended by GitHub's Security Hardening guide.
=> Code Scanning Alert- pin dependency by hash

environments-networks/hmpps-development.json, environments-networks/hmpps-preproduction.json, environments-networks/hmpps-production.json
https://github.com/ministryofjustice/modernisation-platform-environments/pull/4503 is building an SFTP server for external access but requires additional permissions so that a transfer server can be created.
See [here](https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/334) for difference between `transfer` and `transfer.server`
Adds `transfer.server` endpoint for HMPPS domain
n/a
Required to be able to deploy the sftp server.
=> Add transfer.server endpoint  to hmpps

terraform/environments/bootstrap/member-bootstrap/iam.tf
As per this [Slack request](https://mojdt.slack.com/archives/C01A7QK5VM1/p1705313573903589) I've added `cognito:*` to the MemberInfrastructureAccess permissions
Allows GitHub automation to create and delete `cognito` resources
Yes, we've done this for many other permissions
No
=> Add Cognito to allow MemberInfrastructureAccess permissions

source/runbooks/creating-accounts-for-end-users.html.md.erb
Information about the change to allow limitation of approvals to account PRs
Stops other teams/members from approving PRs. It must be done by the owner.
Code was used to make sure only one account can approve PRs
Just a change to the documentation to reflect new approach.
- [ x] I have made corresponding changes to the documentation
- [ x] Plan and discussed how it should be deployed to PROD (If needed)
I expect some comments on the quality of the language in the code.
=> Amended code to include limiting change approvals

environments/hmpps-domain-services.json
Update account settings to hmpps-domain-services in prep for some shared remote desktop resources.
Give CSR app support team access to the account - so they can logon to the servers using FleetManager if needed.
Remove nuke to ensure some core resources don't get deleted at the weekend (e.g. aws_autoscaling_group and aws_launch_template)
Updates json file accordingly
Mod platform pipelines
No
=> DSOS-2537: give csr app support team access to hmpps domain services

source/runbooks/creating-accounts-for-end-users.html.md.erb
Fixed an issue with <owner-name" showing as a blank in the documentation.
=> replacecd <owner-name> with \<owner-name\> to prevent missing item in documentation

terraform/environments/bootstrap/delegate-access/policies.tf
run plans, apply CUR reports as a module in modernisation-platform-environments/baseline
permission needed to deploy
error describes 
```
│ Error: reading Cost And Usage Report Definition (planetfm-development-cost-usage-report): AccessDeniedException: User: arn:aws:sts::326533041175:assumed-role/AWSReservedSSO_modernisation-platform-sandbox_82845f23a0bbb190/robertsweetman@digital.justice.gov.uk is not authorized to perform: cur:DescribeReportDefinitions on resource: arn:aws:cur:us-east-1:326533041175:definition/ because no identity-based policy allows the cur:DescribeReportDefinitions action
```
nope
=> additional permissions to run cur reports

terraform/environments/bootstrap/member-bootstrap/iam.tf
Adds requested cognito-idp permissions for Modernisation Platform customer
Allows MemberInfrastructureAccess role to use `cognito-idp:*` actions
Deployed through GitHub Actions
=> Add cognito-idp permissions

terraform/environments/bootstrap/member-bootstrap/iam.tf
Relates to [this query](https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/7501579296/job/20422527745?pr=4503 ) from Electronic Monitoring Data team regarding the lack of permissions for creation of an aws transfer server 
This gives the `member-access` role the ability to **create** and **delete** ec2 vpc endpoints as listed as min pre reqs in creation of aws transfer servers [here](https://docs.aws.amazon.com/transfer/latest/userguide/getting-started.html)
This will be tested by EMD team when permissions are added by re-running their workflow.
As this will allow members to create/destroy vpc endpoints (something we don't usually want them to do) there is a corresponding PR …
=> add vpc endpoint create/delete permissions

terraform/environments/bootstrap/delegate-access/policies.tf
Enable DPR Devs to Start Stop State Step Functions and Glue Jobs
Enable DPR Devs to Start Stop State Step Functions and Glue Jobs
Enable DPR Devs to Start Stop State Step Functions and Glue Jobs
Yes Tested on Dev/Sandbox
N/A
=> Update policies.tf for DPR Reporting Role

terraform/environments/bootstrap/member-bootstrap/iam.tf
https://github.com/ministryofjustice/modernisation-platform/issues/5286
We want to move bespoke creation of resources from the `modernisation-platform` repository to the `modernisation-platform-environments` repository where we will exercise control over pull requests that deploy certain resources such as VPCs, subnets, endpoints, and IAM configuration.
This will execute the scheduled baselines job
No
=> Broaden permissions for `member-access` policy

source/runbooks/rotating-secrets.html.md.erb
While working on https://github.com/ministryofjustice/modernisation-platform/issues/5648, I noticed there was no guidance on how to rotate a fine-grained personal access token.
Adds a runbook.
I documented the steps I followed to rotate the credential.
N/A
=> Add runbook of how to rotate MP CI User Environments Repo PAT

.github/workflows/publish-gh-pages.yml
As per the vulnerability identified in [CVE-2024-22048](https://github.com/advisories/GHSA-x2xw-hw8g-6773)
This PR updates to the latest version as recommended.
(https://mojdt.slack.com/archives/C02D2NEF9CJ/p1706096643823459)
=> Vulnerability patch for CVE-2024-22048

terraform/environments/core-shared-services/iam.tf
Resolved `invalid principal in policy` error by updating the principal ARN in Terraform configuration #5449 
This PR addresses the issue by correcting the principal ARN, ensuring the Terraform apply process now functions without `invalid principal in policy` error
=> Updated role and policy resource arn

terraform/environments/core-shared-services/iam.tf
Modified trust relationship in IAM role to enable EventBridge scheduler to assume the role #5449 
This PR addresses the issue by updating the trust relationship, facilitating successful assumption of the role by the EventBridge Scheduler
=> Modified trust relationship in IAM role

.github/workflows/publish-gh-pages.yml
following the version upgrade from v2 > v3 this PR uses the new 'deploy' script rather than the 'compile-and-create-artifact.sh' script.
=> Fix breaking changes in tech-docs-github-pages-publisher v3

terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf
Moving Instance scheduler to event bridge scheduling #5449
Replaces Cloudwatch Events with EventBridge Scheduling, providing enhanced scheduling capabilities for InstanceScheduler lambda function.
=> Moving Instance scheduler to event bridge scheduling

.github/ISSUE_TEMPLATE/new-environment.yml, source/user-guide/creating-environments.html.md.erb
This recent feature https://github.com/ministryofjustice/modernisation-platform/pull/5951 enabled members to separate the link between access to environments and who can approve PRs.  
This PR extends the new environment issue template to add a new field for `Github codeowner team slug` and provides a description of the option.
Please feel free to suggest changes to the description to make it more understandable! I think what I've said is correct.
=> add git codeowner option to new env issue template

terraform/environments/core-network-services/cidr-ranges.tf, terraform/environments/core-network-services/firewall-rules/preproduction_rules.json, terraform/environments/core-network-services/firewall-rules/production_rules.json
Including a FW rule that allows traffic from DOM1 domain controllers (10.172.68.146/29) on port 9389 to private subnets, specifically for Planet FM preprod and prod. 
New Preprod and Prod firewall rule, with domain-controller cidr range
Firewall logs indicate that this traffic is currently blocked, will re-test by running connection tests from prod / preprod planet servers.
It will add an additional allow rule to the MP firewall
=> adding in preprod and prod rules from planet FM

terraform/environments/bootstrap/secure-baselines/main.tf, terraform/modernisation-platform-account/baselines.tf
Updates references for module "modernisation-platform-terraform-baselines" to 6.2.2 (8011886209e43f22489429e3573aa14a5cc4a359) as per issue #5012
Issue Ref #5012. Updates the references to module "modernisation-platform-terraform-baselines" which includes a resource that blocks public access to AMIs if that account already has publicly-shared AMIs. 
By default, public sharing of AMIs is blocked. However for accounts that already have shared AMIs this way, this resource needs to be applied to enable it. 
Changes to sprinkler have applied without error.
Also note the outcome of action - …
=> Issue #5012

terraform/environments/core-shared-services/data.tf, terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf
Adds KMS encryption to address a secure code analysis failure [here](https://github.com/ministryofjustice/modernisation-platform/actions/runs/7705153518/job/20998642358).
Creates a data call, then uses the content of that data call to supply a KMS ARN used to encrypt the resource.
Ran `checkov` locally to confirm the issue had been addressed
No
I couldn't seem to get Terraform to correctly reference the content of the module directly, so I created a data call.
I could see that `terraform state show show module.kms["platforms"].aws_kms_alias.general` returned information in the statefile about the resource, but trying to directly retrieve it through the console for confirmation was unsuccessful like so: 
```
module.kms
{} …
```
=> added KMS encryption to eventbridge schedule

terraform/environments/bootstrap/delegate-access/policies.tf
Currently unable to manage AWS Backups in a sandbox account
We manage custom backup plans for certain resources and in the sandbox account where we have been testing the creation of backup vaults we are unable to remove them with terraform because the vaults are not empty. We are also unable to remove the recovery points in the console or via the cli because the current IAM policy doesn't allow any actions other than starting a restore job. In other environment types, we'd be happy to raise an ask request, but in sandbox it feels appropriate that we could do this ourselves.
Adds wildcard iam perms to allow all actions
{Please …
=> Allow all AWS Backup actions whilst assuming the sandbox role

terraform/environments/secrets.tf, terraform/modernisation-platform-account/dynamodb.tf, terraform/modernisation-platform-account/s3.tf, terraform/pagerduty/kms.tf
https://github.com/ministryofjustice/modernisation-platform/issues/5635
Added multi-Region KMS keys for DR replication because existing KMS keys are all single-Region and cannot be converted to multi-Region
Created and tested primary multi_region KMS key and it's replica in eu-west-1 in sprinkler account
=> added pagerduty kms multi-region

.github/workflows/scheduled-baseline.yml, terraform/environments/bootstrap/single-sign-on/main.tf
https://github.com/ministryofjustice/modernisation-platform/issues/5659 Move SSO Permission sets to MP from Root
Now that https://github.com/ministryofjustice/modernisation-platform/pull/6047 has been merged and the sso permission set resources have been migrated from Root to the Mod Platform state this PR makes a change to the bootstrap SSO code so that it references the remote state rather than an data call to the SSO api.
Plan on sprinkler has managed to read the terraform remote state ... https://github.com/ministryofjustice/modernisation-platform/actions/runs/7711719472/job/21017635917#step:7:20
See also the related PR …
=> Reference mp state for sso perm set

terraform/environments/bootstrap/single-sign-on/main.tf, terraform/single-sign-on/data.tf, terraform/single-sign-on/outputs.tf
We are still hitting API limits with the number of data calls we are making. 
Moving the maximum amount of data calls we can realistically move out and storing them in tf state for the platform wide single-sign-on terraform to be queried from here as an output.
Tested locally on a member account, no changes.
No changes operation, no impact.
=> Removing more data calls from SSO

terraform/pagerduty/aws.tf
https://github.com/ministryofjustice/modernisation-platform/issues/4999
Addresses the encryption of PagerDuty secrets
No
No
=> encrypt pagerduty secrets with pagerduty kms key

terraform/environments/bootstrap/single-sign-on/main.tf
Reference to "reporting operations" output has a typo
https://github.com/ministryofjustice/modernisation-platform/actions/runs/7723959610/job/21055604357#step:7:42
Changed typo in output reference for the "reporting operations" permission set (underscore instead of hyphen)
=> fix output reference

terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf
KMS keys cause scheduled jobs not to run. While it may be desirable to encrypt these in future, we'd need to spend time properly investigating the required KMS policy and in the interim there's no need to do so.
=> removed KMS key references

terraform/environments/core-shared-services/iam.tf, terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf
This PR addresses an issue where the EventBridge scheduler was unable to trigger the lambda function due to missing permissions for the KMS key used for encryption
This PR updates the EventBridge scheduler role policy to explicitly grant the permission. This allow the scheduler to decrypt encrypted events and invoke the Lambda function as intended 
Tested this on sprinkler
=> Fix EventBridge Scheduler issue with customer-managed KMS key

source/user-guide/accessing-ec2s.html.md.erb
Hit a strange edge case tonight where after manually editing the ASG for the linux_bastion to bring an instance back online after 9pm, even though the old instance was instance state Terminated, the aws cli was still returning it (and it was visible in the console). 
The current proxy command grabs the first instance only
Adding a second filter to find instances with status code 16 means only "running" instances will be returned
Tested the output of the command manually and have updated my bastion configuration already.
=> Update accessing-ec2s.html.md.erb: filter to running instances

environments/sprinkler.json, policies/environments/environment-definitions.rego, policies/environments/environment-definitions_test.rego, terraform/environments/bootstrap/delegate-access/policies.tf, terraform/environments/bootstrap/single-sign-on/main.tf, terraform/single-sign-on/outputs.tf, terraform/single-sign-on/sso-permission-sets.tf
The purpose of this PR is to create an SSO permission set for use in a specific tactical business case - we are aware of the limitations here and this will not scale / is not expected to become an AP offering.
This is in reference to https://github.com/ministryofjustice/data-platform/issues/2451 specifically.
The user modernisation-platform-powerbi-user shall be assumed by three analytical platform users to configure a data source made up of data being held in analytical platform, in order to make it available in the PowerBI service. This permission set is only to be used in the analytical-platform-data-production account.
This PR adds:
* Definition of the powebi prmission set, reference to the customer-managed policy and the permission set state output
* Amends rego policies to add the …
=> Adding PowerBI User permission set and policy

environments/cdpt-ifs.json
No value for  "github-oidc-team-repositories"
Adds a value for  "github-oidc-team-repositories"
-
=> github-oidc-team-repo

terraform/github/locals.tf, terraform/modernisation-platform-account/iam.tf
JM is no longer a member of the organisation and as such needs to be removed.
JM's name remaining causes conflict with Github as he has been removed from the ministryofjustice group.
=> Changes required to remove Jake Mulley from SuperAdmins & Maintainers list.

terraform/modernisation-platform-account/secrets.tf
https://github.com/ministryofjustice/modernisation-platform/issues/5635
Added multi-Region KMS keys for DR replication because existing KMS keys are all single-Region and cannot be converted to multi-Region
Created and tested primary multi_region KMS key and it's replica in eu-west-1 in sprinkler account
=> Added kms secrets_key_multi_region

terraform/environments/core-network-services/firewall-rules/development_rules.json
We need to allow more bi-directional traffic between hmpps networks/environments and their legacy delius counterparts.
This PR will allow traffic to flow through the central firewall.
No testing performed yet. This PR is a prerequisite to further work.
No negative impact expected
Not aware of any MP docs that need updating due to this change. Is anybody able to point me to relevant pages so I can update?
=> NIT-1038 allow traffic between MP hmpps and legacy delius networks

environments/cortex-xsiam.json, policies/environments/expected.rego
https://github.com/ministryofjustice/modernisation-platform/issues/6112
Adds content required to create new `cortex-xsiam` account
Followed steps in [team runbook](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/creating-accounts-for-end-users.html#new-environment-files).
=> Create `cortex-xsiam` accounts

terraform/environments/bootstrap/single-sign-on/main.tf
See slack thread here: https://mojdt.slack.com/archives/C013RM6MFFW/p1707225725037789
The returned output is already an arn, this PR is to correct the path to it.
This has been run locally for sprinkler.
This will be deployed to all environments.
=> Fixing a bug in the powerbi sso assignment

terraform/environments/bootstrap/delegate-access/iam.tf, terraform/environments/bootstrap/member-bootstrap/iam.tf
#3053 
This PR moves SSM parameters from delegate to member bootstrap access by deleting the SSM parameters from delegate access and recreating them in the member bootstrap access. 
deployed to the sprinkler
=> Move SSM parameters from delegate to member bootstrap access

terraform/environments/bootstrap/member-bootstrap/iam.tf
This PR addresses the issue where two SSM parameters were moved from delegate access to member bootstrap, resulting in deployment solely in member accounts rather than across all accounts. These parameters are crucial for system functionality and need to be deployed universally across all accounts
This PR removes the count variable responsible for limiting the deployment of SSM parameters to member accounts only. By eliminating this constraint, the parameters will now be deployed in all remaining accounts as intended.
=> Removed count variable in ssm resources

scripts/member-account-ram-association.sh
https://github.com/ministryofjustice/modernisation-platform/issues/6048
When we run the `./member-account-ram-association.sh` script, we encounter a problem where we want to apply tags to the RAM shared objects corresponding to VPC subnets.
To add the tags we need a full list of subnet IDs, but this isn't available when we run a Terraform plan. To get this list of subnet IDs we either need to use a statically defined map, or we need to run Terraform in a targeted fashion to get those subnet IDs.
This PR amends the `./member-account-ram-association.sh` script so that it first runs a targeted apply, then a full apply.
Tested locally
No, but there could be unexpected behaviour in a situation where `networking.auto.tfvars` is …
=> Resolve failure to retag RAM shared subnets

source/runbooks/removing-a-team-member.html.md.erb, source/team/team.html.md.erb, terraform/pagerduty/locals.tf
Removing Jake as pagerduty terraform was failing (and he has now left): https://github.com/ministryofjustice/modernisation-platform/actions/runs/7826944229/job/21353765269#step:7:173
=> Removing Jake from pagerduty and team page

environments/analytical-platform.json
https://github.com/ministryofjustice/data-platform/issues/2452
We need to add this level of access to perform end to end testing with data engineers.
Provides the needed access
Code review only.
This is a pre-existing unconstrained access level that is already active in other AP accounts so should not cause any additional issues.
=> Adding data engineering access level to AP-DEV account.

.trivyignore.yaml
See #6158 . Trivy reporting errors that github is not private. All of our are public so it should be ignored.
Added the error to .trivyignore.yaml which should ensure it is no longer considered.
Impossible to test with a plan due to a different error that pops up.
Approve the import and apply the change.
=> Added the error (AVD-GIT-0001) to the .trivyignore.yaml file.

environments/sprinkler.json, policies/environments/environment-definitions.rego
This PR aims to facilitate testing of the fleet-manager role deployed to the Sprinkler environment. Currently, there's a need to verify the functionality and permissions associated with this role.
This PR addresses the problem by providing the necessary access and permissions to test the fleet-manager role deployed on the Sprinkler environment. By doing so, it allows for thorough testing and validation of the role's functionality
=> Added fleet-manager role to sprinkler

terraform/single-sign-on/outputs.tf, terraform/single-sign-on/sso-permission-sets.tf
This PR addresses the need to provide SSO permission sets for the fleet manager role. Previously, fleet managers lacked the necessary permissions to access certain environments. By adding SSO permission sets, we aim to grant them appropriate access
This PR resolves the issue by adding SSO permission sets specifically tailored for the fleet manager role. With these permissions in place, fleet managers can now access the required environments without encountering access restrictions.
=> Added SSO permission sets for fleet-manager role

terraform/environments/bootstrap/single-sign-on/main.tf
This PR addresses the need to provide SSO permission sets for the fleet manager role. Previously, fleet managers lacked the necessary permissions to access certain environments. By adding SSO permission sets, we aim to grant them appropriate access
This PR resolves the issue by adding SSO permission sets specifically tailored for the fleet manager role. With these permissions in place, fleet managers can now access the required environments without encountering access restrictions.
=> Added fleet-manager permission set

terraform/environments/core-network-services/cidr-ranges.tf, terraform/environments/core-network-services/firewall-rules/preproduction_rules.json, terraform/environments/core-network-services/firewall-rules/production_rules.json
Opening AD ports to dom 1 domain cotrollers
Currently blocked traffic to DOM 1 domain controllers preventing fully functioning Planet FM servers
Firewall logs and comparison with Azure networking
Will allow traffic from Active Directory ports - should not impact any running services
=> dom 1 domain controller FW rules

.trivyignore.yaml
Fixes https://github.com/ministryofjustice/modernisation-platform/actions/runs/7882878946
Paths are supported in trivyignore, but are done per vulnerability at present.
=> removed invalid `path` declaration

scripts/provision-member-directories.sh
This pull request is part of https://github.com/ministryofjustice/modernisation-platform-environments/pull/4937
It adds @ministryofjustice/devcontainer-community as a code owner for `.devcontainer`
N/A
It hasn't
It shouldn't impact tenants
=> 🛂 Update CODEOWNERS template

terraform/environments/bootstrap/delegate-access/policies.tf
https://github.com/ministryofjustice/data-platform/issues/1916 in Analytical Platform backlog
PowerBI user needs athena and glue access so amending the policy to include them without resorting to  blanket permissions
We will be testing this out with users. Aside from that, a self-review
Should not do. This is a standalone policy only applicable to AP accounts
=> Rewriting powrbi policy to narrow it down to specific permissions.

terraform/environments/core-network-services/firewall-rules/preproduction_rules.json, terraform/environments/core-network-services/firewall-rules/production_rules.json
Adjust the firewall rules to allow RPC connections to Dom1 domain controller - required for the PlanetFM application and Dom1 device connectivity
Allows outbound traffic in port range 49152:65535
Running Test-NetConnection from the (windows) source to the target works with other opened firewall rules ports. Trying anything in this range fails.  
Nope, other than allowing them to work
=> add firewall rule for RPC to dom1 domain controllers

terraform/environments/bootstrap/single-sign-on/main.tf
This PR addresses the need to disassociate accounts and roles from SSO permission sets. This is necessary because certain policies have entities that cannot be deleted unless they are disassociated from these accounts and roles.
This PR resolves the issue by removing the association between accounts/roles and SSO permission sets. By doing so, it allows for the deletion of entities associated with certain policies, thus resolving the underlying problem.
=> Remove SSO account assignment

terraform/environments/core-network-services/firewall-rules/test_rules.json
Allow traffic to/from delius-test and hmpps-test vpc
=> Update test_rules.json for delius test ldap traffic

terraform/environments/bootstrap/delegate-access/policies.tf
https://github.com/ministryofjustice/data-platform/issues/1916 in Analytical Platform backlog
PowerBI user needs athena and glue access so amending the policy to include them without resorting to blanket permissions
We will be testing this out with users. Aside from that, a self-review
Should not do. This is a standalone policy only applicable to AP accounts
=> Updated powerbi_user_additional policy

terraform/environments/core-shared-services/ad-fixngo.tf, terraform/environments/core-shared-services/files/ad-fixngo-ec2-user-data.yaml, terraform/modules/kms/outputs.tf
In summary, tactical solution for migrating Domain Controllers from Azure FixNGo estate.
Initial commit will standup roles and security group. EC2s will be commented in later
Skeleton terraform to allow creation of EC2s in live and non-live data as per agreed tactical solution.
Tested as far as possible in environments repo in a member account
No
Mod Platform engineers aware of solution: David Sibley + Dave Elliot
=> DSOS-2615: initial terraform for fixngo domain controllers

.github/workflows/terraform-static-analysis.yml
terraform static code workflow is currently failing this is possibly due to the new skip dir functionality that we recently added
after a lot of testing we have reverted the change on the github action repo this change now updates the has to the latest release
=> fix to terraform static code analyst

terraform/environments/core-shared-services/ad-fixngo.tf
Adds skill commit hash error check as the module it is referencing is one of those owned by Modernisation Platform.
Fixes failed run - https://github.com/ministryofjustice/modernisation-platform/actions/runs/7927178027/job/21643126838
See above
See above
=> Fix for Terraform Static Code Analysis Error. 

terraform/environments/core-network-services/firewall-rules/fqdn_rules.json
As part of the current Equip upgrade work including a new power bi server, this PR adds a fqdn firewall rule for `.servicebus.windows.net` as per requirements detailed here https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-communication#ports
I have also sorted the list alphabetically 
TLDR: add servicebus.windows.net to fqdn rules and sort alphabetically.
=> Equip PowerBi Firewall FQDN Rule

environments/cdpt-chaps.json
No go-live date 
Add golive date
- [ x] Plan and discussed how it should be deployed to PROD (If needed)
=> update golive date

environments/laa-oem.json
As per slack request in the ask channel [here](https://mojdt.slack.com/archives/C01A7QK5VM1/p1708099283581729) this PR updates the LAA OEM development environment with sandbox permissions.
=> Add sandbox permissions to LAA OEM development environment

terraform/environments/core-network-services/cidr-ranges.tf, terraform/environments/core-network-services/firewall-rules/development_rules.json, terraform/environments/core-network-services/firewall-rules/production_rules.json
#6157 relies on further network ranges to send syslogs into MP
Adds firewall rules
Tested with a local Terraform plan
=> Add details for further syslog senders

terraform/environments/bootstrap/single-sign-on/policies.tf
Following on from the permission issue raised in ask channel (https://mojdt.slack.com/archives/C01A7QK5VM1/p1708342824264679) 
This PR removes the condition statement and adds the `ec2:ModifyInstanceAttribute` permission to the `instance-management-document`
=> ec2:ModifyInstanceAttribute Permission for Instance-Management

.github/workflows/bootstrap-sprinkler.yml
There was an issue identified in the bootstrap-sprinkler workflow where all the jobs were running in parallel, causing potential conflicts and inefficiencies. This issue was impacting the reliability and performance of our workflow execution.
this PR modifies the workflow to incorporate dependencies between jobs. By adding dependencies, we ensure that certain jobs wait for others to complete before starting, thus preventing parallel execution where it's not desired. This ensures that the workflow runs smoothly and consistently, resolving the problem of parallel execution and improving overall efficiency.
=> Add Dependency Between Jobs in Bootstrap-Sprinkler Workflow

terraform/github/versions.tf
GitHub actions terraform runs have been failing due to a mismatch in allowed provider versions
Sets a consistent floor for the GitHub provider
Test locally
CI run will use new version successfully.
=> Bump provider version

terraform/environments/bootstrap/single-sign-on/policies.tf
Without this, terraform local plans will fail as a preconfigured terraform provider cannot assume the `ModernisationPlatformSSOReadOnly` role.
Adds an IAM resource
Tested manually, and with a local apply to `sprinkler-development`
Thanks @mikereiddigital for spotting my oversight!
=> Allow developers to assume `ModernisationPlatformSSOReadOnly` role

terraform/environments/bootstrap/member-bootstrap/iam.tf
CI user is not able to assume SSO read only role
Adds resource to IAM policy for `sts:assumerole`
Applied locally to `example-development` and tested [here](https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/8003227683)
No
=> Allow GitHub OIDC to assume ssoreadonly role

terraform/environments/core-network-services/cidr-ranges.tf, terraform/environments/core-network-services/firewall-rules/development_rules.json, terraform/environments/core-network-services/firewall-rules/production_rules.json
Cortex-SIAM application is being hosted elsewhere, so these rules are not needed
Removes firewall rules
Discussed with @davidkelliott
=> Remove firewall rules for cortex-siam

terraform/environments/bootstrap/member-bootstrap/iam.tf
OAM permissions required to create a Sink, Sink policy and link.
This is to enable cross account cloudwatch monitoring for DSO to monitor different application teams metrics.
Required permissions will be added 
no
=> Add OAM permissions to MemberInfrastructureAccess

terraform/environments/core-shared-services/ad-fixngo.tf
and https://github.com/ministryofjustice/modernisation-platform/pull/6230
In summary, tactical solution for migrating Domain Controllers from Azure FixNGo estate.
Problem: the EC2 instances are not accessible via developers
Adds a key-pair for Administrator access to servers.  The key-pair private key is held in hmpps-domain-services account along with other domain specific secrets.
Adds a new role which can be assumed by developers (in same ways as member-shared-services) with minimum permissions required to access EC2 via Fleet Manager GUI.  Although any mod platform user can assume this role, the user can't login unless they also have access to hmpps-domain-services where the creds are stored.
The PR …
=> DSOS-2635: add ability to login via FleetManager

.github/ISSUE_TEMPLATE/new-environment.yml
See #6338 for context - This PR adds the new `github_action_reviewers` option into the environment request template.
=> Add github_action_reviewers option from PR #6338 to the account request template

terraform/environments/bootstrap/single-sign-on/policies.tf, terraform/environments/core-shared-services/ad-fixngo.tf
Please see https://github.com/ministryofjustice/modernisation-platform/issues/5970 and https://github.com/ministryofjustice/modernisation-platform/pull/6359
Added policy to allow SSO users ability to assume the core-shared-services-production "ad-fixngo-ec2-access".  This gives access to the FixNGo Domain Controller EC2s via FleetManager console.
Allows role to be assumed by Mod Platform SSO user and therefore EC2s to be accessed.
Not possible to test, other than the role policy does give the required permissions.
No
Alternatively, could add the additional permissions into member-shared-services role.  Just wanted to keep everything to do with …
=> DSOS-2635: add permissions for assuming ad-fixngo-ec2-access role

terraform/environments/core-shared-services/ad-fixngo.tf, terraform/environments/core-shared-services/files/ad-fixngo-ec2-user-data.yaml
Making progress, we can successfully access the EC2 instances but cannot join to domain as it doesn't resolve.
Adds resolver rules to live_data and non_live_data VPCs.
Also fixes an issue about automatically provisioning server. Need to add a SSM parameter containing the IDs of the hmpps-domain-services accounts.
Not really possible but the code is similar to what we have in the member accounts and that is working OK
No
=> DSOS-2635: ad fixngo more fixes

terraform/environments/digital-prison-reporting/iam.tf
dms:ModifyReplicationInstance
Add Permissions to manage DMS Instance
https://app.circleci.com/pipelines/github/ministryofjustice/digital-prison-reporting-domains/786/workflows/0b766364-5f9e-4e0e-bbc6-06b67154a736/jobs/2192
Add Permissions to manage DMS Instance, allows devs to manage DMS Configuration through TF Pipeline
Tested all okay on DPR Dev Sandbox Account
N/A
=> Add Permissions to manage DMS Instance

terraform/environments/bootstrap/single-sign-on/policies.tf
Allow platform users to manage elasticache resources in sandbox environments
This PR will allow all elasticache IAM actions
n/a
no impact expected
- [ x ] I have performed a self-review of my own code
n/a
=> Allow elasticache:* permissions in sandbox

terraform/modules/app-ecr-repo/main.tf
Remove the force suffix `-ecr-repo` from the repo name.
ECR does call it the repo name, but it is technically the image name.
Removes the forced suffix - adds a ignore on the name so that existing repos are unffected.
=> Remove forced suffix for ECR REPOs

.github/workflows/scheduled-baseline.yml
https://github.com/ministryofjustice/modernisation-platform/issues/6387
Traced the cause of the bug to the tests relying on something that is destroyed during the weekly nuke and ought to be recreated during the scheduled baseline. This ensures that the resources have been recreated ready for the start of the working week.
It hasn't
No
=> Switch scheduled baseline to sunday night after weekly nuke run

environments-networks/hmpps-preproduction.json, environments/electronic-monitoring-data.json, policies/networking/expected.rego
#6369 
Removes electronic-monitoring-data-preproduction account
=> Removing electronic-monitoring-data-preproduction Account

terraform/pagerduty/aws.tf, terraform/pagerduty/member-services-integrations.tf
Integrating alarms with PagerDuty and slack for Delius Core Application
creates new PD service and slack integration for delius core 
using the same template/blueprint to create the PD service and integrate with slack to send notifications to
No
=> NIT-1148 slack and pagerduty integration for delius core nonprod env

terraform/environments/core-shared-services/ad-fixngo.tf
The first azure.noms.root DC is working properly now, adding a second one for redundancy.
Provides redundancy for the solution
First server is working correctly now
No
=> DSOS-2635: add second devtest DC for FixNGo migration

terraform/environments/core-vpc/locals.tf, terraform/environments/core-vpc/secrets.tf, terraform/environments/core-vpc/vpc.tf
As per issue https://github.com/ministryofjustice/modernisation-platform/issues/6163 - this adds data items, locals and variable assignments to support the creation of AWS Firehose resources in the required environments - development & production. These are required for the transfer of vpc flow log data to the MoJ's SecOps team that will be used for protective monitoring purposes.
The module https://github.com/ministryofjustice/modernisation-platform-terraform-member-vpc has been updated to build these AWS Firehose & associated resources and this change adds the necessary locals, data items and variable assignments to support this for development & production vpcs.
This build has been tested in core-vpc-sandbox. …
=> Issue 6163 - Add Firehose Resources

terraform/environments/core-shared-services/ecr_repos.tf
Is part of https://github.com/ministryofjustice/data-platform/issues/3501
Adds ECR repos
N/A
N/A
No
=> 🐋 Add ECR repositories for Analytical Platform Ingestion

environments/oas.json
https://mojdt.slack.com/archives/C01A7QK5VM1/p1710337677949329
Adds requested team so that they have SSO access
N/A
Deploy through CI / Scheduled Baseline job
=> allow oas migration team instance management permissions to oas development

terraform/github/locals.tf
Presence of a user no longer in the Ministryofjustice GitHub Organisation causes terraform to report an error
Removes user who is no longer in the MOJ organisation
N/A
No
=> remove deactivated user

environments/ppud.json
As requested in the ask channel [here](https://mojdt.slack.com/archives/C01A7QK5VM1/p1710416114736549) I'm adding `fleet-manager` access to development/preproduction environments for members of the `ppud-replacement-devs` GH Team which Andrew Larcombe is in. 
Updated application.json file to grant access.
=> Add fleet manager access in PPUD

terraform/environments/bootstrap/single-sign-on/policies.tf
This adds appstream permissions to the sandbox_additional policy.
Member account user using oasys-development (which is a sandbox account) has experienced issues when attempting to create resources of that type.
=> Adds appstream permissions to sandbox_additional policy.

terraform/github/repositories.tf, terraform/github/teams.tf
After some discussion [here](https://github.com/ministryofjustice/modernisation-platform/issues/6334) this PR removes the module from code.
The behaviour of the terraform resource will archive this repository on deletion, and remove it from state so that it is no longer managed
https://mojdt.slack.com/archives/C013RM6MFFW/p1708431624229989
No
=> Remove modernisation-platform-infrastructure-test

terraform/environments/core-shared-services/ad-fixngo.tf
First prod DC can't resolve AD Users in infra.int - need to sort this out before promoting to be a DC. 
Temporarily destroying first DC and enabling the second one.  This will allow me to fix any networking before promoting to DC.  
We've done this a few times now.
No impact to prod services
=> DSOS-2635: enable second prod FixNGo DC

terraform/environments/core-shared-services/ad-fixngo.tf
Prod DC can't resolve AD Users in infra.int - need to sort this out before promoting to be a DC.
Rebuild of the first prod DC without promoting to a DC this time. We can then sort out any connectivity issues using the fixed IPs of the DCs.
We've done this a few times now.
No
=> DSOS-2635: re-enable first prod fixngo DC

terraform/modernisation-platform-account/secrets.tf
This adds a new secrets that hold Xsiam endpoint values for sharing data for the vpc flow log data and firewall inspection logs.
Ref issue 6163 (https://github.com/ministryofjustice/modernisation-platform/issues/6163)
See title
=> New Secret for XSIAM Endpoints & Keys

collaborators.json
Syscon are responsible for development of nomis and nomis live support. Adding syscon engineers who are not part of the MoJ Org to the collaborators list
Gives access to nomis-development EC2 instances to syscon
N/A
No
=> DSOS-2667: add syscon collaborators to nomis-development

terraform/environments/core-network-services/firehose.tf
Fixes bug whereby the unique prefix assigned to the firehose resource names was too long. This reduces it to three and allows for it to be identifiable.
See above
=> Issue with values assigned to resource_prefix being too long.

terraform/environments/core-network-services/firehose.tf
As per title. This change adds an additional module call to generate firehose data streams for the firewall VPC flow logs.
This covers one of the requirements to share vpc flow log data with SecOps.
Has been tested via local plan.
=> Firehose Data Transfers - Adds an additional module call but for the firewall vpc flow logs.

terraform/environments/bootstrap/member-bootstrap/iam.tf
This pull request adds permissions for interacting with Internet and NAT Gateways
When trying to create a new VPC in Analytical Platform Ingestion, this error is returned
```bash
Error: creating EC2 Internet Gateway: UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:sts::730335344807:assumed-role/MemberInfrastructureAccess/aws-go-sdk-1710763531327859576 is not authorized to perform: ec2:CreateInternetGateway on resource: arn:aws:ec2:eu-west-2:730335344807:internet-gateway/* because no identity-based policy allows the ec2:CreateInternetGateway action.
```
https://github.com/ministryofjustice/modernisation-platform-environments/pull/5400
It hasn't
A quick search for `CreateInternetGateway` in GitHub doesn't show an `Deny` policies
=> 🛂 Add IGW and NAT GW permissions to `MemberInfrastructureAccess`

policies/environments/environment-definitions.rego
In this Slack thread https://mojdt.slack.com/archives/C013RM6MFFW/p1710935860985819 - we created a new account but missed out a mandatory field `github-oidc-team-repositories`
Test added which will check for inclusion of this field in application.json file. If this fails PRs wont be able to be merged.
Locally I tested this by removing the field in example.json...
```
❯ ./scripts/tests/validate/run-opa-tests.sh
PASS - Environment files check
PASS - Environment network files check
8 tests, 8 passed, 0 warnings, 0 failures, 0 exceptions
374 tests, 374 passed, 0 warnings, 0 failures, 0 exceptions
110 tests, 110 passed, 0 warnings, 0 failures, 0 exceptions
FAIL - - main - `environments/example.json` is missing the …
```
=> Add test to check for missing github-oidc-team-repositories field

terraform/environments/core-shared-services/ecr_repos.tf
This is required to allow our Lambda functions which are being created in `analytical-platform-ingestion` to pull their images.
Enables the above. 
Mirrors the same approach in other ECR repositories in the same file. 
No
NA
=> :wrench: Enable Retrieval for Lambdas - AP Ingestion

terraform/environments/core-logging/firehose.tf, terraform/environments/core-logging/locals.tf, terraform/environments/core-logging/secrets.tf, terraform/environments/core-shared-services/firehose.tf, terraform/environments/core-shared-services/locals.tf, terraform/environments/core-shared-services/secrets.tf
As per title, this adds firehose resources into the two above core accounts in order to share vpc flow log data with SecOps.
=> Adds firehose resources for vpc flow logs in core-shared-services and core-logging.

environments-networks/hmcts-preproduction.json, environments-networks/hmcts-production.json
Adding vpc endpoints to allow ecs to access ecr. This issue occurred after disabling public ip addresses on the ecs service.
It allows for internal communication between the services on a vpc.
The ECS deployments were failing before making this change on the development environment.
=> add vpc endpoints for hmcts preprod and prod

terraform/environments/bootstrap/secure-baselines/providers.tf, terraform/environments/bootstrap/secure-baselines/versions.tf
https://github.com/ministryofjustice/modernisation-platform/issues/6486
I've reverted the code that was pinning the version of the AWS TF provider back to `v5.38.0`
The jobs are now picking up the latest version `v5.42.0` which has had an update that stops client side rate limiting which stops you getting the original error we encountered e.g. 
`failed to get rate limit token, retry quota exceeded, 3 available, 5 requested`
But we were still encountering this error e.g. 
`ListTagsForResource, exceeded maximum number of attempts, 25, https response error StatusCode: 400, RequestID: c17f1153-756e-4968-bd57-e38a51792366, api error ThrottlingException: Rate exceeded`
There is an optional [max_retries](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#max_retries) setting that …
=> Removed pinned provider version & increased max_retries for Secure Baselines

terraform/environments/core-logging/firehose.tf, terraform/environments/core-network-services/firehose.tf, terraform/environments/core-security/firehose.tf, terraform/environments/core-shared-services/firehose.tf, terraform/environments/core-vpc/firehose.tf, terraform/environments/core-vpc/locals.tf, terraform/environments/core-vpc/vpc.tf, terraform/modules/firehose/main.tf, terraform/modules/firehose/variables.tf, terraform/modules/r53-resolver-logs/main.tf
This covers the last set of firehose stream transfers to SecOps - namely the resolver logs for the member account shared VPCs that is managed in core-vpc. It also covers a number of other changes including the use of a more descriptive common_attribute value plus other simplifications.
See above.
Local plan with the core-vpc workspaces
No resources are being deleted - mainly additions and some changes for the new common_attribute var.
=> Adds firehose stream resources for R53 resolver logs plus other minor changes.

environments/oasys-national-reporting.json
Nart team need access to oasys-national-reporting environment, mainly to familiarise themselves as it's moved
Gives them access
Adding github stub, should just work
No 
=> allow nart team access to test, preproduction and production onr envs

terraform/modules/firehose/versions.tf
- Terraform Static Analysis check failed [here](https://github.com/ministryofjustice/modernisation-platform/actions/runs/8447886732/job/23138986897)
- The failure was due tflint complaining about a missing version constraint for the `random` provider [here](https://github.com/ministryofjustice/modernisation-platform/actions/runs/8447886732/job/23138986897#step:4:3448)
- Adds version constraint to the `random` provider. (latest is 3.6, but I've gone for 3.4 since that's what the rest of the codebase uses)
By running `tflint` locally in the `terraform/modules/firehose/` directory before and after the change. I could see the failure disappear ✅ 
No
Interesting how this wasn't caught in the initial …
=> ✨ Add version constraint to `random` provider

.github/workflows/terraform-static-analysis.yml
- In relation to https://github.com/ministryofjustice/modernisation-platform/issues/6625
- v16 of `terraform-static-analysis` action only compares against previous commits which doesn't work well in the context of a PR. 
- v17 now compares the entire branch to ensure all changes in a PR go through static analysis.
- Tested the new command locally against a branch with multiple terraform changes. Using the new command we capture all the changes on the branch instead of just the changes against the previous commit.
- Created a test [PR](https://github.com/ministryofjustice/modernisation-platform/pull/6638) with some terraform changes and can see the first commit with tflint errors is caught
Will this deployment …
=> 🆙 Update `terraform-static-analysis` to `v17.0.1`

terraform/environments/core-shared-services/vpc_additional_cidr.tf
https://github.com/ministryofjustice/modernisation-platform/issues/6633
Aligns additional VPC cidr block with allocated range
Tested with non-prod range successfully
=> Update additional address range for core-shared-services VPC to production range

environments/delete-account.json, policies/environments/expected.rego
https://github.com/ministryofjustice/modernisation-platform/issues/6457
Creating a new account called "delete-account" (unless anyone has another name preference!) 
This will allow us to to an end-to-end test on the account deletion script without disturbing any live member environments.
It has two envs 'development' and 'test' so that we have at least one workspace to delete which we can use to test the logic in our scripts.
=> Create new 'delete-account' for testing deletion scripts

terraform/modules/vpc-nacls/data.tf
https://github.com/ministryofjustice/modernisation-platform/issues/6633
Because our `vpc-nacls` module was never written with the expectation that we would allow east/west traffic between accounts, and because the use of a routable range in `core-shared-services` is a temporary addition until we can have the `core` address ranges routable, I've allowed this traffic in a static rule that will appear before a NACL rule that denies east/west traffic.
It's possible that we could re-write the module to allow lookups in different accounts, but I think this would mean more engineering time than we expected and I don't think it's behaviour that we'd like to encourage vs more cloud-centric approaches like PrivateLink.
Tested behaviour with a local plan against `core-vpc-development`
Will this …
=> Allow traffic to temporary `core-shared-services` range

environments/operations-engineering.json, policies/environments/expected.rego
#6361 
Adds content required to create new `operations-engineering` account
Followed steps in [team runbook](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/creating-accounts-for-end-users.html#new-environment-files).
=> Create `operations-engineering` account

environments/corporate-staff-rostering.json, environments/hmpps-domain-services.json, environments/hmpps-oem.json, environments/nomis-combined-reporting.json, environments/nomis-data-hub.json, environments/nomis.json, environments/oasys-national-reporting.json, environments/oasys.json, environments/planetfm.json
Missing standard mod platform CI/CD role from DSO accounts. Trying to migrate to this rather than having custom CI/CD roles in the account.
Enables mod platform provided CI/CD role
N/A
No
=> add cicd repos to DSO accounts

terraform/environments/core-shared-services/vpc_additional_cidr.tf
https://github.com/ministryofjustice/modernisation-platform/issues/6633
* Adds a security group entry allowing traffic to reach VPC endpoints.
* Adds a route table association resource to ensure the additional subnets are correctly routed to the S3 endpoint
Tested locally & through manual change
No
=> Allow new `core-shared-services` CIDR range to communicate with VPC endpoints

.github/workflows/new-environment.yml, environments/corporate-staff-rostering.json, environments/hmpps-domain-services.json, environments/hmpps-oem.json, environments/nomis-combined-reporting.json, environments/nomis-data-hub.json, environments/nomis.json, environments/oasys-national-reporting.json, environments/oasys.json, environments/planetfm.json
New environment pipeline is failing when multiple environment json files are changed.
See https://github.com/ministryofjustice/modernisation-platform/actions/runs/8525989352
I think it is because the syntax for adding a multiline variable to GITHUB_OUTPUT is not quite right.
This PR just uses single line instead, which seems to be what the $accounts variable a bit further down is expecting anyway.
Note the whitespace changes are just to trigger applies in the environments that were changed in previous PR
Not easy to test as this section of pipeline only runs on main.
No - worst case the variable is not set properly so the subsequent pipeline steps …
=> DSOS-2668: new-environment pipeline fix

environments/observability-platform.json, terraform/environments/core-shared-services/ecr_repos.tf
This is required as we are making this repository a lambda function - https://github.com/ministryofjustice/observability-platform-grafana-api-key-rotator/tree/scaffold-image. We need an ECR to host the image in.
Creates the ECR
NA
NA
=> 🛠️  Create ECR for Observability Platform Key rotation lambda

source/index.html.md.erb, source/runbooks/migrating-an-account-into-the-modernisation-platform.html.md.erb
https://github.com/ministryofjustice/modernisation-platform/issues/6416
Adds a runbook with guideline steps for importing an account.
Based off of notes taken during NOC account import story
No because it's a runbook
=> Add runbook for account migration

environments/cica-data-extraction.json
https://github.com/ministryofjustice/modernisation-platform/issues/6559
Corrects the `github_slug` of the team after a conversation with @Adenipex 
No testing
No
=> Update github slug for cica-data-extraction application

terraform/environments/bootstrap/member-bootstrap/iam.tf
Noticed that we had an incorrect policy attachment to the `MemberInfrastructureBedrockEUCentral` role.
Applies the correct IAM Policy to the `MemberInfrastructureBedrockEUCentral` role
It has not.
=> Fix policy reference for the bedrock provider role

environments/cica-data-extraction.json
Customer wants sandbox access for bedrock investigation
Sandbox allows clickops for bedrock. Rebuild ensures resources are rebuilt from code following a full account wipe.
Used in other environments (eg. `tipstaff).
No. Until the nuke job removes everything in the `cica-data-extraction-development` account.
=> Set cica-data-extraction development access to sandbox with rebuild flag

terraform/environments/bootstrap/secure-baselines/locals.tf, terraform/environments/bootstrap/secure-baselines/main.tf
https://mojdt.slack.com/archives/C01A7QK5VM1/p1711528538461979
Bumps the module reference for the baselines module.
Adds a dynamic selector so that if the `terraform.workspace` belongs to `"digital-prison-reporting"`, a `false` value is supplied and S3 management events are not logged.
Ran local terraform plan
=> Bump baselines module, add dynamic selector for cloudtrail s3 events

.github/workflows/new-environment.yml
https://github.com/ministryofjustice/modernisation-platform/actions/runs/8604863743/job/23580726692
This should resolve the incorrect output expansion introduced in https://github.com/ministryofjustice/modernisation-platform/pull/6720
Ran expansion in local bash (substituting expansion of step output for existing variable)
No
=> Fix step output expansion

terraform/environments/core-logging/s3_logging.tf
Removed some complexity. The sqs permission should only apply to the queue and not the bucket which is possibly why the policy update was failing. Also removed the confition as it is now redundant due to the resources list.
- x ] I have performed a self-review of my own code
=> Issue 6614

.github/workflows/opa-policies.yml
This PR adds merge_group to the OPA workflow check required for merge queue.
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group
=> Adding merge group for merge queue

terraform/github/README.md, terraform/github/repositories.tf, terraform/github/teams.tf
Removing the [modernisation-platform-incident-response](https://github.com/ministryofjustice/modernisation-platform-incident-response) from our repositories, as the infrastructure that this code relates to has been decommissioned a while ago. This repository has been archived in the past, but then kept in code which resulted in it being unarchived.
This repository has been archived again and now it needs deleting in code.
It will make sure that [modernisation-platform-incident-response](https://github.com/ministryofjustice/modernisation-platform-incident-response)
Terraform plan run clean locally.
No impact, the repo is already archived, this is just a code cleanup.
Updated README to include instructions on how to archive a repository.
=> Decommissioning the incident response

.github/workflows/check-inactive-collaborators.yml, scripts/internal/collaborators-inactivity-notification/check_inactive_users.sh, scripts/internal/collaborators-inactivity-notification/disable_user_credentials.sh
This PR addresses the implementation of a feature to disable console logins and access keys for `inactive collaborator users` after 120 days of inactivity. #6390 
This PR introduces a new job that identifies collaborator users with inactivity of 120 days or more and disables their console login and access keys. 
Tested this new functionality in the sprinkler environment to validate its effectiveness and reliability under various scenarios.
=> Implement Feature to Disable Console Login and Access Keys for `Inactive Collaborator Users`

.github/workflows/check-inactive-collaborators.yml, scripts/internal/collaborators-inactivity-notification/disable_user_credentials.sh
This PR addresses two issues:
1. It adds conditional logic to the notify-inactive-collaborators job to run the notification script only if the final_users.list file exists. This prevents unnecessary execution of the script when the file is absent.
2. It includes an if block in the disable_user_credentials.sh script to check if access keys are not empty before executing commands related to making access keys inactive. This prevents errors that occur when attempting to execute commands on empty access key lists.
This PR fixes the issues by adding conditional logic to ensure the notification script is only executed when the final_users.list file exists, preventing unnecessary execution and potential errors. It also adds an if block to the disable_user_credentials.sh script to check for empty …
=> Add Conditional Logic for Notification Script and Error Handling for Access Keys

terraform/environments/core-network-services/cidr-ranges.tf, terraform/environments/core-network-services/firewall-rules/production_rules.json, terraform/environments/core-network-services/firewall-rules/sets.json
Data Engineering are unable to access Oasys DB in Mod Platform
Adds required firewall rules
n/a
No
=> oasys: DSOS-2736: allow data engineering ip ranges to hmpps production

terraform/environments/core-network-services/firewall-rules/preproduction_rules.json, terraform/environments/core-network-services/firewall-rules/production_rules.json
Data engineering cannot access preproduction Oasys DB.  Following further conversation with data engineering teams, the production rules are also too permissive.
Add preproduction firewall rule and restrict the production rule.
No
=> DSOS-2736: tweak data engineering firewall rules

terraform/environments/bootstrap/member-bootstrap/iam.tf
Enabling the OIDC CI/CD role to write clouwatch metric data
Adds the  relevant permission to the policy for the above mentioned user
n/a
No impact expected.
n/a
=> DSO: add cloudwatch:PutMetricData to cicd role

terraform/environments/bootstrap/single-sign-on/policies.tf
This PR addresses an issue where users were unable to connect to EC2 instances due to missing permissions. The problem stemmed from insufficient permissions related to SSM. To resolve this issue, this PR adds the necessary permissions to the migration role.
This fix ensures that users can now successfully connect to EC2 instances using the SSM
.
tested this one on sprinkler
=> Add Missing SSM Permissions to Migration Role

terraform/environments/bootstrap/member-bootstrap/collaborators.tf, terraform/environments/bootstrap/single-sign-on/main.tf, terraform/environments/bootstrap/single-sign-on/policies.tf, terraform/single-sign-on/sso-permission-sets.tf
The current instance-management role is quite permissive.  It allows users to see all secrets and to stop/start instances.  Since some secrets may contain system database credentials within DSO accounts, this is too permissive to give to users in production accounts who just want to access instances.
I propose we create a new instance-access role designed for users who need login access to EC2s.
The proposed role includes conditions based on resource tags to restrict access.
Add an instance-access-policy tag on resources to control access as follows:
tag doesn't exist = s3 put; no secret access;  ec2 ssm full access
"none" = s3 put; no secret access;  no ec2 ssm access
"limited" = s3 put; read-only  secret; ec2 ssm ssh/port-forwarding only
"full"  = s3 put; read-write secret; ec2 ssm full …
=> DSOS-2720: propose a new instance-access role

terraform/environments/bootstrap/member-bootstrap/iam.tf
I've hit a permission issue when trying to copy a snapshot encrypted with a shared KMS key in the `core-shared-services` account, using the GitHub OIDC role.
https://github.com/ministryofjustice/hmpps-delius-operational-automation/actions/runs/8754004224/job/24034310053
I think this is due to a missing `kms:CreateGrant` action in the policy.
Adds required action to GitHub OIDC role.
=> Add kms:CreateGrant action to OIDC role

terraform/environments/bootstrap/single-sign-on/policies.tf
This PR updates the instance-management role by granting the `autoscaling:UpdateAutoScalingGroup` and `autoscaling:SetDesiredCapacity` permissions.
Updates instance-management policy
tested this on sprinkler
=> Enable Autoscaling for instance management role

terraform/environments/bootstrap/single-sign-on/policies.tf
This PR grants `glue:StartTrigger` and `glue:StopTrigger` to the reporting-operations role
This allows the mp-reporting-operations user to deactivate and re-activate glue triggers
This is to be tested in development
This should not impact the platform and / or services on it
N/A
=> DPR2-622: Grant glue:StartTrigger and glue:StopTrigger to reporting-operations role

environments/hmpps-oem.json, environments/nomis-combined-reporting.json, environments/nomis-data-hub.json, environments/nomis.json
Current SSO access is too permissive, e.g. root access and secret access to all accounts for application support teams
Modified existing access for application support teams
- instance-management for dev and test (so servers can be restarted etc, and full secret access)
- instance-access for preprod and prod (no root access or secret access unless tags allow)
Add csr-application-support to nomis accounts for visibility and hmpps-oem which is centralised monitoring. On Glenn Barber's request.
Instance-access role tested in nomis-development by DSO.
No
=> DSOS-2720: revised DSO account access

.github/workflows/format-code.yml
This PR excludes files matching `'terraform/modules/**/*.md'` from the code-formatter markdown linter as these are covered by the `.github/workflows/documentation.yml` workflow which triggers when a PR is opened. 
These two code formatting are currently conflicting with each...
commit created by code formatter: https://github.com/ministryofjustice/modernisation-platform/pull/6846/commits/f12f04a54cbd6df3f9c3da91e39e58bbf10e11f0
commit created by terraform-docs (undoing the above) https://github.com/ministryofjustice/modernisation-platform/pull/6846/commits/5d03d793658ccf999017ce23b6f28d2dd262bd09
=> 📝  Excluded Terraform Docs from Code Formatter

terraform/environments/core-shared-services/ad-fixngo.tf, terraform/environments/core-shared-services/files/ad-fixngo-ec2-user-data.yaml
Please see https://github.com/ministryofjustice/modernisation-platform/issues/5970 and https://github.com/ministryofjustice/modernisation-platform/issues/6633
The first azure.hmpp.root DC is built and can connect to some of the dom1.infra.int DCs. 
Building the second one.  Also fixes issue with the automatic provisioning due to old version of chocolatey on the windows AMI.
Installs second domain controller for redundancy
First DC is working and no issues reported.
=> DSOS-2711: add second azure.hmpp.root domain controller

terraform/environments/bootstrap/member-bootstrap/collaborators.tf
This is the PR that is going to add bedrock back into the collaborators sandbox role
Added new policy back 
=> adding bedrock policy to collaborators

.github/workflows/core-vpc-development-deployment.yml
Removes the -target flags from the core-vpc-development-deployment job in order to confirm its correct working. If the plan runs correctly then other -target flags will be removed from the plan for the other accounts. If it fails the change will be reverted. 
https://github.com/ministryofjustice/modernisation-platform/issues/6615
As -targets limits the scope of the plan, any new resources created via a module call will be excluded from the plan. This is to confirm whether removing the targets doesn't result in plan errors.
=> Test to confirm the core-vpc-development-deployment plan runs correctly without the -target flags.

.github/workflows/format-code.yml
Following this [PR#6856](https://github.com/ministryofjustice/modernisation-platform/pull/6856) yesterday the format-code run failed this morning: https://github.com/ministryofjustice/modernisation-platform/actions/runs/8811176076/job/24193462974 
updating variable for terraform flavour https://megalinter.io/7.11.1/descriptors/markdown_markdownlint/
=> Format-code Fix Varible for terraform flavour 

.github/workflows/format-code.yml
update regex expression to exclude `terraform/modules/<dir>/<filename>.md` from markdown linter checker.
=> Fixup Megalinter regex expression

terraform/environments/bootstrap/secure-baselines/main.tf
This PR uses the latest release of `modernisation-platform-terraform-baselines` which deletes the default vpc functionality
More information can be seen in the release notes here: https://github.com/ministryofjustice/modernisation-platform-terraform-baselines/releases/tag/v7.0.0
=> Update baseline module reference and remove enabled_vpc_regions parameter

terraform/environments/core-logging/iam.tf, terraform/environments/core-logging/vpc.tf, terraform/environments/core-network-services/firewall.tf, terraform/environments/core-network-services/iam.tf, terraform/environments/core-network-services/monitoring.tf, terraform/environments/core-network-services/vpc.tf, terraform/environments/core-security/iam.tf, terraform/environments/core-security/vpc.tf, terraform/environments/core-shared-services/iam.tf, terraform/environments/core-shared-services/vpc.tf, terraform/environments/core-vpc/iam.tf, terraform/environments/core-vpc/vpc.tf
This PR addresses the issue caused by the removal of the baseline module, which contained the AWSVPCLog role. To resolve this, I've added the AWSVPCLog role and related resources directly to the core accounts.
=> Add AWSVPCLog role and related resources for VPC logging

.github/workflows/new-environment.yml, .github/workflows/remove-default-vpc.yml, scripts/internal/remove-default-vpc/remove_default_vpc_all_accounts.sh, scripts/internal/remove-default-vpc/remove_default_vpc_new_account.sh
This PR adds a new job, "remove default vpc," to the existing workflow. Additionally, it includes the corresponding script to handle the removal of default VPCs. This job is triggered when a new file is added or modified in the environments folder. It ensures that any default VPCs associated with the affected accounts are removed, addressing potential issues related to default VPC configurations. #6488 
This PR addresses the problem by introducing a systematic approach to handle default VPC removal when new files are added or modified in the environments folder. By adding the `remove default vpc` job to the `new-environment` workflow and providing the necessary script, it ensures that default VPCs are removed for the affected accounts
Please describe the tests that you ran and provide …
=> Add `remove default vpc` job to `new-environment`workflow and corresponding script

.trivyignore.yaml
Added a CVE to trivyignore; this appears to be a downstream dependency that doesn't appear in our local `go.mod`, or in `go mod graph` but I suspect it's [terratest related](https://github.com/ministryofjustice/modernisation-platform/actions/runs/8874592977/job/24362332657#step:4:192):
```
go mod graph | grep github.com/opencontainers
github.com/gruntwork-io/terratest@v0.46.14 github.com/opencontainers/go-digest@v1.0.0
github.com/gruntwork-io/terratest@v0.46.14 github.com/opencontainers/image-spec@v1.0.2
```
=> Addressed SCA failure

.github/workflows/collaborator-inactivity-monitoring.yml, .github/workflows/remove-default-vpc.yml, scripts/internal/remove-default-vpc/remove_default_vpc_all_accounts.sh, scripts/internal/remove-default-vpc/remove_default_vpc_new_account.sh
This PR introduces error handling for subnet deletion in the script. It ensures that if an error occurs during subnet deletion, the script will proceed to the next region without attempting to delete the VPC. Additionally, it updates the cron job schedule to run on Mondays instead of using the day of the week abbreviation.
This PR addresses the issue by providing error handling for subnet deletion, preventing the script from attempting to delete the VPC if an error occurs during subnet deletion. Furthermore, updating the cron job schedule to specify the day of the week explicitly ensures that the job runs consistently on Mondays, avoiding any ambiguity or potential issues with different system configurations.
tested this on sprinkler …
=> Implement error handling for subnet deletion and update cron job schedule

source/team/ways-of-working.html.md.erb
Documents our agreed approach towards firebreak sprints, as discussed [here](https://mojdt.slack.com/archives/C013RM6MFFW/p1714385189450159)
=> Added firebreak section to Ways of Working

environments/nomis-combined-reporting.json
Unable to test access for application support teams within the nomis-combined-reporting application
Grants DSO team the same permissions as application support teams.
n/a
No
=> DSOS-2748: give DSO team instance-management and access roles for nomis combined reporting

terraform/environments/core-logging/athena.tf
Support for python 3.8 ends in October 2024.  Updating to keep in support.
Updates to the latest supported version
Tested on the Lambda, changed run time then ran, no issues.
No impact
- [x All checks have passed
=> Update python runtime to 3.12

environments-networks/hmpps-development.json, environments-networks/hmpps-production.json
As per [this Slack conversation](https://mojdt.slack.com/archives/C01A7QK5VM1/p1714465418982979)
Adds AWS Glue VPC endpoints for customer use
=> Add glue endpoints to vpcs shared with electronic-monitoring-data

terraform/environments/core-shared-services/vpc_additional_cidr.tf
Without the enforced `availability_zone` argument we can't be certain where additional subnets will be created.
Because the value we use to populate the `for_each` block looks like this:
```
> local.additional_subnet_cidr_map
{
"eu-west-2a" = "10.27.136.0/24"
"eu-west-2b" = "10.27.137.0/24"
"eu-west-2c" = "10.27.138.0/24"
}
```
We can set `availability_zone = each.key` to consume the AZ name from the map of subnets.
=> Build additional subnets in correct availability zones

terraform/environments/core-logging/iam.tf, terraform/environments/core-network-services/iam.tf, terraform/environments/core-security/iam.tf, terraform/environments/core-shared-services/iam.tf, terraform/environments/core-vpc/iam.tf
This PR addresses the issue where VPC flow logs were not being sent to the CloudWatch log group due to missing permissions. By adding the necessary permissions to the existing role, this problem is resolved
This PR fixes the problem by adding the missing permissions required for sending VPC flow logs to the CloudWatch log group.
=> Fixing VPC Flow Logs Permissions

terraform/environments/core-network-services/firewall-rules/test_rules.json
Customer needs traffic to flow between the ccms-ebs-upgrade test account and their LZ test account. In order to do this, i have followed the process below,
https://user-guide.modernisation-platform.service.justice.gov.uk/concepts/networking/network-firewall.html#amending-rules
The PR amends the rule that allows connectivity between the 2 accounts
=> feature/6753 - firewall rule to allow traffic between laa LZ account and new test account

terraform/environments/bootstrap/single-sign-on/policies.tf
[{Please write here}](https://github.com/ministryofjustice/data-platform-support/issues/572)
The requested permission is needed for operational support and remediation of production problems
Requested permission is added to the data engineering role
This can only be tested post-apply.
This change and atomic and shouldn't have impact on the rest of the platform
=> Add lambda:PutRuntimeManagementConfig permission

terraform/github/modules/repository/main.tf
It add a dynamic block for `secret_scanning` and `secret_scanning_push_protection` if the repository is not public and therefore fixes the problem from [this alert](https://mojdt.slack.com/archives/C013RM6MFFW/p1714560729082999).
```
Error: PATCH https://api.github.com/repos/ministryofjustice/modernisation-platform-security: 422 Secret scanning can only be enabled on repos where Advanced Security is enabled. []
```
Terraform plan runs clean.
Deployed one merge with main.
=> Adding dynamic block for secret scanning

terraform/modules/vpc-nacls/data.tf
While some legacy services may require the use of a wide range of ports for return traffic, RDP traffic in from internet hosts is not desirable.
Ensures that traffic to the registered port for Remote Desktop Protocol (`tcp/3389`) is dropped by VPC NACLs applied to public subnets.
Ran local `terraform plan`
=> Add entry to prevent RDP traffic in to public subnet hosts

terraform/environments/bootstrap/single-sign-on/policies.tf
Running a `terraform plan` locally currently runs into a missing permission for OAM.
Add the permission to the `modernisation-platform-developer` role.
Added the permission indicated missing by `terraform plan`:
`Error: listing tags for CloudWatch Observability Access Manager Sink (arn:aws:oam:eu-west-2:X:sink/7d4f9ba0-e432-49d1-8f34-1fda2d165bf8): operation error OAM: ListTagsForResource, https response error StatusCode: 403, RequestI
D: 4f6d8ab2-b8dd-4f2f-87dc-2158cc8e05c3, api error AccessDeniedException: User: arn:aws:sts::X:assumed-role/AWSReservedSSO_modernisation-platform-developer_ad9787b9bbb44c29/jnq@digital.justice.gov.uk is not authorized to perform
: oam:ListTagsForResource on resource: …
=> DSO: add persmissions for 'resource "aws_oam_sink_policy"' to enable local terraform plan

terraform/environments/core-shared-services/ad-fixngo.tf
Please see https://github.com/ministryofjustice/modernisation-platform/issues/5970 and https://github.com/ministryofjustice/modernisation-platform/issues/6633
The first azure.hmpp.root DC is built and can connect to some of the dom1.infra.int DCs.
This is second attempt at building the 2nd DC, should work this time following fix by David Sibley
Installs second domain controller for redundancy
Has been attempted before but failed due to subnet being in wrong AZ. Manually checked the subnet is not in correct AZ.
First DC is working fine.
=> DSOS-2711: ad-fixngo: add 2nd HMPP domain controller

.github/actions/decrypt-secrets/action.yml, .github/workflows/scheduled-baseline.yml, .github/workflows/secrets-retrieval.yml
This PR updates the workflow to utilize AWS Secrets Manager for retrieving secrets instead of relying on GitHub secrets. It introduces a new decrypt secrets action within the workflow to handle decryption of the secrets fetched from AWS Secrets Manager. Each job within the workflow has been modified accordingly to incorporate this change. #6627 
Previously, the workflow relied on GitHub secrets for accessing sensitive information. Now, it will retrieve the secrets from AWS Secrets Manager, enhancing security and providing more robust management of our sensitive data.
I tested this functionality by configuring the updated workflow in my private repository and ensuring that it successfully retrieves secrets from AWS Secrets Manager during workflow execution. I verified that the secrets were …
=> Update Workflow to Retrieve Secrets from AWS Secrets Manager

.github/workflows/new-environment.yml
This PR addresses an issue encountered during the execution of the `Remove Default VPC` job. Previously, the job relied on `GitHub secrets` to access sensitive information, such as the AWS account number. However, this caused a problem as the job was unable to retrieve the new environment number when executed, leading to failure in removing the default VPC in the first run.
To resolve this issue, this PR updates the job to retrieve secrets from AWS Secrets Manager instead of using GitHub secrets. By doing so, the job will be able to fetch the required environment number dynamically during execution, ensuring that it can successfully remove the default VPC.
This PR fixes the problem by updating the job to retrieve secrets from AWS Secrets Manager, which allows the job to dynamically fetch …
=> Update `remove-default-vpc` job to retrieve secrets from Secrets Manager

terraform/modules/vpc-hub/locals.tf, terraform/modules/vpc-hub/main.tf, terraform/modules/vpc-hub/outputs.tf
#2403 
This PR amends how network ACLs are created in the `vpc-hub` module. When the story was originally written this would have used the same `vpc-nacls` module that is currently used by the `modernisation-platform-terraform-member-vpc` code and applied to `core-vpc-*` environments.
This simplifies how and where NACL rules are defined. The content is now located in `locals.tf` under a series of simple maps - `static_acl_rules`, `public_access_acl_rules`, and `transit_gateway_acl_rules`.
As much as possible this is identical to the content in the `vpc-nacls` module to ensure consistency, although there may be future opportunities to trim these rules if we invest time in inspecting VPC flow logs for potential exceptions.
No changes to the `inspection` VPCs - those in …
=> Align NACLs used in `vpc-hub` module with `vpc-nacls` approach

.github/workflows/new-environment.yml
This PR addresses an issue where renaming the environment variable ENVIRONMENT_MANAGEMENT to AWS_ENVIRONMENTS did not replace the value as expected. Despite the renaming, the value remained unchanged, causing unexpected behavior.
The issue is fixed by ensuring that renaming the environment variable replaces the value as intended. This is achieved by implementing the necessary changes in the code to properly handle the renaming process, ensuring that the value associated with the variable is updated accordingly.
=> Fix Issue with Renaming Environment Variable

.trivyignore.yaml, terraform/environments/bootstrap/secure-baselines/main.tf
https://github.com/ministryofjustice/modernisation-platform/issues/6639
This PR updates the version of the baselines module to [v7.1.0](https://github.com/ministryofjustice/modernisation-platform-terraform-baselines/releases/tag/v7.1.0) which will set all Modernisation Platform accounts to default to using IMDSv2 for any new instances being created.
Successful plan in sprinkler which will be deployed first before merging the PR. I will test that the settings are enabled appropriately in Sprinkler before merging to main.
```
+ resource "aws_ec2_instance_metadata_defaults" "default" {
+ http_endpoint               = "no-preference"
+ http_put_response_hop_limit = -1
+ http_tokens                 = "required"
+ id                          = …
```
=> Default all new instances in MP Accounts to IMDSv2

terraform/modules/firehose/main.tf
https://github.com/ministryofjustice/modernisation-platform/actions/runs/9013691702/job/24764963203#step:4:2807
Secure Code Analysis run flagged an error to do with CMK rotation, but bucket is not encrypted with CMK
Adds Checkov skip to resource
Tested with SCA action
=> Add checkov skip for false positive on firehose error logging bucket

terraform/environments/bootstrap/secure-baselines/locals.tf, terraform/environments/bootstrap/secure-baselines/main.tf, terraform/environments/bootstrap/secure-baselines/providers.tf, terraform/modernisation-platform-account/README.md, terraform/modernisation-platform-account/baselines.tf
https://github.com/ministryofjustice/modernisation-platform/issues/6917
https://github.com/ministryofjustice/data-platform/issues/4222
Analytical Platform had a customer request to make Bedrock available in Paris due to model selection being better than Frankfurt. The region is not currently used and therefore bootstrapped on MP.
This updates provider definitions and adds `eu-west-3` to enabled regions. The last attempt had failed due to `sprinkler` not having been enrolled in SecurityHub at the org level. `sprinkler` and other accounts [have now been enrolled](https://github.com/ministryofjustice/aws-root-account/pull/904) and future accounts will be enrolled automatically.
[Last attempt](https://github.com/ministryofjustice/modernisation-platform/pull/6952) failed on apply to sprinkler …
=> :fr: Enabling Paris II: Rebaselining

terraform/modernisation-platform-account/baselines.tf
Scheduled SCA job is failing with errors: https://github.com/ministryofjustice/modernisation-platform/actions/runs/9058641080/job/24884654889
Pointed MP account baseline to v7.1.0 (I forgot to do this when updating the baseline call for members last week!) which will enable IMDSv2 as default for MP account.
Also ignoring Trivy warnings AVD-AWS-0136 & AVD-AWS-0132 at the module call.
Status check below.
=> Fix Static Code Failures for MP Baseline module call

source/index.html.md.erb, source/runbooks/set-up-macie.html.md.erb
New instructions on setting up Macie. Also includes the index to post it to the modernisation-platform instructions.
I have also included some instructions on setting this up using Terraform. This has been tested in Cooker and sets up Macie and includes a sample job. The account should be included in the MemberInfrastructureAccess role so this can be added.
Information
=> Initial setup macie instructions

environments/hmpps-intelligence-management.json
[Slack thread](https://mojdt.slack.com/archives/C013RM6MFFW/p1715869004904839) related to the problem.
Temporarily updating the GH team slug for [hmpps-intelligence-management](https://github.com/ministryofjustice/modernisation-platform/blob/main/environments/hmpps-intelligence-management.json) to unblock the baseline workflow.
=> Updating GH slug for hmpps-intelligence-management

terraform/environments/cooker/s3.tf
Part of this ticket https://github.com/ministryofjustice/modernisation-platform/issues/5346
It mentions " with the assistance of AWS support"
I want to merge this into main, have a bucket made from our module, and get AWS input on the security surrounding it and the policies. 
Already deployed.
=> Created bucket for AWS input

terraform/environments/bootstrap/member-bootstrap/collaborators.tf, terraform/environments/bootstrap/member-bootstrap/iam.tf, terraform/templates/modernisation-platform-environments-isolated/vpc.tf
As part of the check #6989 some errors are listed on checkov - CKV_TF_2 based on [ckv_ft_2 errors](https://github.com/ministryofjustice/modernisation-platform/actions/runs/9121756649) from the list of actions in [workflow action status]( https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/workflow-status.html#modernisation-platform-tools-amp-checks). The error relates to the code having no tag with a version number.
The code has been amended to put so that connects to the correct version of the called code and has removed the version number which is no longer needed.
Note, if terraform change the code, in the future, this will require updates to be made to the code.
=> Terraform code amended to correct CKV_TF_2 error.

source/runbooks/cloudwatch-networking-alarms.html.md.erb
Update of the review data on - [CloudWatch networking alarms](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/cloudwatch-networking-alarms.html)
=> New review date for cloudwatch-networing-alarms

environments/hmpps-intelligence-management.json
The original GH team that was used for the SSO of the `hmpps-intelligence-management` accounts was deleted which meant the loss of access to the accounts for the team that should manage them. These accounts are not used anymore, however they still have application resources in them (e.g. s3 buckets).
Updating GH slug for the ` hmpps-intelligence-management` accounts, so that the application team can do the cleanup of the resources prior to the accounts decommissioning.
=> Updating hmpps-intelligence-management GH slug for the account cleanup

terraform/environments/secrets.tf
For https://github.com/ministryofjustice/modernisation-platform/issues/2415
I'm planning to migrate some code I've created, that monitors all MP ec2 instances to get info back on their status, to the security repo so the results are not displayed in a public repository. I need the secret added to run the workflow in the security repository.
=> Add `environment_management` secret to MP Security Repo

environments/tribunals.json
Recreating the environment every week takes a long time, so I would like it not to be nuked (for a few weeks).
Won't nuke every weekend.
=> Update tribunals.json to exclude nuking

terraform/environments/core-shared-services/ad-fixngo.tf
PlanetFM has had a couple of incidents with failed DOM1 auth.
Removes the Mod Platform HMPP DCs to be on the safe side as issues correspond to periods of these DCs being in use. 
No - safe to run, DC software already stopped.
=> DSOS: temporarily decom HMPP DCs

environments/delius-core.json, environments/delius-nextcloud.json, scripts/git-create-environments.sh, source/runbooks/creating-accounts-for-end-users.html.md.erb, source/user-guide/creating-environments.html.md.erb
Following on from #6338, this allows specifying the owners at the access array level.
In #6338, github actions reviewers can be specified to override the default behavior (of selecting all teams), but this applies to all environments.
Adding support for the `github_action_reviewer` flag to each team allows picking a choosing which teams are added to the github environments required reviewers.
It is backwards compatible as if no `github_action_reviewer` flags are detected in the environment, it falls back to allowing all listed github slugs access.
I have tested the change to the environments file + the jq query locally - all other logic should still apply. …
=> Modify jq query to check for `github_action_reviewer` flag

environments/delius-core.json
[DST-17030](https://jira.engineering-dev.probation.hmpps.dsd.io/browse/DST-17030) - Initial work to migrate User Management Tool to Modernisation Platform.
Grants UMT repo permission to push docker images to ECR.
N/A
N/A
=> DST-17030 - Grant UMT repo permission to push images

environments/nomis.json
Additional access to nomis jump servers for `nomis-access` github team.
Allows members of this team access to Nomis jump servers.
Removes studio-webops instance-access access so we can test it works via this team.
n/a
No
=> DSOS: give nomis-access github team instance-access level

terraform/environments/core-network-services/firewall-rules/fqdn_rules.json
Nomis client test servers require MS Office to test an integrated document feature.  MS office won't install on Mod Platform.
Wireshark reveals that MS office is making some HTTP requests during the install.  Allow these domains through the firewall
n/a
No
=> DSOS-2822: add fqdn for ms office http install traffic

terraform/environments/core-network-services/firewall-rules/fqdn_rules.json
Unable to sign-in to MS Office to check Nomis functionality
Currently hanging on CRL checks. Allows the outbound HTTP to relevant URLs.
No
=> DSOS-2822: allow outbound CRL http checks

environments/cica-tariff.json, policies/environments/expected.rego
Create new environment cica-tariff. 
This will replace the current tariff environment. That will be removed under [Remove tariff environment](https://github.com/ministryofjustice/modernisation-platform/issues/7127)
=> New environment for CICA - cica-tariff

source/concepts/environments/instance-scheduling.html.md.erb
This adds a section to the Instance Scheduling page covering at a high level how use github workflow schedules to run the shutdown & startup of ec2 & rds instances.
Required for context and user information.
=> Flexible Schedules section added to the User Guide

terraform/environments/bootstrap/member-bootstrap/iam.tf
#7032 
Allows role assumed through GitHub Actions to make changes to AWS Shield, such as SRT role association.
Added permission as previous ones are added.
=> Allow Terraform to make Shield changes

terraform/environments/core-shared-services/ad-fixngo.tf
PR to set patch maintenance windows on the mod platform DCs
https://dsdmoj.atlassian.net/browse/DSOS-2746
This PR pulls in the mod platform ssm patching module and is used to patch one AD instance. 
On a successful deployment, I will create another PR to patch the remaining AD instances.
The plan has been inspected via a PR.
`
Plan: 18 to add, 2 to change, 0 to destroy.
`
There seems to be a change to a lambda (`module.instance_scheduler.aws_lambda_function.this`) but I have not done this
The deployment will not affect live services but the subsequent patch schedule will automatically patch `ad-azure-dc-a` instance next Tuesday.
After a successful deployment, I would like to create a similar PR for the remaining AD instances.
=> DSOS-2746 | Patch schedules for domain controllers

terraform/environments/core-shared-services/ad-fixngo.tf
[PR to create patch schedules for fixngo instances
](https://dsdmoj.atlassian.net/browse/DSOS-2746)
This PR references the mod platform ssm module to generate patch schedule for all fixngo instances.
An initial test on patching one instance was successfully done on a prior [PR](https://github.com/ministryofjustice/modernisation-platform/pull/7129).
In addition, the plan of this PR has been inspected.
The deployment will only deploy schedules so no other service will be affected. When those schedules come around, patching will occur on the instance that is referenced by the maintenance window.
Some of the schedules are for instances that are temporarily disabled / commented out. Those instances will be re-enabled in the future.
=> Add patch schedules to FixNGo servers

terraform/environments/core-shared-services/ad-fixngo.tf, terraform/modules/vpc-hub/main.tf, terraform/modules/vpc-inspection/firewall.tf
There are a number of checkov errors showing up in the daily static code analysis. This PR is to skip those checks (they are not required) so the errors no longer continue.
We may find additional ones pop up from time to time and these can be dealt with as they are found.
=> Skip some unrequired checkov checks

.github/workflows/core-logging-deployment.yml, .github/workflows/core-network-services-deployment.yml, .github/workflows/core-security-deployment.yml, .github/workflows/core-shared-services-deployment.yml
Removes the `cache dependency failed` message seen in Terraform jobs for `core-*` environments.
Hardcodes the relevant `go.sum` location.
See [here](https://github.com/ministryofjustice/modernisation-platform/actions/runs/9399380420) for more detail on this flag.
Tested in this action manual run: https://github.com/ministryofjustice/modernisation-platform/actions/runs/9399380420
=> Add cache dependency path to `setup-go` step

environments/operations-engineering.json
The Operations Engineering team are currently trialling a long running prototype of log streaming. This requires us to keep resources running over long periods (approx. 3 months). After this time, we can enable auto-nuke once more.
=> :wrench: Exclude environment from auto-nuke

terraform/environments/core-logging/s3_logging.tf
#7076 
The replication role module has been integrated into the main s3 bucket module so I removed the references to it and updated the source with the new release for the S3 bucket module.
Locally.
=> Removed references to the S3 replication role module

terraform/environments/digital-prison-reporting/iam.tf
This fixes the error below observed which prevents deployment of changes.
```
╷
│ Error: listing tags for CloudWatch Logs Log Group (arn:aws:logs:eu-west-2:771283872747:log-group:dms-tasks-dpr-dms-dps-generic-instance-development): operation error CloudWatch Logs: ListTagsForResource, https response error StatusCode: 400, RequestID: b9ac42da-35da-4f2a-bcb7-a634105d2103, api error AccessDeniedException: User: arn:aws:sts::771283872747:assumed-role/circleci_iam_role/circleci-oidc-session is not authorized to perform: logs:ListTagsForResource on resource: arn:aws:logs:eu-west-2:771283872747:log-group:dms-tasks-dpr-dms-dps-generic-instance-development because no identity-based policy allows the logs:ListTagsForResource action
│ 
│   with …
```
=> DPR2-713: Add logs:ListTagsForResource to circleci_iam_policy

terraform/environments/bootstrap/single-sign-on/policies.tf
Developer roles unable to trigger an ASG instance refresh manually.  This is required in some circumstances, e.g. when an automated refresh fails.
Grants the required permission.
N/a - standard policy change
No
=> Grant developer and instance-management role ASG instance refresh

terraform/environments/core-shared-services/s3.tf
Files are dropping into glacier after 365 days. AMI builds and other configuration management is failing as a result.
Removes glacier and expiration configuration. Enables additional tagging permission so `aws s3 cp` can be used in member accounts.
Standard policy change. Actual permissions can be tested after apply.
No
=> core-shared-services: s3 artefact fixes

.github/workflows/templates/workflow-template.yml
https://github.com/ministryofjustice/modernisation-platform/issues/7160
This is a ressurection of this [PR](https://github.com/ministryofjustice/modernisation-platform/pull/7159) originally raised by @jacobwoffenden
Removes `types` from `pull_request` in the workflow template for members so that changes to the PR body does not trigger workflow runs.
https://mojdt.slack.com/archives/C01A7QK5VM1/p1717497987776109 << shows the original convo regarding this
Already tested by Analytical Platform who use this in production
=> Remove `types` from `pull_request` in workflow template

terraform/environments/bootstrap/member-bootstrap/iam.tf
This is a short-term solution to the issues as described in MP issue 6991. This is combined with the plan evaluator change in Mod Platform Environments that will trap cloudformation resources included in PRs and require MP team approval.
This is a temporary solution whilst the issues with cloudformation:ResourceTypes is resolved and so unblocks MP member accounts who need to create these resource types.
This has been applied to sprinkler & tested successfully.
=> Adds cloudformation actions to the member-access policy re issue/6991

terraform/environments/bootstrap/single-sign-on/policies.tf
https://dsdmoj.atlassian.net/browse/DSOS-2832
There are cross account dashboards in cloudwatch that display errors when trying to display data. I believe we need to enable the  **View cross-account cross-region** feature in cloudwatch however attempting to do this triggers the below error.
```
User: arn:aws:sts::123456789:assumed-role/AWSReservedSSO_modernisation-platform-developer_ad9787b9bbb44c29/xxxxj@xxxx.justice.gov.uk is not authorized to perform: iam:CreateServiceLinkedRole on resource: arn:aws:iam::123456789:role/aws-service-role/cloudwatch-crossaccount.amazonaws.com/AWSServiceRoleForCloudWatchCrossAccount because no identity-based policy allows the iam:CreateServiceLinkedRole action 
```
Added `iam:CreateServiceLinkedRole` permission to developer_policy for …
=> Updated role with CloudWatch cross account permissions

terraform/environments/digital-prison-reporting/iam.tf
The circle-ci role does not have permissions to perform iam:DeletePolicyVersion and is causing the terraform apply to fail with the error: 
```
│ Error: deleting IAM Policy (arn:aws:iam::771283872747:policy/dpr-reporting-hub-batch-movements-development-policy) version (v1): operation error IAM: DeletePolicyVersion, https response error StatusCode: 403, RequestID: 96eb9db6-fb33-4156-bf27-a21d781b703e, api error AccessDenied: User: arn:aws:sts::771283872747:assumed-role/circleci_iam_role/circleci-oidc-session is not authorized to perform: iam:DeletePolicyVersion on resource: policy arn:aws:iam::771283872747:policy/dpr-reporting-hub-batch-movements-development-policy because no identity-based policy allows the iam:DeletePolicyVersion action
│ 
│   with …
```
=> DPR2-713: Add iam:DeletePolicyVersion to circleci

terraform/environments/bootstrap/single-sign-on/policies.tf
Application support teams unable to query nomis load balancer logs
Grants Athena query access to application support team roles (instance-management and instance-access)
N/A - standard policy change
No since just granting additional permissions
=> DSOS: grant athena access to instance-access and instance-management roles

environments/digital-prison-reporting.json
Resolves https://github.com/ministryofjustice/analytical-platform/issues/4551
In order to facilitate testing of integration between Analytical Platform and DPR, `data-engineer` access will be added to the dev, test and preprod DPR environments. 
It adds the roles to the json files.
This is difficult to test outside of applying.
This should not produce destructive changes
Prior to MP, this PR will be reviewed by the DPR developers.
=> Adding data-engineer role to DPR dev/test/prod accounts

terraform/environments/digital-prison-reporting/iam.tf
The DPR circle-ci role is failing to apply terraform changes in with the error:
```
│ Error: waiting for Glue Trigger (dpr-reporting-hub-archive-prisoner-development-trigger) to be Created: AccessDeniedException: User: arn:aws:sts::771283872747:assumed-role/circleci_iam_role/circleci-oidc-session is not authorized to perform: glue:GetTrigger on resource: arn:aws:glue:eu-west-2:771283872747:trigger/dpr-reporting-hub-archive-prisoner-development-trigger because no identity-based policy allows the glue:GetTrigger action
```
This PR fixes the issue by granting the glue:GetTrigger permission to the DPR circle-ci role.
N/A
No impact to the platform and …
=> DPR2-713: Grant glue:GetTrigger to DPR circle-ci role

terraform/pagerduty/aws.tf, terraform/pagerduty/member-services-integrations.tf
This commit adds the necessary resources and configurations to integrate Delius MIS production and non-production alarms with PagerDuty. It includes the creation of PagerDuty services, service integrations, and Slack connections for both environments.
=> feat: Add Delius MIS production and non-production alarms to PagerDuty

terraform/environments/bootstrap/member-bootstrap/iam.tf
Adds "ec2:DeregisterImage" to modernisation-platform-oidc-cicd role as requested by Dominic Robinson @20/06/24
=> Adds ec2:DeregisterImage to  modernisation-platform-oidc-cicd role

.github/workflows/opa-policies.yml, terraform/github/repositories.tf
`"Open Policy Agent: validate JSON structures"` runs on every PR.
This PR restricts the use of this action to only trigger when `*.rego` and `*.json` files present in a PR.
It has not been tested.
No.
=> Calm down OPA Validation workflow

collaborators.json
Additional access to T3 jumpserver via FleetManager for MoJ BAs who aren't part of MoJ github org
Adds them as collaborators
n/a - standard process
No
=> nomis: add additional collaborators for T3 environment

terraform/environments/bootstrap/single-sign-on/policies.tf
This pull request _hopefully_ resolves https://github.com/ministryofjustice/data-platform-support/issues/707
Adds missing S3 permission highlighted in CloudTrail event `c2b862e5-7854-45b7-88be-a7a9b4a129be`
It hasn't been tested
No, it is an additional IAM action
=> 🛂 Add `GetBucketOwnershipControls` to Data Engineering policy

.github/workflows/core-vpc-development-deployment.yml, .github/workflows/core-vpc-preproduction-deployment.yml, .github/workflows/core-vpc-production-deployment.yml, .github/workflows/core-vpc-test-deployment.yml
Duplicate targeted terraform apply in core-vpc workflows
This PR resolves the issue of the terraform apply command being executed twice in the `core-vpc `workflows. Specifically, the command `bash scripts/terraform-apply.sh terraform/environments/core-vpc -target=module.vpc` has been removed. This change ensures that terraform apply is only run once with the command `bash scripts/terraform-apply.sh terraform/environments/core-vpc`, eliminating redundant actions and improving the workflow's efficiency. The updated workflow is to verify that it functions correctly without the targeted terraform apply command with the new environment PR
=> Remove duplicate targeted terraform apply in core-vpc workflows

environments/mlra.json
Permissions required for Crime apps team to use AWS Glue (for Athena)
Add `data-engineer` access for the crime apps team.
N/A
No
=> LASB-2244: Updated crime apps access level for MLRA

.github/workflows/reusable_terraform_plan_apply.yml
This amends the 'Set Account Number' step in the reusable apply workflow to mask the account number variable as it appears in env output in subsequent steps.
https://github.com/ministryofjustice/modernisation-platform-security/issues/13
Uses the ::add-mask:: statement to prevent modernisation platform account number appearing in the env output of workflow logs.
This has been tested against the reusable workflow.
=> Masking account number variables as they appear in logs.

.github/workflows/bootstrap-sprinkler.yml, .github/workflows/collaborator-inactivity-monitoring.yml, .github/workflows/core-vpc-development-deployment.yml, .github/workflows/core-vpc-preproduction-deployment.yml, .github/workflows/core-vpc-production-deployment.yml, .github/workflows/core-vpc-test-deployment.yml, .github/workflows/new-environment.yml, .github/workflows/scheduled-baseline.yml, .github/workflows/secrets-rotation-reminder.yml, .github/workflows/superadmin-access-key-monitoring.yml, .github/workflows/terraform-member-environment.yml
Issue https://github.com/ministryofjustice/modernisation-platform-security/issues/13
This change amends the steps that pull account numbers so that the values are masked in subsequent env outputs in the workflow logs. 
This change is the same as that applied to the reusable workflow.
No services are impacted by this change.
=> Updates remaining workflows to mask account numbers in env log output.

terraform/environments/bootstrap/member-bootstrap/iam.tf
I'm trying to attach PTTP TGW to VPCs in Analytical Platform Compute
```
Error: creating EC2 Transit Gateway VPC Attachment: operation error EC2: CreateTransitGatewayVpcAttachment, https response error StatusCode: 403, RequestID: 3f1bc303-b5bf-49b6-a35f-ba966858ab85, api error UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:sts::381491960855:assumed-role/MemberInfrastructureAccess/aws-go-sdk-1719441876290007039 is not authorized to perform: ec2:CreateTransitGatewayVpcAttachment on resource: arn:aws:ec2:eu-west-2:381491960855:vpc/vpc-01001d7ad4d285e59 because no identity-based policy allows the ec2:CreateTransitGatewayVpcAttachment action.
```
Adds permissions for TGW attachments
Please describe the tests that you ran and provide instructions to …
=> 🛂 Add `TransitGatewayVpcAttachment` permissions

terraform/environments/bootstrap/member-bootstrap/iam.tf
`analytical-platform-compute` accounts have a non-MP AWS Transit Gateway shared with them through Resource Access Manager. In order to correctly filter information on these shares through Terraform, IAM permissions are required for the `MemberInfrastructureAccess` role.
However, because there are other uses of RAM shares to provision general customer accounts, I haven't given blanket `ram:*` permissions in this PR.
Allows member accounts to retrieve details of RAM shares for use in data calls.
It has not been tested
=> added permissions to get & list AWS RAM share resources

scripts/redact-output.sh
https://github.com/ministryofjustice/modernisation-platform-security/issues/13
Redacts account numbers from ARNs in workflow logs.
This change has already been applied in modernisation-platform-environments.
=> Adds aws account number redaction from ARNs listed in plan & apply log output.

policies/environments/environment-definitions.rego, policies/environments/environment-definitions_test.rego, source/user-guide/creating-environments.html.md.erb
https://mojdt.slack.com/archives/C013RM6MFFW/p1719306860238849?thread_ts=1719306746.916439&cid=C013RM6MFFW
I've added a test to check for a valid email address format in the `infrastructure-support` tag in application.json files
Example output tested locally before and after updating the field with a valid email:
```
❯ ./scripts/tests/validate/run-opa-tests.sh
PASS - Environment files check
PASS - Environment network files check
8 tests, 8 passed, 0 warnings, 0 failures, 0 exceptions
408 tests, 408 passed, 0 warnings, 0 failures, 0 exceptions
120 tests, 120 passed, 0 warnings, 0 failures, 0 exceptions
FAIL - - main - `environments/panda-cyber-appsec-lab.json` infrastructure-support value is not a valid email address
1200 tests, 1199 passed, 0 warnings, 1 failure, 0 exceptions
❯ …
```
=> Add test to validate email address in json files

.github/ISSUE_TEMPLATE/new-story-template.yml
The new user story template could do with a bit of polish.
We very, very rarely use the `Assumptions/Hypothesis/Questions/Unknowns` section. Any information that could be placed here could just as easily be placed in the `Additional Information` section.
Also removed elipses from the user story placeholder because these are irritating to delete every time you raise a story.
It has not been tested
No
I'll check the template works once it's in `main` and revert this PR if the template is broken.
=> 🧹 Tidy up the new story template

.github/workflows/opa-policies.yml, policies/collaborators/collaborators_test.rego, policies/networking/core-vpc_test.rego, scripts/tests/validate/run-opa-tests.sh
conftest verify is not run on the workflow, so new OPA tests can be added or old ones amended without they themselves being tested.
This runs the conftest verify command to make sure the rego tests are themselves tested before running.
Also improved the output so that it is more readable.
Tested locally
No impact
=> Add conftest verify

source/index.html.md.erb, source/runbooks/accessing-the-observability-platform.html.md.erb, source/user-guide/workflow-status.html.md.erb
https://github.com/ministryofjustice/modernisation-platform/issues/7224
I'm adding a link to the new Workflow Status dashboard on the Observability Platform to our current status page for workflows.
=> Add runbook for accessing OP & link to workflow dashboard

.github/workflows/bootstrap-sprinkler.yml, .github/workflows/core-logging-deployment.yml, .github/workflows/core-network-services-deployment.yml, .github/workflows/core-security-deployment.yml, .github/workflows/core-shared-services-deployment.yml, .github/workflows/core-vpc-development-deployment.yml, .github/workflows/core-vpc-preproduction-deployment.yml, .github/workflows/core-vpc-production-deployment.yml, .github/workflows/core-vpc-test-deployment.yml, .github/workflows/modernisation-platform-account.yml, .github/workflows/new-environment.yml, .github/workflows/scheduled-baseline.yml, .github/workflows/terraform-github.yml, .github/workflows/terraform-pagerduty.yml, .github/workflows/terraform-single-sign-on.yml
No existing issue. The current github workflows for terraform deployment are triggered on changes within the terraform directories. This includes changes exclusively to `README.md` files, which won't affect the deployment, and shouldn't trigger the workflow.
This PR adds a `- '!**.md'` condition to the `paths` argument for the triggering actions (see [including and excluding paths syntax](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths)). This means that changes to markdown files ending in `.md` (i.e. not `html.md.erb` files) will not trigger these deploy workflows. …
=> ignore markdown files (e.g. README.md) for terraform deployment workflows

terraform/modules/app-ecr-repo/main.tf
Refactor the IAM policy document for the ECR repository in the `main.tf` file. The policy document now dynamically generates the statements for allowing push and pull actions based on the `push_principals` and `pull_principals` variables.
=> fix: Refactor ECR repository IAM policy document

terraform/environments/bootstrap/member-bootstrap/iam.tf
Requested in the ask channel. 
**elasticloadbalancing:SetRulePriorities** - allows pipeline to tweak load balancer permissions - this allows us to put up a user-friendly message if an environment has been taken down out of hours
**ssm:SendCommand**-  allows us to run commands on EC2 instances, e.g. stop services cleanly for example
=> adds elb:SetRulePriorities and ssm:SendCommand to the cicd role

terraform/modernisation-platform-account/s3.tf
This PR introduces a new S3 bucket to store CSV files that contain cost data for each AWS member account. #3683 
Creates an S3 bucket named `mp-cost-explorer-reports` for storing cost-related CSV files.
No
=> create S3 bucket for storing AWS member account cost CSV files

.github/ISSUE_TEMPLATE/new-environment.yml, source/index.html.md.erb, source/runbooks/removing-a-team-member.html.md.erb, source/user-guide/adding-vpc-endpoints.html.md.erb, source/user-guide/environments-networks-json-explained.html.md.erb
#5017 
Adds guidance on the creation of VPC Endpoints for MP users
Asked someone in the team to review the guidance
=> Add guidance for users on creating VPC endpoints

terraform/environments/bootstrap/member-bootstrap/notifications.tf
#7265 
Integrates with recent updates made to the baseline module: https://github.com/ministryofjustice/modernisation-platform-terraform-baselines/pull/495
Only applying the changes to the existing topic first.
Tested in cooker. 
=> Creating the backup failure topic only in production and London region

terraform/environments/bootstrap/secure-baselines/main.tf
Releasing changes to aws backup vault and backup notifications. 
https://github.com/ministryofjustice/modernisation-platform-terraform-baselines/releases/tag/v7.4.1
Created backup vault lock for production accounts.
Changed SNS topics and notifications to only build in eu-west-2 for backup failures (only region we use for it)
Created notifications for backup vault meddling
Created variable for non prod backup retention, with a default value (will not impact users unless called)
Deployed to cooker and long term storage accounts
=> Baselines Update

terraform/environments/core-logging/firehose.tf
https://github.com/ministryofjustice/modernisation-platform/issues/7424
I've updated the dynamic variable assignment for the xsiam endpoint/secret in core-logging as it was always evaluating to the false condition and providing the preprod values for prod.
Local TF plan looks promising:
```
~ resource "aws_kinesis_firehose_delivery_stream" "delivery_stream" {
id             = "arn:aws:firehose:eu-west-2:624384546187:deliverystream/liv-log-delivery-stream-qex2oiu0"
name           = "liv-log-delivery-stream-qex2oiu0"
tags           = {
"Name"          = "liv-log-delivery-stream-qex2oiu0"
"application"   = "Modernisation Platform: core-logging-production"
"business-unit" = "Platforms"
"is-production" = "true"
"owner"         = "Modernisation …
```
=> Update dynamic variable for xsiam endpoint/secret in core-logging

terraform/environments/core-security/firehose.tf, terraform/environments/core-shared-services/firehose.tf
Fixes a bug whereby the condition test was not picking up the correct element of vpc_logs and so was defaulting to nonprod.
https://github.com/ministryofjustice/modernisation-platform/issues/7424
The element used for test was incomplete and so resolving to the values for preprod.
PR tests show correct plan. Change has already been applied to core-logging and this repeats that approach.
No impact on other services.
=> Fixes issue whereby wrong xsiam endpoint & secret were used for core-security & core-shared-services.

terraform/environments/bootstrap/member-bootstrap/notifications.tf
#7265 
Integrates with recent updates made to the baseline module: https://github.com/ministryofjustice/modernisation-platform-terraform-baselines/pull/495
This PR adds CloudWatch Log Metric Filter and Metric Alarm to monitor changes to backup vault configurations. The alarm triggers and sends notifications via an SNS topic when specific API calls related to the backup vault are detected. 
In cooker. 
=> monitoring for backup vault lock changes

terraform/modernisation-platform-account/secrets.tf
Requested here - https://moj.enterprise.slack.com/archives/C013RM6MFFW/p1720178339019439
Copies a key to another region as a replica. Will repeat for all keys if it works.
Plan looks good.
N/A
=> Added KMS key replication to eu-west-1

.github/workflows/core-vpc-development-deployment.yml, .github/workflows/core-vpc-preproduction-deployment.yml, .github/workflows/core-vpc-production-deployment.yml, .github/workflows/core-vpc-test-deployment.yml
Update core vpc workflows to use reusable pipeline
The creation of a reusable workflow resolves the problem of having multiple, redundant workflows for similar tasks. One reusable workflow can be called by various pipelines, eliminating the need to duplicate workflow logic across different projects.
- [ x ] I have performed a self-review of my own code
- [ x ] All checks have passed
- [ x ] Plan and discussed how it should be deployed to PROD (If needed)
=> Update core vpc workflows to use reusable pipeline

.github/workflows/core-vpc-development-deployment.yml, .github/workflows/core-vpc-preproduction-deployment.yml, .github/workflows/core-vpc-production-deployment.yml, .github/workflows/core-vpc-test-deployment.yml
This PR adds the `AWS_REGION` environment variable to the pipeline configuration to prevent failures due to the missing variable.
By including the `AWS_REGION` environment variable, the pipeline will now have access to the required region information, preventing errors that were caused by its absence.
=> Add AWS_REGION Environment Variable

terraform/environments/bootstrap/member-bootstrap/iam.tf
As per Slack request https://mojdt.slack.com/archives/C01A7QK5VM1/p1720426251369899 this PR adds the `kms:encrypt` permissions to the oidc role.
=> Add kms:encrypt permissions to OIDC role

environments/contract-work-administration.json
as per Slack request https://mojdt.slack.com/archives/C01A7QK5VM1/p1720445686062709 this PR excludes `contract-work-administration-development` from the nuke run.
=> exclude nuke for contract-work-administration

source/runbooks/integration-with-protective-monitoring.html.md.erb
https://github.com/ministryofjustice/modernisation-platform/actions/runs/9853367257/job/27203750215
Cleans up a link to an internal page
=> Fix internal link on runbook page

terraform/environments/core-shared-services/ecr_repos.tf
We are looking at creating more generic images to define data engineering jobs utilising tools such as dlt and dbt. We are going to test this both in our shared sandbox account and our development EM environment (using different hosting methods in each). 
Creates the repo and allows the two accounts mentioned above to push to it
n/a
n/a
=> New repo for generic data engineering images

terraform/pagerduty/member-services-integrations.tf
cdpts-chaps needs PagerDuty integration so that devs can be alerted to any loadbalancer issues
this PR adds PagerDuty integration for the #cdpt-chaps slack channel
-
-
=> chaps pagerduty integration

terraform/github/repositories.tf
#7395 
Adds the slack webhook url as a repository secret to the environments repo
=> Add secret value for slack webhook to send failures to

terraform/modernisation-platform-account/secrets.tf
This PR adds secrets for a `Slack webhook URL`, and a `GOV.UK Notify API key`, necessary for integrating with Slack notifications, and sending notifications through GOV.UK Notify. #7402
=> Add secrets for Slack webhook URL, and GOV.UK Notify API key
