ministryofjustice/modernisation-platform

- terraform/global-resources/locals.tf
- terraform/global-resources/s3.tf
This PR:
- Fixes a syntax issue for defining and using local variables
> Fix syntax error with local variables

- architecture-decision-record/0001-record-architecture-decisions.md
- architecture-decision-record/README.md
This PR:
- Creates our first architectural decision, and its corresponding architectural decision record 🎉
> Create and document our first architecture decision

- terraform/global-resources/iam.tf
This PR:
- Adds an output for IAM superadmin passwords, and marks them as sensitive
> Add outputs for sensitive variables

- architecture-decision-record/0001-record-architecture-decisions.md
- architecture-decision-record/README.md
This PR:
- Accepts ADR 0001 - Record Architecture Decisions
- Fixes a link to ADR 0001 in the ADR README.md
> Accepts ADR0001 - Record Architecture Decisions and fixes a link to it

- README.md
This PR:
- Adds a contents section to this repository to explain what different subfolders are
- Adds a section that links to other useful repositories as part of the Modernisation Platform
> Add links to useful repositories and update contents of this repository

- terraform/global-resources/iam.tf
- terraform/global-resources/outputs.tf
- terraform/global-resources/secrets.tf
This PR:
- Configures IAM Federated Access for the Modernisation Platform, and subsequently uses AWS Secrets Manager to store secrets
> Implement IAM Federated Access and Secrets Manager

- README.md
This PR:
- Adds a link to the IAM Federated Access module
> Add link to IAM Federated Access module

- architecture-decision-record/0002-use-iam-federated-access.md
- architecture-decision-record/README.md
This PR:
- Adds a proposed ADR for the use of IAM Federated Access
> Add an ADR for IAM Federated Access

- terraform/global-resources/locals.tf
- terraform/global-resources/s3.tf
This PR allows S3 bucket access for the MOJ root account user `ModernisationPlatformOrganisationManagement`.
> Allow S3 bucket access for the MOJ root account user ModernisationPlatformOrganisationManagement

- terraform/global-resources/providers.tf
Brings the `providers.tf` file up to date with what's generated in the template.
> Bring providers.tf file up to date

- terraform/global-resources/dynamodb.tf
- terraform/global-resources/main.tf
This configures `terraform` state locking via DynamoDB.
> Add DynamoDB state locking for Terraform

- README.md
Updates the README to add links to more modules written by the Modernisation Platform team.
> Add links to more modules

- terraform/github/main.tf
Creates a repository for a Trusted Advisor module.
> Create Trusted Advisor repository

- terraform/github/main.tf
- terraform/github/modules/repository/main.tf
- terraform/github/modules/repository/variables.tf
Sets the homepage URL for the core repo with additional variables in Terraform
> Configure variable for homepage_url for repositories, and set it for the core repo

- terraform/github/main.tf
> Fix spelling mistake

- docs/team.md
- terraform/github/modules/team/main.tf
Adds Don to our GitHub team and our team page.
> Add Don to our GitHub team and team page

- terraform/github/modules/repository/main.tf
- terraform/github/modules/repository/versions.tf
- terraform/github/modules/team/versions.tf
This enables vulnerability alerts for all repositories and adds provider definitions to the submodules.
> Enable vulnerability alerts & include providers

- terraform/github/main.tf
- terraform/github/modules/team/main.tf
Adds a CI user to our GitHub team
> Add modernisation-platform-ci user

- terraform/modernisation-platform-account/s3.tf
> Move S3 bucket state into module

- docs/team.md
- terraform/github/modules/team/main.tf
Adds Phil to our GitHub team and page.
> Add Phil Horrocks

- architecture-decision-record/0004-use-bash-node-python-as-core-languages.md
- architecture-decision-record/README.md
Adds ADR for using preferred languages, resolves #67.
> ADR: Use preferred languages

- environments/remote-supervision.json
Create two environments for the Remote Supervision stream recording application
> Add Remote Supervision team environments

- architecture-decision-record/0005-use-github-actions.md
- architecture-decision-record/README.md
ADR for using GitHub Actions as our CI/CD runner, resolves #12
> ADR for using GitHub Actions as our CI/CD runner

- .github/workflows/create-accounts.yml
- scripts/create-accounts.sh
Fixes an issue where Terraform requires reinitialisation before calling terraform workspace list.
> Add missing Terraform init

- scripts/create-per-account-local-workspaces.sh
- terraform/environments/bichard7/backend.tf
- terraform/environments/bichard7/secrets.tf
- terraform/environments/bootstrap/main.tf
- terraform/environments/core/backend.tf
- terraform/environments/core/secrets.tf
- terraform/environments/remote-supervision/backend.tf
- terraform/environments/remote-supervision/secrets.tf
- terraform/environments/shared-services/backend.tf
- terraform/environments/shared-services/secrets.tf
- terraform/templates/backend.tf
- terraform/templates/secrets.tf
This creates directories and the base Terraform configuration for all applications individually, with workspaces for each environment stored in S3, with some sample data output.
> Implement local and remote workspace creation for applications

- terraform/github/main.tf
Brings the "hello-world" repository into Terraform management.
> Add the "hello-world" repository to Terraform

- docs/index.md
- docs/team/alliance.md
- docs/team/index.md
- docs/team/team.md
Cleans up the directory structure for documentation.
> Cleanup doc structure

- docs/user-guide/cloud-platform-or-modernisation-platform.md
- docs/user-guide/index.md
Adds some placeholders for docs we need to produce and adds a Cloud Platform or Modernisation Platform doc.
> Add Cloud Platform or Modernisation Platform doc

- docs/user-guide/index.md
- docs/user-guide/our-offer-to-you.md
This is a replication of the Modernisation Platform service offering document in Google Drive, but public, so we can direct people here if required.
> Add "Our offer to you" to the user guide

- docs/user-guide/our-offer-to-you.md
Broadens the scope by removing the extreme specificity of an example thing we wouldn't support as mentioned by @SteveMarshall in the previous PR.
> Clarification of application support item: remove solutions

- docs/team/team.md
I clearly can't do maths - there's 5 team members 👍🏼
> Correct team count

- environments/justice-on-the-web.json
Adds a Justice on the Web sandbox environment
> Add JoTW sandbox environment

- .github/workflows/create-accounts.yml
- terraform/environments/.terraform.lock.hcl
Updates Terraform to 0.14.1 for environment creation.
> Update environment creation to Terraform 0.14.1

- docs/index.md
- docs/team/index.md
- docs/team/roadmap.md
> Add roadmap

- terraform/environments/core-shared-services/vpc.tf
- created vpc code for shared services account
> vpc code added to shared-services account

- terraform/environments/core-vpc/subnet-sets/hmpps-production.json
- terraform/environments/core-vpc/vpc.tf
- terraform/modules/member-vpc/outputs.tf
- terraform/modules/vpc-nacls/main.tf
- terraform/modules/vpc-nacls/variables.tf
- refactor vpc_nacl module to tidy up locals
- refactor member-vpc module to tidy up outputs
- add from_port and to_port functionality to nacl module
this change is required to add port information to the nacl module
> feature-update-nacl-module

- terraform/environments/core-shared-services/transit-gateway-attachment.tf
- terraform/environments/core-shared-services/vpc.tf
- terraform/modules/core-vpc/main.tf
- terraform/modules/core-vpc/outputs.tf
- terraform/modules/core-vpc/variables.tf
- include dynamic subnet CIDR creation
- include subnet type nacl defaults
- update shared services to reference module correctly
this change brings core-vpc and member-vpc modules more inline with each
other
> update core-vpc module

- terraform/modules/member-vpc/main.tf
- update port handling to rectify current code
This change is required to ensure that default nacl ports are handled
correctly
> correct nacl port handling on core-vpc module

- docs/team/team.md
Welcome to the team @seanprivett 👍🏼
> Add Sean Privett to the team member pages

- source/user-guide/creating-environments.html.md.erb
- source/user-guide/index.html.md.erb
- source/user-guide/our-offer-to-you.html.md.erb
This fixes the user guide documentation pages into proper code blocks rather than one-liners.
> Fix user guide formatting

- terraform/environments/core-vpc/subnet-sets/laa-production.json
- terraform/modules/member-vpc/main.tf
- now includes S3 Gateway endpoint
> updated endpoints in member-vpc module

- terraform/environments/core-vpc/vpc.tf
- terraform/modules/member-vpc/main.tf
Update security groups in members-vpc module, this allows high port number traffic from protected subnets.
> Update security groups in members-vpc module

- README.md
> Update link to site source

- architecture-decision-record/0005-use-github-actions.md
- architecture-decision-record/0006-use-a-multi-account-strategy-for-applications.md
- architecture-decision-record/README.md
Adds an ADR with a link to our environment concept for using multiple AWS accounts.
> Add ADR for our multi-account strategy

- scripts/provision-terraform-workspaces.sh
This fixes a few syntax issues in provision-terraform-workspaces.sh. It now:
- checks for `tmp/` before trying to delete it
- uses `sed` with multiple replacements and `sort -u -o` to output into a file, rather than piping `cat` into `grep`, `tr`, `tee`
- replaces the incorrect syntax for comparators in bash from `==` to `=`
- quotes the main $1 argument to stop whitespace breaking it
- uses `-z` for the null value comparator to check if `$1` is set
- reorders the `find` arguments as `mindepth` and `maxdepth` are not positional, which suppresses this warning:
```bash
find: warning: you have specified the -mindepth option after a non-option argument -type, but options are not positional (-mindepth affects tests specified before it as well as those specified after it).  Please specify …
```
> Fix syntax issues with provision-terraform-workspaces.sh

- source/team/joining-the-team.html.md.erb
This PR adds some information about joining the team and what to expect during the first sprint ceremonies (i.e. updating the team alliance, meeting the team).
> Joining the team: add 'your first sprint ceremonies'

- source/team/team.html.md.erb
- terraform/github/modules/team/main.tf
Adds @jackstockley89 to our GitHub team and our [team page](https://ministryofjustice.github.io/modernisation-platform/team/team.html#our-team).
> Add Jack Stockley to the team

- terraform/environments/analytical-platform-management/backend.tf
- terraform/environments/analytical-platform-management/locals.tf
- terraform/environments/analytical-platform-management/providers.tf
- terraform/environments/analytical-platform-management/secrets.tf
- terraform/environments/analytical-platform-management/versions.tf
Adds the environments subdirectory for Analytical Platform Management environments.
> Add Analytical Platform Management environment files

- terraform/environments/core-shared-services/transit-gateway-attachment.tf
- terraform/environments/core-shared-services/vpc.tf
This PR brings core-shared-services up to date with new features and fixes implemented in #277.
> Update core-shared-services to retag TGW attachments in the TGW host & tenant

- terraform/environments/core-logging/.terraform.lock.hcl
- terraform/environments/core-logging/iam.tf
- terraform/environments/core-logging/locals.tf
- terraform/environments/core-logging/networking.auto.tfvars.json
- terraform/environments/core-logging/providers.tf
- terraform/environments/core-logging/transit-gateway-attachment.tf
- terraform/environments/core-logging/versions.tf
- terraform/environments/core-logging/vpc.tf
- terraform/environments/core-security/.terraform.lock.hcl
- terraform/environments/core-security/iam.tf
- terraform/environments/core-security/locals.tf
- terraform/environments/core-security/networking.auto.tfvars.json
- terraform/environments/core-security/providers.tf
- terraform/environments/core-security/transit-gateway-attachment.tf
- terraform/environments/core-security/vpc.tf
This PR adds core-vpc-tgw-routes module, core-network-services provider and tags to Core Logging and Core Security accounts.
> This PR adds core-vpc-tgw-routes module, core-network-services provider and tags to Core Logging and Core Security accounts.

- terraform/environments/core-vpc/vpc.tf
- terraform/modules/core-vpc/main.tf
- terraform/modules/ec2-tgw-attachment/main.tf
- terraform/modules/member-vpc/main.tf
Fix member-vpc main.tf file and add core-vpc-tgw-routes to core-vpc VPC file.
> Fix member-vpc main.tf file and add core-vpc-tgw-routes to core-vpc VPC file.

- terraform/modules/bastion_linux/versions.tf
- terraform/modules/core-vpc-tgw-routes/versions.tf
- terraform/modules/core-vpc/versions.tf
- terraform/modules/ec2-tgw-attachment/versions.tf
- terraform/modules/member-vpc/versions.tf
- terraform/modules/ram-ec2-retagging/versions.tf
- terraform/modules/ram-principal-association/versions.tf
- terraform/modules/ram-resource-share/versions.tf
This PR adds:
- minimum version dependencies for required providers in local modules
> Add versions.tf to local modules

- .github/workflows/validate-core-vpc-configuration.yml
- scripts/tests/validate/fixtures/pre-terraform-core-vpc-validation.json
- scripts/tests/validate/validate-core-vpc-configuration.sh
- json validation file created
- created script to check core-vpc json files against
validation json file
- github actions job created to trigger on PR for specific json file
changes
> Add validation testing for core-vpc json files

- terraform/environments/.terraform.lock.hcl
- terraform/environments/environments.tf
> Pin terraform-module-environments to v1.0.0

- .github/workflows/core-network-services-deployment.yml
- scripts/update-pr-comments.sh
- move grep that retrieves Terraform summary line back to calling script
- add error handling to curl statement to ensure the pipeline fails on an error
> fix core network services automation

- .github/workflows/core-logging-deployment.yml
- .github/workflows/core-security-deployment.yml
- .github/workflows/core-shared-services-deployment.yml
- update core-network-services to ignore plan steps when applying
- create code for code-logging
- create code for code-security
- create code for code-shared-services
these changes are required to automate the deployment of networking to
core services
> apply core networking automation

- source/concepts/environments/security.html.md.erb
- source/user-guide/our-offer-to-you.html.md.erb
Adds documentation around what service users get in new environments as part of the Modernisation Platform.
> Add documentation around the security of new environments

- source/team/team.html.md.erb
Welcome @davidkelliott and @ezman 👍🏼
> Add David Elliott and Fasih Rehman to our team page

- terraform/README.md
- terraform/environments/README.md
- terraform/modules/README.md
- terraform/templates/README.md
This PR adds some documentation around ./modules and ./templates, and updates the ./environments README.
> Add READMEs for ./modules and ./templates, and update the ./environments README

- .github/ISSUE_TEMPLATE/bug-template.md
- .github/ISSUE_TEMPLATE/story-template.md
- .gitignore
Basic issue templates, these should probably be discussed further at
some point and refined, especially when we start expecting end users to
be using them.
> Add issue templates

- source/team/roadmap.html.md.erb
This PR removes the old roadmap and links to the ProductPlan roadmap instead.
> Update roadmap link

- .github/workflows/check-links.yml
- .github/workflows/publish.yml
- makefile
This PR updates tech-docs-github-pages-publisher to 1.3.
> Update tech-docs-github-pages-publisher to 1.3

- terraform/modernisation-platform-account/iam.tf
> Update iam-superadmins module version

- terraform/modules/dns-zone/main.tf
> update fix to DNS internal zone

- terraform/environments/core-network-services/acm-pca.tf
- terraform/modules/ram-ec2-retagging/main.tf
- terraform/modules/ram-principal-association/main.tf
- terraform/modules/ram-principal-association/variables.tf
- terraform/templates/locals.tf
- terraform/templates/providers.tf
- terraform/templates/subnet_share.tf
changes:
- ACM S3 bucket destroy set to false
- RAM share data source call fixed
- templates for RAM setup of member accounts
> added RAM share fix and member VPC templates

- terraform/environments/core-vpc/.terraform.lock.hcl
- terraform/environments/core-vpc/vpc.tf
- terraform/modules/dns-zone/main.tf
- terraform/modules/dns-zone/variables.tf
- terraform/modules/vpc-tgw-routing/main.tf
- terraform/modules/vpc-tgw-routing/variables.tf
- terraform/templates/providers.tf
- Update Terraform modules to move data lookups from module to the
calling Terraform code. This stops unchanged items being updated.
> correct-terraform-data-lookup-issue

- source/user-guide/creating-networking.html.md.erb
- source/user-guide/index.html.md.erb
User guidance explaining the networking features
> Add networking user guide

- terraform/environments/sprinkler/.terraform.lock.hcl
- terraform/environments/sprinkler/bastion_linux.json
- terraform/environments/sprinkler/bastion_linux.tf
- terraform/environments/sprinkler/main.tf
- terraform/modules/bastion_linux/README.md
- terraform/modules/bastion_linux/main.tf
- terraform/modules/bastion_linux/user_data.sh
- terraform/modules/bastion_linux/variables.tf
- terraform/modules/member-vpc/main.tf
- various updates to Bastion module
- added a README.md to the module
- updated Sprinkler test app to use updated bastion module
- includes an update to member-vpc module, this changes Security Groups to be singular for an endpoint
> Various updates to Bastion Linux module

- terraform/github/locals.tf
> Add Christine to the github team

- terraform/github/main.tf
We want to separate out user environments from core infrastructure.  We
will put user environment code in this repo.
> Add environments repo

- terraform/github/main.tf
Forgot to do this in the last PR
> Add the team to the environments repo

- scripts/provision-environment-directories.sh
- scripts/provision-member-directories.sh
Change the state file locations to sit under logical subfolders for
neatness.
> Change state file locations

- terraform/environments/analytical-platform-management/backend.tf
- terraform/environments/bench/backend.tf
- terraform/environments/bench/main.tf
- terraform/environments/bichard7/backend.tf
- terraform/environments/bootstrap/delegate-access/backend.tf
- terraform/environments/bootstrap/secure-baselines/backend.tf
- terraform/environments/bootstrap/single-sign-on/backend.tf
- terraform/environments/cooker/backend.tf
- terraform/environments/cooker/main.tf
- terraform/environments/core-logging/backend.tf
- terraform/environments/core-network-services/backend.tf
- terraform/environments/core-sandbox/backend.tf
- terraform/environments/core-security/backend.tf
- terraform/environments/core-shared-services/backend.tf
- terraform/environments/core-vpc/backend.tf
- terraform/environments/heater/backend.tf
- terraform/environments/heater/main.tf
- terraform/environments/justice-on-the-web/backend.tf
- terraform/environments/remote-supervision/backend.tf
- terraform/environments/sprinkler/backend.tf
- terraform/environments/sprinkler/main.tf
Also amend data references to new location where present.
> Point backends to new state file location

- .github/workflows/new-member-environment-files.yml
- scripts/git-commit.sh
- scripts/git-pull-request.sh
- scripts/git-setup.sh
- scripts/provision-member-directories.sh
Adding script to create pull request to new repo
> Adding new pull request

- .github/ISSUE_TEMPLATE/new-environment.md
New environment issue template, so that users can easily add all the
information we need to create a new environment for them.
> Add new environment issue template

- terraform/environments/bench/main.tf
- terraform/environments/cooker/main.tf
- terraform/environments/heater/main.tf
- terraform/environments/sprinkler/bastion_linux.tf
- terraform/environments/sprinkler/main.tf
Comment out lab environment on core for the following applications
- bench
- cooker
- heater
- sprinkler
Applications will be recreated in modernisation-platform-environments repositiory
> comment-out-lab-env-on-core

- source/index.html.md.erb
- source/user-guide/creating-environments.html.md.erb
- source/user-guide/creating-networking.html.md.erb
- source/user-guide/creating-resources.html.md.erb
Now that we have 2 repos we are updating accordingly.
> Update user guidance to reflect repo changes

- terraform/github/locals.tf
Reverts ministryofjustice/modernisation-platform#562
Christine is now part of the MoJ organisation so adding her back in.
> Revert "Revert "Add Christine to the github team""

- source/concepts/environments/problem-and-solution.html.md.erb
- source/index.html.md.erb
A bit more tidying to get the documentation in a good place before
starting to fill out the place holder topics.
> Rejig concepts and add placeholder topics

- .github/workflows/new-environment.yml
- terraform/environments/README.md
when the terraform/environment root directory files have been changed.
> Amend new-environment.yml file to output plan to PR

- .github/workflows/format-code.yml
- .github/workflows/new-environment.yml
- .github/workflows/opa-policies.yml
- .github/workflows/terraform-github.yml
- terraform/github/modules/repository/main.tf
If terraform or OPA fails then manual merging of a PR is prevented.
Resolves #395
> Github merge prevented on test or plan failures.

- terraform/modules/ram-resource-share/main.tf
Reverts ministryofjustice/modernisation-platform#658
> Revert "added adepend_on to the aws ram resource block"

- .github/labeler.yml
> Add some more labelling

- .github/workflows/core-vpc-development-deployment.yml
- .github/workflows/core-vpc-preproduction-deployment.yml
- .github/workflows/core-vpc-production-deployment.yml
- .github/workflows/core-vpc-test-deployment.yml
- scripts/terraform-apply.sh
- scripts/terraform-plan.sh
In some cases we want to be able to add options to the terraform command
that we run.
> Add options to tf scripts

- .github/workflows/publish.yml
You can't have both paths and ignore paths
> Remove ignore paths

- scripts/tests/validate/run-opa-tests.sh
For some reason the TERM value isn't set, so the colours aren't showing.
> Add TERM value

- source/concepts/environments/architecture.html.md.erb
- source/concepts/environments/security.html.md.erb
- source/team-guide/terraform.html.md.erb
- source/team-guide/useful-scripts.html.md.erb
Most pages were fine, some new scripts added to the scripts page.
> Review pages and bring up-to-date

- environments-networks/hmpps-preproduction.json
- environments-networks/template-only.txt
- terraform/environments/core-vpc/vpc.tf
- terraform/modules/member-vpc/main.tf
- terraform/modules/member-vpc/variables.tf
- additional functionality for extra endpoints per vpc via environments-networks
json files
- removed data lookups in modules that returned known names
- added elasticfilesystem endpoint to hmpps as this will be required for
performance hub
- added examples to template-only.txt file
closes #720
> refactor-endpoint-creation

- terraform/github/aws.tf
- terraform/github/main.tf
Adding the new user and secrets to the env repo.
> Add member ci user to environments repo

- scripts/provision-member-directories.sh
We want to prevent other teams from amending directories which are not
their application. This creates the automation to do this with code
owners.  Note that the github teams are assigned per environment, and
the code is stored per application (which then uses workspaces to change
environment). This means there may be multiple teams per applicaion.
Here we are giving any team with access to an environment, the access to approve the code.
Resolves #747 
The code owners file generated should look like this:
```
* @modernisation-platform
/terraform/environments/bichard7 @cjse-bichard7-next @modernisation-platform
/terraform/environments/heater @modernisation-platform @modernisation-platform
/terraform/environments/ops-engineering @operations-engineering @modernisation-platform …
```
> Generate environments repo codeowners file

- terraform/templates/member-providers.tf
We need a provider for network services to allow DNS validation records
to be created and destroyed.
> Add network-services provider

- terraform/github/locals.tf
Added github ID stevelinden to the list of engineers so I can access modernisation platform.
> Added Steve Linden to engineers

- environments/bench.json
- environments/heater.json
- environments/sprinkler.json
In order to generate github environments we need to have a team that
will review deployments.  Doing this allows us to use workflow and
github environments for the test envs.
> Add github slug for the test environments

- terraform/modernisation-platform-account/iam.tf
- terraform/modernisation-platform-account/locals.tf
- terraform/modernisation-platform-account/secrets.tf
Further restrictions to increase security around the member ci user.
Closes #760
> Restrict the roles that the member ci user can use

- terraform/templates/member-providers.tf
Updating the member provider template to use the new member role for core-vpc
> Update template to use new role

- environments/analytical-platform-management.json
- environments/bichard7.json
- environments/justice-on-the-web.json
- environments/remote-supervision.json
Change account type for several accounts in environments JSON files
This change is required to enable these accounts to join the correct AWS Organisations OUs
> change-account-type-for-several-accounts

- terraform/environments/locals.tf
- terraform/environments/scp_mp_core.tf
- terraform/environments/scp_mp_member.tf
- terraform/environments/scp_mp_member_unrestriced.tf
- three separate SCP policies have been created
- SCP policies have been applied to core, member & member-unrestricted
OUs under the Modernisation-Platform OU
A framework was required to ensure that accounts can be correctly managed
by relevant SCPs.
> scp-configuration-added-to-modernisation-platform-OUs

- architecture-decision-record/0009-use-secrets-manager-for-secrets.md
- architecture-decision-record/README.md
> Add ADR for using Secrets Manager

- source/concepts/sdlc/core-workflow.html.md.erb
Starting out by listing them all out and explaining what they do. May go
into more detail at a later date.
> New documentation explaining what our workflows do

- terraform/modules/iam_baseline/main.tf
Change to add an extra permission.
> Added ecs:DescribeTaskDefinition to permission set.

- scripts/git-create-environments.sh
Resolves #874, when the environments json file is changed then the
github environment will be updated to the current json file settings.
> Allow github slugs in environments to be updated

- terraform/environments/bootstrap/delegate-access/iam.tf
- terraform/modules/iam_baseline/versions.tf
> Upgrade delegate access to TF 1.0.1

- source/index.html.md.erb
- source/team-guide/changing-environment-details.html.md.erb
This documents what would happen if you changed certain things in the
environment json files.
> Add page explaining changes in the env files

- .github/workflows/templates/workflow-template.yml
The workflow dispatch trigger wasn't working against main branch for dev
and test, sometimes we may want to run main back into an environment.
> Fix manual trigger not working for dev/test

- environments/testing.json
- policies/environments/expected.rego
Adding new json file to create the new test account for Terratest
> Create Testing Account

- cidr-allocation.md
- environments-networks/platforms-test.json
- policies/networking/expected.rego
allocating subnet sets to testing member account
> Adding Network Rule

- scripts/provision-terraform-workspaces.sh
Fixes 920
This is because the script is creating the temporary files for the main repo, running init and creating the workspace, then changing the backend and running init and create again for the environments repo. Because init has been run once before it now thinks there is a change in the backend. We need to clear the temp folders and start from scratch again for the environments repo.
The reason it works on the 2nd time of running the workflow is because it doesn't create the first workspace and then switch.
This fix puts all the file creation code into a new function, and calls
that function before it is needed. If any thing already exists it is
deleted in the function before recreating the files.
> Fix environments repo workspace creation failing

- terraform/environments/bootstrap/secure-baselines/main.tf
> Update baselines module to latest version

- scripts/provision-member-directories.sh
> Fix environments repo url not substituted

- .github/workflows/modernisation-platform-account.yml
- terraform/modernisation-platform-account/iam.tf
New process added to the .github/workflows to allow terraform to auto-run on changes to the modernisation-platform-account.
Additional file called modernisation-platform-account.yml created and pointed at the modernisation-platform-account locations.
> Terraform auto run modernisation-platform-account

- terraform/modernisation-platform-account/s3.tf
Update Modernisation Platform state files bucket to V3.0.0 of
S3 bucket module.
- Remove bucket replication
> upgrade-mod-platform-s3-state-bucket-to-v3.0.0

- terraform/templates/application_variables.json
- terraform/templates/locals.tf
Plus give relevant local and usage in comments
> Add app variables to template file

- .github/workflows/modernisation-platform-account.yml
- terraform/modernisation-platform-account/iam.tf
> Bump superadmins module version

- source/team/team.html.md.erb
- terraform/github/locals.tf
Adrian needs to be removed while we wait for a Github licence to be 
allocated to him
> Add Seb Norris to GitHub team and temporarily remove Adrian

- source/team/team.html.md.erb
- terraform/github/locals.tf
Adding Adrian as an engineer on the github team
> Adding adrian to github team

- environments/analytical-platform-data.json
- policies/environments/expected.rego
> Add new account for analytical platform.

- terraform/modules/member-vpc/main.tf
- terraform/modules/vpc-hub/main.tf
Temporary exclusion while logging solution is being updated
This is a replacement for changes proposed in https://github.com/ministryofjustice/modernisation-platform/pull/1017
> Suppress KMS Encryption checks

- environments/nomis.json
Bump Nomis team access to admin
> Bump Nomis team access to admin

- environments-networks/cica-development.json
Reverts ministryofjustice/modernisation-platform#1075
> Revert "Trigger a redeploy by changing bastion_linux to false which does not …"

- scripts/member-account-ram-association.sh
> Set -e to ensure script doesn't fail silently

- .github/workflows/documentation.yml
- terraform/modules/core-vpc-tgw-routes/README.md
- terraform/modules/dns-zone-extend/README.md
- terraform/modules/dns-zone/README.md
- terraform/modules/ec2-tgw-attachment/README.md
- terraform/modules/iam_baseline/README.md
- terraform/modules/member-vpc/README.md
- terraform/modules/ram-ec2-retagging/README.md
- terraform/modules/ram-principal-association/README.md
- terraform/modules/ram-resource-share/README.md
- terraform/modules/vpc-hub/README.md
- terraform/modules/vpc-nacls/README.md
- terraform/modules/vpc-tgw-routing/README.md
And add READMEs to modules that did not have them
> Add workflow to automate module documentation

- environments/performance-hub.json
> Adding performance hub production account.

- terraform/environments/core-shared-services/base_variables.tf
- terraform/environments/core-shared-services/ecr_repos.tf
- terraform/modules/app-ecr-repo/main.tf
- terraform/modules/app-ecr-repo/outputs.tf
- terraform/modules/app-ecr-repo/variables.tf
- terraform/modules/app-ecr-repo/versions.tf
Added new internal ecr repo module for shared services.
First implementation for performance-hub.
TODO: Account lookup is failing. Using defaults for now.
> Added new internal ecr repo module for shared services.

- architecture-decision-record/0009-use-secrets-manager-for-secrets.md
- architecture-decision-record/0010-terraform-module-strategy.md
- architecture-decision-record/0011-use-vpc-flow-logs-to-gain-insight-into-network-state.md
- architecture-decision-record/0012-use-tgw-route-analyzer-to-check-desired-state-for-route-tables.md
- architecture-decision-record/0013-use-iac-network-tester-to-test-connectivity-rules.md
- architecture-decision-record/README.md
Capturing decisions from network testing spikes as ADRs, with stated reasons for rejection.
> Add ADRs relating to outcomes of network testing spikes

- environments/bichard7.json
- scripts/internal/find-terraform-workspace.sh
- source/team-guide/deleting-an-environment.html.md.erb
Also make some updates to the user guidance and the find workspaces
script.
> Remove bichard7-dev-next environment

- terraform/modules/vpc-hub/main.tf
- terraform/modules/vpc-hub/variables.tf
- there is a fix in place where using a separate terraform
module to create the tgw routes is needed
> remove-circular-reference-from-terraform-module

- .github/ISSUE_TEMPLATE/bug-template.md
- .github/ISSUE_TEMPLATE/new-environment.md
Adding more detail to help us decide the best configuration for the
application.
> Update new environment issues template

- .github/workflows/terraform-static-analysis.yml
This reverts commit 09f60e6f47aa893b01f5a43ab14fe7527342e8e5.
> Revert "test schedule"

- architecture-decision-record/0014-create-ecr-in-the-shared-services-account.md
- architecture-decision-record/0015-use-aws-image-builder-for-managing-amis.md
ADR to capture Image Builder usage.
> Add ADR for image builder usage

- .github/workflows/terraform-static-analysis.yml
https://github.com/ministryofjustice/modernisation-platform/issues/1165
> tfsec_exclude: github-repositories-require-signed-commits

- terraform/environments/bootstrap/delegate-access/iam.tf
To allow WAF resource creation and route53 resolver resources
> Add permissions to MemberInfrastructureAccess role

- terraform/environments/core-vpc/vpc.tf
This updates adds permissions to be able to create resolver endpoints for member accounts
> Update Member Delegation role

- README.md
- terraform/github/main.tf
https://github.com/diodonfrost/terraform-aws-lambda-scheduler-stop-start
> New repository to fork lambda-scheduler-stop-start terraform module

- terraform/environments/core-vpc/vpc.tf
This allows creation and deletion of security groups
> Add security group permissions to member delegation role

- source/index.html.md.erb
- source/user-guide/sustainability.html.md.erb
Sustainability is important to us as a team, we want to document the
work that we are doing.
> Add sustainability page

- terraform/modules/member-vpc/main.tf
- remove unused code from member-vpc module
> remove-commented-out-code-from-module

- environments/mi-platform.json
- policies/environments/expected.rego
New unrestricted AWS development account for the mi-platform, as
detailed in #1316.
> Set up new mi-platform unrestricted account

- .github/workflows/terraform-pagerduty.yml
- terraform/github/aws.tf
- terraform/github/main.tf
- terraform/pagerduty/aws.tf
This adds a workflow to automate the deployment of pagerduty terraform.
- workflow
- secret for the token
- update main github repo to add the token as a secret
> Add pagerduty workflow

- environments/dex-ta.json
- policies/environments/expected.rego
Creating new member account for the dex-ta
> feat: Adding new member account dex-ta

- environments-networks/hmpps-development.json
Adding dex-ta to the hmpps dev general subnet set
> feat: Adding dex-ta to subnet set

- terraform/modernisation-platform-account/iam.tf
Updates IAM source module reference to use most recent version
> bump reference for iam source module to v1.0.7

- environments-networks/hmpps-test.json
Just notice this is giving the private subnet where it should be the
data
> Fix wrong subnet type

- terraform/github/locals.tf
Add local value for new github slug, allowing merge of #1419
> added ppud-replacement-devs to application_teams

- terraform/github/locals.tf
Add myself to maintainers
Also removing all non team members.
> Update maintainers for core repos

- terraform/environments/bootstrap/delegate-access/iam.tf
The collaborators code was trying to create things in the AWS root
account, this should be in the mp accounts.
> Fix incorrect provider

- cidr-allocation.md
- environments-networks/hmcts-preproduction.json
- policies/networking/expected.rego
* Updated cidr allocation to account for new vpc
* Created JSON containing details of new vpc
* Updated tests to account for new vpc
> Create HMCTS Preproduction VPC

- source/concepts/environments/problem-and-solution.html.md.erb
- source/concepts/environments/security.html.md.erb
- source/concepts/environments/single-sign-on.html.md.erb
- source/index.html.md.erb
- source/user-guide/accessing-ec2s.html.md.erb
- source/user-guide/accessing-the-aws-console.html.md.erb
- source/user-guide/cloud-platform-or-modernisation-platform.html.md.erb
- source/user-guide/creating-environments.html.md.erb
- source/user-guide/creating-networking.html.md.erb
- source/user-guide/creating-resources.html.md.erb
- source/user-guide/deploying-your-application.html.md.erb
- source/user-guide/deploying-your-infrastructure.html.md.erb
- source/user-guide/environment-diagram.html.md.erb
- source/user-guide/getting-aws-credentials.html.md.erb
- source/user-guide/obtaining-deployment-credentials.html.md.erb
- source/user-guide/our-offer-to-you.html.md.erb
- source/user-guide/running-terraform-plan-locally.html.md.erb
- source/user-guide/sustainability.html.md.erb
- source/user-guide/wider-moj-connectivity.html.md.erb
Add in some missing documentation and review existing docs
> Documentation update

- collaborators.json
* adds json entries with the `security-audit` role for users involved in xhibit portal IT Healthcheck
> added json for ITHC collaborators

- source/concepts/networking/dns.html.md.erb
- source/index.html.md.erb
- source/team-guide/deleting-an-environment.html.md.erb
- source/team-guide/removing-a-team-member.html.md.erb
A few updates and corrections plus a new page as a result of the SSO
sync issue to manually remove old users.
> Doc updates and removing a team member page

- terraform/github/locals.tf
- terraform/modernisation-platform-account/iam.tf
* Updated reference to remote IAM superadmins module
* Removed departing engineer from list of engineers
> Updated superadmins

- terraform/templates/data.tf
- terraform/templates/versions.tf
updated deprecated data calls in templates, updated provider version constraint
> Template updates for provider v4

- terraform/modules/vpc-hub/main.tf
Do not allow private and data subnets in core-network-services account communicating with public internet addresses.
> NACL tightening

- .github/workflows/core-logging-deployment.yml
- .github/workflows/core-network-services-deployment.yml
- .github/workflows/core-security-deployment.yml
- .github/workflows/core-shared-services-deployment.yml
This was preventing the merge from running the apply job
> Add missing path to workflow

- environments/equip.json
- policies/environments/expected.rego
Note, modernisation-platform-team added as this application will be
supported by a 3rd party which will be given access via collaborators.
Closes #1524
> Add Equip dev and production environments

- environments-networks/hmpps-development.json
- environments-networks/hmpps-production.json
- policies/networking/expected.rego
Add equip accounts to the relevant hmpps subnet sets.
Also add missing ppud into rego.
> Add networking for equip

- collaborators.json
John is the technical architect for Roc Technologies who will be
building the Equip application and supporting it going forward.
> Add John Broom as a collaborator

- source/team-guide/removing-a-team-member.html.md.erb
> Add a few extra details to leavers process

- README.md
Add a badge to display if we are meeting MoJ repo standards
https://github.com/ministryofjustice/github-repository-standards
> Add badge to display repo compliance status

- terraform/github/main.tf
The nettest repo was manually created, adding it to code here and
expanding the name to make it clearer what the repo is for.
> Add manually created repo to code

- .github/workflows/add-issues-to-project.yml
Any new issue will now be added directly to our GitHub project, this
saves us from doing this manually.
> Automatically add GitHub issues to our project

- terraform/environments/bootstrap/delegate-access/iam.tf
normal SSO developer permissions.  This includes adding the ability to
view market place subscriptions and take snapshots.
> Update collaborator developer permissions to match

- terraform/environments/bootstrap/delegate-access/iam.tf
Support - raise and resolve cases
KMS permissions - needed for copying and sharing snapshots
> Add additional permissions to allow collaborators

- environments/nomis.json
> New environment for Nomis production

- environments-networks/hmpps-production.json
- environments/nomis.json
- terraform/environments/core-network-services/firewall.tf
Put in production firewall changes for Nomis.
Also added nomis-production to hmpps-production.json where it had been missed.
> Nomis production firewall changes

- environments-networks/hmpps-production.json
Some NACLs were missing following creation of nomis production. This PR is to add those.
> Added NACLs missing from nomis setup, as requested by nomis team

- environments-networks/hmpps-test.json
allow inbound traffic on port 9182 from 172.20.0.0/16, it's for monitoring windows VMs from Cloud Platform
> Nomis-test allow inbound traffic on port 9182

- .gitignore
- terraform/environments/bootstrap/secure-baselines/main.tf
- terraform/modernisation-platform-account/baselines.tf
* Updates references to most recent version of baseline module
> updated references to downstream modules for tfsec fixes

- .github/workflows/core-shared-services-deployment.yml
- terraform/environments/core-shared-services/bucket.tf
Fix to allow this to run the apply job as well after the new environment
workflow runs.
> Shared services workflow wasnt triggering on apply

- environments/example.json
- policies/environments/expected.rego
Setting up account that will be used for example code
> New example account to use for example code

- cidr-allocation.md
- environments-networks/platforms-development.json
- policies/networking/expected.rego
Adding the CIDR for the new example-account
> Adding the CIDR for example-development account

- source/index.html.md.erb
- source/runbooks/dos-attack.html.md.erb
What to do if we recieve an alarm or are made aware of a DDoS attack.
Closes #1561
> Add runbook for dos or ddos attack

- terraform/environments/bootstrap/delegate-access/iam.tf
Just thought, it might be nice to give our core accounts an alias as well.
> Include core accounts

- collaborators.json
Remove Sergio following completion of techdata engagement
> Remove remaining Techdata collaborator

- environments/threat-and-vulnerability-mgmt.json
- policies/environments/expected.rego
> Add Security accounts

- terraform/environments/core-logging/athena.tf
SCA was showing excessive permissions for athena, reducing to the
required permissions.
> Restrict athena permissions

- terraform/environments/core-vpc/vpc.tf
* Update tag reference to `modernisation-platform-terraform-member-vpc-hub` version
> update reference to VPC module tagged version

- collaborators.json
Leanne and Sarah need temporary access to Equip via AWS Fleet Manager. This is to allow them access to internal applications while external access issues are resolved.
> added two MOJ users

- environments-networks/hmpps-production.json
- environments-networks/hmpps-test.json
* Add entry to `hmpps-test.json` to allow SSH traffic in to databases
* Add entry to `hmpps-production.json` to allow SSH traffic in to databases.
* PR relates to #1954
> allow tcp/22 in to nomis data subnets from azure fix'n'go

- terraform/environments/core-logging/transit-gateway-attachment.tf
- terraform/environments/core-security/transit-gateway-attachment.tf
- terraform/environments/core-shared-services/transit-gateway-attachment.tf
* Improves name tags for VPC TGW attachments in services VPCs
> improve naming for services VPC TGW attachments

- terraform/environments/core-network-services/locals.tf
* Removes inspection VPC from active monitoring until such time as traffic is passed back through it
> remove inspection vpc from monitoring

- source/team/team.html.md.erb
- terraform/github/locals.tf
Removed entries for Shakeel from team in line with [Adding a new team member to the Modernisation Platform](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/adding-a-new-team-member.html#adding-a-new-team-member-to-the-modernisation-platform)
> removed Shakeel from team

- environments/apex.json
in order to debug delegate access step issues
> Temporarily giving administrator access to Apex

- terraform/environments/analytical-platform-data/locals.tf
- terraform/environments/apex/locals.tf
- terraform/environments/cooker/locals.tf
- terraform/environments/equip/locals.tf
- terraform/environments/example/locals.tf
- terraform/environments/mi-platform/locals.tf
- terraform/environments/nomis/locals.tf
- terraform/environments/performance-hub/locals.tf
- terraform/environments/ppud/locals.tf
- terraform/environments/sprinkler/locals.tf
- terraform/environments/tariff/locals.tf
- terraform/environments/testing/locals.tf
- terraform/environments/threat-and-vulnerability-mgmt/locals.tf
- terraform/environments/xhibit-portal/locals.tf
- terraform/templates/locals.tf
* Correct spelling of mistyped resource attribute
> fixed typo

- environments/apex.json
- scripts/setup-baseline.sh
by hardcoding directory and workspace
> Hacking the setup-baselines.sh script

- environments/apex.json
- scripts/setup-baseline.sh
Reverts ministryofjustice/modernisation-platform#2074
> Revert "Hacking the setup-baselines.sh script"

- environments/apex.json
- scripts/setup-baseline.sh
- scripts/terraform-init.sh
- scripts/terraform-plan.sh
* Drop apex access level back down to `developer`
* Add `set -x` to bash scripts to evaluate behaviour
> Reduce apex account access

- environments-networks/laa-development.json
- terraform/environments/apex/locals.tf
> Add environments file data call to apex locals file

- terraform/environments/bootstrap/delegate-access/iam.tf
- terraform/environments/core-network-services/iam.tf
- terraform/environments/core-vpc/vpc.tf
* Added ability for github-actions role to assume necessary roles
* Partially completes #2306
> OIDC provider permissions

- terraform/environments/bootstrap/delegate-access/iam.tf
Updates to latest version of `cross-account-access` module
> updated references to cross-account-access module

- terraform/environments/bootstrap/delegate-access/iam.tf
* Updates downstream module reference for cross-account-access
* Supplies a per-environment principal statement where requested
> Add cross-account permissions for delegate-access step

- terraform/environments/core-logging/athena.tf
- terraform/environments/core-logging/s3_logging.tf
- terraform/environments/core-shared-services/bucket.tf
Merging these dependabot updates into one to trigger the workflows together
> Update to latest version of S3 module

- terraform/environments/core-network-services/iam.tf
* Add a statement allowing ARN matching `role:github-actions` to assume role for modify-dns
> Add conditional statement for github-actions

- source/concepts/environments/architecture.html.md.erb
- source/concepts/environments/security.html.md.erb
- source/concepts/environments/single-sign-on.html.md.erb
- source/index.html.md.erb
- source/team/vision.html.md.erb
* Alphabetised runbooks
* Update review dates
> Document review

- collaborators.json
They have been given SSO access
> Remove Data & Insights collaborators

- source/user-guide/accessing-ec2s.html.md.erb
- source/user-guide/cloud-platform-or-modernisation-platform.html.md.erb
- source/user-guide/creating-networking.html.md.erb
- source/user-guide/obtaining-deployment-credentials.html.md.erb
- source/user-guide/wider-moj-connectivity.html.md.erb
* Updates `last_reviewed_on` for documents in need of review
> Review documents

- makefile
- source/user-guide/accessing-ec2s.html.md.erb
- source/user-guide/creating-networking.html.md.erb
- source/user-guide/wider-moj-connectivity.html.md.erb
* Update makefile to use new docs action
* Update review dates
> Update makefile for docs

- environments/digital-prison-reporting.json
- policies/environments/expected.rego
* Creates a development account for Digital Prisons Reporting
> Digital Prisons Reporting account

- environments/refer-monitor.json
- terraform/github/locals.tf
This PR is to allow extra users to access the refer-monitor environment
> Added second github slug for team

- source/index.html.md.erb
Missed including this in the index. Now added
> Add athena description to index

- source/index.html.md.erb
> Incorrect brackets on athena user guide

- architecture-decision-record/0020-how-we-create-and-maintain-documentation.md
- architecture-decision-record/README.md
During a retro we realised not everyone is sure on how we create documentation and the decisions we have made around documentation haven't been recorded anywhere.
> Add ADR on how we document things

- source/team/team.html.md.erb
- terraform/github/locals.tf
Adding Julia and Ewa to the team page.
Adding Julia and Ewa to the GH team.
> Feature/#2260 adding new team members.

- terraform/environments/core-shared-services/ecr_repos.tf
The LAA ops team have requested a shared ECR repo for the MLRA application.
> Add Shared ECR repository for MLRA app

- terraform/environments/bootstrap/delegate-access/iam.tf
This hopefully should resolve this error. 
https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/3088378428/jobs/4994777025
> Adding kinesis, missing permissions. Required by DPR.

- source/user-guide/creating-accounts-for-end-users.html.md.erb
- source/user-guide/creating-vpcs.html.md.erb
Page made, will need to link to it from other page, but can be revised in its current state.
> VPC Creation documentation

- source/runbooks/removing-a-team-member.html.md.erb
- source/user-guide/working-as-a-collaborator.html.md.erb
Updated docs for out of date spaniel warning. Two pages changed.
> Updated docs for out of date spaniel warning. Two pages changed.

- terraform/environments/apex/versions.tf
- terraform/environments/cooker/versions.tf
- terraform/environments/core-logging/versions.tf
- terraform/environments/data-and-insights-wepi/versions.tf
- terraform/environments/delius-iaps/versions.tf
- terraform/environments/digital-prison-reporting/versions.tf
- terraform/environments/equip/versions.tf
- terraform/environments/example/versions.tf
- terraform/environments/mi-platform/versions.tf
- terraform/environments/mlra/versions.tf
- terraform/environments/nomis/versions.tf
- terraform/environments/oasys/versions.tf
- terraform/environments/performance-hub/versions.tf
- terraform/environments/ppud/versions.tf
- terraform/environments/refer-monitor/versions.tf
- terraform/environments/sprinkler/versions.tf
- terraform/environments/tariff/versions.tf
- terraform/environments/testing/versions.tf
- terraform/environments/threat-and-vulnerability-mgmt/versions.tf
- terraform/environments/xhibit-portal/versions.tf
> TFLINT remediation for the terraform/environments directory

- terraform/github/main.tf
This repo will be used by application teams for configuration management.
Initially this will be DSO. The code will grow into reusable libraries (e.g. ansible roles).
> Creating a new repository for the configuration management code

- terraform/github/main.tf
Add a repository for the Go lambda function for stopping and starting instance, rds resources and autoscaling groups
> Add instance scheduler repo

- scripts/provision-member-directories.sh
- terraform/templates/service_runbook_template.md
Minor changes to the provision-member-directories script to copy and rename the template file to README.md when creating a new service. I will go back and manually create the README.md for each of the 17 services currently in the mod platform env repo.
> Service Runbook Template Creation. #1517

- terraform/modernisation-platform-account/iam.tf
Update AWS IAM module dependancies, should be no changes to plan.
> Bump superadmins version

- terraform/github/locals.tf
- terraform/modernisation-platform-account/iam.tf
Remove users who have left the team and bump the superadmin version
> Remove users who have left the team

- terraform/environments/bootstrap/delegate-access/iam.tf
- Removes OIDC provider from testing-test so that the OIDC module can be tested (the implication of this is that OIDC provider module repo will need to be run with AWS keys still and potentially we'll need to look at how testing-test jobs applies are managed.)
- Rolls back OIDC provider creation in core-security-production because we'll be taking a different approach.
> Removing OIDC provider from testing-test and core-security-production.

- .github/workflows/core-security-deployment.yml
- terraform/modules/vpc-hub/README.md
- Bumping oidc provider module version.
- Reconfiguing core security workflow for OIDC.
- Commit changes made by code formatters
- Retrieving the correct account id.
- Fixing the deploy section of GHA to reference the right role.
> Fixing core-security workflow deployment job

- environments/maatdb.json
- policies/environments/expected.rego
Initial PR for MAATDB request #2402
> Create MAATDB development environment

- environments-networks/laa-development.json
- policies/networking/expected.rego
* Add maatdb to list of laa-development accounts
> added maatdb to laa-development

- .github/ISSUE_TEMPLATE/new-environment.md
- .github/ISSUE_TEMPLATE/story-template.md
Updating to make labels more meaningful.
> Update issue labelling on templates

- terraform/environments/core-network-services/transit_gateway_connections.tf
In line with a request from the DSO team, this PR adds further routes to the MP TGW route tables.
> MP TGW routes for Nomis/Studiohosting

- .github/workflows/core-logging-deployment.yml
Fix the JQ for the apply step so that the account id is properly exported
> Fix core-logging workflow apply step

- source/user-guide/running-terraform-plan-locally.html.md.erb
Fixing section title to remove platform_secrets.tf
> Small doc fix

- source/runbooks/terraform.html.md.erb
- source/user-guide/running-terraform-plan-locally.html.md.erb
- Updating guidance for running local plans
> Updating local plans guidance

- terraform/environments/core-network-services/firewall.tf
- terraform/modules/firewall-policy/main.tf
- terraform/modules/firewall-policy/variables.tf
* Reduce `rule_group_capacity` to allow headroom for attaching managed rulesets
* Add CloudWatch log group for firewall logging information
* Add `aws_networkfirewall_logging_configuration` to firewall policy module
> Network firewall adjustments

- scripts/provision-member-directories.sh
- terraform/templates/member-locals.tf
Also remove some code which isn't needed now that we've moved to a separate member-locals file rather than substituting.
> Fix wrong code source url in tag

- terraform/environments/core-network-services/transit_gateway_connections.tf
- terraform/modules/vpc-hub/main.tf
Route traffic in `development` / `test` to `analytics-platform-dev` via PTTP transit gateway.
Route traffic in `preproduction` / `production` to `analytics-platform-preproduction` via PTTP transit gateway.
Route traffic in `preproduction` / `production` to `analytics-platform-production` via PTTP transit gateway.
> Route to Analytics Platform via PTTP TGW

- terraform/environments/bootstrap/delegate-access/iam.tf
https://mojdt.slack.com/archives/C01A7QK5VM1/p1667483219658919
> Adding rhelkb permission to collaborator developer role

- terraform/environments/bootstrap/delegate-access/iam.tf
- terraform/environments/core-shared-services/iam.tf
State transition reason: Server.InternalError
State transition message: Client.InternalError: Client error on launch
> Add "kms:CreateGrant" to instance scheduler role to try fixing the issue

- terraform/environments/core-shared-services/iam.tf
Cannot restrict by KMS alias so leaving open resource and ignoring check
> Ignore open KMS resource

- terraform/environments/bootstrap/delegate-access/iam.tf
Reverts ministryofjustice/modernisation-platform#2546
> Revert "Try removing kms:CreateGrant"

- terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf
Enable Instance Scheduling for xhibit-portal-development,xhibit-portal-preproduction,
> Enable Instance Scheduling for xhibit-portal

- .github/workflows/modernisation-platform-account.yml
In addition to using OIDC in the modernisation-platform-account workflow, the env variables has been extracted from the job and set as global variables and added some spacing and consistency too.
> Refactoring  modernisation-platform-account workflow to use OIDC

- source/runbooks/dos-attack.html.md.erb
- source/runbooks/enabling-shield-advanced.html.md.erb
- source/user-guide/our-offer-to-you.html.md.erb
- source/user-guide/sustainability.html.md.erb
Updating the offer and sustainability page now that we have the instance scheduler up and running.
> Update docs with instance scheduler info

- terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf
The only remaining environment is nomis-preproduction
> Turn on instance scheduling for nomis dev and test

- terraform/environments/core-shared-services/iam.tf
- terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf
Moving lambda and related iam code to the module:
* lambda function resource
* lambda iam role
* lambda iam role trust policy
* lambda allowed triggers permissions
> Migrating lambda creation code to module.

- source/runbooks/joining-the-team.html.md.erb
This is to give alternatives for single points of failure with our tooling.
> Update team tools to include alternatives

- terraform/environments/bootstrap/delegate-access/iam.tf
Even though the test lambda is in the same account as the InstanceSchedulerAccess role is, because it is a role, it still needs to be added to the trust policy.
Splitting out the testing-test role into its own resource for code readability to avoid inserting an if-then block into addition_trust_roles list.
> Creating a separate testing-test InstanceSchedulerAccess role

- source/runbooks/changing-environment-details.html.md.erb
> Change review date

- terraform/environments/bootstrap/delegate-access/iam.tf
This will allow the pipeline to create redshift data and serverless resources
> Add redshift permissions to member access

- .github/workflows/terraform-github.yml
- source/runbooks/changing-environment-details.html.md.erb
> terraform-github.yml changes for OIDC

- architecture-decision-record/0023-backup-strategy.md
- architecture-decision-record/README.md
Closes [#1087](https://github.com/ministryofjustice/modernisation-platform/issues/1087)
> Add ADR on backup strategy

- source/runbooks/terraform.html.md.erb
> This had been updated in the last sprint 

- .github/workflows/core-logging-deployment.yml
- .github/workflows/core-network-services-deployment.yml
- .github/workflows/core-security-deployment.yml
- .github/workflows/core-shared-services-deployment.yml
- .github/workflows/core-vpc-development-deployment.yml
- .github/workflows/core-vpc-preproduction-deployment.yml
- .github/workflows/core-vpc-production-deployment.yml
- .github/workflows/core-vpc-test-deployment.yml
- .github/workflows/modernisation-platform-account.yml
- .github/workflows/new-environment.yml
- .github/workflows/scheduled-baseline.yml
- .github/workflows/templates/workflow-template.yml
- .github/workflows/terraform-github.yml
- .github/workflows/terraform-pagerduty.yml
Following Github security hardening guidelines.
> Pin actions/checkout to hash

- .github/workflows/core-logging-deployment.yml
- .github/workflows/core-network-services-deployment.yml
- .github/workflows/core-security-deployment.yml
- .github/workflows/core-shared-services-deployment.yml
- .github/workflows/core-vpc-development-deployment.yml
- .github/workflows/core-vpc-preproduction-deployment.yml
- .github/workflows/core-vpc-production-deployment.yml
- .github/workflows/core-vpc-test-deployment.yml
- .github/workflows/modernisation-platform-account.yml
- .github/workflows/new-environment.yml
- .github/workflows/scheduled-baseline.yml
- .github/workflows/templates/workflow-template.yml
- .github/workflows/terraform-github.yml
- .github/workflows/terraform-pagerduty.yml
As per GitHub security guidance
> Pin aws-credentials to latest hash

- .github/workflows/core-logging-deployment.yml
- .github/workflows/core-network-services-deployment.yml
- .github/workflows/core-security-deployment.yml
- .github/workflows/core-shared-services-deployment.yml
- .github/workflows/core-vpc-development-deployment.yml
- .github/workflows/core-vpc-preproduction-deployment.yml
- .github/workflows/core-vpc-production-deployment.yml
- .github/workflows/core-vpc-test-deployment.yml
- .github/workflows/modernisation-platform-account.yml
- .github/workflows/new-environment.yml
- .github/workflows/scheduled-baseline.yml
- .github/workflows/terraform-github.yml
- .github/workflows/terraform-pagerduty.yml
Following github security guidance
> Pin terraform setup action to hash

- .github/workflows/documentation.yml
- .github/workflows/format-code.yml
- .github/workflows/generate-dependabot-file.yml
- .github/workflows/labeler.yml
- .github/workflows/new-environment-files.yml
- .github/workflows/new-environment.yml
- .github/workflows/new-member-environment-files.yml
- .github/workflows/opa-policies.yml
- .github/workflows/publish-gh-pages.yml
- .github/workflows/scheduled-baseline.yml
- .github/workflows/terraform-static-analysis.yml
As per security guidance from github
> Pin the last remaining github actions

- terraform/github/main.tf
This is the creation of the repo which will be used as the ssm module, automating the patching of ec2 instances in each account.
> Module to automate the patching of ec2 instances in each account

- scripts/internal/multi-repo-git.sh
Run the script with no arguments to see the usage:
********************************** Usage ********************************** 
Install git and the GitHub CLI - https://cli.github.com/, configure/authenticate to GitHub 
Copy this script to the location where you want the modernisation-platform-repos folder to be created and run from there 
First run the clone command to download all of the MP repos in to the new modernisation-platform-repos folder 
Then open your IDE on that folder and make find/replace changes across all the files 
Example of how to copy a file into a certain subfolder: find . -name 'workflows' -type d -exec cp scorecards.yml {} \; 
Once you have made your changes use the commands below to iterate through each repo in the modernisation-platform-repos folder 
If you wish …
> Add a multi repo PR creater script

- .github/workflows/new-environment.yml
- Fixing workflow, adding step name.
> Fixing New Environments Workflow

- terraform/environments/core-network-services/locals.tf
- terraform/environments/core-network-services/vpn.tf
- terraform/environments/core-network-services/vpn_attachments.json
We need to create VPNs for the LAA, adding like this so that it is expandable as needed.
> Add VPN attachments to TGW

- source/index.html.md.erb
- source/team/ways-of-working.html.md.erb
Updating the doc to reflect what we have agreed in our standards/practices session.
> Adding work and task management info into our ways of working guide.

- environments/refer-monitor.json
Happy to change it to an individual email if necessary.
Updated as Tatiana no longer works here.
> Switch to our team email as Tatiana left

- terraform/pagerduty/aws.tf
- terraform/pagerduty/services.tf
These two integration keys have been added manually, adding them here via code.
Also renaming the core alerts integration so that it's clearer.
> Add the integration key via code

- terraform/github/locals.tf
> Adding Engineer to MP

- source/concepts/networking/networking-approach.html.md.erb
- source/runbooks/joining-the-team.html.md.erb
Some important channels were missing.
> Update to include other slack channels

- environments/delius-iaps.json
Added the iaps pre-prod section to the json.
> Adding pre-prod for iaps

- environments/mlra.json
Initial code to build the new mlra environments
> New MLRA environments

- terraform/environments/core-network-services/vpn.tf
- terraform/environments/core-network-services/vpn_attachments.json
* swich `bpg_asn` value to `bgp_asn`
* add configuration for new VPN to Azure FNG environment.
> added VPN for FNG, fixed typo.

- terraform/environments/bootstrap/delegate-access/iam.tf
Required to build the ssm-patching module with member access only.
> Ram Permissions for ssm-patching module.

- .github/workflows/core-vpc-development-deployment.yml
- .github/workflows/core-vpc-preproduction-deployment.yml
- .github/workflows/core-vpc-production-deployment.yml
- .github/workflows/core-vpc-test-deployment.yml
Forgot to do this before the last push, to iterate through it needs a space.
> Replace comma with space

- collaborators.json
- policies/collaborators/collaborators.rego
- policies/collaborators/collaborators_test.rego
Also update the opa tests to account for new access level.
> Change access level for ppud engineers to sandbox

- terraform/environments/core-network-services/vpn.tf
- terraform/environments/core-network-services/vpn_attachments.json
* Hard coded inside tunnel addresses for VPN to Azure
* Programatic advertisement of MP network ranges over VPN connections (by advertising the `external` route table)
> Adjustments to VPN configuration

- source/concepts/environments/auto-nuke.html.md.erb
- source/user-guide/creating-environments.html.md.erb
Relevant Issue: https://github.com/ministryofjustice/modernisation-platform/issues/2400
Updating nuke docs after the code refactor.
> Updating nuke documentation.

- terraform/github/modules/repository/main.tf
- terraform/github/modules/repository/versions.tf
Reverts ministryofjustice/modernisation-platform#2790
> Revert "Enable security scanning on repos"

- terraform/environments/ppud/iam.tf
This user is required for the local MGN agents to transfer data to the MGN service.
> Add MGN user for PPUD

- policies/environments/environment-definitions.rego
- policies/environments/environment-definitions_test.rego
- source/concepts/environments/auto-nuke.html.md.erb
Ensuring the correct values for nuke are given.
Also detailing valid values on the Nuke page.
> Add OPA tests to check nuke values

- terraform/environments/core-network-services/vpn_attachments.json
Naming confusion, these are actually two different data centres, we are connecting to six degrees not northgate.
> Change name from northgate to six degrees

- terraform/environments/bootstrap/delegate-access/iam.tf
- terraform/environments/core-shared-services/iam.tf
Added Admin role in core-shared-services to kick off and use the automation role stuck deploying.
https://github.com/ministryofjustice/modernisation-platform/actions/runs/3714965100/jobs/6326650213
> Wrong type in principal. Removed AWS for Federated.

- environments-networks/laa-development.json
- environments-networks/laa-preproduction.json
- environments-networks/laa-production.json
- environments-networks/laa-test.json
Request from the ask channel to add these endpoints.
> Add secrets manager vpc endpoints for LAA VPCs

- terraform/environments/bootstrap/delegate-access/iam.tf
Now that we have finished the spike and are implementing this can be removed.
> Revert the test policy added

- terraform/environments/bootstrap/delegate-access/policies.tf
> Rename SIDs to match required naming policy

- .github/workflows/bootstrap-sprinkler-plan.yml
Minor amendment to get the workflow valid.
> Fix new workflow yml formatting error

- .github/workflows/core-logging-deployment.yml
- .github/workflows/core-network-services-deployment.yml
- .github/workflows/core-security-deployment.yml
- .github/workflows/core-shared-services-deployment.yml
- .github/workflows/core-vpc-development-deployment.yml
- .github/workflows/core-vpc-preproduction-deployment.yml
- .github/workflows/core-vpc-production-deployment.yml
- .github/workflows/core-vpc-test-deployment.yml
- .github/workflows/generate-dependabot-file.yml
- .github/workflows/modernisation-platform-account.yml
- .github/workflows/new-environment-files.yml
- .github/workflows/new-environment.yml
- .github/workflows/new-member-environment-files.yml
- .github/workflows/publish-gh-pages.yml
- .github/workflows/scheduled-baseline.yml
- .github/workflows/terraform-github.yml
- .github/workflows/terraform-pagerduty.yml
We were using a 3rd party github action - slack integration.  Replacing with the official slack API action.
> Replace slack action with official one

- environments/oas.json
- policies/environments/expected.rego
- source/runbooks/creating-accounts-for-end-users.html.md.erb
Files for the new OAS application, also updating the guidance as I go to make it more readable and easier to refer to steps. (More updates to come for the next stage)
> New OAS application

- source/runbooks/running-emergency-patching.html.md.erb
- terraform/environments/core-shared-services/ssm.tf
This is a runbook of the stages needed to follow to run the patching cross-account. If it needs more detail, or screenshots, I am happy to do that, just comment away with some feedback.
* It may seem sparse, but a lot of ties into AWS supplied tools / scripts which I have linked in the documentation.
> Runbook for emergency patching added, with details on each step needed.

- source/runbooks/running-emergency-patching.html.md.erb
- terraform/environments/core-shared-services/ssm.tf
Documentation fix, and single line change in ssm file.
> Fixed formatting issue in documentation

- environments/nomis.json
- environments/oasys.json
- terraform/environments/bootstrap/delegate-access/policies.tf
give our -development accounts permissions for sandboxing, to allow for easier testing
> DSO - update accounts and revert permission

- environments/ccms-ebs.json
Requested by Marty Taggart, click-ops to try out a POC, nuke will be added in a few weeks when path to take is decided.
> Changing development to sandbox for laa-ccms-migration-team

- environments/long-term-storage.json
- policies/environments/expected.rego
> Add new long-term-storage account

- source/runbooks/accessing-aws-accounts.html.md.erb
- source/team/operational-processes.html.md.erb
- source/user-guide/how-to-configure-dns.html.md.erb
Checked documents for accuracy and amended review dates.
> updated user-guide documents

- terraform/environments/core-network-services/monitoring.tf
> New Branch

- terraform/environments/core-network-services/monitoring.tf
added dependancy and log type to flow log
> changes to the depenency and also adding destination type

- environments/ccms-ebs.json
CCMS is a system that manages certified civil legal aid applications, amendments and bills, it is our general ledger, chart of accounts and payment system and manages accounts receivable.
we have been asked to create new account for test preproduction and production
This pr set up these new accounts
> new ccms ebs account

- environments-networks/laa-preproduction.json
- environments-networks/laa-production.json
- environments-networks/laa-test.json
- policies/networking/expected.rego
Adding new ccms ebs environemts to Ram Share
> Ccms ram share

- environments/analytical-platform-management.json
This PR adds SSO Admin and View-Only to the AP management account.
> Add view-only and administrator access for management account.

- terraform/environments/core-shared-services/s3.tf
Updated them, probation webops got back to me.
> Shared AMI bucket permissions.

- terraform/environments/core-shared-services/s3.tf
Reverts ministryofjustice/modernisation-platform#2996
> Revert "Shared AMI bucket permissions."

- terraform/environments/bootstrap/delegate-access/iam.tf
- terraform/environments/bootstrap/delegate-access/policies.tf
- terraform/environments/core-shared-services/test/test_terraform/providers.tf
- terraform/environments/equip/iam.tf
- terraform/environments/ppud/iam.tf
- terraform/github/testing-ci.tf
- terraform/modules/iam_baseline/main.tf
This Code fixes all this issues that i have found to do with the SCA. SCA should now complete with a green tick
> Fix's implemeneted

- source/concepts/networking/subnet-nacls.html.md.erb
- source/index.html.md.erb
We get a lot of questions on what traffic is allowed, this will help us provide quick answer to users.
> Add docs on NACL rules

- terraform/environments/bootstrap/member-bootstrap/iam.tf
- terraform/modernisation-platform-account/iam.tf
> Last couple of SCA ignores

- terraform/environments/core-shared-services/s3.tf
Update s3.tf in core-shared-services for ami s3 bucket.
Added 2 permissions.
> Update s3.tf in core-shared-services for ami s3 bucket.

- terraform/environments/core-shared-services/s3.tf
Reverts ministryofjustice/modernisation-platform#3055
> Revert "Update s3.tf in core-shared-services for ami s3 bucket."

- terraform/environments/core-shared-services/s3.tf
"s3:DeleteObject",
"s3:ListBucket"
> Added missing resource line.

- terraform/environments/core-shared-services/s3.tf
mod-platform-image-artefact-bucket.
> Update s3 ami bucket to new name.

- terraform/modules/iam_baseline/main.tf
More Errors found in SCA added to call details and added ignores to the alert
> More SCA checks

- terraform/modernisation-platform-account/backend.tf
- terraform/modernisation-platform-account/data.tf
- terraform/modernisation-platform-account/locals.tf
- terraform/modernisation-platform-account/providers.tf
- terraform/modernisation-platform-account/secrets.tf
Move things in to more logical places
> Refactor and tidy up

- environments/analytical-platform-data.json
> Import analytical-platform-data-production

- source/concepts/networking/network-firewall.html.md.erb
- source/index.html.md.erb
- terraform/environments/core-network-services/production_rules.json
Network firewall documentation initial draft and pr request example for firewall change
> Network Firewall documentation

- environments/ppud.json
New ppud preproduction account creation for migration
> New ppud preproduction

- environments-networks/hmpps-preproduction.json
- policies/networking/expected.rego
Networking setup for ppud preproduction
> Ram Share update for ppud

- .github/workflows/format-code.yml
This now accurately creates a PR following a run of the code formatter.
I'm still not convinced that the step to check for changes is working successfully, so will dig into this separately.
> Code formatter pr creation

- collaborators.json
Adding migration access to the ppud team.
> Add preproduction ppud to ppud collaborators

- terraform/pagerduty/aws.tf
- terraform/pagerduty/member-services-integrations.tf
Following https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/integrating-alarms-with-pagerduty-with-slack.html#3-create-a-pagerduty-service
> LAWS-3031: Add PagerDuty Alert for LAA in MP

- terraform/environments/core-network-services/development_rules.json
- terraform/environments/core-network-services/production_rules.json
- terraform/modules/firewall-policy/main.tf
This PR is to put in place the block function for the Network Firewall
> Network Firewall Traffic Block

- environments/tipstaff.json
- policies/environments/expected.rego
Creating new account for tipstaff
> New account for tipstaff

- environments/tipstaff.json
Corrected the github-slug to point to the correct place.
> Amended the github-slug to point to the correct space

- .github/ISSUE_TEMPLATE/new-environment.md
Including the infrastructure support tag
> Update new environment template

- terraform/modules/firewall-policy/main.tf
> Lifecycle change on policy

- terraform/pagerduty/aws.tf
- terraform/pagerduty/member-services-integrations.tf
create low priority alarm channel for nomis alerts
> nomis_nonprod_alarm pagerduty integration

- environments-networks/laa-development.json
- environments-networks/laa-test.json
- policies/networking/expected.rego
Add accounts to the correct networks
> Network changes

- scripts/provision-member-directories.sh
This PR is part of the https://github.com/ministryofjustice/modernisation-platform/issues/2521 ticket.
This is to workaround the permission issue for the backend dynamodb_table.
It is also extracting repository paths as variables for easier testing when running the script locally.
This has been tested  (terraform plan) with the apex account in the env repo (terraform plan).
> Removing dynamodb in env backend

- terraform/environments/core-shared-services/s3.tf
This PR Creates a new S3 bucket for the prepose of storing software for software builds
> New S3 bucket for software installs

- terraform/environments/core-shared-services/s3.tf
Turns out you cannot have another bucket referenced in resources of a bucket's policy.
> Fix the bucket policy

- .github/workflows/templates/workflow-template.yml
Added ability to destroy `development` / `test` environment to standard workflow template
> Updated workflow template

- source/concepts/sdlc/user-workflow.html.md.erb
Added a line about adding to CODEOWNERS if a new team is added
> Added comment about CODEOWNERS in ami-builds

- terraform/modules/firewall-policy/main.tf
This Pr removes the Priority for the rule group we have tested this locally and the change has gone though and updated the firewall with the new rules and rule policy which is now set to default
> priority change

- terraform/environments/core-network-services/preproduction_rules.json
This PR add a block to the ingress traffic to the prod and pre production CIDR range.
> Production and preproduction block

- source/user-guide/creating-networking.html.md.erb
- source/user-guide/creating-resources.html.md.erb
- source/user-guide/environment-diagram.html.md.erb
- source/user-guide/obtaining-deployment-credentials.html.md.erb
- source/user-guide/wider-moj-connectivity.html.md.erb
Added a comment on the restrictions under Creating resources to indicate "platform_" should not be changed without prior consultation. Any changes to these may be blocked.
> Review date changes

- terraform/environments/core-network-services/development_rules.json
- terraform/environments/core-network-services/preproduction_rules.json
- terraform/environments/core-network-services/production_rules.json
- terraform/environments/core-network-services/test_rules.json
analytics platform and nomis cidr ranges added to allow there traffic to pass though when the block is implemented
> Firewall changes

- terraform/environments/core-network-services/development_rules.json
- terraform/environments/core-network-services/preproduction_rules.json
- terraform/environments/core-network-services/production_rules.json
- terraform/environments/core-network-services/test_rules.json
DSO team have pointed out that all the rules that have been specified are in the wrong file this pr corrects this and puts the rules in the right area's
> Rules move around

- terraform/environments/bootstrap/member-bootstrap/iam.tf
Member request, please see this [post](https://mojdt.slack.com/archives/C013RM6MFFW/p1678101624783699) before approving, I am not convinced we should allow it, so I would like some opinions...
> Adding waf API to memberaccess policy

- terraform/environments/core-network-services/preproduction_rules.json
- terraform/environments/core-network-services/production_rules.json
This Pr reimplements the Production network traffic block
> Production block

- environments/digital-prison-reporting.json
This PR adds in a test environment to the HMPPS client
> New test account for digital-prison-reporting

- .github/workflows/format-code.yml
Realised that the `check for changes` step was missing a commit message.
> Updated code formatting action

- environments/ccms-ebs.json
Request from the EBS team to have security be able to review their accounts.
> Give view only access to security

- terraform/environments/core-network-services/firewall.tf
- terraform/modules/firewall-policy/main.tf
- terraform/modules/firewall-policy/variables.tf
This PR changes the way the name is generated for the FQDN rule group name
> Firewall group name change

- terraform/modules/firewall-policy/main.tf
Now the New FQDN rule group is created we need to add the new group to the current firewall policy this PR does this
> add new rulegroup to the firewall policy

- terraform/environments/delius-jitbit/iam.tf
- terraform/environments/ppud/iam.tf
- terraform/modules/firewall-policy/main.tf
- terraform/modules/firewall-policy/variables.tf
- terraform/modules/r53-resolver-logs/main.tf
Reviewed the raised warnings, we can safely ignore these.
> Ignore SCA warnings

- .github/ISSUE_TEMPLATE/new-environment.md
This PR is part of the #3274 
Adding Firewall Rule section to our new env issue template.
Please check if the description of the section makes sense and whether it is technically correct.
I was also not sure whether it is better to let the users to provide a code snippet or provide them with a table to fill out.
> Adding firewall rules option to the new env issue template

- terraform/environments/core-shared-services/ecr_repos.tf
Adds the MLRA to the push principles
> Update to permissions to push to ecr

- environments/oas.json
> Additional OAS environmnents

- collaborators.json
Processing request from the ask channel for more collaborators for the ppud environments
> Adding new collaborators

- terraform/pagerduty/member-services-integrations.tf
- terraform/pagerduty/services.tf
- set acknowledgement_timout to correct "null" value
- create the Modernisation Platform business service in code
- associate our services to the business service
> Add MP business service as code and fix timeout

- terraform/environments/core-shared-services/ecr_repos.tf
Probation Webops work item: nit-579
Addition of 2 ECR repos for initial delius core environment
> Adding hmpps delius ui and testing db ECR repos

- .github/ISSUE_TEMPLATE/new-environment.md
Adjusted template for readability and to make example a little less service specific.
> Amend new environment template

- terraform/environments/core-shared-services/ecr_repos.tf
Small name change to ensure consistency with other repos.
> Name tweak to delius-core ecr repo names for consistency

- terraform/environments/bootstrap/member-bootstrap/iam.tf
added missing brace, applied terraform fmt
> Fix bootstrap for us-east-1 

- terraform/environments/core-shared-services/ecr_repos.tf
Adding extra permission for pulling delius ecr repos.
> Add extra pull permissions for delius ecr repos

- environments/laa-ccms-infra-azure-ad-sso.json
Amend the permissions for the CCMS Azure AD SSO account to the correct ones.
> amend CCMS Azure AD SSO permissions

- terraform/environments/core-vpc/vpc.tf
Related to this request. - https://mojdt.slack.com/archives/C01A7QK5VM1/p1679934502772039?thread_ts=1679926851.614689&cid=C01A7QK5VM1
Hopefully this will solve this error they are currently getting. 
``` updating Security Group () tags: tagging resource (): UnauthorizedOperation: You are not authorized to perform this operation.  ```
> Create Tags on Security Groups

- source/concepts/networking/dns.html.md.erb
- source/user-guide/production-ready-checklist.html.md.erb
Doc changes, date only, contents looks good.
> Feature/docs 30/03/23

- terraform/environments/bootstrap/member-bootstrap/iam.tf
Requested by a user in this slack thread: https://mojdt.slack.com/archives/C01A7QK5VM1/p1680268448793299
> Adding resource explorer perms as requested by a user

- terraform/environments/core-network-services/test_rules.json
Request - https://mojdt.slack.com/archives/C01A7QK5VM1/p1680269213955939
> Update hmpps-test connectivity

- .github/workflows/format-code.yml
Matching changes in the environment repository.
> Prevent report folder creation

- terraform/environments/bootstrap/delegate-access/policies.tf
Additional permission added to allow developers to reset the directory services passwords.
> Add permissions for directory services pw reset

- environments/mojfin.json
- policies/environments/expected.rego
New account for the mojfin database. The request did not specify pre-production so this has not been included.
> New account for MOJFIN database

- scripts/provision-terraform-workspaces.sh
Workspace creation logic was still based on shared templates, updating to reflect different templates.
> Fix broken workspace creation

- environments-networks/hmpps-development.json
- environments-networks/hmpps-production.json
- policies/networking/expected.rego
for hmpps-intelligence-management-production and hmpps-intelligence-management-development
> Network settings for new accounts

- terraform/github/repositories.tf
- terraform/github/teams.tf
Added code to archive but we want to delete it instead so code will be amended. It automatically archives when you delete.
Had to remove a line of code from teams.tf (module.terraform-module-ecs.repository.name) as it was failing when it hit this.
> New section to archive the modernisation-platform-terraform-ecs repo

- source/concepts/sdlc/patching.html.md.erb
- source/user-guide/running-terraform-plan-locally.html.md.erb
For running terraform plan locally and patching
> Change review dates

- collaborators.json
Creation of account for Edward Thomás Caren, it was request in the ask channel from PPUD.
> Account Creation

- environments/data-platform.json
Added nuke rebuild for development on the data platform account
> Changes to the data platform

- terraform/environments/core-network-services/firewall-rules/preproduction_rules.json
- terraform/environments/core-network-services/firewall-rules/production_rules.json
New PR created for ticket [Restrict firewall ranges to VPCs#3652](https://github.com/ministryofjustice/modernisation-platform/issues/3652) as the last PR had to be removed this covers rules renaming and the seperation of the production and pre production rules
> New PR for Firewall changes

- terraform/environments/core-network-services/firewall-rules/inline_rules.json
Found a copy-paste error and updated it to allow HTTP traffic out to all destinations
> Update address in firewall rule

- environments/delius-jitbit.json
Granting access for this team into the dev AWS account
> Grant access for Jitbit dev team to hmpps jitbit dev environment

- source/user-guide/certificate-import-windows.html.md.erb
> Amendment to windows import certificate instructions

- environments/tipstaff.json
New Environment setup for tipstaff preproduction
> Tipstaff preproduction environment

- source/runbooks/changing-environment-details.html.md.erb
Also remove the reference to github repositories which is no longer needed as autogenerated.
> Add nuke to changing environments docs

- terraform/environments/bootstrap/secure-baselines/main.tf
due to issues with s3 ACL we have had to do a version update on the secure base line and do a release this pr changes the code to user the new version of the baseline to hopefully fix the s3 acl issue
> Module version update

- terraform/environments/core-network-services/route53.tf
Request - https://mojdt.slack.com/archives/C01A7QK5VM1/p1683037587322199
Ops engineering will need to delegate the hosted zone to us next (so I have been told)
> Update route53.tf for mojfin and mlra.

- terraform/pagerduty/member-services-integrations.tf
Additional pager duty integrations for the Sheffield DBA team for nomis, oasys etc.
> nomis: DSOS-1833: add new pager duty integrations for Sheffield DBA team

- terraform/pagerduty/aws.tf
Add the integration keys for the Sheffield DBA pager duty services
> nomis: DSOS-1833: add DBA alert integration keys

- terraform/environments/bootstrap/delegate-access/policies.tf
Adding some operational airflow permissions to enable troubleshooting airflow jobs in the environment.
> Adding some additional airflow permissions to the DE role.

- terraform/templates/modernisation-platform-environments/platform_data.tf
Only place this code appears on modernisation-platform so I have amended this. It will need to be merged around the same time as the change for modernisation-platform-environments.
> Amended private-public to shared-private on platform_data.tf

- source/team/roadmap.html.md.erb
- source/user-guide/creating-automated-terraform-documentation.html.md.erb
- source/user-guide/our-offer-to-you.html.md.erb
- source/user-guide/sustainability.html.md.erb
Update docs.
- [Creating Automated Terraform Documentation](https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/creating-automated-terraform-documentation.html) (13 days ago)
- [How to use shared KMS keys](https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/how-to-use-shared-kms-keys.html) (11 days ago)
- [Our roadmap](https://user-guide.modernisation-platform.service.justice.gov.uk/team/roadmap.html) (3 days ago)
- [Our offer to you](https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/our-offer-to-you.html) (2 days ago)
- [Sustainability](https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/sustainability.html) (2 days ago)
> Doc update

- environments/data-platform.json
Removing while PoC work is being carried out
> Exclude Data Platform Development from AWS Nuke

- source/runbooks/dos-attack.html.md.erb
- source/runbooks/enabling-shield-advanced.html.md.erb
Update 
- dos attack
- shield advanced
> Updated docs.

- collaborators.json
New user for PPUD for security audit
> Add new temporary user to PPUD

- environments/tipstaff.json
Updated permissions as requested - https://mojdt.slack.com/archives/C01A7QK5VM1/p1683881171439589
> Update tipstaff.json to migration level.

- environments/mojfin.json
Added laa-mojfin-developers to mojfin access.
> Update mojfin.json to include laa-mojfin-developers

- terraform/environments/core-network-services/acm-pca.tf
- terraform/modules/vpc-inspection/main.tf
- terraform/modules/vpc-inspection/variables.tf
* Fix invocation of `abort_multipart_upload` block
* Fix conditional use of kms key to encrypt logs
> Resolve issues in core-shared-services

- terraform/github/repositories.tf
This PR creates a  new repo for the spike to create a new module for route53 and aws certificates
> New Module Repo

- terraform/pagerduty/member-services-integrations.tf
Required for Mod Platform CloudWatch alarms.
> Adding OASys Pagerduty

- environments/delius-jitbit.json
> Add jitbit test environment

- environments-networks/hmpps-test.json
- policies/networking/expected.rego
Related to this PR - https://github.com/ministryofjustice/modernisation-platform/pull/3861
> Creation of jitbit test

- source/concepts/environments/backups.html.md.erb
- source/runbooks/adding-a-new-team-member.html.md.erb
- source/runbooks/removing-a-team-member.html.md.erb
- source/runbooks/terraform.html.md.erb
- source/user-guide/how-to-use-shared-kms-keys.html.md.erb
Checked documentation, adjusted review dates.
> User guidance review dates

- terraform/environments/bootstrap/delegate-access/policies.tf
As per request here:
https://mojdt.slack.com/archives/C4PF7QAJZ/p1684161937438129
> Updating data engineering policy with permission to list glue sessions

- terraform/github/teams.tf
this PR allow access to the our team to the new module repo i created last week
> adding team to new repo

- terraform/environments/ccms-ebs/iam.tf
Create SES users for CCMS-EBS environments
> Create SES users in CCMS-EBS environments

- source/concepts/environments/single-sign-on.html.md.erb
* Amends review date so that document is assessed on proper schedule
> Review of SSO docs page

- environments/digital-prison-reporting.json
The PR covers a request for a temporary inclusion of hmpps digital prison reporting development environment to the the auto nuke on sunday a second pr will be raised after monday to revert this change
> Nuke request

- environments/ccms-ebs.json
- environments/delius-iaps.json
- environments/equip.json
- environments/example.json
- environments/nomis.json
- environments/performance-hub.json
- environments/ppud.json
- environments/xhibit-portal.json
Related to this story. 
https://github.com/ministryofjustice/modernisation-platform/issues/3642
Was going to add a test, however this is optional, looking at the current tests, they have values which are allowed, but go live will allow any date. Maybe a format check, but not sure that's worth it, as this value is for us.
> go-live-date added to env

- terraform/environments/bootstrap/member-bootstrap/iam.tf
This will allow MP users to create api gateways, following a user request in the ask channel here - https://mojdt.slack.com/archives/C01A7QK5VM1/p1684838327099879
> Add apigateway permissions to the member pipeline

- terraform/environments/core-network-services/cidr-ranges.tf
- terraform/environments/core-network-services/firewall-rules/production_rules.json
- terraform/environments/core-network-services/locals.tf
- terraform/environments/core-network-services/vpn.tf
- terraform/environments/core-network-services/vpn_attachments.json
* Add options for further VPN settings
* Define minimum matching proposals for Parole Board
* Add static route to Parole Board via VPN
> Parole Board VPN settings

- terraform/environments/bootstrap/delegate-access/iam.tf
- terraform/modernisation-platform-account/secrets.tf
- terraform/modules/kms/main.tf
- terraform/modules/vpc-hub/main.tf
- terraform/modules/vpc-inspection/main.tf
- terraform/modules/vpc-nacls/main.tf
Gone through and verified, the actions associated with these warnings are not required.
> Add more ignores for SCA

- terraform/environments/bootstrap/member-bootstrap/instance-scheduler.tf
- terraform/environments/bootstrap/member-bootstrap/ssm.tf
- terraform/environments/ccms-ebs/iam.tf
- terraform/environments/core-logging/athena.tf
- terraform/environments/core-logging/s3_logging.tf
- terraform/environments/core-network-services/acm-pca.tf
- terraform/environments/core-network-services/iam.tf
- terraform/environments/core-shared-services/iam.tf
- terraform/environments/equip/data.tf
- terraform/environments/ppud/iam.tf
- terraform/github/testing-ci.tf
- terraform/modernisation-platform-account/dynamodb.tf
- terraform/modernisation-platform-account/iam.tf
- terraform/modules/iam_baseline/main.tf
- terraform/modules/kms/main.tf
- terraform/modules/vpc-hub/main.tf
- terraform/pagerduty/data.tf
Code was reviewed and ignored / fixed as appropriate.
> More SCA fixes and ignores

- terraform/environments/bootstrap/member-bootstrap/iam.tf
- terraform/environments/core-network-services/firewall.tf
- terraform/environments/secrets.tf
Couple of missed and incorrect ignores fixed.
> SCA Ignore corrections

- environments-networks/hmpps-preproduction.json
- policies/networking/expected.rego
New environment creation: https://github.com/ministryofjustice/modernisation-platform/issues/3911
> Adding networking for preproduction env of DPR

- environments-networks/platforms-development.json
- policies/networking/expected.rego
> RAM setup for account data-platform-apps-and-tools-development

- environments/planetfm.json
This PR is part of the https://github.com/ministryofjustice/modernisation-platform/issues/3908 ticket
> Dummy change to trigger the pipeline for planetfm in secure baseline

- source/concepts/networking/certificate-services.html.md.erb
- source/concepts/networking/instance-access-and-bastions.html.md.erb
- source/concepts/networking/networking-diagram.html.md.erb
updated document dates after reviewing them
> document updates

- environments-networks/hmpps-development.json
- environments-networks/hmpps-preproduction.json
- environments-networks/hmpps-production.json
- environments-networks/hmpps-test.json
- policies/networking/expected.rego
This ticket is part of the https://github.com/ministryofjustice/modernisation-platform/issues/3908 ticket.
> Creating networking for planetfm accounts

- config/tech-docs.yml
- source/team/team.html.md.erb
- terraform/github/locals.tf
Add Aaron Robinson to the team page, GitHub team and fix the broken 'Home' link.
> :memo: Update Team Page

- terraform/environments/core-network-services/monitoring.tf
Fixing SCA tfsec failure as pointed out in this [slack thread](https://mojdt.slack.com/archives/C013RM6MFFW/p1685629980288159).
> Suppressing tfsec sns topic encryption message

- environments/nomis-combined-reporting.json
getting the NART team into the AWS environments for combined reporting
> update nomis-combined-reporting.json to give access to NART team

- environments/hmpps-oem.json
- policies/environments/expected.rego
New environment for HMPPS OEM as per [New hmpps-oem accounts#3892](https://github.com/ministryofjustice/modernisation-platform/issues/3892)
> New environment creation

- environments/hmpps-oem.json
Change to owner line as the account creation failed due to not meeting the pattern
> changed to single e-mail address

- environments/hmpps-oem.json
Extra owner added into tags as per the ticket
> adding in extra owner

- terraform/environments/hmpps-oem/networking.auto.tfvars.json
Adding in missing sections to correct an error which has prevented the vpc's from being created in the new environments
> networking fix for hmpps oem

- terraform/environments/core-shared-services/ecr_repos.tf
adding ecr to contain image for lambda function code being used in data platform's data product development work
> add data platform athena load ecr

- terraform/modernisation-platform-account/iam.tf
This PR removes Julia L and adds Mark R and Aaron R to superadmin users list.
superadmin-iam-update [156](https://github.com/ministryofjustice/modernisation-platform-terraform-iam-superadmins/pull/156)
> Update Superadmin List

- .github/ISSUE_TEMPLATE/story-template.md
After discussing during refinement, adding for all new issues.
> Add needs refining label to all new stories

- source/user-guide/automated-patching.html.md.erb
fixed typo and updated the review date.
> Review Automated Patching Page

- collaborators.json
a Request has come though to update the collaborator access to include github access
> update to collaborator access

- terraform/environments/bootstrap/delegate-access/policies.tf
- terraform/environments/bootstrap/member-bootstrap/iam.tf
- terraform/environments/core-shared-services/ecr_repos.tf
Requesting additional permissions that would allow engineers to trigger jobs via the Console.
> Add glue trigger jobs permissions and terraform fmt.

- .github/workflows/terraform-github.yml
This PR is to address the problem discussed in this [slack thread](https://mojdt.slack.com/archives/C013RM6MFFW/p1686591023431159).
> Fixing the slack notification behaviour

- terraform/pagerduty/aws.tf
- terraform/pagerduty/locals.tf
- terraform/pagerduty/member-services-integrations.tf
This PR covers work for issue [Define pagerduty slack integrations in code#4154](https://github.com/ministryofjustice/modernisation-platform/issues/4154) where we are trying to automate the integration of a slack channel to a pager duty service
> pager duty changes

- terraform/environments/core-shared-services/ecr_repos.tf
adding the lambda function arn so that it can pull the image from the ecr rep
> add lambda function to retrieval policy for repo

- environments/digital-prison-reporting.json
Related to this ticket - https://github.com/ministryofjustice/modernisation-platform/issues/4155
> Update digital-prison-reporting to use reporting-operations role.

- environments/moj-official.json
- policies/environments/expected.rego
New account for moj-offcial preproduction. There is already a "MOJ Official (Production)" account so this one should not impact that one
> New moj-official preproduction account

- terraform/environments/moj-official/networking.auto.tfvars.json
Reverts ministryofjustice/modernisation-platform#4268
> Revert "New files for terraform/environments"

- environments-networks/hq-preproduction.json
- policies/networking/expected.rego
Reverts ministryofjustice/modernisation-platform#4266
> Revert "RAM share section of moj-official-preproduction"

- source/runbooks/creating-accounts-for-end-users.html.md.erb
Adding comments relating to creating member-unrestricted accounts. Some steps are not required when creating these accounts so this is to clarify the documentation. Also updated the refresh date
> Change to creating-accounts-for-end-users.html.nd.erb

- terraform/environments/bootstrap/delegate-access/policies.tf
Added permissions requested for reporting-operations role.
> Added permissions requested for reporting-operations role.

- terraform/environments/analytical-platform/versions.tf
> update versions - analytical-platform

- terraform/environments/apex/versions.tf
> Update versions - Apex

- terraform/environments/analytical-platform-data-engineering/versions.tf
> update versions - analytical-platform-data-engineering

- terraform/environments/bichard7/versions.tf
- terraform/environments/mi-platform/versions.tf
- terraform/environments/remote-supervision/versions.tf
- terraform/environments/tariff/versions.tf
> Glacier TFstate environment upgrades

- terraform/environments/oas/versions.tf
- terraform/environments/oasys/versions.tf
- terraform/environments/performance-hub/versions.tf
- terraform/environments/planetfm/versions.tf
- terraform/environments/portal/versions.tf
- terraform/environments/ppud/versions.tf
> update versions - op

- terraform/environments/digital-prison-reporting/versions.tf
- terraform/environments/equip/versions.tf
- terraform/environments/example/versions.tf
- terraform/environments/hmpps-intelligence-management/versions.tf
- terraform/environments/hmpps-oem/versions.tf
> update versions - Digital > HMPPS

- terraform/environments/refer-monitor/versions.tf
- terraform/environments/sprinkler/versions.tf
> update versions - rs

- terraform/environments/data-and-insights-wepi/versions.tf
> update versions - data-and-insights-wepi

- terraform/environments/maatdb/versions.tf
- terraform/environments/mlra/versions.tf
- terraform/environments/mojfin/versions.tf
- terraform/environments/nomis-combined-reporting/versions.tf
- terraform/environments/nomis-data-hub/versions.tf
- terraform/environments/nomis/versions.tf
> update versions - mn

- terraform/environments/corporate-staff-rostering/iam.tf
Request - https://mojdt.slack.com/archives/C013RM6MFFW/p1687170870158149
```
+ resource "aws_iam_user" "mgn_user" {
+ arn           = (known after apply)
+ force_destroy = false
+ id            = (known after apply)
+ name          = "MGN-Test"
+ path          = "/"
+ tags          = {
+ "application"            = "corporate-staff-rostering"
+ "business-unit"          = "HMPPS"
+ "environment-name"       = "corporate-staff-rostering-development"
+ "infrastructure-support" = "digital-studio-operations-team@digital.justice.gov.uk"
+ "is-production"          = "false"
+ "owner"                  = "digital-studio-operations-team@digital.justice.gov.uk"
+ "source-code"            = "https://github.com/ministryofjustice/modernisation-platform"
}
+ …
```
> Added new mgm user 

- source/user-guide/integrating-alarms-with-pagerduty-with-slack.html.md.erb
with the changes to the way pagerduty is now setup i have amended the documentation to reflect those changes
> pagerduty documentation update

- terraform/environments/core-network-services/cidr-ranges.tf
- terraform/environments/core-network-services/firewall-rules/development_rules.json
This PR creates a firewall rule for hmpps development to Delius Core development as per this [slack request](https://mojdt.slack.com/archives/C01A7QK5VM1/p1687174168001569)
> Delius Firewall Rule Request

- terraform/environments/bootstrap/delegate-access/policies.tf
- Add kinesis Read, List
- Add Kinesis Put Permissions
> Update Kinesis Permissions for Reporting Policy

- .github/workflows/code-scanning.yml
Reverts ministryofjustice/modernisation-platform#4367
> Revert "Update code-scanning.yml"

- terraform/environments/core-network-services/firewall-rules/development_rules.json
Add MP to CP PgTraffic, and Vice-Versa
> Add MP to CP PG Traffic, and Other way

- terraform/environments/bootstrap/member-bootstrap/iam.tf
> Update Cloud Trail Permissions

- source/concepts/sdlc/sandbox-testing-environments.html.md.erb
- source/runbooks/running-emergency-patching.html.md.erb
Reviewed the two documents and the read ok and don't need any changes as far as i can see
> Documents reviewed

- terraform/environments/core-network-services/cidr-ranges.tf
- terraform/environments/core-network-services/firewall-rules/development_rules.json
Also updated name of dev, to keep it consistent with legacy delius naming
> NIT-725 add delius network ranges to FW code

- terraform/environments/bootstrap/delegate-access/policies.tf
> Update DPR Reporting Role

- environments/digital-prison-reporting.json
New production environment for digital-prison-reporting as per #4348
> Add production environment for digital-prison-reporting

- terraform/pagerduty/aws.tf
- terraform/pagerduty/member-services-integrations.tf
LAWS-3318 - PagerDuty for LAA MAAT Application
> LAWS-3318 - PagerDuty for LAA MAAT Application

- terraform/environments/bootstrap/delegate-access/policies.tf
> Reporting Role Policy Updates

- environments-networks/hmpps-production.json
- policies/networking/expected.rego
- terraform/environments/core-network-services/firewall-rules/production_rules.json
Add Digital Prison Reporting network configuration
> DPR Networking Setup

- terraform/environments/data-platform/data-platform-oidc.tf
- terraform/environments/environments.tf
> Commit hash fix.

- terraform/environments/bootstrap/delegate-access/policies.tf
Required to interact with MWAA
> 🛂 Add Airflow permissions to sandbox policy

- source/index.html.md.erb
- source/team/vision.html.md.erb
- source/user-guide/security-testing-and-ithc.html.md.erb
This is a new document about ITHCs on the mod platform
> ITHC doc for user guide

- terraform/environments/bootstrap/delegate-access/policies.tf
This PR is a user request from the following [slack thread](https://mojdt.slack.com/archives/C01A7QK5VM1/p1688468012455799).
> Updating developer role to include rds:AddTagsToResource

- architecture-decision-record/0025-non-standard-user-infrastructure.md
- architecture-decision-record/0026-use-network-services-account-for-dns.md
- architecture-decision-record/README.md
This ADR captures the outcome of a discussion on DNS and specifically the creation of private hosted zones for customers.
> Architectural Decision record following DNS discussion

- collaborators.json
He also needs access to the other ones
> Additional account access needed

- terraform/environments/bootstrap/delegate-access/policies.tf
Failed running a job. May need to repeat this as they go along.
> Adding wellarchitected permissions to developer

- collaborators.json
New collaborator accounts for ITHC users to view config for DPR
> New ITHC accounts

- terraform/environments/bootstrap/delegate-access/policies.tf
Added to development but they were accessing sandbox
> Adding to the sandbox role

- terraform/environments/bootstrap/delegate-access/policies.tf
Added a few yesterday but they are still getting permission warnings. Adding all the permissions to the sandbox user today
> Adding full wellarchitected permissions to sandbox

- terraform/environments/data-platform-apps-and-tools/environment-configuration.tf
- terraform/environments/data-platform-apps-and-tools/iam-policies.tf
- terraform/environments/data-platform-apps-and-tools/iam-roles.tf
- terraform/environments/data-platform-apps-and-tools/mwaa-environments.tf
- Backport the logging configuration that I did in the console when debugging
- Add missing KMS statement
- Consolidate CloudWatch Log statements
> 👷 Update MWAA policy and logging configuration

- terraform/pagerduty/aws.tf
- terraform/pagerduty/member-services-integrations.tf
Set up the MoJFin Development pagerduty access by defining resources in terraform/pagerduty/member-services-integrations.tf
> LAWS-3329: LAA MojFin Dev pagerduty resources created

- environments/long-term-storage.json
Give the new github team access
> Update access for long term storage account

- environments-networks/hmcts-development.json
- environments-networks/hmcts-preproduction.json
- environments-networks/hmcts-production.json
- policies/networking/expected.rego
trying a fresh PR just incase is is something i did on the manual commit via the github page
> Ram Share new PR

- environments/data-and-insights-wepi.json
From this request - https://mojdt.slack.com/archives/C01A7QK5VM1/p1689336579913929
> Excluding from nuke.

- environments-networks/hmcts-development.json
- environments-networks/hmcts-preproduction.json
- environments-networks/hmcts-production.json
- policies/networking/expected.rego
RAM sharing step on creating the environment
> RAM sharing for wardship

- environments-networks/hmpps-development.json
- environments-networks/hmpps-preproduction.json
- environments-networks/hmpps-production.json
In line with [this Slack request](https://mojdt.slack.com/archives/C01A7QK5VM1/p1689622536083959), this PR adds VPC endpoints for Amazon API Gateway.
> Add VPC Endpoint to HMPPS VPCs

- terraform/environments/corporate-staff-rostering/iam.tf
Attaching policy as per Slack request: https://mojdt.slack.com/archives/C01A7QK5VM1/p1689685746877349
AWS Docs: https://docs.aws.amazon.com/migrationhub/latest/ug/new-customer-setup.html
> Adding AWSApplicationDiscoveryServiceFullAccess to MGN User

- environments/corporate-staff-rostering.json
As per conversation on Slack: https://mojdt.slack.com/archives/C013RM6MFFW/p1689779044898269
> Update corporate-staff-rostering level to migration

- source/user-guide/security-testing-and-ithc.html.md.erb
I have tidied up 1 section, and added a section to explain how ITHC testers should access - following on from DPR ITHC test
> updating access info in ITHC doc

- terraform/environments/delius-jitbit/iam.tf
```
+ resource "aws_iam_access_key" "email" {
+ create_date                    = (known after apply)
+ encrypted_secret               = (known after apply)
+ encrypted_ses_smtp_password_v4 = (known after apply)
+ id                             = (known after apply)
+ key_fingerprint                = (known after apply)
+ secret                         = (sensitive value)
+ ses_smtp_password_v4           = (sensitive value)
+ status                         = "Active"
+ user                           = "delius-jitbit-development-email_user"
}
+ resource "aws_iam_user" "email" {
+ arn           = (known after apply)
+ force_destroy = false
+ id            = (known after apply)
+ name          = "delius-jitbit-development-email_user"
+ path …
```
> Email Jitbit user.

- environments/ppud.json
Update to correct go live date following successful cutover weekend.
> Update ppud.json go live date

- environments/digital-prison-reporting.json
Adding multiple GitHub groups to Support different Envs (Non-Prod and Prod)
> DPR-601 support access to non-production environments

- source/concepts/networking/network-firewall.html.md.erb
Clarified use of FQDN inspection rules
> Updated firewall docs

- source/concepts/networking/dns.html.md.erb
- source/runbooks/creating-new-dns-zones.html.md.erb
* Adds runbook detailing addition of new public zones
* Updates concepts to cover expansion to non-modernisation platform domains
Relates to https://github.com/ministryofjustice/modernisation-platform/issues/4475
> DNS Docs refresh

- source/index.html.md.erb
- source/runbooks/creating-new-private-dns-zones.html.md.erb
As part of the ticket to create a new module for private DNS zone there is a need to create documentation show user how to create the new zones in code this pr add this documentation to the runbook section on our user guides.
> New Private zone documentation

- source/runbooks/creating-new-private-dns-zones.html.md.erb
Missed a commit from the last merge for the documentation this PR corrects this issue
> Additional changes for private VPC zone docs

- terraform/environments/core-network-services/route53.tf
Create private hosted zone for MP Portal Development account:
aws.dev.legalservices.gov.uk
> LAWS-3284: added portal dev private hosted zone

- terraform/environments/core-vpc/vpc.tf
- terraform/modules/private-dns-zone-extend/main.tf
Due to an issue with the new module it looks like nothing is being passed though this pr add's an output to check the data element of the module
> added output to see what is being passed

- terraform/environments/bootstrap/delegate-access/policies.tf
Reverts ministryofjustice/modernisation-platform#4676
> Revert "CICD policy adjustment"

- source/runbooks/creating-new-private-dns-zones.html.md.erb
Following on from https://github.com/ministryofjustice/modernisation-platform/pull/4694, this PR updates the documents to match the revised approach
> Updated docs for private zone association

- terraform/environments/core-network-services/firewall-rules/fqdn_rules.json
- terraform/environments/core-network-services/firewall-rules/inline_fqdn_rules.json
Fixing typo as per slack conversation https://mojdt.slack.com/archives/C01A7QK5VM1/p1691052534081459
> Fix ubuntu typo in firewall rules

- terraform/environments/core-shared-services/ecr_repos.tf
Adding repository for a custom base image for data platform python applications to use
> add data platform python base repo

- environments-networks/laa-development.json
We need to associate changed private hosted zone with our VPC
> LAWS-3315: change of MP Portal Dev private hoisted zone domain name

- collaborators.json
New collaborator request for mp portal account from the ask channel
hi team, can I ask you please to grant access to 
[@Saanchi Dubey](https://mojdt.slack.com/team/U0445BDDA3S)
to portal-development environment?
> New collaborator

- terraform/modules/iam_baseline/main.tf
As per slack request https://mojdt.slack.com/archives/C01A7QK5VM1/p1691581358649139 this PR adds the `lambda:UpdateFunctionCode` to `cicd-member-user` policy.
> add lambda update function code

- terraform/environments/ncas/secrets.tf
- terraform/environments/pra-register/secrets.tf
creating a new secret outside of the environments repo so that is is not deleted
> new secret for environment

- terraform/environments/pra-register/data.tf
- terraform/environments/pra-register/secrets.tf
* Added KMS call to encrypt secret
* Tidied up naming as it doesn't need to be self-referential
> adjusted secrets for pra-register to fix SCA errors

- terraform/environments/core-network-services/route53.tf
As per slack [request](https://mojdt.slack.com/archives/C01A7QK5VM1/p1691749457911439) this PR add the [parental-responsibility-agreement.service.justice.gov.uk](http://parental-responsibility-agreement.service.justice.gov.uk/) domain for `pra-register`
> add domain name for pra-register

- source/runbooks/creating-new-dns-zones.html.md.erb
After having seen a few issues in the #ask-modernisation-platform slack channel it appears that we need more explicit guidance on delegating new domains to the Modernisation Platform. This PR briefly updates the process to include that step. Without it, things like adding new records won't resolve.
> 📖 Clarify new zones process

- environments-networks/platforms-production.json
- policies/networking/expected.rego
Missed on this PR I believe. https://github.com/ministryofjustice/modernisation-platform/pull/4785
> Data platform apps and tools production tidy

- terraform/environments/wardship/secrets.tf
Fixes - https://github.com/ministryofjustice/modernisation-platform/actions/runs/5923065434/job/16058039084
> Adding missing ignores

- terraform/environments/core-network-services/cidr-ranges.tf
- terraform/environments/core-network-services/firewall-rules/development_rules.json
Relates to https://github.com/ministryofjustice/modernisation-platform/issues/4797
> added Alpha VPN address range, alphabetised CIDR ranges

- environments/data-platform.json
Additional environments for test, preproduction and production
> New accounts for data-platform

- policies/networking/expected.rego
Included the changes to networking/expected.rego
> Adding missing file

- terraform/pagerduty/aws.tf
- terraform/pagerduty/member-services-integrations.tf
as per https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/integrating-alarms-with-pagerduty-with-slack.html
> Add jitbit prod pagerduty integration

- source/runbooks/reviewing-dependabot-prs.html.md.erb
Document is valid and no changed need to be made date updated
> review of dependabot document

- terraform/environments/bootstrap/delegate-access/policies.tf
https://mojdt.slack.com/archives/C01A7QK5VM1/p1692808560894709
> Adding ec2 instance connect to developer policy.

- terraform/environments/core-network-services/iam.tf
This PR does the following
* Replaces individual data calls for private hosted zones with single call fed by `for_each`
* Replaces individual zone strings in IAM resources for `dns` policy with `for` expression to filter output of new data call
In short, this PR will remove the need to create individual data calls for each new private zone we introduce.
> Dynamically populate list of private zones

- environments/data-platform.json
- terraform/environments/bootstrap/member-bootstrap/iam.tf
- terraform/environments/data-platform/data-platform-oidc.tf
* Update to v2.0.1 of `modernisation-platform-github-oidc-role` module.
* Remove wildcard from value in data-platform.json as not needed with new module version.
> Update OIDC role module version

- terraform/pagerduty/README.md
Fixing the ugly formatting in the on-call README that was introduced in the previous commit.
> Fixing ugly formatting

- terraform/environments/core-shared-services/ecr_repos.tf
Have added in the newly created accounts for data platform to ecr repo permissions
Also removed 2 repos that we will not be using moving forward
> add new data platform accounts to ecr repo permissions

- environments/mlra.json
> Add MLRA go live date

- environments/sprinkler.json
- scripts/git-create-environments.sh
Following on from https://github.com/ministryofjustice/modernisation-platform/pull/4945 this PR fixes with an issue with applying the additional reviewers to GitHub.
also added myself as a reviewer to Sprinker for testing purposes.
> 🐛 Fixing issues with adding additional reviewers function

- terraform/environments/core-shared-services/ecr_repos.tf
* Add ecr repos for reload-data-product and resync-unprocessed-files
> Added ecr repos

- scripts/git-create-environments.sh
Turning on debugging flag -x to help troubleshoot additional reviewers function.
> 🧪  turn on debugging flag -x

- environments/cooker.json
- environments/sprinkler.json
removing additional reviewer from cooker as failed to add and adding to sprinkler for further investigation
> Additional reviewers testing

- environments/cooker.json
- scripts/git-create-environments.sh
This PR adds the GitHub API response and as well removing additional reviewers from the application files ready to be re-added on the next PR.
> :construction: Add API response

- scripts/git-create-environments.sh
This PR initializes `additional_reviewers_json` as an empty JSON array at the beginning of the add_additional_reviewers function and also displays any GitHub API error messages.
> 🚧  Add bracket fix and error echo

- source/team/operational-processes.html.md.erb
add a line to explain secondary on call is available to support primary
> explain 2nd oncall engineer role

- source/user-guide/accessing-ec2s.html.md.erb
> 🐶 Update accessing-ec2s.html.md.erb

- terraform/environments/core-network-services/firewall-rules/preproduction_rules.json
- terraform/environments/core-network-services/firewall-rules/production_rules.json
- terraform/environments/core-network-services/firewall-rules/test_rules.json
previous PR this morning wasn't done with enough care and attention... 
so duplicated the rule names across multiple files which meant they just over-write 👎
> with apologies - getting the rule names right

- environments/opg-lpa-data-store.json
- policies/environments/expected.rego
https://github.com/ministryofjustice/modernisation-platform/issues/5006
> OPG acc creation.

- source/concepts/environments/instance-scheduling.html.md.erb
Updated the documentation to include RDS
> Documentation updated

- environments-networks/hmpps-development.json
> Additional Endpoints Request

- environments-networks/hmpps-development.json
Valid kinesis endpoints are:
```
"com.amazonaws.eu-west-2.kinesis-firehose",
"com.amazonaws.eu-west-2.kinesis-streams",
```
> Correct kinesis endpoint

- environments/ppud.json
- scripts/git-create-environments.sh
This PR fixes an issue with trailing commas when multiple additional reviewers are added. 
This also adds Nick and Umesh as deployment reviewers for the PPUD environments.
> Add PPUD Additional Reviewers

- scripts/git-create-environments.sh
This PR removes two debugging flags that were added for troubleshooting.
> 🧪  Remove Additional Debugging Flags

- source/runbooks/adding-collaborators.html.md.erb
Updated documentation following the additional_reviewers in code feature release (Ticket: https://github.com/ministryofjustice/modernisation-platform/issues/4761)
> 📝 Update Collaborators Documentation

- environments/delius-jitbit.json
Now live in production https://mojdt.slack.com/archives/C057P0R7KSR/p1695027322842199
> Update delius-jitbit go-live date

- environments/nomis.json
As agreed with Dave Elliot, a workaround to allow us to test Athena queries on load balancer logs.
> DSO-2150: Give DSO data-engineer role in nomis

- environments/ccms-ebs.json
As requested by @SahidKhan89 , this PR amends the support email value for CCMS-EBS
> Update CCMS EBS support address

- .github/ISSUE_TEMPLATE/new-story-template.yml
New Field added and mediatory fields set to true on key sections
> Changes to new form

- .github/ISSUE_TEMPLATE/new-story-template.yml
adding back a part of code that was removed as new form does not appear on the list to select it. i think this little bit of code removal is why
> new form not showing

- .github/ISSUE_TEMPLATE/new-story-template.yml
corrected error in code preventing the form from being shown
> corrected error

- environments/example.json
- source/user-guide/deploying-your-application.html.md.erb
fix line reference following an update to the application json file.
> 📝 Update deploying-your-application.html.md.erb

- environments/planetfm.json
As part of the ask channel request for planetfm i am adding migration role to the planetfm environment
> adding migration to planetfm

- environments-networks/hmpps-test.json
Add Additional VPC Endpoints for DPR PRoject
> HMPPS-TEST: Add Additional VPC Endpoints for DPR Project

- environments-networks/hmpps-preproduction.json
HMPPS-PREPROD: Add Additional VPC Endpoints for DPR Project
> HMPPS-PREPROD: Add Additional VPC Endpoints for DPR Project

- environments-networks/hmpps-production.json
HMPPS-PROD: Add Additional VPC Endpoints for DPR Project
> HMPPS-PROD: Add Additional VPC Endpoints for DPR Project

- terraform/environments/core-network-services/firewall-rules/fqdn_rules.json
- terraform/environments/core-network-services/firewall-rules/inline_fqdn_rules.json
FQDN request from the ask channel
Nick Buckingham
[1 hour ago](https://mojdt.slack.com/archives/C01A7QK5VM1/p1695909184183359)
Hello MOD Team
Can I have a domain whitelisted for port 80 inbound - [tlu.dl.delivery.mp.microsoft.com](http://tlu.dl.delivery.mp.microsoft.com/) ?
This is to allow our windows 2022 EC2 instances to download security updates.
> FQDN Request

- terraform/environments/core-shared-services/ecr_repos.tf
* Add ecr repo for the landing to raw lambda which will copy data to raw history.
> Added ECR repo

- terraform/environments/bootstrap/member-bootstrap/iam.tf
This pull request is in relation to the work being carried out for for [#observability-platform] x [#data-platform] to add the relevant iam policy permissions required for managed Prometheus and managed Grafana
> adding iam policies

- terraform/environments/bootstrap/member-bootstrap/iam.tf
adding a sso policy permission for managed grafana in the observability platform
> add an sso policy permission

- environments-networks/laa-production.json
- environments-networks/laa-test.json
- policies/networking/expected.rego
This Pr finishes off the Account creation for the Eric accounts as part of 
[new aws account request for ERIC#5070](https://github.com/ministryofjustice/modernisation-platform/issues/5070)
> Eric ram share setup

- terraform/environments/bootstrap/delegate-access/locals.tf
> Changed skip alias to cover apex-production

- terraform/environments/data-platform-apps-and-tools/mwaa-environments.tf
https://github.com/ministryofjustice/modernisation-platform/actions/runs/6453375619
Failing here.
> Fixing SCA

- terraform/environments/core-shared-services/ecr_repos.tf
adding ecr repo to hold lambda container for creating data product schema
> add ecr repo for data platform create schema lambda

- source/user-guide/quick-start-mac-guide.html.md
- source/user-guide/quick-start-mac-guide.html.md.erb
Add Mac Quick Start Guide for new joiners as part of firebreak sprint ticket https://github.com/ministryofjustice/modernisation-platform/issues/5099
> 📝 Add Mac Quick Start Guide

- environments/delius-core.json
as per environment request https://github.com/ministryofjustice/modernisation-platform/issues/5154
> Add delius-core test environment

- terraform/environments/core-shared-services/ecr_repos.tf
Creating a shared ECR repo for Apex application
> Shared ECR repo for Apex

- source/user-guide/running-terraform-plan-locally.html.md.erb
Reviewed https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/running-terraform-plan-locally.html#run-terraform-plan
> 🐶 Review Spaniel Updates

- terraform/pagerduty/member-services-integrations.tf
> Update member-services-integrations.tf: new slack channel for DPR

- terraform/environments/data-platform-apps-and-tools/environment-configuration.tf
This pull request updates DPAT production to point at Observability Platform Alpha
> 🧱 Update DPAT Production's Prometheus endpoint

- source/index.html.md.erb
> Change to top level modernisation platform documentation

- terraform/environments/core-shared-services/ecr_repos.tf
https://github.com/ministryofjustice/data-platform/issues/1657
> Add ECR repo for new data platform endpoint

- terraform/environments/core-shared-services/ecr_repos.tf
creating ecr repo to hold lambda container images for updating a data product schema
> add ecr repo for data platform update schema

- terraform/modernisation-platform-account/secrets.tf
Copied CP on circle ci secret management.
> Circle CI Secrets.

- terraform/environments/bootstrap/delegate-access/policies.tf
"Grants permission to get database structure metadata for auto-completion.	"
> SQL Workbench Autocompletion Permissions

- terraform/modernisation-platform-account/secrets.tf
* Add checkov/tfsec skips for `circleci` secretsmanager secrets
> Temporarily suppress SCA warnings

- source/user-guide/production-ready-checklist.html.md.erb
Following on from the slack conversation here
https://mojdt.slack.com/archives/C013RM6MFFW/p1698679637313349 adding details of what we would look for in an infrastructure review.
> Add section giving details of infrastructure review

- terraform/environments/core-shared-services/ecr_repos.tf
Creating an ECR repo for deploying the preview data end point
> Added preview data repo

- source/runbooks/changing-environment-details.html.md.erb
Daniel has asked for the following document to be reviewed
Daniel the Manual Spaniel
APP  [09:28](https://mojdt.slack.com/archives/C013RM6MFFW/p1699003712634609)
Hello :feet:, this is your friendly manual spaniel. I've found a page that is due for review:
- [Changing environment (AWS account) details](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/changing-environment-details.html) (yesterday)
i have reviewed the document and no changes need to be made as it it still valid and relevant
> Document Reviewed

- terraform/github/locals.tf
> New team member.

- terraform/environments/data-platform-apps-and-tools/eks-iam-policies.tf
- terraform/environments/data-platform-apps-and-tools/environment-configuration.tf
- terraform/environments/data-platform-apps-and-tools/kms-keys.tf
This pull request switches from a static list of resources to iterate over `openmetadata_target_accounts`
> 🔧 Update Open Metadata's list of assumable roles

- terraform/environments/observability-platform/managed-grafana.tf
> 🚚 Move data-platform-labs from Grafana admins

- source/team/team.html.md.erb
Adding Rich Green to Team Members page
> Adding Rich Green to team members page

- source/runbooks/duty-rota.html.md.erb
Update Duty rota with information on what to do if TVMSOC send an email
> This is to add actions required post emails from TVMSOC

- terraform/environments/core-shared-services/ecr_repos.tf
Need ecr to hold versions of daap-push-to-catalogue lambda container images
This creates the repository
> add data platform push-to-catalogue ecr

- terraform/environments/data-platform-apps-and-tools/environment-configuration.tf
Phase one: upgrade EKS
https://github.com/ministryofjustice/data-platform/issues/2180
N/A
Deployment to development
Change to tenant deployed resources
> 📌 Upgrade DPAT EKS cluster

- terraform/environments/data-platform-apps-and-tools/helm-charts.tf
Phase two: upgrade EKS platform components
https://github.com/ministryofjustice/data-platform/issues/2180
N/A
Deployment to development
Change to tenant deployed resources
Merge after https://github.com/ministryofjustice/modernisation-platform/pull/5435
> 📌 Upgrade DPAT EKS platform components

- source/runbooks/dos-attack.html.md.erb
- source/runbooks/enabling-shield-advanced.html.md.erb
- source/user-guide/creating-automated-terraform-documentation.html.md.erb
- source/user-guide/our-offer-to-you.html.md.erb
- source/user-guide/sustainability.html.md.erb
Daniel the Manual Spaniel 
Checked and there is only one reference that requires changing - raised in the team channel. Pushing the date change anyway.
- [ x] I have made corresponding changes to the documentation
- [ x] Plan and discussed how it should be deployed to PROD (If needed)
> Document review changes

- terraform/pagerduty/member-services-integrations.tf
Integrating CloudWatch Alarms with PagerDuty and Slack
Change slack channel ID
No
> NCAS dev: update slack channel ID

- terraform/environments/core-network-services/iam.tf
Can't filter firewall log events
Allows filtering of firewall log events
Will work fine once we have permission 👍 
No
Simples
> add FilterLogEvents permission

- terraform/environments/data-platform-apps-and-tools/eks-cluster.tf
Updates DPAT's EKS module to 19.19.1
N/A
N/A
No, tenant change
Supersedes https://github.com/ministryofjustice/modernisation-platform/pull/5453
> 📌 Update DPAT EKS module

- terraform/github/locals.tf
Added Aaf as github user to access test environments - sprinkler and cooker
> added github user

- source/concepts/environments/backups.html.md.erb
- source/runbooks/adding-a-new-team-member.html.md.erb
- source/runbooks/removing-a-team-member.html.md.erb
- source/runbooks/terraform.html.md.erb
- source/user-guide/how-to-use-shared-kms-keys.html.md.erb
As per the slack call from Daniel the manual spaniel
Updating the dates
N/A
> Daniel the manual spaniel reviews

- source/runbooks/cloudwatch-networking-alarms.html.md.erb
- source/runbooks/manage-an-incident.html.md.erb
Manual Spaniel Updates
Minor update made to the incident reporting doc including adding link to aws support slack channel
No updates made to the networking alarms page
No
- [ x] I have made corresponding changes to the documentation
> update to incident process and network alarm docs

- environments/delius-core.json
> Add team to Delius-Core env

- environments/planetfm.json
All app owner access to be able to configure machines & track progress
AWS login UI now shows new planetfm environments
Should just work :P 
No
> add application owner access to planetfm

- environments/analytical-platform-management.json
> 🛂 Update `analytical-platform-management`

- environments/analytical-platform-data-engineering.json
> 🛂 Update `analytical-platform-data-engineering`

- environments/analytical-platform-data.json
> 🛂 Update `analytical-platform-data`

- environments/analytical-platform-landing.json
> 🛂 Update `analytical-platform-landing`

- environments/analytical-platform.json
> 🛂 Update `analytical-platform`

- environments/data-platform-apps-and-tools.json
> 🛂 Update `data-platform-apps-and-tools`

- environments/data-platform.json
> 🛂 Update `data-platform`

- .github/workflows/scheduled-baseline.yml
- .github/workflows/scorecards.yml
- .github/workflows/terraform-member-environment.yml
Added Slack failure notification from missing workflows
(https://github.com/orgs/ministryofjustice/projects/17/views/4?pane=issue&itemId=38496837)
Slack notification gets sent out on when push to main fails
Manual run of `scheduled-baseline.yml `
> added slack failure notification

- environments/cdpt-chaps.json
- policies/environments/expected.rego
https://github.com/ministryofjustice/modernisation-platform/issues/5539
Creates dev,preprod and prod accounts for cdpt-chaps
PR ready to run new environment workflows
> create cdpt-chaps accounts

- .github/workflows/scheduled-baseline.yml
- .github/workflows/terraform-member-environment.yml
Reverts ministryofjustice/modernisation-platform#5561
> Revert "added slack failure notification"

- architecture-decision-record/0028-expand-the-scope-of-the-platform.md
- architecture-decision-record/README.md
> Add ADR for change of platform scope

- terraform/environments/core-shared-services/ecr_repos.tf
Migrating cdpt-chaps to modernisation platform
> Add ecr for cdpt-chaps

- environments/cdpt-chaps.json
> Add OIDC role for CHAPS

- .github/workflows/email-requester-onboarding-close.yml
Replacement of previous version with a corrected actions checkout reference
> Corrected line 14 reference

- source/runbooks/enabling-shield-advanced.html.md.erb
Quick fix for a stale link - pointed it at the correct position for the local we're interested in.
> Updated docs for AWS shield

- .github/labeler.yml
- .github/workflows/labeler.yml
Update of label config following upgrade to version 5
updates file structure to match v5
This is untested. 
No
- [X ] I have performed a self-review of my own code
> Update Labeler Config for version 5

- .github/workflows/notify-user-new-environment-created.yml
Comment
#3451 
Sends an auto email on close
Via act
Impacts no other application
- 
Will be tested with a sample issue
> Corrected github.issues.create to make it github.rest.issues.create

- .github/workflows/notify-user-new-environment-created.yml
Reverts ministryofjustice/modernisation-platform#5707
> Revert "Update notify-user-new-environment-created.yml"

- terraform/environments/data-platform-apps-and-tools/environment-configuration.tf
Updates DPAT EKS's Prometheus to use the new role format
It's not a problem
It hasn't, but I'm just updating names of things
No, it's a tenant configuration change
> ⚙️ Update Data Platform's Observability Platform configuration

- .github/workflows/notify-user-new-environment-created.yml
#3451 
Writes a message into the log to let the user know it's complete and includes instructions
See below
Impacts no other services
- 
Will be tested by closing an on boarding call and making sure the message appears
> Feature/notify onboarders #3451

- terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf
Fixing tfsec errors
It suppresses the tfsec error message, as the encryption when integrating SNS with PD is not possible.
The checks should pass now.
No.
> Fixing tfsec errors

- terraform/modernisation-platform-account/iam.tf
> iam-superadmin-mod-version-change

- environments/cica-copilot.json
- policies/environments/expected.rego
AWS Bedrock access for the CICA Copilot
Creates a development environment to get access to AWS Bedrock for the CICA Copilot
> Acc aws bedrock access for cica copilot

- environments-networks/cica-development.json
- policies/networking/expected.rego
> Add networking for copilot

- environments/cica-copilot.json
Update bedrock access from developer to sandbox for copilot
> Update access from developer to sandbox

- source/concepts/environments/architecture.html.md.erb
- source/concepts/environments/security.html.md.erb
- source/runbooks/adding-wider-connectivity.html.md.erb
- source/runbooks/runbook.html.md.erb
- source/user-guide/member-read-only-core-accounts.html.md.erb
Daniel our spaniel popped up with some reviews needed
Corrected the dates so they will pop up in 6 months.
> Amending dates and adding a comment to one piece of documentation

- source/user-guide/running-terraform-plan-locally.html.md.erb
Terraform backend state locking for Modernisation Platform Environments customers.
Makes it clearer how to assume the backend role
Updated the docs based on user feedback
> Update docs about running a local plan

- .github/workflows/notify-user-new-environment-created.yml
N/A
It doesn't fix a problem. It just improves things a bit
M/A
No
> Minor improvements to user notification action

- environments/delius-core.json
Needed to support automation for DBAs
> Rename delius-core env application tag

- architecture-decision-record/0029-how-we-deploy-shared-active-directory-controllers.md
- architecture-decision-record/README.md
https://github.com/ministryofjustice/modernisation-platform/issues/5736
https://github.com/ministryofjustice/modernisation-platform/issues/5737
Completes an ADR for our approach to Managed Active Directory
N/A
N/A
N/A
> ADR 29 - AWS Managed Microsoft AD

- source/concepts/environments/auto-nuke.html.md.erb
- source/concepts/sdlc/testing-strategy.html.md.erb
- source/getting-help/index.html.md.erb
- source/runbooks/joining-the-team.html.md.erb
- source/user-guide/automated-patching.html.md.erb
Reviewed documents flagged by Daniel the spaniel, no revisions were necessary to the content.
> Revised the review dates to keep documentation up-to-date

- source/team/team.html.md.erb
update team review date following https://github.com/ministryofjustice/modernisation-platform/pull/5805 on thursday.
> Update team Review date 

- source/concepts/sdlc/patching.html.md.erb
Daniel the manual spaniel review
Amended date
> Amended review date of patching document

- terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf
This is to finish the implementation of the https://github.com/ministryofjustice/modernisation-platform/issues/2722 issue.
This also updates the lambda version, now that there is a new release.
This change allows for monitoring the instance scheduler lambda's behaviour with cloudwatch and reporting to SNS and then to PagerDuty and [#modernisation-platform-low-priority-alarms](https://moj.enterprise.slack.com/archives/C02PFCG8M1R) slack channel. The alarms will go off if the scheduler finishes with errors or if it does not run.
The opposite (scheduler run successfully) was manually tested with cloudwatch changes.
The tf plan run clean locally as well and all PR checks should pass.
Deployment through the pipeline apply. No impact on other services.
> Introducting cloud watch alarms for the instance scheduler

- source/user-guide/creating-resources.html.md.erb
- source/user-guide/integrating-alarms-with-pagerduty-with-slack.html.md.erb
Reviewed documents flagged by Daniel the spaniel, no revisions were necessary to the content.
Updated the review date
> Amended document review dates

- terraform/environments/bootstrap/delegate-access/policies.tf
Directory Management users will need to connect to a windows service to administer a Managed Microsoft Active Directory service cluster. 
#5810 
Allows users to start, list, and get SSM connections
Will be tested through deploy to Sprinkler first
No
> Expand directory management policy

- collaborators.json
Adds new Equip support staff as requested by Equip team
> added new equip user

- environments/cdpt-chaps.json
Need to give someone outside our team read only access to our AWS resources.
Adds them as an additional reviewer.
> Add additional user for Chaps

- source/runbooks/accessing-aws-accounts.html.md.erb
testing artifact and deploy pages v4
> 🧪 testing artifact and deploy pages v4

- environments/electronic-monitoring-data.json
- policies/environments/expected.rego
Create new environment for electronic monitoring
Creates a development, preproduction and production environments to get access to electronic monitoring
> Account creation for electronic monitoring

- environments-networks/hmpps-development.json
- environments-networks/hmpps-preproduction.json
- environments-networks/hmpps-production.json
- policies/networking/expected.rego
Adding RAM Share for electronic monitoring
> Added networking for electronic-monitoring

- source/team/team.html.md.erb
Issue Ref 5380.
As per title.
Not Applicable
No
> Adds myself (Mike Reid) to the team list page.

- source/concepts/sdlc/sandbox-testing-environments.html.md.erb
- source/runbooks/running-emergency-patching.html.md.erb
Reviewed documents flagged by Daniel the spaniel
Docs are up-to-date
> Updated documents scheduled for a review

- terraform/github/locals.tf
Issue 5380.
As per issue, this adds Mike Reid to the engineers list.
Not Applicable
Not Applicable
> Adds Mike Reid to the engineers list.

- environments/data-platform-compute.json
- policies/environments/expected.rego
Create new environment for data platform compute
Creates a development and production environments to get access to sagemaker for data platform compute
> Account creation for data platform compute

- environments/data-platform-compute.json
single-sign-on failed because for_each supports maps and sets of strings
Updated json file inorder to match pass the single-sign-on job
> Updated data-platform-compute

- environments/maat.json
> LAWS-3579: Add OIDC permissions for GHA in repos

- terraform/environments/bootstrap/member-bootstrap/iam.tf
Ticket  - https://github.com/ministryofjustice/modernisation-platform/issues/5678
Creates the role needed, will still need to deploy it, edit the templates file and maybe change permissions.
No.
> Creation of eu-central-1 role

- terraform/pagerduty/locals.tf
Adds Sukesh to the Pagerduty account
> Added Sukesh to Pagerduty

- terraform/environments/core-shared-services/ecr_repos.tf
As part of the migration of the maat api from LZ to MP, a ECR needs to be created. Instructions used hee: https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/add-an-ecr-for-docker-images.html#how-to-add-an-ecr-for-shared-docker-images
N/A
N/A
> LAWS-3581: Adding maat-api ECR repo in core-shared-services/ecr-repos.tf

- source/team/ways-of-working.html.md.erb
Adds a new section under "Ways of Working" that adds some basic criteria for reviewing PRs to existing supported modules.
This question arose yesterday as to what criteria a member of the team would apply when reviewing a change to an existing module that added a new feature or amended/removed existing features. This addition is meant to provide some clarification & guidance on this matter.
> Suggested Review Criteria for Module Feature Changes.,

- environments/data-platform-compute.json
Ref a bug that @sukeshreddyg had fixed but had subsequently been replaced a formatter action with the existing code
See slack thread - https://mojdt.slack.com/archives/C013RM6MFFW/p1704463359742849
> Fixes an issue whereby the GH slug wasn't correctly formatted to take account of more than one team per env.

- .github/workflows/notify-user-new-environment-created.yml
(https://github.com/ministryofjustice/modernisation-platform/issues/4998)
Fixes code scanning vulnerability - https://github.com/ministryofjustice/modernisation-platform/security/code-scanning/1057
Created a TEST issue with "onboarding" label. Once the fix is merge, I'll close the issue which will trigger the workflow.
> added top-level permissions to fix code scanning vuln

- .github/workflows/code-scanning.yml
Trivy was not told which directorys to start with and also needed to remove the references to tfsec
added code section to tell trivy where to scan and told it to scan from the base repo folder and also removes the tfsec reference
> Trivy update

- terraform/environments/bootstrap/delegate-access/collaborators.tf
creates fleet manager role by attaching fleet manager policy.
creates a fleet manager role
> Added fleet manager role

- .github/workflows/scheduled-baseline.yml
Prevent SSO API limits being hit.
Reduces the number of API calls by running less jobs at once
Previous change worked before additional SSO sets were added.
Yes it should reduce failures.
> Reduce number of parallel jobs

- source/runbooks/creating-accounts-for-end-users.html.md.erb
Amended spelling mistake and changes to code owner text
> Additional changes to correct a spelling and amend owner-name comments

- terraform/environments/bootstrap/delegate-access/policies.tf
Update fleet-manager policy
Updates existing fleet-manager policy
> Updated fleet-manager policy

- environments/hmpps-oem.json
Add repo to github-oidc-team-repositories for hmpps-oem account
cc @ranbeersingh1
> Add hmpps-delius-operational-automation as oidc repo

- environments/data-platform-apps-and-tools.json
- environments/data-platform-compute.json
- environments/data-platform.json
Trims the codeowners for `data-platform-*` environments in the `modernisation-platform-environments` repository.
> updated data platform codeowners

- environments/delius-mis.json
- policies/environments/expected.rego
Create a new environment for **delius-mis** 
#6031 
Creates a development, test, preproduction and production environments to get access to delius-mis.
> New environment request for delius-mis

- architecture-decision-record/0030-cross-environment-network-access.md
- architecture-decision-record/README.md
#5632 
Creates ADR guiding customers towards cloud-native approaches
N/A - docs
N/A - docs
It's an ADR.
> ADR on cross environment network access

- architecture-decision-record/0030-cross-environment-network-access.md
- architecture-decision-record/README.md
Following discussion with team technical architect, ADR 30 is accepted.
> Set ADR30 as accepted

- terraform/environments/core-shared-services/ecr_repos.tf
[{Please write here}](https://dsdmoj.atlassian.net/browse/LAWS-3613)
> Add ECR for MAAT

- terraform/environments/core-shared-services/iam.tf
IAM role and policy to invoke lambda functions #5449 
Event bridge scheduler to trigger lambda functions
> IAM role and policy for lambda invoke

- terraform/environments/core-shared-services/ecr_repos.tf
> create new delius core ecrs

- terraform/environments/core-shared-services/ecr_repos.tf
> add extra delius core ECRs

- terraform/environments/core-network-services/route53.tf
New Domain Request from the ask channel for cdpt-chaps
Hi, please can I get a new domain added for cdpt-chaps production. The domain is [correspondence-handling-and-processing.service.justice.gov.uk](http://correspondence-handling-and-processing.service.justice.gov.uk/)
> New Domain Request

- terraform/modernisation-platform-account/secrets.tf
https://github.com/ministryofjustice/modernisation-platform/issues/4999
Adds a KMS key, and uses this KMS key to encrypt the secrets in the MP account
Using the same policy as used in other MP applications of KMS, this KMS key will be usable freely by principals in the MP account, and to decrypt resources by MP OU members
If the KMS policy is too restrictive, there may be an interruption to secrets access while it is relaxes
> Use KMS key to encrypt MP account secrets, removed tfsec and checkov exclusions

- terraform/environments/core-network-services/route53.tf
Arranged application zones in alphabetical order
> Arranged application zones in alphabetical order

- .github/workflows/terraform-single-sign-on.yml
https://github.com/ministryofjustice/modernisation-platform/issues/5659
Adds a new workflow to run the new 'single-sign-on' TF folder in the MP repo.
> add sso workflow

- terraform/single-sign-on/data.tf
- terraform/single-sign-on/outputs.tf
This can be obtained from the permission set.
> Data for developer not needed

- terraform/environments/bootstrap/secure-baselines/main.tf
- terraform/modernisation-platform-account/baselines.tf
https://github.com/ministryofjustice/modernisation-platform/issues/5635
`modernisation-platform-terraform-baselines
` version upgrade
> version bump from 6.2.2 to 6.3.0

- environments/delius-core.json
- environments/delius-mis.json
- Assign DBAs the developer role in delius-core-test and delius-mis accounts.
- Assign Unlink the developer role in the delius-core-test account.
> Add DBAs and Unlink to delius-core-test

- terraform/modules/vpc-nacls/main.tf
https://github.com/ministryofjustice/modernisation-platform/actions/runs/7780760156/job/21213997942
Adds ignores.
No
No
> Ignore CKV_AWS_231

- environments/analytical-platform-data.json
This is in reference to https://github.com/ministryofjustice/data-platform/issues/2451 specifically.
This PR assigns a user permission level created [here](https://github.com/ministryofjustice/modernisation-platform/pull/6120).
This is to enable the functionality for PowerBI for a limited set of users.
This has been manually tested 
This should not impact other systems.
> Adding PowerBI Access level for users.

- .github/workflows/code-scanning.yml
- .github/workflows/terraform-static-analysis.yml
- .trivyignore.yaml
New functionality has been added to the trivy scanning now and we need to test that it is working as expected also i have removed the ignore_falures: true as this was ignoring all errors and producing a false positive
Add back in trivy functionality and also adds in the new trivy ignore file that will be use to ignore trivy errors that we want to ignore
This has been tested locally on my laptop with a local install of trivy against the modernisation platform repo
> Test of new trivy scan

- .trivyignore.yaml
Tidy up of codes in the misconfigurations section. Now in order
> Tidying up the orders of the codes in the misconfigurations section

- .github/workflows/terraform-static-analysis.yml
This is a continuation of a previous PR to investigate trivy upload functionality for terraform static code analysis and also a bit of code cleanup
removes code that is no longer required in one section as it does not need to upload to github and changes the hash code for the full scan as i am testing an if statment
> Code Clean up and hash update

- terraform/templates/modernisation-platform-environments/platform_providers.tf
https://github.com/ministryofjustice/modernisation-platform/issues/6035
Updates our new account templates to include this new provider
Tested through sprinkler
Created data calls through Terraform in sprinkler and tested to see that data structures were populated
No
> Add sso-readonly provider to platform_providers template

- collaborators.json
Pen test of electronic-monitoring-data env is now completed.
> Remove external pen tester access

- terraform/environments/bootstrap/delegate-access/policies.tf
Reverts ministryofjustice/modernisation-platform#6200
> Revert "Rewriting powrbi policy to narrow it down to specific permissions."

- terraform/environments/bootstrap/single-sign-on/main.tf
Reverts ministryofjustice/modernisation-platform#6202
> Revert "Remove SSO account assignment"

- terraform/pagerduty/member-services-integrations.tf
> LAWS-3612: Add Slack integration for maat nonprod and prod MP alerts

- terraform/environments/bootstrap/delegate-access/policies.tf
Updated developer policy to use resource based access for deleting specific suppressed email address.
Updated developer policy
> Updated developer policy

- environments/oasys.json
This issue was raised in the [ask channel](https://mojdt.slack.com/archives/C01A7QK5VM1/p1707912431092949)
Provides developer access to oasys-operator github team
> Provides developer access to oasys-operator github team

- .github/workflows/terraform-static-analysis.yml
part of the trivy testing was to try an upload the results via a sarif file this is no longer required as the functionality is not possible
This PR removes the part of the workflow that is failing at the moment the upload documents part
> removed document upload

- terraform/environments/core-shared-services/ad-fixngo.tf
Follow on to https://github.com/ministryofjustice/modernisation-platform/pull/6224
Enables first Domain Controller
Tested as far as possible in environments repo in a member account
No
Mod Platform engineers aware of solution: Ewa Stempel, David Sibley, Dave Elliot
> DSOS-2615: enable ad-azure-dc-a EC2 in core-shared-services-production

- terraform/environments/core-shared-services/ad-fixngo.tf
Static analysis is failing for core-shared-services
Fixes tflint issue.  Ignores trivy error, reasoning discussed in slack thread with Ewa
Hopefully the PR will trigger re-run of static analysis
No
> DSOS-2615: fix static analysis for fixngo domain controllers

- .trivyignore.yaml
No issue; addresses SCA checks
Ignores vulnerabilities of little/no significance to us
> Apply SCA fixes

- terraform/environments/core-network-services/cidr-ranges.tf
- terraform/environments/core-network-services/firewall-rules/development_rules.json
- terraform/environments/core-network-services/firewall-rules/production_rules.json
Resolves #6517
Adds firewall rules
Ran local plan
> Add ranges and rules for syslog traffic to cortex accounts

- terraform/environments/bootstrap/delegate-access/iam.tf
- terraform/environments/bootstrap/delegate-access/locals.tf
- terraform/environments/bootstrap/member-bootstrap/iam.tf
- terraform/environments/bootstrap/member-bootstrap/locals.tf
- terraform/environments/bootstrap/single-sign-on/locals.tf
Removed unused resources/locals from TF files and migrate iam account alias resource from delegate access to member bootstrap. #3053 
Moves iam alias resource from delegate access and removes unused resources from tf files
tested this on sprinkler
> Cleanup bootstrap

- terraform/environments/bootstrap/member-bootstrap/iam.tf
> add elastiache iam actions for MemberInfrastructureAccess

- source/runbooks/manage-an-incident.html.md.erb
- source/user-guide/add-an-ecr-for-docker-images.html.md.erb
- source/user-guide/certificate-import-windows.html.md.erb
- source/user-guide/getting-aws-credentials.html.md.erb
- source/user-guide/how-to-configure-dns.html.md.erb
Document review dates had expired
Confirmed that content is still accurate
> Increment document review dates

- terraform/environments/bootstrap/single-sign-on/policies.tf
As discussed [here](https://mojdt.slack.com/archives/C01A7QK5VM1/p1708439468218639), this PR re-adds a permission removed in [this PR](https://github.com/ministryofjustice/modernisation-platform/pull/6256/).
> re-added Glue permission not covered by wildcard

- terraform/github/locals.tf
Added my GitHub user name to engineers list 
This gives me access to AWS via AWS SSO
Checked spelling and formatting and all looks good
no
- [ n/a] I have made corresponding changes to the documentation
- [ n/a] Plan and discussed how it should be deployed to PROD (If needed)
> added my GitHub user name to Update locals.tf

- source/team/ways-of-working.html.md.erb
Amended the update date
No changes needed
> Date amended following a note from Daniel the manual spaniel

- collaborators.json
Toby Petty has left MoJ, Kaleb Sofer is replacing as developer on environment
> Remove colleague that has left MoJ and add replacement

- environments/planetfm.json
Request - https://moj.enterprise.slack.com/archives/C01A7QK5VM1/p1709050812647339
Request - https://moj.enterprise.slack.com/archives/C01A7QK5VM1/p1709050812647339
Removes migration level access
No
> Remove migration level from planetfm.

- source/runbooks/creating-accounts-for-end-users.html.md.erb
See #6338 - this PR adds the corresponding documentation to the account request runbook.
-
-
-
-
> Update documentation for the account request runbook for #6338

- terraform/modernisation-platform-account/iam.tf
Changed reference to release for super admin module to add Kudzai to super admin
> new release for super admin module

- terraform/github/locals.tf
Removed Aaf and added Katie Watson to the mp git hub team
> Removed Aaf and added Katie Watson to the mp git hub team

- environments/delius-core.json
> Assign developer role to unlink group

- environments/delius-core.json
Add delius-core github_aciton_reviewer to test new funcitonally released in PR https://github.com/ministryofjustice/modernisation-platform/pull/6338
Pre PR 6338 GitHub API payload:
```
Creating environment delius-core-test...
DRY Run Payload: {"reviewers": [{"type":"Team","id":5036364},{"type":"Team","id":7873223},{"type":"Team","id":2769242}]}
```
Post PR 6338 GitHub API payload: 
```
Creating environment delius-core-test...
DRY Run Payload: {"reviewers": [{"type":"Team","id":5036364}]}
```
> ✨  Add GitHub Reviewer to delius-core

- terraform/environments/bootstrap/secure-baselines/main.tf
- terraform/modernisation-platform-account/baselines.tf
Failing SCA, this should fix it here - 
https://github.com/ministryofjustice/modernisation-platform/actions/runs/8092247986
New release of module with fixes in.
> Feature/baseline bump 6.5.1

- architecture-decision-record/0030-cross-environment-network-access.md
- architecture-decision-record/0031-llms-will-be-hosted-on-the-analytical-platform.md
- architecture-decision-record/README.md
Following a meeting with the service owners of the Cloud, Modernisation and Analytical Platforms.
See ADR for details.
> Add ADR for LLM hosting location

- source/user-guide/creating-environments.html.md.erb
See #6338 for context - this PR adds the documentation to the documentation/modernisation platform guide.
> Update creating-environments.html.md.erb to add documentation to the guide for #6338

- .github/workflows/check-inactive-collaborators.yml
- scripts/internal/collaborators-inactivity-notification/check_inactive_users.sh
- scripts/internal/collaborators-inactivity-notification/notification.py
#6145 
This PR needs for automating the process of notifying inactive collaborator users
> Add workflow for notifying inactive collaborators

- source/index.html.md.erb
We are trying to capture user interactions with our users pages so we have created a google analytics account and now we need to add in some code to our pages for the information to be captured
This PR added in the code required we have only added it to one page so far as a test but will need to add it to all pages once we have verified that it is working
i have tested this locally on my docker client and the added code does not break the pages and i can see it's in the write places  bu using the developer tools
> adding google analytics

- scripts/internal/collaborators-inactivity-notification/notification.py
Added functionality to retrieve email addresses from JSON files and remove duplicate entries. #6145 
This PR enhances the notification.py script by adding functionality to retrieve email addresses from JSON files and remove duplicate entries. This improvement helps streamline the email notification process by ensuring that each user receives only unique emails.
> Added Functionality: Retrieve Emails from JSON Files and Remove Duplicates

- source/index.html.md.erb
- source/team/roadmap.html.md.erb
- source/user-guide/certificate-import.html.md.erb
As part of data collection into google analytics we have now refined the tags code and need to add it to a few more pages for testing
Add refined code to the head of three user guid pages
run locally in a docker container no issues found
> changes to google tags

- .github/workflows/check-inactive-collaborators.yml
- scripts/internal/collaborators-inactivity-notification/notification.py
Implemented GOV.UK Notify integration to enhance notification capabilities #6145 
This PR addresses the need for enhanced notification functionality by integrating GOV.UK Notify into the script.
> Added GOV.UK Notify Integration for Enhanced Notification Functionality

- source/user-guide/creating-networking.html.md.erb
- source/user-guide/deploying-your-infrastructure.html.md.erb
- source/user-guide/environment-diagram.html.md.erb
- source/user-guide/obtaining-deployment-credentials.html.md.erb
- source/user-guide/wider-moj-connectivity.html.md.erb
Amendments (none) based on the slack message from the manual spaniel.
> Documentation changes based on the slack message from Daniel

- terraform/environments/bootstrap/single-sign-on/policies.tf
> add missing comma

- environments/delius-core.json
> Update delius-core.json - new oidc repo

- terraform/environments/core-shared-services/ecr_repos.tf
- terraform/modules/app-ecr-repo/main.tf
Part 1/2
Renaming ECRs - remove them first, second PR will add them back
> Remove ECRs
