terraform/environments/core-shared-services/ecr_repos.tf, terraform/modules/app-ecr-repo/main.tf
=> Add ECRs back for delius-core

source/runbooks/dos-attack.html.md.erb, source/team/operational-processes.html.md.erb
Reviewed documents flagged by Daniel the spaniel
=> Amended document review dates 

environments/data-platform-apps-and-tools.json
Adds `ministryofjustice/analytical-platform-jml-report` to DPAT's OIDC so we can publish to Core Shared Services ECR
Its not a problem
N/A
No
=> :octocat: Add `ministryofjustice/analytical-platform-jml-report` to DPAT's OIDC

terraform/environments/core-shared-services/ecr_repos.tf
Allows DPAT's OIDC CICD role to push to JML ECR
N/A
N/A
No
=> 🛂 Add DPAT to JML ECR push prinicpals

environments/analytical-platform-ingestion.json, policies/environments/expected.rego
Create new analytical platform ingestion environment as per issue https://github.com/ministryofjustice/modernisation-platform/issues/6364
=> Create new Analytical Platform Ingestion environment 

terraform/environments/core-shared-services/ecr_repos.tf
https://mojdt.slack.com/archives/C01A7QK5VM1/p1710251178430069
Adds permission to IAM policy for `data-platform-apps-and-tools-development`
Tested manually
N/A - PR backfills a manual change
=> Add account permission to ECR repo

environments/analytical-platform-ingestion.json
Is part of https://github.com/ministryofjustice/data-platform/issues/3501
Add Analytical Platform Ingestion repositories to account OIDC
N/A
N/A
N/A
=> 🛂 Add Analytical Platform Ingestion repositories to account OIDC

terraform/environments/bootstrap/secure-baselines/providers.tf
As documented here: https://mojdt.slack.com/archives/C013RM6MFFW/p1710322520089769
Tells provider to use adaptive mode which will hopefully make it retry making API calls rather than erroring once a set limit has been reached.
It's not - I'm not sure of another way to test it locally as it's the bootstrap code. My plan would be to monitor how well this performs when running the worflow.
=> try setting secure baseline provider to adaptive mode

terraform/environments/bootstrap/single-sign-on/policies.tf
This is to address an [ask channel user request](https://mojdt.slack.com/archives/C01A7QK5VM1/p1708004807789509).
=> Allowing iam:PassRole for ECS in developer role

terraform/environments/core-shared-services/ad-fixngo.tf
The devtest DCs are all working so setting up prod ones one at a time.
Commissions the first prod FixNGo DC 
Same code as devtest which is working
No
=> DSOS-2635: enable first prod fixngo DC

source/concepts/environments/instance-scheduling.html.md.erb, source/getting-help/index.html.md.erb
As per title, this ups the reviewed date for the two pages in the user guide.
=> Reviews of user guide pages.

source/index.html.md.erb, source/runbooks/revoke-network-access.html.md.erb
This is a  list of the instructions showing how to restrict network access if we are being attacked. NOTE it is listed with the console changes needed NOT the terraform code changes. The main reason for this are so the code is not amended and can  be re-used to get everything back to the way it was.
Once approved I will amend the readme in the modernisation-platform code.
=> Instructions for revoking network access

terraform/environments/digital-prison-reporting/iam.tf
iam:CreatePolicyVersion
https://app.circleci.com/pipelines/github/ministryofjustice/digital-prison-reporting-domains/903/workflows/b1cd273d-9605-4d3a-9856-ada2c757f0ec/jobs/2589
Allows Circle CI Pipeline to pass
https://app.circleci.com/pipelines/github/ministryofjustice/digital-prison-reporting-domains/903/workflows/b1cd273d-9605-4d3a-9856-ada2c757f0ec/jobs/2589
Tested on DEV/Sandbox
N/A
=> Add CreatePolicyVersion

terraform/modules/firehose/main.tf
=> Fixes errors with underscores in names.

terraform/environments/core-network-services/firehose.tf
See above. The wrong key names for the non-prod secrets were used. Also tightened up the condition so that it works.
=> Fixes issue whereby the non-prod secrets were not being correctly referenced.

source/concepts/sdlc/user-workflow.html.md.erb
Document for review popped up. No changes needed currently.
=> Changed review date

source/runbooks/creating-accounts-for-end-users.html.md.erb
Updated run book stating how requester will get notified of account creation
PR has the details on how customer will get notified
=> Update to account creation runbook - Informing Customer

terraform/environments/core-network-services/firehose.tf
This renames the firewall inspection log module for extensibility reasons. Part 2 will be the removal of the moved blocks.
See above.
=> Module renaming. Part 1 of 2.

environments/analytical-platform-compute.json, policies/environments/expected.rego
New account creation. 
Has isolated-network setting in there
=> New account for analytical-platform-compute

terraform/environments/core-network-services/firehose.tf
This removes the moved blocks as they are no longer required.
The module names have been changed using the moved blocks. These are now no longer required.
Local plan is clean.
=> Refactor Module Names - Part 2 of 2

environments/analytical-platform-compute.json
=> Missing code at then end caused an error - re-run needed

collaborators.json
We've recently had Kaleb Sofer leave our team and Madhu Kadiri has joined. I have therefore replaced the names in the collaborators.json
=> remove and add collaborator

environments/dacp.json, environments/tipstaff.json, environments/wardship.json
I am updating the go-live dates for my environments
-
-
No
=> update go live dates for dacp, tipstaff, wardship environments

environments/ncas.json, environments/pra-register.json
Add go-live dates for two environments.
=> Add go live dates for ncas and pra-register

source/runbooks/manage-an-incident.html.md.erb
Add in additional guidance to add emphasis on updating the status page
=> Update status page guidance

README.md
removing modernisation-platform-infrastructure-test from readme as repo now archived.
=> ⚰️ Remove modernisation-platform-infrastructure-test

environments-networks/hmpps-development.json, environments-networks/hmpps-preproduction.json, environments-networks/hmpps-production.json, environments-networks/hmpps-test.json, policies/networking/expected.rego
New account networking stage configuration (Oasys-National-Reporting)
=> Oasys-National-Reporting Account Creation Networking Stage

collaborators.json
Updating Madhu's access to match the MoJ engineers access
Gives them the same permissions as other developers
Visual check of the json.
No.
n/a
=> Update collaborators.json for electronic monitoring

terraform/environments/core-security/firehose.tf, terraform/environments/core-security/locals.tf, terraform/environments/core-security/secrets.tf, terraform/modules/vpc-hub/outputs.tf
#6163 
VPC flow log data can be shared with SecOps.
Local plan.
=> Creates firehose stream resources for the core security VPC flow log

terraform/environments/core-security/firehose.tf
=> Amended length of name for the firehose resource_prefix

terraform/environments/core-vpc/locals.tf, terraform/environments/core-vpc/secrets.tf, terraform/environments/core-vpc/vpc.tf
This tidies up a number of the secrets data & locals to reduce the number and so make admin simplier.
See above. Note that this is purely a cosmetic change and none of the underlying resources will be updated.
This code has been applied elsewhere (e.g. the transfers for core-logging) and this is reusing it.
=> Refacte core vpc firehose

collaborators.json
Madhu doesnt need access to the em prod env
Removes the access
n/a
n/a
n/a
=> Remove em prod access for Madhu

environments-networks/hmcts-development.json
Adding vpc endpoints to allow ecs to access ecr and disable public ip addresses on ecs.
=> Add vpc endpoints to HMCTS dev env

environments-networks/hmcts-development.json
=> Add secrets manager to additional_endpoints on hmcts dev

environments-networks/hmcts-development.json
=> add elasticloadbalancing to hmcts dev

terraform/environments/core-vpc/firehose.tf
=> Fixes two bugs in the firehose stream for route53 resolver log transfers.

terraform/environments/core-logging/firehose.tf, terraform/environments/core-network-services/firehose.tf, terraform/environments/core-security/firehose.tf, terraform/environments/core-shared-services/firehose.tf
Following some updates to the firehose module, this has a number of changes that both force the source modules to update plus a couple of bug fixes.
=> Forces updates from the source module.

environments/cdpt-ifs.json
Golive date needed
Golive date added
/
no
/
=> added golive date

terraform/environments/core-shared-services/ad-fixngo.tf
Following discussion with MP tech architects, these DCs will need to be moved to a different subnet which is routable to Moj Official ranges.
Deleting the EC2 instances for now. They will be rebuilt at a later date in a new subnet.
N/A
No
=> DSOS-2635: mothball FixNGo DC

environments/moj-network-operations-centre.json
As part of Migrating NOC AWS accounts to Modernisation Platform
[#6416](https://github.com/ministryofjustice/modernisation-platform/issues/6416) i am creating a pr so we can import the account into modernisation platform
code added to the accounts section for the production account
=> Adding NOC production account

source/user-guide/production-ready-checklist.html.md.erb
As part of running through the production ready check i have identified some extra information that needs to be added to the documentation around the use of the wafv2and aws shield
add's in information about internal use of waf and aws shield
=> Updating documentation for production ready checklist

environments-networks/platforms-development.json, environments-networks/platforms-test.json, policies/networking/expected.rego
https://github.com/ministryofjustice/modernisation-platform/issues/6457
Creating networks for delete-account
=> add networking files for delete-account

terraform/environments/core-shared-services/vpc_additional_cidr.tf
https://github.com/ministryofjustice/modernisation-platform/issues/6633
Adds metadata tags to new resources
Ran local plan
No
=> Adds tag to new NACL in core-shared-services resources

source/user-guide/quick-start-mac-guide.html.md.erb
=> Review Mac Quick Start Guide

terraform/environments/core-shared-services/ecr_repos.tf
Solves the issue encountered in this apply in modernisation platform environments repository. 
Allows Lambdas to pull 
Previously done in the same file
No. 
NA
=> 🔧  Modify ECR to allow Lambda retrieval

terraform/environments/core-network-services/cidr-ranges.tf, terraform/environments/core-shared-services/ad-fixngo.tf
Please see https://github.com/ministryofjustice/modernisation-platform/issues/5970 and https://github.com/ministryofjustice/modernisation-platform/issues/6633
Creating EC2 instance in core-shared-services-production to test connectivity with new IP addressing.
Updates related firewall rules.
Allows us to test whether new IP range has required connectivity
Not possible to exactly test.  This terraform worked OK though with the previous addressing.
No
=> DSOS-2711: rebuild azure hmpp root dc

.github/workflows/scheduled-baseline.yml
https://github.com/ministryofjustice/modernisation-platform/issues/6498
Ensure that all failures trigger Slack notifications
Not tested. This is a return to the original logic.
No
=> Unwind slack failure notification change

terraform/environments/core-network-services/cidr-ranges.tf
Add an extra range, lint the local to line it up neatly.
=> Added local value for extra core-shared-services VPC cidr assignment

terraform/environments/bootstrap/secure-baselines/main.tf, terraform/modernisation-platform-account/baselines.tf
See...
https://mojdt.slack.com/archives/C01A7QK5VM1/p1711528538461979
https://github.com/ministryofjustice/modernisation-platform-terraform-baselines/pull/417
Updates module to latest version
=> Bump baseline module to v6.6.0

environments/cica-data-extraction.json, policies/environments/expected.rego
https://github.com/ministryofjustice/modernisation-platform/issues/6559
Covers points 1 and 2 of the [creating AWS accounts](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/creating-accounts-for-end-users.html#1-create-a-new-environment-file) runbook.
Not tested - follows documented process
No
=> Add cica-data-extraction application

environments-networks/cica-development.json, policies/networking/expected.rego
https://github.com/ministryofjustice/modernisation-platform/issues/6559
Covers parts 1 & 2 of [AWS account creation runbook](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/creating-accounts-for-end-users.html#networking-stage) networking stage
Not tested. Documented process
No
=> add cica-data-extraction to networking

collaborators.json
Giving MadeTech developers access to development environment for Electronic Monitoring.
Gives access.
n/a
n/a
n/a
=> Update collaborators.json for electronic-monitoring-data

.github/workflows/new-environment.yml, environments/corporate-staff-rostering.json, environments/hmpps-domain-services.json, environments/hmpps-oem.json, environments/nomis-combined-reporting.json, environments/nomis-data-hub.json, environments/nomis.json, environments/oasys-national-reporting.json, environments/oasys.json, environments/planetfm.json
Reverts ministryofjustice/modernisation-platform#6678
This has caused failures in the `get new account(s)` step of the `delegate-access` job and is blocking runs of the baselines job.
=> Revert "DSOS-2668: new-environment pipeline fix"

.github/workflows/new-environment.yml
GitHub actions currently fail when running this job
Simplifies the logic to get changed `environments/*.json` files, and store their names as a multiline GitHub output
Tested locally only. Will try a workflow dispatch against this branch
No
=> Refactor how `Terraform: New environments` gets changed files

terraform/github/README.md
This is to complete the earlier documentation of the repository archive process.
It updates the documentation
Terraform plan/apply was run manually/locally
Deployment of documentation changes on merge.
=> Further documentation changes for repo archive.

terraform/environments/core-logging/sqs.tf
As per title, this fixes small inconsistencies in the bucket name referenced.
=> Ensure correct bucket is referenced.

source/runbooks/rotating-secrets.html.md.erb
Short runbook for the above user account's access key, namely so we have captured the email address of the team who operate the system.
=> Update to Runbooks for cortex_xsiam_user key rotation.

environments/oasys.json
oasys operator prod access
oasys operators need to log into oasys instances to change the web banners
gives them the required access in prod
N/A
no
=> oasys operator prod access

terraform/environments/core-network-services/firewall-rules/fqdn_rules.json
Firewall rule update as part of ask channel request 
Hi Mod Team
I have an issue with the MS Edge browser on our EC2 instances not auto-updating. This is causing thousands of AWS inspector / security hub findings to be generated due to an out of date browser being detected. On investigation and on attempting to manually update, the update is failing due to a timeout. This is most likely because Edge cannot connect to it's download source.
https://learn.microsoft.com/en-us/deployedge/microsoft-edge-security-endpoints has a list of download locations for Edge.
The core ones being:
HTTP
http://msedge.f.tlu.dl.delivery.mp.microsoft.com/
http://msedge.f.dl.delivery.mp.microsoft.com/
http://msedge.b.tlu.dl.delivery.mp.microsoft.com/
http://msedge.b.dl.delivery.mp.microsoft.com/
HTTPS …
=> Rule change for ms edge

.github/workflows/collaborator-inactivity-monitoring.yml, scripts/internal/collaborators-inactivity-notification/collaborator_user_deletion_issue.sh
Updated the script to remove unnecessary GitHub variables, simplifying its implementation.
By removing unnecessary GitHub variables from the script, we simplify its implementation and ensure that it functions correctly without relying on external environment variables.
=> Fix issue with inactive user issue creation script

environments/hmpps-oem.json
Changing the access level for the Development account
Changes the setup for the development account to update the access level, and exclude the account from being routinely nuked
n/a
n/a
n/a
=> DSO: turn on sandboxing for development environment

environments/oasys.json
OASYS is now live https://mojdt.slack.com/archives/CFE5ZQAQ7/p1713261790728649
=> Update oasys.json to include go live date

environments/sprinkler.json
As part of testing roles and iam changes we need to be able to quickly switch roles easily to make sure that the roles have the permissions required and nothing extra
Adds the roles to the sso login for sprinkler for easy switching
=> Adding new roles to sprinkler sso

environments/delius-iaps.json
Add `ministryofjustice/hmpps-delius-operational-automation` to delius-iaps OIDC team repos.
=> Add ministryofjustice/hmpps-delius-operational-automation to OIDC team repos

terraform/environments/bootstrap/member-bootstrap/iam.tf
Add ability to create, delete and copy RDS snapshots using the OIDC role.  This is required for our data refresh and backup/restore automations defined here:
https://github.com/ministryofjustice/hmpps-delius-operational-automation/actions/workflows/iaps-data-refresh.yml
Allows RDS snapshot actions.
=> OIDC: Allow RDS snapshot actions

environments/nomis.json, policies/environments/environment-definitions.rego
Instance-management role is too permissive for users just requiring login access to instances
instance-access role already created, this allows us to test it within nomis
n/a
no
=> DSOS-2720: try out instance access role in nomis-development

terraform/environments/bootstrap/single-sign-on/policies.tf, terraform/single-sign-on/sso-permission-sets.tf
There is a missing bedrock policy for the sandbox role which is needed by some users
This PR creates and added that policy to the sso role and i will follow up with a PR for the collaborators later on
=> new bedrock policy

cidr-allocation.md, scripts/tests/validate/README.md, terraform/modules/vpc-hub/README.md
Fix markdown warnings from morning run: https://github.com/ministryofjustice/modernisation-platform/actions/runs/8794978373/job/24135304548#step:6:80
=> 📝  fix markdown lint warnings

terraform/environments/core-shared-services/ad-fixngo.tf
Previous PR failed due to subnets not being created in correct zones
Backs out change
=> DSOS-2711: temporarily commenting out second azure.hmpp.root DC 

terraform/environments/bootstrap/member-bootstrap/iam.tf
Add KinesisAnalytics Permissions
The new permissions will allow us to manage Kinesis Resource through Github Actions
Ability to manage the new resource
Yes tested on Sandbox/Dev Environment
N/A
=> Add KinesisAnalytics Pemissions

.github/workflows/remove-default-vpc.yml, scripts/internal/remove_default_vpc.sh
This PR addresses the need to remove default VPCs from all accounts and regions. #6488 
This PR introduces a workflow to remove default VPCs across all accounts and regions, along with a corresponding script for executing the removal process.
tested this on sprinkler
=> Added workflow and script to remove default VPC

environments-networks/laa-development.json, environments-networks/laa-preproduction.json, environments-networks/laa-production.json, environments-networks/laa-test.json, policies/networking/expected.rego
#6790 
Sets up necessary configuration for networking
Followed steps in [team runbook](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/creating-accounts-for-end-users.html#networking-stage).
=> `EDW` account networking

environments/ccms-ebs-upgrade.json
Im creating a test environment for account called ccms-ebs-upgrade
As part of the process, the first step is to create a json file to create the new environment
https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/creating-accounts-for-end-users.html#information-required
This PR follows follows step 1
=> feature/6753 new test environment ccms-ebs-upgrade-account

.trivyignore.yaml
Adds a missing digit to a .trivyignore CVE
=> Add truncated digit

scripts/provision-member-directories.sh
=> Update provision-member-directories.sh adding static codeowners

environments-networks/laa-development.json, environments-networks/laa-preproduction.json, environments-networks/laa-production.json, environments-networks/laa-test.json, policies/networking/expected.rego
=> CWA networking

terraform/github/repositories.tf, terraform/github/teams.tf
This is an internal repo which will be used for raising and managing security issues on the Modernisation Platform.
We cannot do this in our current repos due to the security risk of using public repos.
Following on from discussion with SOC
Gives us a place to manage security issues in the open for MoJ but not too open.
=> Add security repo

terraform/github/modules/repository/main.tf
The logic was the wrong way round.
=> Fix enabling advanced security

terraform/github/modules/repository/main.tf
(Hopefully) fix for the previous [PR](https://github.com/ministryofjustice/modernisation-platform/pull/6913)
=> Removing not needed code

collaborators.json
As per issue/6769 - removes collab user max.malhi
=> issue/6769 - Remove collab user max.malhi

collaborators.json
Removal of inactive collaborator accounts for issues 6781, 6782, 6783 and 6784
=> Removal of inactive collaborator accounts bloc 2.

collaborators.json
Removal of inactive collaborator accounts for issues 6777, 6778, 6779 and 6780.
=> Inactive collaborator accounts bloc 3

collaborators.json
Removal of inactive collaborator accounts for issues 6773, 6774. 6775 and 6776
=> Removal of Inactive collaborator accounts bloc 4

collaborators.json
Removal of inactive collaborator accounts as per issues 6798, 6770, 6771 and 6772.
=> Inactive collaborator account removal bloc 5

collaborators.json
This removes the four inactive collaborator accounts from issues 6794, 6795, 6796 and 6797
=> Final block of 4 inactive collaborator accounts to be removed.

collaborators.json
N/A
Grants necessary access to new collaborator
N/A
No
N/A
=> IAPS: collaborator users

terraform/environments/bootstrap/member-bootstrap/iam.tf
This adds permissions to `CreateRoute` and `DeleteRoute`, operations used when working with VPCs
```
│ Error: creating Route in Route Table (rtb-010d26cc3def9759d) with destination (0.0.0.0/0): UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:sts::381491960855:assumed-role/MemberInfrastructureAccess/aws-go-sdk-1715248668927821965 is not authorized to perform: ec2:CreateRoute on resource: arn:aws:ec2:eu-west-2:381491960855:route-table/rtb-010d26cc3def9759d because no identity-based policy allows the ec2:CreateRoute action. Encoded authorization failure message: a-9gzM_Tbn-b1CSbJahLVtMbWOcWFEaNz8zRVIlK4mD5sFcJ1WV8RX33FEQOScI0iRPStUgmhsfPH45aAeSQ9CT_IsPujcjWbtX4inFpi-c3loBcQhd595Pk8EdeTCwwpSbbQAcfXM0gKVOzEu_8fQ4gtcvd4GzIibWMLW3T2uHtMQ7g0rGSbqPxn1-C_9nrsuQ …
```
=> 🗺️ Add `Route` permissions

terraform/modules/vpc-inspection/locals.tf, terraform/modules/vpc-inspection/main.tf
#2403
Updates the approach used to deploy NACL rules to put it in line with other `core-*` VPCs and `core-vpc-*` member VPCs.
Tested with local plan. As these rules are open (as controls are implemented in these VPCs by AWS Network Firewalls), there will be no impact to traffic.
No
=> Update NACLs in `vpc-inspection` module

source/runbooks/enabling-shield-advanced.html.md.erb, source/user-guide/creating-automated-terraform-documentation.html.md.erb, source/user-guide/our-offer-to-you.html.md.erb
Daniel the Manual Spaniel
APP  10:26
Hello :feet:, this is your friendly manual spaniel. I've found 3 pages that are due for review:
- Enabling AWS Shield Advanced for production applications (today)
- [Our offer to you](https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/our-offer-to-you.html) (today)
- [Creating Automated Terraform Documentation](https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/creating-automated-terraform-documentation.html) (today)
i have reviewed the documentation and no changes are required for the moment so updated the last review date
{Please write …
=> updating review date

environments/oasys.json
=> oasys support permissions

environments/corporate-staff-rostering.json, environments/ppud.json
#6921 
Revoke the migration role and assign the team to the appropriate role.
=> Migration access revoked

terraform/environments/bootstrap/member-bootstrap/iam.tf
To set up macie access for everyone, everywhere
=> Added macie2 to MemberInfrastructureAccess do macie is available everywhere

source/user-guide/working-as-a-collaborator.html.md.erb, terraform/environments/bootstrap/single-sign-on/policies.tf
allows instance-management-policy tag to give put secret permissions
..
..
no
=> Instance management tag put secret permissions

terraform/modernisation-platform-account/iam.tf, terraform/modules/collaborators/main.tf
This pull request updates the superadmin module version to the latest version and updates one of the superadmin usernames.
The updated module version includes the correction of the superadmin username.
=> Update Superadmin Module Version

scripts/internal/remove-default-vpc/remove_default_vpc_all_accounts.sh, scripts/internal/remove-default-vpc/remove_default_vpc_new_account.sh
This PR updates the script to add support for removing default vpc in eu-west-3 region.
=> Add support for removing default vpc in eu-west-3

source/concepts/environments/backups.html.md.erb, source/runbooks/adding-a-new-team-member.html.md.erb, source/runbooks/removing-a-team-member.html.md.erb, source/runbooks/terraform.html.md.erb, source/user-guide/how-to-use-shared-kms-keys.html.md.erb
Addressing documentation review reminder in [slack](https://mojdt.slack.com/archives/C013RM6MFFW/p1715851532164709).
=> Updating the user guide documentation

terraform/pagerduty/aws.tf, terraform/pagerduty/member-services-integrations.tf
Adding pagerduty integration for member account delius-nextcloud
=> Pagerduty for nextcloud set up

source/concepts/environments/single-sign-on.html.md.erb, source/runbooks/how-vpcs-access-the-internet.html.md.erb, source/team/roadmap.html.md.erb
Spaniel updates required https://mojdt.slack.com/archives/C013RM6MFFW/p1716283625307169
I've bumped the dates and added a new link to the SSO page to show that MP-specific permission sets are defined in our codebase (rather than root).
=> Doc Updates

environments/hmpps-domain-services.json, environments/hmpps-oem.json
These accounts are sandbox but with exclude nuke which is not recommended by MP
Removes sandbox. Any manually created resources have been removed.
n/a
No
=> DSOS: remove hmpps-oem and hmpps-domain-services sandbox access

terraform/environments/core-network-services/firewall-rules/preproduction_rules.json, terraform/environments/core-network-services/firewall-rules/production_rules.json
Saw some whitespaces in the firewall rules. Removed them.
=> Clean up some whitespaces

terraform/environments/bootstrap/single-sign-on/policies.tf
Add Lambda Invoke Permissions for Reporting Role
Add Lambda Invoke Permissions for Reporting Role
Able to Invoke Lambda using Reporting Role
Yes on Sandbox/Dev Env
N/A
=> Add Lambda Invoke Permissions for Reporting Role

environments/data-and-insights-wepi.json
New details following chats with CICA over sandbox nuke exclude.
=> Updates owner & contact for data-and-insights-wepi

source/runbooks/set-up-macie.html.md.erb
Minor change to reflect a known bug with the job_status property of the macie job resource.
=> Macie User Guide change

terraform/environments/bootstrap/single-sign-on/policies.tf
https://mojdt.slack.com/archives/C01A7QK5VM1/p1716544872791789
Add glue CreateSession and RunStatement to data engineering policy and allows iam passrole to electronic monitoring account
=> Update data engineering policy

source/concepts/networking/certificate-services.html.md.erb, source/concepts/networking/instance-access-and-bastions.html.md.erb, source/concepts/networking/networking-diagram.html.md.erb
Amending the review date for the documentation. No other changes identified.
=> Amending review dates for documentation. No other changes

environments/hmpps-domain-services.json, environments/hmpps-oem.json, environments/nomis-combined-reporting.json, environments/nomis-data-hub.json, environments/nomis.json, environments/oasys-national-reporting.json, environments/oasys.json
Nomis application support & testers getting barrage of github emails re PRs and action approvals. 
Updates codeowners and github approvers to what it should be. In general, DSO codeowner + approver. For hmpps-oem, migrations and DBAs also have codeowner + approver.
Also removes some instance-management entries that were for testing.
No
=> DSOS-2541: update DSO environment file codeowners and GHA reviewer

scripts/account-deletion/delete-tf-resources.sh
#7122 
Ensures that the account deletion process completes successfully by removing Terraform management of the resources, even if they cannot be directly destroyed.
Tested the solution when decommissioning data-platform-compute
=> Fix Errors in `delete-tf-resources.sh`

source/concepts/networking/certificate-services.html.md.erb, source/concepts/networking/instance-access-and-bastions.html.md.erb
As part Daniel the Manual Spaniel
APP  10:27
Hello :feet:, this is your friendly manual spaniel. I've found 2 pages that are due for review:
- Certificate Services (183 days ago)
- [Instance Access and Bastions](https://user-guide.modernisation-platform.service.justice.gov.uk/concepts/networking/instance-access-and-bastions.html) (183 days ago)
i have reviewed the documents and see no changes required
updated the review dates on the documents
=> Documents update

environments-networks/cica-development.json, policies/networking/expected.rego
Networking change for cica-tariff-development
=> Networking for cica-tariff-development

terraform/pagerduty/aws.tf, terraform/pagerduty/member-services-integrations.tf
=> LAWS-3912: Add PagerDuty Integration for CWA

terraform/environments/core-network-services/observability.tf
Ticket here - https://github.com/ministryofjustice/modernisation-platform/issues/6818
Introduces observability platform.
This is the test.
Merge, and then test.
=> Added observability platform

source/runbooks/enabling-shield-advanced.html.md.erb
#7032 
Updates documentation to remove clickops steps and refer customers to infrastructure-as-code implementation
Documentation to be reviewed by reviewer
=> Update AWS Shield Advanced implementation documentation

terraform/pagerduty/README.md, terraform/pagerduty/locals.tf, terraform/pagerduty/policy-schedules.tf
Following on from the ways of working session, this change is to reflect our minimum criteria policy. Therefore removing junior members from our on-call schedule
The new schedule will be generated on merge of this PR.
=> Updating the PD schedule

terraform/modernisation-platform-account/s3.tf
#7076 
The replication role module has been integrated into the main s3 bucket module so I removed the references to it and updated the source with the new release for the S3 bucket module.
Locally
=> Removed replication role module and updated the source 

terraform/pagerduty/member-services-integrations.tf
NDH doesn't currently have pager duty / slack integration configured
Add the integration
N/A - standard process
No
=> DSOS-2847: add pagerduty integration for NDH

terraform/pagerduty/aws.tf
Forgot to add the NDH pagerduty integration key in previous PR
Adds the integration key
N/A
=> ndh: DSOS-2847: add pagerduty integration fix

environments/genesys-call-centre-data.json, policies/environments/expected.rego
#6980
Starts the creation of new accounts following the user-guidance runbook "[Creating accounts for end-users](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/creating-accounts-for-end-users.html#1-create-a-new-environment-file)".
Follows documented steps
=> Create `genesys-call-centre-data` accounts

environments/cooker.json, terraform/environments/bootstrap/single-sign-on/policies.tf
To carry on with the spike i am moving pver to cooker but cooker does not have the instance management role on the sso so adding it with this PR
add in the instance management role
=> adding instance management role to cooker

environments/corporate-staff-rostering.json, environments/electronic-monitoring-data.json, environments/oasys.json, environments/planetfm.json
#7023 
Resource cleanup - it will nuke resources in the environment and rebuild
=> Replace nuke "exclude" with "rebuild" for sandbox development environments

terraform/pagerduty/aws.tf, terraform/pagerduty/member-services-integrations.tf
=> LAWS-3673: Add PagerDuty for APEX

source/user-guide/certificate-import.html.md.erb
* Refreshes stale link
* Adds summary of steps we undertake
=> updated docs on manual certificates

source/concepts/environments/architecture.html.md.erb, source/concepts/environments/security.html.md.erb, source/team/team.html.md.erb, source/user-guide/member-read-only-core-accounts.html.md.erb
as part of Daniel the Manual Spaniel
APP  10:27
Hello :feet:, this is your friendly manual spaniel. I've found 4 pages that are due for review:
- Viewing Core Account resources as a Member Account Developer (yesterday)
- [Environments (AWS accounts) architecture](https://user-guide.modernisation-platform.service.justice.gov.uk/concepts/environments/architecture.html) (yesterday)
- [Environments (AWS accounts) security](https://user-guide.modernisation-platform.service.justice.gov.uk/concepts/environments/security.html) (yesterday)
- [Our team](https://user-guide.modernisation-platform.service.justice.gov.uk/team/team.html) (today)
Documents reviewed and dates updated this PR covers this
Will …
=> Documents review update

environments/electronic-monitoring-data.json
#7023 
Resource cleanup - it will nuke resources in the environment and rebuild
=> removed exclude and replaced it with rebuild for development environment

terraform/pagerduty/aws.tf
=> fix: Remove duplicate underscore

terraform/environments/core-network-services/firewall-rules/preproduction_rules.json
testing nomis combined reporting connectivity/connections in to AWS resources
opens ports
NA, if this works we'll know we've fixed the issue
Testing this while we have people available. Will likely be improved/cleaned up later
=> allow nomis combined reporting traffic in from azure

terraform/environments/bootstrap/single-sign-on/policies.tf
developer import image
I need to import an oracle image (only exists as an iso) to an ami. iso -> raw -> ami.  
=> developer import image

terraform/environments/secrets.tf
Reverts ministryofjustice/modernisation-platform#7295
=> Revert "Update secrets.tf"

terraform/github/repositories.tf
https://github.com/ministryofjustice/modernisation-platform/issues/6490
I'm adding the testing-test secrets to the baselines repo to facilitate unit testing via github actions.
=> Adding testing secrets to baselines repo

source/runbooks/manage-an-incident.html.md.erb, source/runbooks/revoke-network-access.html.md.erb, source/user-guide/creating-resources.html.md.erb, source/user-guide/integrating-alarms-with-pagerduty-with-slack.html.md.erb
Reviewed document flagged by Daniel the spaniel
Reviewed document flagged by Daniel the spaniel
=> Updated review dates for docs due for review

terraform/environments/bootstrap/single-sign-on/policies.tf
=> developer import snapshot

terraform/github/repositories.tf
As part of #6490 and exdending on from #7302 this PR adds testing secrets to the repos with recently added unit-tests.
The added testing-test secrets to the repos will help facilitate unit testing via github actions.
=> 🧪 Add testing secrets to repos for unit-tests

.github/workflows/opa-policies.yml, policies/collaborators/collaborators.rego, policies/collaborators/collaborators_test.rego, policies/collaborators/utilities.rego, policies/environments/environment-definitions.rego, policies/environments/environment-definitions_test.rego, policies/environments/expected.rego, policies/environments/utilities.rego, policies/member/environment-definitions.rego, policies/member/environment-definitions_test.rego, policies/member/utilities.rego, policies/networking/core-vpc.rego, policies/networking/core-vpc_test.rego, policies/networking/expected.rego, policies/networking/utilities.rego, scripts/tests/validate/run-opa-tests.sh
This blog https://blog.openpolicyagent.org/opa-1-0-is-coming-heres-what-you-need-to-know-c8fb0d258368 describes some of the changes that will be required to OPA test policies so that the code will be ready for when version 1.0 is released later in 2024.
The purpose of this PR is to update the code so that it future proofed with the imminent update.
update four files  to change import future.keywords.in to import rego.v1
=> Test PR for OPA v1

terraform/environments/bootstrap/secure-baselines/main.tf, terraform/modernisation-platform-account/baselines.tf
Update baselines module to v7.2.0
For this issue https://github.com/ministryofjustice/modernisation-platform/issues/6490 some unit testing has been added to the baselines module.
This PR updates references to the module to the latest version.
=> Update baselines module to v7.2.0

environments/panda-cyber-appsec-lab.json, policies/environments/expected.rego
New environment for Panda - panda-cyber-appsec-lab
=> New environment for Panda

environments/panda-cyber-appsec-lab.json
Amended code so it has the email address for the security team in there.
=> Added email address for Panda

environments/panda-cyber-appsec-lab.json
Needed the email in the infrastructure-support section too. Added that
=> Missed adding the infrastructure support email address

.github/workflows/core-logging-deployment.yml, .github/workflows/core-network-services-deployment.yml, .github/workflows/core-security-deployment.yml, .github/workflows/core-shared-services-deployment.yml, .github/workflows/modernisation-platform-account.yml, .github/workflows/reusable_terraform_plan_apply.yml, .github/workflows/terraform-github.yml, .github/workflows/terraform-pagerduty.yml, .github/workflows/terraform-single-sign-on.yml
#6888 
The creation of a reusable workflow resolves the problem of having multiple, redundant workflows for similar tasks. One reusable workflow can be called by various pipelines, eliminating the need to duplicate workflow logic across different projects.
=> Update reusable workflow

environments-networks/platforms-development.json, policies/networking/expected.rego
Changes to make the network changes for Panda - may not be needed but an attempt to fix an error
=> Panda network changes

environments/panda-cyber-appsec-lab.json
Included the missed code of "isolated-network": "true",
Panda should be isolated according to the information in there.
=> Added the isolated-network true code to the Panda settings

source/runbooks/accessing-aws-accounts.html.md.erb, source/user-guide/workflow-status.html.md.erb
=> User Guide page reviews.

source/concepts/sdlc/sandbox-testing-environments.html.md.erb, source/runbooks/running-emergency-patching.html.md.erb
Documentation changes (none) identified by Daniel the Manual Spaniel.
=> Daniel documentation changes

terraform/environments/bootstrap/secure-baselines/main.tf, terraform/modernisation-platform-account/baselines.tf
as part of the issue to improve alerts we have updated the code so we need to update the version used by modplatform to take these changes into account
updated  modernisation-platform-terraform-baselines version in code
=> Updating terraform baselines to new version

.github/workflows/collaborator-inactivity-monitoring.yml, .github/workflows/remove-default-vpc.yml
Redacts ACCOUNT_NUMBER values from logs.
Removes from remove-default-vpc and collaborator-inactivity-monitoring workflows.
Same change as applied to other workflows.
No impact on services.
=> Redact ACCOUNT_NUMBER from logs.

.github/ISSUE_TEMPLATE/new-story-template.yml
Fixes template by adding missing `|`.
=> Add missing pipe to new story template

terraform/environments/core-shared-services/ecr_repos.tf
Create new repos for `delius-core-new-tech-pdfgenerator` and `delius-core-new-tech-web`.
`push_principals` deliberately omitted as it's not required.
=> Nit 1363 delius core pdf generator new tech get images

source/concepts/environments/problem-and-solution.html.md.erb
Fix some broken internal links
=> Fix broken docs links

terraform/environments/core-shared-services/ecr_repos.tf
Add delius-core-development OIDC role to New Tech ECR push principals.
=> fix: Add push principals to new tech ECRs

terraform/environments/core-shared-services/ecr_repos.tf
Moving EM's ecr repo to shared resource so we can nuke our account without it getting needlessly destroyed, causing lots of issues on the EM front this week
Creates the repo
Please describe the tests that you ran and provide 
n/a
I will need to move the references in our repo that talks to the ECR repo but then deployment should be fine
=> add em ecr repo for lambdas

terraform/pagerduty/aws.tf, terraform/pagerduty/member-services-integrations.tf
=> LAWS-3933 : Add EDW PD integration

environments-networks/hmpps-production.json
After successfully testing this in [hmpps development](https://github.com/ministryofjustice/modernisation-platform/pull/7390) wed like to promote it to hmpps production.
Add the endpoint to hmpps production.
n/a
n/a
=> add athena endpoint to hmpps

terraform/github/repositories.tf
This PR adds testing-test secrets to the modernisation-platform-terraform-module-template to help facilitate unit testing via GitHub actions.
=> 🧪 Add testing secrets to repo for unit-tests

.github/workflows/upload-cost-explorer-to-s3.yml, scripts/upload_cost_explorer_to_s3.sh
This PR adds a new script and GitHub Actions workflow to generate a CSV file with AWS Cost Explorer data and upload it to an S3 bucket. #3683
=> Add script and workflow to upload Cost Explorer CSV to S3

source/index.html.md.erb, source/user-guide/environments-networks-json-explained.html.md.erb
Adds a missing link as part of #5017
=> added link to new guide

source/index.html.md.erb
Caught an errant autocomplete error.
=> removed erb suffix from link

environments/contract-work-administration.json
=> LAWS-3966 Add CWA developer access to CWA account

terraform/pagerduty/member-services-integrations.tf
Need an alert from the loadbalancer on cdpt-ifs in case of users getting 5xx errors
adds pagerduty integration with slack  
-
-
=> add cdpt-ifs pagerduty

.github/workflows/core-vpc-development-deployment.yml, .github/workflows/core-vpc-preproduction-deployment.yml, .github/workflows/core-vpc-production-deployment.yml, .github/workflows/core-vpc-test-deployment.yml
This PR adds the `ENVIRONMENT_MANAGEMENT` environment variable to the pipeline configuration to prevent failures due to the missing variable.
=> Add ENVIRONMENT_MANAGEMENT env variable

terraform/pagerduty/aws.tf
missing pagerduty integration key
adds pagerduty integration key
-
-
- [ x] I have made corresponding changes to the documentation
- [ x] Plan and discussed how it should be deployed to PROD (If needed)
=> add integration key

source/index.html.md.erb
Adds protective monitoring page reference to runbook index.
=> Adds protective monitoring page reference to runbook index.

terraform/environments/core-logging/observability.tf, terraform/environments/core-security/observability.tf, terraform/environments/core-shared-services/observability.tf, terraform/environments/core-vpc/observability.tf
As per ticket https://github.com/ministryofjustice/modernisation-platform/issues/7221
Introduces observability platform.
previously implemented under ticket https://github.com/ministryofjustice/modernisation-platform/issues/6818
=> 👀  Add Observability Platform to mp core accounts

architecture-decision-record/0032-ncsc-pdns-not-at-platform-level.md, architecture-decision-record/README.md
#6121 
Adds ADR documenting decision not to implement PDNS
N/A
=> ADR proposal to not implement NCSC PDNS

source/user-guide/environments-networks-json-explained.html.md.erb
Although the markdown in my original version renders correctly through my IDE / online viewers, it appears to render incorrectly. I've added some line breaks to hopefully correct this.
=> Fix markdown for runbook page

environments/corporate-information-system.json, policies/environments/expected.rego
#7415 
Covers first two stages of [our runbook](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/creating-accounts-for-end-users.html#new-environment-files).
Follows standard runbook
=> Create new accounts for `corporate-information-system`

environments-networks/laa-development.json, environments-networks/laa-preproduction.json, environments-networks/laa-production.json, environments-networks/laa-test.json, policies/networking/expected.rego
#7415 
Completes changes for new `corporate-information-system` account
Followed runbook steps
=> Second stage of new account changes for `corporate-information-system`

collaborators.json
=> add NEC support engineers

source/concepts/networking/network-firewall.html.md.erb
Updates the review date of the Network Firewall concepts doc in the User Guide following its review.
=> User Guide Doc Review.

terraform/environments/digital-prison-reporting/iam.tf
glue:GetConnection
Allows CircleCi Pipelines to glue:GetConnection
Allows CircleCi Pipelines to glue:GetConnection
Yes on Sandbox, Manually
N/A
=> glue:GetConnection

terraform/environments/bootstrap/single-sign-on/policies.tf
glue:GetConnections
Allows to view glue Connections
Allows to view glue Connections
Yes on Sandbox
N/A
=> Add glue:GetConnections

environments/core-shared-services.json
as part of the ABAC implementation i want to test that the iam rule works so adding the instance management role to the account
=> adding instance management role for testing

environments/core-shared-services.json
Correction to github team slug
=> update github slug

terraform/github/repositories.tf, terraform/github/teams.tf
https://github.com/ministryofjustice/modernisation-platform/issues/6817
Adds the repository (Needs to be imported as has been clickopsed already :( )
=> Add AWS Chatbot repository

terraform/environments/bootstrap/secure-baselines/locals.tf, terraform/environments/bootstrap/secure-baselines/main.tf, terraform/modernisation-platform-account/baselines.tf, terraform/modernisation-platform-account/locals.tf
Makes sure CCMS test accounts aws backups are only retained for 7 days. Also changes the backup retention minimum to 7 days.
Terraform ouput
```
~ resource "aws_backup_plan" "non_production" {
id       = "b0ac326e-3243-410c-a03d-7ade78045cbf"
name     = "backup-daily-cold-storage-monthly-retain-30-days"
tags     = {
"application"   = "Modernisation Platform: Environments Management"
"business-unit" = "Platforms"
"component"     = "secure-baselines"
"is-production" = "true"
"owner"         = "Modernisation Platform: modernisation-platform@digital.justice.gov.uk"
"source-code"   = "https://github.com/ministryofjustice/modernisation-platform/tree/main/terraform/environments/bootstrap/secure-baselines"
}
- rule {
- completion_window        = 360 …
```
=> Pre Prod CCMS Backup reduction

source/concepts/environments/abac-resource-restrictions.html.md.erb
as part of Apply ABAC to core-shared-services
[#7410](https://github.com/ministryofjustice/modernisation-platform/issues/7410)
one of the tasks was to write up some documentation for the ABAC implementation
New Documentation 
=> New Documentation for abac

terraform/environments/bootstrap/single-sign-on/policies.tf
more serial console permissions
more permissions needed for sandbox to use serial console
=> more serial console permissions

source/runbooks/duty-rota.html.md.erb, source/team/ways-of-working.html.md.erb
Forgot to update the review dates in #7549
=> Updated document review dates

source/team/operational-processes.html.md.erb, source/team/ways-of-working.html.md.erb, source/user-guide/our-offer-to-you.html.md.erb
#7279 
Refactors our operational processes page, and adds some other minor content
Looked at our miro board outputs and updated documents accordingly
=> Updates to operational processes documentation

environments/oasys.json
oasys migration user
adds oasys migration user
no
=> oasys migration user

environments/delius-mis.json
=> Change hmpps-delius-mis team to fleet-manager role

environments/cica-tariff.json
A request for additional accounts for cica-tariff. 3 new accounts requested - test, preproduction, production with developer access.
=> New accounts for cica tariff

environments/analytical-platform-compute.json
https://github.com/ministryofjustice/analytical-platform/issues/4461
We need access to permissions in the Data Engineering role to set up services in Compute Account
N/A
Non-service impacting change
=> Promoted AP Engineers to Data Engineers

environments/delius-iaps.json
Remove hmpps-dba from the delius-iaps codeowners, they don't work on the application infra.
=> Update delius-iaps CODEOWNERS for consistency

source/runbooks/adding-collaborators.html.md.erb, source/user-guide/working-as-a-collaborator.html.md.erb
#7507 
It includes advisory steps to follow before adding a new collaborator
Discussed steps briefly with team
=> Include steps to follow before adding new collaborators

terraform/environments/bootstrap/single-sign-on/policies.tf
Fixing broken permissions in previous PR
https://github.com/ministryofjustice/modernisation-platform/pull/7590
https://github.com/ministryofjustice/analytical-platform/issues/4461
=> Fixing permissions

source/runbooks/creating-vpcs.html.md.erb, source/user-guide/security-testing-and-ithc.html.md.erb
Some docs needed a review.. https://mojdt.slack.com/archives/C013RM6MFFW/p1721899668133629
Updated dates and added a few links.
=> Some small doc updates

source/team/vision.html.md.erb
bringing it in line with the more general P&A style used in our CheckIn documentation
Part of general review
n/a
=> Update the modernisation platform vision

source/runbooks/core-shared-services-production.html.md.erb
#6766 
Outlines the essential steps for recreating the core-shared-services-production account
=> Core shared services production runbook

source/runbooks/core-shared-services-production.html.md.erb
=> fix formatting issues

source/runbooks/creating-new-private-dns-zones.html.md.erb
6 monthly review of this runbook.
=> Runbook Review - Private DNS Zones.

source/team/ways-of-working.html.md.erb
No issue - saw that the formatting needed a little tidying
Fixed formatting, added a line about signed commits
=> Quick tidy up of `ways of working` document

environments/cooker.json
Add Sandbox role to cooker
Adds Sandbox SSO role to cooker environment
=> Add Sandbox role to cooker

collaborators.json
Removes two inactive collaborator accounts #7617  #7618
=> Removal of Inactive Collaborator Accounts

terraform/environments/bootstrap/secure-baselines/main.tf, terraform/modernisation-platform-account/baselines.tf
This PR updates the version or reference of the baseline module to the latest version in the repository.
=> Update baseline module version

terraform/environments/bootstrap/secure-baselines/main.tf, terraform/modernisation-platform-account/baselines.tf
Reverts ministryofjustice/modernisation-platform#7629
=> Revert "Update baseline module version"

source/runbooks/backup-restore-process.html.md.erb
#7441 
Detailed documentation provides clear instructions for restoring services in the event of a failure, ensuring quick and efficient recovery.
=> Backup and restore process

environments/laa-mail-relay.json, policies/environments/expected.rego
Environment files for the new development sandbox account - laa-mail-relay.
#7592 
This creates the development env for laa-mail-relay as requested in #7592 
=> Issue-7592. New Account laa-mail-relay-development

environments-networks/laa-development.json, policies/networking/expected.rego
Adds laa-mail-relay-development to the json & gego files for RAM share & networking stage of the account creation process.
#7592 
=> Issue-7592

environments-networks/laa-development.json, policies/networking/expected.rego
Reverts ministryofjustice/modernisation-platform#7638
=> Revert "Issue-7592"

environments-networks/laa-development.json, policies/networking/expected.rego
#7592 
Sets up necessary configuration for networking
Followed steps in [team runbook](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/creating-accounts-for-end-users.html#networking-stage).
=> `laa-mail-relay` account networking

environments/laa-mail-relay.json, policies/environments/expected.rego
=> Step 1 for the new environment laa-mail-relay-development.

environments-networks/laa-development.json, policies/networking/expected.rego
=> Adds laa-mail-relay-development to the networking.json.

environments/laa-mail-relay.json
=> Creates laa-mail-relay-test

environments-networks/laa-test.json, policies/networking/expected.rego
=> Networking changes for new account laa-mail-relay-test

environments/laa-mail-relay.json
#7592 
Creates preproduction and production environments for `laa-mail-relay`
=> Creates preproduction and production environments for laa-mail-relay

environments-networks/laa-preproduction.json, environments-networks/laa-production.json, policies/networking/expected.rego
#7592 
Adding RAM Share for laa-mail-relay preprod and prod
=> Networking for laa-mail-relay preprod and prod

source/team/ways-of-working.html.md.erb
=> ways-of-working - add for review column and prioritisation

source/team/ways-of-working.html.md.erb
=> Ways of working - update available project board status options

source/concepts/sdlc/repositories.html.md.erb
Updates our repositories page to reference mandatory signed commits.
=> Updates our repositories page to reference mandatory signed commits.

source/runbooks/creating-new-dns-zones.html.md.erb
Raised by document review bot
Increments review date of doc
Reviewed document
=> Review docs on DNS zones

terraform/environments/bootstrap/member-bootstrap/iam.tf
following on from Slack request https://mojdt.slack.com/archives/C01A7QK5VM1/p1723642741120779 and PR https://github.com/ministryofjustice/modernisation-platform/pull/7682 this PR increases the timeout from 2 hours to 4 as part of discussion https://mojdt.slack.com/archives/C013RM6MFFW/p1723802825997389, I am I the middle of raising an issue to investigate further
=> OIDC Role - Increase Max Session Duration from 2 to 4 hours

terraform/environments/core-network-services/firewall-rules/development_rules.json, terraform/environments/core-network-services/firewall-rules/test_rules.json
=> :wrench: Add LDAPS port for delius core

environments/test-bugfix.json, policies/environments/expected.rego
This is a test account, created to fix the bug that occurs during the new account creation process. #7670 
Creates a new environment.
=> Add new environment files

source/user-guide/add-an-ecr-for-docker-images.html.md.erb, source/user-guide/certificate-import-windows.html.md.erb, source/user-guide/getting-aws-credentials.html.md.erb, source/user-guide/how-to-configure-dns.html.md.erb
=> Docs Update

terraform/pagerduty/aws.tf, terraform/pagerduty/member-services-integrations.tf
Clearing up all the alarms DSO manage and making them easier to use
adds services per environment
implemented for CSR previously/yesterday
No
=> Dso/dsos 2903/pagerduty alarms planetfm nomis

source/runbooks/manage-an-incident.html.md.erb
Ticket - https://github.com/ministryofjustice/modernisation-platform/issues/7551
how to potentially revoke IAM and network access - 
IAM - https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/revoking-user-access.html
Network - https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/revoke-network-access.html
how and what we communicate - https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/manage-an-incident.html
where we raise any subsequent ticket - I have added links to the security repos incident raising. 
Built locally, works fine.
NA
- [x ] I have made corresponding changes to …
=> Incident Security

source/runbooks/reviewing-dependabot-prs.html.md.erb
=> Runbook review

terraform/environments/core-logging/cortex.tf
#7607
Bucket policies need to be scoped only to the bucket they're applied to
=> for_each the policies for buckets so they match each bucket

terraform/environments/core-billing/observability.tf
as per issue https://github.com/ministryofjustice/modernisation-platform/issues/7169 this PR adds the Observability platform tenant to core-billing.
=> Add Observability Platform to core-billing

environments/edw.json
=> LAWS-3871 - Add edw tester group access

.github/workflows/new-environment.yml, environments/cooker.json, environments/example.json, environments/sprinkler.json, terraform/modernisation-platform-account/secrets.tf
This PR enhances the existing GitHub Actions workflow by adding a new step to the `environment_json_changes_notification` job. The new step sends a notification to a Slack channel whenever a JSON file in the `environments` folder is modified. #7570 
This PR addresses the gap in real-time communication by enhancing the existing workflow with a Slack notification step. This automation reduces the need for manual communication and ensures immediate visibility into environment changes.
The changes were tested on the branch 
No
=> Enhance existing workflow to add Slack notifications on JSON file changes

source/runbooks/slack-webhook-setup-guide.html.md.erb
This pull request adds a new guide to the repository that provides detailed instructions on how to set up Slack notifications for changes in the `environments.json` file. #7570 
This documentation will help team members easily set up Slack notifications to monitor changes in the environments.json file, ensuring they are promptly informed of any updates. The guide also promotes best practices for securely managing webhook URLs
=> add guide for setting up Slack notifications for JSON file changes

.github/workflows/format-code.yml
Reverts ministryofjustice/modernisation-platform#7794
=> Revert "Issue/7698"

environments/delius-core.json, environments/delius-iaps.json, environments/delius-jitbit.json, environments/delius-mis.json, environments/delius-nextcloud.json
Reverts ministryofjustice/modernisation-platform#7801
=> Revert ":passport_control: Add `hosting-migrations` to codeowners for delius related projects"

environments/delius-core.json, environments/delius-iaps.json, environments/delius-jitbit.json, environments/delius-mis.json, environments/delius-nextcloud.json
Probation WebOps is no more! We are now part of a larger team for migrations - LAA Ops, PWO and DSO all as one. This new team reflects all member of the new team so that PR reviews can be more collaborative.
----
Reintroduces https://github.com/ministryofjustice/modernisation-platform/pull/7801
after fixing multiple env changes at once via
https://github.com/ministryofjustice/modernisation-platform/pull/7806/files
=> :passport_control: add to codeowners for delius related projects

.github/workflows/new-environment.yml
=> :ambulance: Fix space typo in new-environment workflow

source/user-guide/cloud-platform-or-modernisation-platform.html.md.erb
Spaniel notification https://mojdt.slack.com/archives/C013RM6MFFW/p1725269339948559
Updates broken links on page and review date
=> Fix broken links in doc

terraform/github/teams.tf
#7607
Allows MP team members to manage this new repository
N/A
=> Allow MP team to manage new repo

scripts/account-deletion/delete-files.sh, source/runbooks/deleting-an-environment.html.md.erb
This PR updates the `delete-files.sh` to include the removal of the `modernisation-platform/terraform/environments/$APPLICATION_NAME` files which were missed from the removal process. 
I have also updated the documentation to simplify the AWS Org OU instructions which reduces the passing back and forth of tasks and speeds up the steps.
=> :bug: Delete Account Script Update

environments/digital-prison-reporting.json
https://github.com/ministryofjustice/analytical-platform/issues/5252
Enable data engineering access for DPR prod
Enables the access
This can be tested after it's applied
Standard
=> Data Engineering Access Level Enabled for DPR-Prod

terraform/pagerduty/versions.tf
Need to update provider version to address issue where new pagerduty_event_orchestration resources don't seem to work
Updtae provider version to latest
Run plan and see if anything breaks
Possibly, need to look carefully at the plan output to check everything 
=> provider version is over a year old

architecture-decision-record/0033-s3-state-bucket-condition-security.md
Follow on from - https://github.com/ministryofjustice/modernisation-platform/issues/5346 
Raises an ADR for the issue
=> S3 State Bucket ADR

terraform/environments/core-logging/cortex.tf
https://github.com/ministryofjustice/modernisation-platform/actions/runs/10768213003/job/29856926089
Lifecycle configuration rule is present, but not detected by Checkov
Tested through CI
No
=> Address SCA alert

terraform/pagerduty/member-services-integrations.tf
Expression syntax has a 36 character limit
Addresses this and makes the rule easier to understand
If it fails to apply we'll get a different error
Nope
=> at least it's easier to understand

terraform/pagerduty/member-services-integrations.tf
Use PagerDuty PCL for expression
from what I can read this should work
Should add a working rule
=> Dso/dsos 2903/try fix time check

source/team/alliance.html.md.erb
Update review date on alliance doc to re-trigger on 18th September (our next team day).
=> :dog: Review Alliance Doc

source/user-guide/production-ready-checklist.html.md.erb
Caught a small typographical error in the prod ready checklist.
Concisely.
Test through CI.
Deploy through CI.
=> Fix typo in checklist

environments/panda-cyber-appsec-lab.json
=> Updated nuke to exclude for panda-cyber-appsec-lab

terraform/environments/bootstrap/member-bootstrap/iam.tf
=> reverts PR 7873

environments/corporate-staff-rostering.json, environments/hmpps-domain-services.json, environments/hmpps-oem.json, environments/nomis-combined-reporting.json, environments/nomis-data-hub.json, environments/nomis.json, environments/oasys-national-reporting.json, environments/oasys.json, environments/planetfm.json
DSO team has been merged into a new team: Migrations Team.
This PR adds the Migration Team's new GitHub team to DSO's environments.
N/A - JSON update.
No. This just allows a new GitHub team to maintain certain environments.
N/A
=> add hosting-migrations to DSO environments

terraform/pagerduty/member-services-integrations.tf
Related to #5980 
This is the initial attempt to set up PagerDuty on Sprinkler so that it's the same as current settings.
=> Initial setup of Sprinkler

terraform/pagerduty/member-services-integrations.tf
=> Changes to add missing fields to the integration

source/index.html.md.erb, source/user-guide/how-to-setup-code-scanning-locally.html.md.erb
As part of Ability to run static code analysis locally
[#7062](https://github.com/ministryofjustice/modernisation-platform/issues/7062)
I have written documentation on how to install all the scanners locally and how to run them against the code
New Documentation
=> New documentation for running scans locally

terraform/environments/main.tf, terraform/environments/secrets.tf, terraform/modernisation-platform-account/dynamodb.tf, terraform/modernisation-platform-account/s3.tf, terraform/pagerduty/backend.tf, terraform/pagerduty/kms.tf
#7514
The PR adds the multi region replica keys below
- environment-management-multi-region
- s3-state-bucket-multi-region
- pagerduty-secret-multi-region
- dynamodb-state-lock-multi-region
Local terraform plan
=> first commit#7514

source/runbooks/dr-process.html.md.erb, terraform/github/locals.tf
Sean Privett has replaced Steve Marshall
Removes Steve, adds Sean.
_Le roi est mort, vive le roi._
Tested through CI
=> Removed Steve M, added Sean P

terraform/environments/core-logging/observability.tf
Create Athena workgroup for modernisation-platform cur reports
=> Create Athena workgroup

terraform/environments/core-network-services/logging.tf, terraform/environments/core-vpc/logging.tf
#7607 
Updates the module version to one which makes data stream compression optional, rather than hard-coded to `GZIP`.
Tested with one use of the module successfully.
=> Update `aws-data-firehose` module version

collaborators.json
=> feature7821- Removed Collaborator Andy.Land 

source/index.html.md.erb, source/user-guide/how-to-setup-secure-commit.html.md.erb
I have created this documentation as an aid to help users setup there machines to do secure commits for github
New documentation created
=> Secure commit documentation

terraform/pagerduty/aws.tf, terraform/pagerduty/member-services-integrations.tf
=> Copy changes from DBA-766 with signed commit

environments/oasys.json
remove oasys migration role
No longer needed. Was used for migrating audit vault, but that has now been cancelled
yep
=> remove oasys migration role

terraform/environments/bootstrap/member-bootstrap/iam.tf
Ask Channel request to add permissions to the oidc-cicd role
https://mojdt.slack.com/archives/C01A7QK5VM1/p1726748997322969
=> Update `dms:ModifyEndpoint` Permission for OIDC-CICD Role

terraform/environments/bootstrap/member-bootstrap/iam.tf
Ask Channel request to add permissions to the oidc-cicd role
https://mojdt.slack.com/archives/C01A7QK5VM1/p1726748997322969
=> Add dms:ImportCertificate permissions for oidc role

source/runbooks/recreate-modernisation-platform-account.html.md.erb
#6761
Added a little more detail without trying to cover all bases
Tested by peer review
=> Refined the MP account verification steps

terraform/modules/vpc-hub/main.tf, terraform/modules/vpc-hub/variables.tf, terraform/modules/vpc-inspection/main.tf, terraform/modules/vpc-inspection/variables.tf
#7607
Adds configuration to optionally send VPC flow logs to S3
Changes currently not invoked but will be in a following PR
=> Update VPC modules to optionally send flow logs to S3

terraform/environments/core-network-services/locals.tf, terraform/environments/core-network-services/monitoring.tf
#7607 
Outputs flow logs from Transit Gateway to S3 for Cortex XSIAM ingestion
Tested with local terraform plan.
=> Add flow logs from transit gateway to s3

terraform/environments/core-network-services/locals.tf, terraform/environments/core-network-services/monitoring.tf
#7607 
Outputs flow logs from Transit Gateway to S3 for Cortex XSIAM ingestion
Tested with local terraform plan.
=> Send flow logs from TGW to S3 for Cortex XSIAM

terraform/environments/core-network-services/locals.tf, terraform/environments/core-network-services/monitoring.tf
#7607
Adds custom flow log for TGW in line with [AWS Documentation](https://docs.aws.amazon.com/vpc/latest/tgw/tgw-flow-logs.html#flow-logs-default).
Tested with local terraform plan
=> Add TGW-specific custom flow log format

terraform/environments/core-shared-services/ecr_repos.tf
Weve just set up a new environment and need it to have perms to our ecr repo
Adds the EMD-test env everywhere
n/a
no
=> Add Test environment perms to EM ECR repo

terraform/environments/core-logging/versions.tf
Removes unused `random` provider.
=> Remove random provider from `core-logging`

terraform/environments/bootstrap/single-sign-on/policies.tf
=> allow reporting operations to modify dms task

.github/workflows/format-code.yml
This addresses a bug in the original graphql change which requires the existance of the empty remote branch otherwise graphql errors.
See above.
Workflow tested in branch issue/76890-bugfixing.
=> Issue/7689-bugfixing. 

terraform/environments/bootstrap/member-bootstrap/iam.tf
In addition to the `ImportCertificate` action the DBAs need the `DeleteCertificate` action to replace it.
I have changed `dms:ImportCertifcate` to  `dms:*Certificate` and this allows:
* `dms:ImportCertifcate`
* `dms:DescribeCertificate`
* `dms:DeleteCertificate`
In order to conserve policy size.
=> Update DMS actions for oidc role

source/getting-help/index.html.md.erb, source/runbooks/adding-collaborators.html.md.erb, source/runbooks/creating-accounts-for-end-users.html.md.erb, source/team/alliance.html.md.erb, source/user-guide/creating-networking.html.md.erb
=> Doc reviews.

environments-networks/hmpps-test.json, environments/delius-mis.json, policies/networking/expected.rego
=> Delete delius-mis-test account

source/runbooks/manage-an-incident.html.md.erb, source/runbooks/revoke-network-access.html.md.erb, source/user-guide/deploying-your-application.html.md.erb, source/user-guide/working-as-a-collaborator.html.md.erb
=> User guide & runbook reviews.

terraform/environments/sprinkler/locals.tf
=> Adds a formatting change to test the code formatter workflow.

.github/workflows/format-code.yml
=> Adds checks to confirm progress can happen.

source/runbooks/disaster-recovery.html.md.erb, source/runbooks/querying-vpc-flow-logs.html.md.erb
https://mojdt.slack.com/archives/C013RM6MFFW/p1727688718198679
Reviewed docs. Bumping review date.
=> Docs Review 300924

terraform/environments/core-logging/observability.tf
Use Observability platform for Modernisation Platform cost metrics [7169](https://github.com/ministryofjustice/modernisation-platform/issues/7169)
This PR adds a refined Athena access policy with reduced permissions from the _Full Access_ policy. 
work in progress, testing as I go.
No impact expected. 
=> 🧪  Refine athena policy and add cur reports bucket

README.md, source/index.html.md.erb, source/runbooks/recreate-core-vpc-$environment accounts.html.md.erb, source/runbooks/recreate-core-vpc-$environment-accounts.html.md.erb
#6767
Outlines the essential steps for recreating the core-vpc-$enviroments accounts
=> Feature/6767 create runbook for core vpc $environment accounts

terraform/environments/bootstrap/secure-baselines/main.tf
Bump remaining baselines after testing on mp account.
=> Bump baselines for all bootstrap

terraform/environments/core-logging/observability.tf
Small PR to update bucket policy with replication permissions
=> 🪣 Update bucket permissions ready for replication

terraform/environments/core-logging/observability.tf
fixing a typo in the bucket policy ( removing extra } )
=> fixup - remove } from bucket policy

terraform/environments/core-logging/observability.tf
fixup `MalformedPolicy: Policy has invalid resource`
=> fix resource invalid bucket resource

terraform/pagerduty/aws.tf, terraform/pagerduty/member-services-integrations.tf
Additional changes to the code for the cdpt system. This will allow this to work with the orchestration service we have added. It should allow some testing to take place as per a slack conversation with Alistair Curtis.
He has code in place to test this part of the cdpt system and will run the tests once this change is complete.
See #5980
=> Adding cdpt changes to code

terraform/environments/core-network-services/route53.tf
https://mojdt.slack.com/archives/C01A7QK5VM1/p1727787551689569
Adds a top-level domain for `apex` application.
=> Added top-level domain for apex service

environments/corporate-information-system.json
https://mojdt.slack.com/archives/C01A7QK5VM1/p1727947642125339
Adds team to environments file.
Tested via CI pipeline checks
=> Add team to CIS

terraform/environments/core-network-services/route53.tf
https://mojdt.slack.com/archives/C01A7QK5VM1/p1727787551689569
Updates the TLD to one acceptable for the domain admin team
=> Amend tld to suitable suggested name

source/user-guide/production-ready-checklist.html.md.erb, source/user-guide/quick-start-mac-guide.html.md.erb
=> 🐶  Daniel the spaniel reviews

source/user-guide/deploying-your-infrastructure.html.md.erb
=> User Guide doc review

terraform/environments/bootstrap/single-sign-on/policies.tf
Requested in ask channel: https://mojdt.slack.com/archives/C01A7QK5VM1/p1728305369209869 
To update the PPUD load balancer with new certificates
=> add elb:modifylistener permission to developer policy

terraform/environments/bootstrap/member-bootstrap/iam.tf, terraform/environments/bootstrap/single-sign-on/policies.tf
Additional permissions required as per issue that's impacting Nick Buckingham and his lambda deployment.
=> Adds signer:GetSigningProfile to MemberInfrastructureAccess

terraform/environments/core-shared-services/ecr_repos.tf
=> ecr access for ldap pre and prod

terraform/pagerduty/aws.tf
This PR updates the reference to the correct key name to address lookup failures.
=> updated the key reference to match customer code

source/team/team.html.md.erb, terraform/github/locals.tf, terraform/modernisation-platform-account/iam.tf, terraform/modernisation-platform-account/outputs.tf, terraform/pagerduty/locals.tf
Steve has moved on from the MP team
Removes Steve in line with guidance
Tested via PR review
Deploy through CI, follow-up with manual run against Modernisation Platform account to delete IAM superadmin user as CI does not have this power.
=> Remove Steve Linden

terraform/environments/core-logging/observability.tf
creating KMS key for S3 replication for issue:  https://github.com/ministryofjustice/modernisation-platform/issues/7169
=> 🔐 Create KMS Key for S3 replication

terraform/pagerduty/aws.tf
Reverting issue created from this - https://github.com/ministryofjustice/modernisation-platform/pull/8158/files
Raised here - https://moj.enterprise.slack.com/archives/C01A7QK5VM1/p1728553008250389
=> Delius Pagerduty Revert

terraform/environments/core-logging/observability.tf
Missed KMS Alias as part of https://github.com/ministryofjustice/modernisation-platform/pull/8240
=> Add kms key alias

terraform/github/locals.tf
https://mojdt.slack.com/archives/C013RM6MFFW/p1728986067685199
Removing security contractor who has recently left the dept.
=> Remove security user who's left the dept

environments/corporate-information-system.json
Every weekend EBS volumes get nuked. This disturb testing process
Sandbox env remains intact
Not sure mentioned issue needs more clarification.
No
=> [TM-423] changed nuke action for CIS sandbox env

terraform/environments/core-logging/lambda_cur/cur-crawler-initializer.py, terraform/environments/core-logging/observability.tf
**Overview:**
This PR introduces the infrastructure to support querying the AWS Cost and Usage Report (CUR) in Athena via an automated pipeline involving AWS Glue and AWS Lambda. The changes ensure CUR data from an S3 bucket is crawled, processed, and available in Athena for querying by Grafana.
**Key Changes:**
**1. AWS Glue Configuration**:
- Created a **Glue Catalog Database** `moj-cur-athena-db` to store CUR data metadata.
- Created a **Glue Table** `cost_and_usage_data_status` with schema and Parquet-based storage format.
- Added a **Glue Crawler** `moj-cur-reports-crawler` targeting CUR data in S3 for automated schema detection and updates.
- Created a **Glue Security Configuration** for encrypted communication with S3, CloudWatch, and Glue job bookmarks, utilizing KMS encryption. …
=> ✨ Add Athena CUR Pipeline with Glue and Lambda Integration

environments/apex.json
=> TM-612 Correct email for owner tag

environments/analytical-platform-compute.json, environments/analytical-platform-data-engineering.json, environments/analytical-platform-data.json, environments/analytical-platform-ingestion.json, environments/analytical-platform-landing.json, environments/analytical-platform-management.json, environments/analytical-platform.json
adding this tag for AP accounts has caused an issue reverting tag change
=> remove tag

terraform/environments/core-logging/observability.tf
This PR corrects the bucket used for the lambda trigger and also adds a data source tag to the Athena bucket for Grafana.
=> Correct Lambda trigger bucket

environments/laa-mail-relay.json
=> TM-593 Remove nuke for laa-mail account

collaborators.json
#8274 
PR adds the collaborator
=> feature#8274 - New collaborator: Sajid Habib

environments/performance-hub.json
performance hub are having issues since the introduction of the new tag 
removed new tag for now until they are ready
=> revert tag for performance hub

.github/workflows/monitor-ecs-eks-amis.yml, scripts/check-ecs-eks-amis.sh
#7189 
The script retrieves the latest AMI versions from AWS Systems Manager Parameter Store and compares them with the AMIs currently running on ECS and EKS instances. Any outdated AMIs are logged in a CSV file, which can be reviewed to identify instances that require AMI updates. The workflow can be used to trigger the script to run.
The script was tested on a local branch by triggering the workflow 
=> Adds script and workflow for ECS/EKS AMI monitoring

terraform/github/data.tf, terraform/github/testing-ci.tf
#7943 
Updates references in policy to keys now in use and renames aliases to be clear on their attributes
=> Update references to KMS keys for testing

source/team/vision.html.md.erb
=> 🐶  Review team vision

environments/cdpt-chaps.json
creation of a new repo which can push to the cdpt-chaps repo
add the repo to the github-oidc-team-repositories
=> add upgrade repo

.github/ISSUE_TEMPLATE/new-story-template.yml
This adds a new context/background text field to the MP story template. The purpose of this new filed is to allow the ticket author to capture information in a manner so it is clear this has been done so.
This is a follow-on from today's reto (28/10/24)
=> Adds an additional "background & context field to the story template.

scripts/confirm-environment-owner/get-environment-owners.sh, source/user-guide/creating-environments.html.md.erb, source/user-guide/workflow-status.html.md.erb
This updates our docs pages as follows:
- Adds the new confirm owners workflow to the status page.
- Adds a reference to us contacting owners periodically to the create environments page under the tags section.
- Adds some additional explanatory information to the confirm-owner-details script around how the PERIOD value is used.
This is the final part of issue #7047 
=> Updates user-guide man pages for issue/7047

environments/electronic-monitoring-data.json
As part of the pathway to go live, EM want to test their live data feeds in pre production
This PR adds a preproduction environment for electronic-monitoring-data
n/a
No
=> Add Electronic Monitoring Data Store preprod env

terraform/environments/bootstrap/member-bootstrap/locals.tf
https://github.com/ministryofjustice/modernisation-platform/actions/runs/11594119279/job/32281522077
#8353 
Skip alias creation for `electronic-monitoring-data-preproduction`.
Test through CI pipeline
=> Skip alias for EMDS preproduction

terraform/environments/cooker/locals.tf, terraform/environments/sprinkler/locals.tf, terraform/environments/sprinkler/secrets.tf
introduces minor formatting changes to test the workflow as a manual run of the workflow didn't find any formatting issues.
=> small formatting changes to trigger the code formatter

environments-networks/hmcts-preproduction.json, environments-networks/hmpps-preproduction.json, policies/networking/expected.rego
TBC - based on a request from @pricemg for an extra EMDS environment
Adds networking steps as detail [here](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/creating-accounts-for-end-users.html#networking-stage).
=> Set up RAM shares for `electronic-monitoring-data-preproduction`

terraform/modules/kms/main.tf
introduces minor formatting changes to test the format code workflow 
=> Formatting changes

source/runbooks/changing-environment-details.html.md.erb, source/runbooks/reviewing-mp-environments-prs.html.md.erb
Documentation updated for the 4th Nov.
Added a new tag we use in our environment files for the example.
=> Docs update.

terraform/environments/bootstrap/member-bootstrap/iam.tf
`ds:AccessDSData` is required to allow access to the `ds-data` API.
=> chore: add ds:AccessDSData action to OIDC role

terraform/environments/core-shared-services/ecr_repos.tf
=> allow delius core weblogic to pull from ecr

terraform/environments/core-shared-services/ecr_repos.tf
=> add delius core accounts to weblogic ecr principals

collaborators.json
https://github.com/ministryofjustice/modernisation-platform/issues/8406
Remove edward.caren from collaborators 
tried and tested documented process - https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/adding-collaborators.html#removing-collaborators
No
=> Inactive IAM Collaborator Deletion Required - Username: edward.caren 

source/user-guide/how-to-update-pagerduty-status-page.html.md.erb
Review of docs required: https://mojdt.slack.com/archives/C013RM6MFFW/p1731058243266799
A few minor adjustments to the PD Status Page doc
=> Minor updates to pd status page doc

environments/electronic-monitoring-data.json
Recently undergone an internal security review of our environment which has now ended.
Removing roles added for security audit. 
Also removing migration role (will need to readd for one final migration in new year)
n/a
n/a
n/a
=> Update electronic-monitoring-data.json to remove roles

terraform/environments/core-shared-services/ecr_repos.tf
=> add pull access for password manager ecr

terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf
No issue. It just looks wrong.
Alphabetises the list of skippable accounts placed into the variable for the Lambda to consume.
Not tested. Non functional change.
=> Alphabetise list of skippable accounts

terraform/environments/core-network-services/firewall-rules/development_rules.json
TM-602, establishing connection between LZ TST and MP Dev.
I have added an extra connection in the firewall rules.
The PR tests have passed including the terraform plan
This will only add a connection to the firewall rules so it shouldn't impact the platform/services on it
=> Adding LZ TST to MP Dev Connection

terraform/pagerduty/locals.tf
=> Adds Mike Reid (me) to pagerduty

collaborators.json
https://github.com/ministryofjustice/analytical-platform-ithc-2024/issues/26
Adding BSI engineer as collaborator
N/A
N/A
=> Adding ITHC engineer as collaborator

source/runbooks/security-monitoring.html.md.erb
Doc updates required: https://mojdt.slack.com/archives/C013RM6MFFW/p1731576682333639
Security Monitoring doc has been reviewed/updated.
=> Security Monitoring doc update

terraform/modernisation-platform-account/iam.tf
Reverts ministryofjustice/modernisation-platform#8481
=> Revert "Separate OIDC roles for Terraform plan and apply with branch-based restrictions"

terraform/modernisation-platform-account/iam.tf
This PR updates the OIDC role configuration to enhance security and ensure least-privilege access for GitHub Actions workflows. 
Previously, the OIDC role allowed all workflows to potentially perform `terraform apply` actions without restrictions to specific branches, which posed a risk of destructive actions occurring without sufficient review. By splitting roles and restricting `apply` to the main branch, this PR mitigates the risk of unauthorized or unreviewed changes.
=> Separate OIDC roles for Terraform plan and apply with branch-based restrictions

collaborators.json
=> add Laimute Taylor as collaborator

environments/oasys-national-reporting.json
application tag isn't consistent
makes the tag consistent with other environments
I'm assuming it'll just update the tag(s)
Apply
=> change application tag to be consistent

collaborators.json
https://github.com/ministryofjustice/analytical-platform-ithc-2024/issues/26
Adds the user
Testing is post-deployment
We need someone to provide us with the keys and console password for the user after this is applied please.
=> Adding an external collaborator for ingestion

source/concepts/environments/single-sign-on.html.md.erb
Documentation for https://github.com/ministryofjustice/modernisation-platform/issues/8356
Updates the single sign on documentation for Microsoft's Entra ID
Documentation update only.
No
=> 📝 Update single sign on documentation

source/concepts/environments/backups.html.md.erb, source/runbooks/adding-a-new-team-member.html.md.erb, source/runbooks/removing-a-team-member.html.md.erb, source/runbooks/terraform.html.md.erb, source/user-guide/how-to-use-shared-kms-keys.html.md.erb
Docs updated.
- [How to use shared KMS keys](https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/how-to-use-shared-kms-keys.html) 
- [Backups](https://user-guide.modernisation-platform.service.justice.gov.uk/concepts/environments/backups.html) 
- [Removing a Team Member](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/removing-a-team-member.html) 
- [Adding a new team member to the Modernisation Platform](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/adding-a-new-team-member.html) 
- [Terraform](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/terraform.html)
=> Docs updated

terraform/environments/bootstrap/member-bootstrap/iam.tf, terraform/environments/bootstrap/single-sign-on/policies.tf
https://github.com/ministryofjustice/modernisation-platform/actions/runs/11912899416
Directly defining the IAM role with aws_iam_role.
Attaching the existing policy to the role via aws_iam_role_policy_attachment.
=> changes to role and policy for S3 malware protection

terraform/environments/sprinkler/iam.tf
Update GitHub OIDC role assumption for MP account in Sprinkler and create Member Infrastructure roles in Sprinkler.
=> Update sprinkler GitHub OIDC Role

source/runbooks/how-vpcs-access-the-internet.html.md.erb, source/runbooks/rotating-secrets.html.md.erb
=> Runbook doc review

collaborators.json
Offboarding external collaborators
1. This PR removes their collaborator access.
2. Next PR will remove the custom access level
N/A
This should be non-service-impacting change
=> Rememoving AP external collaborators (1 of 2 PRs)

policies/collaborators/collaborators.rego, policies/collaborators/collaborators_test.rego, terraform/environments/bootstrap/member-bootstrap/collaborators.tf
AP created a custom access level per request of their external collaborators that can now be removed.
It removes the access level and adjusts the OPA tests.
Testing post deployment
This is non-service-impacting
=> Removing security-read-only access: PR 2 of 2

source/team/roadmap.html.md.erb
Document reached review date
Confirmed content still accurate. Updated review information.
Tested through peer review
=> Updated roadmap review date

collaborators.json
https://mojdt.slack.com/archives/C01A7QK5VM1/p1732534061130089
Removes collaborator as requested by support team
Tested via peer review
Implement as documented here: https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/adding-collaborators.html#removing-collaborators
=> Remove PPUD collaborator

environments/sprinkler.json
Add modernisation-platform group to sprinkler for testing Entra ID
=> EntraID for sprinkler.json

environments/sprinkler.json
Reverts ministryofjustice/modernisation-platform#8591
=> Revert "Revert "EntraID for sprinkler.json""

environments/sprinkler.json
Reverts ministryofjustice/modernisation-platform#8592
=> Revert "Revert "Revert "EntraID for sprinkler.json"""

source/runbooks/enabling-s3-malware-protection.html.md.erb
#8050 
Provides instructions for enabling Malware Protection for S3 using Terraform, and includes a working example.
=> S3 malware protection implementation guide

environments/tribunals.json
Adding a new GitHub repo - needed for one more tribunal site
=> Add Asylum Support GitHub Repo to tribunals.json

terraform/environments/core-logging/cortex_alarms.tf
This adds the slack channel ID as provided by Thomas Green.
This is the last remaining change for issue 8428.
Currently deployed with a test channel ID which has been confirmed as working.
=> Added the channel ID as provided by SecOps.

environments/ccms-ebs-upgrade.json, environments/ccms-ebs.json
Required for this ticket - https://github.com/ministryofjustice/modernisation-platform/issues/8392
Gives them access to a DB based role.
This role has exited for a while.
=> CCMS Instance Mgmt

source/runbooks/adding-admin-data-lake-formation-permissions.html.md.erb
[#8408](https://github.com/ministryofjustice/modernisation-platform/issues/8408)
Minor changes to existing runbook
Tested using cooker to see if the code works
no
=> Minor Change to lake formation admin user run book

environments/sprinkler.json
As part of https://github.com/ministryofjustice/modernisation-platform/issues/8356 add Azure team for testing Entra ID
=> Add EntraID Modernisation Team

source/user-guide/working-as-a-collaborator.html.md.erb
#8303 
Includes guidance on how to use the s3-upload role for cross-account access, making the information easily accessible.
=> Update collaborator user-guide to include S3-upload role

source/concepts/networking/networking-diagram.html.md.erb
=> Doc review

environments/nomis.json
To enable testing of Entra ID SSO access in Nomis
Grants access to DSO Entra ID SSO group
N/A
N/A
=> TM-782: test entra ID access for DSO in nomis-development

terraform/environments/core-network-services/firewall.tf, terraform/environments/core-vpc/vpc.tf, terraform/modules/vpc-hub/main.tf, terraform/modules/vpc-inspection/main.tf
As part of investigating [this issue](https://mojdt.slack.com/archives/C6D94J81E/p1733228097115609) more detail in VPC flow logs has been requested.
Adds all values to VPC flow logs.
Log format currently used successfully with XSIAM logs
=> Updated VPC flow log formats for full verbosity

collaborators.json
as per slack request for new collaborators - https://mojdt.slack.com/archives/C01A7QK5VM1/p1733482818190009
=> Setup New Collaborators

environments/cooker.json
Team requires quick access to an AWS account to spin up some temporary infrastructure, due to an urgent request. We have agreed offer our Cooker account for the team to complete this work.
Gives MoJRedTeam SSO access to Cooker
NA
NA
=> 🔐 Add `MoJRedTeam` to `cooker`

environments/cdpt-ifs.json
Using Entra ID for AWS Access Management
Add new Azure group name 
\
No
=> add azure-aws-sso-cdpt group name for sso

environments/cdpt-chaps.json, environments/cdpt-ifs.json
add azure-aws-sso-cdpt group name
Fix for Entra SSO
\
No
=> add azure-aws-sso-cdpt group name for Chaps sso

source/runbooks/enabling-shield-advanced.html.md.erb
=> 🐶  Enabling AWS Shield Advanced Review

environments-networks/laa-preproduction.json, policies/networking/expected.rego
#8677 
Completes [part two](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/creating-accounts-for-end-users.html#networking-stage) of the new account process.
=> Add networking configuration statements for `mojfin-preproduction`

source/index.html.md.erb
Issue with new link to oracle licensing broken link
corrected the spelling and fixed the link
=> link correction

source/concepts/environments/single-sign-on.html.md.erb
Adding Azure Portal URL to documentation
=> Add Azure URL

terraform/pagerduty/locals.tf
=> add myself and kudzai to pagerduty

terraform/pagerduty/locals.tf
My email address is already active on pagerduty to updating it to include myself to the existing users.
=> adding Khatra (me) to the existing pd users

.github/workflows/terraform-static-analysis.yml
Updating `ministryofjustice/github-actions` to `v18.6.0`
This version pins the trivy version to `v0.57.1` as the latest version has been causing us some errors.
=> Update ministryofjustice/github-actions to `v18.6.0`

terraform/environments/core-network-services/firewall-rules/preproduction_rules.json
=> Allow LDAP to HMPPS Preproduction VPC from CP

terraform/environments/core-network-services/firewall-rules/production_rules.json
=> Allow LDAP to HMPPS Production VPC from CP

environments/youth-justice-app-framework.json, policies/environments/expected.rego
#8706 
Covers the [first part](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/creating-accounts-for-end-users.html#new-environment-files) of our guidance on creating new accounts.
I've added the `modernisation-platform-engineers` GitHub team so that the account can be included in AWS Nuke runs, and so that we can also approve PRs and deployments for the external collaborators when needed.
=> added json and application for youth-justice-app-framework

collaborators.json
#8706 
Clears up a naming inconsistency
Deploy through CI pipeline, the clean up old user by running code with my admin credentials locally
=> Fix collaborator name

environments/apex.json
=> TM-772 Update APEX go live date and roles

environments/analytical-platform-common.json, policies/environments/expected.rego
#8621
Covers the first part of our new account process. Creating as `member-unrestricted` in line with other analytical platform accounts.
=> Add analytical-platform-common

environments/corporate-information-system.json
(https://dsdmoj.atlassian.net/browse/TM-829)
Gives access to required team to MP CIS Env
=> [TM-829] added access for LAA-CIS-DBAs team to MP CIS Dev env

source/runbooks/joining-the-team.html.md.erb
Reviewed and updated document flagged by Daniel the spaniel.
=> Joining the team doc review and updates

terraform/environments/bootstrap/delegate-access/backend.tf, terraform/environments/bootstrap/member-bootstrap/backend.tf, terraform/environments/bootstrap/secure-baselines/backend.tf, terraform/environments/bootstrap/single-sign-on/backend.tf, terraform/environments/core-sandbox/backend.tf, terraform/environments/main.tf, terraform/github/backend.tf, terraform/pagerduty/backend.tf
https://github.com/ministryofjustice/modernisation-platform/issues/8789 describes the issue.
We are temporarily suppressing the checkov warning until this ticket is completed.
=> Temporarily suppress `CKV_TF_3` Ensure state files are locked

source/concepts/networking/certificate-services.html.md.erb, source/concepts/networking/instance-access-and-bastions.html.md.erb, source/concepts/networking/networking-approach.html.md.erb, source/concepts/networking/subnet-allocation.html.md.erb, source/runbooks/running-emergency-patching.html.md.erb
* Updates review dates for docs - concepts haven't changed and the content is still relevant.
* Some formatting and readability updates to SSM emergency patching document.
=> Review dates for documents

terraform/modernisation-platform-account/s3.tf
This PR introduces an S3 bucket named `modernisation-member-information` for storing member account data or uploading csv file. This bucket will serve as the central storage for member-related information, including account details, contact information, incident details, and service URLs. #7761 
Creates S3 bucket
=> Create S3 Bucket for Member Information

policies/networking/expected.rego
No issue. I just wanted to tidy this up in the wake of setting up the YJB resources.
It sorts the expected VPCs by business unit and environment
Tested with CI pipeline checks
Deploy through CI / non-functional change
=> Tidy up `.rego` file

.github/workflows/modernisation-member-information.yml, scripts/internal/modernisation-member-information.sh
This PR introduces functionality to manage and output member account information to a CSV file. The data includes account name, AWS account number, Slack Channel, Infra-support email, incident hours, incident contact details, and service URLs. The information is stored in an S3 bucket. #7761 
This feature automates the management of member account information, centralizes data storage in AWS S3, and provides structured CSV output for easy access and further processing.
Tested the script locally
=> New feature to fetch the member information

environments/laa-stabilisation-cdc-poc.json, policies/environments/expected.rego
Step 1 for new environment creation - https://github.com/ministryofjustice/modernisation-platform/issues/8835
=> New Environment Step 1 - laa-stabilisation-cdc-poc

environments-networks/laa-development.json, policies/networking/expected.rego
Step 2 for new environment creation - https://github.com/ministryofjustice/modernisation-platform/issues/8835
=> New Environment Step 2 - laa-stabilisation-cdc-poc

collaborators.json
See request here from environment owner: https://mojdt.slack.com/archives/C032BQQHJE5/p1735554259067189
=> chore: add dale.tritschler to collaborators

environments/youth-justice-app-framework.json
#8833 
Adds additional environments to YJAF
Tested with CI pipeline checks
=> Create new environments for YJAF

terraform/environments/core-network-services/iam.tf, terraform/environments/core-network-services/route53.tf
https://mojdt.slack.com/archives/C01A7QK5VM1/p1735817304903079
This PR creates and associates the private DNS zone with the VPC
=> Add private DNS zone `development.yjaf` for internal use

.github/workflows/modernisation-member-information.yml, scripts/internal/modernisation-member-information.sh, terraform/modernisation-platform-account/athena.tf
This PR introduces the setup for querying member information stored in a CSV file using AWS Athena. The implementation includes Creation of an Athena database, table, and workgroup. #7761 
Creates Athena database, table, and workgroup.
=> Add Athena Setup for Querying Member Information

scripts/internal/modernisation-member-information.sh
This PR introduces the `clean_field` logic to the existing workflow to enhance data formatting and ensure clean data output.
=> Add clean_field logic to enhance data formatting and handling

scripts/generate-dependabot-file.sh
#7053 
I left an old comment in the script that creates dependabot files
Tested locally
=> Remove outdated comment from script

terraform/environments/core-network-services/firewall-rules/development_rules.json
=> add oracle access for delius core + mis

terraform/environments/core-shared-services/ecr_repos.tf
Reverts ministryofjustice/modernisation-platform#8892
=> Revert "Update ecr_repos.tf"

environments/nomis.json
As part of the work for issue 8674, this adds the "instance_scheduler_skip" field to nomis preproduction to ensure that the new version of the instance_scheduler excludes that account from testing and production runs.
See ticket https://github.com/ministryofjustice/modernisation-platform/issues/8674 for further information.
A new version of the instance scheduler is to be released that references account details in the environments/*.json files to determine whether the account should be in scope of the scheduler's accounts to be included, or not. To allow accounts of type "member" to be excluded, we will be using a new field in the relevant "environment" list - "instance_scheduler_skip": ["true"]
For example:
```
{
"name": "development",
"access": [
{
"sso_group_name": "dev-team", …
```
=> Issue/8674 - Production deployment dependency.

terraform/environments/core-shared-services/ecr_repos.tf
Reverts failing portions of https://github.com/ministryofjustice/modernisation-platform/pull/8879
=> Reverting JML Changes to fix core-shared-services workflows

environments/delius-alfresco.json, policies/environments/expected.rego
New Environment request https://github.com/ministryofjustice/modernisation-platform/issues/8912
=> delius-alfresco - Create New Environment Step 1

collaborators.json
https://github.com/ministryofjustice/modernisation-platform/issues/8889
Adds collaborator account
=> Add Olivier as a YJAF collaborator

collaborators.json, terraform/pagerduty/aws.tf, terraform/pagerduty/member-services-integrations.tf
Setting up Pager Duty and integtrating with Slack in Production for delius core application.
creates new Pager Duty service and slack integration for Delius Core production env
created as per MP documentation and using the same template/blueprint to create the PD service and integrate with slack to send notifications to
No
=> TM-886 setting up PD and slack integration in Prod

terraform/environments/core-network-services/providers.tf, terraform/environments/core-network-services/transit-gateway.tf
As Part of issue TGW Ireland Creation
[#8584](https://github.com/ministryofjustice/modernisation-platform/issues/8584)
we need to create a new PR to implement a transit gateway for the Ireland region for DR 
This PR creates new code for the creation of the transit gateway
=> new TGW code

terraform/github/repositories.tf, terraform/github/teams.tf
This PR introduces a new repository for GitHub Actions related to the Modernisation Platform. These actions are designed to streamline and enhance workflows across projects within the platform.
Adds the repository
=> Add GitHub Actions repository for the Modernisation Platform

environments/nomis.json
This adds SSO via Entra for the nomis-access group
=> add Entra group for nomis-access SSO

.github/workflows/access-keys-monitoring.yml
Part of ticket https://github.com/ministryofjustice/modernisation-platform/issues/8359 this PR adds a step to the workflow to validate the template version ensuring the template hasn't been altered
similar PR merged here https://github.com/ministryofjustice/modernisation-platform/pull/8992
local testing version validation (incorrect template specified):
local testing version validation (correct template specified):
=> Add Template Validation to workflow

environments/youth-justice-app-framework.json
YJAF have requested additional reviewers.
Reviewers added to environment.json
=> Additional reviewers for YJAF

environments/laa-stabilisation-cdc-poc.json
https://dsdmoj.atlassian.net/browse/STB-685?atlOrigin=eyJpIjoiZDU5NzdhNmIwMjE5NGI3YWEyM2U1ZDVmYTIyZjIzOGYiLCJwIjoiaiJ9
(I hope!) this will create a CI/CD role in the environment to allow us to deploy our application programatically. It needs to have the ability to connect to instances over SSM.
n/a
no
=> Create CI/CD role for Oracle CDC replacement repo

terraform/modernisation-platform-account/s3.tf
#8345
Adds statements to S3 bucket policy that allow terraform native locks to be deleted.
Tested through CI pipeline. PR adds permissions, so there ought to be no impact to existing workflows
=> allow further roles to remove tf locks

terraform/environments/bootstrap/delegate-access/backend.tf, terraform/environments/bootstrap/member-bootstrap/backend.tf, terraform/environments/bootstrap/secure-baselines/backend.tf, terraform/environments/bootstrap/single-sign-on/backend.tf, terraform/environments/core-sandbox/backend.tf, terraform/environments/main.tf, terraform/github/backend.tf, terraform/pagerduty/backend.tf, terraform/single-sign-on/backend.tf, terraform/templates/modernisation-platform/backend.tf
#8345 
Additional environments set to use native state locking. Cleaned up some unneeded comments.
Tested with CI pipeline checks
=> Set `github` and `pagerduty` to use native state locking

environments/mojfin.json
=> TM-893 Add new role for MojFin lower envs for SSM users

architecture-decision-record/0035-terraform-workspaces.md
#8960 - Updates the exceptions to include directories that are using the default workspace.
=> update adr for TF workspaces

terraform/environments/core-network-services/firewall-rules/development_rules.json
=> allow legacy eng dev to connect to mp dev oracle

source/runbooks/adding-a-new-sso-user-role.html.md.erb, source/runbooks/creating-vpcs.html.md.erb
Reviewed documents flagged by Daniel the spaniel, no revisions were necessary to the content.
=> revised the date to keep docs up to date

environments/corporate-staff-rostering.json
=> csr add migration role

collaborators.json
=> removing inactive collaborators

environments/dacp.json, environments/tipstaff.json, environments/wardship.json
=> Update owner and infrastructure-support fields of dacp, tipstaff and wardship

environments/delius-mis.json
hosting-migrations cannot approve GHA workflows, despite hmpps-migration being able to.
Explicitly define GHA reviewers.
=> chore: update gha reviewers for delius-mis

architecture-decision-record/0036-managing-environment-collaboration-with-component-isolation.md
This PR introduces an ADR that addresses the challenge of collaboration within a single account in modernisation platform environments. The ADR proposes a component-based isolation strategy using Terraform workspaces and separate state management.
=> Add ADR for Managing Environment Collaboration via Component Isolation

terraform/pagerduty/member-services-integrations.tf
=> TM-616 - add cis pd key

environments/contract-work-administration.json
=> TM-949 Updating PCUAM CWA DEV permissions

environments/delius-core.json
=>         chore: add zaizi-devs to delius-core env

terraform/environments/bootstrap/member-bootstrap/collaborators.tf
Copied the wrong code, should have copied code to create a role that can be used by customers.
Edited code to work
Testing in sprinkler
Baselines run
=> Fix, wrong collab type

.github/workflows/reusable-signed-commit.yml
Add new workflow for issue https://github.com/ministryofjustice/modernisation-platform/issues/8878 once this PR is merged I will duplicate and update one of the current workflows to use this workflow so I can test.
=> Add reusable signed commit workflow

source/index.html.md.erb, source/team/terraform-style-guide.html.md.erb
Action from past retrospective
Tries to provide some simple guidelines without duplicating the contents of the Hashicorp terraform style guide
Test through peer review
=> Lightweight Terraform style guide

.github/workflows/generate-dependabot-signed-commits.yml
Updated workflow for testing signed commits for generate-dependabot-file workflow
=> updated workflow for signed commits testing

.github/workflows/reusable-signed-commit.yml
Update to test workflow following some troubleshooting / testing.
=> Update Signed Commit Workflow

terraform/environments/core-network-services/firewall-rules/test_rules.json
Update Firewall rules to allow traffic from CP to MP LAA TEST on port 1521
Opens the port
=> CC-3160: Update Firewall to allow traffic from CP to EBSDB on port 1521

collaborators.json
Collaborator access requested in Slack https://mojdt.slack.com/archives/C01A7QK5VM1/p1739797740315019 and an accompanying email
Adds collaborators
=> Adding ROC collaborators for equip

source/user-guide/working-as-a-collaborator.html.md.erb
Amended the collaborator initial login guidance following feedback from users.
=> Collaborator login guidance.

collaborators.json
N/A - requested via Slack
Allows @gregi2n to expand service quotas by hand
Standard process tested via CI pipeline
=> Expand Greg's access to YJAF accounts

environments-networks/yjb-preproduction.json, environments-networks/yjb-production.json, environments-networks/yjb-test.json
(https://mojdt.slack.com/archives/C01A7QK5VM1/p1739898202645929)
PR Extends YJAF newly created private DNS zone
See tests below,
=> Extending YJAF newly created private DNS zone

terraform/environments/bootstrap/single-sign-on/main.tf
This _should_ be kebab cased to follow the pattern of all other assignment levels and documentation
Corrects assignment level naming
It hasn't been tested
Only Analytical Platform Ingestion
=> 🚑 Fix assignment level logic for platform engineer admin

terraform/single-sign-on/outputs.tf, terraform/single-sign-on/sso-permission-sets.tf
=> Added platform engineer admin sso permissions

environments/youth-justice-networking.json, policies/environments/expected.rego
#9305 
Creates account to hold YJB SRX appliances
Follows our new account runbook
=> Create `youth-justice-networking` account

collaborators.json
#9305
Allows YJB collaborators to make use of networking account
=> Add YJB collaborators to YJB networking account

source/user-guide/add-an-ecr-for-docker-images.html.md.erb, source/user-guide/certificate-import.html.md.erb, source/user-guide/getting-aws-credentials.html.md.erb, source/user-guide/how-to-setup-secure-commit.html.md.erb
As part of 
Daniel the Manual Spaniel
APP  09:31
Hello :feet:, this is your friendly manual spaniel. I've found 4 pages that are due for review:
- How to add an ECR for shared Docker images (yesterday)
- [How to import a public SSL certificate into AWS Certificate Manager on Windows](https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/certificate-import-windows.html) (yesterday)
- [How to setup secure commit](https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/how-to-setup-secure-commit.html) (yesterday)
- [Getting AWS Credentials](https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/getting-aws-credentials.html) (yesterday)
i have reviewed the documents and they don't need any updates at the moment …
=> Update to documentation

terraform/environments/sprinkler/iam.tf
[#8964](https://github.com/ministryofjustice/modernisation-platform/issues/8964)
These roles are created solely for testing purposes. Later, these test roles are assumed in the workflow to test the Terraform applying feature.
=> Added new roles to test POC

environments-networks/house-sandbox.json, environments-networks/platforms-test.json, policies/networking/expected.rego
#9238 
Switches RAM association from platforms-test to house-sandbox due to issues using the former.
=> New RAM assignment for cooker-test

.github/ISSUE_TEMPLATE/out-of-hours-support-request.yml
Creating ahead of this PR - https://github.com/ministryofjustice/modernisation-platform/pull/9352
=> Creation of template before docs merge

.github/workflows/generate-dependabot-signed-commits.yml
Update test dependabot workflow to use newly created github action
=> Switch to GitHub action from workflow

collaborators.json
Need to add a CICA external contractor as a collaborator to allow him to run local plans
Adds him as collaborator
Testing after apply
None
=> Adding Toby Petty as Ingestion Dev Collaborator

source/runbooks/adding-collaborators.html.md.erb
small change to clarify the roles available to collaborators.
=> Update user doc

environments/maat.json
=> Provide sandbox access to MAAT account

terraform/environments/core-network-services/route53.tf
Requested via ask channel: https://mojdt.slack.com/archives/C01A7QK5VM1/p1740673725167219
Updates naming accordingly.
=> Update r53 zone names

.github/workflows/generate-dependabot-signed-commits.yml
testing updated action with added debugging
=> Update workflow for testing with updated action

environments/cooker.json, policies/networking/expected.rego
These are the changes generated by the delete account process.
See #9238 
=> Delete cooker environments 1741008571

.github/workflows/format-code.yml
#8757 
Fixed to v1.1.0
https://github.com/ministryofjustice/modernisation-platform/actions/runs/13634945111/job/38111257603
and
https://github.com/ministryofjustice/modernisation-platform/pull/9444
=> Issue/8757 - Fixed to v1.1.0

environments/ccms-ebs-upgrade.json
Create a new component for multi pipeline feature #9434 
Followed documentation for multi pipeline steps, hasn't been tested yet.
=> CC-3225: Added component for anonymisation

environments/bacway.json, policies/environments/expected.rego
#9289 
Creates an account for the Backway application.
Follows our new account runbook
=> Create `Bacway` account

environments-networks/laa-development.json, environments-networks/laa-preproduction.json, environments-networks/laa-production.json, policies/networking/expected.rego
#9289 
Sets up necessary configuration for networking
Followed steps in [team runbook](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/creating-accounts-for-end-users.html#networking-stage).
=> `Bacway` account networking

source/team/terraform-style-guide.html.md.erb
Noticed some missing line breaks in the style guide at the end
Adds mising line breaks
=> Fix formatting of style guide

terraform/environments/bootstrap/member-bootstrap/iam.tf
I am trying to use a workflow that modifies a load balancer rule when needed, this will allow the permission for it
Just the PR checks
It shouldn't be a large change
=> add lb rule modification to oidc role

environments/ccms-ebs-upgrade.json
Create a new component for multi pipeline feature #9489
=> Added component for sandbox

collaborators.json
N/A - received via DM
Adds further environments for Stephen Hobden
Test through CI pipeline checks
=> Add further access to YJAF accounts for Stephen Hobden

collaborators.json
remove collaborator as per ticket https://github.com/ministryofjustice/modernisation-platform/issues/9429
=> Remove Collaborator - yordi.tak

.trivyignore.yaml, terraform/environments/core-shared-services/s3_malware_protection.tf
#8605 
This PR changes the malware detection alerting approach from CloudWatch metric alarms to EventBridge rules, ensuring real-time alerting and better security. It also adds KMS encryption to SNS to enhance security for alert messages.
CloudWatch metric alarm has delays in reporting malware, whereas eventbridge is immediate. 
=> update how the alerting is done

environments/delius-core.json
#9239
Reinstates accidentally deleted key
=> added accidentally deleted key to zaizi devs

source/runbooks/dos-attack.html.md.erb, source/runbooks/migrating-an-account-into-the-modernisation-platform.html.md.erb, source/runbooks/modifying-scps.html.md.erb, source/runbooks/using-athena.html.md.erb, source/user-guide/how-to-setup-code-scanning-locally.html.md.erb
=> User Guide & runbook review.

source/user-guide/access-key-management.html.md.erb
=> Docs  access-key-management.html.md.erb

.github/workflows/new-environment.yml
https://github.com/ministryofjustice/modernisation-platform/issues/9024
Updated `new-environment.yml` to fetch secrets from aws-secrets-manager using github action
=> Fetch secrets from aws-secrets-manager

terraform/environments/core-vpc/providers.tf
As part of Add default tags to terraform providers across the modernisation platform
#1519
This PR adds the default tags to the core vpc environment
=> Adding tags to core vpc environment

terraform/environments/bootstrap/single-sign-on/policies.tf
=> Add DE S3tables access

terraform/environments/bootstrap/single-sign-on/policies.tf
as part of investigateing AWS detective i need to give the modernisation platform engineer role extra permissions 
This Pr adds the necesary permisssions required
=> Adding extra permission to investigate aws detective

environments/analytical-platform-ingestion.json
https://github.com/ministryofjustice/modernisation-platform/issues/9610
Adheres to runbook.
¯\_(ツ)_/¯
New infrastructure, nothing to break. 
=> :wrench: Create `transfer-family` component in `analytical-platform-ingestion`

environments/data-platform-apps-and-tools.json
The introduction of this tag means we have to roll EKS nodes to apply it
I need to perform some emergency patching
Removes it, this env is going to be decommissioned anyway
It hasn't
I don't believe so, scoped to this environment/application
=> 🏷️ Remove CNI tag from DPAT environment

terraform/modernisation-platform-account/iam.tf
Updates superadmins module
This was added to resolve a conflict where users couldn't reset the randomly generated console password on first login due to requiring MFA.
Tested on a real user by manually updating policy
=> Bump modernisation-platform-terraform-iam-superadmins module to v2.1.0

.github/workflows/terraform-member-environment.yml, terraform/environments/youth-justice-app-framework/iam.tf, terraform/environments/youth-justice-app-framework/providers.tf
Adding codedeploy
Request - https://moj.enterprise.slack.com/archives/C01A7QK5VM1/p1743086456236989
=> Circle ci permissions

collaborators.json
=> Additional collab permissions re issue 9613

collaborators.json
https://mojdt.slack.com/archives/C01A7QK5VM1/p1743413672921419
https://mojdt.slack.com/archives/C01A7QK5VM1/p1743418556680159
=> Add Ryan as a collaborator and remove Umesh

environments/coat.json, policies/environments/expected.rego
As per new account request https://github.com/ministryofjustice/modernisation-platform/issues/9631
=> COAT Environment Step 1

terraform/environments/digital-prison-reporting/providers.tf
Discovered after this PR for YJAF 
https://github.com/ministryofjustice/modernisation-platform/pull/9633/files
=> Fix DPR pipeline.

terraform/environments/youth-justice-app-framework/iam.tf
As part of member request : -
Thomas Tipler
12:26
Hi, Can we please have an additional permission added to our circleci IAM role for youth-justice-app-framework
circleci_iam_role
codedeploy:GetApplicationRevision
This PR adds inthe nesacerry permissions required to the iam role
=> youth justice iam change

environments-networks/platforms-development.json, environments-networks/platforms-production.json, policies/networking/expected.rego
Setup networking for new COAT account request as per https://github.com/ministryofjustice/modernisation-platform/issues/9631
=> COAT Environment Step 2 - Networking

environments/analytical-platform-compute.json
Adding a bedrock component for providing the service to central digital product team
Post-deployment
N/A
It's a new component but not new functionality
=> Adding central-digital bedrock component for product team

scripts/generate-dependabot-file.sh
This PR updates the `generate-dependabot-file` script to use `directories` rather than `directory` as well as grouping the GitHub Actions dependencies into a single PR helping to reduce the number of :dependabot: reviews 
Script tested locally and produces the expected dependabot file successfully
=> :dependabot: Update Generate Dependabot File script

environments/mojfin.json
=> CC-3330: Added SSO group for MOJFIN SSM users

collaborators.json
#9723
Removes inactive collaborator
Complete removal by applying change locally through terraform under administrator privileges as CI cannot be used to delete users.
=> Removed inactive collaborator

.github/workflows/access-keys-monitoring.yml, .github/workflows/secrets-rotation-reminder.yml
#9024 
Fixes two sets of issues missed from earlier PR
=> #9024-Bugs

collaborators.json
Satisfies [this](https://github.com/ministryofjustice/data-platform-support/issues/1231) user request.
Duplicates the code for the other MadeTech user - Toby Petty.
NA
I don't think so.
=> 👥 Add Russel McLean as Collaborator

terraform/modernisation-platform-account/secrets.tf
Reverts ministryofjustice/modernisation-platform#9747
=> Revert "Issue/9024 testing keys"

.github/workflows/generate-dependabot-file.yml, .github/workflows/new-environment-files.yml, .github/workflows/new-member-environment-files.yml
#9024 
Adds missing id-token: write permissions to failing workflows.
=> Adds missing  id-token: write permissions.

environments-networks/yjb-development.json
=> adds new sm endpoint for yjb-development vpc

.github/workflows/prune-stale-branches.yml
https://github.com/ministryofjustice/modernisation-platform/issues/9556
This PR ensures that current code works for other repo's which are not Mod Platform Repo
Deletion worked for modernisation-platform-terraform-iam-superadmins repo, please see below.
https://github.com/ministryofjustice/modernisation-platform/actions/runs/14358837165/job/40254742859#step:5:189
=> Feature 9556 auto pruning of stale branches

terraform/modernisation-platform-account/iam.tf
Reverts ministryofjustice/modernisation-platform#9766
=> Revert " Allow all branches in OIDC trust relationship for temporary workaround"

.github/workflows/reusable-signed-commit.yml
as a modernisation platform engineer i want workflows to have proper name not the locations when you look at them in the actions screen
corrects the name on a work flow so that it displays correctly
=> amendment to commit workflow

source/getting-help/index.html.md.erb, source/runbooks/creating-accounts-for-end-users.html.md.erb, source/runbooks/revoke-network-access.html.md.erb, source/runbooks/yjaf-account-creation.html.md.erb, source/runbooks/yjaf-delete-account.html.md.erb, source/user-guide/creating-networking.html.md.erb, source/user-guide/deploying-your-application.html.md.erb
https://github.com/ministryofjustice/modernisation-platform/actions/runs/14360822997/job/40384316744#step:4:58 
Going to raise a new PR.
=> reverts doc changes from pr 9764

source/getting-help/index.html.md.erb, source/runbooks/creating-accounts-for-end-users.html.md.erb, source/runbooks/revoke-network-access.html.md.erb, source/runbooks/yjaf-account-creation.html.md.erb, source/runbooks/yjaf-delete-account.html.md.erb, source/user-guide/creating-networking.html.md.erb, source/user-guide/deploying-your-application.html.md.erb
Updated documents flagged by Daniel the spaniel, and updated the title for YJAF runbooks.
=> Update docs to keep them up-to-date

collaborators.json
=> Add David Reid as delius-core collaborator

collaborators.json
Reverts ministryofjustice/modernisation-platform#9785
=> Revert "Add David Reid as delius-core collaborator"

collaborators.json
Discussed with Ewa and Simon and Rich. 
Only Ewa to merge if she agrees to it.
=> Permissions change temp - Do not merge 

.github/workflows/publish-gh-pages.yml
=> Re-adds the use of secrets management workflows.

.github/workflows/publish-gh-pages.yml
=> Reverts back to previous version.

environments/core-shared-services.json
#9726 
This PR updates the environment file so that MP can use entra ID to access core-shared-services account.
=> Add Entra ID group to Core-Shared-Services Account

terraform/environments/core-network-services/firewall-rules/preproduction_rules.json
=> Allow LAA LZ UAT Oracle access to MP Preprod for MLRA

terraform/environments/bootstrap/single-sign-on/policies.tf
Was attempting to create an sso-deny policy, but it didn't work
Revert attempt
It'll just get removed
Will this deployment impact the platform and / or services on it? 
No
=> delete attempt at sso-deny tag based policy

environments/core-logging.json, environments/core-network-services.json, environments/core-security.json, environments/core-vpc.json
#9726 
This PR updates the environment file so that MP can use entra ID to access core accounts.
=> Adds entra id group to core accounts

terraform/environments/core-network-services/firewall-rules/preproduction_rules.json
=> Update laa_uat_to_mp_laa_preproduction rule to allow all ports

terraform/environments/bootstrap/member-bootstrap/iam.tf
=> Iam pass role backup for mp cicd role

terraform/environments/bootstrap/member-bootstrap/iam.tf
=> Add iamPass on "datasync.amazonaws.com" for MP cicd role

environments/contract-work-administration.json
=> TM-1190 Update CWA Test env permissions

terraform/environments/core-shared-services/ecr_repos.tf
Fixes issue whereby the module was referencing accounts that have been deleted.
=> Removes references to data-platform-apps-and-tools-development & production

terraform/environments/bootstrap/member-bootstrap/locals.tf
=> Removes references to eric accounts from local.

terraform/environments/core-shared-services/bucket.tf, terraform/environments/core-shared-services/s3.tf
https://github.com/ministryofjustice/modernisation-platform/issues/9571
Updates `core-shared-services` s3 buckets to `v8.2.1`
=> Update `core-shared-services` s3 buckets to `v8.2.1`

environments/core-logging.json, environments/core-network-services.json, environments/core-security.json, environments/core-shared-services.json, environments/core-vpc.json
#9726 
Removing the developer role as it's not needed because I have given MP Entra ID group access to admin and mpengineer role. 
=> Remove developer role as we have access to Admin & MP engineer role

terraform/environments/youth-justice-app-framework/iam.tf
User request via the ask channel
Adds codedeploy:ListApplicationRevisions to circleci_iam_role used by the YJAF environment as requested by Thomas Tippler.
=> Adds codedeploy:ListApplicationRevisions to circleci_iam_role used by the YJAF environment

environments/electronic-monitoring-data.json
We have team members who dont have SC, who need access to the data store. This gives them access to test and dev. (May add preprod in the future).
References the azure group i made.
n/a
n/a
=> Add non prod azure team to emd

environments/analytical-platform-compute.json
https://github.com/ministryofjustice/analytical-platform/issues/7331
https://github.com/ministryofjustice/central-digital-architecture-backlog/issues/13
Creates the component without which we are broken. :(
Test post-deployment
It will not impact services
=> Adding a new PowerBI component to Analytical Platform Compute

collaborators.json
https://mojdt.slack.com/archives/C01A7QK5VM1/p1745587313303509 << requested via Slack
Removes James Round and adds three new pen-testers for YJAF.
=> Remove james round and add three new pen-testers for yjaf

source/runbooks/deleting-an-environment.html.md.erb
Amends the above runbook to add some additional required steps but which were not included.
=> Updated deleting-an-environment runbook.

scripts/account-deletion/delete-accounts.sh
Error in script identified casued by addition space
=> :bug: Fix script error

source/runbooks/deleting-an-environment.html.md.erb
=> Correct workflow to be disabled.

source/team/vision.html.md.erb
https://mojdt.slack.com/archives/C013RM6MFFW/p1745834634643169
=> Changed dates

terraform/environments/bootstrap/member-bootstrap/iam.tf
https://moj.enterprise.slack.com/archives/C01A7QK5VM1/p1746016006240269
Should add required permissions
=> Member Access Permissions - Config:*

terraform/environments/bootstrap/member-bootstrap/iam.tf
As per title, this is required to allow the referenced account to use the grant in question.
=> Adds electronic-monitoring-preproduction to the account list.

terraform/environments/bootstrap/member-bootstrap/iam.tf
Requested in Slack https://mojdt.slack.com/archives/C01A7QK5VM1/p1746090624662809
Adds `ec2:*ManagedPrefixList*` to the `MemberInfrastructureAccess` role.
Wildcards added flexibility and will allow...
```
CreateManagedPrefixList
DeleteManagedPrefixList
DescribeManagedPrefixLists
GetManagedPrefixListAssociations
GetManagedPrefixListEntries
ModifyManagedPrefixList
RestoreManagedPrefixListVersion
```
=> Adds `ec2:*ManagedPrefixList*` to pipeline role

terraform/environments/core-network-services/secrets.tf
As per email from AWS on the invalid statement.
=> Adds missing resources entry for malformed policy statement.

.github/workflows/new-member-environment-files.yml
Reverts ministryofjustice/modernisation-platform#9907
=> Revert "Switch New-Memeber-Environmnet-Files to signed commit"

terraform/environments/bootstrap/member-bootstrap/iam.tf
As per Slack request https://mojdt.slack.com/archives/C01A7QK5VM1/p1746175039547419 user is requesting permissions for FIS (Fault Injection Service) https://aws.amazon.com/fis/
=> Add FIS (Fault Injection Service) Permissions

environments-networks/platforms-development.json, policies/networking/expected.rego
Networking step for dummy account
=> Create Dummy Account for testing - Step 2

terraform/environments/core-network-services/vpn_attachments.json
Required for the SRX work on the YJAF networking account. 
Created the customer gateway object and the site to site VPN
N/A
Merge and deploy
=> YJB Juniper vSRX VPN to MP TGW

source/runbooks/rotating-secrets.html.md.erb
=> Minor updates to the xsoar key section.

.github/workflows/prune-stale-branches.yml
Add pagination to branch fetch to ensure all branches are checked for staleness. Without pagination, only the first page of branches was being processed, which caused some stale branches to be missed.
=> Ensure all branches are checked by adding pagination to branch listing

terraform/environments/core-network-services/locals.tf, terraform/environments/core-network-services/vpn.tf
Second part of the YJB networking changes for the network account.
=> Added aws_ec2_transit_gateway_route_table_propagation for yjb

terraform/environments/bootstrap/secure-baselines/main.tf
#9831 
Adds a new SNS topic for High Priority alerts. Sets the root account access alarm to use this alert.
See sprinkler below.
=> Issue/9831 - Sets baselines to v7.13.4 to new high-priority SNS channel.

terraform/modules/core-monitoring/main.tf
Reverts ministryofjustice/modernisation-platform#9954
=> Revert "issue/9831 - PagerDuty Subscription for high-priority alerts."

terraform/environments/bootstrap/secure-baselines/main.tf
Reverts ministryofjustice/modernisation-platform#9953
=> Revert "Issue/9831 - Sets baselines to v7.13.4 to new high-priority SNS channel."

terraform/environments/core-logging/ip_utilisation.tf, terraform/environments/core-logging/lambda/ip_utilisation/ip_usage_metrics.py
https://github.com/ministryofjustice/modernisation-platform/issues/8334
Adds lambda function and associated permissions to monitor ip usage in core-vpc accounts
=> Deploy Lambda function for monitoing IP usage

terraform/environments/core-logging/ip_utilisation.tf, terraform/environments/core-logging/lambda/ip_utilisation/ip_usage_metrics.py
https://github.com/ministryofjustice/modernisation-platform/issues/8334
This adds a 5 minute timeout to the IP monitoring lambda (as it was timing out in 3 secs!) and enables publishing metrics to cloudwatch in the core-logging account rather than each core-vpc account individually.
=> Update IP Monitoring Lambda config

source/user-guide/how-to-update-pagerduty-status-page.html.md.erb
As part of Daniel the Manual Spaniel
APP  10:31
Hello :feet:, this is your friendly manual spaniel. I've found a page that is due for review:
- How to update the PagerDuty status page for the Modernisation Platform (today)
i have reviewed and updated the documentation
=> Pager duty update

terraform/environments/bootstrap/secure-baselines/main.tf, terraform/modernisation-platform-account/baselines.tf
#9831 
Updates version of Baselines to fix dependencies on high-priority SNS topic name.
See the details of the Baselines PR - https://github.com/ministryofjustice/modernisation-platform-terraform-baselines/pull/799
Note that the tests for this PR will show no change as the scope of the change has already been applied to Sprinkler in support of the above tests.
=> This updates Baselines to 7.13.7

terraform/modernisation-platform-account/baselines.tf
Adds additional parameter for baselines in modernisation-platform-account
=> issue/9831 - Modernisation-Platform-Account

terraform/environments/bootstrap/member-bootstrap/iam.tf
adding quicksite to github role
adding permissions to the github role
=> quicksite oicd changes

environments/laa-portal-tactical.json, policies/environments/expected.rego
=> New accounts for LAA Portal 1.5

terraform/environments/core-logging/ip_utilisation.tf
Removing chatbot config temporarily while I figure out how best to configure this.
=> Remove chatbot config

terraform/environments/core-logging/ip_utilisation.tf
The alarm was not properly tracking the metrics for ip usage. The metric name was incorrect and I have update the config so all of the associated dimensions are listed as wildcards which should fix it.
=> Update ip usage alarm 

terraform/environments/bootstrap/member-bootstrap/iam.tf
Quickstite is failing in the pipline due to missing permissions
added missing permission to the role
=> Adding extra permissions to github oidc

environments/laa-portal-tactical.json
=> Provide tactical portal prod sandbox access

source/runbooks/manage-an-incident.html.md.erb
#9827 
Most up to date information on reporting security incidents. 
=> Updated security incident reporting instructions

terraform/environments/core-logging/ip_utilisation.tf, terraform/environments/core-logging/lambda/ip_utilisation/ip_usage_metrics.py
This PR updates the ip utilisation lambda function to publish results of any subnets with over 90% utilisation directly to SNS>ChatBot>Slack instead of using a CW metric filter which was proving more complicated i.e. needing a metric filter per subnet (>500!) or having a more generic alert that fires whenever any 1 subnet hits the threshold (requiring you to go in and find the finer detail.)
This setup publishes the pertinent details directly to the channel allowing the receiver to investigate accordingly.
More details could be injected into the alert but for now I think this is optimal.
As it's been a bit tricky to debug issues I did try by …
=> Updates ip utilisation lambda function to publish results directly to Slack

source/runbooks/manage-an-incident.html.md.erb
Improving the visual layout, as the text was too crowded.
Also, just making doc neater and remove headings for the overview. 
=> fix formatting issue

terraform/environments/core-vpc/locals.tf, terraform/environments/core-vpc/monitoring.tf
#9976
PR creates the metric filters and respective alarms below, for LAA flow logs:
- AcceptedTraffic
- RejectedConnections
- SSHConnectionAttempts
PR to configure Configure alerting to Slack and PagerDuty will follow
Local terraform Plan
=> Implement CloudWatch Anomaly Detection for VPC Flow Logs (Pilot)

terraform/environments/core-vpc/monitoring.tf
(https://github.com/ministryofjustice/modernisation-platform/actions/runs/15043325740/job/42279949611#step:17:2139)
PR fixes the issue by ensuring two elements of the metrics list returns data.
Local Terraform Plan
=> fix for api error validation

terraform/environments/bootstrap/member-bootstrap/iam.tf
In relation to https://github.com/ministryofjustice/modernisation-platform-environments/pull/10612 and https://github.com/ministryofjustice/modernisation-platform/pull/10055
Adds the required permissions
Sprinkler bootstrap
=> Add permissions for VPC peering to member pipelines

environments/maat.json
https://mojdt.slack.com/archives/C01A7QK5VM1/p1747663378104299
Grants `laa-sre-admins` group to access all `maat` accounts
=> Grant `laa-sre-admins` group to access all `maat` accounts

environments/maat.json
Crime apps team added to MAAT in all environments.
=> Add crime apps team to MAAT.

environments/maatdb.json
Crime apps team added to MAAT DB dev environment.
=> Add crime apps team to MAAT DB in dev

environments/maatdb.json
As Part of the maatdb migration we need to create new account for prod preprod and test
This PR adds in the new accounts
=> New accounts for maatdb

environments/laa-ccms-soa.json, environments/laa-ccms.json, policies/environments/expected.rego
Create new accounts for LAA-CCMS as per https://github.com/ministryofjustice/modernisation-platform/issues/10084
=> Create new account for LAA-CCMS-SOA - Step 1

environments/maatdb.json
See above.
Adds access for the laa_maat_migrations github group
=> Adds access for the laa_maat_migrations github group

environments/maatdb.json
Fixes codeowners to allow PR approval.
=> Updates codeowners

source/runbooks/integration-with-protective-monitoring.html.md.erb
The formatting for the cortex doc wasn't rendering quite right e.g. bullet points not displaying correctly.
I've just added a few spaces etc. so that it looks clearer.
=> Update formatting to display better in the docs

environments/maatdb.json
Triggering github workflow for maatdb so i can debug and test a theory I have about an issue Mike shared with me earlier.
=> Trigger Workflow

terraform/environments/core-shared-services/ecr_repos.tf
Add new ECR repos for SOA components (two repos)
New components, no tests can be performed
New resources, N/A
=> feat: add soa ecr repos

environments/maatdb.json
=> Update github_action_reviewer for MAATDB

environments/maat.json
=> Update MAAT permissions github reviewer

terraform/environments/core-vpc/monitoring.tf
[#9976](https://github.com/ministryofjustice/modernisation-platform/issues/9976)
PR adds alarm trigger to existing cloudwatch alarms
Please see tests below.
=> adding alarm trigger for my logs

collaborators.json
User removal request 
Hi,
We have been informed of the following:
Lucie Woellenstein has left YJB. Could all her user accounts be closed please?
Many thanks,
Rhian Manley (she/her)
Head of Statistics and Analysis
T: 07929712426
Could you please close down Lucie’s AWS account and let me know once its been actioned?
Kind Regards
Dale Tritschler
Support Consultant
NEC Digital Studio
Code for the user removed
=> Removed yjaf user

source/team/operational-processes.html.md.erb
https://mojdt.slack.com/archives/C013RM6MFFW/p1748008754071029
Temporarily update the on call email with the direct PD integration email. Review in 2 weeks.
=> Update on call email temporarily

environments/property-cafm-data-migration.json
New GitHub team created for propert-cafm-migration
=> Update sso team

source/runbooks/adding-admin-data-lake-formation-permissions.html.md.erb, source/team/roadmap.html.md.erb
=> User guide reviews

terraform/environments/core-shared-services/ecr_repos.tf
=> CC-3639: Create ECR repo for CCMS EDRMS to host docker image

collaborators.json
This PR removes Neil as a collaborator, as he no longer requires access. #9964
=> Remove Neil's collaborator access

terraform/environments/core-network-services/firewall-rules/preproduction_rules.json
New Firewall rules for preproduction to match what we have put in place for test and development
Firewall rules added and preprod put into alert mode
=> PreProd firewall rules

terraform/environments/core-vpc/monitoring.tf
[#9976](https://github.com/ministryofjustice/modernisation-platform/issues/9976)
Adjusted evaluation period for the 3 alarms 
See below
=> Adjusted evaluation periods for the 3 alarms

environments/analytical-platform-compute.json
Adding cluster and network components
n/a
n/a
no
I'd ordered them as well
=> Add cluster and network components to Analytical Platform Compute

terraform/environments/core-network-services/vpn_attachments.json
=> CC-3621a: Added Prod NEC VPN

terraform/environments/core-network-services/firewall-rules/preproduction_rules.json
spotted a few issues with new reverse lookup rules this have now been corrected
fix nameing and routes
=> fix preprod changes

source/concepts/networking/dns.html.md.erb, source/runbooks/enabling-shield-advanced.html.md.erb, source/team/operational-processes.html.md.erb, source/user-guide/how-to-configure-dns.html.md.erb
=> 🐶 daniel the spaniel reviews

terraform/environments/core-network-services/firewall-rules/preproduction_rules.json
=> Updates preprod rules.

terraform/environments/core-network-services/cidr-ranges.tf, terraform/environments/core-network-services/firewall-rules/development_rules.json, terraform/environments/core-network-services/firewall-rules/inline_rules.json, terraform/environments/core-network-services/firewall-rules/preproduction_rules.json, terraform/environments/core-network-services/firewall-rules/sets.json
Amends ftp f/w rules from private subnets. Adds inline rules for development.
=> Amends laa sets and adds private-general rules for ftp outbound.

terraform/environments/core-network-services/firewall-rules/test_rules.json
=> Changes ALERT to PASS.

terraform/environments/core-network-services/firewall-rules/development_rules.json
revert any rule for laa dev, issues with testing
=> revert dev any rule for laa

terraform/environments/core-network-services/vpn_attachments.json
Reverts ministryofjustice/modernisation-platform#10296
=> Revert "Update vSRX02 cgw IP for testing"

terraform/environments/digital-prison-reporting/iam.tf
Update ECR Permissions
The permissions are required for the CICD Pipeline to create the ECR Repository/Image
Automates Repo creation
Yes on Development Environment, DPR Sandbox
N/A
=> Update ECR Permissions

environments/dummy1.json, policies/environments/expected.rego
Testing account creation as part of issue https://github.com/ministryofjustice/modernisation-platform/issues/9700
=> Trigger Account Creation Process

.github/workflows/new-member-environment-files.yml
test updated version of signed-commit - https://github.com/ministryofjustice/modernisation-platform-github-actions/commit/e0df4eede6fde06c2f9b1d4d568b92d8cc514463
=> Test Updated version of signed commit

terraform/environments/core-logging/s3_logging.tf
https://github.com/ministryofjustice/modernisation-platform/actions/runs/15758025045/job/44418531682#step:17:1115
[#10271](https://github.com/ministryofjustice/modernisation-platform/issues/10271)
PR should fix the error
=> fix for kms error

terraform/environments/core-logging/s3_logging.tf, terraform/environments/core-logging/sqs.tf
https://github.com/ministryofjustice/modernisation-platform/actions/runs/15758025045/job/44418531682#step:17:1115
[#10271](https://github.com/ministryofjustice/modernisation-platform/issues/10271)
tested locally and fix worked
=> fix for kms key error

source/concepts/sdlc/patching.html.md.erb, source/concepts/sdlc/testing-strategy.html.md.erb, source/runbooks/joining-the-team.html.md.erb, source/user-guide/automated-patching.html.md.erb
=> Docs 200625

.github/workflows/new-member-environment-files.yml
Reverting changes and testing latest sign-commit action https://github.com/ministryofjustice/modernisation-platform-github-actions/commit/2ef8ad8d345300905d3d95253cb7f5a5dc2c0abe
=> Reverting Changes

terraform/environments/core-network-services/route53.tf
=> Fix to correct name

environments/property-cafm-data-migration.json
=> Adds a production env for property-cafm data migration

source/team/operational-processes.html.md.erb, source/user-guide/creating-resources.html.md.erb, source/user-guide/integrating-alarms-with-pagerduty-with-slack.html.md.erb
https://mojdt.slack.com/archives/C013RM6MFFW/p1750757589082679
Minor updates to the docs highlighted for review. I have left the on-call process as a two week review as I've raised a query with digital IT forum about setting up an alias for on-call email support. Hopefully we can find out what needs to be done soon.
=> Minor updates to docs

environments/delius-iaps.json
=> TM-1367 IAPS access to ACP team

terraform/environments/core-network-services/vpn_attachments.json
Reverts ministryofjustice/modernisation-platform#10520
=> Revert "Update vpn_attachments.json for yjaf migration"

.github/workflows/new-environment.yml, environments/sprinkler.json, scripts/json-changes-notifier.py
#10266 
Switches JSON change notifications from file links to PR links for better context.  
=> Update JSON change notifications to reference PR instead of file

scripts/json-changes-notifier.py
Updates JSON Notification PR link
=> Update json notification link

terraform/environments/core-logging/r53_logs.tf
https://github.com/ministryofjustice/modernisation-platform/issues/10489
Fixing reference to ram shared query config in eu-west-1
=> fix/reference eu-west-1 resource share

terraform/environments/core-vpc/monitoring.tf
#10239 
Increasing the anomaly band to reduce unnecessary alerts 
=> Increase anomaly detection threshold for rejected connections alarm

environments-networks/hmpps-production.json, policies/networking/expected.rego
Networking Step for new account request https://github.com/ministryofjustice/modernisation-platform/issues/10516
=> New Account - Delius-Core-Training - Step 2

terraform/environments/core-network-services/firewall-rules/development_rules.json
As part of testing firewall rules i am putting the laa any rule in dev back to alert mode so i can monitor for possible ports that are missing
=> Changing dev any rule to alert

environments/maat.json, environments/mlra.json
https://mojdt.slack.com/archives/C01A7QK5VM1/p1751366405611729
Email contact updated as required
=> Updating laa crime apps email contact address

terraform/environments/core-logging/s3_logging.tf
[#10271](https://github.com/ministryofjustice/modernisation-platform/issues/10271)
This PR enhances the centralized WAF logging solution by integrating CloudWatch Logs and Kinesis Firehose for secure, cross-account log delivery to S3.
Key changes include:
- Updates to IAM policy documents to allow both Firehose and CloudWatch Logs services to use KMS encryption/decryption, scoped to the organization.
- Addition of a CloudWatch Log Destination and destination policy to enable member accounts to send logs cross-account.
- New IAM roles and policies for CloudWatch Logs to deliver to Firehose.
- Firehose delivery stream now uses GZIP compression for stored logs.
- Updated resource permissions (PutLogEvents, PutRecord, etc.) to support new delivery mechanisms.
- These changes improve log …
=> Centralized WAF logging

terraform/environments/core-shared-services/ad-fixngo.tf
Unify the network rules between Azure and AWS for our DC's.
Updates the Netbios rule and the instance tags.
No
=> TM-1378: Update-dc-rules-and-tags

terraform/environments/core-network-services/vpn_attachments.json
Reverts ministryofjustice/modernisation-platform#10521
=> Revert "Revert "Update vpn_attachments.json for yjaf migration""

terraform/environments/core-network-services/vpn_attachments.json
Reverts ministryofjustice/modernisation-platform#10585
=> Revert "Revert "Revert "Update vpn_attachments.json for yjaf migration"""

terraform/environments/core-shared-services/ecr_repos.tf
There needs to be an ECR repo for VCMS images.
It creates a VCMS ecr repo.
Just the PR runs.
No.
None.
=> add ecr repo for vcms

terraform/environments/core-logging/sqs.tf
Adding back KMS key which was working
PR adds back KMS key which was working
Please see tests below
=> Putting back AWS Mannaged Key

terraform/environments/core-vpc/monitoring.tf
=> changing the threshold back after successful testing

terraform/environments/core-vpc/monitoring.tf
=> Change the thresholds back after successful testing

environments-networks/platforms-development.json, policies/networking/expected.rego
New Environment request step 2 - https://github.com/ministryofjustice/modernisation-platform/issues/10010
=> New Environment Request - JDDH - Step 2

environments/analytical-platform-next-poc-hub.json, policies/environments/expected.rego
New Environment request step 1 - https://github.com/ministryofjustice/modernisation-platform/issues/10524
=> New Environment Request - APNH - Step 1

environments/analytical-platform-next-poc-producer.json, policies/environments/expected.rego
New Environment request step 1 for https://github.com/ministryofjustice/modernisation-platform/issues/10525
=> New Environment Request - APNP - Step 1

environments/example.json
https://github.com/orgs/ministryofjustice/projects/17/views/4?pane=issue&itemId=113433558&issue=ministryofjustice%7Cmodernisation-platform%7C10215
This PR ensures that example account can now be nuked
=> added example account to be nuked

environments/ccms-ebs.json
=> added new group for instance management permissions

collaborators.json
=> Adds Brian as a collaborator to access ospt-transfer bucket in LTS prod account

environments/analytical-platform-compute.json
https://mojdt.slack.com/archives/C01A7QK5VM1/p1752575920637279
=> Removing powerbi component

terraform/environments/core-network-services/firewall-rules/development_rules.json
adding a rule for ccms soa
found no rule for ccms soa to laa development from mp adding new rule
=> adding rule for soa

collaborators.json
https://github.com/ministryofjustice/modernisation-platform/issues/10970
Grants David Seekins data-scientist access for testing. This is a new role which is being tested which I have manually deploye din these accounts. After testing it will deployed as a proper platform role.
=> Grant David Seekins data-scientist access for testing

terraform/environments/core-network-services/firewall-rules/development_rules.json, terraform/environments/core-network-services/firewall-rules/preproduction_rules.json
After reviewing the firewall logs for over 2 weeks i have not found anything that is getting blocked
This PR removes the any rule for the app stream and shared service vpc's for development and preproduction
=> Remove any rule for appstream/shared services

terraform/modernisation-platform-account/s3.tf
New accounts need adding to the statement
Adds them
no
no
=> 📜 Update Analytical Platform account IDs

source/concepts/sdlc/user-workflow.html.md.erb, source/runbooks/accessing-the-observability-platform.html.md.erb, source/runbooks/running-emergency-patching.html.md.erb, source/user-guide/adding-vpc-endpoints.html.md.erb, source/user-guide/environments-networks-json-explained.html.md.erb
=> Docs review 23-07

environments/laa-enterprise-service-bus.json, policies/environments/expected.rego
[#11076](https://github.com/ministryofjustice/modernisation-platform/issues/11076)
PR creates json file and adds the new app to environment.json and expected.rego
see tests below
=> new app - laa-enterprise-service-bus

collaborators.json
https://github.com/ministryofjustice/modernisation-platform/issues/10970
Grants  Oriana data-scientist access in yjaf prod so she can test the role.
=> Grant Oriana data-scientist access in yjaf prod

terraform/environments/core-network-services/firewall-rules/development_rules.json
after monitoring and adding in extra rules for soa and some testing from the ccms team it's time to remove the any rule for development
PR removed the any rule for development
=> development any rule removed

environments/laa-enterprise-service-bus.json
=> re-trigger New Environment creation for laa-service-bus account

source/user-guide/platform-user-roles.html.md.erb
https://github.com/ministryofjustice/modernisation-platform/issues/10970
Adds explanation of data-scientist role to docs
=> data-scientist role documentation

environments-networks/laa-development.json, policies/networking/expected.rego
New Account setup step 2 - networking
=> New Account setup laa-enterprise-service-bus step 2

environments/long-term-storage.json
Added SSO group `azure-aws-sso-OSPT` with read-only access as users need to review the S3 bucket created in LTS account
=> Added SSO group `azure-aws-sso-OSPT` with read-only access

environments/laa-enterprise-service-bus.json
Member request: https://mojdt.slack.com/archives/C01A7QK5VM1/p1753781549030029
=> Granting dev access to v1-hub20-developers

source/concepts/environments/abac-resource-restrictions.html.md.erb, source/runbooks/duty-rota.html.md.erb, source/runbooks/yjaf-account-creation.html.md.erb, source/runbooks/yjaf-delete-account.html.md.erb, source/runbooks/yjaf-password-reset.html.md.erb, source/user-guide/workflow-status.html.md.erb
```
Daniel the Manual Spaniel
APP  [10:34 AM](https://mojdt.slack.com/archives/C013RM6MFFW/p1753781694588309)
Hello :feet:, this is your friendly manual spaniel. I've found 5 pages that are due for review:
- [GitHub Workflow Action Status](https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/workflow-status.html) (15 days ago)
- [Duty Rota](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/duty-rota.html) (9 days ago)
- [Resource restrictions based on ABAC](https://user-guide.modernisation-platform.service.justice.gov.uk/concepts/environments/abac-resource-restrictions.html) (9 days ago)
- [YJAF AWS IAM Account Creation](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/yjaf-account-creation.html) (7 days ago)
- [YJAF …
```
=> Document reviews

terraform/environments/core-network-services/firewall-rules/preproduction_rules.json
adding in extra rules to cover preproduction soa connections
New rules added
=> laa preproduction changes

.github/workflows/new-environment-files.yml, .github/workflows/new-member-environment-files.yml
bump new member environment files to latest version of signed-commit
=> Bump to latest release of signed-commit

.github/workflows/collaborator-inactivity-monitoring.yml
Added fetch-secrets dependency for notify-collaborator job, so that it will fetch the secrets from the fetch secrets job
=> Added fetch-secrets dependency

terraform/environments/core-shared-services/ecr_repos.tf
Greg Whiting has requested some changes for YJAF ECR repo permissions via Slack
Grants ECR repos permissions as requested 
=> Update yjaf ecr push/pull permissions

source/runbooks/dr-process.html.md.erb, source/team/vision.html.md.erb, source/user-guide/creating-environments.html.md.erb, source/user-guide/platform-user-roles.html.md.erb, source/user-guide/security-testing-and-ithc.html.md.erb
https://mojdt.slack.com/archives/C013RM6MFFW/p1753954504517539
Reviewed and updated docs accordingly
=> Doc updates 31/07/25

source/runbooks/adding-a-new-sso-user-role.html.md.erb, source/runbooks/creating-vpcs.html.md.erb
Hello :feet:, this is your friendly manual spaniel. I've found 2 pages that are due for review:
- [Adding a New SSO User Role](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/adding-a-new-sso-user-role.html) (2 days ago)
- [Creating VPCs in AWS](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/creating-vpcs.html) (2 days ago)
documents reviewed
=> Daniel Documents updates

terraform/environments/core-network-services/firewall-rules/production_rules.json
made slight change to new EIP rule
fix for EIP rule
=> update new eip rule

source/runbooks/adding-collaborators.html.md.erb
- Updated instructions for removing IAM collaborators
- Added step to clean up `additional_reviewers` in `<application>.json` files
=> Update documentation and configuration for collaborator removal

source/runbooks/creating-components-for-member-applications.html.md.erb
https://mojdt.slack.com/archives/C013RM6MFFW/p1754386532426139
Reviewed doc
=> Docs Review

terraform/environments/core-network-services/cidr-ranges.tf, terraform/environments/core-network-services/firewall-rules/production_rules.json, terraform/environments/core-network-services/transit_gateway_connections.tf
N/A
Further restricts access to ECP
Tested through CI
=> Tighten access to ECP

environments/laa-stabilisation-cdc-poc.json
Requested via slack https://mojdt.slack.com/archives/C01A7QK5VM1/p1754409103252399
Grants access as required
=> Add access for v1-hub20-developers

source/runbooks/creating-new-dns-zones.html.md.erb, source/team/operational-processes.html.md.erb, source/user-guide/obtaining-deployment-credentials.html.md.erb
=> 🐶 Daniel Updates - 2025-08-08

terraform/environments/digital-prison-reporting/iam.tf
https://app.circleci.com/settings/project/github/ministryofjustice/hmpps-datahub-landing-zone-processing-lambda?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Fministryofjustice%2Fhmpps-datahub-landing-zone-processing-lambda
Failing Pipeline as its unable to Assume Role,
Yes
Tested for other similar projects,
N/A
https://app.circleci.com/settings/project/github/ministryofjustice/hmpps-datahub-landing-zone-processing-lambda?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Fministryofjustice%2Fhmpps-datahub-landing-zone-processing-lambda
=> Enable Landing Zone Repo to Assume AWS Principal

terraform/pagerduty/locals.tf
Using a data call and removing the old account to fix [this PR](https://github.com/ministryofjustice/modernisation-platform/pull/11237), which failed [here](https://github.com/ministryofjustice/modernisation-platform/actions/runs/16881036904/job/47816702282).
I am not sure if deleting an account will be possible, but giving it a go.
=> Using a data call and removing the old account

terraform/environments/core-network-services/firewall-rules/production_rules.json
Final any rule for LAA prod has been in alert mode since friday and i have not seen any issue sofar 
rule remove
=> remove any rule from production

terraform/pagerduty/locals.tf
This is to fix this pipeline:
https://github.com/ministryofjustice/modernisation-platform/actions/runs/16902575004
=> Adding digital ewas user back to make changes in steps

terraform/modules/collaborators/main.tf, terraform/modules/collaborators/outputs.tf
Dependabot raised this which required some extra updates to support version 6.0https://github.com/ministryofjustice/modernisation-platform/pull/11267/files
Updates made to Dependabot PR to support the new naming conventions introduced in v6.0
Local TF plan with no changes :)
=> Update tf iam-user to v6.0 in collaborators module

terraform/environments/youth-justice-app-framework/iam.tf
Requested here https://mojdt.slack.com/archives/C01A7QK5VM1/p1755198304025899
Adds new project to their approved Circle CI list 
=> Add project to list of approved repos for YJAF circle ci

environments/analytical-platform-common.json, environments/analytical-platform-data-engineering.json, environments/analytical-platform-data.json, environments/analytical-platform-landing.json, environments/analytical-platform-management.json, environments/analytical-platform.json
Reverts ministryofjustice/modernisation-platform#11232 to trigger workflow to test https://github.com/ministryofjustice/modernisation-platform/pull/11273
=> Revert "trigger workflow for multiple envs"

environments/cica-development-sandbox.json, policies/environments/expected.rego
New environment request step 1 - https://github.com/ministryofjustice/modernisation-platform/issues/11227
=> New Environment Request - CICA Development Sandbox - Step 1

terraform/environments/bootstrap/single-sign-on/policies.tf
=> Remove Invalid IAM Identity Center Actions

environments-networks/hmpps-development.json, environments/oasys-national-reporting.json, policies/networking/expected.rego
remove oasys-national-reporting-development - https://github.com/ministryofjustice/modernisation-platform/issues/11083
=> remove oasys-national-reporting-development

source/runbooks/backup-restore-process.html.md.erb, source/runbooks/manage-an-incident.html.md.erb
https://mojdt.slack.com/archives/C013RM6MFFW/p1755595893742499
Reviewed the docs and updated accordingly
=> Daniel documentation review 19/08/25

.github/workflows/securityhub-findings-notification.yml
Update workflow to use the latest release of the Secret action #11304
=> Bump Secret Action to v3.4.2

terraform/github/locals.tf
#11262
The specified users will be added to the `modernisation-platform-security` team.
=> Add Cyber Security team members to the security list

terraform/environments/core-network-services/firewall-rules/test_rules.json
Enable HTTPS traffic from legacy Delius to MP Delius
Create firewall rule
N/A
N/A
N/A
=> Enable legacy to MP https

terraform/environments/core-network-services/transit_gateway_connections.tf
N/A
Tidy up to remove route to unused VPC and route to safe DB VPC
Tested through CI and local plan
=> Adjust routes for ECP

environments/maatdb.json
=> Added laa-dbas to MAAT DB

.github/workflows/scheduled-baseline.yml
Replaced reference to `schedule.yml` with `scheduled-baseline.yml` in the workflow check script.
=> Update workflow reference to `scheduled-baseline.yml`

environments/analytical-platform-compute.json
Resolves https://github.com/ministryofjustice/analytical-platform/issues/8633
=> ⏩ Add Analytical Platform Next component

environments/laa-enterprise-service-bus.json
As part of issue #11342 addtional accounts requested for hub 2.0
new account added to environments file
=> New accounts for hub2.0

terraform/environments/bootstrap/member-bootstrap/iam.tf
Minor change added to validate that the scheduled-baseline workflow trigger works correctly and runs only the intended job when changes are detected.
=> Test scheduled-baseline workflow trigger

terraform/environments/core-shared-services/ecr_repos.tf
=> TM-1338 allow training account to pull and push images

environments/laa-enterprise-service-bus.json
(https://mojdt.slack.com/archives/C01A7QK5VM1/p1756983507498859)
PR actions what was requested by user
=> additional roles for laa-enterprise-service-bus-development account

.github/workflows/create-newenv.yml, scripts/amend-accounts.py, scripts/create-account.py
Been working on some updates to the code to allow for multi role access creation also got the amend account script to work and it now updates the json file based on the app name
Code updated to reflect new changes
=> New code for new accounts

.github/workflows/publish-gh-pages.yml, makefile
Update commit sha to fix failing deployment https://github.com/ministryofjustice/modernisation-platform/actions/runs/17547854964
=> Fixup - correct commit sha

terraform/environments/core-logging/s3_logging.tf
Reverts ministryofjustice/modernisation-platform#11445
=> Revert "Amends cloudtrail bucket policy to fix PutObject AccessDenied errors."

terraform/github/repositories.tf
Reverts ministryofjustice/modernisation-platform#11448
=> Revert "Add new repo for hosting an example cp app "

terraform/modernisation-platform-account/account.tf
To reduce noise in the Modernisation Platform mailbox, as the billing contact seems to just receive invoices, which aren't relevant to the team
Removed Modernisation Platform as The `Billing` Contact for the Management Account and Organisation Security Account
NA
Nope
NA
=> 🔥 Remove Modernisation Platform as Billing Contact

environments/maatdb.json
Corrected the `sso_group_name` value from `laa-dbas` to `laa-dba`.
=> Fix sso_group_name typo

environments/laa-enterprise-service-bus.json
added hub2-prod slack channel for Security Hub Slack Notifications
=> [HUB-148] added hub2-prod slack channel for Security Hub Slack Notifications

environments/ccms-ebs.json
N/A
Creates a component for secure browser to allow independent development
test post-deployment
No
=> Create a Secure Browser Component in CCMS EBS Account

.github/ISSUE_TEMPLATE/new-environment.yml
added missing validation boolen
bug fix
=> fix for validation

.github/workflows/account-network-update.yml
work flow was still running even after skip was implemented
added extra skips to steps in the workflow
=> added extra skips to workflow steps

environments/hmpps-domain-services.json
https://github.com/ministryofjustice/modernisation-platform/issues/11378
Owner consistent with infrastructure-support.
=> Updating owner as per ticket #11378

.github/workflows/create-newenv.yml
change to workflow to remove the issue body text file and remove the need to display the contents of the json file
fix for broken part of the workflow
=> workflow change to fix the removal of issue body

terraform/environments/digital-prison-reporting/iam.tf
=> Onboarding new ProjectID

environments/data-platform.json
Resolves:
- https://github.com/ministryofjustice/data-platform/issues/13
- https://github.com/ministryofjustice/data-platform/issues/14
Creates required components
BAU change
No
=> ✳️ Add Data Platform components

source/runbooks/dos-attack.html.md.erb, source/runbooks/modifying-scps.html.md.erb, source/user-guide/access-key-management.html.md.erb, source/user-guide/accessing-ec2s.html.md.erb, source/user-guide/accessing-the-aws-console.html.md.erb
=> Docs reviews 18/09/2025

.github/workflows/create-newenv.yml
git commit still not working adding permission
adding permission to workflow to fix failed workflow
=> adding  permissions to workflow

terraform/environments/digital-prison-reporting/iam.tf
missing untag permissions, when changing tags
Helps resolve failing pipeline
N/A
=> Update iam.tf with glue:UntagResource policy

environments-networks/hmpps-development.json
I need to connect to lambda in my VPC.
Adds lambda VPC
n/a
n/a
=> Update hmpps-development.json - add lambda endpoint

environments/youth-justice-networking.json
Steve Hobden needs access to approve deployments
Adds his username to the list of approved reviewers
=> Add stephenhobden as reviewer for yjaf networking account

.github/workflows/create-newenv.yml, scripts/create-account.py
After a meeting this morning i pointed out that we are not utilising the github code owners or reviewers or adding them to the json code
this Pr fixes this by amending the scripts and the workflow
=> implementing codeowenrs to json file

.github/workflows/create-newenv.yml
on testing this localy i found it was next executing correctly so have changed the way the script is excuted in the work flow to match the way i have done it localy
change the execution to a one line execution
=> change to how the script is run

scripts/create-account.py
after running a test we have found that the is a strange indent at the beginning of the block this is due to the code adding 4 extra char spaces 
code amended to remove the blank spaces
=> fix rego indent issue

terraform/environments/core-network-services/firewall-rules/production_rules.json
=> TM-1575 allow ldaps connections from legacy to MP

terraform/modernisation-platform-account/secrets.tf
#11298 
This adds a secret to hold the private key for the Modernisation Platform github app.
=> Adds secret and version for the Modernisation Platform Github App.

terraform/environments/core-network-services/firewall-rules/preproduction_rules.json, terraform/environments/core-network-services/firewall-rules/production_rules.json
Open Firewall rules to allow MP LAA VPC to speak to CP
Allows LAA MojFin to communicate with an RDS in CP
Tested in Development
=> update firewall rules to allow mojfin to speak to cp

terraform/environments/core-shared-services/ecr_repos.tf
Create new ECR repos for CCMS applications
Let's us create new ECR repos to push ccms application docker images
N/A
=> Create new ECR repos for CCMS applications

terraform/github/repositories.tf
It was missed in the module creation.
=> Added WAF module to repositories. 

environments/laa-enterprise-service-bus.json
User request from the ask channel  they require a preproduction environment for hub2.0
add in the nesessary filed to the json file
=> New environment for hub2.0

terraform/environments/bootstrap/secure-baselines/main.tf, terraform/modernisation-platform-account/baselines.tf
=> bump baselines to include lifecycle safeguards for SSM service setting

collaborators.json
#11678 
#11680 
#11679 
#11681 
Inactive collaborator account deletions from the terraform state file as per the above tickets. IAM accounts have already been removed manually. 
=> Inactive collaborator deletions on 08/10/25

.trivyignore.yaml
See [this](https://mojdt.slack.com/archives/C013RM6MFFW/p1759935188695189) slack thread for more detail
Added `AVD-AZU-0012` to `.trivyignore` file as it's flagging in SCA as false positive
=> Add AVD-AZU-0012 to .trivyignore 
