.github/workflows/new-environment.yml
scripts/json-changes-notifier.py

This PR introduces a new job and Python script to facilitate timely notifications via Slack and email whenever changes occur in JSON files within the `environments` folder. #7402 
Previously, there was no automated mechanism to notify users about changes in JSON files within the `environments` repository. This PR addresses the issue by:
- Establishing a systematic approach to monitor and notify changes.
- Enhancing responsiveness and ensuring users are promptly informed about critical updates.
Sent test notifications to MP Slack channel and Executed script with mock JSON file changes.
NO

Add new job for JSON change notifications via Slack and email

---

terraform/environments/bootstrap/secure-baselines/main.tf
terraform/modernisation-platform-account/baselines.tf

#7406 
Update to latest baselines module version with includes filter for spurious `ListDelegatedAdministrators` alert
Applied to `sprinkler-development`

Bump baselines module to latest version

---

source/user-guide/creating-environments.html.md.erb

The instructions on the [Creating environments in the Modernisation Platform](https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/creating-environments.html#creating-environments-in-the-modernisation-platform) were showing codeowners in the "blank eample" json but not in the "another example" json code.
It is not generally used and caused an issue with one environment that was built using these instructions. This has since been corrected in New account process incorrectly populates codeowners file
[#7430](https://github.com/ministryofjustice/modernisation-platform/issues/7430).
To ensure it does not happen again a little bit of text has been added to not it is not required and can be ignored. It points to the two pieces of json shown below.

Minor changes to mention not using codeowners when creating environments

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

https://github.com/ministryofjustice/modernisation-platform/issues/6817
I'm adding unit tests to a new aws chatbot terraform module I've created. I was able to run these locally as an administrator but cannot via the testing pipeline and get the following error...
https://github.com/ministryofjustice/modernisation-platform-terraform-aws-chatbot/actions/runs/9988594516/job/27605429883?pr=1#step:6:152
I'm looking to add `chatbot:*` permissions to the member access role. This will enable unit testing on the new module and also in future would allow members to consume the module and set up slack channel configs where required. …

Add aws chatbot permissions to `member-access` policy

---

terraform/environments/bootstrap/single-sign-on/policies.tf

https://github.com/ministryofjustice/analytical-platform/issues/4271
We need to be able to add additional Identity Center groups to QuickSight but doing so via Terraform results in attempt to replace the whole subscription:
https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/9990342858/job/27610845085?pr=7138#step:11:703
We are raising a bug ticket with the aws provider but in the meantime we need to add additional groups to enable testing.
This SSO permission will allow us to add groups via the QuickSight admin console since the groupings are managed via Identity Center
It hasn't. It needs to be tested post-deployment. The specific permission was identified after a cloudtrail search.
There shouldn't be any impact on deployment.

Adding sso:CreateApplicationAssignment so can manage QS Groups via Console

---

terraform/environments/bootstrap/single-sign-on/policies.tf

The work this PR is a part of is being tracked here: 
https://github.com/ministryofjustice/analytical-platform/issues/4358
The problem:
In order to allow the process of sharing resources we have chosen, LakeFormation needs to be updated to `cross-account-sharing-version` 4. Ref: https://docs.aws.amazon.com/lake-formation/latest/dg/optimize-ram.html 
The ability to update the cross account sharing version isn't supported by terraform at present so this needs to be manually done.
This gives the data engineering role enough permissions to make the update in the console once the Lake Formation has been bootstrapped in terraform. 
The permission have been retrieved from CloudTrail
Testing can only happen post-deployment
This …

Adding lakeformation:get and put settings permissions to the data eng role

---

source/concepts/sdlc/sandbox-testing-environments.html.md.erb
source/index.html.md.erb
source/runbooks/adding-collaborators.html.md.erb

Saw that my refactoring of the creating environments docs broke the internal links from some other pages.

fix broken internal document links

---

environments-networks/cica-preproduction.json
environments-networks/cica-production.json
environments-networks/cica-test.json
policies/networking/expected.rego

Change the cica tariff environments to add networking. cica-tariff-development was in place on cica-development.json so I added it to cica-preproduction, production and test.

cica-tariff networking

---

.github/workflows/new-environment.yml

https://mojdt.slack.com/archives/C013RM6MFFW/p1721725689918789
Remove the Slack notification step from the environment_json_changes job so that users are not notified in the MP update channel.

Remove slack notification step from environment_json_changes job

---

.github/ISSUE_TEMPLATE/new-collaborator.yml

#7507
Adds a standard template for requesting external collaborators
Confirmed that this renders through the GitHub webpage [here](https://github.com/ministryofjustice/modernisation-platform/blob/feature/7507-collaborators/.github/ISSUE_TEMPLATE/new-collaborator.yml).
No
I will update the documentation once this PR is complete

New collaborator request template

---

terraform/environments/core-network-services/observability.tf

Refactor the observability_platform_tenant module to use the commit hash rather than version, removing the need for the checkov skips.

♻️  Pin observability_platform_tenant version to commit hash

---

source/runbooks/adding-collaborators.html.md.erb

#7507
Points people reading our docs at the template to add a new collaborator.
Checked that the link was correct

added link to issues page to adding-collaborators docs page

---

source/index.html.md.erb
source/runbooks/adding-a-new-sso-user-role.html.md.erb
source/user-guide/platform-user-roles.html.md.erb

The old document on platform users had incorrect steps describing how to add SSO roles. These have been moved off to their own team runbook and updated to better reflect how roles are added.
I hadn't realised that we'd moved the roles out of the aws-root-account when I wrote the original steps, so this new page more accurately reflects what we need to do.

Update document on platform users

---

terraform/environments/bootstrap/single-sign-on/policies.tf

https://github.com/ministryofjustice/analytical-platform/issues/4461
Users need a way to check their LakeFormation permissions in order to query Athena
Adds the iam action that allows looking up the right permissions in LakeFormation
ref: https://docs.aws.amazon.com/lake-formation/latest/dg/access-control-underlying-data.html
Tested post-apply
This should not impact operational services.

Adding LakeFormation Actions that Queries Permissions Assigned to User

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

Following on from request / issue in raised in the [ask-channel](https://mojdt.slack.com/archives/C01A7QK5VM1/p1721921991134449?thread_ts=1720087038.002219&cid=C01A7QK5VM1) this PR adds the `lambda:UpdateFunctionCode` to the OIDC role.

Add lambda UpdateFunctionCode permission to OIDC role

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

This PR adds necessary permissions to allow the unit test environment to successfully delete cloudtrail logs and S3 bucket. Without these permissions, unit tests are failing due to insufficient access
The added permissions are scoped to specially allow deletion of Cloudtrail logs and S3 Objects with a specific prefix and only on testing-test account. #7307 
By granting required permissions, this PR enables the unit test environment to perform the necessary cleanup actions, ensuring test reliability. This address the current issue where unit tests are failing due to missing permissions.
Testing these permission while testing unit test on testing test account

Enhance Permissions for unit testing Cloudtrail and S3 Bucket deletion

---

environments/electronic-monitoring-data.json

I had previously added the permissions to add cicd to a repo (which ive only just started debugging why it couldnt push), but i never added the name of the repo here.
adds the repo to the list of repos that can use the role
Will this deployment impact the platform and / or services on it? n/a

adding create a data task repo

---

source/runbooks/adding-collaborators.html.md.erb
source/user-guide/accessing-the-aws-console.html.md.erb
source/user-guide/getting-aws-credentials.html.md.erb

https://github.com/ministryofjustice/modernisation-platform/actions/runs/10261428738/job/28389157737
This PR fixes the problem by correcting the internal link in the documentation. The original link pointed to a hash (`github-team-slug`) that did not exist, causing an error. By updating the hash to `sso-group-name`, which exists, the link now correctly points to the intended section, resolving the error.

Fix broken internal link by updating hash from `github-team-slug` to `sso-group-name`

---

.github/workflows/core-vpc-development-deployment.yml
.github/workflows/core-vpc-preproduction-deployment.yml
.github/workflows/core-vpc-production-deployment.yml
.github/workflows/core-vpc-test-deployment.yml
scripts/get-applications-and-run-ram.sh

#7580 
- Added `TF_ENV` variable to all core workflows.
- Updated the script to remove the environment suffix from the account name using the `TF_ENV` variable.
- Ensured proper handling of potential trailing newlines or spaces in the `TF_ENV` variable to avoid mismatches.
Previously, the script failed to remove the environment suffix correctly due to potential hidden characters or mismatches in the environment variable. This inconsistency could lead to errors in account identification and subsequent operations. By introducing `TF_ENV` and sanitizing its input, we ensure the correct suffix removal and improve the reliability of our workflows.
Tested the script locally

Update scripts to use TF_ENV for environment removal from account names

---

terraform/environments/core-shared-services/ecr_repos.tf

After some testing of pushing to the shared services create-a-data-task repo, we want to use some of the images in dev and prod for EM.
Adds the lambda retrieval perms for lambdas in EM prod and dev, and gives pull perms to prod
n/a
no

EM: Add permissions to pull from ECR for different accounts

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

Issue raised in the ask-channel due to OIDC role time outs in for GitHub Actions :  https://mojdt.slack.com/archives/C01A7QK5VM1/p1723642741120779
This PR sets the `max_sessions_duration` to 2 hours (7200 seconds) from the default 1 hour (3600 seconds)
un-tested at present but will apply to sprinkler
No impact expected. 

OIDC Role - Increase Max Session Duration from 1 to 2 hours

---

terraform/environments/bootstrap/secure-baselines/main.tf
terraform/modernisation-platform-account/baselines.tf

https://github.com/ministryofjustice/modernisation-platform/issues/7309 - adding `securityhub-alarms` unit tests
Updates baseline to latest tag v7.6.3 
tested locally and in sprinkler as per workflows below. Zero changes to infrastructure as expected.

Update baselines module to v7.6.3

---

terraform/environments/core-logging/cortex.tf

With an `s3_bucket_acl` resource the following error is triggered:
```
Error: creating S3 Bucket (core-logging-production20240819072032900200000003) ACL: operation error S3: PutBucketAcl, https response error StatusCode: 400, RequestID: 4MFM3A6M2JQS4W01, HostID: 1Kz5QOCX4wNzxBqnSkBn8iaTS0w/DxfbOaVnT1yfoCpefKI6KZoAOgRr6lXVv5xOsbgJ3FM7XwU=, api error AccessControlListNotSupported: The bucket does not allow ACLs
```
Removes the `s3_bucket_acl` resource.
Ran a local plan

Fix terraform for `core-logging` bucket

---

terraform/environments/core-shared-services/ad-fixngo.tf

Cannot complete migration of Azure FixNGo estate without migrating Remote Desktop Licensing server.
Builds a new 2022 licensing server (Azure is 2012) co-located with the Domain Controllers. Needs to be alongside DCs as the licenses are shared across the domain. This PR is for DevTest (azure.noms.root), a subsequent PR will build a licensing server for prod (azure.hmpp.root) if all goes well.
Powershell code for configuring the server has been tested in member account (hmpps-domain-services)
No

DSOS-2919: build azure.noms.root RD Licensing server

---

terraform/environments/core-shared-services/ad-fixngo.tf

Cannot complete migration of Azure FixNGo estate without migrating Remote Desktop Licensing servers.
Builds a new 2022 licensing server (Azure is 2012) co-located with the Domain Controllers. Needs to be alongside DCs as the licenses are shared across the domain. This PR is for Prod (azure.hmpp.root). The DevTest server has been successfully built in https://github.com/ministryofjustice/modernisation-platform/pull/7717
Powershell code for configuring the server has been tested in member account (hmpps-domain-services). DevTest server was built successfully from code.
No

DSOS-2919: build azure.hmpp.root RD Licensing server

---

policies/collaborators/utilities.rego
policies/environments/utilities.rego
policies/member/utilities.rego
policies/networking/utilities.rego

The issue was related to a regal lint error in the utilities.rego file where the variable object was used, which conflicts with a built-in function in Rego. This shadowing of a built-in function caused linting issues, potentially leading to unexpected behavior in policy evaluation. The issue required renaming the variable to avoid conflict with the built-in object function in Rego. #7670 
https://github.com/ministryofjustice/modernisation-platform/actions/runs/10474087493/job/29007520608#step:5:37
This PR fixes the issue where the variable name object was shadowing a built-in function in Rego. The object variable has been renamed to obj to avoid conflicts with the built-in object function, thereby resolving the var-shadows-builtin linting error reported by regal lint.
This change was …

Fix variable shadowing in utilities.rego to resolve Regal linting error

---

terraform/environments/bootstrap/secure-baselines/main.tf
terraform/modernisation-platform-account/baselines.tf

As part of [New Cloud watch alarms](https://github.com/ministryofjustice/modernisation-platform/issues/7450)
#7450
i have done a new release for the secure baselines that removes the NAT alarms. as these are no longer required for the moment
update to new release
tested in sprinkler

update secure baselines version to the latest

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

as part of [Some AWS Nuke workflows fail with error 255](https://github.com/ministryofjustice/modernisation-platform/issues/7623)
#7623 
i have found that one of the accounts in question has a permissions issue this PR is to fix that 
amends the backup section on the eu-central policy doc to be backup:*

Align access eu-central normal

---

terraform/environments/core-logging/cortex.tf
terraform/modules/cloudwatch-firehose/data.tf
terraform/modules/cloudwatch-firehose/main.tf

#7607 
* Updates S3 bucket policy so logs can be delivered
* Sets the S3 bucket to use AWS:SSE for simplicity (we can change this to KMS, but we'll need to consider access to the KMS key from other MP accounts, and the Cortex XSIAM AWS user)
* Resolves some discrepancies and outright errors in IAM policy documents in the module
* Improves policy naming
* Introduces a CloudWatch Log Group for data stream error logging 
Tested with local terraform applies to `core-logging` and `core-vpc` sandbox workspace
The dynamic naming is still possible, but requires that logs be unzipped so that they can be dynamically parsed. As this isn't …

Resolve issues with log streaming module

---

terraform/environments/core-network-services/cidr-ranges.tf
terraform/environments/core-network-services/firewall-rules/live_data_rules.json
terraform/environments/core-network-services/firewall-rules/non_live_data_rules.json
terraform/environments/core-network-services/firewall-rules/sets.json
terraform/environments/core-network-services/locals.tf

Follow on from https://github.com/ministryofjustice/modernisation-platform/pull/7737
The non-live RemoteDesktop Licensing server isn't working due to some connectivity issues.
Adds the non-live Domain Controller and Licence servers firewall rules. These sit in the non-live VNET so additional terraform also required.
Also allows the Azure FixNGo estate to use the licenses on the new prod license server
n/a
No

DSOS-2919: add rd licensing firewall rules part2

---

environments/core-billing.json
policies/environments/expected.rego

This PR creates a new environment name `core-billing` to help investigate better ways to display and dissect our platform costs as per issue #7169

Create core-billing account

---

terraform/environments/core-network-services/locals.tf
terraform/environments/core-network-services/logging.tf
terraform/environments/core-network-services/secrets.tf
terraform/environments/core-vpc/locals.tf
terraform/environments/core-vpc/logging.tf
terraform/environments/core-vpc/secrets.tf

#7607
Now that we have separate buckets for separate destinations, this PR streams logs to the relevant buckets
Tested with local plan, through CI pipeline, and previously in sandbox

Stream logs to separate buckets

---

terraform/modules/cloudwatch-firehose/main.tf

#7607 
Makes KMS alias unique in case module is called more than once
Run deployments against `core-vpc` and `core-network-services` against main branch once PR has been merged in

Make KMS alias unique

---

environments/delius-core.json
environments/delius-iaps.json
environments/delius-jitbit.json
environments/delius-mis.json
environments/delius-nextcloud.json

Probation WebOps is no more! We are now part of a larger team for migrations - LAA Ops, PWO and DSO all as one. This new team reflects all member of the new team so that PR reviews can be more collaborative.

:passport_control: Add `hosting-migrations` to codeowners for delius related projects

---

terraform/environments/bootstrap/secure-baselines/main.tf
terraform/modernisation-platform-account/baselines.tf

https://github.com/ministryofjustice/modernisation-platform/issues/7437
Points baselines module to latest version v7.7.0 which includes teh alerting for when admin role is assumed across MP.
The module update was tested locally for core-shared-services to test the alerting.

Update baselines module to v7.7.0

---

terraform/environments/core-network-services/firewall-rules/fqdn_rules.json

Need to allow traffic out via the http allow list to *.csr.service.justice.gov.uk
This is the only http endpoint we're trying to monitor from within AWS
Consulted the oracle that is the mod-platform team
Can't think how it would

add http://*.csr.service.justice.gov.uk to AWS firewall allow list

---

terraform/pagerduty/member-services-integrations.tf

Supplied wrong slack channel Id for non-prod alarms
Uses correct slack channel ID
Should just work now that the channel is correct, can test manually using pagerduty as well
Nope

use correct channel id for nomis_alarms_non_prod

---

terraform/github/locals.tf
terraform/github/repositories.tf

#7607 
This will allow us to migrate code from our `modules/cloudwatch-firehose` to an independent module which can be used both by ourselves and other teams such as `analytical-platform` and `cloud-platform`.

Create `modernisation-platform-terraform-aws-data-firehose` repository

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

#7707 
This change ensures that the session duration aligns with the maximum runtime of jobs on GitHub-hosted runners, allowing for extended workflows without requiring re-authentication.

Increase OIDC role max_session_duration to 6 hours

---

terraform/pagerduty/locals.tf

PagerDuty access was removed as part of another PR (it was failing). This is to add that back in.

Restore pagerduty for Stephen Linden

---

terraform/environments/core-network-services/vpn.tf
terraform/environments/core-network-services/vpn_attachments.json

https://github.com/ministryofjustice/modernisation-platform/issues/7833
Enables tunnel endpoint lifecycle control for the NOMS VPN. Waiting on their approval to go ahead as running this is in will schedule an endpoint replacement at the point it is applied.
It also creates an eventbridge rule to monitor for any AWS health events relating to the NOMS VPN which will be sent to the  #dba_alerts_prod channel

Enable NOMS VPN tunnel endpoint lifecycle control & health alerting

---

policies/collaborators/collaborators.rego
policies/collaborators/collaborators_test.rego
policies/collaborators/utilities.rego
policies/environments/environment-definitions.rego
policies/environments/environment-definitions_test.rego
policies/environments/expected.rego
policies/environments/utilities.rego
policies/member/environment-definitions.rego
policies/member/environment-definitions_test.rego
policies/member/utilities.rego
policies/networking/core-vpc.rego
policies/networking/core-vpc_test.rego
policies/networking/expected.rego
policies/networking/utilities.rego

https://github.com/ministryofjustice/modernisation-platform/actions/runs/10717883396
The latest version of regal has introduced some stricter rules on pckage naming conventions. See .. https://docs.styra.com/regal/rules/idiomatic/directory-package-mismatch
I've updated all the package definitions to match the directory structure as suggested.
I ran regal linting locally and it passed.

Fix regal liniting errors

---

terraform/environments/bootstrap/single-sign-on/policies.tf

https://github.com/ministryofjustice/analytical-platform/issues/5289
QuickSight can't be fully managed in code. Specifically, adding and removing identity center groups requires manual intervention as terraform forces a destroy when groups are amended.
This creates a policy that will eventually be utilised by a new permission set to carry out admin tasks in QS.
The policy was copied from the AWS docs. Testing will take place after deployment
No special deployment instructions. There will be a follow-up two additional PRs. One that creates the permission set in `aws-root-account` and then amending of the json environment file and the rego tests that will assign the new permissions sets.

Adding Quicksight Admin policy for the new permission set

---

terraform/environments/core-network-services/vpn.tf

#7833
Having merged https://github.com/ministryofjustice/modernisation-platform/pull/7848 I encountered an issue with deploying the aws chatbot config in core-network-services.
I've made a few changes to the module so that it uses non `awscc` resources and now it's behaving (i.e. building the config in the right region). ALso I had to update some SCP policies to get this going as well. Good news is that will help pave teh way if we decide to use chatbot elsewhere in our core accounts.
Applied locally and worked. Now updating code so it's run in properly.

Point to v2.0.0 of aws chatbot module in `core-network-services`

---

terraform/pagerduty/member-services-integrations.tf

Suppress CSR training server endpoint running alarms over the weekend as these instances are turned off - what happens currently is these alarms ALWAYS fire over the weekend... 
Adds condition to pagerduty_event_orchestration_service for alarms summary beginning with trainab-http- and only for the corporate-staff-rostering-preproduction service in PagerDuty
Should just work but have checked everything pretty thoroughly, also the number of changes is minimal
No

set rule for suppress-at-weekend pagerduty alarms

---

terraform/pagerduty/member-services-integrations.tf

time based expressions for conditions don't seem to be well documented. This is a best guess 
Should address syntax error where now. (dot) is not valid
Hard to test without apply. If it keeps failing I'll use the PagerDuty curl code to figure it out instead
Nope, only impacting one alarm type at the moment

use correct syntax for time conditions

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

Restrict kms:CreateGrant permissions for oidc role #6845 
Implements a restriction on the kms:CreateGrant action to ensure that grants can only be created for AWS resources and not to external IAM users, roles, or services. Following the principle of least privilege, I've  tightened the conditions even further by restricting the kms:CreateGrant action only to RDS-related operations.

Restrict kms:CreateGrant permissions for oidc role

---

collaborators.json

#7800 
Grants necessary access to new collaborator

Add new collaborators

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

Restrict kms:CreateGrant permissions for oidc role #6845 
This permission is required for copying snapshots encrypted with a shared KMS key in the core-shared-services account.
Implements a restriction on the kms:CreateGrant action to ensure that grants can only be created for AWS resources and not to external IAM users, roles, or services. 

Restricts kms:CreateGrant permissions for Github OIDC role

---

terraform/environments/core-network-services/cidr-ranges.tf
terraform/environments/core-network-services/firewall-rules/development_rules.json

Allow CICA Dev inbound and outbound to CICA AWS UAT.
Initial firewall rules to allow CICA Tariff on MP to reach CICA AWS
Allows Inbound and Outbound rules on FW, so that CICA AWS can reach Tariff on mod platform across TGW.
This is a WIP and will be the initial test of connectivity

🛂 CICA Development FW rules

---

terraform/environments/core-logging/observability.tf

incorrect arn specified updating from `arn:aws:iam::aws:policy/AmazonGrafanaAthenaAccess` to `arn:aws:iam::aws:policy/service-role/AmazonGrafanaAthenaAccess`

Fix policy arn AmazonGrafanaAthenaAccess

---

source/user-guide/access-key-management.html.md.erb

This PR introduces new documentation for managing access keys for both superadmin and collaborator users. It provides detailed guidelines on when and how access keys are deleted based on their usage. #7714

Add documentation for access key management

---

source/user-guide/platform-user-roles.html.md.erb

This PR updates the existing documentation to include a new role for managing S3 buckets. #7800

Add documentation for S3 upload role to existing roles

---

terraform/environments/digital-prison-reporting/iam.tf

There were errors encountered by the `circle_ci` role when creating an `EventBridge` scheduler:
```
│ Error: creating AWS EventBridge Scheduler Schedule (dpr-start-establishments-development): operation error Scheduler: CreateSchedule, https response error StatusCode: 403, RequestID: bae15e8c-3f7a-4e14-9c1a-cd900ae14b37, api error AccessDeniedException: User: arn:aws:sts::771283872747:assumed-role/circleci_iam_role/circleci-oidc-session is not authorized to perform: scheduler:CreateSchedule on resource: arn:aws:scheduler:eu-west-2:771283872747:schedule/default/dpr-start-establishments-development because no identity-based policy allows the scheduler:CreateSchedule action
```
https://app.circleci.com/pipelines/github/ministryofjustice/digital-prison-reporting-domains/1370/workflows/290d4cf6 …

DPR2-1170: Add scheduler roles to circleci_iam_policy

---

terraform/environments/core-network-services/logging.tf

#7185
The logs appear to be double-compressed; by the CloudWatch log group subscription filter, and by the delivery stream. This PR bumps the data firehose module to a version that supports uncompressed delivery streams.
If the behaviour is as expected - logs are parsed by Cortex XSIAM and successfully interpreted - a following PR will apply this to all other uses of the module.

bump one use of the firehose to assess impact of uncompressed logs

---

terraform/environments/digital-prison-reporting/iam.tf

The error below was encountered by the DPR circle-ci role while trying to update an IAM role:
```
╷
│ Error: updating IAM Role (dpr-start-establishments-development-role) assume role policy: operation error IAM: UpdateAssumeRolePolicy, https response error StatusCode: 403, RequestID: f0c92f6c-6cc1-4c16-845f-75bd9c3ce3cd, api error AccessDenied: User: arn:aws:sts::771283872747:assumed-role/circleci_iam_role/circleci-oidc-session is not authorized to perform: iam:UpdateAssumeRolePolicy on resource: role dpr-start-establishments-development-role because no identity-based policy allows the iam:UpdateAssumeRolePolicy action
```
https://app.circleci.com/pipelines/github/ministryofjustice/digital-prison-reporting-domains/1380/workflows/16f920cd-c430-4716-a2ce-f08d6bcc4cf5/jobs/4234
This PR adds …

DPR2-1170: Add iam:UpdateAssumeRolePolicy to DPR circle_ci role

---

terraform/pagerduty/backend.tf
terraform/pagerduty/providers.tf

Provider for kms replica was in backend.tf and not providers.tf
moved provider to providers.tf
local plan

moved provider from backend.tf to providers.tf

---

source/index.html.md.erb
source/runbooks/recreate-core-shared-services-production.html.md.erb
source/runbooks/recreate-modernisation-platform-account.html.md.erb

#6761
Adds a runbook detailing how to recreate the MP account and resources, along with some post-recreation steps.
The last part about reimporting state files isn't perfect; if the account was deleted the state files would go with them, but some state files will be locally cached by users who have run a terraform plan in their `./terraform` directory. In theory these could be manually restored.
Will be tested when related story is in review

Recreating the MP account runbook

---

terraform/environments/core-network-services/data.tf
terraform/environments/core-network-services/monitoring.tf

As Part of  issue NAT Alarms for Core network services account
[#7724](https://github.com/ministryofjustice/modernisation-platform/issues/7724)
we wanted to setup some new alarms for the NAT gateway in core-networking account
This PR add these alarms to cover both live and non-live vpc's
i have run the plan locally on my machine and the play runs correctly and produces the output required

New NAT Alarms core network services

---

terraform/environments/core-network-services/cidr-ranges.tf
terraform/environments/core-network-services/firewall-rules/development_rules.json

Allow traffic from CICA UAT on-prem to MP Dev.
Allow connectivity from CICA UAT VLAN to Dev environment. Adds CICA on-prem ranges to cidr-ranges.tf and creates firewall rule to allow traffic.
CICA firewall is being configured to allow routes from on-premise across VPN and Transit Gateway to Modernisation Platform. This  PR will allow testing of this connectivity.
Previous PR for allowing Dev traffic to CICA AWS has been tested and connectivity confirmed.

🛂 Allow CICA UAT on-prem to dev

---

terraform/environments/core-vpc/vpc.tf

#7607
It's a precursory step to outputting logs to S3. By bumping the module version, a later PR can supply an attribute to create a flow log which outputs to S3
Ran local terraform plan

Bump VPC module version to latest

---

terraform/environments/core-logging/cortex.tf

#7607
Adds bucket policy statements allowing `delivery.logs.amazonaws.com` service to write to the buckets. This is a precursor to enabling VPC flow logs to be written directly to the buckets, instead of via an AWS Data Stream / kinesis firehose.
You can see the AWS guidance on policies here: https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/configure-vpc-flow-logs-for-centralization-across-aws-accounts.html#configure-vpc-flow-logs-for-centralization-across-aws-accounts-additional
Tested through PR checks & by peer review

Allow VPC flow logs to be written directly to Cortex buckets

---

terraform/environments/core-vpc/logging.tf

#7607 
Remove streaming of flow logs through aws data firehose. A following PR will instate logging directly to S3
Tested with local PR

Remove firehose logging of vpc flow logs

---

terraform/environments/core-vpc/locals.tf
terraform/environments/core-vpc/vpc.tf

#7607
Adds statement to build flow log that outputs to S3 bucket in `core-logging`.
Cleans up formatting of terraform for `module.vpc` a bit.
Tested with local plan and CI pipeline

Send flow logs to S3

---

.github/workflows/format-code.yml
terraform/environments/sprinkler/locals.tf

Triggers an "exit 1" of the workflow if no changes are found. This is to prevent the pushing of a commit that is behind the remote which will error. Also removes some formatting changes in sprinkler locals that were used to test the linter.
#7689 
See above.

Issue 7689 - Bug fixes from testing.

---

terraform/environments/core-logging/cortex.tf

#7607
Because the bucket policy currently uses "aws:PrincipalOrgPaths" which is only for an IAM user, IAM role, federated user, or AWS account root user, flow logs can't be written into the bucket.
This PR switches to use a condition that scopes access only to our AWS Organization.
Tested through local plan
Deploy through CI, then re-run failing VPC deployments.

Update bucket policy to use correct condition

---

terraform/environments/core-vpc/vpc.tf

#7607
As only production VPCs should be in scope, this adds a conditional check to ensure only production VPCs have logs streamed to S3

Add condition to only stream flow logs from production VPCs to S3

---

environments/electronic-monitoring-data.json

Electronic monitoring are going to be receiving data from external suppliers who will be pushing data to an S3 bucket. We want to test and ensure this connection is secure outside of our Production account.
It creates a test account where we can test suppliers sending dummy data before promoting to Prod.
We then have an action to exclude spinning up most infra in our test account as many things won't be needed.
Not tested, just eyeballed config file update against other accounts.
No
Original account request > https://github.com/ministryofjustice/modernisation-platform/issues/5833

Add test account to the electronic-monitoring-data account

---

source/runbooks/recreate-modernisation-platform-account.html.md.erb

#6761 
Adds a little extra detail on how to recover a closed account. It's possible that we might need to set a different alias to the account, but if we're in scope to reuse the alias then we're out of scope to recover the account and I can't see why we'd not recover the account.
Checked link correctly refers to AWS guidance
N/A

Add detail on reopening account to runbook

---

terraform/environments/core-network-services/locals.tf
terraform/environments/core-network-services/logging.tf

#7607
Prior to sending logs directly to S3, this PR removes their streaming through an AWS Data Firehose
Tested with local plan, will test through CI/CD pipeline

Remove config to send `core-network-services` flow logs via data firehose

---

source/runbooks/recreate-core-logging-production-account.html.md.erb

https://github.com/ministryofjustice/modernisation-platform/issues/6763
I've tried to update a few details and add a bit more detail around verifying the resources have been created e.g. more functional type checks. 

Updated `core-logging` DR runbook with some more details

---

terraform/environments/core-network-services/locals.tf
terraform/environments/core-network-services/vpc.tf

#7607
Send flow logs from `live_data` egress VPC to S3 for Cortex XSIAM
Ran local terraform plan

Send `live_data` flow logs go s3

---

environments-networks/hmpps-test.json

electronic-monitoring-data-test has recently been added but required networking has not been added yet.
This PR adds the required networking
fully tried and documented process.
No

Add networking for emd-test env

---

terraform/environments/core-network-services/locals.tf
terraform/environments/core-network-services/monitoring.tf

Reverts ministryofjustice/modernisation-platform#8015
```
Error: creating Flow Log (tgw-053d9dd7f1222a554): operation error EC2: CreateFlowLogs, https response error StatusCode: 400, RequestID: 3689b02c-625d-4d13-93f1-7d72da130de7, api error InvalidParameter: Invalid Resource id tgw-************ for resource-type TransitGatewayAttachment
```
This looks like a provider issue; you can see from my PR that I specified the transit gateway id, not an attachment ID. I'll raise an issue on the AWS Provider repository and refactor this branch to merge in a selection of attachments.

Revert "Add flow logs from transit gateway to s3"

---

terraform/environments/core-network-services/firewall.tf

#7607
Ensure flow logs are sent from `core-network-services` external-inspection (firewall) VPC to S3 for Cortex XSIAM ingestion

Output flow logs from inspection VPC to S3

---

terraform/environments/core-vpc/locals.tf
terraform/environments/core-vpc/vpc.tf

#7607
Bump modernisation-platform-terraform-member-vpc module to [latest tagged release](https://github.com/ministryofjustice/modernisation-platform-terraform-member-vpc/releases/tag/v3.0.0).
Removes configuration explicitly related to triggering firehose creation.

Remove logging to firehose via VPC module

---

terraform/environments/core-shared-services/versions.tf

As the `random` provider is no longer required by any objects in configuration or state, this PR removes it.

Remove provider from `core-shared-services`

---

terraform/pagerduty/member-services-integrations.tf

This code, initially, sets up a different channel for Sprinkler. More importantly, however, is the change to cdpt_chaps_cloudwatch where the code has been amended to replace agerduty_service_integration with pagerduty_event_orchestration. This is to ensure that changes due to happen early next year will not impact us. We are currently testing this to make sure it has no impact on our services.
The code was also amended to put the low priority alarms code in place. Again this has been amended to fix an issue with the value.
The initial code has been left, commented out, so that we can reinstate if required. 
Also see request #5980

Put in the correct channel_id following discussion with Mark

---

terraform/environments/core-security/versions.tf

`random` provider was required to successfully complete Terraform run after module requiring said provider was deleted.

Remove random provider from `core-security`

---

terraform/modernisation-platform-account/secrets.tf

#7607
Now that XSIAM logs are being supplied via S3 instead of a Kinesis firehose http endpoint, this secret is no longer required.
Ran local terraform plan, removed dependent objects from member accounts.

Remove xsiam secret from `modernisation-platform-account`

---

terraform/pagerduty/member-services-integrations.tf

See comments from #7976 
The apply failed due to an incorrect team name in the code. This has been amended in this call.
Applies to request #5980

Incorrect team used. Copied from the service in the code below

---

terraform/modules/firewall-logging/main.tf
terraform/modules/firewall-logging/variables.tf

#7607
Allows optional output of firewall logs to S3
Tested only through a terraform plan - unclear if we can supply `ALERT` logs to two destinations at present.

Optionally output firewall logs to S3 bucket

---

terraform/modules/firewall-logging/main.tf
terraform/modules/firewall-logging/variables.tf

Manually testing showed this failed with an API message like so:
```
│ Error: adding NetworkFirewall Logging Configuration (arn:aws:network-firewall:eu-west-2:*:firewall/external-inspection): operation error Network Firewall: UpdateLoggingConfiguration, https response error StatusCode: 400, RequestID: 872a9584-6f39-4d07-9b0d-0cddfe3108c3, InvalidRequestException: Given logging configuration is unsupported.
```
However from a look at the CloudTrail logs it appears correct. I'd like to revert this PR then investigate with AWS tomorrow before recreating it correctly.

Revert "Optionally output firewall logs to S3 bucket"

---

terraform/pagerduty/member-services-integrations.tf

modernisation_platform_members.id name
After the previous successful run Dave noticed I had used modernisation-platform.id rather than modernisation-platform-members.id. This PR is to correct that error.
The previous PR was #8040

Replaced modernisation_platform.id with the correct 

---

.github/workflows/format-code.yml

Reverts the code formatter workflow to its pre-graphql version to allow time to fix the branch issue.
#7689 
Workflow is failing and this reverts to the last known working state.

Issue/7689 - Reverts code-formatter.yml to its pre-graphql version to allow time to fix the branch issue & so prevent the workflow from failing.

---

environments/hmpps-domain-services.json
environments/hmpps-oem.json
environments/nomis-combined-reporting.json
environments/nomis-data-hub.json
environments/nomis.json
environments/oasys-national-reporting.json
environments/oasys.json

hosting-migrations was not added as a codeowner to all environments changed in #7895.
The team was not added to the `codeowners` key in some of the JSON files. As this acts as an override, the new team was not added as a codeowner. This PR adds the team to the `codeowners` key where applicable.
N/A
No.
N/A

add hosting-migrations team to codeowners

---

terraform/environments/core-network-services/vpn.tf

I set up an alert to notify the #dba_alerts_prod channel when we receive health alerts related to the NOMIS VPN in the `core-network-services` account. However, this failed to work when we received an alert on Monday 23rd Sept (via email).
Added an IAM policy to the SNS topic that specifically allows the events service to publish to the topic.
Tested using a dummy eventbridge rule/sns topic with the new policy and it worked as inteneded.

Allow events service to trigger SNS topic

---

terraform/environments/core-logging/r53_logs.tf

#7607
Creates resolver log query configs and associates them with a new resource share.
This will allow the resource share to be distributed to the MP OU where it can be accepted and used to associate VPCs with said resolver log queries.

Create resolver query logs and new cloudwatch destination

---

terraform/environments/core-logging/locals.tf
terraform/environments/core-logging/r53_logs.tf

#7607
Adds a terraform resource to share the new RAM Shares with accounts in the MP OU. They will still need to accept the share to make use of it.
This is somewhat different to how we carry out shares in the `modules/ram-principal-association` module which share resources on a per-account basis.

Associate R53 Resolver QLC RAM share across MP OU

---

terraform/environments/core-logging/r53_logs.tf

Principal supplied for `aws_ram_principal_association` is incorrectly formatted
Adds a checkov skip for a cloudwatch group, and uses string manipulation to correctly present the ARN to association a RAM principal with a share.
Tested with local terraform plan and compared ARN to AWS documentation.

Fix principal for `core-logging`

---

terraform/environments/bootstrap/single-sign-on/policies.tf

Add glue:getConnection to DPR SSO so problems with connection details can be debugged.
Developer and Operations roles need to be able to view the details of glue connections via AWS CLI or console to debug issues with the connection configuration. Currently we get this error message:
```
aws glue get-connection --name dpr-dps-activities-connection
An error occurred (AccessDeniedException) when calling the GetConnection operation: User: arn:aws:sts::203591025782:assumed-role/AWSReservedSSO_mp-reporting-operations_e480d2547978b388/tom-ogle-moj@digital.justice.gov.uk is not authorized to perform: glue:GetConnection on resource: arn:aws:glue:eu-west-2:203591025782:catalog because no identity-based policy allows the glue:GetConnection action
```
Adds `glue:GetConnection` so roles can view the …

DPR2-1127: Add glue:getConnection to DPR SSO

---

environments-networks/platforms-development.json
environments-networks/platforms-production.json
policies/networking/expected.rego
terraform/environments/analytical-platform-ingestion/networking.auto.tfvars.json

Is part of https://github.com/ministryofjustice/analytical-platform/issues/5175
https://mojdt.slack.com/archives/C01A7QK5VM1/p1727263917973289
Adds `analytical-platform-ingestion` to what I think is the right places based on `data-platform`
It hasn't been tested
No

🌐 Add Platforms General shared VPC to Analytical Platform Ingestion

---

terraform/environments/core-vpc/locals.tf
terraform/environments/core-vpc/logging.tf
terraform/environments/core-vpc/vpc.tf

https://github.com/ministryofjustice/modernisation-platform/actions/runs/11055900092
A VPC can only be associated with one type of log destination (EG, CloudWatch). This PR removes the legacy account-local logging.
Tested with CI checks

remove old account-local resolver logging

---

.github/workflows/upload-cost-explorer-to-s3.yml

The cost collection script, running on the 1st of the month, was missing the data for the 1st day of the current month, leading to discrepancies in the reported costs.
Running the script on the 2nd day allows AWS billing data from the 1st of the month to be finalized, ensuring that the script includes all costs, preventing discrepancies.

Reschedule cost collection to run on second day to include full month's data

---

terraform/environments/core-logging/r53_logs.tf

#7607
Adds a KMS key and policy to encrypt the Route53 Resolver CloudWatch logs.
Guidance on key policy taken from [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/encrypt-log-data-kms.html#cmk-permissions).
Tested with local plan, also tested against `trivy` and `checkov` locally.

Encrypt Route53 Resolver Logs

---

.github/workflows/format-code.yml
terraform/environments/sprinkler/locals.tf

Full details in [Issue-7689](https://github.com/ministryofjustice/modernisation-platform/issues/7689)
This PR updates the formate code workflow to use signed commits
tested here https://github.com/ministryofjustice/modernisation-platform/actions/runs/11069022570
No impact is expected.

Formatcode Bot update to use signed commits

---

terraform/environments/core-logging/r53_logs.tf

https://github.com/ministryofjustice/modernisation-platform/actions/runs/11069352259/job/30757178006
ARN, not ID,of KMS key is required to encrypt a CloudWatch Log Group
Amends argument attribute supplied to encrypt Log Group
Applied key through CLI, tested against Terraform Plan without and with updated reference to attribute.
No functional changes

ARN of key required to encrypt cloudwatch log group

---

terraform/environments/core-logging/locals.tf
terraform/environments/core-logging/logging.tf
terraform/environments/core-logging/vpc.tf

#7607
Adds config to log resolver queries to CloudWatch & S3 in `core-logging`

Log R53 resolver queries for `core-logging`

---

terraform/environments/core-network-services/logging.tf

#7607
Adds config to log resolver queries to CloudWatch & S3 in `core-logging`
Inspection VPC is not included in scope here; it serves only to hold network firewall endpoints.

Log R53 resolver queries for `core-network-services` 

---

terraform/environments/core-security/locals.tf
terraform/environments/core-security/logging.tf
terraform/environments/core-security/vpc.tf

#7607
Adds config to log resolver queries to CloudWatch & S3 in `core-logging`

Log R53 resolver queries for `core-security`

---

terraform/environments/core-shared-services/logging.tf

#7607
Adds config to log resolver queries to CloudWatch & S3 in `core-logging`

Log R53 resolver queries for `core-shared-services`

---

terraform/environments/core-logging/cortex.tf
terraform/environments/core-logging/ssm.tf
terraform/environments/core-logging/versions.tf

#7607 
Creates an assumable role that can be used by Palo Alto Cortex XSIAM in line with their documented guidelines. I deliberately haven't attached the `Security Audit` managed policy as this isn't currently being used by the Cortex user, and provides access to the account which we may not prefer to offer.
Tested with CI pipeline. I expect that this will fail because - at present - there is no value for the account ID SSM parameter. This will be added manually once the parameter has been created
Deploy through CI. Potentially re-run after populating SSM parameter.

Assumable role for Cortex XSIAM

---

terraform/environments/core-logging/ssm.tf

#7607 
An AWS SSM Parameter is a more appropriate way to store non-sensitive information than an AWS Secrets Manager version.
This PR also harmonises the syntax in how we refer to Palo Alto Cortex XSIAM.

Create SSM Parameter to use in preference of secret store value for bucket ARNs

---

terraform/environments/core-network-services/ssm.tf
terraform/environments/core-security/ssm.tf
terraform/environments/core-shared-services/ssm.tf
terraform/environments/core-vpc/ssm.tf

#7607
In order to replace the use of AWS Secret Manager, this PR allows accounts to retrieve the same information through an SSM Parameter. A following PR will remove the old secret and use the new parameter.

Retrieve core-logging bucket arns for cortex through SSM

---

terraform/environments/core-logging/ssm.tf

#7607
SSM Parameter Store was chosen specifically to hold parameters that don't need special handling. This PR swaps from `value` to `insecure_value` to address this. The alternative - wrapping outputs as `nonsecure()` would achieve the same thing, so to make the correct handling of these values clear I've chosen to switch the attributes used.
Tested with local plan and through CI pipeline

Switch to insecure_value for nonsensitive values

---

terraform/environments/core-logging/cortex.tf
terraform/environments/core-logging/ssm.tf

#7607
SSM parameters can't be overwritten without `overwrite = true`. Once an SSM parameter has been created, the value can't be changed to `insecure_value` without this flag. I worked around it originally by deleting the parameters manually to recreate them, but this will allow us to continue to work programatically.
Tested with local apply targeted at parameters.

More fixes for ssm params

---

terraform/environments/core-logging/locals.tf
terraform/environments/core-logging/vpc.tf
terraform/environments/core-network-services/firewall.tf
terraform/environments/core-network-services/locals.tf
terraform/environments/core-network-services/logging.tf
terraform/environments/core-network-services/monitoring.tf
terraform/environments/core-network-services/vpc.tf
terraform/environments/core-security/locals.tf
terraform/environments/core-security/vpc.tf
terraform/environments/core-shared-services/locals.tf
terraform/environments/core-shared-services/vpc.tf
terraform/environments/core-vpc/locals.tf
terraform/environments/core-vpc/vpc.tf

#7607
We originally used AWS Secretsmanager to store values centrally that could be used by `core-*` accounts. However, AWS SSM Parameter Store is the more appropriate way to hold these values. This PR updates how we retrieve values relevant to storing Cortex XSIAM information.
Tested through CI pipelines; no changes expected

Use SSM parameter to retrieve bucket ARNs

---

source/runbooks/integration-with-protective-monitoring.html.md.erb

By removing the broken links from the firehose documentation, the workflow that depends on these links can run successfully without encountering failures.

Remove broken links from firehose documentation

---

terraform/modernisation-platform-account/baselines.tf

Latest release excluding getmaciesession from security hub alarms

Bump Baselines version

---

scripts/account-deletion/delete-accounts.sh

Having spoken to @Khatraf who recently ran through the account deletion process - she didn't have jq installed which is required in one of the scripts so it failed part-way through.
I've added a small function to check the requirements for the script. Esssentially it checks that `terraform` and `jq` are installed and cancels the run if they are not.
Tested locally. When I put in dummy package names I got the following result:
```
./delete-accounts.sh
Error: terrafom is not installed.
Error: j is not installed.
Please install the missing programs and try again.
```
But it runs through successfully when set to the proper names and the requirements are installed.

add check requirements function

---

terraform/environments/core-network-services/logging.tf

#7607
As neither firehose nor direct-to-s3 are suitable methods to store logs for XSIAM consumption, this PR removes the existing method of populating the `core-generic-logs` S3 bucket.
Tested with Terraform plan

Remove firehose for firewall logging

---

terraform/environments/core-logging/cortex.tf

#7607
Now that AWS data streams are not used to supply logs to S3, these policy statements are not required.

Remove bucket policy statements for firehose access

---

terraform/modules/firewall-policy/main.tf

When the firewall policy terraform is executed an empty `rule_variables` block is created regardless of if `ip_sets` or `port_sets` is populated.
Wraps the `rule_variables {}` in a dynamic block, and creates it only when `ip_sets` or `port_sets` is supplied.
Tested with local terraform plan
Non-functional deployment through CI; expect no changes.

Improve use of `firewall_policy` module

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

Action currently fails to update lambda code as doesnt have perms to create a grant for kms keys in our account, this adds those permissions
Please describe the tests that you ran: n/a
no

Allow KMS:CreateGrant for the EM accounts in the OIDC

---

terraform/pagerduty/aws.tf
terraform/pagerduty/member-services-integrations.tf

Reverts ministryofjustice/modernisation-platform#8145
This PR appears to be causing errors due to a duplicate name as seen here: https://github.com/ministryofjustice/modernisation-platform/actions/runs/11158921844

Revert "Adding cdpt changes to code"

---

terraform/modernisation-platform-account/iam.tf

The AWS console home has widgets which display some data such as health and costs.
This gives permissions for users assuming the mp account read only role to view that data.
This will reduce the number of unauthorised API call alerts that we recieve every time a user assumes that role.
The read only policy is also being attached to the collaborator user group, this means that collaborators also have permissions to view these widgets, plus they no longer need to switch to a read only role in the same account.

Add permissions for users to view console home widgets

---

terraform/environments/core-network-services/vpn.tf

Health alerts relating to the NOMIS VPN were still not successfully triggering the associated SNS topic.
Having made some manual changes, tested it and spoken to AWS support I've updated the policy to be less specific (condition statement removed).
Local TF plan works and manual changes have been tested previously.

Update NOMIS vpn sns topic access policy

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

Ps per issue raised in slack here https://mojdt.slack.com/archives/C01A7QK5VM1/p1728054312206809 this PR add the `lambda:GetCodeSigningConfig` permission to the OIDC role.

Add lambda permission

---

terraform/environments/core-shared-services/ecr_repos.tf

Electronic monitoring are going to be sent files from external suppliers that will need virus scanning before we do anything else with them. 
The AP ingestion scan repo implements virus scanning for objects in S3 in a modular manner (i.e. no hard coded variables). As we need to add virus scanning of s3 objects into the Electronic Monitoring infrastructure, this PR is piggy backing on that code to add into our EM accounts.
Already deployed in AP accounts.
No
n/a

Add EM account access for AP ingestion scan ECR repo

---

terraform/environments/core-network-services/logging.tf
terraform/environments/core-network-services/ssm.tf

#7607
Invokes data stream module and supplies configuration to stream logs to Palo Alto XSIAM endpoint
Tested through unit tests, but will need final confirmation from XSIAM integration team.

Stream firewall logs to XSIAM endpoint

---

source/runbooks/integration-with-protective-monitoring.html.md.erb

#7607
Updated runbook to cover the essentials. I removed the links to code as these are prone to linkrot.
Test through peer review / pipeline checks

Trimmed protective monitoring runbook

---

source/runbooks/creating-accounts-for-end-users.html.md.erb

A small PR to fix the `skip-alias` link in the account creation documentation.

Fix skip-alias link in documentation

---

collaborators.json

Removes four inactive collaborator accounts as per tickets #8178, #8179, #8180 and #8181 
IAM accounts have already been removed via the console.
As per document https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/adding-collaborators.html#access-to-be-able-to-approve-deployments

Deleted expired collaborator accounts.

---

source/runbooks/integration-with-protective-monitoring.html.md.erb
terraform/environments/core-logging/cortex.tf

#7607
Removes Cortex user now that the role is being used, updates documentation to reflect this.

Cortex cleanup

---

terraform/environments/core-network-services/logging.tf

#7607
Incorrect CW Log Group was being applied to data stream

Correct reference to firewall log group

---

.trivyignore.yaml

Adds AVD-GIT-0004 which adds an ignore for signed commits not being set for modernisation-platform-environments.
The repository modernisation-platform-environments does not have "require signed commits" enabled for the main branch. This adds the required ignore as it is failing the test as evidenced here - https://github.com/ministryofjustice/modernisation-platform/actions/runs/11287877020
See above.

Adds AVD-GIT-0004 to trivyignore.

---

terraform/environments/core-logging/observability.tf

As part of ticket https://github.com/ministryofjustice/modernisation-platform/issues/7169 this PR adds the KMS key to the cur-reports-buckets for encryption.

Add custom key to s3 bucket

---

terraform/environments/core-logging/observability.tf

This PR adds the KMS permissions for the replication role as well the `s3:List*` permission to the buckets (also now rearragned alphabetically)

Add KMS permssions for replication role

---

terraform/environments/core-logging/observability.tf

core-logging deployment workflow has [failed](https://github.com/ministryofjustice/modernisation-platform/actions/runs/11295859359/job/31419490253) deploying my latest PR https://github.com/ministryofjustice/modernisation-platform/pull/8250 which I believe was oversight on behalf where I combined some bucket permissions with some KMS permissions, this PR should rectify the issue.

Fix Policy Permissions

---

terraform/environments/core-logging/observability.tf

This PR updates the S3 bucket policy for the `moj-cur-reports-modplatform` bucket to resolve a MalformedPolicy error.
The issue stemmed from using object-level actions on bucket-level resources. The policy now correctly defines both the bucket-level ARN (`"arn:aws:s3:::moj-cur-reports-modplatform"`) and the object-level ARN (`"arn:aws:s3:::moj-cur-reports-modplatform/*"`), ensuring that:
- **Bucket-level** actions like `s3:ListBucket` and `s3:PutBucketVersioning` are applied to the bucket ARN.
- **Object-level** actions like `s3:ReplicateObject` and `s3:GetObjectVersionTagging` are applied to the object ARN.

Add Object and Bucket level Resources

---

terraform/environments/bootstrap/single-sign-on/policies.tf

As part of the ask channel request 
Madhu Kadiri
13:36
Ref:- "https://mojdt.slack.com/archives/C01A7QK5VM1/p1728640192868709"
Hi, When I enabled "glue:TagResource" in the policy associated to the role "arn:iam::976799291502:role/glue-notebook-role-tf", it hasn't fixed the issue. I see this is to be enabled at user-level (IAM-Role>> "AWSReservedSSO_modernisation-platform-data-eng_e01f956b5b720d1f").
Could someone eligible, update the relevant policy associated to the above role to 'allow' >>
"glue:TagResource",
"glue:UntagResource"
Madhu Kadiri
Ref: Glue Notebook Session:
%iam_role arn:aws:iam::976799291502:role/glue-notebook-role-tf
Hi, I am using jupyter-notebook to run glue pyspark script on my local machine using the above mentioned IAM role.
amended the IAM role so that glue resources …

adding the ability to tag glue resources

---

environments/electronic-monitoring-data.json

Electronic monitoring are having an internal ITHC being conducted on our infrastructure and therefore need to grant access to the team performing the ITHC
This PR gives the following access to the [hmpps-electronic-monitoring-data-store-appsec-202410](https://github.com/orgs/ministryofjustice/teams/hmpps-electronic-monitoring-data-store-appsec-202410/members) team in our prod account.
* `read-only`
* `view-only`
* `security-audit`
n/a
no
n/a

Add access for `electronic-monitoring-data` accounts  ITHC

---

terraform/modules/vpc-nacls/main.tf

Daily run of the Static Code Analysis job is failing...
https://github.com/ministryofjustice/modernisation-platform/actions/runs/11340947819/job/31538282534#step:4:3094
Added an ignore on a few resources in the `vpc-nacls` module for `avd-aws-0102` as the rules are open to all ports by design.
As suggested, I've also removed the tfsec ignores as that is no longer in use.
Status checks are passing.

Trivy ignore AVD-AWS-0102 for subnet NACLs

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

#8277 // [This](https://mojdt.slack.com/archives/C01A7QK5VM1/p1729175294137729) Slack conversation. 
Adds requested permissions to role used by Terraform ahead of terraform support. Users of the GitHub OIDC access role will want this in place so that they can migrate their use across to Terraform once support becomes available
Test through CI pipeline checks

Add `ds-data` permissions to memberinfrastructureaccess role

---

terraform/environments/bootstrap/single-sign-on/policies.tf

We are trying to set up lakeformation, and testing in our dev account with sandbox roles and noticed we have no permissions in there to do anything lf related. Some of these are already in the[ data engineering policy.](https://github.com/ministryofjustice/modernisation-platform/blob/0ce2becd9b8ac56935812ae776933057d510cd03/terraform/environments/bootstrap/single-sign-on/policies.tf#L413-L423)
Add lakeformation:* to sandbox policy
n/a
no

Add Lakeformation policies to sandbox role

---

terraform/environments/core-logging/observability.tf

following the failed deployment of `core-logging` from PR https://github.com/ministryofjustice/modernisation-platform/pull/8286 this PR fixes the KMS access by adding AWS logs service principal to the KMS key.
failed deployment run: https://github.com/ministryofjustice/modernisation-platform/actions/runs/11440085982/job/31825154636

Fix KMS access for logs service

---

terraform/environments/bootstrap/single-sign-on/policies.tf

https://github.com/ministryofjustice/analytical-platform/issues/5658
Adds DynamoDB permissions as per https://developer.hashicorp.com/terraform/language/backend/s3#dynamodb-table-permissions
It hasn't
No, it an addition
Resource based policy for DynamoDB table created here https://github.com/ministryofjustice/analytical-platform/pull/5744
Signed-off-by: Jacob Woffenden <jacob.woffenden@justice.gov.uk>

🛂 Add DynamoDB permissions to Data Engineering role

---

source/runbooks/creating-accounts-for-end-users.html.md.erb

This Pr updated the new account documentation with the information about the new tag implemented in the JSON environment files
Adds in a paragraph on critical-national-infrastructure tag

New runbook documentation

---

terraform/environments/core-logging/observability.tf

Switch back to `aws_kms_key` from `aws_kms_alias` as `InvalidArnException KMS Message: Key Aliases are not supported for this operation`
also added `lambda.amazonaws.com` to KMS permissions.

Fix lambda kms arn

---

terraform/environments/bootstrap/single-sign-on/policies.tf

This seeks to resolve [this](https://github.com/ministryofjustice/data-platform-support/issues/707) issue. And the approach mirrors that taken further up in the ticket in this PR. 
Adds missing S3 permission highlighted in ticket.
It hasn't been tested
No, it is an additional IAM action

:wrench: Add S3 Permissions to DataEngineeringAllow

---

terraform/pagerduty/aws.tf
terraform/pagerduty/services.tf

https://github.com/ministryofjustice/modernisation-platform/issues/8076
Builds a dedicated PagerDuty service/integration for Security Hub findings which will be linked to the newly created `modernisation-platform-security-hub-alerts` Slack channel.
After a chat with Dave we felt it best to create a dedicated channel as the alerts will be quite noisy for a while and it will be easier to separate them from our other alerts while we look to tune the findings that Security Hub is flagging.

Create PagerDuty Service/Integration for Security Hub

---

terraform/environments/core-logging/observability.tf

following on from PR https://github.com/ministryofjustice/modernisation-platform/pull/8301 which failed to deploy this PR updates the resources from the ARN to bucket name

Use Bucket Name not ARN

---

terraform/environments/bootstrap/single-sign-on/policies.tf

Adds permissions to list s3 objects for s3-upload. This is the result of collaborator feedback on using the role and has been requested by the product team.
See above.
- x ] I have performed a self-review of my own code

Adds additional read permissions to the collaborator role s3-upload.

---

terraform/environments/core-logging/observability.tf

This PR merges the S3 bucket configuration into a single bucket for handling AWS Cost and Usage Reports (CUR) and Athena querying. This approach simplifies the architecture by centralising CUR data management and access.
Highlights:
- Updated` grafana_athena`, `crawler_role`, and `cur_initializer_lambda_executor` roles to allow access to the merged S3 bucket.
- Configured Glue crawler to target the CUR report location in the consolidated bucket.
- Updated Lambda function to trigger on new CUR reports in the S3 bucket.

Consolidate S3 Bucket Configuration for CUR Athena Setup

---

terraform/environments/bootstrap/single-sign-on/policies.tf

Is part of https://github.com/ministryofjustice/analytical-platform/issues/5658
Adds `sts:AssumeRole` for `arn:aws:iam::${local.environment_management.account_ids["analytical-platform-management-production"]}:role/data-engineering-state-access`
It hasn't
No, its an addition
The role being assumed is scoped to specific AWS accounts https://github.com/ministryofjustice/analytical-platform/pull/5782

🛂 Allow role assumption of Analytical Platform Terraform state for Data Engineering

---

terraform/pagerduty/aws.tf

#7943 
Updates the Pagerduty terraform to refer to the multi-region KMS key
It has not. Assuming CI tests pass, replacing one KMS key with another should be seamless.
Deploy through CI.
Once deployed and tested, old key can be removed and scheduled for deletion.

Update references to KMS key from single-region to multi-region

---

terraform/environments/secrets.tf
terraform/github/data.tf
terraform/github/testing-ci.tf

#7943 
Updates terraform references to the `environment_management` KMS key from the single-region key to the multi-region key.
It has not. Assuming CI tests pass, replacing one KMS key with another should be seamless.
Deploy through CI.
Once deployed and tested, old key can be removed and scheduled for deletion.

Update references for `environment_management` KMS to multi-region key

---

terraform/github/data.tf
terraform/github/testing-ci.tf
terraform/modernisation-platform-account/dynamodb.tf

#7943 
Replaces key used to encrypt DynamoDB state table with multi-region equivalent
Will test through CI pipeline checks
Deploy through CI. A later PR will be required to schedule the old KMS key for deletion.

Replace dynamodb kms key with multiregion

---

terraform/environments/bootstrap/secure-baselines/main.tf
terraform/modernisation-platform-account/baselines.tf

https://github.com/ministryofjustice/modernisation-platform/issues/8076
Updates baselines module to `v7.9.0` which enables Security Hub findings to be sent to the [`#modernisation-platform-security-hub-alerts`](https://moj.enterprise.slack.com/archives/C07SNBJBVC6) Slack channel.
Tested locally on sprinkler and in status checks for this PR.

Update baselines to v7.9.0 to enable Security Hub alerting

---

.github/workflows/terraform-static-analysis.yml

We've all seen / been impacted by the below `TOOMANYREQUEST` error causing our TSCA workflow to fail, well thanks to @jacobwoffenden we now have the option to download the trivy database from ECR 🥳 
available in version https://github.com/ministryofjustice/github-actions/releases/tag/v18.3.0 and upwards.
```
ERROR	[vulndb] Failed to download artifact	repo="ghcr.io/aquasecurity/trivy-db:2" err="oci download error: failed to fetch the layer: GET https://ghcr.io/v2/aquasecurity/trivy-db/blobs/sha256:cae74bde88d988a66b3a4fb824b17b48f38c92258dfecbb748975694233641be: TOOMANYREQUESTS: retry-after: 205.218µs, allowed: 44000/minute"
2024-10-23T15:32:51Z	FATAL	Fatal error	init error: DB error: failed to download vulnerability DB: OCI artifact error: failed to download vulnerability DB: failed to …
```

Enable use_trivy_ecr_database - TOOMANYREQUESTS 🔥 

---

terraform/environments/core-logging/observability.tf

As PR reverts part of https://github.com/ministryofjustice/modernisation-platform/pull/8316/ where the KMS key was added to the Athena workgroup as I am now seeing errors when trying to run queries and want to rule this out as the cause.

Revert workgroup KMS

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

https://github.com/ministryofjustice/analytical-platform/issues/5175
Trying to create a Route53 resolver endpoint and getting
```
│ Error: creating Route53 Resolver Endpoint: operation error Route53Resolver: CreateResolverEndpoint, https response error StatusCode: 400, RequestID: b76acb63-a66e-42d1-a060-36ef595f6fcb, AccessDeniedException: User: arn:aws:sts::***:assumed-role/MemberInfrastructureAccess/aws-go-sdk-1729718246063734309 is not authorized to perform: route53resolver:CreateResolverEndpoint on resource: arn:aws:route53resolver:eu-west-2:***:resolver-endpoint/ because no identity-based policy allows the route53resolver:CreateResolverEndpoint action
│ 
│   with module.connected_vpc_outbound_route53_resolver_endpoint.aws_route53_resolver_endpoint.this[0],
│   on …
```

🛂 Add `route53resolver` permissions

---

terraform/environments/bootstrap/secure-baselines/main.tf
terraform/modernisation-platform-account/baselines.tf

https://github.com/ministryofjustice/modernisation-platform/issues/8076
There was an issue rolling out `v7.9.0` as there was a naming clash for the kms key in `core-network-services`.
`v7.9.2` uses `name_prefix` for the kms alias which adds a unique ID and avoids the naming clash.
Sprinkler!

Bump baselines release to `v7.9.2`

---

terraform/modernisation-platform-account/s3.tf

#7943
Replaces references to single-region KMS key with multi-region equivalent
Tested through CI checks.
Deploy through CI. Once deployed, existing objects will need to be re-encrypted using new key prior to scheduling old key for deletion.

Replace state bucket and cur bucket KMS keys with multi-region key

---

terraform/modernisation-platform-account/secrets.tf

#7943 
Observed a number of secrets not listed in this backlog issue were using the single-region key.
This PR updates them, and also alphabetises the secret resources
Previous changes to KMS key for secrets have been seamless.
Deploy through GitHub actions

Update and alphabetise more secrets keys

---

terraform/pagerduty/member-services-integrations.tf

Adding a Slack/PagerDuty integration to support the alerting of DSO's Azure subscriptions. Rest of the IaC is in a DSO repo. Thought it made more sense contextually to keep it in IaC beside the alarm integrations for our other AWS environments; as well as the fact some of these environments are part AWS and part Azure as we migrate over.

add PagerDuty service for DSO Azure alerting

---

terraform/modernisation-platform-account/dynamodb.tf
terraform/modernisation-platform-account/s3.tf
terraform/modernisation-platform-account/secrets.tf

#7943
Now that the multi-region KMS keys are in active use this PR removes the old keys and schedules them for deletion

Remove non-multi-region KMS keys

---

terraform/environments/core-logging/cortex.tf

https://github.com/ministryofjustice/modernisation-platform/actions/runs/11517694104
Removes a data call that does not appear to be references in code anywhere
Tested with CI pipeline

Remove data call from `core-logging`

---

terraform/environments/core-logging/observability.tf

This PR adds the `logs:AssociateKmsKey` for glue permissions as well as sorting lots permissions alphabetically.

Athena/glue permissions - logs:AssociateKmsKey

---

terraform/modernisation-platform-account/s3.tf

#7943 
Because the IAM policy applied to the `ModernisationPlatformGithubActionsRole` role in the MOJ Master account has a condition applied like so:
```
"Condition": {
"ForAnyValue:StringLike": {
"kms:ResourceAliases": [
"alias/s3-state-bucket"
]
}
}
```
This PR applies the old alias to the new multi-region key in order to preserve this functionality.
Broadly speaking the role needs this alias to point at the key used to encrypt the default state file in the root of the state file bucket, which Terraform uses to confirm that access to the backend is available prior to switching to the configured workspace.
Tested manually.
1. Remove alias from Modernisation Platform account manually
2. Amend KMS key used to encrypt `terraform.tfstate` in the root of the bucket to the new key
3. Run …

Added alias to multi_region kms key used for terraform state bucket

---

.github/workflows/publish-gh-pages.yml

#6333
Updates reference to tech docs publish and amends action in line with guidance [here](https://github.com/ministryofjustice/tech-docs-github-pages-publisher?tab=readme-ov-file#v4)
Will test through CI pipeline checks

Update version of tech docs publisher

---

environments-networks/platforms-test.json

Support request from Analytical Platform user to be able to connect QuickSight to a database which requires networking connectivity.
This will share the standard subnets into Analytical Platform Compute Test account so we can set up a vpc connection with QuickSight.
Will be tested post-implementation
This should not have impact on wider platform.

Adding standard networking to APC Test

---

environments-networks/platforms-production.json

Support request from Analytical Platform user to be able to connect QuickSight to a database which requires networking connectivity.
This will share the standard subnets into Analytical Platform Compute Production account so we can set up a vpc connection with QuickSight.
Will be tested post-implementation
This should not have impact on wider platform.

Adding standard networking to APC Production

---

environments/analytical-platform-compute.json

https://mojdt.slack.com/archives/C01A7QK5VM1/p1730285409189469
Removing this value should allow our scripts to populate the `networking.auto.tfvars.json` for analytical-platform-compute.
It has not been tested.
Deploy through CI. Fallback to manual terraform runs if required.

Remove isolated value from APC json

---

terraform/modules/kms/main.tf

These keys are currently not able to be used for s3 inventory generation
adds the `s3.amazonaws.com` service principal to allow the key to be used by the s3 service

Add S3 service principal to KMS keys

---

scripts/confirm-environment-owner/get-environment-owners.sh

Spotted bug whereby the wrong variable was used as the test to exclude MP's own environments.
Spotted an issue that would have prevented MP's own environments from being excluded from the notifications. This amends the bash script to use the right variable.
See above.
Yes - see https://github.com/ministryofjustice/modernisation-platform/actions/runs/11609777100/job/32327722227 (which has the subsequent steps disabled.

Confirm Owner Environments - Bug fix

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

#6170
This IAM statement restricts the ability of the `MemberInfrastructureAccessRole` to be passed to other entities.
Checked for any references to this role being passed to services in either this repository of `Modernisation-Platform-Environments`
https://aws.amazon.com/blogs/security/how-to-use-the-passrole-permission-with-iam-roles/
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_passrole.html

Denying `iam:PassRole` of infrastructure access roles

---

terraform/environments/core-vpc/vpc.tf

When running Terraform for one of the `core-vpc` workspaces the following warning is output:
```
│ Warning: Argument is deprecated
│ 
│   with aws_iam_role.member_delegation_read_only,
│   on vpc.tf line 320, in resource "aws_iam_role" "member_delegation_read_only":
│  320:   managed_policy_arns = ["arn:aws:iam::aws:policy/ReadOnlyAccess"]
│ 
│ The managed_policy_arns argument is deprecated. Use the aws_iam_role_policy_attachments_exclusive resource instead.
│ 
│ (and one more similar warning elsewhere)
```
This PR implements the `aws_iam_role_policy_attachments_exclusive` resource. Strictly speaking I don't think this exact resource is required, but it will enforce that only the read-only policy will be attached to this role, and any other policies will be detached should they be picked …

Resolve resource deprecation warning for read-only role

---

terraform/environments/bootstrap/member-bootstrap/iam.tf
terraform/environments/bootstrap/single-sign-on/policies.tf

#7907
Prior to implementing any controls or conditions, this PR separates out the `iam:PassRole` permission into separate statements in line with [AWS documented practice](https://aws.amazon.com/blogs/security/how-to-use-the-passrole-permission-with-iam-roles/).
Tested through CI pipelines; no practical impact from this PR.

Separate out `iam:PassRole` statements

---

terraform/modules/kms/main.tf

Trying to create a DMS Event Subscription targetting SNS encrypted with the general shared key fails with the following error:
```
│ Error: creating DMS Event Subscription (dms-task-event-alerts): operation error Database Migration Service: CreateEventSubscription, https response error StatusCode: 400, RequestID: 172d846f-d7ae-46e9-881e-fca921829ab9, KMSAccessDeniedFault: The request to create event subscription for SNS topic 'arn:aws:sns:eu-west-2:***:delius-dms-alerting' has failed because the ciphertext references a key that doesn't exist or DMS account doesn't have an access to
│ 
│   with module.environment_dev[0].module.dms[0].aws_dms_event_subscription.dms_task_event_subscription,
│   on modules/components/dms/cloudwatch-alarms.tf line 109, in resource "aws_dms_event_subscription" …
```

chore: add dms to kms service principal list

---

terraform/environments/bootstrap/secure-baselines/main.tf
terraform/modernisation-platform-account/baselines.tf

This PR updates the version or reference of the baseline module to the latest version in the repository. #8325

bump baselines module reference to 7.10.0

---

terraform/environments/core-shared-services/ecr_repos.tf

electronic-monitoring-data-preproduction  account needs access to ECR.
Adds electronic-monitoring-data-preproduction access to ECRs
n/a
no
n/a

Add ecr access for electronic-monitoring-data-preproduction account

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

#7907 
This PR prevents the `modernisation-platform-oidc-cicd` role from being passed to any AWS service or resource unless it is `ssm.amazonaws.com`.
This will prevent the accidental - or malicious - passing of this role to an unexpected resource such as an EC2 instance or lambda function.
Tested via ClickOps with `nomis-test` and @keirwilliams who confirmed the condition does not negatively affect their automation tasks.

Add condition to `modernisation-platform-oidc-cicd` `iam:PassRole` permission

---

.github/workflows/monitor-ecs-eks-amis.yml
.github/workflows/publish-gh-pages.yml
.github/workflows/scorecards.yml

Saw a few cases where our hash value refers to the latest version of the `artifact` action, but that isn't reflected by the comment.
EG: https://github.com/actions/upload-artifact/releases/tag/v4.4.3 has the SHA value `b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882`.

Update comments referring to action version

---

terraform/environments/bootstrap/single-sign-on/policies.tf

After modifying the artifact bucket's object ownership settings, cross-account users began experiencing permission issues while trying to upload objects using the CLI. Without `s3:PutObjectACL` permission, these users cannot set the ACL for their uploaded objects, resulting in a permissions error.
This PR addresses the issue where cross-account users are unable to upload objects to the artifact bucket due to missing permissions. By adding the s3:PutObjectACL permission, users from other accounts will now have the ability to set the ACL on the uploaded objects, ensuring successful uploads from the command line.
tested on nomis-test account developer role

Add s3:PutObjectAcl permission to allow object uploads from cross-account

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

Had the following through via Slack from @roncitrus :
```
Error: Failed to register task definition in ECS: User: arn:aws:sts::111111111111:assumed-role/modernisation-platform-oidc-cicd/GitHubActions is not authorized to perform: iam:PassRole on resource: arn:aws:iam::111111111111:role/task-cdpt-chaps because no identity-based policy allows the iam:PassRole action
Error: User: arn:aws:sts::111111111111:assumed-role/modernisation-platform-oidc-cicd/GitHubActions is not authorized to perform: iam:PassRole on resource: arn:aws:iam::111111111111:role/task-cdpt-chaps because no identity-based policy allows the iam:PassRole action
```
Adds `ecs` to allowed services for passrole permission.
Tested through CI pipeline tests

Add ecs to allowed services for oidc-cicd role

---

terraform/github/locals.tf

https://github.com/ministryofjustice/modernisation-platform/actions/runs/11728688602/job/32673722475#step:12:1959
Job is failing I believe as Katie's github account has been removed from the MoJ organisation.
Removing Katie's account form locals.

Remove `imkatiewatson` github account

---

terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf

We have long running overnight jobs in our test EKS cluster that are being shutdown
https://github.com/ministryofjustice/data-platform-support/issues/946
Excludes APC non-prod accounts
It hasn't
I don't think so
Signed-off-by: Jacob Woffenden <jacob.woffenden@justice.gov.uk>

🙅 Exclude Analytical Platform Compute accounts from instance scheduler

---

terraform/modernisation-platform-account/iam.tf

This PR updates the OIDC role configuration to enhance security and ensure least-privilege access for GitHub Actions workflows. #8078 
Previously, the OIDC role allowed all workflows to potentially perform `terraform apply` actions without restrictions to specific branches, which posed a risk of destructive actions occurring without sufficient review. By splitting roles and restricting `apply` to the main branch, this PR mitigates the risk of unauthorized or unreviewed changes.

Separate OIDC roles for Terraform plan and apply with branch-based restrictions

---

scripts/provision-member-directories.sh

#8272 
Removes `providers.tf` from the autogenerated `CODEOWNERS` file we populate [modernisation-platform-environments](https://github.com/ministryofjustice/modernisation-platform-environments) with.
This is a precursory step to renaming the `platform_providers.tf` file in our templates directory.
Tested script locally and confirmed behaviour
Deploy through CI, review PR in modernisation-platform-environments

Amend `provision-member-directories.sh`

---

terraform/modernisation-platform-account/iam.tf

The` github-actions-plan` policy currently does not allow assuming roles and is missing required permissions for actions in the GitHub workflow. This results in failures when attempting to execute tasks during the `plan` step. #8078 
The updated permissions explicitly grant the` sts:AssumeRole` action for the required roles and ensure that the policy includes read-only permissions for all resources needed during the `plan` step. This resolves the failures encountered when attempting to assume roles or access specific AWS resources in the current setup.
tested manually editing the role

Fix permissions for GitHub Actions plan role to allow role assumption and add missing permissions

---

collaborators.json

https://github.com/ministryofjustice/analytical-platform-ithc-2024/issues/26
External collaborators need read-only + security-audit access.
Bumping them to the new `security-read-only` access level
Testing post-deployment
This should not impact wider platform.

Moving AP collaborators to different access level

---

terraform/modernisation-platform-account/s3.tf

https://github.com/ministryofjustice/modernisation-platform/issues/8360
Adds a SSM inventory sync bucket and associated policy which grants the SSM service permission to add objects as long as they are in they originate from MP OU.
Next step will be to add a resource data sync to the bootstrap so that all other environments can send their inventory data to this central bucket.
Terraform plan in status checks.

 Add SSM Inventory Sync bucket/policy to Mod Platform account

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/11878640330
Nuke jobs all failed due to a lack of permissions for CloudWatch Synthetics
Not tested - but this is a simple PR that adds a permission to a role which we regularly manipulate.

Add permission for CloudWatch Synthetics to MemberInfrastructureAccess

---

source/concepts/environments/single-sign-on.html.md.erb

fixup numbering and update to previous sso instructions

fixup numbering

---

terraform/environments/bootstrap/single-sign-on/policies.tf

https://mojdt.slack.com/archives/C01A7QK5VM1/p1731918476419409
This PR addresses the issue where cross-account users are unable to download objects to the artifact bucket due to missing permissions. By adding the s3:GettObjectACL permission, users from other accounts will now have the ability to get the objects, ensuring successful download from the command line.
Tested manually on developer role

Add s3:GetObjectACL permission to allow cross-account object download

---

.github/workflows/remove-default-vpc.yml

This PR updates the GitHub Actions OIDC role to enhance security by restricting admin-level permissions to the `main` branch only #8078 
Admin permissions are only available on the main branch, preventing potentially harmful terraform apply commands from running in pull requests or non-reviewed branches.
Engineers must go through the review and merge process, enforcing compliance with the code review policies and enhancing overall security.

Restrict GitHub OIDC role permissions to main branch

---

terraform/environments/bootstrap/single-sign-on/main.tf

#8285
This PR attaches an AWS managed policy to the Data Engineering role so that data engineers can responsibly investigate what they require to place into code for Lake Formation cross-account sharing.
Cross-account sharing will still require the receiving account to accept the resource share.
You can see the AWSLakeFormationCrossAccountManager policy [here](https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AWSLakeFormationCrossAccountManager.html).
You will note that it does not have [ram:AcceptResourceShareInvitation](https://docs.aws.amazon.com/ram/latest/APIReference/API_AcceptResourceShareInvitation.html).
Will be tested by deployment to sprinkler

Additional data engineer permissions

---

terraform/environments/bootstrap/member-bootstrap/iam.tf
terraform/environments/bootstrap/single-sign-on/policies.tf

#8050 
This PR adds a new role and policy configuration for GuardDuty S3 malware protection. This will help detect and mitigate malware in files uploaded to S3 buckets across our accounts. 
The policy gives permissions for:
EventBridge Management: Managing rules and targets specific to GuardDuty operations.
S3 Access: Accessing objects, managing bucket notifications, and handling validation objects for scanning. But also tagging so post-scan it will show if threat was found/not found.
KMS: for decryption
More detailed information can be found here: https://docs.aws.amazon.com/guardduty/latest/ug/malware-protection-s3-iam-policy-prerequisite.html
Will this deployment impact the platform and / …

Add GuardDuty S3 malware protection role and policy

---

terraform/modernisation-platform-account/iam.tf

This PR updates the GitHub Actions OIDC role to include the missing assume roles that were causing failures in the pipeline. Certain workflows were failing due to insufficient permissions for assuming the necessary roles, leading to execution errors. By adding the required assume roles to the OIDC role configuration, these failures will be resolved. #8078

Fix Missing Assume Roles in GitHub Actions OIDC Plan Role

---

terraform/modernisation-platform-account/iam.tf

This PR updates the GitHub Actions OIDC role to include the missing assume role that were causing failures in the pipeline.
https://github.com/ministryofjustice/modernisation-platform/actions/runs/11912296203/job/33197467818#step:12:26

Update assume role in OIDC plan role

---

.github/workflows/reusable_terraform_plan_apply.yml
.github/workflows/scheduled-baseline.yml

#8078 
Ensures that each action uses the appropriate AWS role for security and compliance. Reduces duplication by keeping the workflow as a single job with conditional steps. Maintains clarity and efficiency in the workflow definition.

Add conditional OIDC role switching for Terraform plan and apply jobs

---

terraform/modernisation-platform-account/s3.tf

Having created a central bucket to store inventory data in the Modernisation Platform account I subsequently tried to create a resource data sync from Sprinkler but encountered an access denied error: https://github.com/ministryofjustice/modernisation-platform/actions/runs/11895397311/job/33146521856?pr=8517#step:7:236
After troubleshooting with AWS support it seemed that my policy where I had deviated slightly from AWS's [suggested one](https://docs.aws.amazon.com/systems-manager/latest/userguide/inventory-create-resource-data-sync.html#systems-manager-inventory-resource-data-sync-AWS-Organizations) was causing the issue.
I can only restrict this down to the source org ID of the MoJ organization rather than a `ForAnyValue:StringLike` in `aws:PrincipalOrgPaths`.
Though this means MoJ …

Edit SSM Inventory Sync bucket policy for matching source org ID

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

This PR removes the `github-actions` and `MemberInfrastructureAccess` roles from `Sprinkler` and will be replaced with a new role in a subsequent PR.

Remove github-actions role from Sprinkler

---

terraform/environments/sprinkler/iam.tf

This PR introduces an OIDC role for Sprinkler to replace the previously removed `github-actions` role.

Add OIDC role for sprinkler

---

terraform/environments/bootstrap/member-bootstrap/iam.tf
terraform/environments/bootstrap/member-bootstrap/locals.tf

This PR updates the creation of the `MemberInfrastructureAccess` role in the Sprinkler environment to accommodate the new GitHub OIDC role configuration. Since the GitHub OIDC role is now created in its own account, it is no longer accessible via the previously used module (`module.github-oidc[0]`). Therefore, we are adding a new `member-access-sprinkler` module to ensure that the `MemberInfrastructureAccess` role is correctly created in the Sprinkler environment with the correct trust relationship.

Update MemberInfrastructureAccess role creation for Sprinkler with new GitHub OIDC

---

terraform/environments/bootstrap/member-bootstrap/iam.tf
terraform/environments/bootstrap/member-bootstrap/locals.tf

This PR introduces conditional logic to the `sprinkler_oidc` IAM role data block. The role is only loaded for the `sprinkler-development` workspace, ensuring that it is not retrieved or used in other environments.

Conditionally load OIDC role for `sprinkler-development` workspace only

---

terraform/pagerduty/aws.tf
terraform/pagerduty/member-services-integrations.tf

Alerts for failed pipelines (github or SSM) are distracting in the main application alerting channels.
Creates a separate pagerduty integration specifically for pipeline monitoring using an existing DSO channel. Linked to pagerduty so we can still see all alarms on one PagerDuty page.
Also adds some missing Pagerduty Integration Secrets for DSO.
Ensures all DSO pagerduty integrations are added via a for loop to avoid future mistakes
For the integration secrets, first tested to make sure the pagerduty_service_integration.integrations for loop doesn't introduce any plan changes. It didn't, see https://github.com/ministryofjustice/modernisation-platform/actions/runs/11957369113/job/33334360508?pr=8560. Then added the pagerduty_service_integration.az_dso_alerts for loop which  add our missing …

TM-720: add missing DSO pagerduty integrations

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

#8050 
This PR updates the MemberInfrastructureAccess IAM role to include:
- Trust policy for `malware-protection-plan.guardduty.amazonaws.com.
- Permissions to create and manage GuardDuty malware protection plans for S3.
The role already has permissions for:
EventBridge Management: Managing rules and targets specific to GuardDuty operations.
S3 Access: Accessing objects, managing bucket notifications, and handling validation objects for scanning. But also tagging so post-scan it will show if threat was found/not found.
KMS: for decryption
More detailed information can be found here: https://docs.aws.amazon.com/guardduty/latest/ug/malware-protection-s3-iam-policy-prerequisite.html
Will this …

add guardduty permissions and update trust policy for MemberInfrastructureAccess role

---

terraform/pagerduty/member-services-integrations.tf

Some DSO alerts are not showing in "impacting incidents" page in PagerDuty
This assigns a default priority to AZ DSO alerts which ensures these alerts then show up in the impacting incidents business service page.
This is already working for some of our alerts - we just missed some for our az services
No

TM-720: set default priority on DSO pagerduty alerts

---

.github/workflows/reusable_terraform_plan_apply.yml

This PR will remove the conditional logic for the OIDC role, as it is causing issues during Terratest runs due to the use of github-action-plan, which has only read permissions. By removing this condition, it will revert to using the previous GitHub Actions role, restoring the earlier functionality.

Remove Conditional logic to switch OIDC role

---

terraform/environments/bootstrap/member-bootstrap/ssm.tf

https://github.com/ministryofjustice/modernisation-platform/issues/8360
This PR creates a resource data sync in the bootstrap which will send all the gathered inventory data into a central bucket in the `organisation-security` account.
To note:
An SSM [global inventory association](https://docs.aws.amazon.com/systems-manager/latest/userguide/inventory-collection.html#inventory-management-inventory-all) has already been applied to every account because AWS Inspector has been configured at the organisation level. This means that by default any accounts with instances using the SSM agent are already reporting their inventory information every 30 minutes. This is why I haven't configured a separate resource to enable this as the information is already being collected. This PR will now ensure …

Add inventory resource data sync to member bootstrap

---

terraform/modernisation-platform-account/s3.tf

Recent changes to the Sprinkler workflow require the use of the `github-actions` role created in the Sprinkler account. To ensure compatibility, the S3 bucket policy must grant appropriate permissions to the `github-actions` role for specific operations on defined folders within the state bucket. #8078 
The updated policy ensures that the `github-actions` role has the necessary permissions to execute the Sprinkler workflow without permission errors. This change aligns the policy with the new workflow requirements.
Tested manually

Update S3 bucket policy to support Sprinkler workflow using GitHub Actions role

---

.github/workflows/bootstrap-sprinkler.yml
terraform/environments/sprinkler/iam.tf

Previously, the workflow used the github-actions role in the Modernisation Platform (MP) account. Due to a recent change restricting the OIDC role in the MP account, the workflow is updated to use the github-actions role in the Sprinkler account. This allows the workflow to function as expected for pull request events. #8078 
By switching to the github-actions role in the Sprinkler account, the workflow can continue to process pull request events. This change resolves the issue caused by OIDC restrictions in the MP account and ensures proper functionality.|

Update workflow to use GitHub Actions role from Sprinkler account

---

terraform/environments/bootstrap/member-bootstrap/ssm.tf

Relates to Issue https://github.com/ministryofjustice/modernisation-platform/issues/8360
Reverts PR ministryofjustice/modernisation-platform#8517
I'm reverting this PR for now as we have a clash in around 131 Mod Platform accounts where we have already hit the hard limit of 5 SSM resource data syncs. 
See [error log](https://github.com/ministryofjustice/modernisation-platform/actions/runs/12046298138) for reference.
We will need to review and rationalise our use of these resources before this work can continue.

Revert "Add inventory resource data sync to member bootstrap"

---

.github/workflows/core-vpc-development-deployment.yml
.github/workflows/core-vpc-preproduction-deployment.yml
.github/workflows/core-vpc-production-deployment.yml
.github/workflows/core-vpc-test-deployment.yml
.github/workflows/failed-workflows-report.yml
.github/workflows/generate-dependabot-file.yml
.github/workflows/new-environment-files.yml
.github/workflows/new-environment.yml
.github/workflows/new-member-environment-files.yml
.github/workflows/publish-gh-pages.yml
.github/workflows/reusable_terraform_plan_apply.yml
.github/workflows/scheduled-baseline.yml
.github/workflows/terraform-github.yml
.github/workflows/terraform-member-environment.yml
.github/workflows/terraform-static-analysis.yml

This morning I noticed that our slack failure notifications were not working when merging a PR e.g. https://github.com/ministryofjustice/modernisation-platform/actions/runs/12046298138/job/33587774224#step:10:26
The `slackapi/slack-github-action` was updated to `v.2.0.0` a couple of weeks back which introduced some breaking changes https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0
Specifically for us.... _This Action now requires setting the `webhook-type` as a step input value._
I spent a little while considering if this was a candidate for a reusable workflow as I've had to make many repetitive updates to fix the problem. But as this failure notification runs as a step within a job and you cannot use a reusable workflow, instead you need a composite workflow and I …

Fix slack failure notifications in MP workflows

---

terraform/environments/core-logging/athena.tf

#8545 
The AccessDenied error encountered when the athena_table_update Lambda function attempts to retrieve the environment_management secret from AWS Secrets Manager was caused by the Lambda function using an incorrect single-region KMS key for decryption, instead of the multi-region key associated with the secret.

Use multi-region KMS key for environment management

---

.github/workflows/collaborator-inactivity-monitoring.yml
.github/workflows/secrets-rotation-reminder.yml
.github/workflows/terraform-member-environment.yml

This change adds workflow_dispatch to the GitHub workflow to allow manual execution of pipelines.
The purpose is to test the default GitHub token by providing the necessary permissions. Manually triggering these pipelines will help verify whether the token works correctly after adding the required permissions. #8476

Add workflow_dispatch to enable manual trigger in GitHub workflow

---

terraform/environments/bootstrap/member-bootstrap/collaborators.tf
terraform/environments/bootstrap/member-bootstrap/iam.tf
terraform/environments/bootstrap/member-bootstrap/notifications.tf
terraform/environments/bootstrap/single-sign-on/policies.tf

As part of https://github.com/ministryofjustice/modernisation-platform/issues/7825 I've been looking at the ability to monitor/alert for root account activity.
As part of this I've noticed that the baselines code has already deployed a set of alarms for certain scenarios to all MP accounts, including root usage activity: https://github.com/ministryofjustice/modernisation-platform-terraform-baselines/blob/main/modules/securityhub-alarms/main.tf#L133
These are labelled "security-hub alarms" and have been deployed as they are direct recommendations from the security hub controls e.g. AWS/CIS best practices.
Currently we only receive alerts for these issues where we have subscribed our "core" accounts (i.e. `core-shared-services`, `core-logging`, `core-network-services`, `core-security`, …

Subscribe member account alarms into pagerduty/slack

---

terraform/pagerduty/member-services-integrations.tf

Must clear the underlying issue
Notifications raised by CloudWatch alarms for Oracle should not clear automatically if still in alarm state.
Remove auto-resolve.
Change required for testing.
This is for development notifications only - no live service impact.
PROD not applicable at present.

Remove auto-resolve-timeout for Oracle notifications

---

terraform/environments/digital-prison-reporting/iam.tf

The digital prisons reporting `circle_ci` role needs to be able to modify DMS instances e.g. when performing an upgrade.
This PR grants `dms:ModifyReplicationInstance` to the `circle_ci` role
N/A
No
None

DPR2-1553: Grant dms:ModifyReplicationInstance to DPR circle_ci

---

terraform/environments/core-shared-services/instance-scheduler-lambda-function.tf

This PR updates the instance scheduling skip list by adding missing accounts that were causing the `InstanceSchedulerLambdaFunctionPolicy` role to fail in assuming the `InstanceSchedulerAccess` role. These accounts were previously skipped due to being either **member-unrestricted** or opted out by the **members**.
By adding these accounts to the skip list, we ensure that the scheduling process runs smoothly without triggering alarms in the **low-priority channel**, as these accounts should not cause unnecessary notifications.
#8558 
#8559

Update Instance Scheduling Skip List to Include Missing Accounts

---

terraform/pagerduty/member-services-integrations.tf

Some pagerduty alarms are being missed, especially over long weekend, due to auto resolve
Disables auto resolve. Each alarm needs to be resolved in AWS/Azure, slack or pagerduty
Other services already have same setting so assume this works.
No

TM-781: disable pagerduty alarm auto resolve for DSO services

---

source/concepts/networking/dns.html.md.erb
source/user-guide/how-to-configure-dns.html.md.erb

This PR updates the link to the new location for the MoJ Domain Naming Standard. All DNS related guidance is being co-located in the Operations Engineering User Guide.
Updated link to Domain Naming standard
N/A
No. Just update to documentation
I like your template 😀

Update links to domain naming standard

---

environments/cooker.json

MoJ Read Team will be using this account temporarily, so we don't want to destroy the resources in this account
Excludes cooker from the Nuke job
NA
NA
NA

🙈 Exclude Cooker From Nuke

---

terraform/github/modules/repository/main.tf
terraform/github/modules/repository/variables.tf
terraform/github/repositories.tf

No issue - but I've noted that our commit messages aren't always to the highest standard; GitHub can allow us to - by default - set the commit title & message in a squash merge to the PR title and concatenated commit messages by default
Sets the values for `squash_merge_commit_message` and `squash_merge_commit_title`.
Tested through local plan.
Deploy through CI.

Added optional configuration to keep squash merges tidy

---

terraform/environments/bootstrap/single-sign-on/policies.tf

This enables sandbox users to quickly set up SSM on instances if they are clickopsing.
Note the role is already in sprinkler hence no changes sprinkler plan and apply

Add SSM quicksetup to sandbox policy

---

terraform/environments/bootstrap/single-sign-on/main.tf

https://github.com/ministryofjustice/modernisation-platform/actions/runs/12236290660/job/34131158803#step:7:3385
Removes the resource that attaches lakeformation permissions. For what it's worth I can't actually see how this duplication occurs, but as the policy was only attached as a convenience we're removing it.
Tested via local plan

Remove lakeformation managed policy 

---

policies/networking/expected.rego

A missing comma in [this PR](https://github.com/ministryofjustice/modernisation-platform/pull/8713/files) is causing the linter to fail
Adds the missing comma
Tested locally with `regal lint`

Fix missing comma in `expected.rego`

---

scripts/git-commit.sh

Failures such as the following are not triggering a failed GitHub Actions step, and as such not being surfaced through Slack notifications:
https://github.com/ministryofjustice/modernisation-platform/actions/runs/12297013276/job/34319794955#step:6:24
Ensure script exits out on failure
It hasn't.

Ensure `git-commit.sh` triggers Slack notifications when failing.

---

.github/workflows/new-member-environment-files.yml

This PR reverts the workflow to using the old `TERRAFORM_GITHUB_TOKEN` after encountering commit failures with the new `MODERNISATION_PAT_MULTIREPO` token. The new token caused issues when pushing changes to the `modernisation-platform-environments` repository, resulting in a `403` permission error.
https://github.com/ministryofjustice/modernisation-platform/actions/runs/12297013276/job/34317223598#step:6:24

Revert to using old TERRAFORM_GITHUB_TOKEN due to commit failures with MODERNISATION_PAT_MULTIREPO

---

.trivyignore.yaml

As described; there's an entry in the trivyignore that breaks the YAML and means that Trivy can't parse it.

Remove breaking line from trivy ignore file

---

terraform/environments/secrets.tf

Cooker is cureently being used by MoJ Red team for a special project and we don't want it to be nuked at the weekend.
This removes cooker from being hard-coded into the nuke secret. Ideally we should follow-up and make all the testing accounts follow the same convention as any other sandbox 

Remove cooker from `autonuke` secret

---

terraform/environments/digital-prison-reporting/iam.tf

Error below was encountered when applying terraform changes in dev.
```
Error: moving DMS Replication Task (dpr-dms-dps-postgres-s3-dps-inc-reporting-task-development): operation error Database Migration Service: MoveReplicationTask, https response error StatusCode: 400, RequestID: f7f5ca3c-0bef-40d1-bbd5-cf0fa0f05ffb, api error AccessDeniedException: User: arn:aws:sts::771283872747:assumed-role/circleci_iam_role/circleci-oidc-session is not authorized to perform: dms:MoveReplicationTask on resource: arn:aws:dms:eu-west-2:771283872747:rep:34VQXCP7DNFIPI7ZFSC43FAYOQ because no identity-based policy allows the dms:MoveReplicationTask action
```
https://app.circleci.com/pipelines/github/ministryofjustice/digital-prison-reporting-domains/1935/workflows/c64347ab-af99-4bf8-b670-3126e9da626e/jobs …

DPR2-1450: Add MoveReplicationTask to circleci role

---

environments-networks/platforms-production.json
policies/networking/expected.rego

#8621
Completes [part two ](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/creating-accounts-for-end-users.html#networking-stage)of our new account setup. Does a little extra alphabetising.
Deploy through CI. Confirm RAM shares are in place following deployment

Add `analytical-platform-common` to networking resources

---

.github/workflows/core-vpc-development-deployment.yml
.github/workflows/core-vpc-preproduction-deployment.yml
.github/workflows/core-vpc-production-deployment.yml
.github/workflows/core-vpc-test-deployment.yml

When running the ram association jobs I encountered an error where terraform is not installed on the GHA runner e.g. https://github.com/ministryofjustice/modernisation-platform/actions/runs/12350065862/job/34462206713#step:5:25
This PR adds a setup terraform step to the ram association jobs as latest version of ubuntu (24.04) does not have it pre-installed in GHA runners
See [here](https://github.com/actions/runner-images/issues/10636) for more details.
Longer term we could finesse this setup in our backlogged issue to make this a reusable workflow step: https://github.com/ministryofjustice/modernisation-platform/issues/8233
Difficult to test as the ram association step is skipped unless running on main but I …

Add setup terraform step to ram association jobs

---

environments/analytical-platform-common.json

After speaking to @jacobwoffenden we're changing this account type to `member` as it should create the necessary files to create infra/pipelines in the `modrnisation-platform-environments` repository. 
Also there wasn't a real need for the account to be unrestricted.
Changes account type.

Change `analytical-platform-compute-common` to `member` account type

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

https://github.com/ministryofjustice/analytical-platform/issues/6355
Running a POC in SageMaker JumpStart and encountering this while applying: https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/12392755001/job/34593931257?pr=9132#:~:text=Error%3A%20creating,sagemaker%3AAddTags%20action
Adds `sagemaker` permissions to the infra role.
Test post-deployment
N/A

Add SageMaker permissions to Deployment role

---

source/concepts/sdlc/sandbox-testing-environments.html.md.erb
source/getting-help/index.html.md.erb
source/runbooks/accessing-aws-accounts.html.md.erb
source/runbooks/revoke-network-access.html.md.erb
source/user-guide/workflow-status.html.md.erb

User Guide and Runbook reviews on 27/12.

User Guide & Runbook Reviews on 27/12

---

terraform/environments/bootstrap/member-bootstrap/notifications.tf

https://github.com/ministryofjustice/modernisation-platform/actions/runs/12319236885/job/34387352123#step:7:302
Places a `depends_on` similarly to an [existing example](https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/environments/bootstrap/member-bootstrap/notifications.tf#L25) in the same code.
I'm not 100% convinced that this is the right approach - if anything this feels like a tactical fix that we should look at again in a strategic manner. Relying on a data call to retrieve an SNS topic created elsewhere doesn't feel right to me, but we might want to raise an issue / discuss with our TA a more strategic approach.
Ran local plan. Tested through CI.
A more thorough test might involve a `terraform apply --destroy` in say, the `sprinkler-development` …

Temporarily resolve SNS topic error for new account bootstrapping

---

scripts/git-commit.sh

We are seeing the git-commit.sh script fail when there are no changes to commit, e.g.
```
Switched to a new branch 'date-1734447481'
On branch date-1734447481
nothing to commit, working tree clean
Error: Process completed with exit code 1.
```
https://github.com/ministryofjustice/modernisation-platform/actions/runs/12374331516/job/34540652979
The issue seemed to be that when the script runs a `git commit` and there are no changes the script would exit with code 1.
Runs successfully here: https://github.com/ministryofjustice/modernisation-platform/actions/runs/12379611085/job/34554145511

Graceful handling of git commit in `git-commit.sh`

---

scripts/internal/modernisation-member-information.sh

The function was defined as extract_member_readme_info but was being called as extract_service_info, causing the script to break. By aligning the function name with its references, this PR ensures the script runs as intended.

Fix function call error by renaming `extract_service_info` to `extract_member_readme_info`

---

terraform/environments/core-shared-services/vpc.tf

Attempting to manage the association of the `s3` gateway endpoint with the route table associated with the private subnets in the `core-shared-services` additional cidr results in some resource thrashing.
VPC endpoint route table associations can be handled by the resource that creates the endpoint, or by the association resource, but not by both simultaneously.
This PR disaggregates the association of the gateway endpoint with the route tables from the resource creation.
Tested with local plan and CI pipeline

Use `aws_vpc_endpoint_route_table_association` resource

---

environments-networks/yjb-development.json

Adds the necessary steps and configuration for extending a newly created private DNS zone to the required VPCs.
[extending-the-newly-created-private-dns-zone](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/creating-new-private-dns-zones.html#extending-the-newly-created-private-dns-zone)
The newly created private DNS zone was not associated with the required VPCs, causing DNS resolution issues within the VPCs. This PR ensures the zone is correctly created and associated.

Add support for extending private DNS zone to relevant VPC

---

environments/cooker.json

As requested in the ask channel here: https://mojdt.slack.com/archives/C01A7QK5VM1/p1736171196013009
And after the requirement was refined in a private group chat here: https://moj.enterprise.slack.com/archives/C087EKMGXLK
1. Removes `MoJRedTeam` acceess from cooker as they no longer require it.
2. Grants`tvm-purple-team` access to cooker as agreed

Remove `MoJRedTeam` and grant`tvm-purple-team` access to cooker

---

scripts/failed-workflows-report/create-slack-report.sh
scripts/failed-workflows-report/get-failed-workflows.sh

This change prevents any no-failed-workflows alerts being sent to the MP team slack channel. This cuts down on the overall noise of the channel.
This was mentioned in today's team retro.
If no failed workflows are found then the steps to create & send the report are skipped. The shell script that compiles the report has the "no faults found" option removed.

Stops "No failed workflows" notification being sent to the team slack.

---

environments/nomis-combined-reporting.json

NART team are unable to run ansible to patch SAP software.
Ansible requires ssm and s3:DeleteObject permissions.  Neither instance-access nor instance-management allow s3:DeleteObject. Since NART will be patching EC2 instances anyway with sudo, it seems reasonable to grant them developer access, in the same way we do DBAs.
Tested ansible patching using lesser roles and it doesn't work. Developer role is known to work.
No

TM-844: update nart role to enable patching

---

scripts/generate-dependabot-file.sh

#7053 
Updates the `generate-dependabot-file.sh` to do the following:
* Clear the file at the start of the script running to ensure a clean run
* Replace the `for` expression that created `directory:` keys with one that populates a single `directories:` key
Tested locally.
Deploy through CI. Run `Generate Dependabot file` action then review / merge PR to update Dependabot action.

Use `directories` key for Dependabot action

---

terraform/environments/core-shared-services/ecr_repos.tf

Add push/pull principals to facilitate the move of a lambda function from one AWS account to another.
Relates to [this](https://github.com/ministryofjustice/analytical-platform/issues/6517) issue. 
Adds the correct push/pull principals for the new AWS account. I'll remove the old ones once this is working. 
NA
Allows pulls from another AWS account.

:wrench: Add push/pull principals

---

terraform/environments/core-shared-services/ecr_repos.tf

This PR resolves errors seen as a result of [this](https://github.com/ministryofjustice/modernisation-platform/commit/1783aae3e2e08b8bef8ae2f440740bd0b23eeefe) previous commit. 
This was raised in [this](https://mojdt.slack.com/archives/C06TFT94JTC/p1736429549168269) Slack thread.

:adhesive_bandage: Fix `arn:aws:iam` -> `arn:aws:lambda`

---

terraform/environments/core-shared-services/ecr_repos.tf

https://github.com/ministryofjustice/modernisation-platform/actions/runs/12706190508/job/35418649556
Forces the full principal as, for reasons I'm not currently sure of, the ECR policy for this repository is not expanding out an AWS account ID into a full principal
Tested with local Terraform plan only

Force full principal for data-platform-jml-extract-lambda ECR policy

---

environments/analytical-platform-compute.json
environments/analytical-platform-ingestion.json
environments/cooker.json

This removes a number of accounts from the instance-scheduler that had been erroneously included following the move away from the fixed skip lists.

Adds additional accounts to skip instance-scheduler.

---

architecture-decision-record/0032-ncsc-pdns-not-at-platform-level.md
architecture-decision-record/0034-use-cloud-map.md
architecture-decision-record/0035-terraform-workspaces.md
architecture-decision-record/README.md

https://github.com/ministryofjustice/modernisation-platform/issues/8960
It doesn't, but it does document the decision
N/A
N/A

Update ADR list and add ADR for workspace use

---

.github/workflows/access-keys-monitoring.yml
scripts/iam-monitoring/access-key-monitoring/notify_access_key_deletion.py

As per ticket https://github.com/ministryofjustice/modernisation-platform/issues/8359 this PR updates the `access-keys-monitoring` script to use a generic gov notify template containing only ((subject)) and ((message)) personalisation's (see below screenshot).
The email body and subject are now defined in code and passed to Gov Notify.
Tested locally and emailed received successfully:

Update Access Monitoring to use generic template

---

.github/workflows/core-vpc-development-deployment.yml
.github/workflows/core-vpc-preproduction-deployment.yml
.github/workflows/core-vpc-production-deployment.yml
.github/workflows/core-vpc-test-deployment.yml
.github/workflows/reusable-member-account-ram-association.yml

This PR introduces a reusable GitHub Actions workflow for associating a member account with RAM. #8233 
Previously, multiple workflows may have repeated steps to perform RAM association. With this reusable workflow, the steps can be centralized and reused across projects, improving consistency and reducing duplication of effort.

Add reusable workflow for member account RAM association

---

terraform/environments/bootstrap/single-sign-on/policies.tf

YJAF are struggling to delete resources with sandbox role, example error:
```
Error: deleting CodeDeploy Application (841c729b-4e5d-442d-802c-0f5456acaef3:ui): operation error CodeDeploy: DeleteApplication, https response error StatusCode: 400, RequestID: 00f872cb-b2ba-4ae9-969d-115e1dae0323, api error AccessDeniedException: User: arn:aws:sts::711387140977:assumed-role/sandbox/sandbox-moj is not authorized to perform: codedeploy:DeleteApplication on resource: arn:aws:codedeploy:eu-west-2:711387140977:application:ui because no identity-based policy allows the codedeploy:DeleteApplication action
```
Adds `codedeploy:*` to teh sandbox role. …

Enable `codedeploy:*` for the sandbox role

---

terraform/environments/bootstrap/single-sign-on/policies.tf

https://mojdt.slack.com/archives/C01A7QK5VM1/p1737114582221569
Developers have the ability to request service quota increases. In some instances, those quota changes require the ability to create service-linked roles to an account. So that developers can continue to self-serve their quota requests, this PR grants them the necessary permission.
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create-service-linked-role.html
N/A

added permission for service linked roles to developer permissions

---

terraform/environments/bootstrap/single-sign-on/policies.tf

https://github.com/ministryofjustice/modernisation-platform/issues/8617
Adds back the AllowPassRoleForBackup statement using the local environment_management to obtain the current account id. This was chosen as updating the existing statement to use the local was resulting in an low-level error with the plan. See above ticket for further details.
Sprinkler bootstrap.
None - this adds back the statement to developer_policy.

Issue/8617 - Using local environment_management to obtain the local account id.

---

.github/workflows/new-environment.yml
scripts/json-changes-notifier.py

As per ticket https://github.com/ministryofjustice/modernisation-platform/issues/8359 this PR updates the `json-changes-notifier` script to use a generic gov notify template containing only ((subject)) and ((message)) personalisation's (see below screenshot).
The email body and subject are now defined in code and passed to Gov Notify.
Tested locally and emailed received successfully:

Update `json-changes-notifier` to use generic template

---

terraform/modernisation-platform-account/s3.tf

#8345 
Amends S3 bucket policy to allow the deletion of `terraform.tfstate.tflock` files. This is necessary in order to cleanly remove locks after Terraform runs complete
Checked against Terraform documentation and AWS guidance
Deploy through CI. This PR _adds_ permissions so there ought to be no negative impact to existing workflows.
https://developer.hashicorp.com/terraform/language/backend/s3#s3-bucket-permissions
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_resource.html

Added bucket statement to allow GitHub Actions to delete tflock files

---

environments/delius-core.json
environments/delius-iaps.json
environments/delius-jitbit.json
environments/delius-mis.json
environments/delius-nextcloud.json

We used to use the hmmps-migration team but have had a team restructure and want to use the hosting-migrations team now
It adds the hosting-migrations team to the envs we need access to
The built in github checks are the only ones being used here
No as it is only adding access to a new team

add hosting-migrations team to their environments

---

terraform/environments/core-vpc/vpc.tf
terraform/modules/r53-dns-firewall/README.md
terraform/modules/r53-dns-firewall/fetch-aws-managed-domain-lists.sh
terraform/modules/r53-dns-firewall/main.tf
terraform/modules/r53-dns-firewall/outputs.tf
terraform/modules/r53-dns-firewall/variables.tf
terraform/modules/r53-dns-firewall/versions.tf

https://github.com/ministryofjustice/modernisation-platform/issues/7474
This PR adds a new module `r53-dns-firewall` which creates the following resources per VPC:
-  a R53 Resolver Firewall Rule Group 
- a custom list of allowed and blocked domains which can be defined via locals
- R53 Resolver Firewall Rules in the following priority:
**1** - An allow rule for the custom allowed domains list
**2-5** - a set of rules that alert any domains that match the [AWS-managed threat lists](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver-dns-firewall-managed-domain-lists.html)
**6** - A Block rule for the custom blocked domains list
- Associates the rule group to the VPC
- R53 Resolver query logging config to be associated with a cloudwatch log group
- Cloudwatch alarm so any …

Enable R53 DNS Firewall in ALERT mode

---

terraform/environments/core-network-services/cidr-ranges.tf

CIDR range for Global Protect is no longer accurate as discussed in [this Slack thread](https://mojdt.slack.com/archives/C01A7QK5VM1/p1737540393862249).
Updates the CIDR block for Global Protect.

Update CIDR block for `global-protect`

---

.github/workflows/new-environment.yml

Part of ticket https://github.com/ministryofjustice/modernisation-platform/issues/8359 this PR adds a step to the workflow to validate the template version ensuring the template hasn't been altered
similar PR merged here https://github.com/ministryofjustice/modernisation-platform/pull/8992
local testing version validation (incorrect template specified):
local testing version validation (correct template specified):

Add Template Validation to workflow

---

environments/delius-core.json

Give zaizi-devs group access to delius-core-dev account with instance-access role.

chore: add zaizi-devs to delius-core-dev

---

terraform/modernisation-platform-account/s3.tf

#8345 
Amends the S3 bucket policy so that Sprinkler can place native terraform locks into S3.
The bucket policy allows Sprinkler slightly broader wildcard permissions, but this is in line with other roles.

Allow Sprinkler to place native lockfiles

---

terraform/single-sign-on/backend.tf

#8345
Removes the `dynamodb_table` and inserts one to use native state locking
Tested with CI pipeline

Set `single-sign-on` to use native lockfile

---

terraform/modernisation-platform-account/backend.tf

#8345
Removes the use of DynamoDB and sets the backend to use native state locking
Tested with CI pipeline

Set modernisation platform account to use native locking

---

terraform/environments/bootstrap/member-bootstrap/iam.tf
terraform/environments/sprinkler/iam.tf
terraform/github/testing-ci.tf
terraform/modernisation-platform-account/iam.tf
terraform/modernisation-platform-account/s3.tf
terraform/single-sign-on/backend.tf

#8345
Where roles permit access to the `modernisation-platform-terraform-state` S3 bucket, this PR expands them to allow them to `put` and `delete` .tflock files.
This PR also implements small linting fixes where appropriate.

Expand native locking permissions

---

terraform/environments/core-logging/logging.tf
terraform/environments/core-logging/r53_logs.tf
terraform/environments/core-vpc/logging.tf

https://github.com/ministryofjustice/modernisation-platform/issues/7474
Having already enabled r53 DNS firewall for all MP VPCs in https://github.com/ministryofjustice/modernisation-platform/pull/8917 , I had to rollback the query logging/monitoring config as in https://github.com/ministryofjustice/modernisation-platform/pull/9041 as it conflicted with the existing logging setup in `core-logging`.
In this PR I have done two things:
1. Associated all dev/test/preprod VPCs with the cloudwatch r53 query logging config (shared from `core-logging`) so that we can capture when the r53 dns firewall captures traffic in the logs.
2. In `core-logging` I've created a Cloudwatch metric filter/alarm so any matching domains that the firewall acts on triggers a dedicated SNS topic which is hooked into …

Associate non-prod VPCs with cloudwatch rqlc-only and r53 dns firewall monitoring

---

environments/sprinkler.json
scripts/git-create-environments.sh

This PR fixes an issue identified in issue  https://github.com/ministryofjustice/modernisation-platform/issues/8623 by amending the GitHub create environment script to filter out teams that begin with `azure-aws-sso-*`
script now shows `azure-aws-sso-*` teams being skipped.
rather than trying to process the team as a GitHub team:

Update script to filter Azure Teams from GitHub

---

source/runbooks/terraform.html.md.erb
source/user-guide/running-terraform-plan-locally.html.md.erb

#8345 
Updates documentation to reflect that there's no need to assume a backend role for state locking through DynamoDB
Tested through peer review of PR

Update docs now that state files are stored natively in S3

---

terraform/pagerduty/member-services-integrations.tf

Adding a pager duty service for alerting for EMD
Adds the service
n/a
n/a

Add PagerDuty service and Slack connection for electronic monitoring data alarms

---

terraform/modernisation-platform-account/s3.tf

#8345
Permissions for Developer wishing to run local plans were not sufficient
Manually amended bucket policy, tested access with developer credentials

Allow developers to manipulate Terraform state locks

---

environments/example.json

[#8739](https://github.com/ministryofjustice/modernisation-platform/issues/8739) - Example account will be used for GreenOps PoC, as a result 
- it needs to be temporarily removed from nuke
- Julien Nioche will need access to the account so a new GitHub group has been created (green-ops) to allow him to access the account as opposed to his whole team.
See above
See unit tests below.

feature#8739-excluding example account from nuke & adding green-ops sso

---

environments/laa-stabilisation-cdc-poc.json

Simple change to update the OIDC role for deployments to AWS after the repo name was changed. PoC environment for CDC replacement.

Update repo name in OIDC role

---

.github/workflows/new-environment.yml
scripts/provision-member-component-workspaces.sh
scripts/provision-member-directories.sh
terraform/templates/modernisation-platform-environments-components/platform_backend.tf
terraform/templates/modernisation-platform-environments-components/platform_base_variables.tf
terraform/templates/modernisation-platform-environments-components/platform_data.tf
terraform/templates/modernisation-platform-environments-components/platform_locals.tf
terraform/templates/modernisation-platform-environments-components/platform_providers.tf
terraform/templates/modernisation-platform-environments-components/platform_secrets.tf
terraform/templates/modernisation-platform-environments-components/versions.tf

The current structure of the Modernisation Platform Environments makes it challenging for multiple teams to collaborate within a single account. The common workaround—requesting a new account—is not always practical, especially for larger projects that require multiple teams working concurrently.
https://github.com/ministryofjustice/analytical-platform/issues/6602
This PR introduces a component-based subfolder structure within the application folder
- Work on different components in their own isolated directories.
- Reduce the need for requesting additional accounts.
- Improve maintainability and scalability of projects.
This change enhances collaboration within the Modernisation Platform Environments, making it easier for larger teams to contribute without conflicts.
Tested all the …

Introduce Component-Based Subfolder Structure in Modernisation Platform Environments

---

terraform/environments/bootstrap/member-bootstrap/iam.tf
terraform/environments/bootstrap/single-sign-on/policies.tf

#8345
Found and removed some further references to the old state access role

removed some legacy referencing to the old state access role

---

.github/workflows/templates/workflow-template.yml

Updated the template workflow to incorporate reusable workflows that support both component-based and non-component environments. This change eliminates the need for maintaining two separate workflow versions, simplifying workflow management and ensuring consistency across environments. With this update, the workflow dynamically adapts based on whether components exist, reducing duplication and making future maintenance easier. The template is used in the environments repo when creating accounts, ensuring that all newly created accounts follow a unified and scalable workflow structure.

Update template workflow to support components in environments

---

environments/sprinkler.json

This PR is for testing MPE components.
Added two new components: `playground` and `testbed` to the JSON configuration. This change will create two subfolders in the environments repo, each containing separate configuration and state files for the components.
This change ensures that `playground` and `testbed` components can be deployed into the same account, but their code and configurations are managed independently. By isolating their configurations and state files into separate subfolders, we avoid potential conflicts and make it easier to maintain and update each component individually.
{Please write …

Add components to the JSON configuration

---

.github/ISSUE_TEMPLATE/new-component.yml
.github/workflows/templates/workflow-template.yml
terraform/templates/modernisation-platform-environments-components/platform_backend.tf

The current destroy process in the workflow template removes all resources within the application, including both the root folder and individual components. This broad behavior increases the risk of unintentionally destroying critical infrastructure.
By adding the `component` input with a default value of `root`, this template update ensures that the destroy process is controlled and predictable:
- **Default behavior:** Only the root folder will be destroyed if no component is specified.
- **Custom behavior:** Specific components can be targeted for destruction when explicitly provided.
And Adds a new template for requesting the creation of components in member applications
Will this …

Add new component request template and update destroy process to target specific components or root by default

---

terraform/pagerduty/aws.tf

As part of the migration of CIS to MP, laa-ops need to set-up CIS pagerduty in MP. I previously merged the CIS pagerduty module but forgot to add the reference to it in the aws.tf file. I have now added this in this PR.
Adding CIS pagerduty to allow alerts for MP

update pd module

---

environments/analytical-platform-common.json
environments/analytical-platform-compute.json
environments/analytical-platform-ingestion.json

Add mwaa-user to common
Sets `codeowners` for members accounts
Adds analytical-platform-airflow as mwaa-user to common accounts
N/A
No
No

🛂 Amendments to Analytical Platform accounts

---

terraform/environments/core-network-services/cidr-ranges.tf
terraform/environments/core-network-services/firewall-rules/development_rules.json

as per slack request https://mojdt.slack.com/archives/C01A7QK5VM1/p1738939223827109?thread_ts=1738939094.061929&cid=C01A7QK5VM1 this PR creates a new firewall allow traffic between Mojo-Azure-Lanading-Zone and LAA Development on port 1521.

New firewall rule for Mojo-Azure-Landing-Zone to LAA Development

---

.devcontainer/devcontainer-lock.json
.devcontainer/devcontainer.json
terraform/single-sign-on/sso-permission-sets.tf

Updates the permissions for the mwaa-user role to cover KMS and Secrets Manager access
- Scopes MWAA access to Analytical Platform Compute
- Gives access to KMS CMK MRK and Secrets Managed in Analytical Platform Data Production
mwaa-user was an experimental role for something that never took off in Analytical Platform, this pull request reuses it for our new Airflow service
It hasn't been tested, but the changes are additions
No, only Analytical Platform use this role
Adds a dev container to mirror modernisation-platform-environments

🛂 Update mwaa-user permissions

---

terraform/environments/bootstrap/single-sign-on/policies.tf

as part of an ask channel request here
Matt Heery
12:21
hellooo - can someone start [this glue crawler](https://396913731313-hio47vvi.eu-west-2.console.aws.amazon.com/glue/home?region=eu-west-2#/v2/data-catalog/crawlers/view/historic_api_mart_crawler) (in electronic monitoring data test, called historic_api_mart_crawler) for me? its a one off job so sorry but need it done :sweat_smile:
i have found that not even us as administrators can start a crwaler job 
this PR adds in the missing permission to run a crawaler job from the console

extra permissions need to be able to run a crawler job

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

User request: https://mojdt.slack.com/archives/C01A7QK5VM1/p1739446680635549?thread_ts=1739380874.018489&cid=C01A7QK5VM1
This should fix the error experiences by the customer: https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/13306577923/job/37159407352#step:9:21
Deployment to Sprinkler prior to rolling out to all member accounts
see above

Adding ram:AssociateResourceShare to the MemberInfrastructureAccess role

---

.github/workflows/reusable-signed-commit.yml

Removing GitHub token as GitHub automatically provides secrets.GITHUB_TOKEN, so defining it inside the workflow_call is causing an error.

remove secret from reusable-signed-commit.yml

---

terraform/environments/bootstrap/secure-baselines/main.tf
terraform/modernisation-platform-account/baselines.tf

https://github.com/ministryofjustice/modernisation-platform/issues/9207
Bumps baselines to `v7.12.0` which introduces the following changes:
- It adds a local to conditionally filter on MP-owned accounts so that we only subscribe to alerts for MP-owned accounts for the unauthorised-api-calls alarm
- It adds the account alias to the name of all the metric filters so that these will feature prominently in the slack alerts making it easier to identify the affected account at a glance
Tested against sprinkler locally

Bump baselines to `v7.12.0`

---

terraform/environments/bootstrap/secure-baselines/main.tf
terraform/modernisation-platform-account/baselines.tf

https://github.com/ministryofjustice/modernisation-platform/issues/9207
`v7.12.0` rollout failed https://github.com/ministryofjustice/modernisation-platform/actions/runs/13367813632
If there is no account alias set you get the error...
```
Error: reading IAM Account Alias: empty result
with module.baselines.data.aws_iam_account_alias.current
```
Bumps baselines to `v7.12.2` which uses a workspace call to get the account name with a tweak in there for the MP account which uses `default` workspace.

Bump baselines to `v7.12.2`

---

terraform/environments/core-network-services/versions.tf
terraform/environments/core-vpc/8854-migrations.tf
terraform/environments/core-vpc/transit-gateway-attachment.tf
terraform/environments/core-vpc/versions.tf
terraform/environments/core-vpc/vpc.tf

#8874 
Bumps module version, implements a `migrations.tf` to move the transit gateway attachments and route table associations across to the new code preventing their destruction/recreation.
`aws_ec2_tag` resources have not been included in the scope of this PR. They _could_ be, but would require ~750 additional lines in `migrations.tf`.
Tested with local plans against `sandbox` and `development`.
On approval of this PR, will run with local `apply` against `sandbox` prior to completing the PR.

Transit gateway circular dependency

---

environments/analytical-platform-ingestion.json

This has been created off of the back of [this](https://github.com/ministryofjustice/analytical-platform/issues/5175) issue.
That being said, that issue is large and the reason for this PR is to allow AP engineers to act as Administrators in the Analytical Platform Ingestion accounts.
Provides `platform-engineer-admin` access.
Adopted elsewhere.
No
NA

:wrench: Update engineer access in `analytical-platform-ingestion` accounts

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

We'd like to create a GitHub workflow to manage SES suppression lists in the `delius-jitbit` accounts. The Jitbit devs need to be able to remove emails that have been incorrectly added. Currently, the role used lacks the required permissions.
```
An error occurred (AccessDeniedException) when calling the DeleteSuppressedDestination operation: User: arn:aws:sts::142262177450:assumed-role/modernisation-platform-oidc-cicd/hmpps-cr-ancillary-jitbit-app-2 is not authorized to perform: ses:DeleteSuppressedDestination on resource: * because no identity-based policy allows the ses:DeleteSuppressedDestination action
```
Adds required SES permissions to the OIDC role.
Will this deployment impact the …

chore: add ses suppression list actions to oidc role

---

environments/analytical-platform-ingestion.json

Platform Engineer Admin does not contain
Adds developer and sandbox access back for Analytical Platform Engineering
No
No, its additive

⏪ Revert removal of developer and sandbox access for Analytical Platform Ingestion

---

terraform/environments/bootstrap/single-sign-on/policies.tf

This isn't being tracked by an issue. Adding some services to the plat-eng-admin policy
The policy as-is lacks some permissions that are quite needed for a platform engineer, chiefly S3, CloudWatch, SSM and Secrets Manager. Because AP is going to utilise these permissions extensively, and because MP engineers also work with some of the analytical services, also adding Glue and Athena.
Will be tested post-deployment
Nothing specific

Addinb S3, Athena, SSM, Secrets Manager, Glue and CloudWatch to platform-engineer-admin policy

---

terraform/environments/core-shared-services/ad-fixngo.tf

Enable VSS backup capability on AWS Domain Controllers for azure.noms.root domain, currently completing with VSS warnings.
This PR assigns the missing IAM policy to fix the warning.
As tested in other accounts managed by DSO.
Scope is limited to DSO instances.

TM-988: Enable VSS backups for DSO managed DC's

---

environments/analytical-platform-common.json
environments/analytical-platform-compute.json
environments/analytical-platform-ingestion.json

1. All our customers that are included in access config are getting spammed with notifications for environment approval
2. We want Platform Engineer Admin access to our member accounts
1. Sets `github_action_reviewers`
2. Adds `platform-engineer-admin` to all our member accounts
No
If anything, just AP

🛂 Update Analytical Platform's member account environments

---

terraform/environments/core-network-services/cidr-ranges.tf
terraform/environments/core-network-services/firewall-rules/development_rules.json

Allow CICA end user devices access to Tariff Development.
CICA devices require access to Dev Tariff for testing.
Allows inbound to Tariff on specific ports and all outbound.

🛂 Allow CICA devices access to Tariff.

---

terraform/environments/core-network-services/firewall-rules/development_rules.json

This PR corrects the source_ip field in the cica_tariff_dev_to_cica_devices rule by replacing "$${cica-development}" with "${cica-development}". The extra $ was causing incorrect variable resolution.

Fix incorrect variable reference in source_ip

---

source/runbooks/duty-rota.html.md.erb

N/A
TVM SOC no longer distributes information via mailing list as per Mike Cooper's email on the 18th of December 2024
Test through CI pipeline

Update Duty Rota responsibilities

---

environments/ccms-ebs-upgrade.json

#9238 
Enables sandbox access to ccms-ebs-upgrade-test as covered in ticket 9238
Sandbox access to a test account has been confirmed in the above ticket. Note that the nuke: exclude flag is necessary to ensure the account is not wiped.

Enables sandbox access to ccms-ebs-upgrade-test

---

terraform/modernisation-platform-account/secrets.tf

#9232 (This secret is no longer needed)
Removes `slack_webhook_url_modernisation_platform_update` secret

Remove `slack_webhook_url_modernisation_platform_update` secret

---

terraform/modernisation-platform-account/s3.tf

When trying to refresh the state I got
```
│ Error: Error refreshing state: Unable to access object "environments/members/analytical-platform-ingestion/analytical-platform-ingestion-production/terraform.tfstate" in S3 bucket "modernisation-platform-terraform-state": operation error S3: HeadObject, https response error StatusCode: 403, RequestID: TRTAA1RYFJD08N9P, HostID: 71Tg6Idj/mP7QcMnn5pUdDXqEXcpg/0vpW6GA6ltItImyMJpp0rFnoEdlvktuwAHQFs2D3SCNR/n35ybBFDJ7A==, api error Forbidden: Forbidden
```
Adds `s3:GetObject` which resolves `HeadObject` issues
It hasn't, but is based on https://developer.hashicorp.com/terraform/language/backend/s3#permissions-required
No, it's adding permissions
I have also added a new statement with …

🛂 Update Analytical Platform Engineer state access

---

cidr-allocation.md
terraform/environments/core-security/vpc.tf

#9366
Resizes `core-security` VPCs to /20 blocks, releasing ~32 /24 blocks.
Of these we will assign two /22 blocks to YJAF for their vSRX appliances to perform source NAT on traffic into the YJAF environments
Tested with local terraform plan
This will require us to manually remove the existing transit gateway attachments for both `core-security` VPCs and prune them from state. This is preferable to making two PRs to make the attachment resources destroyable and then non-destroyable.

Resize core-security VPCs to release IP address space

---

environments-networks/yjb-preproduction.json
environments-networks/yjb-production.json

This PR fixes an issue where the `additional_private_zones` were incorrectly referenced in the configuration. The zones were mistakenly linked to `preprod.yjaf` and `prod.yjaf` instead of the correct `preproduction.yjaf` and `production.yjaf`. This caused the "no matching Route 53 Hosted Zone found" error when extending DNS zones.
https://github.com/ministryofjustice/modernisation-platform/actions/runs/13652425862/job/38164501844#step:13:26
https://github.com/ministryofjustice/modernisation-platform/actions/runs/13652425857/job/38163878256#step:13:25

Fix incorrect references for additional private zones

---

terraform/modules/vpc-hub/main.tf

#9366 
Adds conditional logic to correctly size transit gateway subnets when the VPC CIDR is a `/20`, without affecting existing `/19` allocations
Tested with local plan. Will also test with CI pipeline checks

Adjusted cidr allocations to handle /20 blocks

---

cidr-allocation.md

#9366
Assigns a block of sufficient size for `youth-justice-networking` to have 8 separate /24 blocks for their networking needs.
N/A - document change only
N/A

Update CIDR block allocations for youth-justice-networking

---

source/concepts/networking/r53-resolver-dns-firewall.html.md.erb
source/index.html.md.erb

https://github.com/ministryofjustice/modernisation-platform/issues/9037
This PR adds a guide to explain the R53 resolver dns firewall configuration applied to MP VPCs

Adds guide to explain r53 resolver dns firewall configuration applied to MP VPCs

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

This PR adds a new OIDC role, github-actions-dev-test, to enable deployment workflows in the development and test environments for the modernisation-platform repository. #8590 
Currently, the terraform-member-environments workflow in the Modernisation Platform (MP) account does not support deploying changes on pull requests. The existing setup (github-action-plan) is limited and does not allow for deployments during the PR process, which is critical for testing and validation in development and test environments.
This new OIDC role, github-actions-dev-test, will allow the terraform-member-environments workflow to deploy changes on pull requests in the development and test environments.
Will …

Add new OIDC role for GitHub Actions in dev-test environments

---

terraform/environments/bootstrap/delegate-access/iam.tf
terraform/modernisation-platform-account/iam.tf
terraform/modernisation-platform-account/s3.tf

This PR adds the `github-actions-dev-test` role to the cross-account access module and updates the state bucket permissions to allow access for this role. #8590 
- **Cross-Account Access**: Ensures the `github-actions-dev-test` role is trusted only in the appropriate environments, preventing unnecessary access in other environments.
- **State Bucket Permissions**: Enables the `github-actions-dev-test` role to read/write Terraform state files while restricting access to authorized roles within the organization.

Add `github-actions-dev-test` role to cross-account access and state bucket permissions

---

.trivyignore.yaml
terraform/environments/core-shared-services/s3_malware_protection.tf

#8605 
This PR does the following for buckets in core shared services that have S3 malware protection enabled:
- Creates aws_sns_topic.s3_malware_scan_alerts for notifications.
- Links the SNS topic (s3-malware-scan-alerts) to PagerDuty.
- Monitors the InfectedScanCount metric in AWS/GuardDuty
- Triggers an alert when at least 1 malware infection is detected to make sure malware-infected files in S3 are detected immediately in our low priority alarms channel in slack.
AVD-AWS-0095 (HIGH): Topic does not have encryption enabled - added to trivyignore as encrypted topics do not work with pagerduty subscription.
{Please write …

Set up guardduty malware protection alerting 

---

terraform/environments/mi-platform/providers.tf
terraform/environments/mlra/providers.tf
terraform/environments/moj-network-operations-centre/providers.tf
terraform/environments/mojfin/providers.tf
terraform/environments/ncas/providers.tf
terraform/environments/nomis-combined-reporting/providers.tf
terraform/environments/nomis-data-hub/providers.tf
terraform/environments/nomis/providers.tf
terraform/environments/oas/providers.tf
terraform/environments/oasys-national-reporting/providers.tf
terraform/environments/oasys/providers.tf
terraform/environments/observability-platform/providers.tf
terraform/environments/operations-engineering/providers.tf
terraform/environments/opg-lpa-data-store/providers.tf
terraform/environments/panda-cyber-appsec-lab/providers.tf
terraform/environments/performance-hub/providers.tf
terraform/environments/planetfm/providers.tf
terraform/environments/portal/providers.tf
terraform/environments/ppud/providers.tf
terraform/environments/pra-register/providers.tf
terraform/environments/refer-monitor/providers.tf
terraform/environments/tipstaff/providers.tf
terraform/environments/tribunals/providers.tf
terraform/environments/wardship/providers.tf
terraform/environments/xhibit-portal/providers.tf
terraform/environments/youth-justice-app-framework/providers.tf

This work covers the environments that i could not add from the second PR due to the docker instance running out of space
add the default tag to the provider files for the rest of the environments excluding the core accounts 

adding tags to the rest of the environments

---

terraform/environments/bootstrap/delegate-access/iam.tf

This PR adds the `github-actions-dev-test` role to the list of trusted roles that can assume the `ModernisationPlatformAccess` role in the following workspaces:
- `core-vpc-development`
- `core-vpc-test`
- `core-network-services-production`
Recently, new GitHub Actions roles were created for development and test accounts. The `github-actions-dev-test` role needs to assume the `ModernisationPlatformAccess` role in the specified workspaces to perform necessary operations.
#8590
This change ensures that the newly created github-actions-dev-test role can assume the ModernisationPlatformAccess role in the core-vpc-development, core-vpc-test, and core-network-production workspaces. By conditionally applying the additional_trust_policy only to these workspaces
Please describe the tests that you …

Add `github-actions-dev-test` role access to `core-vpc` and `core-network-services` workspaces

---

collaborators.json
terraform/github/modules/team/variables.tf
terraform/github/permissions.tf
terraform/github/teams.tf

#8670
* Ignores teams added at the GitHub Org level
* Removes an unneeded variable from a module now that we don't use `github_team_repository` to manage repo access
* Removes population of unneeded variable
* Resolves some small typographical errors in collaborator GitHub slugs

Further cleanup for `github_repository_collaborators`

---

terraform/environments/bootstrap/secure-baselines/locals.tf
terraform/environments/bootstrap/secure-baselines/main.tf

#9306 
Adds the means to pass a different pagerduty integration key depending on the account type. This is useful for routing securityhub alerts from member accounts to new different slack channel - `modernisation-platform-members-security-hub-alerts`
See tests below. Also ref #9514 for the creation of the pagerduty rules and the new integration key.

#9306 - Adds use of alternate integration key for SecurityHub alerts depending on account type.

---

.github/workflows/terraform-github.yml

#8670
Adds a simple `curl` / `jq` evaluation that will set an exit code to stop the workflow when a query of the GitHub status api returns a result for incidents other than `none`.
Tested locally to evaluate output

Prevent GitHub Terraform from running during periods of degraded GitHub status

---

terraform/environments/bootstrap/secure-baselines/locals.tf

#9306 
Restricts list of mp_owned_workspaces to just the core accounts to move critical SecurityHub alerts from test accounts to the members channel. This will cut down the noise of alerts being generated by unit tests & development work in the main SecurityHub alerts channel.
Amendment of the previous PR https://github.com/ministryofjustice/modernisation-platform/pull/9518
--

#9306 - Redirects the SecurityHub alerts for testing-test, sprinkler, cooker, example to the members slack channel.

---

source/runbooks/adding-collaborators.html.md.erb

#8670
Over two years I don't think we've had a single outside collaborator request access to the ami-builds repository. Also, this updates the process guidance for how collaborators get access to the modernisation-platform-environments repository now that we no longer use the OpsEngineering [github-collaborators](https://github.com/ministryofjustice/github-collaborators) repository.
Test with peer review

updated runbook for collaborator access to repositories

---

terraform/environments/core-network-services/firewall-rules/development_rules.json
terraform/environments/core-network-services/firewall-rules/sets.json

Add rules to allow ingress and egress for CICA Dev. Remove unnecessary rule for on-prem UAT.
Allow connectivity from Tariff to CICA AWS dev account for connectivity to Tempus system.

🛂 Add rules for CICA Dev. Remove CICA on-prem

---

terraform/github/locals.tf

#8670
The GitHub `CODEOWNERS` file can specify teams with the ability to approve PRs, but these teams need corresponding `push` access to a repository in order to approve said PRs.
This PR introduces a simple static list of repositories where we want to map all teams using MP to have access rights to the repositories in the list. This then allows them to approve PRs when the PRs affect paths they're specified in with `CODEOWNERS`.

Allow further repositories to receive full team access

---

source/runbooks/enabling-s3-malware-protection.html.md.erb

#8605 
We've separated the roles to make things clearer and more secure. GuardDutyS3MalwareProtectionRole now handles enabling malware protection, while MemberInfrastructureAccess is only responsible for managing GuardDuty configurations like creation and deletion.

Updates the doc to reference new role created for enabling s3 malware protection

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

https://mojdt.slack.com/archives/C01A7QK5VM1/p1741943875017419
Allows application developer teams to update their own SecurityHub findings.
Tested through CI pipeline deployment to Sprinkler

Allow developers to update SecurityHub findings

---

terraform/environments/core-network-services/cidr-ranges.tf

GlobalProtect CIDR range has been expanded with the move into Prisma after discussion with Ian Norris
Expands GlobalProtect CIDR range to currently assigned address range
Tested with CI pipeline checks 
Deploy through GitHub Actions

Expand GlobalProtect CIDR range

---

.github/workflows/terraform-member-environment.yml

This PR updates the GitHub Actions workflow for Terraform to restrict the `terraform apply` step to only run on the `main` branch for pre-production and production environments. For pull requests, `terraform apply` will not be executed for pre-production or production environments, but the plan step will still run for these environments as well as for development and test environments. #8590 
This PR addresses the issue where Terraform apply was running inappropriately on pull requests for `pre-production` and `production` environments. By introducing conditions that restrict the `terraform apply` to the `main` branch only for these environments, this PR ensures that Terraform changes are only applied to pre-prod and prod when intended, preventing potential errors or unintended …

Restrict Terraform Apply to Main for Preprod and Prod Environments

---

terraform/environments/bootstrap/delegate-access/iam.tf

When running the Member workflow on `sprinkler` and `cooker`, the `github-actions-dev-test` role is failing to assume the `ModernisationPlatformAccess` role. This is because the necessary trust relationships were not defined for these roles in the `core-vpc-sandbox` workspace. #8590 
- Ensures that core-vpc-sandbox has the required roles allowed in its trust policy.
- Allows GitHub Actions and other automated systems to assume the correct IAM roles.

Fix cross-account access for sprinkler and cooker `github-actions-dev-test` roles

---

terraform/environments/core-shared-services/ad-fixngo.tf

Background see https://github.com/ministryofjustice/modernisation-platform/issues/5970
For business objects reporting systems (both nomis and oasys), a promotion management process is used to promote changes from preproduction into production. For example, configuration from preproduction is saved onto multiple file(s)  using a preprod web interface, and subsequently uploaded to production also using a prod web interface.
Putting file shares into the usual member environments won't work for this as the environments are network isolated, and a S3 based solution will be too cumbersome for the end users. A file share which sits alongside the DCs is the proposed solution. This can be mounted by jump servers in both preproduction and production.  A separate files share will be used for dev and …

TM-946: add secrets and SG in prep for HMPP domain file share

---

terraform/environments/core-shared-services/ad-fixngo.tf

Background see https://github.com/ministryofjustice/modernisation-platform/issues/5970
Follow up to https://github.com/ministryofjustice/modernisation-platform/pull/9551
For business objects reporting systems (both nomis and oasys), a promotion management process is used to promote changes from preproduction into production. For example, configuration from preproduction is saved onto multiple file(s) using a preprod web interface, and subsequently uploaded to production also using a prod web interface.
Putting file shares into the usual member environments won't work for this as the environments are network isolated, and a S3 based solution will be too cumbersome for the end users. A file share which sits alongside the DCs is the proposed solution. This can be mounted by jump servers in …

TM-946: add fileshare for devtest azure AD

---

terraform/environments/core-sandbox/providers.tf

as part of Add default tags to terraform providers across the modernisation platform
[#1519](https://github.com/ministryofjustice/modernisation-platform/issues/1519)
Default tags added to core sandbox

Default tags for core sandbox

---

terraform/environments/core-security/providers.tf

As part of Add default tags to terraform providers across the modernisation platform
[#1519](https://github.com/ministryofjustice/modernisation-platform/issues/1519)
Adding default tags to core security account

Adding default tags core security

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

We've separated the roles for enabling s3 malware protection to make things clearer and more secure. GuardDutyS3MalwareProtectionRole now handles enabling malware protection, while MemberInfrastructureAccess is only responsible for managing GuardDuty configurations like creation and deletion.
This PR removes the unnecessary trust policy and iam:PassRole permission, as they are no longer required now that we have a dedicated GuardDutyS3MalwareProtectionRole.

remove trust policy and passrole for MemberInfrastructureAccess role

---

terraform/environments/core-shared-services/ad-fixngo.tf

Background see https://github.com/ministryofjustice/modernisation-platform/issues/5970
Follow up to https://github.com/ministryofjustice/modernisation-platform/pull/9551 and https://github.com/ministryofjustice/modernisation-platform/pull/9553
For business objects reporting systems (both nomis and oasys), a promotion management process is used to promote changes from preproduction into production. For example, configuration from preproduction is saved onto multiple file(s) using a preprod web interface, and subsequently uploaded to production also using a prod web interface.
Putting file shares into the usual member environments won't work for this as the environments are network isolated, and a S3 based solution will be too cumbersome for the end users. A file share which sits alongside …

TM-946: add fileshare for preprod-prod hmpp AD

---

terraform/environments/core-shared-services/ad-fixngo.tf

Previous PR failed https://github.com/ministryofjustice/modernisation-platform/pull/9565
Fixes issue - only uses 2 subnets instead of 3.
Not really possible to test, but was just a mistake in terraform and only new resources are being created.
No

TM-946: azure.hmpp.root fsx fix

---

.github/workflows/new-environment.yml
scripts/json-changes-notifier.py

This PR addresses issues in the notification scripts and updates the secrets action to the latest version. 
- Scripts were failing due to missing or incorrectly accessed environment variables.
- The NoneType error in the email script caused crashes, preventing notifications from being sent.
By using **os.environ.get**, the scripts now safely handle missing environment variables and provide meaningful error messages. The updated module version ensures the scripts work with the latest fixes.
https://github.com/ministryofjustice/modernisation-platform/actions/runs/13921759785/job/38956486284

resolve script errors and Bump secrets action to latest

---

terraform/environments/core-network-services/providers.tf

as part of Add default tags to terraform providers across the modernisation platform
[#1519](https://github.com/ministryofjustice/modernisation-platform/issues/1519) we are adding 
This Pr add the default atgging to the provider files for core network services

core network services tags

---

terraform/environments/core-shared-services/ad-fixngo.tf

The ad-fixngo terraform for HMPP DCs has a warning re role attachments. Noticed this during the recent file share PRs, e.g. https://github.com/ministryofjustice/modernisation-platform/pull/9569
Fixes the attachments
Same change has been made in ec2_instance module without issue
No, since services are not currently in production.

TM-946: ad-fixngo terraform warning fix

---

terraform/environments/bootstrap/member-bootstrap/iam.tf
terraform/environments/bootstrap/single-sign-on/policies.tf

Reverts #9545 and resolves [this Slack request](https://mojdt.slack.com/archives/C01A7QK5VM1/p1742460615254379).
Moves IAM permission to correct policy

Move IAM permission for SecurityHub to correct policy

---

environments/analytical-platform-compute.json

This PR adds the quicksight and lakeformation components to the analytical-platform-compute environment. This is needed so that workspaces can be created.
This has not been tested, but follows instructions set out [here](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/creating-components-for-member-applications.html#overview)

🔧 add components to Analytical Platform Compute

---

.github/workflows/new-member-environment-files.yml

Issue whereby if the org name is omitted from the remote repository name the branch action fails.
Fixes bug whereby the required organisation name was not being passed with the remote repo.

Bug fix for use of signed-commits.

---

source/index.html.md.erb
source/user-guide/how-to-add-default-tags.html.md.erb

As part of Add default tags to terraform providers across the modernisation platform
#1519 i have created some documentation on how this can be added to the provider files in the modernisation platform envrionments repo
Documentation created

documentation on how to add default tags to environments

---

terraform/environments/core-network-services/cidr-ranges.tf
terraform/environments/core-network-services/firewall-rules/development_rules.json

We need to enable connectivity between an AWS DMS service within `analytical-platform-ingestion-development` to a CICA Tariff UAT instance (AWS-UAT6) in order to test the replication of data from Tariff in a non-prod context
This is part of a project to make Tariff data available in the Analytical Platform
It sets `PASS` rules between the CIDR that encompasses `analytical-platform-ingestion-development` to the CIDR encompassing the `AWS-UAT6` instance, on the correct port.
It also allows ICMP traffic to enable `ping`
I lack the permissions to test this change within the Modernisation platform. I have followed precedent as closely as possible.
No
- [?] All checks have passed
- [N/A] I have made corresponding changes to the …

Open firewall from analytical-platform-ingestion-development to Tariff UAT instance

---

terraform/environments/bootstrap/single-sign-on/policies.tf

as part of my investigation into aws detective i need to add some extra permissions for the modernisation engineer role to be able to see graphs in aws detective
adds the required permissions to use graphs in aws detective

Adding extra permissions for egineer role

---

environments/corporate-staff-rostering.json
environments/delius-iaps.json
environments/nomis-data-hub.json
environments/oasys.json
environments/planetfm.json

N/A
Noted that a number of now-live applications still have `sandbox` access, so I reached out to the infrastructure team to confirm that sandbox access was no longer required.
Tested through CI pipeline / peer review

Remove sandbox access from hosting migrations applications

---

environments/dacp.json
environments/ncas.json
environments/pra-register.json
environments/tipstaff.json
environments/wardship.json

Our sandbox role exists for exploratory clickops prior to defining infrastructure fully through code.
Following discussion with @mark-butler-solirius these migrated applications no longer need `sandbox` access. This will have the side effect of removing them from our regular AWS Nuke runs.

Remove Central Digital sandbox access for migrated applications

---

environments-networks/yjb-preproduction.json
environments-networks/yjb-production.json

https://mojdt.slack.com/archives/C01A7QK5VM1/p1742855805300839
YJAF cannot assume the `member-delegation-yjb-preproduction` role as it doesn't have a trust relationship for their preprod account.
Tracing back the way this iam role is populated I found that the accounts had not been added to their respective environment-networks json files.

Add missing YJAF accounts to environment-networks json files

---

terraform/environments/core-shared-services/ecr_repos.tf

#8682 
This adds an ecr repo to hold the SigV4 proxy docker image that will be used by a lambda in the observability-platform accounts to support the use of secure header information when calling a lambda function url.
Image will be built & uploaded to ecr manually so no requirement for push permissions using OIDC.
See https://github.com/awslabs/aws-sigv4-proxy

Issue/8682 - Adds ecr repo to host AWS SigV4 Proxy image.

---

environments/data-platform.json

Adding on the back of the ticket below, https://github.com/ministryofjustice/modernisation-platform/pull/9616 and the below https://mojdt.slack.com/archives/C01A7QK5VM1/p1742981967053399
Im removing the tag for the Data Platform Account to enable them to do emergency maintenance 
PR Removes the tag
Please see test results below

Remove CNI tag from Data Platform App

---

terraform/environments/bootstrap/member-bootstrap/collaborators.tf

YJAF users are requiring redshift-serverless access to restore some snapshots for the migration, see [this](https://mojdt.slack.com/archives/C01A7QK5VM1/p1742915867696489)
This make the role available to collaborators

Add `reporting-operations` role for collaborators

---

.github/workflows/new-environment.yml

This PR removes the unnecessary plan step from the pipeline execution for jobs restricted to run only on the main branch. Since the apply command already includes a plan before applying changes, running a separate plan step is redundant. #9507 
- Reduces pipeline execution time by eliminating an unnecessary step.
- Ensures faster deployments without affecting the correctness of the pipeline.

Optimize pipeline by removing redundant `plan` step

---

README.md

Fix-up - remove cloud-platform from badge URL 
This PR updates the README to use the new GitHub-Community repository-standards badge as per announcement: https://mojdt.slack.com/archives/C05L0KBA7RS/p1742897064793689

Update README to use new GitHub-Community repository-standards badge

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

https://mojdt.slack.com/archives/C01A7QK5VM1/p1743589134311979
Adds `scheduler:*` permissions to MemberInfrastructureAccess role

added EventBridge scheduler permissions to CI role policy

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

OIDC role cannot currently run commands against ECS
Adds permission to OIDC role
Just the github runs
People will be able to run commands against ECS

add ecs commands to oidc role

---

terraform/environments/bootstrap/single-sign-on/policies.tf

https://mojdt.slack.com/archives/C01A7QK5VM1/p1743613015578239
Adds secrets manager permissions to `reporting-operations` role in line with the [aws-managed policy](https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AmazonRedshiftQueryEditorV2FullAccess.html) scope for Redshift Query Editor

Add secrets manager permissions required for Redshift query editor

---

policies/collaborators/collaborators.rego
policies/collaborators/collaborators_test.rego
terraform/environments/bootstrap/member-bootstrap/collaborators.tf
terraform/environments/bootstrap/single-sign-on/main.tf
terraform/environments/bootstrap/single-sign-on/policies.tf
terraform/single-sign-on/outputs.tf
terraform/single-sign-on/sso-permission-sets.tf

#9630 
This change creates a new IAM role and policy that grants users only the necessary permissions to manage EC2 instances via AWS Systems Manager (SSM) Session Manager and are blocked from accessing other AWS services, including Secrets Manager and Parameter Store. It also adds an SSO permission set.
Once the role is deployed, I will test this role on sprinkler

SSM Session Access Role

---

terraform/environments/bootstrap/single-sign-on/policies.tf

https://mojdt.slack.com/archives/C01A7QK5VM1/p1743678382327099
Adds permissions already available to developer role users into sandbox policy

Allow sandbox users to update their securityhub findings

---

.github/workflows/terraform-github.yml
environments/sprinkler.json

This PR aims to facilitate testing of the `ssm-session-access` role deployed to the `Sprinkler` environment. Currently, there's a need to verify the functionality and permissions associated with this role. #9630 
**This PR also improves our GitHub status check to:**
**Probelm**: 
Currently, our [workflows fail](https://github.com/ministryofjustice/modernisation-platform/actions/runs/14243024595/job/39917283083#step:2:11) during GitHub maintenance even when core services are operational
**Fix**
Handle maintenance periods gracefully by accepting both `none` and `maintenance` status indicators
Add more precise component status checks (focusing on Git Operations)
Make our CI pipeline more resilient during GitHub's scheduled maintenance

Add ssm-session-access role to sprinkler

---

source/user-guide/platform-user-roles.html.md.erb

This PR updates the documentation to include a new `SSM Session Access` Role #9630

Add documentation for new `SSM Session Access` Role

---

.github/workflows/new-member-environment-files.yml

Reverts the workflow to the latest version to use unsigned commits due to some files being missed from the commit.
Reverts to the last known working version as used on the 4th March 2025. As the environments repo has not implemented signed commits this will work correctly.
See issue from this action - https://github.com/ministryofjustice/modernisation-platform/actions/runs/14173956354/job/39704169161#step:6:51

Reverts new-member-envrionment-files workflow to last known working version due to issue.

---

scripts/generate-dependabot-file.sh

This PR updates the `genereate-dependabot-file.sh` to include grouping for the GoMod dependencies.

Add Dependabot Grouping

---

terraform/environments/environments.tf

https://github.com/ministryofjustice/modernisation-platform/issues/9527
Bumps the `modernisation-platform-terraform-environments` module to `v7.1.0` to remove `+mp` from new account emails

Bump`modernisation-platform-terraform-environments` module to `v7.1.0`

---

source/concepts/environments/auto-nuke.html.md.erb

#9557 
Updates documentation references to the AWS Nuke tool to reflect the move from the deprecated [rebuy-de/aws-nuke](https://github.com/rebuy-de/aws-nuke) repo to the actively maintained [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).

update aws nuke refs to maintained repo

---

collaborators.json

https://github.com/ministryofjustice/modernisation-platform/actions/runs/14311493150/job/40107423240#step:13:461
Corrects the capitalisation of a collaborator GitHub slug
Test through CI

Fix capitalisation of collaborator github username

---

terraform/environments/core-shared-services/ad-fixngo.tf

(https://dsdmoj.atlassian.net/browse/TM-1154)
Cleans up the patch schedules and moves to v4 of the ssm-patching module.
As tested in hmpps-domain-services account.
This PR cleans up the patch manager patching, which currently isn't working.
This only effects DSO fixngo instances.
The 102 resources destroyed are expected as the module was previously called 6x (6x17 resources)

TM-1154: core-shared-services-fixngo-patching

---

terraform/environments/core-shared-services/ad-fixngo.tf

Removing Definition updates from the OS patch baseline as they should not be subject to the auto-approval setting delay associated with the environment.
Tested in hmpps-domain-services account
This only effects DSO managed fixngo instances.

tm-1154-fixngo-instance-patching-baseline

---

terraform/environments/bootstrap/single-sign-on/policies.tf

There are ec2 instances, especially in hmpps-domain-services that are basically going to be jumpservers that we’d like NOT to be accessible via Fleetmanager’s SSO option… Other RDP options are fine though ’cause we still want RDP via domain credentials to work.
Now, we could probably do that via Group Policy (’cause they’ll be on the domain) but it would potentially be better to have an IAM policy that specifically denies sso-* users access to a few specific EC2 instances.
Need to apply the sso-deny instance-profile-policy tag to something and see if sso login fails but everything else works
See comment ref testing above. I'm not sure how you deploy stuff. 

starting point for additional sso-deny tag/policy

---

environments/delius-alfresco.json

N/A
Noticed that Delius Alfresco had incorrect use of `github_action_reviewers` key.

Fix action reviewers for Delius Alfresco

---

terraform/environments/bootstrap/single-sign-on/policies.tf

Changes to params associated with removing FleetManager SSO based on instance-profile-policy tag
Use different params
Merge it and try again
- Nope - will just remove the tag on the instance if it causes an issu

making a second attempt

---

terraform/environments/bootstrap/member-bootstrap/collaborators.tf

This PR implements the creation of a sandbox IAM role in the preproduction environment. The role is created temporarily to allow for specific access requirements in the `YJAF preproduction` environment. The access will be reverted after the agreed-upon time.
https://mojdt.slack.com/archives/C01A7QK5VM1/p1744625102301059

Temporarily create sandbox role for YJAF preproduction environment

---

terraform/modernisation-platform-account/iam.tf

This PR removes the role assumption permissions from the Plan OIDC role. The Plan OIDC role was previously assuming roles that were unnecessary for its functionality, as it only needs to read the state file and match new resources against the existing ones. This change will help reduce unnecessary permissions and improve security. #9676 
By removing the role assumption permissions, we ensure that the Plan OIDC role no longer has access to assume roles that it does not require. This improves the overall security posture and simplifies the role configuration.
Yes, I have tested this change on several workflows running at the branch level. All workflows executed successfully without any errors related to role assumption or permission issues.  …

Remove unnecessary role assumption permissions from `Plan OIDC` role

---

terraform/environments/bootstrap/single-sign-on/policies.tf

I am having issues creating an AWS GuardDuty Malware Protection Plan as the platform engineer admin user. This PR seeks to resolve this.
Additional permissions
No testing other than this is an addition to a list.
No

:wrench: Update Platform Engineer Additional Policy

---

terraform/modernisation-platform-account/iam.tf

As part of the migration to use AWS Secrets Manager for retrieving secrets in GitHub Actions, we encountered an issue where the existing OIDC role is restricted to a small set of repositories. This restriction prevents other repositories owned by `modernisation-platform` from assuming the role, leading to failures when trying to fetch secrets.
This PR introduces a new **OIDC role** intended specifically for GitHub Actions to retrieve secrets from AWS Secrets Manager. #9804 
This PR resolves the issue by:
- Creating a new, purpose-built OIDC role that is **restricted to Secrets Manager permissions only**
- Updating the trust policy to allow **all repositories owned by `modernisation-platform`** to assume the role via GitHub Actions
- Enabling broader access while maintaining …

Create OIDC Role for GitHub Actions to Access Secrets from Secrets Manager

---

terraform/environments/bootstrap/single-sign-on/policies.tf

User request for additional metrics & dashboard read only permissions for the instance-access and management policies.
Adds some basic cloudwatch metrics & dashboard read-only permissions to instance-access and instance-management policies as requested by Domonic Robinson.

Cloudwatch metric & dashboard read only permissions.

---

environments-networks/yjb-development.json
environments-networks/yjb-preproduction.json
environments-networks/yjb-production.json
environments-networks/yjb-test.json

as part of member request 
Greg Whiting
11:08
Morning, could I please have the following endpoint added to our vpcs for yjaf
under additional_endpoints add "com.amazonaws.eu-west-2.email-smtp"
I believe it is these files under environments-networks in https://github.com/ministryofjustice/modernisation-platform
image.png
image.png
ministryofjustice/modernisation-platform
A place for the core work of the Modernisation Platform • This repository is defined and managed in Terraform
Website
https://user-guide.modernisation-platform.service.justice.gov.uk
Stars
697
Added by https://mojdt.slack.com/services/B08L6LF38E6
Adds the vpc endpoints  to the youth justice vpc's
Will this deployment impact …

VPC endpoints for youth justice

---

terraform/environments/bootstrap/single-sign-on/main.tf

#9726 
Added aws_ssoadmin_account_assignments resource to link the MP Entra ID group to the ModernisationPlatformEngineer & Administrator permission set and assign access to AWS accounts.
Applied in sprinker and I can see permission sets have applied and account assignment can be seen in IAM Identity Center in master account.

Add SSO account assignments for MP Entra ID group

---

terraform/environments/core-network-services/firewall-rules/fqdn_rules.json

Require to be able to send emails related to tasks such as backups from EC2 instance using office365 login on port 587. 
As described in this [issue](https://github.com/ministryofjustice/modernisation-platform/issues/9755).
Adds smtp.office365.com to fqdn rules, to allow sending of emails from the instance.
Would allow other services to use O365 for mails. If required.

🛂 Add smtp.office365.com to fqdn rules

---

terraform/environments/core-logging/athena.tf
terraform/environments/core-logging/cortex.tf
terraform/environments/core-logging/observability.tf
terraform/environments/core-logging/s3_logging.tf

https://github.com/ministryofjustice/modernisation-platform/issues/9571
- Bumps s3 modules in `core-logging` to `v8.2.1` - doing this as dependabot doesn't seem to trigger PRs when pinning to commit SHAs. This included adding `prefix ""` to the lifecycle rules specified.
- Also I've fixed an issue with the athena lambda role which had an inline policy which is deprecated. This now has seperate policy defined and attachment.
- I've also added extra inputs to the `module.s3-bucket-cloudtrail` resource as when updating the module past v8.2.0 some changes meant that the logging bucket was being marked for deletion. This now doesn't show as a deletion in the plan.
- There is still a warning relating to the chatbot module which can be fixed in another PR.
Please describe the tests that you ran …

Bump core-logging s3 modules to `v8.2.1`

---

terraform/modernisation-platform-account/baselines.tf
terraform/modernisation-platform-account/s3.tf

https://github.com/ministryofjustice/modernisation-platform/issues/9571
Updates  s3 modules to `v8.2.1` in modernisation-platform-account and includes `prefix = ""` in the lifecycle rules.
This also updates the baselines module to `v7.13.3` to fix warning RE the config bucket lifecycle rule.

Update s3 modules to `v8.2.1` and baseline module to `v7.13.3` in modernisation-platform-account

---

terraform/modernisation-platform-account/iam.tf

This PR updates the IAM policy to allow GitHub Actions Plan workflows to assume the `ModernisationPlatformAccess` role via `sts:AssumeRole`. It fixes the AccessDenied error encountered during Terraform runs where the role could not be assumed.
https://github.com/ministryofjustice/modernisation-platform/actions/runs/14599333409/job/40953310966?pr=9846#step:9:20

Allow GitHub Actions Plan to Assume `ModernisationPlatformAccess` Role

---

terraform/environments/bootstrap/single-sign-on/policies.tf

https://mojdt.slack.com/archives/C01A7QK5VM1/p1745922438486479
Adds `firehose:*` permissions to sandbox role for clickops exploration

Add firehose permissions to sandbox role

---

environments/analytical-platform-compute.json

This PR adds the following components to the analytical-platform-compute environment. This is needed so that workspaces can be created.
- airflow
- mlflow
- sagemaker-ai
- actions-runner
This has not been tested, but follows instructions set out [here](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/creating-components-for-member-applications.html#overview)

🔧 add new components to Analytical Platform Compute

---

.github/workflows/scheduled-baseline.yml

This PR introduces concurrency control to the GitHub Actions workflow by adding a `concurrency` block. This ensures that multiple workflow runs do not execute simultaneously, which can help avoid race conditions. #8212 
Previously, triggering the workflow multiple times in quick succession could result in runs being cancelled or overlapping. With this change:
- The first run executes normally and is protected from being cancelled.
- Any subsequent runs that are triggered will be queued, awaiting the completion of the first run.
- When a new run is triggered, it does not cancel the previous runs that are queued.
- **However, only the latest queued run will be executed once the current run completes**, and the other queued runs will be skipped.
This ensures that no two workflow runs will …

Add concurrency group to prevent overlapping workflow runs

---

terraform/environments/core-network-services/locals.tf
terraform/environments/core-network-services/moved-rename-pttp-attachment.tf
terraform/environments/core-network-services/transit_gateway_connections.tf
terraform/environments/core-network-services/vpn.tf

The PTTP transit gateway name is no longer accurate
Renames all resources referring to PTTP to reflect the correct name.
Implements `moved {}` blocks for all renamed resources to minimise disruption.

Rename PTTP transit gateway attachment

---

terraform/environments/core-network-services/locals.tf
terraform/environments/core-network-services/moved-rename-pttp-attachment.tf
terraform/environments/core-network-services/transit_gateway_connections.tf

https://github.com/ministryofjustice/modernisation-platform/pull/9892
Solves a chicken-and-egg problem around renaming an attachment.
Tested with local plan. Will recreate some CloudWatch alarms but otherwise nondestructive

Rename pttp attachment again

---

.github/workflows/new-member-environment-files.yml

As per ticket https://github.com/ministryofjustice/modernisation-platform/issues/9700 this PR switches the `New-Memeber-Environmnet-Files` workflow back to using the signed-commit action so further investigation can be carried out.

Switch New-Memeber-Environmnet-Files to signed commit

---

.github/workflows/confirm-contacts-for-environments.yml

Amends how the environment variables are assigned for the notification step.
The template_id and api_key vars were not available to the python script that sends the email notifications. This adds the env variables to the step.
Ran from feature branch successfully.

Fixes issue with env vars not accessible to the python script.

---

environments/delius-core.json

[DST-19341](https://jira.engineering-dev.probation.hmpps.dsd.io/browse/DST-19341) - National Delius database uplift pipeline in Modernisation Platform.
Grants the delius-pdm-uplift-scripts repo access to upload uplift scripts to S3 buckets for use by the deployment pipeline.
N/A
N/A

Grant delius-pdm-uplift-scripts repo access

---

terraform/pagerduty/aws.tf
terraform/pagerduty/policy-schedules.tf
terraform/pagerduty/services.tf

#9831 
Adds new PagerDuty service & slack integration for the handling of high priority alerts that are not to trigger the on-call workflow. I've attempted to follow the existing naming convention.
A further PR will follow later that covers the SNS & cloudwatch changes.

#9831 - Adds new pagerduty resources for routing high priority alerts without on-call workflow.

---

terraform/environments/digital-prison-reporting/iam.tf

The Digital Prison Reporting circleci pipeline is failing with the error:
```
│ Error: updating tags for IAM (Identity & Access Management) Policy (arn:aws:iam::771283872747:policy/dpr-reconciliation-dps-testing2-development-policy): tagging resource (arn:aws:iam::771283872747:policy/dpr-reconciliation-dps-testing2-development-policy): operation error IAM: TagPolicy, https response error StatusCode: 403, RequestID: 4f73ccf2-8f3b-479e-a6e7-02ce576fb54e, api error AccessDenied: User: arn:aws:sts::771283872747:assumed-role/circleci_iam_role/circleci-oidc-session is not authorized to perform: iam:TagPolicy on resource: policy arn:aws:iam::771283872747:policy/dpr-reconciliation-dps-testing2-development-policy because no identity-based policy allows the iam:TagPolicy action
``` …

DPR2-1774: Add iam:TagPolicy to digital-prison-reposrting circleci

---

terraform/modernisation-platform-account/secrets.tf

This PR fixes as SCA warning and also changes the KMS from `secrets-key-multi-region` to `environment-management-multi-region`

Fix SCA warning and update KMS Key

---

terraform/environments/bootstrap/single-sign-on/policies.tf
terraform/single-sign-on/outputs.tf

This PR is tracked upstream by [📋 Add tiros:* to the platform-engineer-admin roles](https://github.com/ministryofjustice/analytical-platform/issues/7642#top)
AWS Tiros is an internal service used by the AWS VPC Reachability Analyzer tool. In order to simplify reachability checks being conducted by platform administrators this IAM permission will allow them to use the reachability tool to pinpoint where traffic flows are failing within an account.

Allow Platform Engineer Admin `tiros:*` IAM permissions

---

environments/youth-justice-app-framework.json

as part of a user request:
've just tried to create an Enterprise Quicksight subscription in account youth-justice-app-framework-development  using authentication method "Use IAM federated identities & QuickSight-managed users" and got error  "Signup request failed because the IAM user does not have ds:CreateIdentityPoolDirectory permission."
Can this permission be provided to the sandbox role? Or should I be using another role?
Quicksight is needed so that we can do a lift-and-shift of our current Quicksite setup.
adding quicksite role to users environment

Adding quicksite to yjaf

---

terraform/environments/bootstrap/secure-baselines/main.tf

#9831 
Updates baselines to 7.13.6 which routes root account usage to high priority alarms channel.
See sprinkler tests below. @connormaglynn successfully demonstrated alerts via use of root account usage in Sprinkler.

Issue/9831 - Sets root account usage alarm to route to high priority slack channel

---

terraform/environments/core-logging/ip_utilisation.tf

https://github.com/ministryofjustice/modernisation-platform/issues/8334
This change adds a daily trigger to the ip usage lambda so that metrics are refreshes on a daily basis and we can subsequently set up alerting based on fresh data.
It could be ran more frequently but as the figures are unlikely to change that quickly I don't feel we need real-time monitoring of this.

add daily trigger to ip usage lambda

---

terraform/environments/bootstrap/member-bootstrap/collaborators.tf

Required for YJAF.
Makes the quickight-admin role available for collaborators.

Quicksight Admin for Collab

---

terraform/environments/core-network-services/locals.tf
terraform/environments/core-network-services/vpn.tf
terraform/environments/core-network-services/vpn_attachments.json

https://github.com/ministryofjustice/modernisation-platform/issues/9624
Adds IKE versions input to the vpn resource and specifies `ikev2` for the YJB VPN tunnels.
Local plans and via the checks in this PR.
I've added a condition that checks the if the IKE versions have been set in the vpn configs in `vpn_attachments.json` and if not it will fall back on a default value that specifies BOTH options i.e. `["ikev1", "ikev2"]`. 
The other VPNs show as changes required but they already show as having default config via the console i.e. both ikev1 and ikev2 enabled. This is being triggered I believe as the versions were being ignored as a lifecycle which I've also had to remove as part of this change. 
As best I can tell this won't have any impact on the existing tunnels.
Will this deployment …

Add IKE versions input and specify ike2 for yjb vpn tunnels

---

terraform/environments/digital-prison-reporting/iam.tf

The Digital Prisons Reporting circleci is failing with the error:
```
│ Error: unable to revoke LakeFormation Permissions (input: &{[DESCRIBE GRANT_WITH_LF_TAG_EXPRESSION ASSOCIATE] 0xc00289dbc0 0xc002315310 <nil> <nil> [DESCRIBE DROP GRANT_WITH_LF_TAG_EXPRESSION ALTER ASSOCIATE] {}}): unable to revoke Lake Formation Permissions: operation error LakeFormation: RevokePermissions, https response error StatusCode: 400, RequestID: 5ed4958a-49b6-4813-846f-a936f38ae1c6, InvalidInputException: No permissions revoked. Revoking Tag permissions on Tags that grantee does not have permissions on.
```
This PR adds the required `lakeformation:RevokePermissions` action to the role.
This fails on pipelines: …

DPR2-849: Add lakeformation:RevokePermissions to reporting circleci role

---

terraform/environments/core-logging/ip_utilisation.tf

This PR adds a cloudwatch metric alarm to monitor ip usage metrics and alert when subnet utilisation is greater than 90%.
It's going to send a notification to the low priority alerts channel for now as I don't see this as a high priority at this point in time. We can always change the destination later if we feel different.
I will manually lower the threshold after this PR is merged to ensure the alerting will work when needed.

Add cloudwatch metric alarm to monitor ip usage metrics

---

terraform/environments/core-logging/cortex_alarms.tf

I tried to create a chatbot config so that we could receive alerts to the low priority alerts slack channel when the ip usage sns topic was in alarm. However a config had already been established for the `core-logging` account when the cortex alarms were configured.
This adds a condition so that the IP usage alerts SNS topic is added to the `modplatform` chatbot config.

Add IP usage alerts SNS topic to chatbot config 

---

terraform/pagerduty/locals.tf
terraform/pagerduty/member-services-integrations.tf

PoC to see if we can use PagerDuty to manage DSO/ProbationHosting/LAAOps concierge rota. Since our current mechanism will break post MS365 migration
Adds DSO team to PagerDuty as a PoC. Putting this here as the pipeline/terraform is already setup for managing PagerDuty, and related PagerDuty services are created here also.
It hasn't. However there's similar code for MP which looks like it works.
No

TM-1218: add DSO pager duty team

---

environments/analytical-platform-common.json
environments/analytical-platform-compute.json
environments/analytical-platform-data-engineering.json
environments/analytical-platform-data.json
environments/analytical-platform-ingestion.json
environments/analytical-platform-landing.json
environments/analytical-platform-management.json
environments/analytical-platform.json

Give `azure-aws-sso-analytical-platform-engineers` access to Analytical Platform accounts
Enables access via Entra ID
It hasn't, but following https://user-guide.modernisation-platform.service.justice.gov.uk/concepts/environments/single-sign-on.html#using-entra-id-for-aws-access-management
No, its additive

🛂 Give Analytical Platform Engineers Entra ID group access

---

terraform/environments/core-network-services/locals.tf

Steve Hobden has asked for the routes to be flipped to match his configuration.
https://github.com/ministryofjustice/modernisation-platform/issues/9624
Routes have been flipped around accordingly.

Flip static route cidrs for YJAF VPN

---

environments/ccms-ebs.json
environments/laa-portal-tactical.json

Creates a component for CrowdStrike resources to be deployed to the referenced accounts, without impacting existing Terraform code.
Deploy as per our runbook guidance [here](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/creating-components-for-member-applications.html#creating-components-for-member-applications).

Add crowdstrike component to ccms-ebs and laa-portal-tactical accounts

---

terraform/pagerduty/member-services-integrations.tf

PoC to see if we can use PagerDuty to manage DSO/ProbationHosting/LAAOps concierge rota. Since our current mechanism will break post MS365 migration
Adds a DSO escalation policy so DSO services are allocated to correct team + to enable notifications
It hasn't. However there's similar code for MP which looks like it works.
No

TM-1218: add DSO pagerduty escalation policy

---

terraform/pagerduty/member-services-integrations.tf

PoC for using PagerDuty to manage DSO concierge rotas.
Adds a restriction for the weekend. Allows manual overrides to be made.
By messing about in PagerDuty UI and getting terraform to match
No

TM-1218: add dso pagerduty restriction

---

.github/workflows/new-environment.yml
terraform/modernisation-platform-account/iam.tf

This PR introduces a new step in the `New environment` workflow to enable a `plan` phase for the single sign-on process. The new step is designed to run only when `.json` files under the `environments/` directory are modified (not for new files). It allows users to pre-review the changes that would be applied to the SSO configuration, without making actual changes to the infrastructure. #9381 
Previously, there was no visibility into potential SSO changes before applying them. This led to reduced confidence and potential misconfigurations. With this plan step:
- The workflow filters only modified JSON files.
- SSO plans are executed per modified account file, allowing a targeted review of changes.
- It does not run on main branch or when triggered manually via workflow_dispatch, ensuring …

Add `SSO Plan` Step for Modified JSON Files Only (Pre-review Before Apply)

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

We need to peer a custom LAA VPC with our existing VPCs, currently this is prevented with an explicit deny.
Removing this to allow it.  2nd PR here https://github.com/ministryofjustice/modernisation-platform-environments/pull/10612 to add this to the plan evaluator.

Remove VPC peering deny

---

terraform/pagerduty/aws.tf
terraform/pagerduty/member-services-integrations.tf

As part of our app migration to dotnet core, we'd like to move away from our current error notification using GOV.UK Notify.
Add a new PagerDuty integration
As yet untested
No

PagerDuty integration for Performance Hub

---

terraform/environments/core-vpc/locals.tf
terraform/environments/core-vpc/vpc-peering.tf

We need to peer the laa-development VPC with the laa-portal-tactical VPC.
This adds a peering acceptor for LAA tactical portal account.
Using aws_vpc_peering_connections so that the data source doesn't fail if there isn't a connection and we can use a count for the acceptor.
TF plans locally

Add VPC peering acceptor for LAA tactical portal

---

.github/workflows/terraform-static-analysis.yml

This PR updates the `terraform-static-analysis.yml` to use the recently pinned `checkov` version here https://github.com/ministryofjustice/modernisation-platform-github-actions/pull/55

Pin Checkov

---

terraform/environments/sprinkler/iam.tf

I'm running some testing for https://github.com/ministryofjustice/modernisation-platform/issues/9882
This PR adds the `modernisation-platform-environments` repo to the sprinkler github actions OIDC role, so that the pipeline no longer fails e.g.
https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/15055734744/job/42321478706#step:6:27

Add mpe repo to sprinkler gh actions OIDC role

---

terraform/environments/core-vpc/vpc-peering.tf

N/A - See [this Slack thread](https://mojdt.slack.com/archives/C08QWK76VQR/p1747396350459819) for context
This PR allows us to set up routes on a per-workspace basis to send return traffic to `laa-portal-tactical` over the VPC peering link.
Tested with a local terraform plan against all environments
Deploy through CI. This PR will add routes to the `laa-general-private` route table in the `core-vpc-development` account, while also making it easy to amend routes in future.
@davidkelliott , @vc13837

LAA `portal-tactical` return routes via VPC Peering

---

terraform/environments/core-shared-services/s3.tf

When users from different AWS accounts or roles upload objects to the S3 bucket, those objects retain ownership and permissions scoped to the uploader's identity. This leads to access failures when other roles or services try to read or manage these objects. #9970 
By disabling ACLs:
1. All uploaded objects are automatically owned by the bucket owner.
2. Ensures consistent permissions and access behavior across accounts.
3. Aligns with AWS best practices for secure and simplified S3 access management.

Disable S3 ACLs to Support Cross-Account Uploads

---

terraform/environments/bootstrap/single-sign-on/policies.tf

https://mojdt.slack.com/archives/C01A7QK5VM1/p1747655966000939
Adds `ssm-guiconnect:*` back to instance mgmt policy

Add `ssm-guiconnect:*` back to instance mgmt policy

---

terraform/github/modules/repository/main.tf

Following the change to enable Security & Analysis on all repo's by default, this PR removes the public/internal repo logic

Enable Security and Analysis

---

terraform/environments/bootstrap/single-sign-on/policies.tf

This PR resolves the issue encountered during cross-account S3 object uploads where the target bucket requires either no ACL or the `bucket-owner-full-control` canned ACL. The source object was previously carrying ACLs that conflicted with the target bucket’s ownership controls. #9970

Fix S3 cross-account upload error by updating permissions and ACL usage

---

source/runbooks/rotating-secrets.html.md.erb

#10003 
All necessary Azure Entra ID credentials for AWS SSO and SCIM integrations are managed using the azure_entraid_oidc and entra_id_aws_connectivity_details secrets. This documentation makes it clear their purpose and eiminates confusion about it's use and makes secret rotation more straightforward. A third secret was adding to the confusion, but have raised a PR to remove it as can be seen here: https://github.com/ministryofjustice/aws-root-account/pull/1232

update doc to include purpose of secrets

---

terraform/environments/core-network-services/route53.tf

This adds the new route53 domain for the LAA's MAAT application and it's production migration. The name was proposed by the LAA Crime Apps team and approved by the COAT team via the domains email group.

Adds the production route53 domain for the maat application.

---

terraform/environments/bootstrap/single-sign-on/policies.tf

Uploading files to the S3 bucket using the AWS Console was failing with an `Access Denied` error when using a CMK from another account. This PR adds the `kms:Decrypt` permission to the IAM role used for uploading objects to S3 with a cross-account customer managed KMS key. #9970

Fix cross-account S3 upload failure by adding `kms:Decrypt` permission

---

.github/workflows/format-code.yml

The sign-commit step is currently failing on this workflow with an of `Argument list too long` This PR updates the action to a version that uses `slurpfile` rather than `argjson` to see if this resolves the issue. 
details of the signed-commit update can be found here https://github.com/ministryofjustice/modernisation-platform-github-actions/pull/59

🧪  Testing new version of signed-commit

---

terraform/environments/core-vpc/monitoring.tf

[#9976](https://github.com/ministryofjustice/modernisation-platform/issues/9976)
PR  standardises CloudWatch metric filter/alarms to use VPCFlowLogs namespace
See tests below

Standardised CloudWatch metric filter/alarms to use VPCFlowLogs namespace

---

terraform/environments/core-shared-services/ecr_repos.tf

This PR updates the `push_principals` and `pull_principals` values for the `soa_admin_ecr_repo` and `soa_managed_ecr_repo` modules to fix the following error:
> InvalidParameterException: Invalid parameter at 'PolicyText' failed to satisfy constraint: 'Principal not found'

Fix ECR repository policy errors for soa-admin and soa-managed

---

terraform/environments/core-shared-services/ecr_repos.tf

This PR removes the `role/modernisation-platform-oidc-cicd` as the role does not exist in the account.

Remove oidc-cicd role from ecr_repo 

---

.github/workflows/monitor-ecs-eks-amis.yml

This PR updates the GitHub Actions workflow to use the `modernisation_platform_account_id` instead of the AWS Organizations `root_account_id` when assuming IAM roles.
Previously, the workflow attempted to assume a role using the root account ID, which is not the correct target. This change ensures the `github-actions-apply` role is assumed in the correct (Modernisation Platform) account.

Use modernisation platform account ID for role assumption

---

terraform/environments/core-vpc/monitoring.tf

[#9976](https://github.com/ministryofjustice/modernisation-platform/issues/9976)
Currently standard deviation of 2 is constantly being breached. Reducing sensitivity to get less false positives.
PR increases SD to 3
Please see below

Adjust Anomaly Detection Band to 3 in CloudWatch Alarms

---

terraform/environments/core-network-services/firewall-rules/development_rules.json
terraform/environments/core-network-services/firewall-rules/test_rules.json

as part of the security update for wire wall rules we need to remove any fire wall rule that uses the any port and not useing a port set this first PR will cover dev and test on LAA
two any rules removed one from dev and one from test

remove overly permissive rules

---

terraform/environments/bootstrap/single-sign-on/policies.tf

Requested here: https://mojdt.slack.com/archives/C01A7QK5VM1/p1748950157969649 
This PR adds permissions for AWS Fault Injection Simulator to the sandbox + developer role.

Add FIS permissions to sandbox+dev role

---

terraform/environments/core-vpc/monitoring.tf

https://github.com/ministryofjustice/modernisation-platform/issues/9976 
Removing Code for SNS, as we are giving the alarms about a month for the AWS AI to get used to the LAA VPC traffic and we dont want to be getting alerts, in the slack channel during this period.
The alarms will be  reviewed in about a month, If the team finds the pilot useful, This PR will be reversed, in this [ticket](https://github.com/orgs/ministryofjustice/projects/17/views/1?pane=issue&itemId=113851569&issue=ministryofjustice%7Cmodernisation-platform%7C10239)
PR
* Removes `alarm_actions` from the following CloudWatch alarms:  
- `accepted_traffic_alarm`  
- `rejected_connections_alarm`  
- `ssh_connection_attempts_alarm`  
* Deletes the KMS key (`aws_kms_key.vpc_flowlog_sns_encryption`) and its alias …

Removing SNS Integration Code for VPC Flow Logs Alarms

---

environments/delius-core.json

Adds sandbox to hmpps-dba role in delius-core as per discussions earlier.
Note that sandbox access already exists for other roles in this account.

Sandbox access for hmpps-dba role in delius-core env.

---

terraform/environments/core-network-services/cidr-ranges.tf
terraform/environments/core-network-services/firewall-rules/preproduction_rules.json

This adds outgoing on tcp 22 from laa public subnets to support the implementation of sftp integration across various laa MP accounts.

Adds outgoing port 22 from laa public subnets.

---

environments/analytical-platform-compute.json

This PR adds the following component to the analytical-platform-compute environment. This is needed so that workspaces can be created.
- dashboard_service
This has not been tested, but follows instructions set out [here](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/creating-components-for-member-applications.html#overview)

Add dashboard_service component to Analytical Platform Compute

---

environments/core-logging.json
environments/core-network-services.json
environments/core-sandbox.json
environments/core-security.json
environments/core-shared-services.json
environments/core-vpc.json
terraform/modernisation-platform-account/secrets.tf

This PR introduces a new secret named `securityhub-slack-channel` which stores Slack channel names as keys and their corresponding webhook URLs as values in a key-value JSON format. #10041 
Currently, there is no centralised way to manage Slack webhook URLs for Security Hub notifications. By storing all Slack channel webhook URLs in a dedicated secret (securityhub-slack-webhooks), the system can easily retrieve and send summary reports to the correct Slack channels. This improves operational efficiency and ensures timely alerting of security findings.

Add secret to store Slack channel webhook URLs for Security Hub notifications

---

.github/workflows/securityhub-findings-notification.yml
scripts/extract-securityhub-severity-summary.sh

This PR introduces a GitHub Actions workflow that sends AWS SecurityHub findings (CRITICAL, HIGH, MEDIUM, LOW) to designated Slack channels per account environment. #10041 
Previously, SecurityHub findings were not being communicated to relevant stakeholders automatically. This workflow ensures that each environment sends its own summarized severity findings directly to its respective Slack channel (if defined), improving visibility, response time, and accountability.

Add Slack Notification Workflow for SecurityHub Severity Summaries

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

This PR removes the existing OIDC roles and identity providers that were manually or previously created in the core accounts except from `core-shared-services`. To avoid conflicts and duplication, these resources need to be cleaned up before migrating to the new Terraform module that will properly manage OIDC providers going forward.

remove existing OIDC roles in core accounts to prepare for new module

---

terraform/environments/bootstrap/single-sign-on/policies.tf

We have data in a bucket that has object tags on it, but cannot manually move it elsewhere when it gets stuck as the `data-engineer` role has insufficient permissions.
This adds the s3:PutObjectTagging permission to the data engineering role.
Not tested, as need permissions to check I am then able to move data.
No, just gives data engineers another iam permission.
n/a

Update policies.tf to give data-engineer PutObjectTagging permissions

---

terraform/environments/core-network-services/firewall-rules/production_rules.json

after Looking through a list of rules i have identified one rule that can be removed which is an icmp rule that allow ping to be done from cloud platform to hampps production that was for testing reasons.
removed the ICMP rule

remove production ICMP rule

---

environments/core-security.json
scripts/internal/export-route53-records.sh
terraform/environments/core-security/s3.tf

This PR moves the final Route53 record inventory upload from the `Modernisation Platform` (MP) to the `core-security-production` account. It also provisions the required S3 bucket and grants the security team read-only access to the data. [#issue](https://github.com/ministryofjustice/modernisation-platform-security/issues/54)

Upload records to core-security bucket and grant security team read-only access 

---

.github/workflows/new-member-environment-files.yml

As per issue https://github.com/ministryofjustice/modernisation-platform/issues/9700 this PR updates the `new-member-environments-files` workflow to use the signed-commits GitHub action.

update new-member-environmnets-files workflow to use signed commits

---

.github/workflows/new-member-environment-files.yml

following errors seen in https://github.com/ministryofjustice/modernisation-platform/actions/runs/15714559840/job/44280937554 this PR updates the script and exports the github token after running the git-setup script in the environments repo.

New Member Environment Files Script Fix

---

terraform/environments/outputs.tf

https://github.com/ministryofjustice/modernisation-platform/issues/10126
These outputs need to be declared so they can be referenced in a subsequent PR where I'm looking to populate the values in aws secrets manager in the mod platform account.

Declare outputs of environments module nuke lists

---

terraform/environments/core-network-services/route53.tf

We need to migrate the legalservices hosted zone from LAA Production to MP so we can decommissoin the LAA Production account.
Creating the records matching in the old hosted zone.  Note these will not become active until the NS record for the domain has been updated.
TF Plan
Records will be compared with the current records before switching Nameservers

Add DNS records for legalservices hostedzone

---

terraform/environments/bootstrap/single-sign-on/policies.tf

I want to view CloudWatch Network Flow Monitor
Gives access to Platform Engineer Admin role
It hasn't been tested, but its additive
No

🛂 Add Network Flow Monitor permissions to Platform Engineer Admin role

---

terraform/environments/core-network-services/cidr-ranges.tf
terraform/environments/core-network-services/firewall-rules/development_rules.json

As per above title, this adds outbound access to SES public endpoint via tcp 587. This is required to allow MAATDB RDS to connect to the SES SMTP endpoint. Note that the general-data subnets already have NACL rules for general outbound access via this port.
This is initially for testing and if successful a follow-up PR will add it for the other LAA VPCs.

Adds tcp 587 outbound for SES public endpoint access from MAATDB RDS.

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

Follows:
- https://github.com/ministryofjustice/modernisation-platform/pull/10477
- https://github.com/ministryofjustice/modernisation-platform/pull/10483
Enables same permissions for CI/CD role
Tested via linked pull requests
No, its additive

🛂 Add Network Monitor permissions to Member Infrastructure Access role

---

source/runbooks/integration-with-protective-monitoring.html.md.erb

This PR updates the XSIAM integration documentation to include AWS Config logs. #912

Add AWS Config logs to XSIAM documentation

---

terraform/environments/digital-prison-reporting/iam.tf

The Digital Prison Reporting circleci pipeline is failing with the error:
```
Error: creating S3 Bucket ... Notification: operation error S3: PutBucketNotificationConfiguration, https response error StatusCode: 403, RequestID: VZSVNG5Q936SPZMN, HostID: ..., api error AccessDenied: User: ...:assumed-role/circleci_iam_role/circleci-oidc-session is not authorized to perform: s3:PutBucketNotification on resource: "..." because no identity-based policy allows the s3:PutBucketNotification action
```
See: https://app.circleci.com/pipelines/github/ministryofjustice/digital-prison-reporting-domains/3113/workflows/145a1467-5c64-4732-9451-d1c3409135fa/jobs/10242
Adds the missing `s3:PutBucketNotification` permission to the digital prison reporting circleci_iam_policy and also adds …

DPR2-1499: Add Put and Get BucketNotification permissions to DPR circleci policy

---

terraform/environments/secrets.tf
terraform/github/repositories.tf

https://github.com/ministryofjustice/modernisation-platform/issues/10126
Removes GitHub secrets from the Mod Platform Environments repo now that all the workflows have been updated to pull their secrets from AWS using the centralised github action.
A couple of GH secrets remain (`MODERNISATION_PLATFORM_ACCOUNT_ID` and `PASSPHRASE`) which are still required to call the secrets github action.
Tested in each of the other workflows that have already been migrated (see ticket for details).

Remove GH secrets for MPE repo

---

terraform/environments/core-network-services/cidr-ranges.tf
terraform/environments/core-network-services/firewall-rules/development_rules.json
terraform/environments/core-network-services/firewall-rules/preproduction_rules.json
terraform/environments/core-network-services/firewall-rules/production_rules.json
terraform/environments/core-network-services/firewall-rules/sets.json
terraform/environments/core-network-services/firewall-rules/test_rules.json

Adds firewall rules for SES SMTP (tcp 587) access from laa general data subnets test, preprod and prod. 
Create a new IP list for the current public IP endpoints for SES SMTP in eu-west-2.
These are required by LAA to access SES SMTP endpoints from MAATDB.
Tested in development.

Adds firewall rules for SES SMTP (tcp 587) access from laa general data subnets test, preprod and prod. 

---

source/concepts/networking/dns.html.md.erb
source/user-guide/certificate-import.html.md.erb
source/user-guide/how-to-configure-dns.html.md.erb

PR to update links to Ops Eng guidance that has moved.
Prevent broken links and ensure guidance can be found.
N/A
No.

Update links to new location of legacy Ops Eng documentation

---

terraform/environments/core-shared-services/s3-laa-shared.tf

As per the title. The LAA FTP Lambdas need this permission to read the ftp client python file.

Adds GetObjectVersion permissions to the laa shared bucket.

---

.github/workflows/update-securityhub-slack-secret.yml

Added `AWS_REGION` env and OIDC permissions (id-token: write, contents: read) to the workflow.

Add AWS_REGION env and OIDC permissions to GitHub Actions workflow

---

environments/laa-ccms-soa.json

Adds OIDC auth between MP env `laa-ccms-soa` and container image build repo `laa-ccms-soa-docker`
Currently no auth exists
No infra currently exists to test

chore: add github auth for laa-ccms-soa docker builds

---

.github/workflows/update-securityhub-slack-secret.yml

This PR improves the security of our GitHub Actions workflow by ensuring that the `slack_webhook_url` input is masked and never printed in the logs. #10302

Securely mask Slack webhook input in GitHub Actions

---

terraform/environments/core-shared-services/ecr_repos.tf

Widens scope of laa-ccms-soa ECR repos to allow `modernisation-platform-oidc-cicd` to pull

chore: widen soa ecr iam further

---

terraform/environments/core-logging/s3_logging.tf

[#10271](https://github.com/ministryofjustice/modernisation-platform/issues/10271)
This PR updates the Kinesis Firehose configuration to set `compression_format = "UNCOMPRESSED"` for the `waf-logs-to-s3` delivery stream. Previously, the logs were being written to S3 in GZIP format, which caused Cortex XSIAM to ingest unreadable binary data when `Log Format = RAW` was selected. By disabling compression, the logs are now written as plain text JSON, enabling proper ingestion and parsing in XSIAM.
PR disables compression

change to uncompress firehose logs

---

terraform/environments/core-network-services/route53.tf

SES validation has broken for the legalservices.gov.uk domain post zone migration
Adds in the required CNAME records

Add legalservices.gov.uk ses validation records

---

terraform/github/versions.tf

https://github.com/ministryofjustice/modernisation-platform/issues/10509
Updates the following TF configs to v6 of the provider:
- `terraform/github` (no changes)
Terraform plan can be seen here (no changes) - https://github.com/ministryofjustice/modernisation-platform/actions/runs/16220612714
no impact expected

Update to v6 aws provider for GitHub

---

terraform/environments/bootstrap/single-sign-on/policies.tf

I am trying to create, list glue connections and zero etl jobs. I can't see them with my DE role as I don't have `glue:DescribeInboundIntegrations` permission.
Adds `glue:Describe*` permissions: https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsglue.html.
n/a
n/a

Update DE policy

---

terraform/environments/bootstrap/member-bootstrap/iam.tf

#10731 
This PR adds Rekognition permissions only to the specified development and production accounts for hmpps-esupervision so only those accounts have access, ensuring other member accounts can't deploy Rekognition resources.

Add Rekognition permission to memberinfrastructureaccess role for hmpps-esupervision

---

terraform/environments/core-logging/s3_logging.tf

- In relation to #10511 
- To align with AWS best practices by using Policies over ACLs https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-server-access-logging.html#grant-log-delivery-permissions-bucket-policy
- Removes bucket ACLs and replaces it with a Bucket Policy
- Will need to test live 🧪 
- Potential to lose some access logs if things go wrong, but access logs are delivered on a [best effort](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerLogs.html#LogDeliveryBestEffort) basis anyways - so robustness is not essential here
NA

♻️ Refactor Cloud Trail S3 Logging Bucket to Use Bucket Policy Instead of ACLs

---

terraform/modernisation-platform-account/baselines.tf
terraform/modernisation-platform-account/iam.tf
terraform/modernisation-platform-account/monitoring.tf
terraform/modernisation-platform-account/observability.tf
terraform/modernisation-platform-account/s3.tf
terraform/modernisation-platform-account/versions.tf
terraform/modules/collaborators/versions.tf
terraform/modules/core-monitoring/versions.tf

https://github.com/ministryofjustice/modernisation-platform/issues/10509
Updates the `modernisation-platform-account` code to be compatible with v6 of the aws terraform provider.
I've also migrated the code away from using the local `core-monitoring` module (as it's just a local module that calls a remote module so seems like an uneccessary extra level of obfuscation). I can remove the `moved` blocks in a follow-up PR.

Update mp account code to v6 aws TF provider

---

.github/workflows/publish-gh-pages.yml
makefile

- Updates to the latest version of the tech-docs-pages-publisher https://github.com/ministryofjustice/tech-docs-github-pages-publisher/releases/tag/v6.0.1
NA
- Tested by running the docs site locally with `make preview` 🧪 
- Only the docs site, but easy enough to roll back if anything goes wrong 😬 
NA

🆙 Update `tech-docs-github-pages-publisher` to `v6.0.1`

---

terraform/environments/digital-prison-reporting/iam.tf

The CircleCI Digital Prison Reporting pipeline is failing as the CirclCI "circleci_iam_role" role does not have permission to list tags for Athena resources.
See the error below:
```
Error: listing tags for Athena Data Catalog (arn:aws:athena:eu-west-2:771283872747:datacatalog/dps_prison_reg): operation error Athena: ListTagsForResource, https response error StatusCode: 400, RequestID: a59782c1-b9d1-44fd-9f80-f2273e677de0, api error AccessDeniedException: You are not authorized to perform: athena:ListTagsForResource on the resource. After your AWS administrator or you have updated your permissions, please try again.
│ 
│   with aws_athena_data_catalog.dps_data_catalog["dps-prison-reg"],
│   on main.tf line 1163, in resource "aws_athena_data_catalog" "dps_data_catalog":
│ 1163: resource …
```

DPR2-1897 add Athena: ListTagsForResource action to allow circleci to return the list of tags

---

.github/workflows/terraform-unlock-state.yml

#10493
This workflow simplifies and automates the state unlock process, reducing manual errors and saving time. It empowers users to unlock state locks by just providing minimal inputs in a consistent format via the GitHub UI.

Add GitHub Actions workflow for automated Terraform state unlock with environment and workspace support

---

terraform/modules/ram-ec2-retagging/versions.tf
terraform/modules/ram-principal-association/versions.tf

https://github.com/ministryofjustice/modernisation-platform/issues/10509
Updates RAM modules to AWS Terraform provider version 6

Update to v6 aws provider

---

.github/workflows/terraform-unlock-state.yml

https://github.com/ministryofjustice/modernisation-platform/actions/runs/16522619124
Error using state unlock job:
```
The selected workspace is currently overridden using the TF_WORKSPACE
environment variable.
To select a new workspace, either update this environment variable or unset
it and then run this command again.
```
Removes the step to sleect workspace as it is already set in a previous step in env vars.

Remove command to select workspace as already set in TF_WORKSPACE env var

---

terraform/templates/modernisation-platform-environments/platform_data.tf

Fix:
```
│ Warning: Deprecated attribute
│ 
│   on platform_data.tf line 46, in data "aws_subnet" "data_subnets_a":
│   46:     "Name" = "${var.networking[0].business-unit}-${local.environment}-${var.networking[0].set}-data-${data.aws_region.current.name}a"
│ 
│ The attribute "name" is deprecated. Refer to the provider documentation for
│ details.
│ 
│ (and 8 more similar warnings elsewhere)
╵
Releasing state lock. This may take a few moments...
exitcode=1
```

Update template for v6 provider

---

README.md
source/user-guide/deploying-your-infrastructure.html.md.erb

Small update to remove reference to legacy GitHub-Actions repo and also add two repo's to our MP readme which appear to be missing:
- modernisation-platform-terraform-dns-certificates
- modernisation-platform-github-oidc-role

Docs Update

---

.github/workflows/format-code.yml

This PR updates the **Format Code** GitHub Actions workflow to **retrieve and use a GitHub token via the** `aws-secrets-management` **reusable workflow**, enabling the signed commit and PR creation steps to complete successfully.
🛠️ **Fixes**
Previously, the `signed-commit` step failed with the error:
> GraphQL: Resource not accessible by integration (createPullRequest)
This occurred because the default `${{ secrets.GITHUB_TOKEN }}` does **not have sufficient permissions** to create pull requests via the GraphQL API used by `signed-commit`.
✅ Solution
- Adds a `fetch-secrets` job using the [aws-secrets-management](https://github.com/ministryofjustice/modernisation-platform-github-actions/blob/main/.github/workflows/aws-secrets-management.yml) reusable workflow.
- Retrieves …

🔐 Fix: Use Secure GitHub Token for Signed Commits and PR Creation

---

terraform/environments/core-network-services/cidr-ranges.tf
terraform/environments/core-network-services/firewall-rules/production_rules.json

LAA ECP Provision
Ensures hosts in LAA Production can initiate TLS connections to Oracle instances
Tested through CI check

Add firewall rule allowing laa prod to ecp

---

terraform/modernisation-platform-account/locals.tf

This is to implement one of the steps from: [{Issue 11168}](https://github.com/ministryofjustice/modernisation-platform/issues/11168)
Add access to the bucket from the management account for the SSO admins.
The role will be used to run tf plan to test this, once it is merged.
on merge

Allow bucket access from the management account for SSO Admins

---

source/runbooks/revoking-user-access.html.md.erb
terraform/environments/youth-justice-app-framework/iam.tf

Addresses issue 56 in mod-platform security repo. to tighten who can assume CircleCI role.
This change improves security by ensuring only authorised CircleCI projects can assume the CircleCI role, reducing the risk of unauthorised access.

Restrict CircleCI IAM role to specific CircleCI projects via trust policy

---

terraform/environments/core-network-services/firewall-rules/test_rules.json

We're migration Delius test DBs from legacy account to MP. Connectivity will be required bidirectionally between these accounts over port 1521/1522.
Creates firewall rules.
N/A
N/A

Allow delius-mp test 1521/1522

---

.github/workflows/new-environment.yml

**Summary**
This PR fixes a bug where environment names were truncated in the Slack notification step of the `environment_json_changes_notification` job. The truncation caused "No such file or directory" errors when filenames like `analytical-platform-compute.json` were processed incorrectly.
**Root cause**
The bug was caused by how the Slack notification step decoded and iterated over modified filenames.
The workflow:
1. Collected changed `environments/*.json` files.
1. Stripped the `environments/` prefix.
1. Base64-encoded the list.
1. Decoded it back in the Slack step.
1. Iterated with:
```bash
for file in $DECODED_FILES; do ...
```
which splits on spaces, tabs, and newlines.
Because base64 output wraps at 76 characters by default, a newline was inserted in the encoded output mid-way …

Fix truncation of environment names in Slack notifications for JSON changes

---

terraform/environments/core-network-services/cidr-ranges.tf
terraform/environments/core-network-services/firewall-rules/production_rules.json

N/A
Allows traffic to the ECP connection test VPC, for reachability testing prior to allowing hosts to reach other destinations on ECP
Tested through CI

Add CIDR range and rule allowing traffic to connection test vpc on 443

---

terraform/environments/core-network-services/transit_gateway_connections.tf

N/A
As a follow-up to https://github.com/ministryofjustice/modernisation-platform/pull/11231, this PR adds a route to the ECP connection test VPC

Add route to ECP connection test VPC

---

terraform/environments/core-network-services/firewall-rules/preproduction_rules.json

Some DSO firewall rules are too wide, e.g. to and from Azure estate. Other DSO firewall rules can be simplified by use of IP sets and port sets. A series of PRs will tighten the existing firewall rules and simplify using IP/port sets. This will make the platform more secure, and the firewall rules will be easier to manage.
Removes preprod rules that have been superceded by portset introduced in https://github.com/ministryofjustice/modernisation-platform/pull/11256
Validated the rules are subset using a python script. Also applying to preprod first.
No

TM-1464: dso firewall rules improvements v5

---

terraform/environments/core-network-services/firewall-rules/production_rules.json

Some DSO firewall rules are too wide, e.g. to and from Azure estate. Other DSO firewall rules can be simplified by use of IP sets and port sets. A series of PRs will tighten the existing firewall rules and simplify using IP/port sets. This will make the platform more secure, and the firewall rules will be easier to manage.
Removes prod rules that have been superceded by portset introduced in https://github.com/ministryofjustice/modernisation-platform/pull/11256
Preprod rules have already been removed by https://github.com/ministryofjustice/modernisation-platform/pull/11258
Validated the rules are subset of existing rules using a python script. Also applied to preprod first.
Will this deployment impact the …

TM-1464: dso firewall improvements v6

---

terraform/modernisation-platform-account/iam.tf

https://github.com/ministryofjustice/modernisation-platform/pull/11266
Dependabot noted a new [release](https://github.com/terraform-aws-modules/terraform-aws-iam/releases/tag/v6.0.0) is available to suppport v6.0
Updates to v6.0 and changes naming conventions etc.

Update collaborators_group module to v6.0

---

terraform/environments/core-network-services/iam.tf
terraform/environments/core-network-services/locals.tf
terraform/environments/core-network-services/vpn.tf
terraform/environments/core-network-services/vpn_attachments.json

https://github.com/ministryofjustice/modernisation-platform/issues/11200
1. Creates a new github oidc role to allow a GitHub actions workflow to carry out VPN maintenance on VPNs with tunnel lifecycle control enabled
1. Adds a `github-environment` tag to VPNS with tunnel lifecycle control enabled using an appropriate GH team
Another PR will generate a GH workflow in the MP Environments repo which will use the OIDC role to...
1. Query the `github-environment` tag of the VPN the user is trying to maintain
1. Pin the maintenance job in the workflow to the relevant github environment …

GH OIDC role for VPN Maintenance

---

.github/workflows/scheduled-baseline.yml

Removed an extra closing parenthesis in the job condition. This fixes the syntax error in the workflow.

Fix workflow condition syntax

---

terraform/environments/core-network-services/iam.tf

This job errored https://github.com/ministryofjustice/modernisation-platform/actions/runs/17318196272/job/49165281553#step:17:1323
due to duplicate role names for the VPN OIDC roles
Updates name tag for new role so that it is unique

Update VPN OIDC role name to make it unique

---

.github/ISSUE_TEMPLATE/new-collaborator.yml
.github/ISSUE_TEMPLATE/new-environment.yml
.github/workflows/secrets-rotation-reminder.yml
scripts/confirm-environment-owner/create-confirm-owner-issue.sh
scripts/iam-monitoring/collaborators-inactivity-monitoring/collaborator_user_deletion_issue.sh

As part of [retro actions](https://mojdt.slack.com/archives/C013RM6MFFW/p1756722813133119) we are experimenting with the creation of a new kanban label and project view to make it easier to identify and track these tasks which are completely independently of the sprint cycle.
Many of the standard tasks which we've agreed are kanban have their issues created by issue template or script. This PR adds the kanban label which will ensure they are highlighted in the project [kanban view](https://github.com/orgs/ministryofjustice/projects/17/views/48) which is still being refined.

Retro experiment - Add kanban label to issues automatically

---

environments/data-platform.json
terraform/modernisation-platform-account/s3.tf

Data Platform accounts are currently unused but we're looking at using them soon
Gives the same level of access as we already have for Analytical Platform 
It hasn't, but its additional
It will only impact Data Platform
Resolves https://github.com/ministryofjustice/data-platform/issues/5

🛂 Gives Data Platform Engineering access to environments and state

---

terraform/environments/bootstrap/single-sign-on/policies.tf

I was applying Lake Formation resource locally with my platform engineer admin role, but was ultimately missing any RAM permissions
Adds them
I added it manually via IAM while completing my tasks, but every so often it will revert when whatever job reconciles policies runs
Its additive, so no

🐏 Add RAM access to Platform Engineer Admin role

---

terraform/environments/core-network-services/firewall-rules/sandbox_rules.json
terraform/environments/core-network-services/locals.tf

Testing network revoke access runbook.. https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/revoke-network-access.html#revoke-network-access-if-required
I'm not sure that we've ever done this before but I believe it should work in theory, I have templated out a new `sandbox_rules.json` file and added default drop and pass rules for http/https between cp and the house-sandbox vpc. 
Also, added new locals so this should be picked up by the deployment.
the aim is to test network connection and then implement the runbook to test an effective block of network acces to MP.

Allow access between cp and house-sandbox vpc on mp 

---

terraform/environments/core-logging/s3_logging.tf

Receiving an Access Denied error for the PutObject opertion since remoivng the `module.s3-bucket-cloudtrail.bucket.arn` resource in the IAM Policy
Adds `module.s3-bucket-cloudtrail.bucket.arn` back into the IAM Policy
NA
Minimal, logs are retried fairly often if anything goes wrong
NA

🔧 Fix IAM Policy for CloudTrail Central Log Bucket

---

terraform/environments/core-network-services/firewall-rules/sandbox_rules.json

https://github.com/ministryofjustice/modernisation-platform/issues/11460
I'm testing in sandboxes to avoid intefering with real apps. This PR adds a firewall rule to allow https between the garden and house sandbox VPCs so I can test the revoking network access runbook.

Test network access between the sandboxes

---

source/runbooks/revoke-network-access.html.md.erb

https://github.com/ministryofjustice/modernisation-platform/issues/11460
- Having tested the existing runbook I have made a major update to this documentation to improve accuracy and hopefully make it easier to understand.
- I've tried to add more context on why/when you may wish to take each action but also noted that the business process needs more refinement in this area
- I've removed the final two sections which were focused on conatining access to the core MP environments as the actions made no sense and the scenarios need more thought - I will raise a ticket for that.
Runbook was tested in multiple environments all documented [here](https://justiceuk.sharepoint.com/:w:/r/sites/msteams_480621/_layouts/15/Do …

Major update to revoke network access runbook

---

environments/delius-core.json

Add delius test access for hmpps-community-payback
Gives delius test access to hmpps-community-payback devs to allow them to analyse the data.

Add delius test access for hmpps-community-payback

---

terraform/pagerduty/locals.tf

I need a little more Slack access to set up ECP PagerDuty integrations with Slack
Sets my role to manager for Slack Connection Management as noted [here](https://support.pagerduty.com/main/docs/slack-integration-guide#:~:text=Slack%20Connection%20Management%3A).
Test through CI pipeline

Bump David's permissions so he can do more in PagerDuty with ECP

---

terraform/pagerduty/policy-schedules.tf

Dave and David are now part of the ECP on-call rota and there will be time when their ECP schedules clash with MP schedules. This is to update the on-call schedule in Pager Duty for the Modernisation Platform to remove Dave and David from the rota.
This was agreed between the teams and discussed within the MP team.
See thread for further details on the changes implementation: https://mojdt.slack.com/archives/C013RM6MFFW/p1758809588520189

Removing Dave and David from the PD rota

---

environments/hmcts-claude-provider.json

Adds linusnorton as additional reviewer
Linus doesn't have access to review deployments, discussed here https://mojdt.slack.com/archives/C01A7QK5VM1/p1759156969485449?thread_ts=1759155286.388579&cid=C01A7QK5VM1
Added `linusnorton` as additional reviewer

Add additional reviewer to hmcts-claude-provider.json

---

terraform/environments/core-network-services/logging.tf

https://github.com/ministryofjustice/modernisation-platform/actions/runs/18223102990
My PR failed again
The issue was the name of the cw log group could not be added dynamically in the kms key policy so teh name has to be hardcoded for TF to be able to create it.
This is fixed now and deployed it locally. I'm pushing this PR to get the code into main.

Fix log group name and update KMS encryption context for public DNS query logging

---

terraform/environments/core-network-services/firewall-rules/fqdn_rules.json
terraform/modules/firewall-policy/main.tf

Traffic from the LAA VPC (`172.20.0.0/16`) to Cloud Platform services was being dropped, despite the destination being included in the FQDN allowlist. Investigation showed that the FQDN rule group wasn’t being applied to these flows because the LAA CIDR was not listed in `fw_home_net_ips`. As a result, the traffic bypassed FQDN inspection and was caught by default layer-4 drop rules.
Additionally, the firewall policy was configured with `stateless_fragment_default_actions = ["aws:drop"]`, which caused fragmented packets to be dropped before reaching the stateful engine for FQDN evaluation.
Added `172.20.0.0/16` to the `fw_home_net_ips` list so FQDN rules apply to flows sourced from the LAA VPC.  
- Updated firewall policy to set `stateless_fragment_default_actions = …

bug fix for firewall rules

---

.github/workflows/secrets-rotation-reminder.yml
scripts/iam-monitoring/collaborators-inactivity-monitoring/collaborator_user_deletion_issue.sh

Correct label formatting in the issue creation commands for secrets rotation and collaborator deletion workflows.
The list of labels is comma seperated and included a whitespace which was being read as part of the label name.

Fix label formatting in issue creation for workflows

---

architecture-decision-record/README.md

Correct a typo in the architecture decision log ReadMe which caused [this job](https://github.com/ministryofjustice/modernisation-platform/actions/runs/18304885936) to fail.

Fix typo in architecture decision log

---

environments-networks/laa-test.json
terraform/environments/core-network-services/firewall-rules/test_rules.json

enterprise service bus lambda functions need connectivity to ECP
allows name resolution and passage through inspection firewall

Add rules and association to allow laa-test to ecp

---

terraform/environments/core-logging/logs_r53_public_dns_firehose.tf
terraform/environments/core-logging/providers.tf
terraform/environments/core-network-services/logging.tf

https://github.com/ministryofjustice/modernisation-platform/issues/11061
This pull request updates the AWS provider configuration and resource definitions to ensure that Route 53 public DNS query logging and related resources are correctly provisioned in the `us-east-1` region, which is required for Route 53 public DNS logging. It also introduces new IAM roles and policies to support forwarding CloudWatch logs to a centralized logging account.
The most important changes are:
**Provider Configuration and Regionalization:**
* Added a dedicated AWS provider with alias `aws-us-east-1` for the `us-east-1` region, including role assumption and tagging, to support resources that must reside in that region. (`providers.tf`)
* Updated `aws_iam_role`, `aws_iam_role_policy`, and …

Add cloudwatch log subscription filter for r53 public DNS logs

---

terraform/environments/core-logging/logs_r53_public_dns_cloudwatch.tf

https://github.com/ministryofjustice/modernisation-platform/issues/11061
I'm rebuilding the cloudwatch logs destination resources in `us-east-1` as the firehose lives in that region and they need to be in the same region to link up.

🔧  Build CW Log Destination in `us-east-1`
